### ISSUE TITLE
(aws-lambda-event-sources): `S3EventSource` should take `IBucket` instead of `Bucket`

### ISSUE THREAD

**Issue by guangyuzh** [aws/aws-cdk#4323] opened 2019-10-01 18:40 UTC
### Reproduction Steps

Cannot import an existing s3 bucket when creating Lambda s3 events:
1. `aws_s3.Bucket.from_bucket_name(...)` or `aws_s3.Bucket.from_bucket_arn(...)`, etc. returns `aws_s3.IBucket` type
1. However, `aws_lambda_event_sources.S3EventSource` only takes `aws_s3.Bucket` type as a parameter
1. Note: `aws_s3.Bucket` implements `aws_s3.IBucket`

### Error Log

```
File "/usr/local/lib/python3.6/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aws_cdk/aws_lambda_event_sources/__init__.py", line 199, in __init__
    jsii.create(S3EventSource, self, [bucket, props])
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 208, in create
    overrides=overrides,
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 331, in create
    return self._process.send(request, CreateResponse)
  File "/usr/local/lib/python3.6/site-packages/jsii/_kernel/providers/process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Object of type @aws-cdk/aws-s3.IBucket is not convertible to @aws-cdk/aws-s3.Bucket
```

### Environment

  - **CLI Version      :** v1.10.1
  - **Framework Version:** v1.10.1
  - **OS               :** Mac OS
  - **Language         :** Python

### Other

`aws_lambda_event_sources.S3EventSource` should take `aws_s3.IBucket` as a parameter's type.

--- 

This is :bug: Bug Report

**Comment by AjkayAlan** [comment] 2020-03-12 14:15
+1 - This is causing us some pain around unit testing S3EventSource in C#.

**Comment by leantorres73** [comment] 2020-04-29 19:54
+1 - same issue for Typescript

**Comment by TonyFNZ** [comment] 2020-05-06 10:46
The underlying issue here is that CloudFormation can only set the NotificationConfiguration on a S3 Bucket in the CFN template which created the bucket.  This means that if an existing S3 bucket is imported into a CDK stack then it is not possible to update the notification configuration of the bucket, even if the parameter types on `aws_lambda_event_sources.S3EventSource` are changed. 

Please +1 to get this changed in CFN https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/466

**Comment by purnesh** [comment] 2020-05-06 11:45
+1

**Comment by pigna90** [comment] 2020-07-06 12:42
+1

**Comment by iliapolo** [comment] 2020-07-10 12:10
@TonyFNZ Wrote:

> The underlying issue here is that CloudFormation can only set the NotificationConfiguration on a S3 Bucket in the CFN template which created the bucket.

Yes, you can see more details here: https://github.com/aws/aws-cdk/issues/2004

> Please +1 to get this changed in CFN aws-cloudformation/aws-cloudformation-coverage-roadmap#79

Yes, please do that :) (rather that on this cdk issue).

**Comment by iliapolo** [comment] 2020-07-10 12:11
Converting to a feature-request which is somewhat a duplicate of #2004.

**Comment by ireneaguilar-seat** [comment] 2020-10-15 08:05
Any update for this issue?

**Comment by iliapolo** [comment] 2020-10-15 10:05
Pending https://github.com/aws/aws-cdk/issues/2004

**Comment by RZME** [comment] 2021-02-12 22:12
Looking forward to support for this

**Comment by FreeWillaert** [comment] 2021-06-11 08:48
Any news here?

**Comment by iliapolo** [comment] 2021-06-20 14:53
Even though https://github.com/aws/aws-cdk/pull/15158 was merged, we still can't change the type since it constitutes a breaking change. Would need to come up with some additive approach.

**Comment by farshadniayeshpour** [comment] 2021-07-01 14:18
Any updates on this? We still cannot add new notifications to an existing bucket?

**Comment by itharavi** [comment] 2021-07-03 04:15
+1. Facing the same issue in our case too.

**Comment by istvanszabo92** [comment] 2021-07-23 08:55
Similar problem with 1.115.0 (Object of type @aws-cdk/aws-s3.BucketBase is not convertible to @aws-cdk/aws-s3.Bucket)

**Comment by githubkamalanathan** [comment] 2021-08-23 14:58
Any resolutions yet?

**Comment by farshadniayeshpour** [comment] 2021-09-08 14:11
@eladb Unfortunately, this is something that forces me not to use CDK on a monthly basis even though I start writing my app in CDK but then realize we cannot create a lambda event source with an existing bucket. I would really appreciate it if you could resolve this or provide some type of recommendations so I can start working on it.

**Comment by nija-at** [comment] 2021-09-10 13:26
@farshadniayeshpour - have you tried using the bucket notification mechanism in the s3 module - https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-s3#bucket-notifications. This supports setting up notification on imported buckets to invoke a lambda function.

**Comment by LucasOliveiraS** [comment] 2021-09-27 15:21
+1. Facing the same issue.

**Comment by kornicameister** [comment] 2021-09-29 18:57
@nija-at using this module you can't exactly submit to `objectcreated:*`. You can choose one event type like `objectcreated:post` but if you try to submit another notification for, say, multipart it will tell you that you have two notifications with overlapping configuration (prefix, suffix). Perhaps that would be a workaround if there were ability to specify wildcard event? 

Hope I didn't confuse things up ;P

**Comment by ThomasKiec** [comment] 2021-10-04 07:35
@kornicameister Subscribing all object created events is possible. When adding the event notification via `addEventNotification` you can simply use the `EventType.OBJECT_CREATED` (=s3:ObjectCreated:*). 

See [@aws-cdk/aws-s3: EventType interface](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-s3/lib/bucket.ts#L1978-L1986)

A wildcard pattern is probably not useful, since currently only the event types listed [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html) are supported by AWS. Also, the above interface contains all supported event types

**Comment by deepak3082** [comment] 2021-11-19 20:19
Does this fix also work for `lambda.add_event_source(S3EventSource)` . I am still getting an error with the following code block. I have this code in my create-lambda stack and i am on cdk 1.122.0 version.

`myexistingbucket = _s3.Bucket.from_bucket_name(self, 'existingbucket', 'mybucketName')`

```
lambda_trigger.add_event_source(S3EventSource(myexistingbucket,
                                                      events=[_s3.EventType.OBJECT_CREATED],
                                                      filters=[_s3.NotificationKeyFilter(prefix="lambdacode/")]
                                                      )
                                        )
```

**Comment by ericbn** [comment] 2021-11-19 21:15
@deepak3082, not sure about versions after cdk 1.110.0. But up to that version, only `IBucket.add_event_notification` works. And it actually will create the exact CloudFormation structure as expected. You're just defining the event notification from the bucket to the lambda, instead of from the lambda to the bucket.

**Comment by deepak3082** [comment] 2021-11-20 18:19
@ericbn .yes, my use case is to trigger lambda once a file is created/updated in s3 and i can not make any code change in the create-s3-stack. Hence, i want to update the create-lambda-stack code and add the eventsource method per aws cdk docs and I am not able to use IBucket.

**Comment by bchathoth** [comment] 2021-11-24 13:20
+1. Facing same issue with cdk 1.130.0 version

**Comment by Xyz426** [comment] 2021-12-28 02:34
+1, Any update? CDK V2 still doesn't fix the problem

**Comment by alxojy** [comment] 2022-04-12 02:14
any updates on this issue? 3 years later, still not fixed

**Comment by wcheek** [comment] 2022-06-02 07:51
I still get an error when trying to define the event notification on the lambda function, but things work when defining on the bucket as suggested by @ericbn. So although this issue should still be fixed, it's no longer a breaking problem. Simply create an `IBucket` object using its name or `arn` and then `add_event_notification()`

**Comment by luca-ferreri** [comment] 2022-07-14 10:04
In my case the solution of @ericbn proposed [here](https://github.com/aws/aws-cdk/issues/4323#issuecomment-937769403) worked only partially. In facts, with `.add_event_notifications` I got the error 

```python
AttributeError: '_BucketBaseProxy' object has no attribute 'add_event_notfication'
```

while I had no problem with `.add_objcet_created_notification`.

My working snippet follows for reference
```python
bucket = aws_s3.Bucket.from_bucket_name(
    self, id="id-bucket", bucket_name="bucket-name"
)
bucket.add_object_created_notification(
    aws_s3_notifications.LambdaDestination(lambda_fn),
    aws_s3.NotificationKeyFilter(prefix="someprefix/"),
)
```

**Comment by Smikha** [comment] 2022-10-19 05:07
Using ```aws_s3.Bucket.from_bucket_name(self, id='bucket-name', bucket_name="some_bucket_name")```
Causes my lambda stacks to throw the following error:

``` Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (NoSuchBucket) when calling the PutBucketNotificationConfiguration operation: The specified bucket does not exist.```

Alternatively, using ```aws_s3.Bucket.from_bucket_arn(self, id='bucket-name',bucket_arn='some-bucket-arn') works fine. 

Any hope for a fix?

**Comment by kornicameister** [comment] 2022-10-25 01:24
I think from importing by name implies both account and region you are currently deploying to whereas the ARN version allows to explicitly set both of those.

**Comment by lkr2des** [comment] 2023-09-05 21:22
+1

**Closed** 2024-02-08 05:12 UTC
Labels: p1, feature-request, @aws-cdk/aws-s3, effort/small, @aws-cdk/aws-lambda-event-sources, @aws-cdk/aws-s3-notifications
