### ISSUE TITLE
aws-appmesh: ECS Fargate and Virtual Gateway

### ISSUE THREAD

**Issue by RigoIce** [aws/aws-cdk#16405] opened 2021-09-07 16:06 UTC
### The Question
How could we connect a network load balancer from ELB to the Virtual Gateway of App Mesh? 

### Environment

  - **CDK CLI Version:** 1.120.0
  - **Module Version:** 1.120.0
  - **Node.js Version:** 14.16.1
  - **OS:** all
  - **Language (Version):** TypeScript

### Other information
We are about to set up an ECS Fargate cluster alongside App Mesh. For Egress traffic, we head for a virtual gateway in the mesh and want to accompany that gateway with an NLB from Elastic Load Balancing. What we do not understand is how we can bring NLB and virtual gateway together so that the virtual gateway does its job after NLB forwarded the request. Maybe we oversee something but any attempt to set the virtual gateway as a target for the NLB fails. Would be great if someone could shed some light on it.

More specifically, whenever we try to define the virtual gateway as a target to the NLB, we encounter the issue, that 'attachToNetworkTargetGroup' property is missing on the virtual gateway. The same occurs for virtual services. So, we assume that we got something wrong here how the App Mesh is targeted. All tutorials and results found are more related to EKS spinning up automatically an NLB in front of the gateway - but that didn't help for Fargate on plain ECS.  

### Remark
This issue was also posted in the general channel of the CDK Slack workspace and it was advised to be better posted here.

**Comment by rajal-amzn** [comment] 2021-09-07 21:00
@Rigolce Have you taken a look at [this walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-ingress-gateway) It uses NLB and Virtual Gateway with ECS (though the setup is using Cloudformation.) But that should not affect how NLB targets to Virtual Gateway.

**Comment by RigoIce** [comment] 2021-09-08 07:58
@rajal-amzn Thanks for the hint. Indeed we had a look into it but as you may know, CloudFormation templates often do not explain how higher-level constructs in CDK work. So, we saw this walkthrough but it did not explain how we target the virtual gateway from NLB using CDK constructs from App Mesh or ELBv2. For us, there seems to be no relation to connect...

**Comment by rishijatia** [comment] 2021-09-13 17:52
Understood, thank you for the clarification @RigoIce. 

We are currently working on a reproduction of this in CDK and will update this thread as soon as we have an answer for you. Thank you for your patience :)

**Comment by RigoIce** [comment] 2021-09-13 20:09
In the meantime, we figured out how to achieve the App Mesh configuration with ECS and an NLB. It seems that we trapped somehow in some suboptimal documentation. In fact, everything is documented but the connection is not that obvious. We think a CDK walkthrough could help here a lot as this was something we desired to find somewhere as we struggled in the very detail things. That cost unnecessary time. 

Is there a possibility for us to support you or contribute to a walkthrough for this issue taking our experiences into account? We'd be happy to share our knowledge and prevent others from struggling as we did.

**Comment by Seiya6329** [comment] 2021-09-15 18:48
Hi @RigoIce . I am glad to hear you figured out the solution! Thanks for offering to contribute and it is extremely helpful! 

I will try to find if we have any documentations to explain how one can submit a walkthrough.

**Comment by Seiya6329** [comment] 2021-09-15 21:10
Unfortunately we don't have written instructions on writing a walkthrough. It would be great if you could refer existing walkthroughs and replicate the pattern and send us the PR.

---
Since the issue is resolved, I am closing this thread.

**Closed by Seiya6329** 2021-09-15 21:10 UTC
Labels: guidance, response-requested, @aws-cdk/aws-appmesh
