### ISSUE TITLE
(cli): `progress: events` is ignored when running `cdk destroy`

### ISSUE THREAD

**Issue by udondan** [aws/aws-cdk#12235] opened 2020-12-26 11:03 UTC
Having this in your cdk.json:
```json
{
  "progress": "events"
}
```

... disables the progress bar when running `cdk deploy`. This flag though is ignored when running `cdk destroy`. In destroy mode you still get the progress bar.

### Reproduction Steps

`cdk destroy`

### What did you expect to happen?

Show events.

### What actually happened?

Show progress bar.

--- 

This is :bug: Bug Report

**Comment by zackster** [comment] 2021-03-17 23:46
Took a look at this...hypothesizing that the root cause is because the user's `options` aren't being passed into the printer factory.

- in [deploy-stack.ts#L391](https://github.com/aws/aws-cdk/blob/18184df05f5b8478ef9cae1285e45e61a0833822/packages/aws-cdk/lib/api/deploy-stack.ts#L391), the fourth parameter to `withDefaultPrinter`, `options: WithDefaultPrinterProps`, isn't passed in.
  -  this is [invoked through destroyStack](https://github.com/aws/aws-cdk/blob/18184df05f5b8478ef9cae1285e45e61a0833822/packages/aws-cdk/lib/cdk-toolkit.ts#L253)
  - `progress?: StackActivityProgress`; should be part of `export interface DestroyStackOptions`; 
  -  then, `{ progress: options.progress }` should be presented as the fourth parameter 
- This would require adding an integration test to [cli.integtest.js](https://github.com/aws/aws-cdk/blob/18184df05f5b8478ef9cae1285e45e61a0833822/packages/aws-cdk/test/integ/cli/cli.integtest.ts)

**Comment by ryparker** [comment] 2021-06-03 20:15
Hey @udondan 👋🏻 

Thanks for bringing this to our attention. I tried to reproduce this with the latest CDK `v1.107.0 (build 52c4434)` however I did not notice the progress bar appearing on the destroy command. This may have been fixed in a recent package update.

Could you try reproducing this with the latest CDK?

**Comment by peterwoodworth** [comment] 2021-07-08 00:21
Closing this due to staleness - Please ping us if you have additional concerns!

**Closed by peterwoodworth** 2021-07-08 00:21 UTC
Labels: bug, closing-soon, effort/small, good first issue, p1, package/tools
