### ISSUE TITLE
ECS Cluster.addCapacity does not set autoscalingGroup property

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#5893] opened 2020-01-21 18:40 UTC
When calling the ECS Cluster.addCapacity() method it does not actually set the "autoscalingGroup" property as expected:

### Reproduction Steps

```js
    // Create an ECS cluster
    this.cluster = new ecs.Cluster(this, 'Cluster', {
      vpc: this.vpc
    });

    // Add capacity to it
    this.cluster.addCapacity('greeter-capacity', {
      instanceType: new ec2.InstanceType('t3.xlarge'),
      minCapacity: 3,
      maxCapacity: 3
    });

    console.log(this.cluster.autoscalingGroup);
```

### Expectation

According to the docs the expected output from the above code sample would be the construct for the autoscaling group that was created by addCapacity(): https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html#autoscalinggroup

However instead you just see "undefined". This is because the [getter for `autoscalingGroup`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L234) property uses an internal property which is only set in one place in the constructor: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L116

If you do not specify capacity options at constructor time and instead choose to subsequently use the `addCapacity()` method then this property is never set within the [`addAutoscalingGroup()` method](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L182-L228), therefore the reference to the autoscaling group is not retrievable via the getter method as expected

### Workarounds

You can [specify capacity options as part of the constructor](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html#capacity) to get around this issue, instead of using `addCapacity()`. However, we should fix this so that `addCapacity()` sets the property correctly, as expected.

### Environment

  - CLI Version      : 1.21.0
  - Framework Version: 1.21.0

--- 

This is :bug: Bug Report

**Comment by nathanpeck** [comment] 2020-01-27 18:07
Looking into the code for this I think there is a slightly deeper problem. The `addCapacity()` function can be called multiple times, to add multiple ASG's to the cluster. The `autoscalingGroup` property is not an array, so it can only ever point to a single ASG. 

I think design wise we need to create a new property which is a list of the different capacities in the cluster, ideally at the same time that we add support for multiple capacity providers.

**Comment by bf-sodle** [comment] 2020-02-10 18:06
Is it currently possible at all to create an auto-scaling cluster using the CDK or CloudFormation? The following code, in TypeScript CDK 1.23.0, fails to attach the ASG to the cluster. When trying to attach it manually through the UI, I get an error because the ASG doesn't have "instance protection from scale in" enabled. That's required because the default (and desired) behavior is to enable "managed termination protection" on the capacity provider. Neither of these parameters appear to be customizable through CDK or Cfn.

```
    const cluster = new ecs.Cluster(this, `ec2-cluster-${clusterName}`, {
      clusterName,
      vpc: this.vpc,
      containerInsights: enableInsights,
      capacity: {
        instanceType: ec2.InstanceType.of(instanceClass, instanceSize),
        machineImage,
        minCapacity,
        maxCapacity,
        allowAllOutbound: false,
        associatePublicIpAddress: false
      }
    });
    cluster.connections.addSecurityGroup(securityGroup);
    if (cluster.autoscalingGroup) {
      cluster.autoscalingGroup.scaleOnMetric(`${clusterName}-scaler`, {
        metric: cluster.metricCpuReservation(),
        adjustmentType: asg.AdjustmentType.CHANGE_IN_CAPACITY,
        scalingSteps: [
          { change: 1, lower: scaleOutCpuThreshold },
          { change: -1, upper: scaleInCpuThreshold }
        ]
      });
    }
```

**Comment by bf-sodle** [comment] 2020-02-10 19:12
Nevermind, I see how this is working under the hood, and it's not using capacity providers at all. My problem is that my instance wasn't using the ECS-optimized AMI, and therefore couldn't add itself to the cluster.

**Comment by nathanpeck** [comment] 2020-02-11 17:01
@bf-sodle Correct, we are still working on adding full support for ECS capacity providers in CloudFormation. Once that support is in CloudFormation we can add it to CDK as well. You can watch this issue for updates on the CFN work: https://github.com/aws/containers-roadmap/issues/631

**Comment by gandroz** [comment] 2020-07-20 15:11
The `addCapacity` method allows you to add several auto scaling groups, so this getter is irrelevant in this case. It is only fed if you provide the asg to the construct. But I agree it is confusing and useless here. However, you could always access to the asg create with the `addCapacity` method as it is returned to you https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html#add-wbr-capacityid-options 
> This method adds compute capacity to a cluster by creating an AutoScalingGroup with the specified options. 
>
> Returns the AutoScalingGroup so you can add autoscaling settings to it.

**Comment by jgtvares** [comment] 2020-09-15 18:34
My question is not really about the issue, but maybe someone can help.
Is there any difference between using **addCapacity** or **addAutoscalingGroup**?
I know that using **addAutoscalingGroup** I'll need to create an ASG first.
To me it seems that both methods do the same thing.
Am I wrong?

**Comment by gandroz** [comment] 2020-09-15 18:43
> My question is not really about the issue, but is kinda' related.
> Is there any difference between using **addCapacity** or **addAutoscalingGroup**?
> I know that using **addAutoscalingGroup** I'll need to create an ASG first.
> To me it seems that both methods do the same thing.
> Am I wrong?

As far as I understand it, `addAutoscalingGroup` adds an ASG already created to your cluster, whereas `addCapacity` creates an ASG under the hood, attaches it to the cluster and returns it so you can edit it. You have the same behavior when you use the console, you can choose to use an existing ASG or let ECS build one for you.

**Comment by jgtvares** [comment] 2020-09-15 19:34
> > My question is not really about the issue, but is kinda' related.
> > Is there any difference between using **addCapacity** or **addAutoscalingGroup**?
> > I know that using **addAutoscalingGroup** I'll need to create an ASG first.
> > To me it seems that both methods do the same thing.
> > Am I wrong?
> 
> As far as I understand it, `addAutoscalingGroup` adds an ASG already created to your cluster, whereas `addCapacity` creates an ASG under the hood, attaches it to the cluster and returns it so you can edit it. You have the same behavior when you use the console, you can choose to use an existing ASG or let ECS build one for you.

Yeah!
Thanks for answering!

**Comment by avivmag** [comment] 2021-03-16 08:32
Hi guys,

Just to be sure, currently AddCapacity and AddAutoScalingGroup are not working as intended? (not adding the autoScalingGroup to the cluster)
If so and by considering the fact that adding full support for ECS capacity providers is taking its time, will it be possible to add a setter for the private field of _autoscalingGroup (that will be deprecated in the future)?
I'm stuck because AddCapacityOptions method does not support setting the UserData field (so it seems).

Thanks a lot in advance!

**Comment by SoManyHs** [comment] 2021-05-13 01:40
With [ASG Capacity Provider](https://github.com/aws/aws-cdk/pull/14386) support now merged, these methods are now deprecated. Closing.

**Closed by SoManyHs** 2021-05-13 01:40 UTC
Labels: @aws-cdk/aws-ecs, bug, effort/medium, needs-reproduction, p2
