### ISSUE TITLE
(ecs-patterns): ScheduledFargateTask target role does not enough permission to launch the task

### ISSUE THREAD

**Issue by sarbajitdutta** [aws/aws-cdk#16093] opened 2021-08-17 13:47 UTC
## :question: General Issue
ScheduledFargateTask target role(eventsRole) does not enough permission to launch the task. The target task does not have iam:passRole permission to the taskExecutionRole. The default target role only have permission for iam:passRole on only taskdefinitionRole

### The Question

ScheduledFargateTask target role does not enough permission to launch the task. The target task does not have iam:passRole permission to the taskExecutionRole. The default target role only have permission for iam:passRole on only taskdefinitionRole.
The cdk does not expose the eventsRole through software.amazon.awscdk.services.events.Rule to add the policy. For reference on how the scheduledFargateTask is created see here - [CDK-Repo](https://github.com/wcmc-its/ReCiter-CDK/blob/4c039cd6cddde99486d331be2658f85c2a4967f9/src/main/java/edu/wcm/reciter/ReCiterCDKECSStack.java#L780)

### Environment

  - **CDK CLI Version:** 1.117.0
  - **Module Version:** 1.117.0
  - **Node.js Version:** 16
  - **OS:** macOS Sierra
  - **Language (Version):** java8

### Other information

CloudTrail logs when task is launched using the cron expression
```
    "sourceIPAddress": "events.amazonaws.com",
    "userAgent": "events.amazonaws.com",
    "errorCode": "AccessDenied",
    "errorMessage": "User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/ReCiterCdkMasterStack-reC-reCiterMachineLearningAn-xxxxxxxxxxx/xxxxxxxxxxx is not authorized to perform: iam:PassRole on resource: arn:aws:iam::xxxxxxxxxxxxxxx:role/ReCiterCdkMasterStack-reC-reCiterMachineLearningAn-xxxxxxxxxxxxx",
```

**Comment by peterwoodworth** [comment] 2021-09-08 20:28
Closing as duplicate of #16181

**Closed by peterwoodworth** 2021-09-08 20:28 UTC
Labels: guidance, @aws-cdk/aws-ecs-patterns
