### ISSUE TITLE
[@aws-cdk/aws-secretsmanager] ARN is incorrect when getting via fromSecretName 

### ISSUE THREAD

**Issue by arpowers** [aws/aws-cdk#11072] opened 2020-10-23 18:27 UTC
When using `fromSecretName` with secrets manager, it returns a secret but the `arn` property is returned as the name of the secret (used for lookup) not the actual ARN. 

### Reproduction Steps

```js
const theSecret = secretsmanager.Secret.fromSecretName(
      this,
      "TheSecret",
      "my-secret-name",
    )

return [theSecret.secretArn]

// returns  ["my-secret-name"] should be [<the arn of the secret>]
--- 

This is :bug: Bug Report

**Comment by njlynch** [comment] 2020-10-26 10:31
Duplicate of #10519. PR to fix is #11042.

**Closed by njlynch** 2020-10-26 10:31 UTC
Labels: @aws-cdk/aws-secretsmanager, bug, needs-triage
