### ISSUE TITLE
cdk code stopped working since 04/28 version - 1.101.0

### ISSUE THREAD

**Issue by priya238** [aws/aws-cdk#14513] opened 2021-05-03 22:43 UTC
Hi team ,

There was cdk code which was working earlier and stopped working since new version launched for CDK.

The code is to get  and IAM role arn from SSM parameter using below command:

from aws_cdk import (
    aws_stepfunctions as sfn,
    aws_stepfunctions_tasks as sfn_tasks,
    aws_iam as iam,
    aws_ssm as ssm,
    aws_sns as sns,
    aws_events as events,
    aws_events_targets as targets,
    core,
)

test_role_arn = ssm.StringParameter.value_for_string_parameter(self,"Parameter for ARN of IAM role ")

role =iam.Role.from_role_arn(
            self, 'role_id',test_role_arn)

while running cdk deploy its not able to resolve above role and returning  "Error [ValidationError]: Template error: Fn::Select  cannot select nonexistent value at index 5".  Looks like since SSM generates token instead above function stopped working.

Please provide necessary help here.

Can see message -
If the imported Role ARN is a Token (such as a CfnParameter.valueAsString or a Fn.importValue()) *and* the referenced role has a path (like arn:...:role/AdminRoles/Alice), the roleName property will not resolve to the correct value. Instead it will resolve to the first path component. We unfortunately cannot express the correct calculation of the full path name as a CloudFormation expression. In this scenario the Role ARN should be supplied without the path in order to resolve the correct role resource.

**Comment by njlynch** [comment] 2021-05-04 13:07
Duplicate of #14476 -- we are aware of this and are actively working on a fix.

**Closed by njlynch** 2021-05-04 13:07 UTC
