### ISSUE TITLE
ServiceCatalog: Missing ProductStack class in v2

### ISSUE THREAD

**Issue by vahagn-madatyan** [aws/aws-cdk#17895] opened 2021-12-08 00:17 UTC
### What is the problem?

The [ProductStack class ](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_servicecatalog_alpha/ProductStack.html) appears to be missing from CDK v2.0  aws_cdk.aws_servicecatalog_alpha constrcut

### Reproduction Steps

1. Install the alpha library
`install_requires=[
        "aws-cdk-lib",
        "constructs",
        "aws_cdk.aws_servicecatalog_alpha"
]`

2. Import 

`from aws_cdk import  aws_servicecatalog_alpha as service_catalog`

3. Use

`class ACMPCAStack(service_catalog.ProductStack)`

3. Notice error that ProductStack is not included in the package
![image](https://user-images.githubusercontent.com/74753362/145125633-950338e7-ba8d-43b7-a063-3fc172d72a7b.png)

### What did you expect to happen?

Per [documentation](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_servicecatalog_alpha/ProductStack.html), the ProductStack and CloudFormationTemplate.from_product_stack should exist in v2 alpha. They were working fine in v1.X after they were released.

### What actually happened?

The class and the functions are not found under the module.

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Node.js Version

v14.18.0

### OS

MacOS

### Language

Python

### Language Version

3.9.7

**Comment by arcrank** [comment] 2021-12-08 01:42
Thank you for detailed comments, I'm able to reproduce and see that the package has missing features.  Will hope to provide update or resolution soon.

**Comment by skinny85** [comment] 2021-12-08 01:55
Thanks for opening the issue @vahagn-madatyan. Looks like the last release of the `aws-servicecatalog-alpha` package was on October 31 2021, so it doesn't contain the latest changes, including the `ProductStack` class.

We'll dig into what happened there, and report back when we know more!

**Comment by njlynch** [comment] 2021-12-08 10:59
Apologies for the poor experience here.

The most recent release -- as of right now -- is actually [`2.0.0a11`](https://pypi.org/project/aws-cdk.aws-servicecatalog-alpha/2.0.0a11/). There was a mistake with the initial release of the alpha modules that accidentally released with the `rc` suffix instead of the `a` suffix. Unfortunately, that means with out specifying a concrete version, it's selecting the older `rc` releases.

Thankfully, this should be resolved by the next release, where the latest versions will be `2.1.0` and `2.1.0-a1`, respectively. This next release will be out Very Soon.

**Comment by njlynch** [comment] 2021-12-08 14:09
https://pypi.org/project/aws-cdk.aws-servicecatalog-alpha/2.1.0a0/ has been released, which should fix the awkward versioning we had before.

Closing out; let me know if you have any follow-ups.

**Closed by njlynch** 2021-12-08 14:09 UTC
Labels: bug, p1, @aws-cdk/aws-servicecatalog, python
