### ISSUE TITLE
CDK resources defined within Nested Stacks does not show meaningful errors when deploying

### ISSUE THREAD

**Issue by akrsmv** [aws/aws-cdk#7699] opened 2020-04-30 05:31 UTC
I am using dotnet core CDK facade, but I believe bug is reproducible also in typescript.

When using using nested stacks, if there is an error deploying it is not propagated to the aws /stack/events tab, nor it is visible from the cdk cli output.

How I got there - I am using SNS with SQS subscription filters and my team is doing environment per developer. So with 7 stacks and around 30 subscriptions per stack in the same region, we easily reached the 200 subscription filter limit.

However, because all lambda constructs that have their subscription filters defined, are in a nested stack error was not visible.

It was only visible when I moved the constructs into the main stack and redeployed again. Then I saw the meaningful error.

### Reproduction Steps

create more than 200 queues subscribed to an SNS topics (not necessary the same SNS topic) with subscription filters. 

- Define them in a Stack --> you see a meaningful error:

filter policy quota exceeded (Service: AmazonSNS; Status Code: 403; Error Code: FilterPolicyLimitExceeded

- Define them in a NestedStack --> you only see errors of the form:

The following resource(s) failed to create: [OperationsNestedStackOperationsNestedStackResource956E95E5,
and 
Embedded stack arn:aws:cloudformation:eu-central-1.... failed to create

### Environment
dotnet core cdk libs with cdk cli version 1.31.0 (build 8f3ac79)

This is :bug: Bug Report

**Comment by LanderN** [comment] 2020-04-30 15:18
This is a duplicate of #5974

**Comment by SomayaB** [comment] 2020-05-05 22:37
Closing since it's a duplicate of #5974

**Closed by SomayaB** 2020-05-05 22:37 UTC
Labels: bug, duplicate, in-progress, p2
