### ISSUE TITLE
(aws-lambda): function with alias can generate too long (>140) arn

### ISSUE THREAD

**Issue by mikaelstaldal** [aws/aws-cdk#18795] opened 2022-02-02 15:19 UTC
### What is the problem?

When you create a lambda function with a long id, a version and an alias, you get this error:

```
1 validation error detected: Value 'arn:aws:lambda:us-east-1:603241479242:function:TrcaServiceStack-dev-TrcaLeaderboardReportHandlerd-AggdQu2Fyr5C:TrcaLeaderboardReportHandlerAlias-dev' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 140 (Service: AWSLambda; Status Code: 400; Error Code: ValidationException; Request ID: d1cb4f89-12c7-4bcf-ae5a-c5f0ce20b0c7; Proxy: null)
```

### Reproduction Steps

```
        Function function = Function.Builder.create(this, "TrcaLeaderboardReportHandler-dev")
                .runtime(...)
                .code(...)
                .handler(...)
                .build();

        Version version = Version.Builder.create(this, "TrcaLeaderboardReportHandlerVersion-dev")
                .lambda(function)
                .build();

        return Alias.Builder.create(this, "TrcaLeaderboardReportHandlerAlias-dev")
                .aliasName("TrcaLeaderboardReportHandlerAlias-dev")
                .version(version)
                .build();
```

### What did you expect to happen?

CDK generate an arn not longer than 140 characters.

### What actually happened?

CDK generated an arn longer than 140 characters, which is not allowed, and the creation failed.

### CDK CLI Version

2.8.0 (build 8a5eb49)

### Node.js Version

v16.13.0

### OS

Linux

### Language

Java

### Language Version

11

**Comment by alexandervandekleutab** [comment] 2022-05-17 15:30
I see that there was a PR merged that fixed this. What version of the CDK is needed for this fix? I'm currently on 1.144.0 for all of my resources, and we are planning to move to 2.x in the near future.

**Comment by Borduhh** [comment] 2022-09-30 14:52
Any updates on this? We are having this issue while trying to use provisioned concurrency with Lambda.

**Comment by null-reference** [comment] 2022-09-30 19:34
Just started encountering this today. +1 for an update.

**Comment by madeline-k** [comment] 2023-01-28 00:22
@alexandervandekleutab, the PR merged fixed a different, but related issue. I believe this is still an issue.

**Comment by colifran** [comment] 2023-04-24 23:26
I've attempted to replicate this in both Java and TypeScript. It appears that the issue has been resolved - I was able to generate an ARN > 140 characters using the id, version, alias, and stack name provided in the reproduction steps. If this is still an issue please let me know and we can re-open this for further work.

**Comment by daveharig** [comment] 2024-03-23 21:10
@colifran this issue still exists in CDK 2.x typescript.

**Comment by daveharig** [comment] 2024-03-23 21:12
@colifran @madeline-k  this issue still exists in CDK 2.x typescript

**Comment by colifran** [comment] 2024-03-25 18:17
@daveharig I'll reopen this. Thanks for letting us know.

**Comment by daveharig** [comment] 2024-03-25 18:19
@colifran encountering it on CDK 2.133.0 (build dcc1e75)

**Comment by Leo10Gama** [comment] 2024-06-28 22:24
Hi @daveharig! I've tried recreating the issue on the current version (2.147.2 (build f4b0897)) and I'm not getting the error. The generated ARN for the alias is still > 140 characters, but since it's not being used as the function name, it's not giving me an error, and is deploying fine. Could you provide any additional details on how you encountered it so I can reproduce the issue?

**Comment by Leo10Gama** [comment] 2024-07-24 04:34
Closing due to inactivity. If this issue still persists, feel free to open a new one with updated reproduction steps.

**Closed by Leo10Gama** 2024-07-24 04:34 UTC
Labels: bug, p1, @aws-cdk/aws-lambda, effort/small
