### ISSUE TITLE
(aws-iam): PermissionsBoundary is not applied on raw CfnResource(s) representing users or roles

### ISSUE THREAD

**Issue by iliapolo** [aws/aws-cdk#13850] opened 2021-03-29 17:02 UTC
When the `PermissionsBoundary` aspect is applied to a raw `CfnResource` that represents a role, the boundary isn't applied. 

This is actually blocking some legit scenarios in CDK, namely any custom resource implemented by the `custom-resource-provider` in the core package, will suffer from this problem:

https://github.com/aws/aws-cdk/blob/7176a5d5208da7d727bbf5112bc12533983380ea/packages/%40aws-cdk/core/lib/custom-resource-provider/custom-resource-provider.ts#L196-L197

### Reproduction Steps

```ts
const role = new cdk.CfnResource(this, 'Role', {
  type: 'AWS::IAM::Role',
  properties: {
    AssumeRolePolicyDocument: {
      Version: '2012-10-17',
      Statement: [{
        Action: 'sts:AssumeRole',
        Effect: 'Allow',
        Principal: {
          Service: 'lambda.amazonaws.com'
        }
      }],
    },
  },
});

iam.PermissionsBoundary.of(role).apply(
  iam.ManagedPolicy.fromAwsManagedPolicyName("ManagedPolicy"))
```

Generates the following template:

```json
"Role": {
  "Type": "AWS::IAM::Role",
  "Properties": {
    "AssumeRolePolicyDocument": {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": "lambda.amazonaws.com"
          }
        }
      ]
    }
  },
},
```

### What did you expect to happen?

Expected permission boundaries to be applied to all roles, regardless of what class is used to represent it.

```json
"Role1ABCC5F0": {
  "Type": "AWS::IAM::Role",
  "Properties": {
    "AssumeRolePolicyDocument": {
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": "lambda.amazonaws.com"
          }
        }
      ],
      "Version": "2012-10-17"
    },
    "PermissionsBoundary": {
      "Fn::Join": [
        "",
        [
          "arn:",
          {
            "Ref": "AWS::Partition"
          },
          ":iam::aws:policy/ManagedPolicy"
        ]
      ]
    }
  },
},
```

### What actually happened?

The permission boundary is not applied.

### Environment

  - **CDK CLI Version  : ALL**
  - **Framework Version: ALL**
  - **Node.js Version: ALL** 
  - **OS               : ALL**
  - **Language (Version): ALL** 

### Other

Root cause is:

https://github.com/aws/aws-cdk/blob/7176a5d5208da7d727bbf5112bc12533983380ea/packages/%40aws-cdk/aws-iam/lib/permissions-boundary.ts#L34

Seems like we should be able to do some trickery here and identify that a raw `CfnResource` is actually a `CfnRole`.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-03-30 12:17
Duplicate of #13310

**Closed by rix0rrr** 2021-03-30 12:17 UTC
Labels: @aws-cdk/aws-iam, bug, needs-triage
