### ISSUE TITLE
(aws-cdk-api-reference): allow searching in the ref

### ISSUE THREAD

**Issue by Lewenhaupt** [aws/aws-cdk#17813] opened 2021-12-02 14:11 UTC
### Describe your issue?

We've just started trying to move from cloudformation templates to aws-cdk in our org and it immediately struck me as odd that I cannot search in https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.CfnDBInstance.html ? This makes it much harder to find what a user is looking for unless they know exactly where to look.

Not sure of the technical feasibility of this but I just needed to bring it up at least.

**Comment by jonniedarko** [comment] 2021-12-09 18:45
:+1:  for this

**Comment by peterwoodworth** [comment] 2022-01-06 18:53
Closing as duplicate of https://github.com/aws/aws-cdk/issues/5634

**Closed by peterwoodworth** 2022-01-06 18:53 UTC
Labels: feature-request, @aws-cdk/aws-rds, needs-triage, documentation
