### ISSUE TITLE
(s3-deployment): zip file uploaded to bucket is empty

### ISSUE THREAD

**Issue by fabriciolelis** [aws/aws-cdk#12801] opened 2021-02-01 12:18 UTC
When the zip file is uploaded to S3 bucket, the file is empty. I use this zip file to deploy my application on AWS infrastructure. 

### Reproduction Steps

export interface ScanecosystemUploadDeployFileStackProps extends cdk.StackProps {
	appSourceFromS3: s3.Bucket;
	appDeployFile: string;
} 

export class ScanecosystemUploadDeployFileStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: ScanecosystemUploadDeployFileStackProps) {
	super(scope, id, props);

	const releaseFolder = '../release/';
	const tmpFolder = '../.tmp/';

	if (!fileSystem.existsSync(releaseFolder)){
		fileSystem.mkdirSync(releaseFolder);
	}

	if (!fileSystem.existsSync(tmpFolder)){
		fileSystem.mkdirSync(tmpFolder);
	}

	fileSystem.copySync('../cdk/', tmpFolder + 'cdk',
		{ filter: (path) => { return !(path.indexOf('node_modules') > -1) && !(path.indexOf('cdk.out') > -1)} });

	const output = fileSystem.createWriteStream(releaseFolder + props.appDeployFile);
	const archive = archiver('zip');
	
	archive.pipe(output);
	archive.directory(tmpFolder + 'cdk', 'cdk');
	archive.directory('../app/', 'app');
	archive.finalize();	
	
	new s3deploy.BucketDeployment(this, 'ScanecosystemDeployFile', {
		sources: [s3deploy.Source.asset('../release')],
		destinationBucket: props.appSourceFromS3,
	  });
  }

### What did you expect to happen?
I expected to deploy my application on AWS infrastructure. 

### What actually happened?
Nothings happen because the file upload is empty but the file in my local machine is not empty.

### Environment

  - **CDK CLI Version  :** 1.87.1
  - **Framework Version:** 1.87.1
  - **Node.js Version:** 14.15.4
  - **OS               :** Linux
  - **Language (Version):** 3.9.7

### Other

I used this same code to upload the zip file on previous **CDK CLI** version and it works but now when I decided to update the version, it does not work anymore.

--- 

This is :bug: Bug Report

**Comment by alex-hladun** [comment] 2021-02-01 15:39
Follow the recommended steps at the top here: https://github.com/aws/aws-cdk/issues/12536

**Comment by fabriciolelis** [comment] 2021-02-01 20:59
> Follow the recommended steps at the top here: #12536

I use node versions 14.15.4 and 15.7.0 with CDK versions 1.87.1 and 1.74.0
I deleted cdk.out, the files on the bucket
And the problem persists.

**Comment by alex-hladun** [comment] 2021-02-01 21:02
And you are clearing the staging bucket, and not the bucket itself? 

Also check in the logs that the changeset (changing the node version) is being recognized, we have added cdk deploy --force to ensure the new config is taking effect.

**Comment by fabriciolelis** [comment] 2021-02-01 21:10
> And you are clearing the staging bucket, and not the bucket itself?
Yes
> Also check in the logs that the changeset (changing the node version) is being recognized, we have added cdk deploy --force to ensure the new config is taking effect.
Where I can get the logs?

**Comment by alex-hladun** [comment] 2021-02-01 21:20
Should be in your terminal or your CICD provider

**Comment by fabriciolelis** [comment] 2021-02-02 14:47
> Should be in your terminal or your CICD provider

I've tested with node version 14.15.1 and I used `cdk deploy --force` and the problem not solved. Anymore suggestions?

**Comment by iliapolo** [comment] 2021-02-02 20:47
@nija-at Could you take a look?

**Comment by iliapolo** [comment] 2021-02-10 19:45
Closing. Root cause is https://github.com/aws/aws-cdk/issues/12536 which is now resolved

**Closed by iliapolo** 2021-02-10 19:45 UTC
Labels: @aws-cdk/aws-s3-deployment, bug, needs-triage
