### ISSUE TITLE
cdk cli: isolate stack

### ISSUE THREAD

**Issue by tommydongaws** [aws/aws-cdk#26589] opened 2023-08-01 16:07 UTC
### Describe the feature

Could there be a flag to just run 1 stack inside the app?

`cdk synth <stacka>`
Current Behavior:
running all the stacks and then return the template for stack A.

Requested behavior:
only run stack A and then return that template for stack A.

Cx workaround:
remove stack b from App

### Use Case

If it is isolated then in cases where "stack b" modifies "stack a" the output for stack a would be different.
Additionally it would be faster.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.89.0

### Environment details (OS name and version, etc.)

Windows

**Comment by khushail** [comment] 2023-08-01 16:44
@tommydongaws , thanks for reaching out. It would be helpful if you could state your usecase why this particular change is requested.

**Comment by kprashob** [comment] 2023-08-02 20:52
the issue is when you follow this guidance from AWS, the stacks are no longer isolated:
https://docs.aws.amazon.com/cdk/v2/guide/resources.html#resource_stack

if you create a resource in one stack and expose it, then modify it in another stack, the stacks are no longer isolated. The change from stack 2 is deployed when you deploy stack 1. This breaks the mental model of stacks being isolated.

For example, if you create a lambda in one stack, then in another stack you create a dynamo table and grant access to the lambda, the lambda permissions from stack 2 are deployed with stack 1. This can create unexpected behavior if you were expecting the stacks to deploy in isolation.

**Comment by adrianwright** [comment] 2023-08-03 12:57
Why is stack isolation not default behavior in CDK? It seems to me that resource definitions from one stack should not exist in the CF template generated by a different stack.

**Comment by peterwoodworth** [comment] 2023-08-03 16:10
Duplicate of https://github.com/aws/aws-cdk/issues/6743

**Closed by peterwoodworth** 2023-08-03 16:10 UTC
Labels: duplicate, feature-request, package/tools
