### ISSUE TITLE
aws-eks: Cannot update cluster endpoint access

### ISSUE THREAD

**Issue by resnikb** [aws/aws-cdk#21439] opened 2022-08-03 11:30 UTC
### Describe the bug

Changing endpoint access for an existing EKS cluster fails.

I have an existing EKS cluster with 
```
endpointAccess: EndpointAccess.PUBLIC_AND_PRIVATE
```

If I change that to
```
endpointAccess: EndpointAccess.PRIVATE
```

CloudFormation update fails with error:
```
Received response status [FAILED] from custom resource. Message returned: Only one type of update can be allowed.
```

### Expected Behavior

The update should succeed, and change the endpoint access to `PRIVATE`.

### Current Behavior

Cluster update fails with:
```
Received response status [FAILED] from custom resource. Message returned: Only one type of update can be allowed.
```

### Reproduction Steps

Create a new cluster with logging enabled:
```
   new Cluster(stack, 'Cluster', {
      clusterName: 'MyCluster',
      version: KubernetesVersion.V1_21,
      endpointAccess: EndpointAccess.PUBLIC_AND_PRIVATE,
      vpc,
      clusterLogging: [
        ClusterLoggingTypes.API,
        ClusterLoggingTypes.AUDIT,
        ClusterLoggingTypes.AUTHENTICATOR,
        ClusterLoggingTypes.CONTROLLER_MANAGER,
        ClusterLoggingTypes.SCHEDULER,
      ],
    });
```

Change endpoint access to `EndpointAccess.PRIVATE` and redeploy

### Possible Solution

The cluster handler lambda specifies logging configuration even when only endpoint access needs to be updated. If logging configuration doesn't need updating, it should not be specified in the call to `updateClusterConfig`.

### Additional Information/Context

CloudWatch logs for lambda execution:
```log
2022-08-03T11:07:30.872Z	c627c94c-6ee5-4193-9d6b-18f1b376637a	INFO	onUpdate: {
    "updates": {
        "replaceName": false,
        "replaceVpc": false,
        "updateAccess": true,
        "replaceRole": false,
        "updateVersion": false,
        "updateEncryption": false,
        "updateLogging": false
    }
}

2022-08-03T11:07:31.798Z	c627c94c-6ee5-4193-9d6b-18f1b376637a	INFO	[AWS eks 400 0.925s 0 retries] updateClusterConfig({
  name: '<redacted>',
  logging: {
    clusterLogging: [
      {
        types: [
          'api',
          'audit',
          'authenticator',
          'controllerManager',
          'scheduler',
          [length]: 5
        ],
        enabled: true
      },
      { types: [ [length]: 0 ], enabled: true },
      [length]: 2
    ]
  },
  resourcesVpcConfig: {
    endpointPrivateAccess: true,
    endpointPublicAccess: false,
    publicAccessCidrs: undefined
  },
  clientRequestToken: '<redacted>'
})

2022-08-03T11:07:31.812Z	c627c94c-6ee5-4193-9d6b-18f1b376637a	ERROR	Invoke Error 	{
    "errorType": "InvalidParameterException",
    "errorMessage": "Only one type of update can be allowed.",
    "code": "InvalidParameterException",
    "message": "Only one type of update can be allowed.",
    "time": "2022-08-03T11:07:31.797Z",
    "requestId": "<redacted>",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 23.61820879655758,
    "stack": [
        "InvalidParameterException: Only one type of update can be allowed.",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)"
    ]
}
```

### CDK CLI Version

2.35.0 (build 5c23578)

### Node.js Version

v16.16.0

### OS

Linux

### Language

Typescript

**Comment by resnikb** [comment] 2022-08-03 11:52
On further inspection, this might be related to #21436 and the changes made in #21185, as the `clusterLogging` JSON in the call to `updateClusterConfig` is now invalid.

**Comment by juweeks** [comment] 2022-08-09 15:06
we're getting this too now. v2.33

**Comment by johnnyhuy** [comment] 2022-09-09 23:45
One way we've worked around it was to turn off logging on the first run, switch-over endpoint access and then turn on logging. Not ideal since it doesn't resolve the root issue because we're doing three deploys instead of one.

**Comment by pahud** [comment] 2022-11-16 22:08
I can reproduce this issue in cdk v2.50.0 and I'm assigning this to myself as p2. I'll look into it for the root cause and investigate if there's anything we can do to fix it.

**Comment by pahud** [comment] 2022-11-16 22:32
I think we probably should fix here. 

https://github.com/aws/aws-cdk/blob/5b3d06d808d1eb110943b2c68de75ae6d5b5e624/packages/%40aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts#L139-L154

According to the lambda logs:

```js
{
    "updates": {
        "replaceName": false,
        "replaceVpc": false,
        "updateAccess": true,
        "replaceRole": false,
        "updateVersion": false,
        "updateEncryption": false,
        "updateLogging": false
    }
}
```

We actually need to `updateAccess` only, it's not clear to me why we should have this line:
https://github.com/aws/aws-cdk/blob/5b3d06d808d1eb110943b2c68de75ae6d5b5e624/packages/%40aws-cdk/aws-eks/lib/cluster-resource-handler/cluster.ts#L142

**Comment by pahud** [comment] 2022-11-17 16:08
Just created a PR draft for a quick fix https://github.com/aws/aws-cdk/pull/22957

I can successfully update the stack by simply updating the endpoint access like

```ts
   new eks.Cluster(this, 'Cluster', {
      vpc,
      endpointAccess: eks.EndpointAccess.PRIVATE,
      version: eks.KubernetesVersion.V1_23,
      clusterLogging: [
        eks.ClusterLoggingTypes.API,
        eks.ClusterLoggingTypes.AUDIT,
        eks.ClusterLoggingTypes.AUTHENTICATOR,
        eks.ClusterLoggingTypes.CONTROLLER_MANAGER,
        eks.ClusterLoggingTypes.SCHEDULER,
      ],
    });
    ```
    
    Will look into previous commits to see if I miss anything.

**Comment by jaredhancock31** [comment] 2022-12-05 23:06
We're seeing a similar problem when mutating the list of `allowAccessFrom` CIDRs.

Example:

1. deploy a cluster with something like the following:

```yaml
     # assume clusterLogging also enabled here
      allowAccessFrom:
        - 2.4.6.0/24
        - 1.2.3.4/32
 ```
 
2.  Then, try to update it by removing an entry:

```yaml
     # assume clusterLogging is still the same as before
      allowAccessFrom:
        - 2.4.6.0/24
 ```

3. Observe the following error:

```
4:59:47 PM | UPDATE_FAILED        | Custom::AWSCDK-EKS-Cluster            | EKSClusterE11008B6
Received response status [FAILED] from custom resource. Message returned: Only one type of update can be allowed.

Logs: /aws/lambda/redacted-name-awscdkawseks-OnEventHandler42BEBAE0-5fCPxU8lMELN

at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 7e00f099-29a7-4f0e-8bc9-4e9a7e552922)
```

This was tested using cdk 2.50

**Closed** 2022-12-20 00:47 UTC
Labels: bug, p2, @aws-cdk/aws-eks, effort/medium
