### ISSUE TITLE
(aws-lambda-nodejs): NodejsFunction support EdgeFunction for Lambda@Edge

### ISSUE THREAD

**Issue by radiosilence** [aws/aws-cdk#15661] opened 2021-07-20 11:18 UTC
If I wish to use NodejsFunction to create a Lambda@Edge, I need to make sure that my whole stack is currently in `us-east`.

If there was a prop or flag on NodejsFunction props, we could easily deploy our NodeJS functions to Lambda@Edge.

Something similar likely needs to happen with other lambda helpers.

It seems someone has already made a EdgeFunction construct:
https://github.com/aws/aws-cdk/pull/10500

So it could be a case of just refactoring so that there was a class that inherited from that instead of lambda.Function.

This would probably need to be done with the go/python helpers, too.

### Use Case

I would like to use NodejsFunction to create lambdas that can be used with Lambda@Edge with my stack in any region.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by radiosilence** [comment] 2021-07-20 20:28
Implementation wise, I have done this if I copy paste the class and change what it inherits and slightly weaken the props. Works perfectly, but now I have a copy of the aws-lambda-nodejs project in my own which is not ideal.

**Comment by Shiroy** [comment] 2021-07-21 09:20
I think a better implementation would be to publicly expose the bundler in `aws-lambda-nodejs` as a top-level component instead of keeping it package private.

https://github.com/aws/aws-cdk/blob/464cdc0baa1fc5b0634e428a9c7a15de4ca93d50/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L40

This would allow any kind of lambda function to rely on the esbuild bundler. This would benefit 

https://github.com/aws/aws-cdk/blob/464cdc0baa1fc5b0634e428a9c7a15de4ca93d50/packages/%40aws-cdk/aws-cloudfront/lib/experimental/edge-function.ts#L37

and

https://github.com/aws/aws-cdk/blob/464cdc0baa1fc5b0634e428a9c7a15de4ca93d50/packages/%40aws-cdk/aws-cloudfront/lib/function.ts#L133

As an example, the following snippet works for deploying Lambda@Edges but it relies on the `Bundling` component which is internal to `aws-lambda-nodejs`

```ts
import { Runtime } from "@aws-cdk/aws-lambda";
import * as cdk from "@aws-cdk/core";
import { Bundling } from "@aws-cdk/aws-lambda-nodejs/lib/bundling"; 
// Not OK as we rely on the package private bundler. 
// This does not provide any stability guarantee in the long run.
import * as path from "path";
import { EdgeFunction } from "@aws-cdk/aws-cloudfront/lib/experimental";

export interface PrefixRemoverProps {
    prefixToRemove: string
}

export class PrefixRemover extends cdk.Construct {
    readonly lambda: EdgeFunction
    constructor(scope: cdk.Construct, name: string, props: PrefixRemoverProps) {
        super(scope, name)

        this.lambda = new EdgeFunction(this, `${name}-prefixRemover` , {
            code: Bundling.bundle({
                runtime: Runtime.NODEJS_14_X,
                depsLockFilePath: path.join(__dirname, "src" , "package-lock.json"),
                entry: path.join(__dirname, "src", "handler.ts"),
                projectRoot: path.join(__dirname, "src"),
                define: {
                    'process.env.PREFIX_TO_REMOVE': `"${props.prefixToRemove}"`
                },
                forceDockerBundling: true
            }),
            runtime: Runtime.NODEJS_14_X,
            handler: "index.handler"
        });
    } 
}
```

**Comment by radiosilence** [comment] 2021-07-22 11:56
That would be quite cool too. Then we could in theory just copy one class and reference it in our projects.

These are the things that need to be exposed:

```ts
import { Bundling } from './bundling';
import { PackageManager } from './package-manager';
import { BundlingOptions } from './types';
import { callsites, findUp } from './util';
```


And most of these methods etc could be mixed in somehow:


```ts
export class NodejsEdgeFunction extends cloudfront.experimental.EdgeFunction {
  constructor(scope: Construct, id: string, props: NodejsEdgeFunctionProps = {}) {
    if (props.runtime && props.runtime.family !== lambda.RuntimeFamily.NODEJS) {
      throw new Error('Only `NODEJS` runtimes are supported.');
    }

    // Entry and defaults
    const entry = path.resolve(findEntry(id, props.entry));
    const handler = props.handler ?? 'handler';
    const runtime = props.runtime ?? lambda.Runtime.NODEJS_14_X;
    const depsLockFilePath = findLockFile(props.depsLockFilePath);
    const projectRoot = props.projectRoot ?? path.dirname(depsLockFilePath);

    super(scope, id, {
      ...props,
      runtime,
      code: Bundling.bundle({
        ...(props.bundling ?? {}),
        entry,
        runtime,
        depsLockFilePath,
        projectRoot,
      }),
      handler: `index.${handler}`,
    });
  }
}

/**
 * Checks given lock file or searches for a lock file
 */
function findLockFile(depsLockFilePath?: string): string {
  if (depsLockFilePath) {
    if (!fs.existsSync(depsLockFilePath)) {
      throw new Error(`Lock file at ${depsLockFilePath} doesn't exist`);
    }

    if (!fs.statSync(depsLockFilePath).isFile()) {
      throw new Error('`depsLockFilePath` should point to a file');
    }

    return path.resolve(depsLockFilePath);
  }

  const lockFile =
    findUp(PackageManager.PNPM.lockFile) ?? findUp(PackageManager.YARN.lockFile) ?? findUp(PackageManager.NPM.lockFile);

  if (!lockFile) {
    throw new Error(
      'Cannot find a package lock file (`pnpm-lock.yaml`, `yarn.lock` or `package-lock.json`). Please specify it with `depsFileLockPath`.',
    );
  }

  return lockFile;
}

/**
 * Searches for an entry file. Preference order is the following:
 * 1. Given entry file
 * 2. A .ts file named as the defining file with id as suffix (defining-file.id.ts)
 * 3. A .js file name as the defining file with id as suffix (defining-file.id.js)
 */
function findEntry(id: string, entry?: string): string {
  if (entry) {
    if (!/\.(jsx?|tsx?)$/.test(entry)) {
      throw new Error('Only JavaScript or TypeScript entry files are supported.');
    }
    if (!fs.existsSync(entry)) {
      throw new Error(`Cannot find entry file at ${entry}`);
    }
    return entry;
  }

  const definingFile = findDefiningFile();
  const extname = path.extname(definingFile);

  const tsHandlerFile = definingFile.replace(new RegExp(`${extname}$`), `.${id}.ts`);
  if (fs.existsSync(tsHandlerFile)) {
    return tsHandlerFile;
  }

  const jsHandlerFile = definingFile.replace(new RegExp(`${extname}$`), `.${id}.js`);
  if (fs.existsSync(jsHandlerFile)) {
    return jsHandlerFile;
  }

  throw new Error(`Cannot find handler file ${tsHandlerFile} or ${jsHandlerFile}`);
}

/**
 * Finds the name of the file where the `NodejsFunction` is defined
 */
function findDefiningFile(): string {
  let definingIndex;
  const sites = callsites();
  for (const [index, site] of sites.entries()) {
    if (site.getFunctionName() === 'NodejsFunction') {
      // The next site is the site where the NodejsFunction was created
      definingIndex = index + 1;
      break;
    }
  }

  if (!definingIndex || !sites[definingIndex]) {
    throw new Error('Cannot find defining file.');
  }

  return sites[definingIndex].getFileName();
}
```

**Comment by blimmer** [comment] 2021-08-05 16:03
Is this ticket potentially a dupe of #12671?

**Comment by njlynch** [comment] 2021-08-16 10:53
Thanks all for the conversation and discussion here. This is indeed a duplicate of #12671, so I'm going to close this one out and refer to the other for tracking. Please :+1: that issue and continue the discussion there.

**Closed by njlynch** 2021-08-16 10:53 UTC
Labels: feature-request, @aws-cdk/aws-cloudfront, needs-triage

**Comment by mmuller88** [comment] 2022-02-05 07:21
Trying something :) https://github.com/aws/aws-cdk/pull/18836

**Comment by hugomallet** [comment] 2023-06-01 14:24
Can you just add bundling to the packages.json.exports
that would really help !

**Comment by AllanOricil** [comment] 2024-01-02 21:38
It does not work with cdk v2

<img width="988" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/1fcfab9e-de2b-4128-89fc-83368184ed7e">

<img width="644" alt="image" src="https://github.com/aws/aws-cdk/assets/55927613/6836ee5b-6b27-49fb-b584-afc37f808042">
