### ISSUE TITLE
(pipelines): Allow re-generating CloudFormation changeset after failure

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#11995] opened 2020-12-10 18:32 UTC
As of today, I couldn't find a way to re-run an application stage deployment if application of the CloudFormation changeset failed. We can kick off the pipeline again by committing a dummy/no-op commit to the repository, but this creates unnecessary cruft in the SCM history.

### Use Case

Consider a CloudFormation template that could not apply for some reason. In my case, it was because of a naming conflict with another CloudFormation stack that needed to be destroyed.

The CodePipeline user interface looks like this after the failure:

![Screen_Shot_2020-12-10_at_10_20_02_AM](https://user-images.githubusercontent.com/630449/101806577-5d21bc80-3ad1-11eb-8855-aeae2c3a93a1.png)

So, I took a look at the failure and noticed the naming conflict. I went and destroyed the other CDK stack and wanted to re-run the deployment. However, when I clicked the "Retry" button in the UI, the "Deploy" stage failed with this error message:

```
ChangeSet [PipelineChange] does not exist (Service: AmazonCloudFormation; Status Code: 404; Error Code: ChangeSetNotFound; Request ID: <redacted>)
```

Indeed, in the CloudFormation user interface, the changeset was not present:

![Screen Shot 2020-12-10 at 10 06 59 AM](https://user-images.githubusercontent.com/630449/101814162-01f4c780-3adb-11eb-9346-1e2f757c2a8b.png)

The problem appears to be because there's no way to retry an entire stage in CodePipeline, including steps that previously succeeded. According to the `aws cli` docs (`aws codepipeline retry-stage-execution help`):

```
--retry-mode (string)
  The scope of the retry attempt. Currently, the only supported  value
  is FAILED_ACTIONS.

  Possible values:

  o FAILED_ACTIONS
```

Because I didn't have a way to rerun the `.Prepare` step (which produces the changeset), I was kind of stuck and had to revert to pushing a no-op commit to force the step to re-run.

### Proposed Solution

Since this appears to be a CodePipeline limitation, maybe a custom "step" is needed? Like maybe an SNS topic or something to kick off the deployment again? Or maybe a better solution would be to +1 feature requests on the CodePipeline side to allow "Retry (including succeeded)" behavior?

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by blimmer** [comment] 2020-12-10 19:05
Is it possible that this is only an issue with the initial deploy of the stack? Potentially similar to this: https://github.com/aws/aws-cdk/issues/901?

**Comment by blimmer** [comment] 2020-12-10 20:10
I also just found this command to re-trigger a pipeline from the CLI - maybe it's just not exposed via the UI?

```
aws codepipeline start-pipeline-execution
```

Perhaps this is a good workaround.

**Comment by rix0rrr** [comment] 2020-12-14 10:07
> Or maybe a better solution would be to +1 feature requests on the CodePipeline side to allow "Retry (including succeeded)" behavior?

I would agree that a better solution would be to petition to fix the root cause, rather than try to work around it.

There should be a button at the top-right of your pipeline though that says "Release Change", which does the same as starting the execution using the CLI.

![image](https://user-images.githubusercontent.com/524162/102068261-88bbe400-3dfc-11eb-82d9-842ce3745dc9.png)

Not actionable for CDK. Closing.

**Closed by rix0rrr** 2020-12-14 10:07 UTC
Labels: @aws-cdk/pipelines, feature-request, needs-triage

**Comment by openwebsolns** [comment] 2021-11-16 21:36
> I also just found this command to re-trigger a pipeline from the CLI - maybe it's just not exposed via the UI?
> 
> ```
> aws codepipeline start-pipeline-execution
> ```
> 
> Perhaps this is a good workaround.

This is available through the UI by clicking the "Release change" button.

**Comment by openwebsolns** [comment] 2021-11-16 21:37
This is still a problem. If you have a large pipeline, "releasing a change" would require deploying through all the previous stages before you can retry the failed stage. Is there a creative workaround by which we can "replay" a changeset with the same name (`PipelineChange`) so that the CodePipeline retry works? Does CDK provide the ability to _just_ create the changeset?

**Comment by fab-mindflow** [comment] 2021-12-07 18:27
Indeed, we also have a large CDK deployment and this forces us to build everything again and again. Any workaround?

**Comment by XTEKiyZRLr8UsiQN** [comment] 2023-08-27 21:48
> Indeed, we also have a large CDK deployment and this forces us to build everything again and again. Any workaround?

Hi, a workaround for this is to actually disable change sets. They are auto enabled but based on https://github.com/aws/aws-cdk/pull/21619/files you should be able to remove them. I have had success with this and can now retry my stages. Hope this helps.

https://github.com/aws/aws-cdk/pull/21619/files
