### ISSUE TITLE
GitHub Process: Why do you close unresolved bug reports?

### ISSUE THREAD

**Issue by garyd203** [aws/aws-cdk#13361] opened 2021-03-03 06:13 UTC
### The Question
Why do you have a bot that automatically closes valid bug reports irrespective of whether they have been fixed (such as #10233)? Does this mean that you don't intend to fix bugs if they have been around for a while? Or is the expected process for other users to open a duplicate bug report when we encounter the same issue?

### Environment

GitHub

**Comment by NGL321** [comment] 2021-03-05 18:57
Hey @garyd203!

That is a good question, and I am realizing we dont have any externally facing documentation about how this works. Essentially, we have two events that drive auto-closing issues:
1. "Ancient" issues - If an issue has not received attention in a year (although this timeline is subject to change). This is preceded with an automatic warning, if a comment is left, the issue will not be closed.
2. "Stale" issues - This process _ONLY_ triggers when the `response-requested` label is added to an issue. When said label is applied, the automation listens for response, if a comment is left within 1 week, the label is simply removed; however, if no response is made within a week, the action leaves a comment warning that the issue is becoming "stale" and changes the label to `closing-soon`. If no response is left within the 4 days following that, the issue is automatically closed.

Both of these processes allow us to better isolate and prioritize. We are a small team and the number of incoming issues far exceeds our capacity to resolve, these are one part of a larger system that allows us to identify and focus our energy on the most important issues.

I will make sure to add some sort of more permanent documentation of this process to our READMEs.

😸 😷

**Comment by garyd203** [comment] 2021-03-08 02:25
ok, thank you for explaining your process

**Comment by NGL321** [comment] 2021-05-14 22:52
Closing due to resolution

😸 😷

**Closed by NGL321** 2021-05-14 22:52 UTC
Labels: guidance
