### ISSUE TITLE
(cli) cdk destroy does not obey --profile flag

### ISSUE THREAD

**Issue by baumannalexj** [aws/aws-cdk#12544] opened 2021-01-15 22:45 UTC
When running CDK destroy with the --profile flag `$ cdk destroy --profile my-admin-profile`
I get an error stating my default aws-cli profile  (`my-default-user-profile`) is not authorized. 

It's true **my-default-user-profile** is not authorized, which is why use --profile **my-admin-profile** to run CDK commands.

```
stack-cdk-service: destroying...
4:34:15 PM | DELETE_FAILED        | AWS::IAM::Policy                 | lambda-cdk-service...Role/DefaultPolicy
API: iam:DeleteRolePolicy User: arn:aws:iam::357128852511:user/my-default-user-profile is not authorized to perform: iam:DeleteRolePolicy on resource: role stack-cdk-service-lambdacdkyn-1EK7W5OZZZMFM
```

### Reproduction Steps

* create an IAM account with no privileges
* run `aws-cli` configure to set this account as your default profile
* create an admin IAM account with create and delete privileges
* create a small CDK project 
* deploy cdk with the admin IAM profile (this should pass only for admin-profile, not default profile) `$ cdk deploy --profile admin-profile`  
* run cdk destroy with admin profile (this should fail): `$ cdk destroy --profile admin-profile`  

### What did you expect to happen?

the --profile flag would use the aws-cli profile I provided

### What actually happened?

the default profile was used 

What is the unexpected behavior you were seeing? If you got an error, paste it here.
```
stack-cdk-service: destroying...
4:34:15 PM | DELETE_FAILED        | AWS::IAM::Policy                 | lambda-cdk-service...Role/DefaultPolicy
API: iam:DeleteRolePolicy User: arn:aws:iam::357128852511:user/my-default-user-profile is not authorized to perform: iam:DeleteRolePolicy on resource: role stack-cdk-service-lambdacdkyn-1EK7W5OZZZMFM
```

### Environment

  - **CDK CLI Version  : ** 1.85.0 (build 5f44668)
  - **Framework Version:** 
  - **Node.js Version:** v12.20.1
  - **OS               :** mac os mojave - 10.14.6 (18G7016)
  - **Language (Version):** v12.20.1

### Other

nothing else

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment] 2021-06-03 20:14
Hey @baumannalexj 👋🏻 

Thanks for providing clear reproduction steps! I spent some time going through those steps with the latest release `v1.107.0 (build 52c4434)` and was not able to reproduce the error you were receiving. It may be possible that this bug was fixed in a recent update.

Could you check to see if upgrading your CDK to the latest resolves this issue?

**Comment by baumannalexj** [comment] 2021-06-04 01:30
Thanks for looking into this @ryparker !

I no longer have my environment setup for this an am working on a different stack. Let's close this.

**Closed** 2021-06-13 05:36 UTC
Labels: bug, effort/medium, p1, package/tools
