### ISSUE TITLE
(module name): (short issue description)

### ISSUE THREAD

**Issue by guganscode** [aws/aws-cdk#22160] opened 2022-09-21 03:40 UTC
### Describe the feature

Rust language support

### Use Case

Ability to use Rust language with CDK

### Proposed Solution

Rust programing model

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.42.1

### Environment details (OS name and version, etc.)

Mac

**Comment by indrora** [comment] 2022-09-21 18:17
This fundamentally depends on jsii supporting rust. Closing as dupe of https://github.com/aws/jsii/issues/1684

**Closed by indrora** 2022-09-21 18:17 UTC
Labels: feature-request, needs-triage
