### ISSUE TITLE
EKS Update API server endpoint access functionality

### ISSUE THREAD

**Issue by nikhilbhoj** [aws/aws-cdk#7084] opened 2020-03-31 05:38 UTC
Hi,

I was searching for EKS package if I can update EKS  API server endpoint access private or public ( in public also white list IP ranges).

But, I was unable to find that functilanity ot options in EKS package.

CDK version 1.28.
Language : Typescript

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by eladb** [comment] 2020-04-01 06:14
Can you please provide a reference to AWS docs with the feature you need?

**Comment by nikhilbhoj** [comment] 2020-04-02 00:23
Hi @eladb 

This is reference for the AWS docs that mentions this functionality.

https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html

Thanks,
Nikhil

**Comment by arjanschaaf** [comment] 2020-06-16 12:52
@eladb isn't this an duplicate of this issue? https://github.com/aws/aws-cdk/issues/5220

**Comment by eladb** [comment] 2020-06-24 07:02
Dup https://github.com/aws/aws-cdk/issues/5220

**Closed by eladb** 2020-06-24 07:02 UTC
Labels: @aws-cdk/aws-eks, effort/small, feature-request
