### ISSUE TITLE
cdk deploy : Could not refresh notices: Error: Request timed out.

### ISSUE THREAD

**Issue by mpekalski** [aws/aws-cdk#20228] opened 2022-05-05 10:27 UTC
### Describe the bug

Following advice from the logs:

> Could not refresh notices: Error: Request timed out. You should never see this message; if you do, please let us know at https://github.com/aws/aws-cdk/issues

### Expected Behavior

I guess I should not see this message.

### Current Behavior

there are no exceptions and the error is included in description of the bug

### Reproduction Steps

cdk deploy ... 

### CDK CLI Version

 CDK_CLI_ASM_VERSION: '17.0.0',   CDK_CLI_VERSION: '2.22.0'

### Node.js Version

v17.9.0

### OS

Ubuntu 20.04

### Language

Python

### Language Version

3.8.10

**Comment by rix0rrr** [comment] 2022-05-09 10:13
Thanks. Duplicate of #20069.

**Closed by rix0rrr** 2022-05-09 10:13 UTC
Labels: bug, package/tools, needs-triage
