### ISSUE TITLE
(ec2): addS3DownloadCommand with CDK Asset errors for opt in regions

### ISSUE THREAD

**Issue by timothy-mcphie** [aws/aws-cdk#12946] opened 2021-02-09 17:45 UTC
When using `addS3DownloadCommand`, for EC2 user data, with an S3 file uploaded as an asset via CDK - the generated command will fail in opt in regions with `IllegalLocationConstraintException`.

### Reproduction Steps
Opt in an AWS account to `eu-south-1` and create a stack with the following:
```ts
const asg = new AutoScalingGroup(this, "ASG", { ...props });

const asset = new Asset(this, "Asset", {
        path: "/some/path/to/a/file"
});

asg.userData.addS3DownloadCommand({
        bucket: asset.bucket,
        bucketKey: asset.s3ObjectKey,
});
```
### What did you expect to happen?

- My file to be downloaded from S3 onto my host.

### What actually happened?

- It failed with `IllegalLocationConstraintException`

### Other
It looks like the `addS3DownloadCommand` or the `Asset` construct are missing the ability to infer bucket region information between the two.

The [generated command](https://github.com/aws/aws-cdk/blob/a72cfbd5d0f9af87aacf0657a6fc370ce2a23c55/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L159) will work if `--region $REGION` is appended.

Or is this a case of myself misusing the CDK Asset API in relation to `addS3DownloadCommand` here?

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-02-15 10:16
Duplicate of #11958

**Closed by rix0rrr** 2021-02-15 10:16 UTC
Labels: @aws-cdk/aws-ec2, bug, needs-triage
