### ISSUE TITLE
[module] 

### ISSUE THREAD

**Issue by informity** [aws/aws-cdk#10664] opened 2020-10-03 00:43 UTC
### The Question
I am getting multiple "The stack MyStack already includes a CDKMetadata resource" warnings each time I synth or deploy my stacks. I am using the latest CDK 1.66.0 with:

* @aws-cdk/aws-ec2;
* @aws-cdk/aws-rds;
* @aws-cdk/aws-elasticloadbalancingv2;
* @aws-cdk/aws-elasticloadbalancingv2-targets;
* @aws-cdk/aws-ssm;

Here are my stacks -> https://github.com/informity/aws-powerdns/

### Output

```
cdk diff MyStack-West-VPC
The stack MyStack-East-EC2 already includes a CDKMetadata resource
The stack MyStack-East-LBH already includes a CDKMetadata resource
The stack MyStack-East-PAR-RHEL8 already includes a CDKMetadata resource
The stack MyStack-East-RDS already includes a CDKMetadata resource
The stack MyStack-East-VPC already includes a CDKMetadata resource
The stack MyStack-West-ADM already includes a CDKMetadata resource
The stack MyStack-West-EC2 already includes a CDKMetadata resource
The stack MyStack-West-LBH already includes a CDKMetadata resource
The stack MyStack-West-PAR-RHEL8 already includes a CDKMetadata resource
The stack MyStack-West-RDS already includes a CDKMetadata resource
The stack MyStack-West-VPC already includes a CDKMetadata resource
Stack MyStack-West-VPC
```

### Environment

  - **CDK CLI Version:** 1.66.0 (build 459488d)
  - **Module Version:** 1.65.0
  - **Node.js Version:** v12.18.4
  - **OS:** MacOS Catalina 10.15.6
  - **Language (Version):** TypeScript (Version 4.0.3)

**Comment by shivlaks** [comment] 2020-10-03 07:17
@informity - I believe this was a warning recently added in `1.65.0` - closing this issue as it's a duplicate of #10625 
Please feel free to +1 and add any context.

**Closed by shivlaks** 2020-10-03 07:17 UTC
Labels: guidance, needs-triage
