### ISSUE TITLE
[pipeline/route53] HostedZone.fromLookup always returns `DUMMY` in CDK pipeline

### ISSUE THREAD

**Issue by justin8** [aws/aws-cdk#9922] opened 2020-08-24 01:21 UTC
I was attempting to use a route53 hosted zone from lookup in CDK, which works quite well locally but when used within a CDK pipeline everything synths fine, and then when attempting to deploy the output CloudFormation template contains the hosted zone ID `DUMMY`.

### Reproduction Steps

* Create a route53 hosted zone elsewhere

```typescript
    const hostedZone = route53.HostedZone.fromLookup(this, "zone", { domainName: parentDomainName() }});

    const cert = new acm.Certificate(this, "vodCert", {
      domainName: SubDomainName(props.stage),
      validation: CertificateValidation.fromDns(hostedZone),
    });
```

### What did you expect to happen?

I expected fromLookup to return a valid hosted zone ID

### What actually happened?

The generated CloudFormation template contains `DUMMY` as the hosted zone ID

### Environment

  - **CLI Version      :**1.60
  - **Framework Version:**1.60
  - **Node.js Version:** v14.8.0
  - **OS               :** MacOS
  - **Language (Version):** all

### Other

--- 

This is :bug: Bug Report

**Comment by fspaniol** [comment] 2020-09-24 15:56
For anyone out there looking for a solution for this, I managed to workaround this by hard coding the value of the Hosted Zone in the context within `cdk.json`

This was originally proposed (although for a different resource) here: https://github.com/aws/aws-cdk/issues/9226#issuecomment-678932687

**Comment by njlynch** [comment] 2020-11-04 17:15
Closing out as duplicate of #9226

**Closed by njlynch** 2020-11-04 17:15 UTC
Labels: @aws-cdk/aws-route53, @aws-cdk/pipelines, bug, effort/medium, needs-triage, p1
