### ISSUE TITLE
[docs] Package overview in Python API documentation doesn't render Markdown correctly

### ISSUE THREAD

**Issue by alexpulver** [aws/aws-cdk#10713] opened 2020-10-06 05:21 UTC
One example is AppSync, but it happens in additional modules (aws_apigatewayv2 and more)
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_appsync.README.html

Example from link above: 
--- ![cfn-resources: Stable](https://img.shields.io/badge/cfn--resources-stable-success.svg?style=for-the-badge) > All classes with the `Cfn` prefix in this module ([CFN Resources](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html#constructs_lib)) are always stable and safe to use. ![cdk-constructs: Experimental](https://img.shields.io/badge/cdk--constructs-experimental-important.svg?style=for-the-badge) > The APIs of higher level constructs in this module are experimental and under active development. They are subject to non-backward compatible changes or removal in any future version. These are not subject to the [Semantic Versioning](https://semver.org/) model and breaking changes will be announced in the release notes. This means that while you may use them, you may need to update your source code when upgrading to a newer version of this package. ---

---

This is a 📕 documentation issue

**Comment by SomayaB** [comment] 2020-10-08 21:16
Duplicate of #10701

**Closed by SomayaB** 2020-10-08 21:16 UTC
Labels: bug, documentation, needs-triage
