### ISSUE TITLE
Updating ECS TaskDefinition reverts other changes to running service image definition tag (eg due to CodeDeploy)

### ISSUE THREAD

**Issue by Plasma** [aws/aws-cdk#14437] opened 2021-04-29 01:53 UTC
### The Question

Whenever an update to the TaskDefinitions for an ECS service is required (for example, new environment variables or CPU limits), the service has the indicated instance image re-applied as to what's in the CDK template, instead of using whatever is already in the ECS's service task definition.

Ideally, it would just find and re-use the existing service's running TaskDefinition container image tag, that would have been set by a separate process since the CDK last performed an update (eg via a CodePipeline deployment process).

### Environment

  - **CDK CLI Version:** 1.101.0 (build 149f0fc)
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:**  all
  - **Language (Version):**  C#

**Comment by danwiltshire** [comment] 2021-05-27 22:35
I'd like to understand in general how to handle this.  In my case I have two stacks; application and CICD.  CICD depends on ecs.FargateService outputs from the application stack but the Task Definition relies on a built image from CICD (via CodePipeline).  Today I'm using a placeholder image but I run into this exact problem.

I'm aware the CDK docs suggest deploying a synthed CloudFormation template as generated by CDK within CodePipeline along with TagParameterContainerImage supplied to the Task Def.  Guess I'm hoping for something cleaner.

**Comment by skinny85** [comment] 2021-05-27 23:27
@danwiltshire What's the problem with using `TagParameterContainerImage` as the CDK docs propose? What's "not clean" about it?

**Comment by danwiltshire** [comment] 2021-05-28 08:43
Hey,

My use case may be unique.  The pipeline is triggered when application source code changes (essentially just a Docker image build with Packer, hosted in a different repo).

So to use `TagParameterContainerImage` I would need to:
- Implement everything per the CDK docs (I would have to pull the CDK code into the CodePipeline which runs when the application source code is changed)
- Split the Fargate resource into its own CDK stack to avoid unexpected changes of other resources.

What do you think? Does using `TagParameterContainerImage` sound like a reasonable approach for my use case?

Why I didn't think it is clean - mainly the fact I'd have to pull in the CDK code into the application build pipeline and hard code the path to the synthed CloudFormation JSON.

Admittedly if I was just building with Dockerfiles I could use the builtin magic but I've got other systems to integrate at this time.

**Comment by skinny85** [comment] 2021-05-28 16:46
I have to say, I don't exactly follow your setup.

Where is the CDK code that defines your infrastructure deployed?

**Comment by danwiltshire** [comment] 2021-05-28 16:56
Separate repo and has multiple stacks.  That seemed to make more sense to me rather than having a CDK project for each application (in each application repo).

**Comment by skinny85** [comment] 2021-05-28 17:02
Sorry, I'm still not following...

Can you maybe write a simple diagram, maybe using https://app.diagrams.net, that shows:

1. What are your deployment Pipelines.
2. What sources do the deployment pipelines have (CDK code, application code).
3. How is the CDK application code divided.
4. Where is the CDK code that defines the deployment Pipeline(s).
5. Where is the CDK application code deployed.
6. How is the deployment Pipeline(s) CDK code deployed (it's fine if the answer is "manual `cdk deploy`").

Sorry, but I really can't answer this question:

> What do you think? Does using TagParameterContainerImage sound like a reasonable approach for my use case?

If I don't understand what the desired end goal is.

**Comment by danwiltshire** [comment] 2021-05-28 17:19
![Screenshot 2021-05-28 at 18 14 48](https://user-images.githubusercontent.com/35703524/120019632-9945cc80-bfe0-11eb-83f7-b9bed1cabc82.png)

Quick and crude diagram.  My goal is what OP is asking for - to prevent CloudFormation replacing a running image which was deployed to the FargateService outside of CDK using CodePipeline.

**Comment by skinny85** [comment] 2021-05-28 19:14
In my opinion, the problem is that you've split the deployment between code and infrastructure, and that's why you're running into this problem.

Unless you're willing to dramatically change your setup, and move the CDK deployment also to the Pipeline (which is absolutely what you should do), I don't think you'll ever solve this problem.

**Comment by danwiltshire** [comment] 2021-05-28 19:25
Fair enough, I appreciate your help and I'll have a play with the setup!

**Comment by peterwoodworth** [comment] 2021-06-02 20:49
@danwiltshire please keep us updated on if the guidance skinny posted helped you out!

**Comment by danwiltshire** [comment] 2021-06-02 21:00
Sure, I actually implemented a working solution in the past few hours.

I'm now using the TagParameterContainerImage solution mentioned in the [CDK docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-codepipeline-actions-readme.html#deploying-ecs-applications-stored-in-a-separate-source-code-repository).

The main change was tightly coupling application and infrastructure within the application deployment pipeline as suggested by @skinny85.

For anyone else watching, this info might be useful:
- My CDK project holds stacks for each application As such, the CDK project has its own repo.  Main driver was to centralise our own CDK constructs, data, etc.
- Our application repos now hold a Dockerfile which CDK builds and deploys to Fargate.

So yes, I'm all good, thanks all. Hopefully this helps you @Plasma?  Feel free to ask further questions.

**Comment by peterwoodworth** [comment] 2021-06-11 19:27
Thanks for the update! I'll be closing the issue now, feel free to ping me if anyone wants to reopen this issue!

**Closed by peterwoodworth** 2021-06-11 19:27 UTC
Labels: @aws-cdk/aws-ecs, guidance, response-requested

**Comment by spyoungtech** [comment] 2023-11-22 02:15
Another option beside the `TagParameterContainerImage` is just to use a static tag in your CDK app.  If you have multiple services, say, per 'environment' you would use a different tag for each of these. Whenever you (successfully) update the ECS service, just update the tag reference to point to the image currently in use by the service.

e.g.:

1. Create the taskdefinition in your CDK app using a static tag in the taskdef e.g.`tag="production"`
2. Create and push new image to ECR with a unique tag (say, a git SHA or similar)
3. Create a new task definition that updates the tag to the new unique tag and update the ECS service with the new taskdef
4. After the deployment stabilizes, push the static tag onto the same ref in ECR you pushed in step 2 (e.g. `docker tag myrepo/myimage:abc-123 myrepo/myimage:production; docker push myrepo/myimage:production`

This way, even if infrastructure updates occur that require an update/replacement of the ECS service, it will still reference the correct image in ECR.
