### ISSUE TITLE
[cognito] Unable to create user pool with MFA required

### ISSUE THREAD

**Issue by binoculars** [aws/aws-cdk#11478] opened 2020-11-15 01:47 UTC
(See reproduction steps for code example)

Ideally, I would like to enable MFA required with OTP only (not SMS)

When `mfaSecondFactor.sms` is set to `false`, the stack is able to be synthesized, but CloudFormation gives this error:

> SMS configuration and Auto verification for phone_number are required when MFA is required/optional (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: d5cbb83e-b38a-4f57-9993-65ff923ac325; Proxy: null)

When `mfaSecondFactor.sms` is set to `true, the stack is not able to be synthesized with the following error:

```
TypeError: Cannot read property 'uniqueId' of undefined
    at UserPool.smsConfiguration (/Users/barrett/Projects/github.com/tributumtax/monorepo/.yarn/$$virtual/@aws-cdk-aws-cognito-virtual-cef0628d0c/0/cache/@aws-cdk-aws-cognito-npm-1.73.0-8a062b6262-b3bdc35f1d.zip/node_modules/@aws-cdk/aws-cognito/lib/user-pool.ts:884:37)
    at new UserPool (/Users/barrett/Projects/github.com/tributumtax/monorepo/.yarn/$$virtual/@aws-cdk-aws-cognito-virtual-cef0628d0c/0/cache/@aws-cdk-aws-cognito-npm-1.73.0-8a062b6262-b3bdc35f1d.zip/node_modules/@aws-cdk/aws-cognito/lib/user-pool.ts:740:30)
    at new AuthStack (/Users/barrett/Projects/github.com/tributumtax/monorepo/packages/aws/lib/auth-stack.ts:23:22)
    at Object.<anonymous> (/Users/barrett/Projects/github.com/tributumtax/monorepo/packages/aws/bin/aws.ts:45:19)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Module.m._compile (/Users/barrett/Projects/github.com/tributumtax/monorepo/.yarn/unplugged/ts-node-virtual-9b8834e7f3/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/barrett/Projects/github.com/tributumtax/monorepo/.yarn/unplugged/ts-node-virtual-9b8834e7f3/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.external_module_.Module._load (/Users/barrett/Projects/github.com/tributumtax/monorepo/.pnp.js:26436:14)
Subprocess exited with error 1
```

### Reproduction Steps

```typescript
import { App, Stack, StackProps } from '@aws-cdk/core';
import * as cognito from '@aws-cdk/aws-cognito';

export class AuthStack extends Stack {
  constructor(scope: App, id: string, props: StackProps) {
    super(scope, id, props);

    const userPool = new cognito.UserPool(this, 'UserPool', {
      selfSignUpEnabled: true,
      signInAliases: {
        email: true,
      },
      autoVerify: {
        email: true,
      },
      mfa: cognito.Mfa.REQUIRED,
      mfaSecondFactor: {
        sms: true,
        otp: true,
      },
      passwordPolicy: {
        minLength: 16,
        requireLowercase: true,
        requireUppercase: true,
        requireDigits: true,
        requireSymbols: true,
      },
      accountRecovery: cognito.AccountRecovery.EMAIL_ONLY,
    });
  }
}
```

### What did you expect to happen?

I should be able to deploy the stack

### What actually happened?

The synth fails if sms is true and CloudFormation fails if it is set to false.

### Environment

  - **CDK CLI Version  :** 1.62.0
  - **Framework Version:** 1.62.0
  - **Node.js Version:** 14.2.0
  - **OS               :** OS X Catalina
  - **Language (Version):** TypeScript (4.0.20

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-11-17 15:39
> Ideally, I would like to enable MFA required with OTP only (not SMS)

I am able to set this up by taking the code you provided but setting `mfaSecondFactor.sms` to `false` and `mfaSecondFactor.otp` to `true`. The stack deployed successfully.

I was able to set up the stack again by setting `mfaSecondFactor.sms` to `true`.

Can you try creating the user pool afresh, rather than as an update to an existing user pool?

**Comment by binoculars** [comment] 2020-11-17 17:56
@nija-at This is a new stack, so I'm not sure what you mean by creating the user pool afresh. Again, when `mfaSecondFactor.sms` is set to `false`, I get a the CloudFormation error

**Comment by nija-at** [comment] 2020-11-18 10:41
I can't seem to figure out what the correct configuration for the user pool in this case is.

As you've noted, when MFA is required with OTP only (not SMS), the error message is -
> SMS configuration and Auto verification for phone_number are required when MFA is required/optional (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: d5cbb83e-b38a-4f57-9993-65ff923ac325; Proxy: null)

However, if I do set the SMS configuration (even if it's just OTP only MFA), the error message I get is -
> Can't turn off SMS_MFA when SMS configuration is set for the user pool with a required or optional MFAConfiguration. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)

It's not clear what the correct configuration is for setting up a user pool for OTP only MFA.
I've reached out to the Cognito team for guidance.

Internal ref: t.corp/ea0d5c0e-6634-48b5-8946-1b760c0b6fee

**Comment by heyarnold1** [comment] 2020-12-22 15:41
I think i created a duplicate ticket
https://github.com/aws/aws-cdk/issues/12075

Does this issue impact just CDK or does it also impact Cloudformation?

I note Terraform had a similar issue that appears to now be closed
https://github.com/hashicorp/terraform-provider-aws/issues/7261

**Comment by velovix** [comment] 2020-12-28 17:57
I believe this is also an issue with CloudFormation. I see this problem when using Serverless with CloudFormation templates.

**Comment by ravenscar** [comment] 2021-02-09 04:54
I ran into this problem and have discovered if I create the userpool first then add in 
```
      mfa: cognito.Mfa.REQUIRED,
      mfaSecondFactor: {
        sms: true,
        otp: true,
      },
```
and run it again, it gets set up correctly.

Obviously not a particularly useful workaround but might work in a pinch.

**Comment by heikkis** [comment] 2021-02-10 21:52
I think CDK produce wrong Cloudformation template. It is not Cloudformation problem in general.

```
      EnabledMfas:
        - SMS_MFA
        - SOFTWARE_TOKEN_MFA
      MfaConfiguration: "OFF"
```

I'm now able to bypass this problem with CFN modification:

```
            const cfnUserPool = userPool.node.defaultChild as CfnUserPool
            cfnUserPool.addPropertyOverride(
                'MfaConfiguration',
                "ON"
            )
```

**Comment by BenassiJosef** [comment] 2021-04-03 02:57
Hey guys,
I was also getting this error: "SMS configuration and Auto verification for phone_number are required when MFA is required/optional..." When using the CDK (typescript) and setting `mfa: cognito.Mfa.REQUIRED,
      mfaSecondFactor: {
        sms: false,
        otp: true
      }`

**Comment by Gslaughl** [comment] 2021-04-12 23:31
I just want to bump this issue. Fwiw I'm also seeing the same error with CloudFormation.

> SMS configuration and Auto verification for phone_number are required when MFA is required/optional

**Comment by ChrisSargent** [comment] 2021-04-30 13:43
I am also seeing this issue with the following stack:

```ts
const userPool = defaults.buildUserPool(this, {
      accountRecovery: AccountRecovery.EMAIL_ONLY,
      autoVerify: {
        email: true,
        phone: false,
      },
      enableSmsRole: false,
      mfa: cognito.Mfa.OPTIONAL,
      mfaSecondFactor: {
        otp: true,
        sms: false,
      },
      removalPolicy: RemovalPolicy.DESTROY,
      selfSignUpEnabled: true,
      signInAliases: {
        email: true,
        phone: false,
        preferredUsername: false,
        username: false,
      },
      signInCaseSensitive: false,
    });
```

**Comment by polarizeme** [comment] 2021-05-19 22:11
> UPDATE:
> 
> I was able to deploy the stack if I set `mfa` to off. And then I could switch to optional via the UI.... which is not ideal and also not that interesting. What is slightly interesting is that if I tried to redeploy the stack (still with mfa = off), it successfully deployed but did not actually change the user pool mfa setting back to off...

Unless you have drift detection on, the stack has no way of knowing that you flipped MFA on, so re-running the stack with it set to "off" shouldn't do anything because the stack won't know there's anything to update for the MFA setting. Figuring this out when they launched Drift Detection was a massive help to solving the "people are manually changing stuff" problem over here haha.

Also, just to chime in on the topic at hand, as of today this is 100% still an issue in Cloudformation, so I'd imagine it's still plaguing the CDK as well since I think the CDK synths CFN for the resource generation. Hopefully this is fixed soon, because UGH this is dumb.

**Comment by ChrisSargent** [comment] 2021-05-21 08:11
> Unless you have drift detection on, the stack has no way of knowing that you flipped MFA on, so re-running the stack with MFA set to "off" shouldn't do anything because the stack won't know there's anything to update for the MFA setting. Figuring this out when they launched Drift Detection was a massive help to solving the "people are manually changing stuff" problem over here haha.

Right, yeah, makes sense.

**Comment by drawde111** [comment] 2021-07-06 03:55
Also experiencing this issue with cdk when mfa is required. 
Any update on this?

**Comment by wmarcuse** [comment] 2021-08-13 14:54
The SMS configuration correlates to the auto verification service Cognito provides, if this verification method is set on `phone_number` then SMS configuration is required.

>  Default: - If signInAlias includes email and/or phone, they will be included in autoVerifiedAttributes by default. If absent, no attributes will be auto-verified.

So make sure you don't have auto verify enabled for phone number and MFA required with only otp enabled should work.

**Comment by jumic** [comment] 2022-01-21 21:04
The CloudFormation issue `SMS configuration and Auto verification for phone_number are required when MFA is required/optional` was resolved, see https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/769.

I was able to deploy the examples from the original issue (`sms` set to `true` and `false`) and from the [replies](https://github.com/aws/aws-cdk/issues/11478#issuecomment-830104847).

@corymhall Should we close this issue and open a new one, if there is another specific problem?

**Comment by corymhall** [comment] 2022-01-24 13:29
@jumic thanks for letting me know! I'll close this issue for now since the issue looks to be resolved, but if anyone thinks the issue is not resolved let me know.

**Closed by corymhall** 2022-01-24 13:29 UTC
Labels: bug, @aws-cdk/aws-cognito, needs-cfn, blocked

**Comment by welljj** [comment] 2023-07-27 17:41
> @jumic thanks for letting me know! I'll close this issue for now since the issue looks to be resolved, but if anyone thinks the issue is not resolved let me know.

@corymhall I'm still having similar issues in CDK:

Here's my code:

Scenario 1
```python
import aws_cdk.aws_cognito as cognito
from aws_cdk import Stack, RemovalPolicy, Duration
from constructs import Construct


class AuthStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        user_pool = cognito.UserPool(
            self,
            "userpool",
            account_recovery=cognito.AccountRecovery.EMAIL_AND_PHONE_WITHOUT_MFA,
            auto_verify=cognito.AutoVerifiedAttrs(email=False, phone=True),
            mfa=cognito.Mfa.REQUIRED,
            mfa_second_factor=cognito.MfaSecondFactor(otp=True, sms=True),
            removal_policy=RemovalPolicy.DESTROY,
            self_sign_up_enabled=True,
            sign_in_aliases=cognito.SignInAliases(
                email=False, phone=True, username=False, preferred_username=False
            ),
        )
```

But this gives me the error: `Invalid account recovery setting parameter. Account Recovery Setting cannot use verified_phone_number as a recovery mechanism when SMS MFA is configured.`

Furthermore, if I change this to

Scenario 2
```python
mfa_second_factor=cognito.MfaSecondFactor(otp=True, sms=False),
```

I get the following error: `Can't turn off SMS_MFA when SMS configuration is set for the user pool with a required or optional MFAConfiguration.`

As I understand it, both of these scenarios are possible using the AWS Console, but CDK is throwing errors for them.

Scenario 1: My best guess here is that CloudFormation templates only allow setting a Priority for each Account Recovery Method, but no way to apply logic so that it won't use the Phone when SMS MFA is utilized, as both the CDK documentation and Console describe.

Scenario 2: I don't know why SMS_MFA cannot be disabled, since it's an option in the Console, and CDK provides the ability to disable it.

The easiest fix here to get this deploying without errors is using Scenario 1, except changing to 
```python
account_recovery=cognito.AccountRecovery.EMAIL_ONLY,
```
Since Scenario 2 with this change still gives the same error.
