### ISSUE TITLE
RuntimeError: Cannot find module '@aws-cdk/cx-api' but it's installed

### ISSUE THREAD

**Issue by UriZafrir** [aws/aws-cdk#30088] opened 2024-05-07 11:52 UTC
### Describe the bug

Hi
I'm using cdk 2.140.0 (build 46168aa) with python.
in my requirements i have
aws-cdk-lib==2.139.1
constructs>=10.0.0,<11.0.0

after 
pip install -r requirements.txt

when i do 
cdk synth

 i get:
```
$ cdk synth
jsii.errors.JavaScriptError:
  Error: Cannot find module '@aws-cdk/cx-api'
  Require stack:
  - /tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/cfn-resource.js
  - /tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/tag-aspect.js
  - /tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/index.js
  - /tmp/jsii-kernel-rLzub6
      at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
      at Module._load (node:internal/modules/cjs/loader:984:27)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:179:18)
      at Object.<anonymous> (/tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/cfn-resource.js:3:15)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12)
      at Module.require (node:internal/modules/cjs/loader:1231:19)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uri/general/python-cdk/app.py", line 4, in <module>
    import aws_cdk as cdk
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/aws_cdk/__init__.py", line 34089, in <module>
    from . import aws_apigateway
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1819, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 250, in <module>
    from ..aws_cloudwatch import (
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 12, in <module>
    import aws_cdk.aws_iam
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/aws_cdk/aws_iam/__init__.py", line 12, in <module>
    import aws_cdk.cdk
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/aws_cdk/cdk/__init__.py", line 13, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load("@aws-cdk/cdk", "0.28.0", __name__, "cdk@0.28.0.jsii.tgz")
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/jsii/_runtime.py", line 55, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 299, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 354, in load
    return self._process.send(request, LoadResponse)
  File "/home/uri/general/python-cdk/.venv/lib/python3.10/site-packages/jsii/_kernel/providers/process.py", line 342, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Cannot find module '@aws-cdk/cx-api'
Require stack:
- /tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/cfn-resource.js
- /tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/tag-aspect.js
- /tmp/jsii-kernel-rLzub6/node_modules/@aws-cdk/cdk/lib/index.js
- /tmp/jsii-kernel-rLzub6

Subprocess exited with error 1
```

when i list my installed packages it's installed:
```
pip list
Package                           Version
--------------------------------- -----------
attrs                             23.2.0
aws-cdk.asset-awscli-v1           2.2.202
aws-cdk.asset-kubectl-v20         2.1.2
aws-cdk.asset-node-proxy-agent-v6 2.0.3
aws-cdk.aws-cloudwatch            0.28.0
aws-cdk.aws-iam                   0.28.0
aws-cdk.cdk                       0.28.0
aws-cdk.cx-api                    0.28.0
aws-cdk-lib                       2.139.1
aws-cdk.region-info               0.28.0
cattrs                            23.2.3
constructs                        10.3.0
exceptiongroup                    1.2.1
importlib_resources               6.4.0
jsii                              1.98.0
pip                               22.0.2
publication                       0.0.3
python-dateutil                   2.9.0.post0
setuptools                        59.6.0
six                               1.16.0
typeguard                         2.13.3
typing_extensions                 4.11.0
```

### Expected Behavior

should work

### Current Behavior

not working

### Reproduction Steps

in my requirements.txt i have
aws-cdk-lib==2.139.1
constructs>=10.0.0,<11.0.0

after 
pip install -r requirements.txt

do 
cdk synth

### CDK CLI Version

2.140.0 (build 46168aa)

### Node.js Version

v20.12.2

### OS

windows 10

### Language

Python

**Comment by AlexGurtoff** [comment] 2024-05-07 12:11
It is a duplicate of https://github.com/aws/aws-cdk/issues/30067

**Comment by ashishdhingra** [comment] 2024-05-07 18:24
@UriZafrir Could you please share the sample code to reproduce the issue? OR, kindly confirm if your scenario same as mentioned in the issue https://github.com/aws/aws-cdk/issues/30067 per previous comment by @AlexGurtoff.

**Comment by UriZafrir** [comment] 2024-05-09 22:45
Hi, I think this is irrelevant, problem solved. 
I had a package that caused this. I deleted the virtual environment and it was solved. 
Sorry for the hassle.
best regards

**Closed** 2024-05-10 03:23 UTC
Labels: bug, @aws-cdk/aws-cloudwatch
