### ISSUE TITLE
(aws-batch): create fargate environment with Cfn classes

### ISSUE THREAD

**Issue by mazerte** [aws/aws-cdk#12329] opened 2021-01-04 14:06 UTC
Hello,

I got a lot of trouble to create a Fargate environment in AWS Batch with the CDK. The problem is only linked to a type issues. When you when to create a Fargate compute environment you shouldn't provide `instanceRole`, `instanceTypes` and `minvCpu` but the CDK enforce it.

### Reproduction Steps

```typescript
    const batchRole = new iam.Role(this, 'BatchRole', {
      assumedBy: new iam.ServicePrincipal('batch.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSBatchServiceRole')
      ],
    });

    const sg = new ec2.CfnSecurityGroup(this, 'ComputeEnvironmentSG', {
      vpcId: vpcId.valueAsString,
      groupDescription: 'Bust Tests Environment Security Group'
    })
    
    const computeEnvironment = new batch.CfnComputeEnvironment(this, 'ComputeEnvironment', {
      type: 'MANAGED',
      serviceRole: batchRole.roleArn,
      computeResources: {
        type: 'FARGATE_SPOT',
        subnets: subnets.valueAsList,
        maxvCpus: 256,
        securityGroupIds: [
          sg.ref
        ]
      }
    });
```

### What did you expect to happen?

I don't expect to see type errors

### What actually happened?

The CDK isn't able to compile the stack due to the errors

### Environment

  - **CDK CLI Version  :** 1.82
  - **Framework Version:**
  - **Node.js Version:** v12.19.0 
  - **OS               :** MacOS
  - **Language (Version):** TypeScript (3.8.3) (guessing all)

### Other

I try to fix the error locally by manually editing `@aws-cdk/aws-batch/lib/batch.generated.d.ts` by adding `?` to the concerned porperties and `@aws-cdk/aws-batch/lib/batch.generated.ts` by commenting the lines `errors.collect(cdk.propertyValidator('instanceRole', cdk.requiredValidator)(properties.instanceRole));` (and the others). After that everything work fine on CloudFormation side.

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2021-01-04 18:13
Closing as duplicate of https://github.com/aws/aws-cdk/issues/12028.

See https://github.com/aws/aws-cdk/issues/12028#issuecomment-745370833 for a workaround.

**Closed by iliapolo** 2021-01-04 18:13 UTC
Labels: @aws-cdk/aws-batch, bug, needs-triage
