### ISSUE TITLE
(aws-ssm): short issue description

### ISSUE THREAD

**Issue by jncheung** [aws/aws-cdk#14017] opened 2021-04-07 10:07 UTC
Return error during deploy when trying to retreive the latest ssm value for my lambda layer.

### Reproduction Steps
```              javascript
 layers: [ LayerVersion.fromLayerVersionAttributes(this, 'layer', { layerVersionArn: StringParameter.fromStringParameterAttributes(this, `GraphQLLayerArnFromSSM-${id}`, { simpleName: false, parameterName: `/${props.appName}/${props.denv}/layer/graphqllayerarn`, type : ParameterType.STRING }).stringValue }) ]
```

```
5:55:30 PM | UPDATE_FAILED        | AWS::CloudFormation::Stack | DLWUtilsPostStack-...estedStackResource
Template format error: Every Default member must be a string.
```

### What did you expect to happen?

resolved the latest ssm value for my lambda layer

### What actually happened?

Require ssm version number 

i can deploy cdk app if i provide a specific version number
``` javascript
layers: [ LayerVersion.fromLayerVersionAttributes(this, 'layer', { layerVersionArn: StringParameter.fromStringParameterAttributes(this, `GraphQLLayerArnFromSSM-${id}`, { version: 3, simpleName: false, parameterName: `/${props.appName}/${props.denv}/layer/graphqllayerarn`, type : ParameterType.STRING }).stringValue }) ]

```

### Environment

  - **CDK CLI Version  : 1.94.1**
  - **Framework Version:**
  - **Node.js Version:** v12.19.0
  - **OS               : mac 10.15.7**
  - **Language (Version):** typescript  4.0.5

### Other

--- 

This is :bug: Bug Report

**Comment by MrArnoldPalmer** [comment] 2021-04-07 18:21
This looks like a duplicate of https://github.com/aws/aws-cdk/issues/7722.

See if [this comment](https://github.com/aws/aws-cdk/issues/7722#issuecomment-680029258) related to clearing context gives you a workaround. This is something that we need to spend some time investigating and coming up with a solution for. Cloudformation has some non-straightforward support for parameters "latest" versioning and cdk context complicates that a bit.

Reopen if you think this a separate issue. Thanks!

**Closed by MrArnoldPalmer** 2021-04-07 18:21 UTC
Labels: @aws-cdk/aws-ssm, bug, needs-triage
