### ISSUE TITLE
Java: Listing Subnets of existing Vpc fails with exception

### ISSUE THREAD

**Issue by lohithsamaga** [aws/aws-cdk#6147] opened 2020-02-06 11:59 UTC
A Vpc object is created using lookup by passing vpc-id.

When I try to list the subnets by iterating through ISubnet list, it fails.

### Reproduction Steps
    	SelectedSubnets sulist = vpc.selectSubnets();
    	
    	sulist.getSubnets().forEach(su -> {
    		System.out.println(su.getSubnetId() + " == " + su.getAvailabilityZone());
    	});

### Error Log
```console
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project lcs-core-stack: An exception occured while executing the Java class. software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project lcs-core-stack: An exception occured while executing the Java class. software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet
```

### Environment

  - **CLI Version      : 1.22.0**
  - **Framework Version: 12.13.1**
  - **OS               : Windows 10**
  - **Language         : Java**

### Other

The same exception is thrown when iterating through vpc.getPrivateSubnets, etc., too.

--- 

This is :bug: Bug Report

**Comment by pkspks** [comment] 2020-02-09 22:36
Duplicate of #5279 ?

**Comment by rix0rrr** [comment] 2020-02-10 08:51
Yep, duplicate.

**Closed by rix0rrr** 2020-02-10 08:51 UTC
Labels: bug, language/java, package/vpc, status/needs-triage
