### ISSUE TITLE
Cannot use IAuthorizer to create an apigateway method

### ISSUE THREAD

**Issue by joemcclane85** [aws/aws-cdk#4532] opened 2019-10-16 06:30 UTC
Hello, 
I'm using python and this is my code:

```
auto_scaling_res=apigw_autoscaling.root.add_resource('autoscaling_update')
        get=auto_scaling_res.add_method('GET')

        auth=apigw.CfnAuthorizer(self,
        "authorizer",
        rest_api_id=apigw_autoscaling.rest_api_id,
        type="TOKEN",
        authorizer_uri="".join(["arn:aws:apigateway:",'eu-west-1',':lambda:path/2015-03-31/functions/',lamdbda_api_authorizer.function_arn,"/invocations"])
        )
 auto_scaling_res.add_method('POST', authorization_type=apigw.AuthorizationType.CUSTOM, authorizer=????)
```
How I can fill the **authorizer** paragraph? I didn't find an high level construct and the documentation is a little poor about it
Giuseppe

### Environment

  - **CLI Version      :** 13.1
  - **Framework Version:**
  - **OS               :** MacOS
  - **Language         :** python

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2019-10-16 08:41
You can never mix `CfnXxx` and non-`CfnXxx` classes, those are not designed to work together. In this case, you are mixing `RestApi` and `CfnAuthorizer`.

Duplicate of https://github.com/aws/aws-cdk/issues/1402, which contains a workaround (written in TypeScript but can be ported to Python by following this guide: https://docs.aws.amazon.com/cdk/latest/guide/multiple_languages.html)

Another solution would be to use the [escape hatch mechanism](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) to inject the ID of your `CfnAuthorizer` into the resource after the fact.

**Closed by rix0rrr** 2019-10-16 08:41 UTC
Labels: bug, status/needs-triage
