### ISSUE TITLE
AmplifyGraphqlApi: Validation error deploying AmplifyGraphqlApi CDK construct

### ISSUE THREAD

**Issue by AnilMaktala** [aws/aws-cdk#27526] opened 2023-10-12 20:13 UTC
### Describe the bug

I am following the walkthrough in the CDK construct announcement blog post found here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/. The only difference is I am deploying from a package in a pnpm monorepo, however, everything else is identical. During the cdk deploy logs I see the following error message:

Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*; Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1
    at Request.extractError (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:46430)
    at Request.callListeners (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90083)
    at Request.emit (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:89531)
    at Request.emit (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196289)
    at Request.transition (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:189841)
    at AcceptorStateMachine.runTo (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:154713)
    at C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:155043
    at Request.<anonymous> (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:190133)
    at Request.<anonymous> (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196364)
    at Request.callListeners (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-12T14:16:28.072Z,
  requestId: 'e828bd70-e9db-4173-8924-3dec501fccf6',
  statusCode: 400,
  retryable: false,
  retryDelay: 142.81362092100824
}
Following deploy, the generated resources appear to work correctly.

### Expected Behavior

No errors during cdk deploy

### Current Behavior

During the cdk deploy logs I see the following error message:

Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*; Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1
    at Request.extractError (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:46430)
    at Request.callListeners (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90083)
    at Request.emit (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:89531)
    at Request.emit (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196289)
    at Request.transition (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:189841)
    at AcceptorStateMachine.runTo (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:154713)
    at C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:155043
    at Request.<anonymous> (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:190133)
    at Request.<anonymous> (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:196364)
    at Request.callListeners (C:\...\AppData\Local\pnpm\global\5\.pnpm\aws-cdk@2.100.0\node_modules\aws-cdk\lib\index.js:362:90251) {
  code: 'ValidationError',
  time: 2023-10-12T14:16:28.072Z,
  requestId: 'e828bd70-e9db-4173-8924-3dec501fccf6',
  statusCode: 400,
  retryable: false,
  retryDelay: 142.81362092100824
}

### Reproduction Steps

Follow instructions found here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/

### CDK CLI Version

2.100.0

### Node.js Version

18.18.0

### OS

windows

### Language

TypeScript

**Comment by dpilch** [comment] 2023-10-12 21:17
To add some additional details. Sometimes the `PhysicalResourceId` of a StackEvent is an empty string. https://github.com/aws/aws-cdk/blob/b2200a8018205bab1699b9eb684d014376d7a14a/packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts#L257

This causes an `describeStackEvents` to be called with `{ stackName: '' }`. https://github.com/aws/aws-cdk/blob/b2200a8018205bab1699b9eb684d014376d7a14a/packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts#L232

**Comment by awudarowicz** [comment] 2023-10-14 05:51
I have similar issue and it looks that it is not the graphql api problem but something else.
I'm creating HttpApi with ApiGateway and I have the same error. I've tried everything.. changing ids, providing stackNames etc. Nothing helps.
The error occurs only when I'm creating nested stack. When I will cut out the `new ApiStack` then there is no error.
Here is the dumbest and shortest example I could prepare:

main.stack.ts
```
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { ApiStack } from "./api.stack";

export class MainStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new ApiStack(this, 'SuperTestApi');
  }
}
```

api.stack.ts
```
import {Construct} from "constructs";
import {NestedStack} from "aws-cdk-lib";

export class ApiStack extends NestedStack {
    constructor(scope: Construct, id: string) {
        super(scope, id);
    }
}
```

Currently in ApiStack the props are not set because they are optional and stackName should be taken from stack id.
Even if I provide `stackName` then error still exists:

```
Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
```

**Comment by eduborto** [comment] 2023-10-17 01:47
Same problem here with CDK code in Python.

Node 18.18.1
aws-cdk == 2.101.1

**Comment by pahud** [comment] 2023-10-20 18:44
Hi,

Can you help us verify if this still exists in the latest 2.102.0 ?

**Comment by dpilch** [comment] 2023-10-20 19:26
I am still seeing the issue in 2.102.0.

**Comment by eduborto** [comment] 2023-10-20 19:28
> Hi,
> 
> Can you help us verify if this still exists in the latest 2.102.0 ?
Hi @pahud,

It is still happening for me (I deployed two different solutions with the same error):
`Error occurred while monitoring stack: Error [ValidationError]: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*`

❯ npm -g ls aws-cdk
~/.nodenv/versions/18.18.1/lib
└── aws-cdk@2.102.0

**Comment by pahud** [comment] 2023-10-20 19:38
@eduborto Thanks for your prompt response. We'll review this internally.

**Comment by jonslo** [comment] 2023-10-25 12:28
<img width="953" alt="Screenshot 2023-10-25 at 7 27 26 AM" src="https://github.com/aws/aws-cdk/assets/13545408/8c16d407-8cac-4306-aaf9-77ea084770dd">
I am experiencing the same issue with nested stacks. Had this issue with 2.93.0 and 2.102.0.

**Comment by wmz7year** [comment] 2023-10-31 09:00
same issue with the 2.103.1 (build 3bb19ac) version

`
const cdk = require('aws-cdk-lib');
const eks = require('aws-cdk-lib/aws-eks');
const { KubectlV27Layer } = require('@aws-cdk/lambda-layer-kubectl-v27');


class Demo extends cdk.Stack {

  constructor(scope, id, props) {
    super(scope, id, props);

    const cluster = new eks.Cluster(this, 'eks', {
      version: eks.KubernetesVersion.V1_27,
      clusterName: 'demo-cluster',
      kubectlLayer: new KubectlV27Layer(this, 'kubectl'),
    });
  }

}
`

**Comment by pahud** [comment] 2024-04-17 17:16
As this issue is related to the blog post, I will reach out to the blog post authors for inputs.

@wmz7year your comment seems to be related to EKS instead of Amplify?

**Comment by pahud** [comment] 2024-04-23 20:46
```
Reproduction Steps
Follow instructions found here: https://aws.amazon.com/blogs/mobile/announcing-aws-amplifys-graphql-api-cdk-construct-deploy-real-time-graphql-api-and-data-stack-on-aws/
```

Hi @AnilMaktala

If this error only happens with the code provided by that blog post, I'd recommend cutting a ticket to https://github.com/aws-amplify/amplify-category-api for clarifying.

If you believe it's a general issue that exists in aws-cdk-lib, please provide a minimal code snippet in this issue so we can reproduce it on our end.

**Comment by dpilch** [comment] 2024-04-24 15:27
The issue did exist in aws-cdk-lib and was surfaced when using the Amplify GraphQL API L3 construct.

This issue was resolved with https://github.com/aws/aws-cdk/pull/27692. This issue can be closed now.

**Comment by pahud** [comment] 2024-08-07 17:57
Closing by https://github.com/aws/aws-cdk/pull/27692.

**Closed by pahud** 2024-08-07 17:57 UTC
Labels: bug, p2, investigating, @aws-cdk/aws-logs
