### ISSUE TITLE
[@aws-cdk/pipelines] Pipeline fails to deploy on PipelineArtifactsBucketEncryptionKey with custom toolkit bootstrap

### ISSUE THREAD

**Issue by aneeshrelan** [aws/aws-cdk#9747] opened 2020-08-16 12:47 UTC
I am trying to deploy a Pipelines stack to deliver a CDK app. This was bootstrapped using a custom toolkit name to not interfere with our other CDK projects running on the older version of bootstrapping using the following command:
```
cdk bootstrap --toolkit-stack-name cdk-pipeline-toolkit --qualifier demo-pipeline --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess aws://AWS_ACCOUNT_ID/AWS_REGION
```

The bootstrapping works just fine and doesn't interfere with any other (older versions) of CDK bootstrapping. However, when the very first `cdk deploy --toolkit-stack-name cdk-pipeline-toolkit` it fails with the below error:

```
Policy contains a statement with one or more invalid principals. (Service: AWSKMS; Status Code: 400; Error Code: MalformedPolicyDocumentException; Request ID: d2213b60-0def-46d4-8d90-be6a176a51de)
```

Also, to make it work, I had to figure out the usage of the `DefaultStackSynthesizer` for using the custom qualifier as follows:

```
import { App, DefaultStackSynthesizer } from "@aws-cdk/core";

import PipelineStack from "./stacks/PipelineStack";

const app = new App();

const synthesizer = new DefaultStackSynthesizer({ qualifier: "demo-pipeline" });

new PipelineStack(app, "DemoPipeline", {
    env: {
        account: "AWS_ACCOUNT_ID",
        region: "AWS_REGION"
    },
    synthesizer
});

app.synth();
```

Also, no cross accounts are involved, the pipeline is expected to be created in the same account and deploy the app in the same account too

### Reproduction Steps

1. Bootstrap using the newer bootstrap environment and a custom toolkit stack name
2. Add a `DefaultStackSynthesizer` with the same qualifier
3. Run `cdk deploy` with the ` --toolkit-stack-name` parameter

### What did you expect to happen?

The pipeline should get created and configured

### What actually happened?

Stack failed with the following error

```
Policy contains a statement with one or more invalid principals. (Service: AWSKMS; Status Code: 400; Error Code: MalformedPolicyDocumentException; Request ID: d2213b60-0def-46d4-8d90-be6a176a51de)
```

### Environment

  - **CLI Version      :** 1.59.0
  - **Framework Version:** 1.59.0
  - **Node.js Version:** v12.18.3
  - **OS               :** Linux Mint 19
  - **Language (Version):** TypeScript (3.8.3)

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-08-17 09:27
Duplicate of #9154

**Closed by rix0rrr** 2020-08-17 09:27 UTC
Labels: @aws-cdk/pipelines, bug, needs-triage
