### ISSUE TITLE
(aws-ec2): AWS::EC2::FlowLog is incorrectly considered taggable in some regions

### ISSUE THREAD

**Issue by tiefps** [aws/aws-cdk#15277] opened 2021-06-23 17:37 UTC
### The Question

Adding flowlogs to a VPC (`vpc.addFlowLog`) causes tags to be added to the `AWS::EC2::FlowLog` resource, however FlowLog doesn't support tags in the `us-iso-east-1 ` and `us-isob-east-1` regions.

> Error AWS::EC2::FlowLog Encountered unsupported property Tags

### Environment

  - **CDK CLI Version:** `1.109.0`
  - **Module Version:** `monocdk 1.109.0`
  - **Node.js Version:** `v14.17.1`
  - **OS:** `macOS Big Sur 11.4`
  - **Language (Version):** `TypeScript (v14.17.1)`

**Comment by peterwoodworth** [comment] 2021-06-24 23:47
I'm sorry for the experience here @tiefps,

It looks like the Tags property is set so that the flow log name can be set. 

I'm not familiar with the `-isob-` regions, but if the issue is that `AWS::EC2::FlowLog` doesn't support tags then that's a Cloudformation issue. You can submit an issue [here](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) if an issue for this doesn't exist already

**Comment by peterwoodworth** [comment] 2021-07-19 17:27
Closing due to staleness, ping me if you still need help with this

**Comment by tiefps** [comment] 2021-08-12 15:48
@njlynch - This issue should still be open as it is unresolved.

**Comment by peterwoodworth** [comment] 2021-08-12 16:22
Reopened and working with customer in DMs

**Comment by peterwoodworth** [comment] 2021-09-08 21:04
Closing in favor of #16373

**Comment by peterwoodworth** [comment] 2022-04-21 22:28
Reopening to potentially fix in our `region-info` package

**Comment by corymhall** [comment] 2022-08-08 17:03
I'm going to close this in favor of #16373. I think it makes more sense to try and solve this issue in a way that would apply to all resources and not address a single one at a time.

In general the solution to these type of things is to handle it in your CDK app. For tags that would mean filtering out certain resource types.

```ts
Tags.of(this).add('Key', 'Value', { excludeResourceTypes: ['AWS::EC2::FlowLog'] });
```

**Closed by corymhall** 2022-08-08 17:03 UTC
Labels: bug, p1, @aws-cdk/aws-ec2, effort/small, @aws-cdk/region-info
