### ISSUE TITLE
(lambda): Uploaded file must be a non-empty zip

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#12667] opened 2021-01-22 14:26 UTC
For hours I'm trying to get a lambda working without success. Always getting CFN message: "Uploaded file must be a non-empty zip". Doesn't matter if I try with Inline Code or as asset dir. Now I've downgraded to 1.70.0 and my code works fine. 

### Reproduction Steps

```typescript
import {App, Arn, Duration, RemovalPolicy, Stack, StackProps, Tags} from '@aws-cdk/core'
import {ARecord, HostedZone, RecordTarget} from '@aws-cdk/aws-route53'
import {Function, InlineCode, Runtime} from '@aws-cdk/aws-lambda'
import {Cors, HttpIntegration, LambdaIntegration, RestApi} from '@aws-cdk/aws-apigateway'
import {Bucket, BucketAccessControl} from '@aws-cdk/aws-s3'
import {BucketDeployment, Source} from '@aws-cdk/aws-s3-deployment'
import {ApiGateway} from '@aws-cdk/aws-route53-targets'
import {Certificate, DnsValidatedCertificate} from '@aws-cdk/aws-certificatemanager'
import * as fs from 'fs';

export class TimeStack extends Stack {
    constructor(scope: App, id: string, props?: StackProps) {
        super(scope, id, props)

        const fn = new Function(this, 'Function', {
            code: new InlineCode(fs.readFileSync('app/lambda/time.py', {encoding: 'utf-8'})),
            handler: 'index.main',
            runtime: Runtime.PYTHON_3_6,
        })

        // same issue
        //const fn = new Function(this, 'Function', {
        //    runtime: Runtime.PYTHON_3_6,
        //    code: AssetCode.fromAsset('app/lambda/'),
        //    handler: 'index.main',
        //})
    }
}
```
### What did you expect to happen?

A working stack.

### What actually happened?

CDK is successfully publishing the zip to s3 and I can find my file in it. But CFN reports: "Uploaded file must be a non-empty zip" for this lambda function.

### Environment

  - **CDK CLI Version  :** 1.86.0
  - **Framework Version:** 1.86.0
  - **Node.js Version:** v15.6.0
  - **OS               :** osx Catalina
  - **Language (Version):** TypeScript

### Other

The same code works with 1.70.0

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment] 2021-01-22 20:55
We are on it, duplicate of https://github.com/aws/aws-cdk/issues/12536

**Closed by NetaNir** 2021-01-22 20:55 UTC
Labels: @aws-cdk/aws-lambda, bug, needs-triage
