### ISSUE TITLE
(core): allow synthesizing a CFN template as an asset (without necessarily deploying it)

### ISSUE THREAD

**Issue by wulfmann** [aws/aws-cdk#12249] opened 2020-12-28 14:53 UTC
I would like to be able to synthesize and publish cloudformation stack assets without actually creating (deploying) the stack.

### Use Case

When using features like [Modules](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-moduleversion.html#cfn-cloudformation-moduleversion-modulepackage) or [StackSets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html#cfn-cloudformation-stackset-templateurl), you need to provide an s3 url for the template you want to use.

In order to make these features simpler to use with CDK, i'd like the add a cli/configuration/stack option to **not** actually create the stack on deployment. There may be a simpler way to do this, but i'd like the following experience:

- I create a stack (stack1) that contains my module/stackset template.
- I create another stack (stack2) that accepts stack1 as a parameter. I can then use this stack to build the asset / get other properties i may need for the stackset/module.
- I run the `cdk deploy` command and both stack1 and stack2 are synthesized / published to s3, but only stack2 is created/updated.

### Proposed Solution

Ideas:

- Property on the `core.Stack` class: `deploy: false`.

### Other

Current workaround:

Maintain 2 separate `core.App` files. One that is "deployed" and one that is not. The "deployed" app stacks expect that app1 is synthesized first, and then it uses the filesystem to fetch the corresponding templates.

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by wulfmann** [comment] 2020-12-28 14:53
I poked around a little bit to check if this is a duplicate, but didn't notice anything immediately. Feel free to close if it is.

**Comment by rix0rrr** [comment] 2021-02-08 14:59
This is an interesting request. I feel there's probably a generalization to be made between `Stack`, `NestedStack` and what you're asking for. Something like a `CfnTemplate` or something.

For example, passing a `Stack` to a `Module` doesn't feel quite right.

Seems like a useful feature for the use cases you indicated.

**Comment by rix0rrr** [comment] 2021-03-11 14:45
Probably also related to #11896

**Comment by wulfmann** [comment] 2021-03-12 18:36
> Probably also related to #11896

Yea 100% this is a use-case for my original issue. Would love to see this get traction!

**Comment by fitzoh** [comment] 2022-06-17 16:43
>If you want to keep this issue open, please leave a comment below

Yes please, I want this for stack sets specifically

**Comment by comcalvi** [comment] 2023-01-25 22:28
Closing this as a duplicate of #11896, which is linked to the StackSets L2 RFC.

**Closed by comcalvi** 2023-01-25 22:28 UTC
Labels: p1, @aws-cdk/core, feature-request, effort/medium
