### ISSUE TITLE
[module] using imported secret fails to use arn on rds proxy

### ISSUE THREAD

**Issue by amwill04** [aws/aws-cdk#11117] opened 2020-10-26 14:53 UTC
When using `Secret.fromSecretName` to use existing secret within the `RDS` `addProxy` it fails to set the correct `arn` within the `"Auth"` proprties leading to a `cloudformation` error

### Reproduction Steps

```typescript
import { Stack, Duration, Construct, StackProps, RemovalPolicy } from '@aws-cdk/core';
import {
  Credentials,
  DatabaseInstance,
  DatabaseInstanceEngine,
  OptionGroup,
  ParameterGroup,
  PerformanceInsightRetention,
  PostgresEngineVersion,
  StorageType,
  SubnetGroup,
} from '@aws-cdk/aws-rds';
import { InstanceClass, InstanceSize, InstanceType, ISecurityGroup, IVpc, SubnetType, Vpc } from '@aws-cdk/aws-ec2';
import { Secret } from '@aws-cdk/aws-secretsmanager'

export class TestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const password = new Secret(this, 'RDSAdminPassword', {
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: 'admin' }),
        generateStringKey: 'password',
        excludeCharacters: `/@" '`,
      },
    }).secretValueFromJson('password');

    const vpc = Vpc.fromVpcAttributes(this, 'FooVPC', { availabilityZones: ['eu-west-2'], vpcId: 'foo-vpc', privateSubnetIds: ['foo'] });

    const rds = new DatabaseInstance(this, 'RDS', {
      allocatedStorage: 20,
      autoMinorVersionUpgrade: true,
      backupRetention: Duration.days(28),
      copyTagsToSnapshot: true,
      credentials: Credentials.fromUsername('admin', {
        password,
      }),
      databaseName: 'foo',
      deleteAutomatedBackups: false,
      deletionProtection: true,
      enablePerformanceInsights: true,
      engine: DatabaseInstanceEngine.postgres({ version: PostgresEngineVersion.VER_11_8 }),
      iamAuthentication: true,
      instanceIdentifier: 'foo',
      instanceType: InstanceType.of(InstanceClass.T3, InstanceSize.SMALL),
      maxAllocatedStorage: 1000,
      monitoringInterval: Duration.seconds(60),
      multiAz: true,
      performanceInsightRetention: PerformanceInsightRetention.DEFAULT,
      removalPolicy: RemovalPolicy.RETAIN,
      storageEncrypted: true,
      storageType: StorageType.GP2,
      vpc: vpc,
    });

    const fooSecret = new Secret(this, 'FooSecret', {
      secretName: 'foo'
    })

    const importedFooSecret = Secret.fromSecretName(this, 'ImportedFoo', 'importedFoo')

    rds.addProxy('FooProxy', {
      borrowTimeout: Duration.seconds(30),
      dbProxyName: `foo-proxy`,
      debugLogging: false,
      iamAuth: false,
      idleClientTimeout: Duration.minutes(5),
      maxConnectionsPercent: 50,
      maxIdleConnectionsPercent: 50,
      requireTLS: false,
      secrets: [fooSecret, importedFooSecret],
      vpc,
    })
    // The code that defines your stack goes here
  }
}

```

### What did you expect to happen?

corretly format the arn for the imported secret on the proxy `auth` property

### What actually happened?

uses the `secret name` as the arn

```json
{
    "RDSFooProxy5446BF9F": {
      "Type": "AWS::RDS::DBProxy",
      "Properties": {
        "Auth": [
          {
            "AuthScheme": "SECRETS",
            "IAMAuth": "DISABLED",
            "SecretArn": {
              "Ref": "FooSecretB03CA68B"
            }
          },
          {
            "AuthScheme": "SECRETS",
            "IAMAuth": "DISABLED",
            "SecretArn": "importedFoo"
          }
        ],
        "DBProxyName": "foo-proxy",
        "EngineFamily": "POSTGRESQL",
        "RoleArn": {
          "Fn::GetAtt": [
            "RDSFooProxyIAMRoleD1F0AD32",
            "Arn"
          ]
        },
        "VpcSubnetIds": [
          "foo"
        ],
        "DebugLogging": false,
        "IdleClientTimeout": 300,
        "RequireTLS": false
      },
      "Metadata": {
        "aws:cdk:path": "TestStack/RDS/FooProxy/Resource"
      }
    },
}
```

this then fails the `cloudformation` regex check on `arns`

### Environment

  - **CLI Version      :*1.70.0*
  - **Framework Version:*1.70.0*
  - **Node.js Version:*14.13.1* 
  - **OS               :*macos*
  - **Language (Version):*typescript* 

This is :bug: Bug Report

**Comment by amwill04** [comment] 2020-10-26 15:04
This seems to be the issue - the secret arn is being set as the name. It has an override method for policies but that then fails for something like `rds proxy` with directly calls the `.secretArn` property

https://github.com/aws/aws-cdk/blob/575e47e4d6e8b89b4402ddc4b7bdea985b1e6edf/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L281-L298

https://github.com/aws/aws-cdk/blob/575e47e4d6e8b89b4402ddc4b7bdea985b1e6edf/packages/%40aws-cdk/aws-rds/lib/proxy.ts#L390-L397

**Comment by skinny85** [comment] 2020-10-26 16:45
> Looking at this - I dont think its a bug as `secrets arn` has a random 6 character string appended. Which I am assuming cant be found without a `fromLookup` method

Or with `fromSecretArn` 🙂

**Comment by njlynch** [comment] 2020-10-26 17:00
@amwill04  - This sounds like a duplicate of #10519 .

Do you happen to have the exact error message handy for the validation that fails? I'm curious if RDS will support the ARN without the 6-character suffix on it or not; the error message might indicate that, or might lead me to the code that tells me that. :)

**Comment by amwill04** [comment] 2020-10-26 21:23
@skinny85 - was tring to use the friendly name rather than having to pass in the `arn` with the random 6 characters. I ended up using `aws-sdk` to use `getSecertValue` that accepts the user friendly name and return the `arn` with the random characters.

@njlynch - sorry didnt see that as was searching for `proxy` on here rather than more general `secretsmanager` . The error is a `cloudformation` error regarding an `arn` must satisfy the regex. So you dont get the feed back that your code will fail until you deploy.

**Comment by njlynch** [comment] 2020-11-02 13:07
Closing as duplicate of #10519

**Closed by njlynch** 2020-11-02 13:07 UTC
Labels: @aws-cdk/aws-secretsmanager, guidance
