### ISSUE TITLE
metrics_collection support in aws_cdk.aws_autoscaling.AutoScalingGroup

### ISSUE THREAD

**Issue by huangzbaws** [aws/aws-cdk#7116] opened 2020-04-01 12:16 UTC
Currently there is no metrics_collection in aws_cdk.aws_autoscaling.AutoScalingGroup
It is only supported by low level API: aws_cdk.aws_autoscaling.CfnAutoScalingGroup

### Use Case
Collect metrics of Autoscaling Group In-service Instances, Desired Instances and etc.
Just like the metrics_collection in aws_cdk.aws_autoscaling.CfnAutoScalingGroup

### Proposed Solution
Support metrics_collection in aws_cdk.aws_autoscaling.AutoScalingGroup

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment] 2020-04-05 02:43
Hi! 
Good news! We have a PR to add metricscollections: https://github.com/aws/aws-cdk/pull/6712, currently under review.

**Comment by NetaNir** [comment] 2020-04-19 07:33
closing as duplicate of https://github.com/aws/aws-cdk/issues/6453

**Closed by NetaNir** 2020-04-19 07:33 UTC
Labels: feature-request, in-progress, needs-triage, package/autoscaling
