### ISSUE TITLE
Enable health checks for ELB lambda target

### ISSUE THREAD

**Issue by arturalbov** [aws/aws-cdk#5523] opened 2019-12-23 10:29 UTC
Health checks for lambda targets are disabled by default according to [AWS::ElasticLoadBalancingV2::TargetGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-healthcheckenabled) cfn resource reference. They're not enabled by attaching `aws_elasticloadbalancingv2.HealthCheck` resource to my lambda target group. And there is no `HealthCheckEnabled` property in  `aws_elasticloadbalancingv2.HealthCheck` resource.

### Use Case

I configuring health check
```
my_health_check = HealthCheck(
            healthy_http_codes="200",
            healthy_threshold_count=5,
            interval=Duration.seconds(30),
            path="/",
            timeout=Duration.seconds(5),
            unhealthy_threshold_count=2,
        )
```
and then attaching it to my lambda target group
```
my_lambda_target = LambdaTarget(my_lambda_function)

my_alb_listener.add_targets(
            "my-alb-listener-targets",
            target_group_name="my-target-group",
            targets=[my_lambda_target],
            path_pattern="/my", priority=0,
            health_check=my_health_check
        )
```
I want health check for this target group be enabled.

### Proposed Solution

There are two ways to implement this:
1. Add a new property called `health_check_enabled` to `aws_elasticloadbalancingv2.HealthCheck`.
2. Enable health check by default when attaching it to target group.
---

This is a :rocket: Feature Request

**Comment by njlynch** [comment] 2020-09-14 11:18
Duplicate of #7023, which was released in CDK 1.32.0.

**Closed by njlynch** 2020-09-14 11:18 UTC
Labels: @aws-cdk/aws-elasticloadbalancing, effort/medium, feature-request, p1
