### ISSUE TITLE
(aws-cdk): "cdk bootstrap" to upgrade from v5 to v6 will fail because CICDPipelinePermissionsBoundaryArn cannot be deleted

### ISSUE THREAD

**Issue by mduecker** [aws/aws-cdk#15420] opened 2021-07-05 11:50 UTC
I've upgraded `aws-cdk` to 1.111.0 and then received the following error during deploy:
> This CDK deployment requires bootstrap stack version '6', found '5'. Please run 'cdk bootstrap'.

I've then tried to run `cdk bootstrap` for the profile where my CDK Pipelines are deployed, which fails with the following error on `CDKToolkit` stack:
> Export CICDPipelinePermissionsBoundaryArn cannot be deleted as it is in use by DNS-Pipeline and LandingPageStackPipeline

### Reproduction Steps

My environment is setup exactly as suggested by [aws-bootstrap-kit-examples](https://github.com/aws-samples/aws-bootstrap-kit-examples/tree/main/source)

Which is still on aws-cdk version `1.91.0`
To reproduce the bug please deploy these CDK stacks and then upgrade the project to the newest `aws-cdk` version (1.111.0) and try deploying a new CDK stack into the same account. It will tell you to upgrade bootstrap version from 5 to 6 by running `cdk boostrap`, which will fail because of a PermissionBoundary that's used in the existing stacks.

### What did you expect to happen?

I'm trying to deploy a new CDK Pipeline after upgrading aws-cdk to version 1.111.0
I would expect to fix the bootstrap v5 vs v6 issue by just running `cdk bootstrap`. Not being able to upgrade the bootstrap version in-place would be a big problem
* if it's a production stack, removing and re-creating it with all resources contained in it would not be an option

### What actually happened?

Trying to upgrade bootstrap version in an existing account fails with:
> Export CICDPipelinePermissionsBoundaryArn cannot be deleted as it is in use by DNS-Pipeline and LandingPageStackPipeline

### Environment

  - **CDK CLI Version  :** 1.111.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by flochaz** [comment] 2021-07-06 14:49
The issue is on [aws-bootstrap-kit-examples](https://github.com/aws-samples/aws-bootstrap-kit-examples/tree/main/source). I think you can close this issue and create one on [aws-bootstrap-kit-examples](https://github.com/aws-samples/aws-bootstrap-kit-examples/tree/main/source)  repo. A fix should be out tomorrow.

**Comment by peterwoodworth** [comment] 2021-07-12 15:07
Hey @mduecker was the above response helpful?

**Comment by flochaz** [comment] 2021-07-19 08:29
Fixed by https://github.com/aws-samples/aws-bootstrap-kit-examples/pull/80 .

**Closed** 2021-07-21 16:03 UTC
Labels: guidance, response-requested
