### ISSUE TITLE
UserData - Add helper functions to create common commands

### ISSUE THREAD

**Issue by grbartel** [aws/aws-cdk#5911] opened 2020-01-22 18:51 UTC
The UserData objects in the aws-ec2 package are currently set up in a way that users have to create their full user data by hand.  While working with the CDK I have come across multiple repeated patterns that I believe will be beneficial to include as functions which build commands for you.

### Use Case

The main use cases that I have found so far are the need to:
* Send signals to cloud formation resources at the end of each UserData I create
* Download and execute files (normally scripts) from S3 usually in the form of assets.

### Proposed Solution

The implementation I am proposing for this feature is to add functions which build general commands.

An example function for the linux implementation of sending a cfnSignal could be 
```
public addCfnSignalResourceCommand( params: CfnSignalResourceCommandOptions ): void {

    const stack = Stack.of(params.resource);
    const resourceID = stack.getLogicalId(params.resource.node.defaultChild as CfnElement);

    this.addCommands(`/opt/aws/bin/cfn-signal --stack ${stack.stackName}` +
      ` --resource ${ resourceID }` +
      ` --success ${ params.success === undefined ? true : params.success }` +
      params.signalID ? ( " --id " + params.signalID ) : ""
    );
  }
```

Using this function users could easily signal that an instance is ready with code such as:

```
instance.userData.addCommands("do some setup stuff")
instance.userData.addCfnSignalResourceCommand( { instance } )
```

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2020-01-23 13:20
Duplicate of https://github.com/aws/aws-cdk/issues/623.

**Closed by rix0rrr** 2020-01-23 13:20 UTC
Labels: feature-request, package/ec2, status/needs-triage
