### ISSUE TITLE
[ec2] ec2.InterfaceVpcEndpoint not adding construct or resource tags

### ISSUE THREAD

**Issue by maclema** [aws/aws-cdk#9786] opened 2020-08-18 01:24 UTC
InterfaceVpcEndpoint does not add tags to the resource. Example below results in no tags being applied to the VPC endpoint.

### Reproduction Steps

```ts
const endpoint = new ec2.InterfaceVpcEndpoint(this, "Vpce", {
  service: props.service,
  vpc: this.vpc,
  subnets: this.subnets,
  securityGroups: [this.securityGroup]
})
cdk.Tag.add(endpoint, "MyTag", "MyValue")
```
### What did you expect to happen?

VPC endpoint get's tags applied to the construct it resides in or to the resource directly.

### What were you trying to achieve by performing the steps above?

Ensuring a ec2:DescribeNetworkInterfaces IAM policy statementcould be scoped to resources containing a specific tag.

### What actually happened?

No tags on VPC endpoint (or associated endpoint ENI's)

### Environment

  - CLI Version: 1.59.0
  - Framework Version: 1.59.0
  - Node.js Version: 14.8.0
  - OS: Mac (and CodeBuild using CDKPipelines)
  - Language (Version): TypeScript

**Comment by rix0rrr** [comment] 2020-08-18 07:45
Duplicate of #8463  (not strictly, but same root cause).

**Closed by rix0rrr** 2020-08-18 07:45 UTC
Labels: @aws-cdk/aws-ec2, bug, needs-triage
