### ISSUE TITLE
aws-iam: Calling grant methods with immutable role fails silently

### ISSUE THREAD

**Issue by willdady** [aws/aws-cdk#25952] opened 2023-06-13 05:25 UTC
### Describe the bug

Calling `grantEncryptDecrypt` on a KMS key when passing an immutable role fails silently. No errors or warning are shown during synthesis.

```typescript
    const myRole = iam.Role.fromRoleArn(
      this,
      "MyRole",
      "arn:aws:iam::999999999999:role/my-role",
      { mutable: false }
    );

    const myKey = new kms.Key(this, "MyKey");

    myKey.grantEncryptDecrypt(myRole); // This should be a build-time error as role is marked as immutable
```

### Expected Behavior

Calling a `grant*` methods with an immutable role should raise an error, or at a minimum a warning, during synthesis. It's unexpected behaviour that calling `grantEncryptDecrypt` has no effect if the role has `{ mutable: false }` set.

### Current Behavior

Calling `grantEncryptDecrypt` as shown in the snippet above has **no effect**. No IAM policy is created and no errors or warnings are emitted.

### Reproduction Steps

See above snippet.

### CDK CLI Version

2.79.1

### Node.js Version

18

### OS

MacOS

### Language

Typescript

**Comment by pahud** [comment] 2023-06-13 15:50
I think this is by design as described [here](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.FromRoleArnOptions.html#addgrantstoresources) but I agree we should print warning messages at least. I am making it a p2 feature request and we welcome pull requests.

**Comment by peterwoodworth** [comment] 2023-06-13 18:43
Thanks for reporting, closing as a duplicate of this https://github.com/aws/aws-cdk/issues/12188

**Closed by peterwoodworth** 2023-06-13 18:43 UTC
Labels: bug, duplicate, p2, feature-request, @aws-cdk/aws-iam, effort/medium
