### ISSUE TITLE
(cognito): SMS configuration and verification is required when OTP is chosen

### ISSUE THREAD

**Issue by heyarnold1** [aws/aws-cdk#12075] opened 2020-12-14 23:12 UTC
Cannot build a User Pool with MFA using OTP without phone number configuration and verification which is inconsistent with the console

### Reproduction Steps

```
mfa_second_factor = aws_cognito.MfaSecondFactor(otp=True, sms=False)

cognito_user_pool = aws_cognito.UserPool(
            self,
            "my-cognito-pool",
            account_recovery=aws_cognito.AccountRecovery.EMAIL_ONLY,
            auto_verify=auto_verify,
            enable_sms_role=False,
            mfa=aws_cognito.Mfa.REQUIRED,
            mfa_second_factor=mfa_second_factor,
            self_sign_up_enabled=True,
            sign_in_aliases=sign_in_aliases,
            sign_in_case_sensitive=False,
        )
```

### What did you expect to happen?

In the console I can create User Pool with the above configuration.  I would expect the same behaviour on the CDK

### What actually happened?
I got this error

`SMS configuration and Auto verification for phone_number are required when MFA is required/optional (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; R`

### Environment

  - CDK CLI Version  :1.78.0
  - Node.js Version:15.3.0
  - Language (Version): Python (3.8)

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2021-01-07 14:40
Duplicate of https://github.com/aws/aws-cdk/issues/11478

**Closed by nija-at** 2021-01-07 14:40 UTC
Labels: @aws-cdk/aws-cognito, bug, needs-triage
