### ISSUE TITLE
Create CfnDeliveryStream with new kinesis datastream ,role get  "not authorized to perform: kinesis:DescribeStream on resource error"

### ISSUE THREAD

**Issue by stevensu1977** [aws/aws-cdk#5221] opened 2019-11-27 16:23 UTC
Role arn:aws:iam::*:role/** is not authorized to perform: kinesis:DescribeStream on resource issue

I create new kinesis datastream and new role with policy ( I'm sure already give DescribeStream permission),where I create firehose delivery stream I get error. If I create role with same policy use web console , I can use this role arn in my code.

there have IAM or datastream eventually consistent issue ?

### Reproduction Steps

my code:

 ```ts
//get bucket or create bucket
    var bucket=s3.Bucket.fromBucketName(this,"s3Bucket","stevensu-cdk-bigdata-day")
    if (bucket.bucketArn==""){
      bucket=new s3.Bucket(this,"s3Bucket",{
        bucketName:"stevensu-cdk-bigdata-day"
      })
    }
    
    //create kinesis data stream
    const dataStream=new Stream(this,"dataStream",{shardCount:1,streamName:"stevensu_cdk_stream"})
    
    //create Role for firehose delivery stream    
    const firehoseRole=new iam.Role(this,"firehoseRole",{
      assumedBy:new iam.ServicePrincipal('firehose.amazonaws.com')    
    })
  
    //add s3 permission
    firehoseRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      resources: [bucket.bucketArn],
      actions: ['s3:AbortMultipartUpload', 's3:GetBucketLocation','s3:GetObject','s3:ListBucket','s3:ListBucketMultipartUploads','s3:PutObject'],
    }));
   
    //add kinesis permission
    firehoseRole.addToPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      resources: [dataStream.streamArn],
      actions: ['kinesis:DescribeStream', 'kinesis:GetShardIterator','kinesis:GetRecords'],
  }));


    //create firehose delivery stream
    var firehostDliverySteram=new firehose.CfnDeliveryStream(this,"stevensuFireHoseStream",
      {
        deliveryStreamName:"stevensu_cdk_firehose_stream",
        deliveryStreamType:"KinesisStreamAsSource",
        kinesisStreamSourceConfiguration:{
          kinesisStreamArn:dataStream.streamArn,
          roleArn:firehoseRole.roleArn
          //roleArn:"arn:aws:iam::9999999999:role/firehose_delivery_role"
          //roleArn:"arn:aws:iam::9999999999:role/Module2KinesisStack-firehoseRoleE5891AF8-14BJY2KFPNK3O"
        },
        s3DestinationConfiguration:{
          bucketArn:bucket.bucketArn,
          bufferingHints:{
            intervalInSeconds:60,
            sizeInMBs:5
          },
          compressionFormat:"GZIP",
          roleArn:firehoseRole.roleArn
        }
      }
      )
 }
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment] 2019-11-27 17:04
Hey @stevensu1977 ,

the issue is a missing dependency between the `DeliveryStream` and the `firehoseRole`'s default IAM policy. This works for me:

```ts
import { App, CfnResource, Construct, RemovalPolicy, Stack } from '@aws-cdk/core';
import iam = require('@aws-cdk/aws-iam');
import kinesis = require('@aws-cdk/aws-kinesis');
import firehose = require('@aws-cdk/aws-kinesisfirehose');
import s3 = require('@aws-cdk/aws-s3');

export class TestStack extends Stack {
    constructor(scope: Construct, id: string) {
        super(app, id);

        // get bucket or create bucket
        const bucket = new s3.Bucket(this, "s3Bucket", {
            // bucketName: "stevensu-cdk-bigdata-day"
            removalPolicy: RemovalPolicy.DESTROY,
        });

        // create kinesis data stream
        const dataStream = new kinesis.Stream(this, "dataStream", {
            shardCount: 1,
            streamName: "stevensu_cdk_stream",
        });

        // create Role for firehose delivery stream
        const firehoseRole = new iam.Role(this, "firehoseRole", {
            assumedBy: new iam.ServicePrincipal('firehose.amazonaws.com')
        });

        // add s3 permission
        firehoseRole.addToPolicy(new iam.PolicyStatement({
            effect: iam.Effect.ALLOW,
            resources: [bucket.bucketArn],
            actions: ['s3:AbortMultipartUpload', 's3:GetBucketLocation', 's3:GetObject', 's3:ListBucket', 's3:ListBucketMultipartUploads', 's3:PutObject'],
        }));

        const firehosePolicy = new iam.Policy(this, 'FirehosePolicy', {
            roles: [firehoseRole],
            statements: [
                new iam.PolicyStatement({
                    effect: iam.Effect.ALLOW,
                    resources: [dataStream.streamArn],
                    actions: ['kinesis:DescribeStream', 'kinesis:GetShardIterator', 'kinesis:GetRecords'],
                }),
            ],
        });

        // create firehose delivery stream
        const firehostDliverySteram = new firehose.CfnDeliveryStream(this, "stevensuFireHoseStream", {
            deliveryStreamName: "stevensu_cdk_firehose_stream",
            deliveryStreamType: "KinesisStreamAsSource",
            kinesisStreamSourceConfiguration: {
                kinesisStreamArn: dataStream.streamArn,
                roleArn: firehoseRole.roleArn,
                // roleArn:"arn:aws:iam::9999999999:role/firehose_delivery_role",
                // roleArn:"arn:aws:iam::9999999999:role/Module2KinesisStack-firehoseRoleE5891AF8-14BJY2KFPNK3O",
            },
            s3DestinationConfiguration: {
                bucketArn: bucket.bucketArn,
                bufferingHints: {
                    intervalInSeconds: 60,
                    sizeInMBs: 5,
                },
                compressionFormat: "GZIP",
                roleArn: firehoseRole.roleArn,
            },
        });
        firehostDliverySteram.addDependsOn(firehosePolicy.node.defaultChild as CfnResource);
    }
}
```

**Comment by stevensu1977** [comment] 2019-11-28 00:10
@skinny85  It's work , thanks a lot ,  :P  firehosePolicy.node.defaultChild  it's looks too long!!  :P

**Comment by skinny85** [comment] 2019-11-28 02:30
NP :). I'll be closing this one then, let me know if you need anything else from our side for this issue.

**Closed by skinny85** 2019-11-28 02:30 UTC
Labels: guidance, package/firehose, package/kinesis

**Comment by luketn** [comment] 2021-05-10 01:37
BTW an alternative to this that works for me is to use an inline policy on the delivery stream role:

```
const deliveryStreamRole = new Role(this, `${s3Destination.id}DeliveryStreamRole`, {
    assumedBy: new ServicePrincipal('firehose.amazonaws.com'),
    inlinePolicies: {
        'allow-s3-kinesis-logs': new PolicyDocument({
            statements: [
                new PolicyStatement({
                    effect: Effect.ALLOW,
                    actions: [
                        "kinesis:DescribeStream",
                        "kinesis:DescribeStreamSummary",
                        "kinesis:GetRecords",
                        "kinesis:GetShardIterator",
                        "kinesis:ListShards",
                        "kinesis:SubscribeToShard"
                    ],
                    resources: [stream.streamArn]
                }),
                new PolicyStatement({
                    effect: Effect.ALLOW,
                    actions: [
                        "s3:GetObject*",
                        "s3:GetBucket*",
                        "s3:List*",
                        "s3:DeleteObject*",
                        "s3:PutObject*",
                        "s3:Abort*"
                    ],
                    resources: [
                        bucket.bucketArn,
                        bucket.bucketArn + "/*"
                    ]
                }),
                new PolicyStatement({
                    effect: Effect.ALLOW,
                    actions: [
                        "logs:PutLogEvents"
                    ],
                    resources: [
                        logGroup.logGroupArn
                    ]
                })
            ]
        })
    }
});
```
