### ISSUE TITLE
sam.CfnApi usagePlan support

### ISSUE THREAD

**Issue by senioroman4uk** [aws/aws-cdk#8616] opened 2020-06-18 02:36 UTC
Extend CfnApi to enable usage of ApiGateway usage plans that is already available in cloudFormation according to https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html

But is not available in CDK construct according to https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-sam.CfnApi.AuthProperty.html
 

### Use Case

We are using cfn.Api to define api gateway and now have to implement usage plan for throttling 

### Proposed Solution

I would extend CfnApi.AuthProperty with missing properties from the spec  https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment] 2020-06-18 17:05
@senioroman4uk -

Thanks for your interest in contributing to the CDK. However, we don't manually implement anything in the SAM package. It's all autogenerated based on a SAM spec.

This feature is unavailable because the SAM spec we currently is out of date, and unfortunately there is no authoritative and up to date spec for SAM.

This is a duplicate of https://github.com/aws/aws-cdk/issues/7493.

Let me know if there's anything more you would like, or if I've missed anything.

**Comment by senioroman4uk** [comment] 2020-06-18 17:14
So do you have any plans on implementing #7493? Or you need help with it?

**Comment by nija-at** [comment] 2020-06-22 11:26
Unfortunately, I don't have a solution for how to fix #7493 yet. There is no machine readable spec that SAM publishes - https://github.com/awslabs/serverless-application-model/issues/1133. 

Do you have ideas on how we can do this? If you do, post them on the other issue and I'll be happy to see if they may work.

Closing this issue for now. Let's move this discussion there.

**Closed by nija-at** 2020-06-22 11:26 UTC
Labels: @aws-cdk/aws-sam, feature-request
