### ISSUE TITLE
[cli] cdk diff always reports diff if resource has non-ASCII characters

### ISSUE THREAD

**Issue by idm-ryou** [aws/aws-cdk#10523] opened 2020-09-25 01:34 UTC
`cdk diff` always reports diff if resource has non-ASCII characters.

### Reproduction Steps

```typescript
import * as cdk from "@aws-cdk/core";
import * as codebuild from "@aws-cdk/aws-codebuild";

const app = new cdk.App();
const stack = new cdk.Stack(app, "stack1");
new codebuild.Project(stack, "FooProject", {
  buildSpec: codebuild.BuildSpec.fromObject({
    version: "0.2",
    phases: {
      build: {
        commands: ["echo こんにちは"], // "Hello" in Japanese
      },
    },
  }),
});

```

```console
$ cdk --version
1.63.0 (build 7a68125)

$ cdk deploy stack1 --require-approval=never
stack1: deploying...
<snip>
 ✅  stack1

$ cdk diff stack1
Stack stack1
Resources
[~] AWS::CodeBuild::Project FooProject FooProject9FE653E4 
 └─ [~] Source
     └─ [~] .BuildSpec:
         ├─ [-] {
  "version": "0.2",
  "phases": {
    "build": {
      "commands": [
        "echo ?????"
      ]
    }
  }
}
         └─ [+] {
  "version": "0.2",
  "phases": {
    "build": {
      "commands": [
        "echo こんにちは"
      ]
    }
  }
}
```

### What did you expect to happen?

`cdk diff` reports no diff, when resources are in sync.

### What actually happened?

`cdk diff` always reports diff, even when resources are in sync.

### Environment

  - **CLI Version      :** 1.63.0
  - **Framework Version:** 1.63.0
  - **Node.js Version:** v12.18.4 
  - **OS               :** Linux (Docker container)
  - **Language (Version):** all (I guess...)

### Other

~~Guessing from its behavior, it seems like correct encoding(UTF-8?) is not specified while fetching current template from CloudFormation. So that the non-ASCII characters are converted to the "?" character and treated as if it is having diffs.~~

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-10-02 08:37
I don't believe it's possible to specify the encoding when retrieving a stack template. Is it?

**Comment by alicekaerast** [comment] 2021-02-22 12:15
This also appears to affect `SynthUtils.toCloudFormation` in `@aws-cdk/assert`, but I haven't looked at whether it is the same root cause.

**Comment by Amakata** [comment] 2022-06-01 08:31
> I don't believe it's possible to specify the encoding when retrieving a stack template. Is it?

I think  cloudformation template encoding is utf8.
but  I seem cloudformation API(aws cloudformation get-template) don't support utf8 string.
"aws cloudformation get-template" has no encoding option.

**Comment by peterwoodworth** [comment] 2022-06-21 20:56
If anyone is interested in this feature, I recommend opening an issue in [Cloudformation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues)

**Comment by idm-ryou** [comment] 2022-06-22 01:00
Done.
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1220

**Comment by peterwoodworth** [comment] 2023-06-09 00:50
Thanks all, closing in favor of #25309

**Closed by peterwoodworth** 2023-06-09 00:50 UTC
Labels: bug, p1, package/tools, effort/medium, needs-cfn, blocked
