### ISSUE TITLE
(dynamodb): deletion policy not applied to replicas from global tables

### ISSUE THREAD

**Issue by esiefkas** [aws/aws-cdk#20220] opened 2022-05-04 21:11 UTC
### Describe the bug

When provisioning a DynamoDB table with replication enabled, the removal policy is only applied to the primary table, not the replicas. 

### Expected Behavior

All tables (primary and replicas) should have the same removal policy applied.

### Current Behavior

Primary has the selected deletion policy applied, all replicas have the `DESTROY` deletion policy

### Reproduction Steps

```
const globalTable = new dynamodb.Table(this, 'Table', {
  partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
  replicationRegions: ['us-east-1', 'us-east-2', 'us-west-2'],
  billingMode: dynamodb.BillingMode.PROVISIONED,
  removalPolicy: RemovalPolicy.RETAIN,
});
```

### Possible Solution

This may be intended? If so what is the rationale?

### CDK CLI Version

1.152.0

### Node.js Version

16.13.0

### OS

OSX

### Language

Typescript

**Comment by peterwoodworth** [comment] 2022-05-04 22:27
This is similar to this issue https://github.com/aws/aws-cdk/issues/18582, in that we use custom resources to implement this instead of the CfnGlobalTable resource. That could potentially be a better choice here. The way CDK typically sets deletion policy is through the CfnResource [DeletionPolicy attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html), which resources created through custom resources can't make use of.

On a quick look through the docs [Adam linked](https://github.com/aws/aws-cdk/issues/18582#issuecomment-1018075852) related to the SDK call, I wasn't able to find anything related to deletion policy. Do you know of a way to do this with the SDK call we're using?

**Comment by skinny85** [comment] 2022-05-04 23:37
Thanks for opening the issue @esiefkas. This is a duplicate of https://github.com/aws/aws-cdk/issues/17011, so let's try to keep the conversation there 🙂.

Thanks,
Adam

**Closed by skinny85** 2022-05-04 23:37 UTC
Labels: p1, feature-request, @aws-cdk/aws-dynamodb, effort/medium, feature/coverage-gap
