### ISSUE TITLE
(aws-events-targets): Event Rule Targets do not apply to multiple Lambda Functions

### ISSUE THREAD

**Issue by stuartgraham** [aws/aws-cdk#12435] opened 2021-01-09 15:12 UTC
When applying Event Rules to multiple Lambda targets it only applies to one function. When you edit the rule in the console and update (without change), the rules apply the desired targets correctly.

### Reproduction Steps
- Target > 1 function in rule definition
- Deploy via CDK Pipeline
- Verify in Console that lambda_target_2 is missing an event source
- Edit Rule in EventBridge console
- Press Update
- Verify lambda_target_2 function now has an event source

```ts
events.Rule(self, "Every1Mins",
	schedule=events.Schedule.rate(core.Duration.minutes(1)),
	targets=[lambda_target_1, lambda_target_2]
)
```

### What did you expect to happen?
Event source to be deployed to all defined targets

### What actually happened?
As above, one 1 function receives the event source

### Environment

  - **CDK CLI Version**  : 1.83
  - **Framework Version**: 1.83
  - **Node.js Version**:  As per aws/codebuild/standard:4.0
  - **OS**               : As per aws/codebuild/standard:4.0
  - **Language (Version)**:  Python 3.8

### Other

--- 

This is :bug: Bug Report

**Comment by 0xfff0** [comment] 2021-03-08 22:38
Hello, is this a real bug? We just ran into the exact problem and couldn't find any help on this.

**Comment by AndyEfaa** [comment] 2021-03-16 10:31
I can confirm, we do have the same issue.
As a temp workaround, we created a new rule for each lambda.

**Comment by ssimono** [comment] 2021-04-27 13:24
Also ran into this.

>  As a temp workaround, we created a new rule for each lambda.

This works indeed

**Comment by ryparker** [comment] 2021-06-15 19:27
Hey @stuartgraham  :wave:

Thanks for opening this issue. This issue is marked as p1 which means it has been prioritized as important and should see attention soon, although please keep in mind that we have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

In the mean time it looks like a workaround was discovered for this by creating a new rule for each lambda. I understand that this is not ideal however we will do our best to get to a more permanent fix implemented.

**Comment by Jacco** [comment] 2022-05-15 06:48
I think this issue can be closed. I tried this out with CDK version 2.23, typescript.

The generated CloudFormation template only includes 2 Lambda, 2 Permissions, 2 Roles, 1 Rule (no EventSources). Evenything is deployed correctly and template resources also do not show any explicit EventSources deployed. 

My guess is that this used to be a problem with CloudFormation not with CDK.

Stack I used for testing:

```typescript
import { Stack, StackProps, Duration } from 'aws-cdk-lib';
import { Rule, Schedule } from 'aws-cdk-lib/aws-events';
import { LambdaFunction } from 'aws-cdk-lib/aws-events-targets';
import { Function, Runtime, Code } from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';
// import * as sqs from 'aws-cdk-lib/aws-sqs';

export class RuleTargetsStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const lambda1 = new Function(this, 'MyLambda1', {
      runtime: Runtime.NODEJS_14_X,
      code: Code.fromAsset('./lib/lambda'),
      handler: 'index.handler',
    });

    const lambda2 = new Function(this, 'MyLambda2', {
      runtime: Runtime.NODEJS_14_X,
      code: Code.fromAsset('./lib/lambda'),
      handler: 'index.handler',
    });

    const rule = new Rule(this, 'MyRule', {
      schedule: Schedule.rate(Duration.minutes(1)),
      targets: [
        new LambdaFunction(lambda1),
        new LambdaFunction(lambda2),
      ]
    });
  }
}
```

**Comment by corymhall** [comment] 2022-08-15 14:01
@Jacco thanks for testing this out! I'll go ahead and close this, but if anyone is still experiencing this issue let me know.

**Closed by corymhall** 2022-08-15 14:01 UTC
Labels: bug, p1, @aws-cdk/aws-lambda, effort/small, @aws-cdk/aws-events-targets
