### ISSUE TITLE
(custom-resources): singleton function runtime out of date

### ISSUE THREAD

**Issue by maclema** [aws/aws-cdk#20426] opened 2022-05-19 19:48 UTC
### Describe the bug

The AwsCustomResource construct uses an out-of-date Lambda runtime.

Line: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L373

### Expected Behavior

Should use latest NodeJS version.

### Current Behavior

Uses old Node JS version.

### Reproduction Steps

```typerscript
import * as cdk from "@aws-cdk/core";
import * as cr from "@aws-cdk/custom-resources";
import { Aspects } from "@aws-cdk/core";
import { AwsSolutionsChecks, NagSuppressions } from "cdk-nag";
// import * as sqs from '@aws-cdk/aws-sqs';

export class CrTestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const mycr = new cr.AwsCustomResource(this, "test", {
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
        resources: ["s3"]
      }),
      onCreate: {
        action: "PutObject",
        service: "s3",
        physicalResourceId: cr.PhysicalResourceId.of("hi")
      }
    });

    // FAILS cdk-nag
    Aspects.of(this).add(new AwsSolutionsChecks());
  }
}
```

### Possible Solution

Update runtime version.

### CDK CLI Version

1.156.1

### Node.js Version

v18.0.0

### OS

Mac

### Language

Typescript

**Comment by rix0rrr** [comment] 2022-05-25 15:51
Duplicate of https://github.com/aws/aws-cdk/issues/19992

**Closed by rix0rrr** 2022-05-25 15:51 UTC
Labels: bug, p1, effort/small, @aws-cdk/custom-resources
