### ISSUE TITLE
[lambda] CDK tries to add permission to an imported lambda in another account

### ISSUE THREAD

**Issue by johan-lindqvist** [aws/aws-cdk#11141] opened 2020-10-27 10:55 UTC
We have an API Gateway (LambdaRestApi) that uses an authorization lambda, in version 1.68.0 and above of the packages it tries to add a lambda:InvokeFunction permission in the account where the authorization lambda is. But the role we're deploying with has no access to that account. In versions below 1.68.0 it doesn't try to add this permission.

What I get when running `cdk diff` with v1.68.0 and above.
![image](https://user-images.githubusercontent.com/1523775/97291893-c9f73500-184a-11eb-92b2-fa6034c0d10b.png)

When I run `cdk diff` with v1.67.0 or below I get "There were no differences".
 
We get the authorization lambda using the `Function.FromFunctionArn`-method.

### Reproduction Steps

1. Create an API GW in one account using an authorization lambda that exists in a different account.
2. CDK tries to add permission in the account where the authorization lambda is.

### What did you expect to happen?

I expected it to work as in versions below 1.68.0, where CDK don't try to add resources in a different account.

### What actually happened?

CDK tries to add resources in the wrong account.

### Environment

  - **CLI Version      :1.70.0 (build c145314)**
  - **Framework Version: .NET Core 3.1**
  - **Node.js Version: v14.12.0** 
  - **OS               : Windows 10**
  - **Language (Version): .NET Core 3.1** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-10-30 14:07
Hey @johan-lindqvist,

Sorry to hear about this issue you're having.

We've made some changes recently to how lambda permissions work for imported lambdas - https://github.com/aws/aws-cdk/commit/99111f72adc210f48e269db50f2b8e8b78d21252 and https://github.com/aws/aws-cdk/commit/9bf8e13bd47608070b73221c11c55b09d03c0a4c. I'm afraid this may be the cause for your problem.

Can you provide the details on how you initialize your CDK stack? 
Specifically, if and how you configure [the CDK envrionment](https://docs.aws.amazon.com/cdk/latest/guide/environments.html). Do you set the `env` property or the CDK specific environment variables?

**Comment by johan-lindqvist** [comment] 2020-11-02 08:30
We don't set the `env` property. No special initialization stuff, we just run cdk deploy.

These are the settings in the cdk.json

```json
{
  "context": {
    "aws-cdk:enableDiffNoFail": "true",
    "identifier": "dev"
  },
  "app": "dotnet run -p <csharp csproj file>",
  "region": "eu-west-1"
}
```

**Comment by nija-at** [comment] 2020-11-09 12:43
I've posted a fix for this - https://github.com/aws/aws-cdk/pull/11369

**Closed** 2020-11-16 11:54 UTC
Labels: @aws-cdk/aws-lambda, bug, effort/small, p1
