### ISSUE TITLE
(aws-cdk-ecs): metricCpuUtilization never returns data

### ISSUE THREAD

**Issue by m90** [aws/aws-cdk#13769] opened 2021-03-24 15:05 UTC
### The Question

I'm trying to create a CPU Usage alert for an ECS cluster using the following code:

```js
    this.cpuUsageAlarm = new cloudwatch.Alarm(this, 'EcsCpuUsageAlarm', {
      alarmName: `some name`,
      metric: this.cluster.metricCpuUtilization(),
      threshold: 90
    })
```

The alarm gets created, but will never show data (i.e. "no data", not zero). When I use the Cloudwatch dashboard to view the cluster's CPU Usage, data is being displayed. I'm not sure if I use it incorrectly or if this a bug, but [the docs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs.Cluster.html#metricwbrcpuwbrutilizationprops) read like it should return something:

> This method returns the CloudWatch metric for this clusters CPU utilization.

For the sake of completeness, the cluster has `ContainerInsights` enabled:

```js
    this.cluster = new ecs.Cluster(this, 'EcsCluster', {
      clusterName: `cluster`,
      vpc: this.vpc,
      containerInsights: true
    })
```

Capacity is provisioned by Fargate using `ecsPatterns.ApplicationLoadBalancedFargateService`.

### Environment

  - **CDK CLI Version:** 1.94.1 
  - **Module Version:** 1.94.1 
  - **Node.js Version:** 14
  - **OS:** Ubuntu
  - **Language (Version):** JS

**Comment by peterwoodworth** [comment] 2021-07-08 23:50
Hey @m90, sorry for the long response time.

I can't seem to reproduce this, but I can think of a couple things that might be going wrong. I'm sure you're already doing this, but make sure you're using your cluster so that there's data to measure. Second, it may take a bit of time after deployment for the alarm to start measuring data.

If you're still running into this, could you share your `cdk synth` output for the alarm?

**Comment by m90** [comment] 2021-07-16 08:41
Thanks @peterwoodworth, to answer your question:

- the application does see load, so there certainly is data to measure
- a lot of time has passed since the deployment and it still does not display anything

This is the relevant portion of `cdk synth` as requested:

```yml
  BaseAgaveConstructAgaveEcsCpuUsageAlarmDE2F5F9C:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      AlarmDescription: CPU usage is very high on the application instance. Check if request volume is unusually high or if requests are stalling. If things look normal, consider scaling the cluster capacity.
      AlarmName: "Agave (shelflife/production): CPU usage above 90%"
      Dimensions:
        - Name: ClusterName
          Value:
            Ref: BaseAgaveConstructAgaveECSCluster17356C5A
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: 90
      TreatMissingData: notBreaching
    Metadata:
      aws:cdk:path: AgaveStack-shelflife/BaseAgaveConstruct/AgaveEcsCpuUsageAlarm/Resource
```

Don't know if it makes a difference, but the cluster itself has "Container Insights" enabled:

```yml
  BaseAgaveConstructAgaveECSCluster17356C5A:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: agave-shelflife-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
    Metadata:
      aws:cdk:path: AgaveStack-shelflife/BaseAgaveConstruct/AgaveECSCluster/Resource
```

**Comment by m90** [comment] 2021-07-19 20:05
So for the ECS Cluster my metrics will look like this (hovering over any datapoint shows `-`):

![image](https://user-images.githubusercontent.com/1662740/126220020-66c76dc9-c1c1-4067-b16f-5a953acdce86.png)

when I would expect something like this (which is from an idling EC2 - hovering will show sth like `0.321672`):

![image](https://user-images.githubusercontent.com/1662740/126220096-f0eeb7e7-4186-4c48-bc4d-5786ee78feb0.png)

**Comment by peterwoodworth** [comment] 2021-07-22 19:20
Hmm, if you're 100% certain that you're using your cluster then I don't think this is a CDK issue since your synth output is perfectly fine. I'm sorry about this

**Comment by m90** [comment] 2021-07-22 20:21
The cluster definitely is running as a. it's in use and b. other metrics like memory usage seem to work as expected.

Is this something we need to raise with AWS support then?

**Comment by peterwoodworth** [comment] 2021-07-27 18:15
@m90 did you receive any help?

**Comment by m90** [comment] 2021-07-29 07:42
I didn't get around to contacting them yet (we've been without this metric for a long time now ...). I'll post here once I have further info. Thanks.

**Comment by m90** [comment] 2021-08-02 08:14
Surprisingly, it turns out I cannot contact AWS support about this anymore as we've graduated out of Activate recently and are on a Basic support plan, so there's that. Since all non-production environments do work as intended using the same config I guess I will just wait for a good moment to recreate our production stack and see if it fixes that.

**Comment by peterwoodworth** [comment] 2021-08-02 16:18
Sorry again for the experience here. Please ping me once you're ready to revisit this issue :) Hopefully a recreation will work out since your non-prod environments work. I'll close this issue for now

**Closed by peterwoodworth** 2021-08-02 16:18 UTC
Labels: @aws-cdk/aws-ecs-patterns, guidance, response-requested
