### ISSUE TITLE
(cdk-core): CDK diff does not work with umlauts

### ISSUE THREAD

**Issue by Xarno** [aws/aws-cdk#25309] opened 2023-04-26 08:12 UTC
### Describe the bug

When doing a CDK diff it always detect a change in the tags because the „ü“ in this case results in a „?“. 
Although the Tags on the resource are correct including the umlaut as specified.

### Expected Behavior

Diff command should be capable to handle all allowed chars for tags.

### Current Behavior

[~] AWS::IAM::Role VirtualGuideiaaInstance/Cert/Certificate/CertificateRequestorFunction/ServiceRole VirtualGuideiaaInstanceCertCertificateCertificateRequestorFunctionServiceRole3B312417 
 └─ [~] Tags
     └─ @@ -5,7 +5,7 @@
        [ ] },
        [ ] {
        [ ]   "Key": "customer",
        [-]   "Value": "Messe M?nchen"
        [+]   "Value": "Messe München"
        [ ] },
        [ ] {
        [ ]   "Key": "environment",

### Reproduction Steps

const app = new App();
// ...
Tags.of(app).add("Ära", "München")

### CDK CLI Version

2.76.0 (build 78c411b)

### Framework Version

2.76.0

### Node.js Version

v16.17.0

### OS

Mac OS 13.3

### Language

Typescript

### Language Version

3.9.10

**Comment by rix0rrr** [comment] 2023-04-28 11:29
We can reproduce it but not fix it. This is a limitation of the `GetStackTemplate` API offered by CloudFormation, which does not support unicode.

**Comment by peterwoodworth** [comment] 2023-06-09 00:50
We've had multiple reports of this, making this the main thread

**Comment by DanielLaberge** [comment] 2023-06-14 19:33
Could someone from the CloudFormation API Team confirm whether or not there is any chance of getting this addressed?

The fact that UTF-8 Characters are supported by many AWS APIs, but are mangled by the CloudFormation GetStackTemplate API is not only inconsistent and confusing, but potentially dangerous.

I wonder how CloudFormation's team would feel about [the proposed solution to this issue which is currently being implemented in this PR](https://github.com/aws/aws-cdk/pull/25912#pullrequestreview-1476806470). On one hand, I'm grateful there might be a solution coming to "fix" CDK diff, but on the other hand, the solution is more akin to a band-aid since it can't be fixed on the CDK side.

@peterwoodworth: It looks like inter-team communication might be required for a proper fix, and it would be appreciated if someone that can make it happen chimed in.

**Closed** 2023-06-15 08:49 UTC
Labels: bug, p2, package/tools, effort/small, needs-cfn, blocked
