### ISSUE TITLE
EC2: Cross account VPC lookup dummy values

### ISSUE THREAD

**Issue by khan-a1** [aws/aws-cdk#17921] opened 2021-12-09 03:10 UTC
### What is the problem?

ec2.Vpc.fromLookup cross account lookup followed by vpc.selectSubnets results in TypeError: Cannot read properties of undefined (reading 'routeTable').

If I lookup the VPC alone without querying subnets and it completes the synth command and writes the vpc and subnet details in cdk.context.json and rerun the CDK app again this time with subnet lookups, it works fine

### Reproduction Steps

  const vpc = ec2.Vpc.fromLookup(this, 'testvpc', {
      vpcId: 'vpc-12345,
      isDefault: false
    });
const subnetFilter = ec2.SubnetFilter.byIds(['subnet-12345'])
const tempSubnet = vpc.selectSubnets({ subnetFilters: [subnetFilter] })

### What did you expect to happen?

VPC lookup to have the actual subnet details right after first call not needing to run vpc lookup first to write the information to cdk.context.json and only then be able to lookup subnets on the second run

### What actually happened?

Initial VPC lookup followed by subnet selection should work on the first attempt

### CDK CLI Version

1.134.0 (build dd5e12d)

### Node.js Version

v17.0.1

### OS

macOS Catalina 10.15.7

### Language

Typescript

### Language Version

4.4.3

**Comment by njlynch** [comment] 2021-12-30 15:11
Thanks for filing this bug. This looks -- to me -- to be a duplicate of https://github.com/aws/aws-cdk/issues/14066. The issue is the same: wanting to be able to do a fromLookup call and then immediately access the subnets/etc. I'm going to close this one in favor of #14066.

**Closed by njlynch** 2021-12-30 15:11 UTC
Labels: bug, p2, @aws-cdk/aws-ec2, needs-triage
