### ISSUE TITLE
[ec2] allow_to for IPv6 has no effect on connections

### ISSUE THREAD

**Issue by gergnz** [aws/aws-cdk#9017] opened 2020-07-11 05:32 UTC
Unable to allow all outbound/egress traffic for IPv6 on a connection class.

### Reproduction Steps
```
asg = asg.AutoScalingGroup(self, "asg",
                vpc=vpc,
                instance_type=ec2.InstanceType('t3a.nano'),            
                machine_image=ec2.MachineImage.latest_amazon_linux(generation=ec2.AmazonLinuxGeneration('AMAZON_LINUX_2')))

asg.connections.allow_to(ec2.Peer.any_ipv6(),ec2.Port.all_traffic())
```

### Error Log
No error is produced.

### Environment

  - **CLI Version: 1.51.0 (build 8c2d53c)
  - **Framework Version: aws-cdk.aws-ec2                    1.51.0
  - **Node.js Version: v12.8.0
  - **OS               : MacOS 10.15.5 (19F101)
  - **Language (Version): Python 3.7.7

### Other
Expected Result:
```
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          },
          {
            "CidrIp": "::/0",
            "IpProtocol": "-1"
          }
        ],
```

Actual Result:
```
        "SecurityGroupEgress": [
          {
            "CidrIp": "0.0.0.0/0",
            "Description": "Allow all outbound traffic by default",
            "IpProtocol": "-1"
          }
        ],
```

--- 

This is :bug: Bug Report

**Comment by NetaNir** [comment] 2020-07-15 06:19
The `SecurityGroupEgress` resource is created by the configuration set on the `AutoScalingGroup` default `SecurityGroup`, which is created when no `SecurityGroup` is provided to the `AutoScalingGroup` constructor. By default, all IPV4 traffic is allowed (we have an issue  https://github.com/aws/aws-cdk/issues/7094 to change the default behavior to allow IPV6 & IPV4 by default). You can set custom rules by providing a `SecurityGroup` to the `AutoScalingGroup`, on which you can configure custom behavior:

```ts
const mySecurityGroup = new ec2.SecurityGroup(this, 'SecurityGroup', {...});
securityGroup.addEgressRule(ec2.Peer.anyIpv6(), ec2.Port.allTraffic())

new autoscaling.AutoScalingGroup(this, 'ASG', {
  vpc,
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MICRO),
  machineImage: new ec2.AmazonLinuxImage(),
  securityGroup: mySecurityGroup,
});
```

**Comment by NetaNir** [comment] 2020-07-15 06:54
The `SecurityGroupEgress` resource is created by the configuration set on the `AutoScalingGroup` default `SecurityGroup`, which is created when no `SecurityGroup` is provided to the `AutoScalingGroup` constructor. By default, all IPV4 traffic is allowed (we have an issue  https://github.com/aws/aws-cdk/issues/7094 to change the default behavior to allow IPV6 & IPV4 by default). You can set custom rules by providing a `SecurityGroup` to the `AutoScalingGroup`:

```ts
const securityGroup = new ec2.SecurityGroup(stack, 'Resource-Security-Group', { vpc,
  allowAllOutbound: false
})
securityGroup.addEgressRule(Peer.anyIpv6(), Port.allTraffic())

new autoscaling.AutoScalingGroup(this, 'ASG', {
  vpc,
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.BURSTABLE2, ec2.InstanceSize.MICRO),
  machineImage: new ec2.AmazonLinuxImage(),
  securityGroup,
});
```

**Comment by NetaNir** [comment] 2020-07-16 17:53
Im closing this as duplicate of https://github.com/aws/aws-cdk/issues/7094 as it will prevent the need to actually add the "allow traffic from Ipv6"

**Closed** 2020-07-16 17:54 UTC
Labels: @aws-cdk/aws-ec2, guidance
