### ISSUE TITLE
S3 Bucket grant* stopped working in 1.20.0

### ISSUE THREAD

**Issue by jeshan** [aws/aws-cdk#5740] opened 2020-01-10 09:25 UTC
I've upgraded cdk (and aligned their modules as well) from 1.16.3(?) to 1.20.0 and I noticed that bucket policies that I created with the following stopped working
```javascript
myBucket.grantReadWrite(myRole, `*/${templatesPublic}/*`);
```

### Reproduction Steps

What I saw with `cdk diff` 1.20.0:
![image](https://user-images.githubusercontent.com/1020565/72141201-d7baf700-33ab-11ea-8bf4-e658d18b80e7.png)
![image](https://user-images.githubusercontent.com/1020565/72141217-dd184180-33ab-11ea-92cd-56ab3b56ccdd.png)

If I renamed the bucket, I'd get:
![image](https://user-images.githubusercontent.com/1020565/72141291-0507a500-33ac-11ea-847c-af760ad7b1ae.png)
_So, it suggests that it's broken for new and existing buckets as well._

It's not just the diff that was wrong; when I did `cdk deploy`, the bucket policy was actually gone.

Downgrading cdk (and the node modules) to 1.19.0:
I saw iam policies are back to what I had before:
![image](https://user-images.githubusercontent.com/1020565/72141379-308a8f80-33ac-11ea-88a4-27260a4a082a.png)
![image](https://user-images.githubusercontent.com/1020565/72141388-33858000-33ac-11ea-8734-91dafc9a1f5b.png)

### Environment

  - **CLI Version      :*1.20.0*
  - **Framework Version:**
  - **OS               :*Linux*
  - **Language         :*JavaScript*

I didn't spot any breaking change notice in the release notes at:
https://github.com/aws/aws-cdk/releases/tag/v1.20.0

--- 

This is :bug: Bug Report

**Comment by netroy** [comment] 2020-01-10 11:28
@jeshan is `myRole` imported with `Role.fromRoleArn`? 
if not, can you please share some more into on how `myRole` is created?

**Comment by jeshan** [comment] 2020-01-10 15:28
Sorry, I didn't realise that that was relevant. It is indeed created with fromRoleArn:

```javascript
Role.fromRoleArn(
            this,
            'deployment-account-role',
            `arn:aws:iam::123456789012:role/deployment-role`,
        );
```

and I'm creating the bucket with something like:
```javascript
this.publicBucket = new Bucket(this, 'bucket', {
            publicReadAccess: true,
            bucketName: 'my-public-bucket',
        });
```

**Comment by netroy** [comment] 2020-01-10 15:37
I believe the change that's causing this issue for you, landed in this PR https://github.com/aws/aws-cdk/pull/5568

**Comment by jeshan** [comment] 2020-01-10 15:40
OK. I'm trying with a newly created role just now (with 1.20) and I'm getting the same incorrect behaviour:

```javascript
let myRole = new Role(this, 'dep-role', {
            assumedBy: new ServicePrincipal('...'),
            managedPolicies: [
                ManagedPolicy.fromAwsManagedPolicyName(
                    '...',
                ),
            ],
        });
```

**Comment by netroy** [comment] 2020-01-10 15:47
For a new role, that's been the expected behaviour.
For imported roles, I'd recommend waiting for one of the repo owners to confirm if this is a regression or not.

**Comment by jeshan** [comment] 2020-01-10 15:49
> For a new role, that's been the expected behaviour.

I don't understand. Why would it be different for new v/s imported ones? How else would you reference a role in a bucket policy?

**Comment by rix0rrr** [comment] 2020-01-14 11:18
Normally you wouldn't add the permissions to the bucket but to the role.

Since this is an imported role we assume the permissions have already been added to the role and we don't add them to the bucket. On the other hand, this is an imported role from another account (seems like?), in which case the permissions need to be added to BOTH the resource and the role.

For the moment, you can work around this by using `bucket.addToResourcePolicy()` while we sort this out.

Sorry for the problems this has caused.

**Closed** 2020-08-19 21:45 UTC
Labels: @aws-cdk/aws-iam, @aws-cdk/aws-s3, bug, effort/medium, in-progress, p1
