### ISSUE TITLE
(ec2): software.amazon.awscdk.services.ec2.SubnetType enum does not have PRIVATE_WITH_NAT or PRIVATE_ISOATED

### ISSUE THREAD

**Issue by sarbajitdutta** [aws/aws-cdk#16443] opened 2021-09-09 19:52 UTC
## :question: General Issue
SubnetType `PRIVATE_WITH_NAT` does not exist with 1.22.0. It says `PRIVATE` is deprecated for SubnetType and to use `PRIVATE_WITH_NAT`. But the class does not have those enums. According to the latest javadocs - [javadoc](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/ec2/SubnetType.html)

### The Question

Include all the relevant enums for SubnetType
### Environment

  - **CDK CLI Version:** 1.22.0
  - **Module Version:** 1.22.0
  - **Node.js Version:** v16.4.2
  - **OS:** macOS
  - **Language (Version):** java

**Comment by njlynch** [comment] 2021-09-10 09:24
Thanks for the bug report, @sarbajitdutta !

This is an unfortunate known issue with the underlying software that powers CDK's multi-language support, `jsii`. At the moment, it doesn't support multiple enums with the same value, which is the case here with `PRIVATE`/`PRIVATE_WITH_NAT`. As the two are still functionality equivalent -- we merely did the deprecation and rename to improve clarity -- you can continue to use the `PRIVATE`/`ISOLATED` enums. I've left a comment on the linked issue tracking the root cause so we're tracking that this is another use case impacted by the bug.

**Comment by njlynch** [comment] 2021-11-29 12:39
It's worth noting that this issue has now been fixed for the V2 release of the CDK. The V2 version of the CDK now prefers the non-deprecated versions of the enums, and those can be used in favor of the deprecated ones.

**Comment by aarcro** [comment] 2022-07-15 19:54
In 2.27 `ISOLATED` worked,  I just updated to 2.32 and found that the name has changed to `PRIVATE_ISOLATED`. That was surprising and frustrating. Trying to build a shared internal library and doubt that every team wants to be constantly updating and playing whack-a-mole.

**Comment by TheRealAmazonKendra** [comment] 2023-01-27 02:28
The original issue was for v1, which is now in maintenance mode so we will not be making fixes on it. I'm going to go ahead and close this issue. If there is still an ongoing issue in v2 or you believe this was closed in error, please open a new issue.

**Closed by TheRealAmazonKendra** 2023-01-27 02:28 UTC
Labels: bug, p1, @aws-cdk/aws-ec2, effort/small, jsii
