### ISSUE TITLE
(aws-codepipeline-actions): CodeCommitSourceAction accepts repository from region X and creates role for region Y

### ISSUE THREAD

**Issue by cardosi** [aws/aws-cdk#13025] opened 2021-02-12 23:50 UTC
I have a pipeline that is replicated 3 times [Dev/QA/Prod]. I'm using the Python aws-cdk library, version 1.89.0. Here's an break down of where things are:

**Dev Pipeline:**
Account: 111111111111
Region: us-west-2

**QA Pipeline:**
Account: 111111111111
Region: us-west-1

**Prod Pipeline:**
Account: 222222222222
Region: us-west-2

**CodeCommit Repository**
Account: 111111111111
Region: us-west-2

### Reproduction Steps

**pipeline_stack.py**
```python3
import aws_cdk.aws_codepipeline as codepipeline
import aws_cdk.aws_codepipeline_actions as codepipeline_actions
import aws_cdk.aws_codecommit as codecommit
from aws_cdk.core import Stack, StackProps, Construct, Environment
from aws_cdk.pipelines import CdkPipeline, SimpleSynthAction

repo_arn = "arn:aws:codecommit:us-west-2:111111111111:backend"

classPipelineStack(Stack):
    def __init__(self, scope: Construct, id: str, app_stage: str = 'dev', **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        repo = codecommit.Repository.from_repository_arn(self, "backend-repository",
                  repo_arn)

        source_artifact_master = codepipeline.Artifact()
        cloud_assembly_artifact = codepipeline.Artifact()

        pipeline = CdkPipeline(self, "Pipeline",
            pipeline_name=f"{app_stage}-BackendPipeline",
            cloud_assembly_artifact=cloud_assembly_artifact,
            source_action=codepipeline_actions.CodeCommitSourceAction(
                 action_name="CodeCommit_Source",
                 branch='master',
                 repository=repo,
                 output=source_artifact_master),
            synth_action=SimpleSynthAction(
                source_artifact=source_artifact_master,
                cloud_assembly_artifact=cloud_assembly_artifact,
                install_commands=[
                    "npm install -g aws-cdk",
                    "npm update",
                    "python -m pip install -r requirements.txt"
                ],
                synth_command="cdk synth"
            )
        )
```

**app.py**
```python3
#!/usr/bin/env python3

from pipeline_stack import PipelineStack
from aws_cdk import core

app = core.App()

# AWS Accounts
nonprod = "111111111111"
prod = "222222222222"

# Application Environments
Development = core.Environment(account=nonprod, region="us-west-2")
QA = core.Environment(account=nonprod, region="us-west-1")
Production = core.Environment(account=prod, region="us-west-2")

# Development Pipeline
RmwPipelineStack(app, "dev-backend-pipeline",
    env=Development,
    app_stage='dev'
    )

# QA Pipeline
RmwPipelineStack(app, "qa-backend-pipeline-1",
    env=QA,
    app_stage='qa'
    )

# Production Pipeline
RmwPipelineStack(app, "prod-backend-pipeline",
    env=Production,
    app_stage='prod'
    )


app.synth()
```

### What did you expect to happen?
I expected `codepipeline_actions.CodeCommitSourceAction` to create an IAM role with the necessary permissions to access the CodeCommit repository that was passed.

### What actually happened?
A role was created with permission to access a CodeCommit repository of the same name in the region that the pipeline exists and not in the region in which the repository exists. The Source stage/CodeCommit Action in the pipeline had the following error:

> Insufficient permissions
> The service role or action role doesn’t have the permissions required to access the AWS CodeCommit repository named backend. Update the IAM role permissions, and then try again. Error: User: arn:aws:sts::111111111111:assumed-role/qa-backend-pipeline-PipelineSourceCodeCommitSo-1AFJNC9J3CPCJ/1613161686899 is not authorized to perform: codecommit:GetBranch on resource: arn:aws:codecommit:us-west-1:111111111111:backend
> 

### Environment

  - **CDK CLI Version  :** 1.88.0 (build f65009b)
  - **Framework Version:** 
  - **Node.js Version:** v15.5.0
  - **OS               :** macOS 10.15.7
  - **Language (Version):** Python (3.8.0)

### Other
This seems like a bug to me, but the argument could be made that this is just how it works and you need to explicitly add permission to the role. However I wasn't able to find anyway of accessing the role from the `CDKPipeline` object. Individual roles are created for each action and there's no way to easily and explicitly access a specific action (or it's role) from the `CDKPipeline` object. If I could access that role I could easily do something like:

`repo.grant_read(pipeline.stage('Source').action('CodeCommit_Source').role)`

Here's the policy statement that was created and added to the role:

```
      {
            "Action": [
                "codecommit:GetBranch",
                "codecommit:GetCommit",
                "codecommit:UploadArchive",
                "codecommit:GetUploadArchiveStatus",
                "codecommit:CancelUploadArchive"
            ],
            "Resource": "arn:aws:codecommit:us-west-2:111111111111:backend",
            "Effect": "Allow"
        }
```

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment] 2021-02-15 23:41
Thanks for opening the issue @cardosi . I confirm I was able to reproduce the problem. The root cause of the issue is that the account & region of the imported Repository is not saved correctly.

I have a fix of that issue in this PR: https://github.com/aws/aws-cdk/pull/13066

Thanks,
Adam

**Comment by cardosi** [comment] 2021-02-15 23:57
@skinny85 - Thanks so much for looking into this, I really appreciate it!

Would you be able to give me any idea of when that change might be released (is that a matter of hours/days/weeks)? I'm just trying to figure out I should invest much time into a work around.

**Comment by skinny85** [comment] 2021-02-16 00:12
I hope this change will be released this week.

**Closed** 2021-02-16 09:19 UTC
Labels: @aws-cdk/aws-codepipeline-actions, bug, in-progress, needs-triage
