### ISSUE TITLE
[sagemaker] CfnModel.model_name has no value 

### ISSUE THREAD

**Issue by oonisim** [aws/aws-cdk#10146] opened 2020-09-03 06:40 UTC
aws_sagemake.CfnModel.model_name has no value for CfnOutput. CfnModel.getatt("model_name") causes error stating it is not available. 

CDK CfnOutput of the model_name.
```
Mlai-MetadataDevSageMaker.SageMakerModelNewsArticleKeywordModelname281BFE27 = None
```

When tried to use the model_name, CDK causes error stating "undefined".
### Reproduction Steps

```
from aws_cdk import (
    aws_ec2,
    aws_sagemaker,
    aws_iam,
    core
)

class HelloCdkStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        sagemaker_execution_role = aws_iam.Role(
            self,
            "SagemakerExecutionRole",
            assumed_by=aws_iam.ServicePrincipal("sagemaker.amazonaws.com")
        )

        sagemaker_vpc = aws_ec2.Vpc(
            self,
            "Vpc",
            cidr="192.168.0.0/16"
        )

        sagemaker_security_group = aws_ec2.SecurityGroup(
            self,
            "SG",
            vpc=sagemaker_vpc
        )

        subnet_selection = sagemaker_vpc.select_subnets(
            subnet_type=aws_ec2.SubnetType.PRIVATE
        )

        vpc_config = aws_sagemaker.CfnModel.VpcConfigProperty(
            security_group_ids=[
                sagemaker_security_group.security_group_id
            ],
            # This is how you set the subnets for the SageMaker model
            subnets=subnet_selection.subnet_ids
        )

        sagemaker_model: aws_sagemaker.CfnModel = aws_sagemaker.CfnModel(
            scope=self,
            id="SagemakerModel",
            execution_role_arn=sagemaker_execution_role.role_arn,
            containers=[aws_sagemaker.CfnModel.ContainerDefinitionProperty(
                image="123456789012.dkr.ecr.us-west-2.amazonaws.com/mymodel:latest"
            )],
            # This is how you setup vpc_config here
            vpc_config=vpc_config
        )

        endpoint_config = aws_sagemaker.CfnEndpointConfig(
            scope=self,
            id="config",
            production_variants=[
                aws_sagemaker.CfnEndpointConfig.ProductionVariantProperty(
                    initial_instance_count=1,
                    initial_variant_weight=1.0,
                    instance_type="ml.m5.xlarge",
                    model_name=sagemaker_model.model_name,
                    variant_name="variant",
                )
            ]
        )

```
### What did you expect to happen?
Be able to use the model_name as an expected CDK token.

### Environment

  - **CLI Version      :** aws-cli/2.0.7 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev11
  - **Framework Version:** 1.58.0
  - **Node.js Version:** v12.18.3
  - **OS               :**  MacOS catalina 10.15.6
  - **Language (Version):** Python (3.7.3)

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment] 2020-09-04 08:42
@oonisim ,

This seems like exactly the same issue you filed as #10082, where we've already given you two options for getting the model name. [`attr_model_name`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_sagemaker/CfnModel.html#aws_cdk.aws_sagemaker.CfnModel.attr_model_name) is the property you're looking for, that will be populated by a token and available post-deployment as an output. `model_name` is only available on the model if you explicitly set it on creation. 

Closing as a duplicate of #10082.

**Closed by njlynch** 2020-09-04 08:42 UTC
Labels: @aws-cdk/aws-sagemaker, bug, needs-triage
