### ISSUE TITLE
[ec2] 'undefined' being placed in user data script

### ISSUE THREAD

**Issue by jake-jester-nih** [aws/aws-cdk#9116] opened 2020-07-16 18:49 UTC
https://github.com/aws/aws-cdk/blob/8c2d53c1830eea396be45d742443623aeb1294c1/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L168

because the  ${params.arguments} is ... undefined.

### Reproduction Steps

I appreciate what you are saying, but the information below is not applicable.

Here is the definition of the interface in question:

https://github.com/aws/aws-cdk/blob/8c2d53c1830eea396be45d742443623aeb1294c1/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L45

Here is the "arguments" parameter that is being defined as OPTIONAL:

https://github.com/aws/aws-cdk/blob/8c2d53c1830eea396be45d742443623aeb1294c1/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L57

here is the code where that interface is used:

https://github.com/aws/aws-cdk/blob/8c2d53c1830eea396be45d742443623aeb1294c1/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L225
https://github.com/aws/aws-cdk/blob/8c2d53c1830eea396be45d742443623aeb1294c1/packages/%40aws-cdk/aws-ec2/lib/user-data.ts#L168

Because the code is not accounting for the params.arguments as an optional parameter, if one does not provide the arguments parameter, "Undefined" is placed in the output of the command, in the userdata script that is placed on a ec2 instance.

This doesn't cause a problem, as long as your script is not trying to use any argvs, which it should not be, but it is definitely unintended behavior.

### Error Log

N/A

### Environment

N/A

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment] 2020-07-16 21:09
Hi @jake-jester-nih, thanks for opening an issue. Please use the issue template provided so that we can have as much information as possible to understand how to help. You can just edit your post above. Thanks!

**Comment by rix0rrr** [comment] 2020-08-03 14:29
Oh yeah. This ought to be an easy fix.

`?? ''`.

**Comment by AnderEnder** [comment] 2020-10-25 13:30
Duplicate of #10687.
It was fixed by #10692.

**Closed** 2020-11-10 20:59 UTC
Labels: @aws-cdk/aws-ec2, bug, effort/small, good first issue, p2
