### ISSUE TITLE
aws-apigateway: Invalid method (404) when creating Usage Plan

### ISSUE THREAD

**Issue by michchan** [aws/aws-cdk#15426] opened 2021-07-05 16:11 UTC
"Invalid method...404" error occurred when running `cdk deploy`.
The error indicates on the line of `api.addUsagePlan`, some method is not found.

### Reproduction Steps

```typescript
import * as cdk from '@aws-cdk/core'
import {
  Deployment,
  LambdaIntegration,
  Method,
  MethodLoggingLevel,
  Resource,
  RestApi,
  Stage,
} from '@aws-cdk/aws-apigateway'
import { ServicePrincipal } from '@aws-cdk/aws-iam'
import addCorsOptions from './addCorsOptions'
import env from '../../../lib/env'

interface Resources {
  someResources: Resource;
}
const constructEndpoints = (api: RestApi): Resources => {
  // Add records path
  const service = api.root.addResource('someService')
  const someResources = service.addResource('someResources')

  return {
    someResources,
  }
}

const DEFAULT_METHOD_OPTIONS = { apiKeyRequired: true }
const integrateResourcesHandlers = (resources: Resources, handlers: Handlers): Method[] => {
  const {
    someResources,
  } = resources
  const {
    listSomeResources,
  } = handlers

  // Integrations
  const listSomeResourcesIntegration = new LambdaIntegration(listSomeResources)

  // Add CORS options
  Object.values(resources).forEach((resource: Resource) => addCorsOptions(resource))

  return [
    someResources.addMethod('GET', listSomeResourcesIntegration, DEFAULT_METHOD_OPTIONS),
  ]
}

const DEV_STAGE_NAME = 'dev'
const IS_DEV_CACHING_ENABLED = false
const DEV_THROTTLING_RATE_LIMIT = 1000
const DEV_THROTTLING_BURST_LIMIT = 200

const PROD_STAGE_NAME = 'prod-v1'
const IS_PROD_CACHING_ENABLED = false
const PROD_THROTTLING_RATE_LIMIT = 10
const PROD_THROTTLING_BURST_LIMIT = 2

interface DeploymentStages {
  dev: Stage;
  prod: Stage;
}
const constructDeploymentStages = (
  scope: cdk.Construct,
  api: RestApi,
): DeploymentStages => {
  const devDeployment = new Deployment(scope, `${DEV_STAGE_NAME}Deployment`, { api })
  const devStage = new Stage(scope, `${DEV_STAGE_NAME}Stage`, {
    stageName: DEV_STAGE_NAME,
    deployment: devDeployment,
    cachingEnabled: IS_DEV_CACHING_ENABLED,
    loggingLevel: MethodLoggingLevel.INFO,
  })

  const prodDeployment = new Deployment(scope, `${PROD_STAGE_NAME}Deployment`, { api })
  const prodStage = new Stage(scope, `${PROD_STAGE_NAME}Stage`, {
    stageName: PROD_STAGE_NAME,
    deployment: prodDeployment,
    cachingEnabled: IS_PROD_CACHING_ENABLED,
    loggingLevel: MethodLoggingLevel.ERROR,
  })

  api.deploymentStage = prodStage
  return {
    dev: devStage,
    prod: prodStage,
  }
}

const constructRateLimitApiKeys = (
  api: RestApi,
  methods: Method[],
  stages: DeploymentStages,
): void => {
  const config = [
    {
      name: 'Dev',
      rateLimit: DEV_THROTTLING_RATE_LIMIT,
      burstLimit: DEV_THROTTLING_BURST_LIMIT,
      apiKeyValue: env.values.API_KEY_DEV,
      stage: stages.dev,
    },
    {
      name: 'DefaultPublicAccess',
      rateLimit: PROD_THROTTLING_RATE_LIMIT,
      burstLimit: PROD_THROTTLING_BURST_LIMIT,
      apiKeyValue: env.values.API_KEY_DEFAULT_PUBLIC_ACCESS,
      stage: stages.prod,
    },
  ]
  config.forEach(({
    name,
    rateLimit,
    burstLimit,
    apiKeyValue,
    stage,
  }) => {
    const throttle = { rateLimit, burstLimit }

    const apiKeyName = `${name}ApiKey`
    const key = api.addApiKey(apiKeyName, {
      apiKeyName,
      value: apiKeyValue,
    })

    const planName = `${name}PlanName`
    const plan = api.addUsagePlan(planName, {
      name: planName,
      throttle,
    })
    plan.addApiKey(key)
    plan.addApiStage({
      stage,
      throttle: methods.map(method => ({ method, throttle })),
    })
    
    // The error occurred either with or without this line
    plan.node.addDependency(...methods)
  })
}

const grantLambdaInvoke = (
  api: RestApi,
  stages: DeploymentStages,
  handlers: Handlers,
): void => Object.values(stages).forEach(({ stageName }: Stage, stageIndex) => {
  const sourceArn = api.arnForExecuteApi('*', '/*', stageName)
  Object.values(handlers)
    .forEach((handler: Handlers[keyof Handlers], i) => {
      handler.addPermission(`apigatewayPermission_${stageIndex}_${i}`, {
        action: 'lambda:InvokeFunction',
        principal: new ServicePrincipal('apigateway.amazonaws.com'),
        sourceArn,
      })
    })
})

const constructApiGateway = (scope: cdk.Construct, handlers: Handlers): void => {
  const api = new RestApi(scope, 'SomeApiID', {
    restApiName: 'Some Service',
    description: 'Services for accessing some resources',
    deploy: false,
  })
  const resources = constructEndpoints(api)
  const methods = integrateResourcesHandlers(resources, handlers)
  const stages = constructDeploymentStages(scope, api)

  constructRateLimitApiKeys(api, methods, stages)
  grantLambdaInvoke(api, stages, handlers)
}
export default constructApiGateway
```

### What did you expect to happen?

Deploy successfully with usage plan and new API.

### What actually happened?

```
11:09:27 PM | UPDATE_FAILED        | AWS::ApiGateway::UsagePlan       | AppApiDevPlanNameF87BFE8A
Invalid method {resourcePath: /someServices/someResources,method: GET} specified (Service: AmazonApiGateway; Status Code: 404; Error Code: NotFoundException; Request ID: d917a033-2155-417c-8fb8-017070274200; Proxy: null)

	new UsagePlan (/Users/someUser/appName/node_modules/@aws-cdk/aws-apigateway/lib/usage-plan.ts:104:16)
	\_ RestApi.addUsagePlan (/Users/someUser/appName/node_modules/@aws-cdk/aws-apigateway/lib/restapi.ts:182:12)
	\_ /Users/someUser/appName/construct/services/someServices/constructs/constructApiGateway.ts:198:22
	\_ Array.forEach (<anonymous>)
	\_ constructRateLimitApiKeys (/Users/someUser/appName/construct/services/someServices/constructs/constructApiGateway.ts:182:10)
	\_ Object.constructApiGateway [as default] (/Users/someUser/appName/construct/services/someServices/constructs/constructApiGateway.ts:240:3)
	\_ Object.construct (/Users/someUser/appName/construct/services/someServices/someServices.ts:16:22)
	\_ new SomeStack (/Users/someUser/appName/construct/some-stack.ts:48:57)
	\_ Object.<anonymous> (/Users/someUser/appName/bin/some.ts:7:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1063:30)
	\_ Module.m._compile (/Users/someUser/appName/node_modules/ts-node/src/index.ts:1043:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	\_ Object.require.extensions.<computed> [as .ts] (/Users/someUser/appName/node_modules/ts-node/src/index.ts:1046:12)
	\_ Module.load (internal/modules/cjs/loader.js:928:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
	\_ main (/Users/someUser/appName/node_modules/ts-node/src/bin.ts:225:14)
	\_ Object.<anonymous> (/Users/someUser/appName/node_modules/ts-node/src/bin.ts:512:3)
	\_ Module._compile (internal/modules/cjs/loader.js:1063:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	\_ Module.load (internal/modules/cjs/loader.js:928:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:769:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
	\_ /Users/michaelchan/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

### Environment

  - **CDK CLI Version  :** 1.111.0
  - **Framework Version:** 1.111.0
  - **Node.js Version:** v12.14.1
  - **OS               :** macOS BigSur 11.4
  - **Language (Version):** TypeScript (4.1.3)

### Other

--- 

This is :bug: Bug Report

**Comment by BenChaimberg** [comment] 2021-07-09 17:05
I was unable to reproduce this error, see: https://github.com/BenChaimberg/cdk-test-app-ts/compare/usage_plan_invalid_method_15426. Are you sure that including `plan.node.addDependency(...methods)` does not fix the issue?

**Comment by peterwoodworth** [comment] 2021-09-20 22:20
Please ping me if you'd like to reopen this issue. Closing for now

**Closed by peterwoodworth** 2021-09-20 22:20 UTC
Labels: bug, response-requested, @aws-cdk/aws-apigateway, needs-reproduction, needs-triage
