### ISSUE TITLE
(servicecatalog): Service Catalog does not support assets out of the box!

### ISSUE THREAD

**Issue by padaszewski** [aws/aws-cdk#20361] opened 2022-05-16 12:42 UTC
### Describe the bug

The docs states:
```
Creating a product from a stack
You can create a Service Catalog CloudFormationProduct entirely defined with CDK code using a service catalog ProductStack.
A separate child stack for your product is created and you can add resources like you would for any other CDK stack,
such as an S3 Bucket, IAM roles, and EC2 instances. This stack is passed in as a product version to your product.
```
But unfortunately this is not the case. Each resource that creates S3 assets, like eg. complex bundled lambdas, can not be created in the desired customer (target) account.
This applies to the game changer method ```fromProductStack()``` and also (found today) to the ```fromAsset()``` method.

### Expected Behavior

```fromProductStack()```: The behaviour of ProductStack containing assets in the target account is the same as of Stack in the development account.
```fromAsset()``` : The product containing assets is successfully deployed in the target account

### Current Behavior

```fromProductStack()``` : Not even synthable, because the ```ProductStackSynthesizer``` throws the following error: ```Service Catalog Product Stacks cannot use Assets```
```fromAsset()``` : before we create the product we presynth the App with following stack synthesizer:
```typescript
synthesizer: new DefaultStackSynthesizer({
          generateBootstrapVersionRule: false,
        }
```
and put the result into the ```fromAsset()``` method. This leads to actually generating the product but if we try to launch the product we got the error that the cdk-bootstrap-bucket in the target account  does not exists (what is correct, we do not want to bootstrap the account, just launch the CFN product) and the asset, obviously, can not be created. So this leads to an error during the launch.

### Reproduction Steps

Lets consider the following simple stack:
```typescript
export class SimpleStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props)

    const simpleBucket: IBucket = new Bucket(this, 'my-simple-bucket', {
      autoDeleteObjects: true,
      removalPolicy: RemovalPolicy.DESTROY,
    })
  }
}
```
This construct creates the custom resource lambda for auto deleting objects, so it fits perfect as a small example.
Now the actual portfolio stacks:
```fromAsset()```:
```typescript
export class PortfolioStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props)

    const portfolio = new servicecatalog.Portfolio(this, 'my-portfolio', {
      displayName: 'somename',
      description: 'somedesc',
      providerName: 'someprovidername',
    })

    portfolio.shareWithAccount('SOME_ACCOUNT_ID_TO_SHARE_THE_PORTFOLIO_WITH')

    PortfolioStack.getTemplate()

    const product = new servicecatalog.CloudFormationProduct(this, 'Product', {
      productName: 'someProductName',
      owner: 'someProductOwner',
      productVersions: [
        {
          productVersionName: 'someProductVersionName',
          description: 'someProductDesc',
          cloudFormationTemplate: servicecatalog.CloudFormationTemplate.fromAsset(
            path.join(__dirname, 'templates', 'mySimpleStack.template.json'),
          ),
        },
      ],
    })

    portfolio.addProduct(product)
  }

  private static getTemplate() {
    const app = new cdk.App({
      stackTraces: false,
      treeMetadata: false,
      //context
    })

    const applicationStack = new SimpleStack(
      app,
      'mySimpleStack',
      {
        env: {
          account: 'ENV_ACCOUNT_ID',
          region: 'ENV_REGION',
        },
        synthesizer: new DefaultStackSynthesizer({
          generateBootstrapVersionRule: false,
        }),
      },
    )

    const synth = app.synth()
    const template = synth.getStackArtifact(applicationStack.artifactId).template
    const templateDir = path.join(__dirname, 'templates')
    console.log(templateDir)

    if (!fs.existsSync(templateDir)) {
      fs.mkdirSync(templateDir)
    }
    const templatePath = `${templateDir}/mySimpleStack.template.json`
    console.log(templatePath)
    fs.writeFileSync(templatePath, JSON.stringify(template, null, 2))
  }
}
```

```fromProductStack()```:
Just simply exchange the product creation method and ignore ```getTemplate()```
```typescript
 cloudFormationTemplate: CloudFormationTemplate.fromProductStack(
            new ProductStack(new SimpleStack(), 'mySimpleProductStack'),
          )
 ```

### Possible Solution

Currently the only solution we got is to have one application wich contains the assets in the specified S3 buckets, provide read permissions for the target account and then create the assets like:
```typescript
lambda.Code.fromBucket(bucket, key[, objectVersion])
```
But as You can see this is kind of ironic.
If You have any better solution please share it here.
```fromProductStack()``` is a very big game changer for using the Service Catalog with CDK so we want to encourage You to provide a clean solution for this.

### CDK CLI Version

2.23.0 (build 50444aa)

### Node.js Version

v16.15.0

### OS

Windows

### Language

Typescript

### Language Version

TypeScript (4.6.4)

**Comment by wanjacki** [comment] 2022-05-16 17:06
@padaszewski 
We are aware of this issue and are currently working on a feature to improve ProductStack in order fix this.

**Comment by padaszewski** [comment] 2022-05-16 17:31
@wanjacki
Thats cool, do You have any orientation date when this feature might be released?

According to ```fromAsset()``` we do not want to bootstrap the target account. Deploying the CFN Product should work without bootstraping in target. The devops guys in the target account should have only to import the portfolio and launch the product. We do not have the power to tell them to bootstrap the account according to our needs,

**Comment by wanjacki** [comment] 2022-05-16 17:58
@padaszewski 
We do not have any orientation date at the moment, however we are prioritizing this feature and are actively working on it. I can provide an update if we do have a date available.

In regards for `fromAsset()`, if I am understanding correctly, are you referring to deploying an asset file using `fromAsset()` that is also containing another nested Asset. This nested asset is available to the admin account but not to the end user account when the portfolio is shared with them? (Same issue that is existing with `fromProductStack`)

**Comment by padaszewski** [comment] 2022-05-17 06:38
@wanjacki 
Sure, please keep me up to date with this, because this would enorm simplify our release process.

According to ```fromAsset()``` we tried exactly that what You wrote in the edit section. I thought it might fail, but I had to check it out as I didn't find a good solution on how to work with the combination assets + cdk + service catalog.

**Comment by peterwoodworth** [comment] 2022-06-10 01:47
I'm going to close this as a duplicate of the feature request #20690. Thanks for the discussion all! I'd appreciate it if we could keep this all in the FR thread 🙂

**Closed by peterwoodworth** 2022-06-10 01:47 UTC
Labels: bug, @aws-cdk/aws-servicecatalog
