### ISSUE TITLE
RunLambdaTask with outputPath not working 

### ISSUE THREAD

**Issue by eikeon** [aws/aws-cdk#7709] opened 2020-04-30 12:24 UTC
`outputPath` when used with `RunLambdaTask` is not working as documented. In the step functions overview under `Lambda example` 

"The following snippet invokes a Lambda and sets the task output to only include the Lambda function response."

```typescript
new sfn.Task(this, 'Invoke and set function response as task output', {
  task: new tasks.RunLambdaTask(myLambda, {
    payload: sfn.TaskInput.fromDataAt('$'),
  }),
  outputPath: '$.Payload',
});
```

### Reproduction Steps

Starting from a working tasks.InvokeFunction:

```diff
<!--
minimal amount of code that causes the bug (if possible) or a reference:
-->

         const getObject = new sfn.Task(this, "Get Object", {
-            task: new tasks.RunLambdaTask(getObjectLambda, {}),
-            outputPath: "$.Payload",
+            task: new tasks.InvokeFunction(getObjectLambda, {}),
             resultPath: "$.GetObjectResult",
         });
```

Also tried outputPath: "$.output.Payload" with same result.

### Error Log

`TaskSucceeded` with: 
```json
{
  "resourceType": "lambda",
  "resource": "invoke",
  "output": {
    "ExecutedVersion": "$LATEST",
    "Payload": {
      "Done": true,
      "Next": null,
      "BitsFetched": 0
    },
    "SdkHttpMetadata": {
      "HttpHeaders": {
        "Connection": "keep-alive",
        "Content-Length": "41",
        "Content-Type": "application/json",
        "Date": "Thu, 30 Apr 2020 00:36:36 GMT",
        "X-Amz-Executed-Version": "$LATEST",
        "x-amzn-Remapped-Content-Length": "0",
        "x-amzn-RequestId": "f1e1c5df-4740-4389-8230-2c495c5cd829",
        "X-Amzn-Trace-Id": "root=1-5eaa1d94-16cf39fcb6ea5d8bb11bd635;sampled=0"
      },
      "HttpStatusCode": 200
    },
    "SdkResponseMetadata": {
      "RequestId": "f1e1c5df-4740-4389-8230-2c495c5cd829"
    },
    "StatusCode": 200
  }
}

followed by `ExecutionFailed` with:

```json
{
  "error": "States.Runtime",
  "cause": "An error occurred while executing the state 'Get Object' (entered at the event id #2). Invalid path '$.Payload' : No results for path: $['Payload']"
}
```

{

```


### Environment

  - **CLI Version      :** 1.36.1
  - **Framework Version:** 1.36.1
  - **OS               :** macOS Catalina 10.15.5 Beta (19F62f)
  - **Language         :** Typescript

### Other

<!-- e.g. detailed explanation, stacktraces, related issues, suggestions on how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc -->




--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment] 2020-05-01 08:25
@eikeon I think you're `TaskSucceeded` entry you're sharing there is from the Execution Event History, which uses the `output` field.

When you're setting `resultPath` to be `$.GetObjectResult`, you're putting the result of your Lambda into a node called `GetObjectResult` which is appended to the state input.

If you want the Lambda's result, you'd have to set your `outputPath` to be `$.GetObjectResult.Payload`

Let me know how it goes!

**Comment by eikeon** [comment] 2020-05-01 15:44
I should have stared at https://docs.aws.amazon.com/step-functions/latest/dg/concepts-input-output-filtering.html longer. Had it in my head that the $outputPath happens before not after the $resultPath in that diagram.
 
But I'm still not able to replicate the TaskOutput I get with InvokeFunction when using RunLambdaTask. Attempt 1)

 ```diff
--- a/lib/getobject-statemachine.ts
+++ b/lib/getobject-statemachine.ts
@@ -48,6 +48,7 @@ export class GetObjectStateMachine extends cdk.Construct {
 
         const getObject = new sfn.Task(this, "Get Object", {
             task: new tasks.InvokeFunction(getObjectLambda, {}),
+            outputPath: "$.GetObjectResult.Payload",
             resultPath: "$.GetObjectResult",
         });
```

results in `LambdaFunctionSucceeded` with output:

```json
{
  "output": {
    "Done": true,
    "Next": null,
    "BitsFetched": 0
  }
}
```

followed by `ExecutionFailed` with:

```json
{
  "error": "States.Runtime",
  "cause": "An error occurred while executing the state 'Get Object' (entered at the event id #2). Invalid path '$.GetObjectResult.Payload' : No results for path: $['GetObjectResult']['Payload']"
}
```

### Attempt 2) 

```diff
--- a/lib/getobject-statemachine.ts
+++ b/lib/getobject-statemachine.ts
@@ -48,6 +48,7 @@ export class GetObjectStateMachine extends cdk.Construct {
 
         const getObject = new sfn.Task(this, "Get Object", {
             task: new tasks.InvokeFunction(getObjectLambda, {}),
+            outputPath: "$.GetObjectResult",
             resultPath: "$.GetObjectResult",
         });
```

followed by `TaskStateExited` with:

```json
{
  "name": "Get Object",
  "output": {
    "Done": true,
    "Next": null,
    "BitsFetched": 0
  }
}
```

where as with the InvokeFunction the task state exited with:

```json
{
  "name": "Get Object",
  "output": {
    "ParentContentID": "AQERFLelzPqbNGewZ3/CDNW/o/ZzuA4U",
    "Hash": "ERTg6jh13sV9G3ILH6qyChVfn4i2Bg==",
    "URL": "https://archive.org/download/snowyforluck00good/snowyforluck00good_metasource.xml",
    "Size": 0,
    "PartInfo": null,
    "GetObjectResult": {
      "Done": true,
      "Next": null,
      "BitsFetched": 0
    }
  }
}
```

**Comment by shivlaks** [comment] 2020-05-01 18:12
@eikeon I see what you mean now. This is a limitation that's imposed by using RunLambda (or any service integration really since they all have the metadata).

There is a workaround, I'm giving it a try and will share if it works for me. Stay tuned!

**Comment by shivlaks** [comment] 2020-05-01 19:28
@eikeon so, you cannot merge a **part** of the task output to the input, which is what you're going for when using resultPath.

The workaround from the Step Functions team if this behavior is still desired is to use a `Pass` state to merge the input and the part of the output you'd like.

The issue is also discussed[here](https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/8#issuecomment-558419812)

From the CDK side of things, here's a [gist](https://gist.github.com/shivlaks/49b53d79762b0cf9283ee33caa6c96ee#file-sfn-mergeresultpath-stack-ts-L37-L47) that shows it's usage of the workaround.

This applies to all service integrations that follow the service integration pattern (essentially all of them except the old InvokeFunction). I think we should at the very least update our README and documentation on paths to detail the limitation more clearly.

I'm not sure it's actionable from the CDK side since Step Functions doesn't allow it yet. I've also passed along the feedback to the team.

**Comment by eikeon** [comment] 2020-05-01 22:54
@shivlaks Thank you. And agreed re: very least since InvokeFunction is being deprecated and others will likely be going down this path with the rake on the ground.

From the CDK side, where higher level constructs are being created, would it be possible to add an option to RunLambdaTask that would create the extra `Pass` state?

Alternatively, document how one can expect an additional layer of output and update the rest of their state machine to expect it. Going to find out what that looks like now ;)

Thanks again for your help! Hope my feedback has been helpful as well. Let me know is there's anything I can do to help. Else I should be set now.

**Comment by shivlaks** [comment] 2020-05-01 23:01
@eikeon thanks for taking the time to provide this valuable feedback!

I'll circle back as to whether it would be a useful thing to try and generate the pass state when chaining Lambdas together or whether we would want to wait a bit before jumping into an implementation. My initial instinct is that It still feels a little clunky to encode a workaround into the API.

Let me know if you run into any other snags. At a minimum I'll start with documenting this since it applies to all service integrations, it'll likely be a FAQ

**Comment by eikeon** [comment] 2020-05-01 23:09
Agreed re: a little clunky. Versus updating a few references elsewhere in the state machine to deal with the extra layer. I don't anticipate that's going to be a problem in my case.

**Comment by eikeon** [comment] 2020-05-01 23:37
Yep; the addition of a few `.Payload`s elsewhere in my step functions and no need for workarounds. So maybe just a note along side the deprecated notice of InvokeFunction of what options lie ahead. If I would have started with RunLambdaFunction I would not have been trying to preserve that exact behavior so hard

**Comment by eikeon** [comment] 2020-05-02 19:32
Doh, linked the above merge request accidentally to this one in a commit even though the title had the correct issue #

**Comment by shivlaks** [comment] 2020-05-03 01:36
> Doh, linked the above merge request accidentally to this one in a commit even though the title had the correct issue #

@eikeon no worries, it's not a big deal

**Comment by nideveloper** [comment] 2020-05-08 07:37
Hey,

A use case I hit last night was I wrapped a SAR application in CDK that uses a stepfunction. The plan was to redefine the stepfunction in cdk but pull in all the latest lambda changes from the remote repo with every build rather than creating a stale fork.

The SAR app uses the "old" style for step function definition

I got it working but I had to introduce adapter steps between the lambda functions and the next step like you suggested (https://www.npmjs.com/package/cdk-lambda-powertuner)

If you didn't deprecate the "old" api I could just use that and not need to make any of these extra adapter changes.

Just curious why CDK can't keep offering both since StepFunctions do? Or are the StepFunctions team planning on dropping support?

**Comment by nideveloper** [comment] 2020-05-08 13:04
Forget the last comment I learned how easy it is to deploy a SAR app with CDK. 

```
new sam.CfnApplication(this, 'samPowerTuner', {
      location: {
        applicationId: 'arn:aws:serverlessrepo:us-east-1:451282441545:applications/aws-lambda-power-tuning',
        semanticVersion: '3.2.4'
      },
      parameters: {"lambdaResource":testLambda.functionArn}
})
```

**Comment by nija-at** [comment] 2020-05-11 09:50
> From the CDK side, where higher level constructs are being created, would it be possible to add an option to RunLambdaTask that would create the extra Pass state?

This seems like a useful option to add to the `RunLambdaTask`. 
@shivlaks - maybe we should open a separate feature request for this, and close this guidance issue?

**Comment by shivlaks** [comment] 2020-05-18 22:23
@nija-at I'm good with opening a separate feature request. I'm still skeptical as to whether it's a commonly used mechanism. I agree that we can do better if it is. 

As an aside, `RunLambdaTask` does not control state level properties or behavior. If we choose to implement the feature, it should be done after we have merged those properties into a single class.

**Comment by shivlaks** [comment] 2020-07-23 20:01
In #9022 we introduced a flag `payloadResponseOnly` to the `LambdaInvoke` class which succeeded `RunLambdaTask` to request the legacy behaviour where Lambda's function result only is the state output and no other metadata is included.

The legacy Lambda integration with Step Functions does not support callbacks (`.sync`) and is request response only. It does offer the benefit of a simpler experience for users that just want Lambda's results to become the state output and for the Lambda to run synchronously.

**Closed by shivlaks** 2020-07-23 20:01 UTC
Labels: @aws-cdk/aws-stepfunctions-tasks, guidance, in-progress
