### ISSUE TITLE
Inaccessible host: `cloudformation.'. This service may not be available in the `"us-east-1"' region.

### ISSUE THREAD

**Issue by omerlh** [aws/aws-cdk#6577] opened 2020-03-04 08:48 UTC
Trying to use AWS cdk from Codefresh CD tool, I'm getting this error when running `cdk diff`:

I'm using AWS access keys for authentication - by setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_REGION

### Error Log

```
Stack <>
Reading existing template for stack <>.
Using default AWS SDK credentials for account <>
Inaccessible host: `cloudformation.'. This service may not be available in the `"us-east-1"' region.
UnknownEndpoint: Inaccessible host: `cloudformation.'. This service may not be available in the `"us-east-1"' region.
    at Request.ENOTFOUND_ERROR (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/event_listeners.js:495:46)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/event_listeners.js:333:22)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:311:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
Reading environment variable exporting file contents.
Reading environment variable exporting file contents.
[31m[SYSTEM] 
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment] 2020-03-05 09:59
Looks like a networking issue. Could it be that your host doesn't have access to the internet? Can you try to run something like `aws s3 list` from this host?

**Comment by omerlh** [comment] 2020-03-05 17:38
I think it's another issue - see the URL? it's missing the root dns under the `.` and I can't figure out what put there the region and the aws root URL

**Comment by eladb** [comment] 2020-03-10 07:33
Can you please run with `--verbose` and paste your log here?

**Comment by omerlh** [comment] 2020-03-10 08:31
```
cdk diff -v
CDK toolkit version: 1.27.0 (build a98c0b3)
Command line arguments: {
  _: [ 'diff' ],
  v: true,
  verbose: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  'context-lines': 3,
  contextLines: 3,
  strict: false,
  '$0': '/usr/local/bin/cdk'
}
Determining whether we're on an EC2 instance.
Looks like EC2 instance.
cdk.json: {
  "app": "npx ts-node bin/<>-cdk.ts"
}
cdk.context.json: {
  "@aws-cdk/core:enableStackNameDuplicates": "true",
  "aws-cdk:enableDiffNoFail": "true"
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'npx ts-node bin/<>-cdk.ts',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true
}
Setting "CDK_DEFAULT_REGION" environment variable to "us-east-1"
Resolving default credentials
Looking up default account ID from STS
Default account ID: <>
Setting "CDK_DEFAULT_ACCOUNT" environment variable to <>
context: {
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws-cdk:enableDiffNoFail': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: '"us-east-1"',
  CDK_DEFAULT_ACCOUNT: '<>',
  CDK_CONTEXT_JSON: '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws-cdk:enableDiffNoFail":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.21.0',
  CDK_CLI_VERSION: '1.27.0'
}
Stack <>
Reading existing template for stack <>.
Using default AWS SDK credentials for account <>
Inaccessible host: `cloudformation.'. This service may not be available in the `"us-east-1"' region.
UnknownEndpoint: Inaccessible host: `cloudformation.'. This service may not be available in the `"us-east-1"' region.
    at Request.ENOTFOUND_ERROR (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/event_listeners.js:495:46)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/event_listeners.js:333:22)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:311:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)

```

**Comment by eladb** [comment] 2020-03-10 10:06
I suspect that the problem is that the  `CDK_DEFAULT_REGION` environment variables is set to `"us-east-1"` (quoted) instead of just `us-east-1` (without quotes).

**Comment by eladb** [comment] 2020-03-11 14:59
Closing with the assumption that this was the issue. Reopen is needed.

**Closed by eladb** 2020-03-11 14:59 UTC
Labels: guidance, package/eks

**Comment by omerlh** [comment] 2020-03-12 05:51
Thanks, that indeed solved the issue :)
