### ISSUE TITLE
(stepfunctions): S3 LambdaDestination creates a cyclic reference when used with Step Function and SageMaker train job

### ISSUE THREAD

**Issue by diana-tchalakova** [aws/aws-cdk#11650] opened 2020-11-23 23:12 UTC
Setting S3 Bucket used in Step Function with SageMaker training task notification to a Lambda function in the other stack creates a cyclic reference.

### Reproduction Steps

```ts
const app = new cdk.App();
const stack1 = new cdk.Stack(app, "stack1");
const stack2 = new cdk.Stack(app, "stack2");

const lambdaFunction = new lambda.Function(stack1, "lambdaFunction", {
  code: lambda.Code.fromInline("whatever"),
  handler: "index.handler",
  runtime: lambda.Runtime.NODEJS_10_X
});
const inputBucket = new s3.Bucket(stack2, "bucket");

const sagemakerTrainingJob = new SageMakerCreateTrainingJob(stack1, "TrainingJob",
{
//specify more properties ....
    inputDataConfig: [
        {
            channelName: 'train',
            dataSource: {
                s3DataSource: {
                    s3Location: S3Location.fromBucket(inputBucket)
                }
            }
        }
    ]
});

const stateMachine = new StateMachine(stack1, "StateMachine", {
    stateMachineName: "some name",
    definition: Chain.start(sagemakerTrainingJob)
});

inputBucket.addObjectCreatedNotification(new LambdaDestination(lambdaFunction));
```

```sh
$ cdk synth
```

### Error Log

```sh
Validating contents of /home/workspace/training/src/App/cdk.json conforms to cdk-build schema
cdk-build schema validated
Using cdk out from cdk.json: /local/home/workspace/training/src/App/build/cdk.out
Error: 'SageMakerTrainStorage-Devo-us-west-2' depends on 'SageMakerTrain-Devo-us-west-2' (SageMakerTrainStorage-Devo-us-west-2 -> SageMakerTrain-Devo-us-west-2/SampleStepMachine/S3EventBasedTrainingInvoker/Resource.Arn). Adding this dependency (SageMakerTrain-Devo-us-west-2 -> SageMakerTrainStorage-Devo-us-west-2/sagemaker-input-70a5672883d34f62b02f225c2c4f3ee8c2915ffd/Bucket/Resource.Arn) would create a cyclic reference.
    at SageMakerTrainStepMachineStack._addAssemblyDependency (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/stack.ts:652:19)
    at Object.addDependency (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/deps.ts:46:24)
    at SageMakerTrainStepMachineStack.addDependency (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/stack.ts:429:9)
    at resolveValue (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/private/refs.ts:86:14)
    at Object.resolveReferences (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/private/refs.ts:29:30)
    at Object.prepareApp (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/private/prepare-app.ts:28:5)
    at Object.synthesize (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/private/synthesis.ts:19:5)
    at App.synth (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/stage.ts:168:29)
    at process.<anonymous> (/local/home/workspace/training/src/App/node_modules/monocdk/lib/core/lib/app.ts:109:51)
    at Object.onceWrapper (events.js:421:26)
Subprocess exited with error 1
    Error: Failed to run cdk synth:
```

### Environment

  - **CDK CLI Version  :** 1.72.0 (on mono cdk)
  - **OS               :** All
  - **Language :** TypeScript 

--- 

This is :bug: Bug Report

**Comment by robpolak** [comment] 2021-03-25 20:35
Any updates on this issue?   Running into this as well.  For me, it was issues with defining IAM roles in a separate stack and using bucket.addEventNotification

Thanks!

**Comment by ryparker** [comment] 2021-06-14 21:41
Hey @diana-tchalakova 

Thanks for bringing this to our attention. This does seem like a valid bug. I was able to reproduce that error using what you had provided. Thank you! 

A dev will pick up this bug in order of priority. This is marked as p1 which means it has been prioritized as important and should see attention soon, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR. 

Here's my full repro code:

```TS
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import * as s3 from '@aws-cdk/aws-s3';
import {
  SageMakerCreateTrainingJob,
  S3Location,
} from '@aws-cdk/aws-stepfunctions-tasks';
import { StateMachine, Chain } from '@aws-cdk/aws-stepfunctions';
import { LambdaDestination } from '@aws-cdk/aws-s3-notifications';

const app = new cdk.App();

// Stack 2
const stack2 = new cdk.Stack(app, 'stack2');

const inputBucket = new s3.Bucket(stack2, 'bucketInput');
const outputBucket = new s3.Bucket(stack2, 'bucketOutput');

// Stack 1
const stack1 = new cdk.Stack(app, 'stack1');

const lambdaFunction = new lambda.Function(stack1, 'lambdaFunction', {
  code: lambda.Code.fromInline('whatever'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_10_X,
});

const lambdaDestination = new LambdaDestination(lambdaFunction);
inputBucket.addObjectCreatedNotification(lambdaDestination); // Depends on Stack 2

const sageMakerTrainingJob = new SageMakerCreateTrainingJob(
  stack1,
  'TrainingJob',
  {
    trainingJobName: 'TrainingJob',
    algorithmSpecification: {
      algorithmName: 'KNN',
    },
    outputDataConfig: {
      s3OutputLocation: S3Location.fromBucket(outputBucket, 'output'), // Depends on Stack 2
    },
    inputDataConfig: [
      {
        channelName: 'train',
        dataSource: {
          s3DataSource: {
            s3Location: S3Location.fromBucket(inputBucket, 'input'), // Depends on Stack 2
          },
        },
      },
    ],
  }
);

const stateMachine = new StateMachine(stack1, 'StateMachine', {
  stateMachineName: 'someName',
  definition: Chain.start(sageMakerTrainingJob), // Triggers circular dependency error
});
```

**Comment by ryparker** [comment] 2021-06-14 21:45
@robpolak Would you mind providing some repro code?

**Comment by peterwoodworth** [comment] 2021-08-10 17:55
Possibly related issue: #11650 (Thanks Ryan)

@BenChaimberg can we have you take a look at this and the issue I linked? I'm unable to diagnose the root cause of these or able to determine if they're related. Thanks!

**Comment by BenChaimberg** [comment] 2021-08-11 23:52
This is not a Step Functions issue. The missing link is that the following line does not add a dependency of stack 1 -> stack 2, but in fact the other way around.
```ts
inputBucket.addObjectCreatedNotification(lambdaDestination);
```
This is because adding a notification onto an S3 bucket creates a new resource in the S3 bucket's scope that refers to the destination. When combined with a state machine in the Lambda function's scope that refers to another resource in the scope of the bucket with a notification, causes a cyclical dependency.

You can fix this by treating the bucket with notification as "unmanaged": re-import it with [`s3.Bucket.fromBucketArn`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-s3.Bucket.html#static-fromwbrbucketwbrarnscope-id-bucketarn) and then call `addObjectCreatedNotification`.
```ts
const reImportedInputBucket = s3.Bucket.fromBucketArn(stack1, 'Re-Imported Input Bucket', inputBucket.bucketArn);
reImportedInputBucket.addObjectCreatedNotification(lambdaDestination);
```

**Closed** 2021-08-11 23:52 UTC
Labels: bug, p1, @aws-cdk/aws-stepfunctions, effort/medium
