### ISSUE TITLE
(step_functions): Support new (12/1/2022) Map fields

### ISSUE THREAD

**Issue by dschultz0** [aws/aws-cdk#23837] opened 2023-01-25 19:31 UTC
### Describe the feature

The Amazon States Language used by Step Functions added new Map fields that increase the utility of step functions for parallel processing: https://states-language.net/#2022-12-01. These new fields support the "Distributed" processing mode described here: https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-map-state.html

These fields are not currently available from the CDK in any of the variants: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions.Map.html

### Use Case

These updates to the States Language are a big step forward in improving the utility of Step Functions, particularly building data processing pipelines that benefit from parallel processing across a large corpus of data. Being able to leverage these through CDK created state machines would enable a greater range of uses for Step Functions.

### Proposed Solution

Add the additional fields.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.61.1

### Environment details (OS name and version, etc.)

Windows, Python

**Comment by ffxsam** [comment] 2023-01-31 21:00
Would love to see some progress on this soon!

**Comment by peterwoodworth** [comment] 2023-02-07 03:01
Thanks for the request! I'm going to close this as a duplicate of https://github.com/aws/aws-cdk/issues/23216, please leave a thumbs up on that issue if you would like to give your support 🙂

**Closed by peterwoodworth** 2023-02-07 03:01 UTC
Labels: duplicate, feature-request, @aws-cdk/aws-stepfunctions
