### ISSUE TITLE
[aws-eks] Default NodeGroup uses all subnets of VPC instead of selected ones

### ISSUE THREAD

**Issue by dmoser04** [aws/aws-cdk#10312] opened 2020-09-11 17:31 UTC
When creating an EKS cluster with a custom subnet selection, the default NodeGroup tries to use all subnets of the VPC instead of the selected ones, which results in CloudFormation failing with `Subnets are not tagged with the required tag. Please tag all subnets with Key: kubernetes.io/cluster/...`

### Reproduction Steps

```typescript
const vpc = ec2.Vpc.fromLookup(this, "myvpc", {
  vpcId: "<VPC ID of VPC with multiple private subnets>"
});

const cluster = new eks.Cluster(this, "mycluster", {
  clusterName: "mycluster",
  version: eks.KubernetesVersion.V1_17,
  defaultCapacityType: eks.DefaultCapacityType.NODEGROUP,
  defaultCapacity: 2,
  defaultCapacityInstance: new ec2.InstanceType(defaultCapacityInstance),
  endpointAccess: eks.EndpointAccess.PRIVATE,
  vpc: vpc,
  vpcSubnets: [
    {subnets: vpc.privateSubnets.slice(0, 1)}
  ]
});
```

### What did you expect to happen?

The CloudFormation deployment should succeed and the NodeGroup should use only the specified subnets

### What actually happened?

CloudFormation failed with `Subnets are not tagged with the required tag. Please tag all subnets with Key: kubernetes.io/cluster/...`. CloudTrail log proves that indeed all subnets of the VPC are included in the `CreateNodegroup` call instead of only the selected ones.

### Environment

  - **CLI Version      :** 1.62.0 (build 8c2d7fc)
  - **Framework Version:** 1.62.0 (build 8c2d7fc)
  - **Node.js Version:** 12.18.3
  - **OS               :**
  - **Language (Version):** TypeScript

### Other

When the default Nodegroup is created, no subnets are passed to the constructor (https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L991), therefore `props.subnets` in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-eks/lib/managed-nodegroup.ts#L272 is empty and all subnets are selected.

So I guess `this.addNodegroup('DefaultCapacity', { instanceType, minSize: minCapacity })` should instead be something like `this.addNodegroup('DefaultCapacity', { instanceType, minSize: minCapacity, subnets: this.vpcSubnets })`

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2020-09-20 21:00
@dmoser04 Thanks for reporting this. 

As a workaround for anyone interested, you can add capacity post instantiation with specific subnet selection:

```typescript
const cluster = new eks.Cluster(this, "mycluster", {
  clusterName: "mycluster",
  version: eks.KubernetesVersion.V1_17,
  defaultCapacityType: eks.DefaultCapacityType.NODEGROUP,
  endpointAccess: eks.EndpointAccess.PRIVATE,
  vpc: vpc,
  vpcSubnets: [
    {subnets: vpc.privateSubnets.slice(0, 1)}
  ]
});

cluster.addNodeGroup('node-group', {
  subnets: { subnets: vpc.privateSubnets.slice(0, 1) },
  minSize: 2,
})
```

**Comment by otaviomacedo** [comment] 2021-12-16 16:21
Duplicate of https://github.com/aws/aws-cdk/issues/17023.

**Closed by otaviomacedo** 2021-12-16 16:21 UTC
Labels: bug, p1, @aws-cdk/aws-eks, effort/small
