### ISSUE TITLE
pipelines: allow selfmutate stage to run in privildged mode. 

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#14206] opened 2021-04-16 09:26 UTC
My cdk pipeline based pipelines use some docker images as the executable for lambdas.  Specifically, i have a lambda that clones a repo from AzureDevops which has no native integration.    There is an option to when configuring a pipeline to allow the synth action to run in privildged mode.   This allows my pipeline to build its docker images.   

However it does not allow the selfmutate codebuild project to run in privildged mode.  So, if a change to the pipeline itself is pushed, the self mutate stage fails. 

### Proposed Solution

I have implemented a workaround using escape hatches. to resolve this...   however this is a workaround to solve the problem. 
```
#Breakout the escape hatches, and make the self mutating codebuild run privilidged
        if pipeline_cfg['Pipeline']['SelfMutate'] == True:
            mutating_codebuild = self.pipeline.node.find_child(id ='UpdatePipeline')
            codebuild_project = mutating_codebuild.node.find_child(id ='SelfMutation')
            raw_code_build = codebuild_project.node.default_child    
            raw_code_build.add_override("Properties.Environment.PrivilegedMode", "True")
```
I would suggest that if the the pipeline is configured to self mutate, that both the build and self mutate stages shoudl be set to run in Privildge mode..

As far as i can tell the only time you really need it to run in privilidged mode, is if you are bundling lambdas, or building docker images that form part of the pipeline itself. 

This is a :rocket: Feature Request

**Comment by mrpackethead** [comment] 2021-04-16 23:24
Just to add some clarification:

My 'pipeline' stack, which uses cdk pipeline builds lambda ECR images, for lambdas that are used **IN** the pipeline stack.  It also could potentially also bundle lambdas that are used as part of the pipeline.      In my case the lambdas are being used to do integratation with Azure Devops. 

Because they are **PART** of the pipeline stack, if the pipeline needs to mutate, you potentially need to rebuild them, that means that the self mutate stage needs to be able to run in prividlged mode. 

If you are building images ( or bundling lambdas ) that are part of the stacks that the pipeline is deploying then you dont' have this issue. 

This might be a bit of corner case, but it is a case non the less.

**Comment by mrpackethead** [comment] 2021-04-21 04:11
Adding yet another note to this..

Not only do i need to add prividlged, it would also be useful to set the compute type, so i can use a larger build container.

**Comment by rix0rrr** [comment] 2021-04-21 12:29
Duplicate of #11425.

**Closed by rix0rrr** 2021-04-21 12:29 UTC
Labels: @aws-cdk/pipelines, feature-request, needs-triage
