### ISSUE TITLE
[sam] 'version' field should be optional but is mandatory

### ISSUE THREAD

**Issue by nsstensoriot** [aws/aws-cdk#3841] opened 2019-08-28 20:19 UTC
### What is the problem?
When using the Python aws_sam module, and trying to declare a CfnApi object, the definition_uri is requiring 'version', when the documentation says it should be an optional field.

### Reproduction Steps

Try to create a Python CfnApi object instance, like so:

```
        self.serverlessAPI = sam.CfnApi(
            scope=self.scope,
            id=apiName,
            name=apiName,
            stage_name=self.scope.config['ApiGatewayStageName'],
            definition_uri={'bucket': mySwaggerS3File.s3_bucket_name, 'key': mySwaggerS3File.s3_object_key}
        )

```

If you run 'cdk synth', it'll error out. The log is provided below.

### Verbose Log
```
Traceback (most recent call last):
  File "stack.py", line 72, in <module>
    myStack = BaseStack(app)
  File "/Users/harmony/project/cdkstack/env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "stack.py", line 33, in __init__
    self.stackApiGateway = stackApiGateway.APIGatewayResources(self, './swagger/swagger.yaml')
  File "/Users/harmony/project/cdkstack/stackModules/apiGateway.py", line 18, in __init__
    definition_uri={'bucket': mySwaggerS3File.s3_bucket_name, 'key': mySwaggerS3File.s3_object_key}
  File "/Users/harmony/project/cdkstack/env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/harmony/project/cdkstack/env/lib/python3.7/site-packages/aws_cdk/aws_sam/__init__.py", line 45, in __init__
    jsii.create(CfnApi, self, [scope, id, props])
  File "/Users/harmony/project/cdkstack/env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 208, in create
    overrides=overrides,
  File "/Users/harmony/project/cdkstack/env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 331, in create
    return self._process.send(request, CreateResponse)
  File "/Users/harmony/project/cdkstack/env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 316, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Value did not match any type in union: Expected Scalar, got {"bucket":"${Token[TOKEN.71]}","key":"${Token[TOKEN.74]}${Token[TOKEN.76]}"},Expected object reference, got {"bucket":"${Token[TOKEN.71]}","key":"${Token[TOKEN.74]}${Token[TOKEN.76]}"},Missing required properties for @aws-cdk/aws-sam.CfnApi.S3LocationProperty: version
```
### Environment

  - **CDK CLI Version:** 1.6.0 (build 3a0cde0)
  - **Module Version:** aws-cdk.aws-sam==1.6.0
  - **OS:** OSX Mojave
  - **Language:** Python

### Other information
Here's the documentation that says the 'version' for the bucket should be optional:
[https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3-location-object)

**Comment by nija-at** [comment] 2019-09-24 11:02
Confirmed that this is an issue and is not isolated with Python.

It looks like SAM schema [does state](https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/validator/sam_schema/schema.json#L111-L125) that the `version` field of the `AWS::Serverless::Api.S3Location` is not mandatory. However, CDK enforces the presence of this field.

The issue is coming from the SAM schema [defined in the Goformation repo](https://github.com/awslabs/goformation/blob/master/schema/sam.schema.json). CDK [uses this as the SAM schema](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/cfnspec/build-tools/update.sh#L52-L56) to generate its language bindings.

**Comment by nija-at** [comment] 2019-09-24 11:07
There's an existing discussion on this in the Goformation repo - https://github.com/awslabs/goformation/issues/87

**Comment by nija-at** [comment] 2019-10-18 09:28
This has fixed in goformation. Awaiting propagation to CDK.

**Comment by nija-at** [comment] 2019-11-07 14:24
Change is now in the CDK - https://github.com/aws/aws-cdk/commit/fd167c37927a5524bc4a064c28f07b5bcb30e9ac#diff-2a4aee8c725dbbe91207a037eecbb2dd

Closing.

**Closed by nija-at** 2019-11-07 14:24 UTC
Labels: bug, package/cfn, package/sam, status/in-progress

**Comment by prestomation** [comment] 2020-04-15 08:13
This was never fixed. The original issue is about `AWS::Serverless::Api.S3Location`, but the fix was for `AWS::Serverless::Function.S3Location`.

Can we  get this same fix for the Api resource?
