### ISSUE TITLE
(All) Fields of DomainNameAttributes should be made optional

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#6804] opened 2020-03-19 03:15 UTC
In order to be able to create an Alias record on Route53 with an API Gateway target, one needs to use the `DomainNameAttributes` interface. However, currently all fields of `DomainNameAttributes` are required, which makes it difficult to use.

### Reproduction Steps

1. Create a public hosted zone on Route53.
1. Try to add an `ARecord` targeting an existing api gateway.
1. The `ARecord` constructor requires `target` field of type `RecordTarget`.
1. The `RecordTarget` constructor takes a field, `aliasTarget`, of type `IAliasRecordTarget`.
1. The constructor of `ApiGatewayDomain`, which implements `IAliasRecordTarget`, requires an argument of type, `IDomainName`.
1. An object of type `IDomainName` can be obtained by calling `DomainName.fromDomainNameAttributes()`.
1. `fromDomainNameAttributes()` takes an argument of type `DomainNameAttributes`.
1. There is currently no easy way to construct a `DomainNameAttributes` object because all of its properties are required, `domainName`, `domainNameAliasHostedZoneId`, and `domainNameAliasTarget`.
 
### Error Log

N/A

### Environment

  - **CLI Version - 1.30.0 (build 4f54ff7)     :**
  - **Framework Version: 1.30.0 ;**
  - **OS               Ubuntu 18:**
  - **Language         Typescript:**

### Other

This is needed, among other things, to support naked domains (zone apex record) pointing to the API Gateway. 

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment] 2020-03-19 20:59
Related to #6803

**Comment by nija-at** [comment] 2020-03-20 10:55
(this is not a bug, switching the type to feature-request)

You are referring to the [`fromDomainNameAttribute()` import API](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.DomainName.html#static-from-wbr-domain-wbr-name-wbr-attributesscope-id-attrs). 

This is kept in line with what [CloudFormation returns](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#aws-resource-apigateway-domainname-return-values) when a new Domain is created. This is so that, after importing, the CDK doesn't differentiate very much between an imported `Domain` and a `Domain` that was created in the app. This ensures that all features that are implemented or implemented are consistent between these two.

Can you describe your use case on why you would not or unable to provide these?

**Comment by realharry** [comment] 2020-03-20 13:21
Hi @nija-at Thanks for the reply. Here's what I want to do: "create an Alias record on Route53 with an API Gateway target". Can you please tell me how this can be done? Maybe, an example would be very helpful. The distinction between "feature request" and "bug" is not that meaningful, in my view. the api (seems to) provides a way to achieve this, and yet I couldn't do it. as far as I'm concerned, there is a problem with api design. thanks!

**Comment by nija-at** [comment] 2020-04-03 10:34
We have code snippets available for this in our route53 documentation page - https://docs.aws.amazon.com/cdk/api/latest/docs/aws-route53-targets-readme.html

The following code should work. The code assumes that you already have a valid certificate that you can associate with the domain -

```ts
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { RestApi } from '@aws-cdk/aws-apigateway';
import { HostedZone, ARecord, RecordTarget } from '@aws-cdk/aws-route53'
import { ApiGateway } from '@aws-cdk/aws-route53-targets'
import { Certificate } from '@aws-cdk/aws-certificatemanager';

const app = new App();
const stack = new Stack(app, 'myroute53stack');

const cert = Certificate.fromCertificateArn(stack, 'certificate', '<certiticate arn>');

const api = new RestApi(stack, 'myrestapi');
api.addDomainName('muydomainname', {
  domainName: 'https://example.com',
  certificate: cert 
});
api.root.addMethod('ANY');

const hostedzone = new HostedZone(stack, 'myhostedzone', {
  zoneName: 'myhostedzone'
});

new ARecord(stack, 'myrecordset', {
  zone: hostedzone,
  target: RecordTarget.fromAlias(new ApiGateway(api)),
});
```

Does that help?

**Comment by SomayaB** [comment] 2020-04-14 17:06
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Closed by SomayaB** 2020-04-14 17:06 UTC
Labels: closing-soon, guidance, package/apigateway

**Comment by bmVsc29u** [comment] 2020-12-25 16:55
@nija-at's solution is totally ok for certain use cases, but consider the scenario to manage `route53` and `api-gateway` stacks separately in different repositories, the below seems impossible and even the documentation does not helped with such field **domainNameAliasTarget**:

```typescript
// shorthands are given
 const d = DomainName.fromDomainNameAttributes(this, 'domain', {
            domainName,
            domainNameAliasTarget: **'what should I filled up for this?',**
            domainNameAliasHostedZoneId
        })
 const aliasApi = new ARecord(this, `alias.api`, {
            zone,
            recordName,
            target: RecordTarget.fromAlias(new ApiGatewayDomain(d)),
        });
```
