### ISSUE TITLE
AppSync: support for AWS_IAM authorization type

### ISSUE THREAD

**Issue by oleh-kolinko** [aws/aws-cdk#6772] opened 2020-03-17 14:52 UTC
Currently, there is no support for AWS_IAM authorization type for AppSync, only API_KEY & AMAZON_COGNITO_USER_POOLS available

### Use Case

In my application, I use User Pool authorization but I also need additional authorization for backend and internal processes and the best approach is to use IAM_AUTH as stated in [here](https://aws.amazon.com/blogs/mobile/supporting-backend-and-internal-processes-with-aws-appsync-multiple-authorization-types/)

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by 0xdevalias** [comment] 2020-04-08 05:30
According to CloudFormation, there doesn't appear to be any other configuration options required when using IAM, just a matter of setting the appropriate `AuthenticationType` keys to `AWS_IAM`:

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlapi.html#cfn-appsync-graphqlapi-authenticationtype
  - > Security configuration for your GraphQL API. For allowed values (such as API_KEY, AWS_IAM, or AMAZON_COGNITO_USER_POOLS, OPENID_CONNECT),
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-additionalauthenticationproviders.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-additionalauthenticationprovider.html#cfn-appsync-graphqlapi-additionalauthenticationprovider-authenticationtype
  - > API key, AWS IAM, OIDC, or Amazon Cognito user pools.

**Comment by kastork** [comment] 2020-04-30 21:06
I'm trying to accomplish something similar to this by modeling my CDK stack after the templates generated by Amplify.  Here's what Amplify produces as a CF Template when trying to use IAM as a way to provide both authenticated and unauthenticated access to appsync.
```
  IdentityPool:
  # Always created
    Type: AWS::Cognito::IdentityPool
    Properties: 
      IdentityPoolName: !If [ShouldNotCreateEnvResources, 'ngc35ff4b0e_identitypool_35ff4b0e', !Join ['',['ngc35ff4b0e_identitypool_35ff4b0e', '__', !Ref env]]]
      
      CognitoIdentityProviders:
        - ClientId:  !Ref UserPoolClient
          ProviderName: !Sub
            - cognito-idp.${region}.amazonaws.com/${client}
            - { region: !Ref "AWS::Region",  client: !Ref UserPool}
        - ClientId:  !Ref UserPoolClientWeb
          ProviderName: !Sub
            - cognito-idp.${region}.amazonaws.com/${client}
            - { region: !Ref "AWS::Region",  client: !Ref UserPool}
            
      AllowUnauthenticatedIdentities: !Ref allowUnauthenticatedIdentities
       
       
    DependsOn: UserPoolClientInputs 
    
  
  IdentityPoolRoleMap:
  # Created to map Auth and Unauth roles to the identity pool
  # Depends on Identity Pool for ID ref
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties: 
      IdentityPoolId: !Ref IdentityPool
      Roles:
          unauthenticated: !Ref unauthRoleArn
          authenticated: !Ref authRoleArn
    DependsOn: IdentityPool

```

I can't seem to replicate this with `CfnIdentityPoolRoleAttachment`

because this...
(I'm leaving out the definitions for `AuthRole` and `UnAuthRole` since this is already long enough)

```
// This is kotlin code with the java cdk.
	val identityPool: CfnIdentityPool = CfnIdentityPool.Builder.create(this, "idp")
			.allowUnauthenticatedIdentities(true)
			.cognitoIdentityProviders(listOf(webClientIdp, appClientIdp))
			.build()

	val roleMappings = CfnIdentityPoolRoleAttachment.Builder.create(this, "IdentityPoolRoleMap")
			.identityPoolId(identityPool.logicalId)
			.roles(mapOf(
					"authenticated" to authRole.attrArn,
					"unauthenticated" to unAuthRole.attrArn
			))
			.build()
```
produces this
```
    "idp": {
      "Type": "AWS::Cognito::IdentityPool",
      "Properties": {
        "AllowUnauthenticatedIdentities": true,
        "CognitoIdentityProviders": [
          {
            "ClientId": {
              "Ref": "UserPoolClientWebAA099225"
            },
            "ProviderName": {
              "Fn::ImportValue": "ngsuserpoolFD3AC84D:userpoolExportsOutputFnGetAttpool056F3F7EProviderNameFE989B1F"
            }
          },
          {
            "ClientId": {
              "Ref": "UserPoolClientAppE719858A"
            },
            "ProviderName": {
              "Fn::ImportValue": "ngsuserpoolFD3AC84D:userpoolExportsOutputFnGetAttpool056F3F7EProviderNameFE989B1F"
            }
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "ngs/user-authn/idp"
      }
    },

    "IdentityPoolRoleMap": {
      "Type": "AWS::Cognito::IdentityPoolRoleAttachment",
      "Properties": {
        "IdentityPoolId": "idp",
        "Roles": {
          "authenticated": {
            "Fn::GetAtt": [
              "AuthRole",
              "Arn"
            ]
          },
          "unauthenticated": {
            "Fn::GetAtt": [
              "UnAuthRole",
              "Arn"
            ]
          }
        }
      },
      "DependsOn": [
        "AuthRole",
        "idp",
        "UnAuthRole"
      ],
      "Metadata": {
        "aws:cdk:path": "ngs/user-authn/IdentityPoolRoleMap"
      }
    }
```

The problem is on the line

```
      "Properties": {
        "IdentityPoolId": "idp",
```
Which I think should instead be
```
      "Properties": {
        "IdentityPoolId": {
             "Ref": "idp"
        },
```

**Comment by kastork** [comment] 2020-05-04 16:37
Got my example working by discovering a property on `CfnIdentityPoolRoleAttachment.Builder`

Where I had put

```
val roleMappings = CfnIdentityPoolRoleAttachment.Builder.create(this, "IdentityPoolRoleMap")
	.identityPoolId(identityPool.logicalId)  // PROBLEM IS HERE
	.roles(mapOf(
		"authenticated" to authRole.attrArn,
		"unauthenticated" to unAuthRole.attrArn
	)).build()
```

I put instead, 

```
val roleMappings = CfnIdentityPoolRoleAttachment.Builder.create(this, "IdentityPoolRoleMap")
	.identityPoolId(identityPool.ref)  // CHANGE IS HERE
	.roles(mapOf(
		"authenticated" to authRole.attrArn,
		"unauthenticated" to unAuthRole.attrArn
	)).build()
```

And the reference is properly rendered.

**Comment by BryanPan342** [comment] 2020-07-08 04:12
Hi @oleh-kolinko! I'm taking on this issue and want to scope out the issue completely. I see the current codebase has implementation for `User_Pool` and `OIDC`.

> https://github.com/aws/aws-cdk/blob/61e7094bed83b74014d517910b395e7051afd0ca/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L331-L338

> https://github.com/aws/aws-cdk/blob/61e7094bed83b74014d517910b395e7051afd0ca/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L323-L330

And I'm guessing you're getting an error from here
https://github.com/aws/aws-cdk/blob/61e7094bed83b74014d517910b395e7051afd0ca/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L471-L478

I will try to get this done by the end of the week since we have much support for this issue! Also I'm curious if you're looking for something like a `addAuthentication` from your statement here:

> I also need additional authorization for backend and internal processes and the best approach is to use IAM_AUTH as stated in here

If anyone cares to add any comment to this please add it below!

**Comment by oleh-kolinko** [comment] 2020-07-08 15:05
In my use case, I need to have 2 auth modes (User Pool & IAM), which you can do with config 
https://github.com/aws/aws-cdk/blob/61e7094bed83b74014d517910b395e7051afd0ca/packages/%40aws-cdk/aws-appsync/lib/graphqlapi.ts#L165-L179
By adding the first mode in `defaultAuthorization` and then add the second mode into `additionalAuthorizationModes`. 
Having 2+ modes is currently possible so something like `addAuthentication` not needed but would be nice to have.

The problem is you can't use IAM in either one because of a lack of implementation.

That error you mentioned happens when there is duplicated AuthorizationType value IAM in `defaultAuthorization` and `additionalAuthorizationModes` which I think is expected as you should not duplicate modes.

**Comment by BryanPan342** [comment] 2020-07-08 15:31
@oleh-kolinko thanks for the clarification! I read the code base today and saw the missing implementation and already working on it :) Goal is to get a PR today/tomorrow and have it merged by friday

**Comment by oleh-kolinko** [comment] 2020-07-08 16:04
@BryanPan342 Thank you
If you have a chance take a look to the related issue https://github.com/aws/aws-cdk/issues/6773

**Comment by BryanPan342** [comment] 2020-07-16 15:31
@oleh-kolinko A PR is in review right now. 

`IAM` doesn't require any configuration as an Authorization Type. It enables authorization via `IAM` headers (which are generated with AWS service calls through role policies). 

In order to use `IAM`, you going to need to have the right policies to allow access to the resources you specify. I implemented a couple `grant` methods to make this easier to use. 

Hopefully, this clears up some confusion on how it `IAM` works!

**Comment by BryanPan342** [comment] 2020-07-20 22:18
Just for posterity and reference, to utilize `AWS_IAM` as an authorization mode you need to do 3 things:

1. Set configuration to `AWS_IAM`
```ts
const api = new appsync.GraphQLApi(stack, 'API', {
  //...
  authorizationConfig: {
    defaultAuthorization: {
      authorizationType: appsync.AuthroizationType.AWS_IAM,
    }
  },
});
```
2. Give permissions to an role to allow for certain resources:
```ts
const role = new iam.Role(...);
api.grant(role, appsync.IamResource.custom('types/Query/fields/getExample'), 'appsync::GraphQL');
```
This will create policy that allows the `role` to execute the operation `getExample`.

3. If you have MULTIPLE authorization configurations, make sure to use directive `@aws_iam` in your `schema.graphql` file
```gql
...
type Query {
  getExample(...): ...
    @aws_iam
}
...
```

**Closed** 2020-07-23 22:43 UTC
Labels: @aws-cdk/aws-appsync, effort/medium, feature-request, in-progress, p2
