### ISSUE TITLE
cdk pipelines: CDK bootstrap names should not be hardcoded into mutation policies

### ISSUE THREAD

**Issue by mtgrasse** [aws/aws-cdk#12991] opened 2021-02-11 17:47 UTC
The roles that are created for CDK Pipelines have the following policies to allow the the deployment to self-mutate:

```
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Resource": [
                "arn:*:iam::*:role/*-deploy-role-*",
                "arn:*:iam::*:role/*-publishing-role-*"
              ]
            },

```

It appears this policy is created from update-pipeline-action.ts:79

```
    selfMutationProject.addToRolePolicy(new iam.PolicyStatement({
      actions: ['sts:AssumeRole'],
      resources: ['arn:*:iam::*:role/*-deploy-role-*', 'arn:*:iam::*:role/*-publishing-role-*'],
    }));
```

It's possible, however, to change the names of the relevant policies using a custom bootstrap template. If you don't
create a role name that matches the above pattern, the mutation step will fail when the pipeline runs

### Reproduction Steps

1. Create a custom bootstrap template that uses a name that does not match the above pattern
2. Deploy any self-mutating pipeline

### What did you expect to happen?

Expected the pipeline to run successfully

### What actually happened?

The mutation step in the pipeline fails to assume the deployment role

### Environment

  - **CDK CLI Version  : 1.88.0**
  - **Framework Version: 1.88.0**
  - **Node.js Version: 14.15.4** 
  - **OS               : macOS**
  - **Language (Version):  python 3.9.1** 

### Other

There's an obvious workaround which is to use names that match the pattern.  That is what I am doing now.

Preferred approach would be to use the names passed to the DefaultStackSynthesizer when generating this policy

Alternatively, better doc and the expected pattern names, and warnings during bootstrap if they don't match would have saved a good bit of time sorting this issue out

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-02-15 10:28
Duplicate of #9271.

**Closed by rix0rrr** 2021-02-15 10:28 UTC
Labels: @aws-cdk/pipelines, bug, needs-triage
