### ISSUE TITLE
(cli): `cdk deploy specific-stack` should not synthesize all stacks

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#26421] opened 2023-07-19 08:48 UTC
### Describe the bug

When synthesizing or deploying a single stack, CDK synthesizes ALL stacks that are part of the app, regardless of any `.addDependency()` clauses.

### Expected Behavior

I would expect CDK to synthesize only the stack that was requested as well as its direct dependencies.

### Current Behavior

CDK synthesizes the whole app, causing a tremendous overhead and bad developer experience.

A typical setup of splitting the stacks by lifecycle:
e.g. Layer 1 - DB stacks, VPC/Networking stacks, Storage stacks
Layer 2 - Compute
Layer 3 - Domains and Certificates and CloudFront related

When working on Layer 2 stuff on a daily basis, one is forced to "wait" for the Layer 1 stacks to be synthesized all the time, considering that they rarely change and I've never requested to deploy them (e.g. I'm only deploying some specific stack from Layer 2).

### Reproduction Steps

Create a DB stack
Create an API Gateway stack
Create a stack to hold a bunch of Lambdas
Don't touch the DB or API Gateway stacks
Work on the Lambdas on a daily basis (a typical setup for a lot of companies)
Synthesize and deploy the Lambda stacks
You get a bunch of latency in the whole list of stacks being synthesized

### Possible Solution

Propagate the provided stack name to the framework, so CDK can skip the synthesis of skipped stacks

### CDK CLI Version

2.43.1 (build c1ebb85)

### Node.js Version

18

### OS

MacOS

### Language

Typescript

**Comment by khushail** [comment] 2023-07-19 22:53
Hi @Dzhuneyt , thanks for reaching out.
Is [this](https://docs.aws.amazon.com/cdk/v2/guide/cli.html#cli-deploy) something you are trying to do ? 

```
Skipping synthesis

The cdk deploy command normally synthesizes your app's stacks before deploying to make sure that the deployment reflects the latest version of your app. If you know that you haven't changed your code since your last cdk synth, you can suppress the redundant synthesis step when deploying. To do so, specify your project's cdk.out directory in the --app option.

cdk deploy --app cdk.out StackOne StackTwo
```

let me know if this doesn't help.

**Comment by Dzhuneyt** [comment] 2023-07-31 12:38
@khushail that's actually a different scenario. What you are describing is:
Skipping synthesis completely and jumping straight to deploy

The issue I describe is:
In a multi-stack environment, synthesize and deploy just specific stack(s) and skip others.

**Comment by peterwoodworth** [comment] 2023-08-09 20:35
Seems to be a duplicate of this https://github.com/aws/aws-cdk/issues/6743 or this https://github.com/aws/aws-cdk/issues/26589

**Closed** 2023-08-09 20:35 UTC
Labels: bug, duplicate, response-requested, package/tools, @aws-cdk/aws-cloudfront
