### ISSUE TITLE
CDK CLI: TTL Option for bootstrap bucket

### ISSUE THREAD

**Issue by mikebroberts** [aws/aws-cdk#21928] opened 2022-09-06 13:03 UTC
### Describe the feature

Be able to specify an optional TTL in days as a command line argument when running `cdk bootstrap` . This would translate to a lifecycle policy with an "ExpirationInDays" value on the CDK bootstrap bucket.

### Use Case

For teams who solely use `cdk deploy` to deploy, rather than a separate synth vs subsequent deploy, and (for example) who don't have containers in their stack, the current bootstrap bucket will grow without constraint for no good reason. For such teams it would be useful to be able to specify at bootstrap time a lifecycle policy on the bootstrap bucket to expire contents after (say) 7 days.

The current workarounds are (a) to use a custom bootstrap template, but that is a lot more work when capturing future CDK changes, or (b) to manually add a lifecycle policy to the bootstrap bucket, but that introduces drift.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.36.0

### Environment details (OS name and version, etc.)

Mac, latest version

**Comment by jogold** [comment] 2022-09-06 20:44
https://github.com/jogold/cloudstructs/blob/master/src/toolkit-cleaner/README.md

**Comment by peterwoodworth** [comment] 2022-09-07 18:37
We're actually working on a feature real similar to this which should address your needs @mikebroberts. I'm going to close this as a duplicate of #6692 

Until we introduce this feature, you can [customize the bootstrap template](https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html#bootstrapping-customizing) to configure a lifecycle policy, or anything else on your bootstrapping resources

**Closed** 2022-09-07 18:38 UTC
Labels: feature-request, package/tools

**Comment by mikebroberts** [comment] 2022-09-07 20:03
@peterwoodworth - thanks. I did see that issue but until you just changed the issue name it seemed ECR specific, which is why I posted this new issue.

I mentioned the custom template in my original issue - there are long term maintainability issues with such an approach.
