### ISSUE TITLE
Memory . data type in fargate task definition

### ISSUE THREAD

**Issue by w601sxs** [aws/aws-cdk#5361] opened 2019-12-10 17:23 UTC
Currently memory in the main Task definition is a string but memory limit is an int / float. Can this be consistent? Any strong reason to do this?

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/TaskDefinition.html

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pkandasamy91** [comment] 2019-12-10 23:23
Duplicate of https://github.com/aws/aws-cdk/issues/5088

**Closed by pkandasamy91** 2019-12-10 23:23 UTC
Labels: feature-request, package/ecs, status/needs-triage
