### ISSUE TITLE
(core): `Stack` should be able to provide template body as variable

### ISSUE THREAD

**Issue by IngussNeilands** [aws/aws-cdk#12396] opened 2021-01-07 13:53 UTC
aws_cdk_core.Stack should be able to provide cloudformation template body as variable so we could reuse it.

For example:

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_cloudformation/CfnStackSet.html#aws_cdk.aws_cloudformation.CfnStackSet.template_body

`AWS::CloudFormation::StackSet.TemplateBody` could be provided by another Stack output.

---

This is a :rocket: Feature Request

**Comment by redbaron** [comment] 2021-01-07 18:01
There is a workaround with cdk.Stage, see https://github.com/aws/aws-cdk-rfcs/issues/66#issuecomment-754599325

**Comment by IngussNeilands** [comment] 2021-01-11 10:37
Thanks for a workaround , but I suggest it needs a proper solution :)

**Comment by rix0rrr** [comment] 2021-02-08 16:21
Duplicate of https://github.com/aws/aws-cdk/issues/12249

**Closed by rix0rrr** 2021-02-08 16:21 UTC
Labels: @aws-cdk/core, feature-request, needs-triage
