### ISSUE TITLE
[core] AWS CDK 1.69.0 not compatible with Python 3.9

### ISSUE THREAD

**Issue by pinkolivia** [aws/aws-cdk#11043] opened 2020-10-22 18:26 UTC
AWS CDK 1.69.0 not compatible with Python 3.9.

### Reproduction Steps

run `CDK Synth` command in Python3.9 enviroment

### What did you expect to happen?
run `CDK Synth` command in Python3.9 enviroment with no error

### What actually happened?

```console
Traceback (most recent call last):
File "C:\i-003bb62df2b1f10c1\_work\8\s\app.py", line 3, in <module> from aws_cdk import core File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\aws_cdk\core\__init__.py", line 904, in <module> import jsii File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\jsii\__init__.py", line 4, in <module> from ._runtime import ( File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\jsii\_runtime.py", line 10, in <module> from ._kernel import Kernel File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\jsii\_kernel\__init__.py", line 15, in <module> from .providers import BaseProvider, ProcessProvider File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\jsii\_kernel\providers\__init__.py", line 2, in <module> from .process import ProcessProvider File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\jsii\_kernel\providers\process.py", line 15, in <module> import cattr # type: ignore File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\cattr\__init__.py", line 2, in <module> from .converters import Converter, UnstructureStrategy File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\cattr\converters.py", line 15, in <module> from ._compat import ( File "C:\i-003bb62df2b1f10c1\_work\8\s\.env\lib\site-packages\cattr\_compat.py", line 87, in <module> from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (C:\Python39\lib\typing.py) Subprocess exited with error 1
Error: Subprocess exited with error 1
at ChildProcess.<anonymous> (C:\Users\ADOservice\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\cxapp\exec.ts:117:23)
at ChildProcess.emit (events.js:314:20) at ChildProcess.EventEmitter.emit (domain.js:486:12) at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

### Environment

  - **CLI Version      :** aws-cli/2.0.6
  - **Framework Version:** 
  - **Node.js Version:** v12.16.3
  - **OS               :** Windows10
  - **Language (Version):** Python 3.9
  - **CDK Version:** 1.69.0

### Other

--- 

This is :bug: Bug Report

**Comment by Joe-Zer0** [comment] 2020-10-22 19:53
I am having the same issue.
```
node --version
v12.11.1

cdk --version
1.69.0 (build 2b474b9)

python --version
Python 3.9.0

aws --version
aws-cli/2.0.25 Python/3.7.7 Windows/10 botocore/2.0.0dev29
```

**Comment by SomayaB** [comment] 2020-10-26 20:38
Duplicated by #11102

**Comment by MrArnoldPalmer** [comment] 2020-10-26 23:40
So this same error happened with the release of python 3.8 as well. https://github.com/aws/jsii/issues/913

It's caused by the `cattrs` dependency in JSII. [There is an issue](https://github.com/Tinche/cattrs/issues/100) for it already and apparently it has been fixed on master and should be released soon.

**Comment by RomainMuller** [comment] 2020-11-06 08:53
`cattrs` has actually released `1.1.0` which is compatible with Python 3.9, and as a result, jsii >= 1.14.0 would be compatible with Python 3.9.

**Closed by RomainMuller** 2020-11-06 08:53 UTC
Labels: @aws-cdk/core, bug, language/python, p1

**Comment by nitin-bit** [comment] 2020-11-13 06:34
Is there any workaround for this issue to move forward. Struggling to run the cdk synth command as it gives the error message as shared ealier

**Comment by nitin-bit** [comment] 2020-11-13 06:36
CDK Version : 1.73.0
Python version: 3.8.3
OS Version : Windows 10

**Comment by victormwenda** [comment] 2021-01-21 14:20
(.venv) C:\Users\...\AWS-CDK>`cdk synth`
Traceback (most recent call last):
  File "C:\Users\...\AWS-CDK\app.py", line 3, in <module>
`    from aws_cdk import core`
ImportError: cannot import name 'core' from 'aws_cdk' (C:\Users\...\AWS-CDK\aws_cdk\__init__.py)
Subprocess exited with error 1

```
cdk --version === 1.85.0 (build 5f44668)
python --version === Python 3.9.1
npm --version === 6.14.6
```

**Comment by Jerry-AWS** [comment] 2021-01-28 01:31
I can't reproduce this with CDK v1.87. Is it possible that you didn't activate your virtual environment or do the `pip install` of the base requirements?
