### ISSUE TITLE
dynamodb: Nested stack cannot depend on a parent stack when replicationRegions specified

### ISSUE THREAD

**Issue by cmckni3** [aws/aws-cdk#6726] opened 2020-03-14 15:35 UTC
Nested stack `synth` fails with error when `replicationRegions` is set on DynamoDB Table.

### Reproduction Steps

```typescript
import { Construct, Stack, StackProps } from '@aws-cdk/core';
import { NestedStack } from '@aws-cdk/aws-cloudformation';
import { Table, AttributeType } from '@aws-cdk/aws-dynamodb';

export class DynamoNestedStack extends NestedStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new Table(this, 'MyTable', {
      partitionKey: { name: 'pk', type: AttributeType.STRING },
      replicationRegions: ['us-east-2', 'us-west-1'],
    });
  }
}

export class CdkNested6726Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new DynamoNestedStack(this, 'DynamoStack');
  }
}
```

### Error Log

Here's the error during **synth**.

```
     throw new Error(`Nested stack '${sourceStack.node.path}' cannot depend on a parent stack '${targetStack.node.path}'`);
           ^
Error: Nested stack 'CdkNested6726Stack/DynamoStack' cannot depend on a parent stack 'CdkNested6726Stack'
```

### Environment

  - **CLI Version      : 1.24.0**
  - **Framework Version: 1.24.0**
  - **OS               : macOS**
  - **Language         :TypeScript**

### Other

I have tried this on CDK version 1.24.0, 1.25.0, 1.26.0, and 1.28.0.

The stack synths and deploys fine on CDK versions 1.19.0-1.23.0.

--- 

This is :bug: Bug Report

**Comment by cmckni3** [comment] 2020-03-16 17:43
Appears to be working now. Strange.

**Comment by cmckni3** [comment] 2020-03-16 17:56
I thought the issue wasn't happening anymore.

I believe the synth was cached with `cdk.out` directory.

I upgraded to 1.28.0 and have the same error message during synth.

**Comment by cmckni3** [comment] 2020-03-16 22:52
Updated title and description and added minimal reproduction.

Apologize for the initial issue. I had to dig around what was happening in my large stack.

**Comment by NetaNir** [comment] 2020-03-17 06:05
Duplicate issue https://github.com/aws/aws-cdk/issues/6473

**Comment by eladb** [comment] 2020-03-19 15:13
@NetaNir why did you reopen? Do you believe this is not a duplicate of #6473 ?

**Comment by NetaNir** [comment] 2020-03-19 16:37
> @NetaNir why did you reopen? Do you believe this is not a duplicate of #6473 ?

Accidentally, closing!

**Closed by NetaNir** 2020-03-19 16:37 UTC
Labels: bug, cross-stack, needs-triage, p1, package/cdk-core

**Comment by cmckni3** [comment] 2020-03-19 17:08
> @NetaNir why did you reopen? Do you believe this is not a duplicate of #6473 ?

I actually think they are unrelated issues. In my minimal reproduction, I am not referencing anything across stacks.

I could be wrong and they are related at a code level but I don’t want this to get lost in the shuffle.

**Comment by cmckni3** [comment] 2020-03-19 17:11
I think the confusion may come from the labels that were applied to my initial bug report. I did a lot more digging into the failure of my stack synth and update the description after the labels were applied.

Will leave it up to CDK but that’s my thoughts on the matter.

**Comment by jogold** [comment] 2020-03-19 17:12
@cmckni3  `replicationRegions` is implemented using a custom resource in a nested stack.

**Comment by cmckni3** [comment] 2020-03-27 17:24
I read further down in the comments of #6473 and it makes sense now. Didn't dig into the code to see how replication regions are implemented.

Thanks @jogold

**Comment by cmckni3** [comment] 2020-04-25 05:07
Now, I receive a validation error from CloudFormation during deploy with CDK 1.34.1.

```
  code: 'ValidationError',
  time: 2020-04-25T01:59:51.888Z,
  requestId: '<ID>',
  statusCode: 400,
  retryable: false,
  retryDelay: 51.22703251258302

Tags must have length less than or equal to 50
```

**Comment by cmckni3** [comment] 2020-04-25 05:08
Should I open a new issue?

**Comment by eladb** [comment] 2020-04-25 13:28
> Should I open a new issue?

Yes please.
