### ISSUE TITLE
(aws-cdk): Cannot perform more than one GSI creation or deletion in a single update

### ISSUE THREAD

**Issue by viventra** [aws/aws-cdk#14920] opened 2021-05-30 10:02 UTC
### The Question

In my C# CDK project, I am trying to create two Global Secondary Indexes on a table. I get the following error while running `cdk deploy`:

```
  0/27 | 3:10:08 PM | UPDATE_FAILED        | AWS::DynamoDB::Table                            | MyTable (MyTableXXXX) Cannot perform more than one GSI creation or deletion in a single update
```
I would imagine this is quite a common use case to have a table with multiple GSIs. Why is this not supported out-of-the-box? Is there a work around?

If I comment out the GS index creation and then add them one by one, it succeeds. But I need to run multiple passes of the CDK program which is less than desirable.

### Environment

  - **CDK CLI Version:**  1.96.0 (build 39f3df8)
  - **Module Version:** 
  - **Node.js Version:** v14.15.4
  - **OS:** Microsoft Windows [Version 10.0.19042.985]
  - **Language (Version):** C# .NET Core SDK:  Version:   3.1.401 Commit:    5b6f5e5005

### Other information

```
                // 3.a. Create the table for the entity
                var resourceTable = new Table(this, ent, new TableProps
                {
                    PartitionKey = new Attribute {
                        Name = idFieldName,
                        Type = AttributeType.STRING
                    },
                    BillingMode = BillingMode.PAY_PER_REQUEST,
                    RemovalPolicy = RemovalPolicy.DESTROY,
                });

                ...

                    // The secondary index #1
                   resourceTable.AddGlobalSecondaryIndex(new GlobalSecondaryIndexProps() {
                        IndexName = $"{ent}_accountid_id_gsi",
                        PartitionKey = new Attribute() {
                            Name = "accountid",
                            Type = AttributeType.STRING
                        },
                        SortKey = new Attribute() {
                            Name = "id",
                            Type = AttributeType.STRING
                        },
                        ProjectionType = ProjectionType.INCLUDE,
                        NonKeyAttributes = new [] {
                            "accountid",
                            "id",
                            "ownerid",
                            "pointscharged",
                            "viewstart",
                            "viewexpiry",
                            "lastviewed",
                            "position",
                            "status",
                            "history"
                        }
                    });

                    // The secondary index #2
                    resourceTable.AddGlobalSecondaryIndex(new GlobalSecondaryIndexProps() {
                        IndexName = $"{ent}_ownerid_gsi",
                        PartitionKey = new Attribute() {
                            Name = "ownerid",
                            Type = AttributeType.STRING
                        },
                        SortKey = new Attribute() {
                            Name = "viewstart",
                            Type = AttributeType.NUMBER
                        },
                        ProjectionType = ProjectionType.INCLUDE,
                        NonKeyAttributes = new [] {
                            "accountid",
                            "id",
                            "ownerid",
                            "pointscharged",
                            "viewstart",
                            "viewexpiry",
                            "lastviewed",
                            "position",
                            "status",
                            "history"
                        }
                    });
```

**Comment by skinny85** [comment] 2021-06-01 16:15
Duplicate of https://github.com/aws/aws-cdk/issues/12246.

**Closed by skinny85** 2021-06-01 16:15 UTC
Labels: guidance, needs-triage
