### ISSUE TITLE
Running "cdk diff" returns error code 1

### ISSUE THREAD

**Issue by nicklaw5** [aws/aws-cdk#5885] opened 2020-01-20 22:56 UTC
Despite the fix introduced in #4650. I'm still experiencing `cdk diff` exiting with status code 1.

### Reproduction Steps
Run the following shell script:

```bash
#!/usr/bin/env bash

set -uo pipefail

cdk diff
EXIT_STATUS=$?
echo "Exit: $EXIT_STATUS"
```
### Environment

  - **CLI Version      :** 1.21.1 (build 842cc5f)
  - **Framework Version:** 1.21.1 (build 842cc5f)
  - **OS               :** macOS Catalina 10.15.2
  - **Language         :** Typescript

### Other

Relates to #2111

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment] 2020-01-21 04:40
@nicklaw5 - can you provide some additional information?

what version of the CDK was your project created with? I'm trying to reproduce your error but can't seem to get there.

Steps I've tried:
1. `cdk init --language typescript`
2. `cdk diff` - this has a diff (Conditions) -> `echo $?` returns 0
3. `cdk deploy`
4. `cdk diff` - No differences -> `echo $?` returns `0`
5. `cdk diff --fail` -> `echo $?` returns `1`

what does your `cdk.context.json` contain in it? does it have the `"aws-cdk:enableDiffNoFail": "true"` key?

**Comment by nicklaw5** [comment] 2020-01-21 05:18
@shivlaks Thanks for taking a look. I will put together a small repro tomorrow.

**Comment by nicklaw5** [comment] 2020-01-21 22:32
Doesn't appear I can reproduce using the sample app:

```bash
npm install -g aws-cdk
cdk version # 1.21.1 (build 842cc5f)
cdk init sample-app --language=typescript
cdk diff # exits with 0
```

This may having something to do with how we extend and wrap `cdk.Stack` with our own opinions. I'll see if I can figure it out. Feel free to close this in the mean time.

**Comment by nicklaw5** [comment] 2020-01-21 23:34
I've managed to create a repro: https://github.com/nicklaw5/aws-cdk-5885-repro. Please follow the steps in the readme to reproduce yourself.

**Comment by shivlaks** [comment] 2020-01-22 08:48
@nicklaw5 - thanks so much for creating the repro, I'll follow up on this tomorrow

**Comment by udondan** [comment] 2020-04-01 16:24
Confirming this, I'm experiencing the same problem.

```
$ cdk diff MyApp
Stack MyApp
Resources
[~] AWS::AutoScaling::LaunchConfiguration ASG-MyApp/LaunchConfig ASGMyAppLaunchConfig298A8983 replace
 └─ [~] ImageId (requires replacement)
     ├─ [-] ami-075138d2c6349b882
     └─ [+] ami-0516c16a5a46a3b17

$ echo $?
1
```

CDK Version: 1.31.0 (build 8f3ac79)

> what does your cdk.context.json contain in it? does it have the "aws-cdk:enableDiffNoFail": "true" key?

No, my `cdk.context.json` does not contain this setting at all.

**Comment by Norbinsh** [comment] 2020-04-04 11:28
I can also reproduce this from our CI environment  (codebuild) running 1.22.0 (diff --fail supported since 1.19).

$? will return 1 instead of 0 in case of any diff, without the --fail flag.

**Comment by angusfz** [comment] 2020-04-17 02:48
Same issue as @udondan 
cdk version: 1.32.2 (build e19e206)

Resolved this issue by adding  `"aws-cdk:enableDiffNoFail": "true" ` in  `cdk.context.json`.
But, according to the [changelog](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#1190-2019-12-17) , cdk diff should always exit with 0  ?

**Comment by xycodex** [comment] 2020-04-17 03:34
+1 this is an issue for me as well, running cdk version 1.32.2, python 3.8.2, as well as python 3.8

**Comment by xycodex** [comment] 2020-04-17 03:38
workaround @angusfz mentioned works for me locally, but not amenable for a cicd system since cdk.context.json isn't supposed to be checked into a vcs

**Comment by shivlaks** [comment] 2020-04-17 07:25
@angusfz - as mentioned in the changelog, it's under a `feature flag` and not natively as it represents a change in behaviour that we introduced.

@xycodex - runtime context can be set in a few [locations](https://docs.aws.amazon.com/cdk/latest/guide/context.html#context_construct). Your alternatives to committing it would include setting the key in ~/cdk.json or providing it as an option to your command. `cdk diff -c aws-cdk:enableDiffNoFail=true`

**Comment by udondan** [comment] 2020-04-17 07:32
OK, so you _HAVE_ to set that manually in the context. I missed that, I assumed it is the default. Thanks for clarification @shivlaks

**Comment by shivlaks** [comment] 2020-04-17 08:01
@udondan Yes, we flipped it to being the default for projects initialized through `cdk init` from that version onwards. But since it represents a change in behaviour, projects prior to it or created outside of the CLI's `cdk init` would need to opt into it.

I also amended the changelog entry to include the details from the initial commit (#7401)

**Comment by xycodex** [comment] 2020-04-17 09:17
ah, that all makes sense now. I did try adding the flag to cdk.json, but was wrong about the format.
https://docs.aws.amazon.com/cdk/latest/guide/featureflags.html helped me there, and now the flag works. =)

However, my cdk.json gets overwritten every time I run something like `cdk diff`, for some reason.

**Comment by udondan** [comment] 2020-04-17 09:21
Yeah I noticed this as well. I first added it to `cdk.json`. But when I run `cdk diff`, it automatically removes that key from the `cdk.json` and writes it into `cdk.context.json`.  I guess that's alright in CI. Just will confuse you if you run it locally.

**Comment by shivlaks** [comment] 2020-04-17 09:26
@udondan - yep that's a bug (fix is being tracked in #7399)

**Comment by Norbinsh** [comment] 2020-04-17 10:04
thank for the update! added this to the cdk.json in our buildspecs files and it works as expected

**Closed** 2020-04-18 01:56 UTC
Labels: bug, effort/small, p2, package/tools

**Comment by eikeon** [comment] 2020-04-23 15:33
Shouldn't the --fail option be removed if it doesn't actually work? Seems like it needs to be spelled `cdk diff -c aws-cdk:enableDiffNoFail=true`?

**Comment by metametadata** [comment] 2020-08-26 20:24
+1. `--fail` is still mentioned in `cdk help diff` and doesn't seem to work. v1.60.0.

**Comment by shivlaks** [comment] 2020-08-27 00:14
@metametadata - does the context have `aws-cdk:enableDiffNoFail` set to true? the `--fail` flag only works when that context key is set (in `~/.cdk.json`, `cdk.json` in your project or with `-c aws-cdk:enableDiffNoFail=true`)

The reason the option is not removed is because the context can be established in multiple ways. Perhaps the wording can still clarify that fail requires the context key `aws-cdk:enableDiffNoFail`

**Comment by metametadata** [comment] 2020-08-27 08:18
Thank you for the explanation. I set no context in my cases. I agree that the wording should be improved.
