### ISSUE TITLE
(golang) awscdk/v2/awsiot: CfnTopicRule_DynamoDBv2ActionProperty empty generated cfn

### ISSUE THREAD

**Issue by karl-dau** [aws/aws-cdk#17902] opened 2021-12-08 09:33 UTC
### What is the problem?

When I construct a TopicRule using `CfnTopicRule_DynamoDBv2ActionProperty`, then the generated CloudFormation is missing the actual action details.

### Reproduction Steps
```go
	ddbV2Action := &awsiot.CfnTopicRule_ActionProperty{
		DynamoDBv2: &awsiot.CfnTopicRule_DynamoDBv2ActionProperty{
			PutItem: awsiot.CfnTopicRule_PutItemInputProperty{
				TableName: table.TableName(),
			},
			RoleArn: iotRole.RoleArn(),
		},
	}

	ruleprops := &awsiot.CfnTopicRuleProps{
		TopicRulePayload: awsiot.CfnTopicRule_TopicRulePayloadProperty{
			Actions:          &[]*awsiot.CfnTopicRule_ActionProperty{ddbV2Action},
			AwsIotSqlVersion: aws.String("2016-03-23"),
			Sql:              aws.String(sqlStatement),
		},
	}

	awsiot.NewCfnTopicRule(stack, aws.String("ExampleRule"), ruleprops)
```

### What did you expect to happen?

I expected the Output to look like this:

```
  Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - DynamoDBv2:
              PutItem:
                TableName:
                  Ref: <table name redacted>
              RoleArn:
                Fn::GetAtt:
                  - IoTtoDynamoDBRole47C5C8A5
                  - Arn
        AwsIotSqlVersion: "2016-03-23"
        Sql: <sql redacted>
```

### What actually happened?

I only see this:

```
  Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Actions:
          - DynamoDBv2: {}
        AwsIotSqlVersion: "2016-03-23"
        RuleDisabled: false
        Sql: <sql redacted>
```

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Node.js Version

v17.2.0.

### OS

macOS Monteray

### Language

Go

### Language Version

Go 1.17.3

### Other information

A workaround:

```go
ddbV2Action := &awsiot.CfnTopicRule_ActionProperty{
		DynamoDBv2: &awsiot.CfnTopicRule_DynamoDBv2ActionProperty{
			PutItem: awsiot.CfnTopicRule_PutItemInputProperty{
				TableName: table.TableName(),
			},
			RoleArn: iotRole.RoleArn(),
		},
	}

	ruleprops := &awsiot.CfnTopicRuleProps{
		TopicRulePayload: awsiot.CfnTopicRule_TopicRulePayloadProperty{
			Actions:          &[]*awsiot.CfnTopicRule_ActionProperty{ddbV2Action},
			AwsIotSqlVersion: aws.String("2016-03-23"),
			Sql:              aws.String(SqlString),
		},
	}

	bytes, err := json.MarshalIndent(ruleprops, "", "    ")
	if err != nil {
		panic(err)
	}

	correctProps := &awsiot.CfnTopicRuleProps{}
	err = json.Unmarshal(bytes, correctProps)
	if err != nil {
		panic(err)
	}

	awsiot.NewCfnTopicRule(stack, aws.String("EampleRule"), correctProps)
```

**Comment by karl-dau** [comment] 2021-12-08 09:38
I downgraded node to  v16.13.1, same problem.

**Comment by skinny85** [comment] 2021-12-08 16:54
Hey @karl-dau,

thanks for opening the issue.

I'm not sure if the problem is not in your JSON marshal/unmarshal code. Can you try removing that part, and see if that works?

Thanks,
Adam

**Comment by skinny85** [comment] 2021-12-08 16:56
BTW, we also have [Layer 2 IoT TopicRule resources](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-iot.TopicRule.html) 🙂.

**Comment by karl-dau** [comment] 2021-12-08 17:09
> Hey @karl-dau,
> 
> 
> 
> thanks for opening the issue.
> 
> 
> 
> I'm not sure if the problem is not in your JSON marshal/unmarshal code. Can you try removing that part, and see if that works?
> 
> 
> 
> Thanks,
> 
> Adam

Hi 

The JSON marshal/Unmarshal is what makes it work. 

For some reason the CFN code generation for that action is not working or I am missing something.

**Comment by skinny85** [comment] 2021-12-08 17:24
Sorry. Can you show the code without the marshal/unmarshal part, and how it fails?

**Comment by skinny85** [comment] 2021-12-08 17:25
Oh, I see - you edited your description to include the original code (I missed that in the original notification).

**Comment by karl-dau** [comment] 2021-12-08 17:30
> Oh, I see - you edited your description to include the original code (I missed that in the original notification).

Hi

Yes, everything should be there. The action seems to be generating 

`  - DynamoDBv2: {}`

instead of

```
- DynamoDBv2:
              PutItem:
                TableName:
                  Ref: <table name redacted>
              RoleArn:
                Fn::GetAtt:
                  - IoTtoDynamoDBRole47C5C8A5
                  - Arn```

The JSON marshal/unmarshal trick works because the struct tags match.

**Comment by skinny85** [comment] 2021-12-14 02:15
Hey @karl-dau,

can you show me the Go module declaration and import you are using?

Thanks,
Adam

**Comment by skinny85** [comment] 2021-12-14 02:29
OK, I figured it out. The mistake was that you made the array of `CfnTopicRule_ActionProperty` an array of pointers, but it's in fact an array of values.

This works for me:

```go
	awsiot.NewCfnTopicRule(stack, jsii.String("ExampleRule"), &awsiot.CfnTopicRuleProps{
		TopicRulePayload: awsiot.CfnTopicRule_TopicRulePayloadProperty{
			Sql:              jsii.String("SELECT topic(2) as device_id, temperature FROM 'device/+/data'"),
			AwsIotSqlVersion: jsii.String("2016-03-23"),
			Actions: &[]awsiot.CfnTopicRule_ActionProperty{
				awsiot.CfnTopicRule_ActionProperty{
					DynamoDBv2: &awsiot.CfnTopicRule_DynamoDBv2ActionProperty{
						PutItem: &awsiot.CfnTopicRule_PutItemInputProperty{
							TableName: jsii.String("mytable"),
						},
						RoleArn: jsii.String("my-role-arn"),
					},
				},
			},
		},
	})
```

**Comment by skinny85** [comment] 2021-12-14 02:30
I'm resolving this one, please comment if you need anything else from our side.

**Closed by skinny85** 2021-12-14 02:30 UTC
Labels: bug, p2, response-requested, needs-triage, @aws-cdk/aws-iot

**Comment by karl-dau** [comment] 2021-12-14 06:09
@skinny85 Thanks! that was it! 

I got confused with optionals being pointer types and building up those structs with values and not pointers.
The JSON marshal/unmarshal trick works because the reflection code dereferences those pointers.
I guess everything taking `interface{}` also did not help.
