### ISSUE TITLE
VPCPeeringConnection: CfnVPCPeeringConnection tries to accept cross-account request

### ISSUE THREAD

**Issue by luqmanulkhair** [aws/aws-cdk#17383] opened 2021-11-07 13:14 UTC
### What is the problem?

I want to create a cross-account peering request and don't want to accept it immediately as the default behavior in UI and also awscli, however creating a peering connection using CfnVPCPeeringConnection, I get the error **User cannot accept peering pcx-....**. An example is given below.

### Reproduction Steps

```ts
const connection = new CfnVPCPeeringConnection(
this, 
'xyzzy', 
{   
    peerOwnerId: '1234',
    peerVpcId: 'abc',
    vpcId: vpc.vpcId,
});
```

### What did you expect to happen?

It should create a peering request instead of trying to accept it directly after creating it.

### What actually happened?

It creates a peering request and tries to accept it. Since the role is not available and therefore it fails and gives this error.
**User 'XYZ' cannot accept peering pcx-.**

### CDK CLI Version

1.130.0 

### Node.js Version

v12.7.0

### OS

macOS Catalina 10.15.6 

### Language

Typescript

**Comment by ryparker** [comment] 2021-11-08 21:28
Hey @luqmanulkhair 👋🏻 

[`CfnVPCPeeringConnection`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnVPCPeeringConnection.html) is a L1 construct which means that it is auto generated from the [`AWS::EC2::VPCPeeringConnection` CloudFormation resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html). This means that there shouldn't be any CDK logic that overrides the defaults of CloudFormation. 

Could you provide an example of how you're using the awscli to achieve what you are expecting?

**Comment by luqmanulkhair** [comment] 2021-11-09 09:06
@ryparker  i used [create-vpc-peering-connection](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpc-peering-connection.html) which works perfectly fine.

**Comment by ryparker** [comment] 2021-11-09 22:51
> It creates a peering request and tries to accept it. Since the role is not available and therefore it fails and gives this error.
User 'XYZ' cannot accept peering pcx-.

Have you tried using[ `CfnVpcPeeringConnection.addDependsOn()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnVPCPeeringConnection.html#addwbrdependswbrontarget) to guarantee that the role is created before it attempts the connection?

**Comment by luqmanulkhair** [comment] 2021-11-09 23:12
@ryparker I don't understand what should I write in dependsOn(), To me seems like it wants the role from another VPC and I don't have access to it. I only want to create a pending connection. Even the connection request is created but then it is rolled-back.

**Comment by rix0rrr** [comment] 2021-11-22 13:37
Looking at the documentation here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html

Are you not missing `peerRoleArn` ?

We cannot really help you any more than that. VPC Peering has not been implemented in the hand-written layer of CDK. As such, you need to use exactly the same mechanisms as you would need to set up VPC peering using CloudFormation, except using CDK.

Otherwise, this seems like a duplicate of https://github.com/aws/aws-cdk/issues/9338. Closing.

**Closed by rix0rrr** 2021-11-22 13:37 UTC
Labels: bug, p2, @aws-cdk/core, effort/small

**Comment by klinec** [comment] 2025-04-08 13:33
I have the same issue, but the solution is described in documentation https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/CfnVPCPeeringConnection.html

```
If the VPCs belong to different accounts, the acceptor account must have a role that allows the requester account to accept the VPC peering connection
```
`peerRoleArn` is the answer
