### ISSUE TITLE
cdk init lib should come with unit tests

### ISSUE THREAD

**Issue by rhboyd** [aws/aws-cdk#3945] opened 2019-09-04 22:58 UTC
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change

### Description
when running `cdk init --language typescript lib` the generated code should include the devDependencies on nodeunit and cdk-assert as well as sample unit tests for the SQS Queue and SNS Topic it creates by default.

### Proposed Solution

Should be a pretty straight-forward change to the TS Template.
### Environment
  - **Language:** TypeScript

**Comment by NGL321** [comment] 2019-09-04 23:17
Duplicate of #1217, but since that is a number of versions behind and this is more explanatory, I will keep this issue!

**Comment by rhboyd** [comment] 2019-09-04 23:21
Ohhh, I didn’t know nodeunit was deprecated. I’m not up on the TS ecosystem. Would jest be the in vogue alternative?

**Comment by rhboyd** [comment] 2019-09-05 04:22
https://github.com/aws/aws-cdk/pull/3948

![](https://i.imgur.com/uyKgrYk.gif)

**Closed** 2019-09-09 16:24 UTC
Labels: feature-request, management/devenv, package/cdk-core
