### ISSUE TITLE
[pipelines] automatically delete application stacks

### ISSUE THREAD

**Issue by stephankaag** [aws/aws-cdk#10759] opened 2020-10-07 08:21 UTC
The pipeline SelfMutate action correctly adds new application stages to itself and creates a Stack for each application stage.
 
However, when application stages are _removed_ they are removed from the pipeline but the corresponding stack is kept untouched. This causes dangling stacks.

### Reproduction Steps

Create a pipeline with an additional application stage and let it deploy.
Remove the additional application stage from the code and let the pipeline update itself.

### What did you expect to happen?

I would expect the CloudFormation stack for the additional application stage to be removed.

### What actually happened?

The CloudFormation stack is left untouched.

### Environment

  - **CLI Version      : 1.6.0
  - **Framework Version:
  - **Node.js Version: v12.18.4
  - **OS               : OSX Mojave
  - **Language (Version): TypeScript

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-10-13 11:52
It is true, and we don't have a good answer for it yet, sorry. I have a feeling this issue might be a duplicate. I will add it as a warning to the documentation to be sure.

**Comment by 1oglop1** [comment] 2021-03-15 09:34
This is basically a duplicate of #10190

**Comment by rix0rrr** [comment] 2021-03-19 11:38
Yep duplicate of #10190

**Closed by rix0rrr** 2021-03-19 11:38 UTC
Labels: @aws-cdk/pipelines, effort/large, feature-request, p2
