### ISSUE TITLE
(aws-lambda-event-sources): FilterCriteria for SQS eventsources

### ISSUE THREAD

**Issue by hongnan0512** [aws/aws-cdk#20338] opened 2022-05-13 16:48 UTC
### Describe the feature

Filtering event sources for AWS Lambda functions.This helps reduce requests made to your Lambda functions, may simplify code, and can reduce overall cost.

### Use Case

Consider a logistics company with a fleet of vehicles in the field. Each vehicle is enabled with sensors and 4G/5G connectivity to emit telemetry data into Kinesis Data Streams:

    In one scenario, they use machine learning models to infer the health of vehicles based on each payload of telemetry data, which is outlined in example 2 on the [Lambda pricing page](https://aws.amazon.com/lambda/pricing/).
    In another scenario, they want to invoke a function, but only when tire pressure is low on any of the tires.

If tire pressure is low, the company notifies the maintenance team to check the tires when the vehicle returns. The process checks if the warehouse has enough spare replacements. Optionally, it notifies the purchasing team to buy additional tires.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

v2

### Environment details (OS name and version, etc.)

mac

**Comment by kaizencc** [comment] 2022-05-17 14:36
Closing this as a duplicate of #17874. There's a PR open for it, so we're working on getting this out there.

**Closed by kaizencc** 2022-05-17 14:36 UTC
Labels: feature-request, needs-triage, @aws-cdk/aws-lambda-event-sources
