### ISSUE TITLE
[CDK issue] addToResourcePolicy always fail if I change the princal ARN

### ISSUE THREAD

**Issue by YizhouHao** [aws/aws-cdk#13530] opened 2021-03-10 20:30 UTC
### The Question
Hi, I'm using CDK to build infra. I've successfully build everything, lambda, sqs, etc. I used "addToResourcePolicy" so that I can grant an IAM role permission to write to the SQS.

```ts
backInStockQueue.addToResourcePolicy(
	new PolicyStatement({
		effect: Effect.ALLOW,
		//placeholder. todo: change the arn
		principals: [new ArnPrincipal('arn:aws:iam::597414380752:user/testuser')],
		actions: ["sqs:SendMessage"],
		resources: [backInStockQueue.queueArn],
	})
);
```

However, when I tried to change the principal arn above and deploy it, it always fail. It even fails with I just change the arn a little bit. Please see log below, I only tried to change arn from ' AWS:arn:aws:iam::597414380752:user/testuser' to ' AWS:arn:aws:iam::597414380752:user/testuserdevo' and it still failed on SQS with "InvalidAttributeValue". Any tips on this? Thank you

### Environment

  - **CDK CLI Version:** 1.32
  - **Module Version:** 
  - **Node.js Version:** 12.x
  - **OS:** mac
  - **Language:** typescript

### Other information
https://paste.amazon.com/show/hayizhou/1615363438

**Comment by ryparker** [comment] 2021-06-16 20:22
Hey @YizhouHao :wave:

I'd like to help you out here.

I attempted to recreate your scenario however did not experience the same error. I'll attach my reproduction code below.

You might want to take a look into the following:

- Make sure the IAM user you have hardcoded in the policy statement has the proper permissions to access that SQS resource.
- There have been many updates to the CDK since you posted this issue. Try updating to the latest version (currently: v1.108.1)

If none of the above helps could you post the full error and more details/code from your setup?

Hope this helps!

Scenario code:

```ts
import * as cdk from '@aws-cdk/core';
import * as sqs from '@aws-cdk/aws-sqs';

import { PolicyStatement, Effect, ArnPrincipal } from '@aws-cdk/aws-iam';

const app = new cdk.App();
const stack1 = new cdk.Stack(app, 'stack1');

const backInStockQueue = new sqs.Queue(stack1, 'Queue', {
  encryption: sqs.QueueEncryption.KMS_MANAGED,
});

backInStockQueue.addToResourcePolicy(
  new PolicyStatement({
    effect: Effect.ALLOW,
    principals: [new ArnPrincipal(process.env.IAM_TEST_USER_ARN)],
    actions: ['sqs:SendMessage'],
    resources: [backInStockQueue.queueArn],
  })
);
```

**Comment by peterwoodworth** [comment] 2021-07-07 23:54
Closing because the response-requested label has been applied for more than two weeks. Ping us if you need additional help with this issue!

**Closed by peterwoodworth** 2021-07-07 23:54 UTC
Labels: effort/small, guidance, p2, response-requested
