### ISSUE TITLE
Expose EIP(s) from created NAT gateway(s)

### ISSUE THREAD

**Issue by balkat** [aws/aws-cdk#4705] opened 2019-10-27 22:19 UTC
* Provide a NAT gateway construct which exposes its allocated EIP.
* Expose NAT gateway constructs in the VPC properties to allow EIPs to be discovered.

### Use Case

* It is desirable to know the EIPs allocated to NAT gateways in a VPC.
* Most compelling reason for this is when you need to access a third-party service via a set of whitelisted IP addresses (those of the NAT gateways).

### Proposed Solution

* Provide a NAT Gateway construct that exposes its allocated EIP address.
* Expose the list of NAT gateways in a VPC construct in a manner similar to e.g. the subnets.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by lbjay** [comment] 2020-05-12 16:39
This would be particularly useful as there's no plan to make BYO EIP less onerous, e.g. #4067

**Comment by michaelday008** [comment] 2020-06-02 18:31
I would love to see this.  Going even further, here is my use case.

We may at times need to rebuild our internal subnets and VPC configuration, while retaining the external EIPs associated with the NAT gateways.

CDK does not seem to currently have this functionality.  I would love to be able to provide EIPs with the subnet configuration when specifying a VPC so I don't have to make the choice between:
A) Go to all our partners who whitelist us and give them new IPs to whitelist
B)Manually create all our VPCs and subnets and NAT gateways so we can keep the same IPs when the internal implementation details change.

**Comment by ralovely** [comment] 2020-09-04 08:51
Hello.

In the meantime, this could be achieved by creating the EIP in your stack, and replacing the ones created by CDK in your VPC (same idea as [here](https://github.com/aws/aws-cdk/issues/4067#issuecomment-687011458)).

In Typescript:

```typescript
// Define the number of AZ (which will also be number of EIPs)
const numberOfAz = 2;

const allocationIds: string[] = [];
const eips: string[] = [];


// Create the VPC construct first
const vpc = new ec2.Vpc(this, 'VPC', {
  cidr: "10.0.0.0/16",
  maxAzs: 2,
})

// Create as many EIP as there are AZ/Subnets and store their allocIds & refs.
for (let i = 0; i < numberOfAz; i++) {
    var eip = new ec2.CfnEIP(this, `VPCPublicSubnet${i+1}NATGatewayEIP${i}`, {
        domain: 'vpc',
        tags: [
            {
                key: 'Name',
                value: `MyApp/VPC/PublicSubnet${i+1}`,
            },
        ]
    })
    allocationIds.push(eip.attrAllocationId)

    // Do whatever you need with your EIPs here, ie. store their ref for later use
    eips.push(eip.ref)

    // Add a dependency on the VPC to encure allocation happens before the VPC is created
    vpc.node.addDependency(eip)
}


vpc.publicSubnets.forEach((subnet, index) => {
    // Find the NAT Gateway
    var natGateway = subnet.node.children.find(child => child.node.id == 'NATGateway') as ec2.CfnNatGateway
    // Delete the default EIP created by CDK
    subnet.node.tryRemoveChild('EIP')
    // Override the allocationId on the NATGateway
    natGateway.allocationId = allocationIds[index]
})
```

**Comment by iwarshak** [comment] 2021-02-02 22:49
@michaelday008 I am in  a very similar situation with partners needing a consistent IP. what workaround solution worked for you?

**Comment by michaelday008** [comment] 2021-02-02 23:25
@iwarshak We never found a good solution to this. The team just ended up creating them manually.

**Comment by iwarshak** [comment] 2021-02-02 23:29
@michaelday008 not being able to see the EIP address, and not being able to reference an existing EIP resource is so unfortunate. I am surprised this isn't a bigger deal, since I am sure lots of companies would like to keep a static IP.

**Comment by michaelday008** [comment] 2021-02-03 00:46
@iwarshak I think that people, when faced with issues like this, are just using another solution.  For example, another team I was in contact with about the issue just used Terraform instead.

I do agree that it is unfortunate that you are forced to use a solution like Terraform due to the immaturity of CDK at this point.  I would much rather go 100% CDK since Terraform comes with its own set of issues, like all users needing direct admin access to the resources they want to provision and no ability to 'run as role' like the service catalog provides.

**Comment by ralovely** [comment] 2021-02-03 00:58
I find offloading to another system a bit extreme.
CDK has the concept of [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) which make _most_ things doable.

The solution [posted above](https://github.com/aws/aws-cdk/issues/4705#issuecomment-687017198), if still a cumbersome (some might find ugly) workaround, it's a working, 100% CDK solution, just going at a lower level to synth the CFn template as needed.

If anything, the fact that you create your own EIPs first gives you more control for future changes.

Wrap it in a custom module, and you'll even have the feeling of using an L3 construct ;)

**Comment by jpSimkins** [comment] 2021-02-04 16:41
I too am finding myself with the need to get the NAT Gateway IP to allow connections for restricted ALB to work from the project's containers. I tried the method posted above but that doesn't seem to work. I am using a single NAT Gateway so the logic is a bit different but still not able to get this to work. It would be really nice to have an attribute to get the EIP of each NAT Gateway so we can actually use it in our stacks.

**Comment by firxworx** [comment] 2021-04-14 14:14
Just as much as it should be easy to get the EIP's from new NAT Gateways, especially those created as part of a new VPC, it'd be huge to specify which EIP's you want a VPC's NAT Gateways to use on creation (e.g. by providing allocation ID's).

The big picture is: practically every company I've ever had the privilege of seeing inside, and every non-trivial client that I've ever worked with, has had the need to whitelist IP's with any of their customers, software/platform providers, partners, etc. In some cases its a painful hassle with third party bureaucracies to get an IP whitelisted.

For some reason I see @rix0rrr username on issue after issue and he closes anything related to improving NAT gateways in this area despite clearly a lot of users out there asking repeatedly for better support re EIP + NAT GW + VPC.

- https://github.com/aws/aws-cdk/issues/11884
- https://github.com/aws/aws-cdk/issues/4067
- https://github.com/aws/aws-cdk/issues/8327
- etc

@TikiTDO's https://github.com/aws/aws-cdk/issues/11884#issuecomment-740767829 couldn't have said it better.

Bruh... Seriously.

I'm working on my first for-production aws-cdk infrastructure project and the first thing I did was manage expectations that despite all these lovely examples that make everything look so fast and easy that when it comes to something meatier than a contrived example "AWS will gap on completely obvious production use-cases and can often force devs to run through hoops to do the most basic and obvious thing". In other words, there were hidden time traps like this one.

Alongside needing to work around apparent oversights re use-cases re requiring infrastructure in regions other than `us-east-1` while requiring ACM certificates to be that region (for CloudFront etc), this is right up there as the next big example of hassle that I've encountered so far.

The EIP association is an obvious use-case that the AWS console UI maintainers clearly appreciate and consider to be important.

Nobody wants to write their own `NatGatewayProvider` or tweak CloudFormation output to accommodate such a painfully obvious and common case. The whole reason anyone is using AWS CDK is to avoid that BS with AWS in the first place and make AWS less of a pain in the ass to do anything with. Feature gaps like this one are discouraging users from adopting aws-cdk and even AWS itself when it would otherwise be the leading choice for AWS.

+1 to the OP, +1 to everyone contributing solutions and workarounds. Thanks that's huge.

**Comment by TikiTDO** [comment] 2021-04-14 15:41
For anyone looking for a drop-in, modular solution, here is the code I used to work around this issue:

```ts
import * as ec2 from "@aws-cdk/aws-ec2"
import * as cdk from "@aws-cdk/core"

/**
 * Custom provider to allow NATs with existing EIP allocation IDs
 */

export default class OverrideNatEIP extends ec2.NatProvider {
  private allocationIds: string[]
  private gateways: Array<[string, string]> = []
  private construct: cdk.Construct

  constructor(construct: cdk.Construct, allocationIds: string[]) {
    super()
    this.allocationIds = allocationIds
    this.construct = construct
  }

  configureNat(options: ec2.ConfigureNatOptions): void {
    // Create the NAT gateways
    options.natSubnets.forEach((subnet, index) => {
      const gateway = new ec2.CfnNatGateway(this.construct, `NATGateway-${index}`, {
        allocationId:
          this.allocationIds[index] ??
          new ec2.CfnEIP(this.construct, `EIP-${index}`, {
            domain: "vpc",
          }).attrAllocationId,
        subnetId: subnet.subnetId,
      })

      this.gateways.push([subnet.availabilityZone, gateway.ref])
    })

    // Add routes to them in the private subnets
    for (const sub of options.privateSubnets) {
      this.configureSubnet(sub)
    }
  }

  configureSubnet(subnet: ec2.PrivateSubnet): void {
    const az = subnet.availabilityZone
    const [, gatewayRef] = this.gateways.find(([gatewayAz]) => az === gatewayAz) ?? []
    if (gatewayRef) {
      subnet.addRoute("DefaultRoute", {
        enablesInternetConnectivity: true,
        routerId: gatewayRef,
        routerType: ec2.RouterType.NAT_GATEWAY,
      })
    }
  }

  public get configuredGateways(): ec2.GatewayConfig[] {
    return this.gateways.map((x) => ({ az: x[0], gatewayId: x[1] }))
  }
}
```

This module can then be consumed as follows:

```ts
const vpc = new ec2.Vpc(this, 'VPC', {
  cidr: "10.0.0.0/16",
  natGateways: 3,
  natGatewayProvider: new OverrideNatEIP(this, ["eipalloc-0123456789abcdef0", "eipalloc-0123456789abcdef1"]),
})
```

This will create a VPC with 3 NAT gateways, the first two will use the allocations provided, while the third one will create a new allocation.

**Comment by mteichtahl** [comment] 2021-08-13 02:01
Adding a +1 for this feature

**Comment by jamiepeloquin** [comment] 2021-11-08 16:11
Adding a +1 for this feature as well.

**Comment by firxworx** [comment] 2022-02-06 18:08
Update: in cdk v2 (`aws-cdk-lib`) I noticed `NatGatewayProps` now accepts `eipAllocationIds`. 

Docs: <https://docs.aws.amazon.com/cdk/api/v2//docs/aws-cdk-lib.aws_ec2.NatGatewayProps.html>. 

I assume the following (unconfirmed) would therefore be supported:

```ts
const eipAllocationIds = ['1234abc', '4321cba']

const vpc = new ec2.Vpc(this, 'VPC', {
  // ...
  natGatewayProvider: ec2.NatProvider.gateway({ eipAllocationIds })
})
```

Note: if your use-case is related to whitelisting (or similar) you may wish to allocate/reserve the EIP's in a separate stack or via the cli or console UI. This ensures the IP address reservations cannot be lost if/when the stack you are working on is destroyed.

Thanks @TikiTDO your solution was effective when it was the only option I could find.

**Comment by TikiTDO** [comment] 2022-02-06 20:05
@firxworx Sweet, thanks for pointing this out. This can clean up a few of my stacks.

@rix0rrr Not sure if you're the right person to tag here, but it looks like this issue has been resolved so it can probably be closed.

**Comment by corymhall** [comment] 2022-03-08 18:46
Closing this since the solution is to create your EIPs and pass them into the NatGatewayProvider.

**Closed by corymhall** 2022-03-08 18:46 UTC
Labels: p2, feature-request, @aws-cdk/aws-ec2, effort/medium

**Comment by kichik** [comment] 2024-02-12 15:13
You can use escape hatches to get access to all EIPs allocated by a VPC.

```
let vpc: ec2.IVpc;
const eips: string[] = [];
vpc.node.findAll().forEach((resource) => {
  if (resource instanceof ec2.CfnEIP) {
    eips.push(resource.attrPublicIp);
  }
});
```

**Comment by madhan987** [comment] 2024-11-27 10:14
+1
