### ISSUE TITLE
(app-config-alpha): (make content optional for hosted configuration)

### ISSUE THREAD

**Issue by morrijm4** [aws/aws-cdk#28391] opened 2023-12-15 19:28 UTC
### Describe the feature

I would like the `content` property to be optional for the HostedConfiguration construct.

### Use Case

I would like to manage my configuration outside of my source control.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.115.0-alpha.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.6.3

**Comment by pahud** [comment] 2023-12-15 21:07
duplicate of https://github.com/aws/aws-cdk/issues/28390

**Closed by pahud** 2023-12-15 21:07 UTC
Labels: feature-request, needs-triage
