### ISSUE TITLE
(All Previous Versions): Provide hosting service to allow customers to easily browse versions of previous documentation

### ISSUE THREAD

**Issue by tylerwalts** [aws/aws-cdk#12341] opened 2021-01-05 01:47 UTC
**Context:**

This is related to a previous issue requesting ability to "_browse documentation by version since CDK is always evolving._":

https://github.com/aws/aws-cdk/issues/8083

The above issue was closed after providing a workaround of "_download old copies of the documentation from the GItHub Releases Page: https://github.com/aws/aws-cdk/releases_" and then further clarification that the documentation source would need to be self-hosted on a machine that has the required development capabilities on it.

I recently discussed with a coworker if we should have someone pull down the code matching the version we're using and host it somewhere for all our team to use such that we didn't all have to sink the same time investment into just being able to look at the docs.  However, we do not want to maintain or have an SLA for this and it seems reasonable for a team more closely involved with CDK to host this for all customers to benefit from having it available.

**Feature Request:**

Can this service of hosting legacy documentation versions be considered for 2021?

The documentation is very useful, but only available as the latest release version.  There are times when customers are using a previous version of CDK for development, and the documentation they can search and find on the web does not match in versions.  Since this is the only search result available on the web, they go forward with using this reference anyway (often times it works fine), but it can/has/will lead to unexpected errors and time wasted troubleshooting differences between versions.

This also impacts the business planning process because a person making estimates might understand based on documentation that a feature is easy to add via CDK, budget little time for this, and then be inaccurate later if the feature was only available in a version after what the business is using.  Then an upgrade needs to be done, without being planned or having time allocated for it.

An ideal user experience is to have the option of changing the URL (replace `latest` with a version like `1.45.0`) and a drop-down user interface that can take a user to that version instantly.

For example:
* https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html (works today)
* https://docs.aws.amazon.com/cdk/api/1.45.0/docs/aws-lambda-readme.html (requesting this to take us to the docs as of CDK 1.45.0 branch head https://github.com/aws/aws-cdk/commits/v1.45.0)

It seems like this should be possible to automate in a pipeline, every time a version is Tagged, the package up and host a static snapshot of the documentation in S3/CloudFront or something?

---

This is a 📕 documentation issue

**Comment by gurjaspalbedi** [comment] 2021-01-05 01:53
This will be helpful, thank you for creating this issue.

**Comment by tf-cambria** [comment] 2021-01-06 03:03
I agree with the rationale in this issue, @tylerwalts. Thanks for providing clear business impacts and costs for using the current documentation capabilities. We have experienced similar issues based on the publicly available (latest) documentation API. I certainly appreciate how quickly updates of the CDK are occurring and making it easier to leverage and research other versions would provide high value.

**Comment by rix0rrr** [comment] 2021-02-08 16:16
Given our current tooling, unfortunately not easy to implement.

**Comment by tim-finnigan** [comment] 2023-01-25 22:46
I'm going to close this as a duplicate of https://github.com/aws/aws-cdk/issues/11172 for the sake of consolidating issues. I think the ask here is the same but if there are any distinctions you want to clarify please let us know.

**Closed by tim-finnigan** 2023-01-25 22:46 UTC
Labels: p1, feature-request, effort/large, docs/generated, documentation

**Comment by tylerwalts** [comment] 2023-01-25 22:50
@tim-finnigan Yes I agree that these issues are asking for the same thing.

Thank you for making this a priority.
