### ISSUE TITLE
using json instead of a string as context in cdk.json

### ISSUE THREAD

**Issue by markosha** [aws/aws-cdk#3760] opened 2019-08-22 15:08 UTC
### The Question

Hello,
I'm trying to setup one cdk,json which will provide parameters for  all DEV, QA and PROD environments.  My cdk.json looks like this:
``` Perl
"context": {
   "appName": "app1",
   "ENV:TEST": {
          "vpcId": "vpc-111111111111"
    },
   "ENV:QA": {
          "vpcId": "vpc-222222222222"
    },
   "ENV:PROD": {
          "vpcId": "vpc-333333333333"
    }
}
```
I have it working, but every time i run "cdk synth", all "ENV:XXX" entries get removed from cdk.json. After  running cdk synth my cdk.json looks like this: 
``` elixir
"context": {
   "appName": "app1"
}
```
All values do persist in the cdk context though. Is this by design? 

The problem im trying to solve is to have one repository, which can be deployed to a any environment by say doing - `cdk deploy -c "ENV:QA"`. 

Thanks!

### Environment

  - **CDK CLI Version:**  1.3.0 (build bba9914)
  - **Module Version:** 
  - **OS:**  Windows 10
  - **Language:**  TypeScript

**Comment by jgondron** [comment] 2019-10-30 20:21
I think this should work, although this will break some of the cli options for managing context since cdk currently doesn't really support this. In your case, I think you would need to do something like `cdk deploy -c env="QA"`, then in code use that to look up the correct context object, ex:
```
const targetEnv = app.node.tryGetContext('env');
const env = app.node.tryGetContext(`ENV:${targetEnv}`);
const vpcId = env.vpcId;
```

**Comment by sacag** [comment] 2020-01-06 04:20
@jgondron , @markosha - were you able to get anywhere with this issue? Trying to do something similar and would like to know if you guys were able to figure out something. Thanks

**Comment by shivlaks** [comment] 2020-04-23 19:34
@markosha was this resulting in your keys being moved from `cdk.json` to `cdk.context.json` ?

**Comment by drissamri** [comment] 2020-08-01 10:22
Is there a cleaner way to do this in meanwhile? It seems like a basic requirement for anything over POC's/demos. 

In our case we are deploying from Jenkins/GitLab and we have an AWS account (with different params) per environment so it should be easy to pass these in.

**Comment by drissamri** [comment] 2020-09-09 15:19
It looks like you can set environment params in your context json and then pass the environment you want on the command line, that would do it for me yes. I'll have to try to give it a go.

**Comment by SomayaB** [comment] 2020-09-29 22:59
Closing this issue for now. Please tag me if the issue isn't fixed and you'd like me to reopen the issue.

**Closed by SomayaB** 2020-09-29 22:59 UTC
Labels: guidance, management/devenv
