### ISSUE TITLE
(cli): "Invalid config." when doing tutorial and adding `publicReadAccess: true`

### ISSUE THREAD

**Issue by radiosilence** [aws/aws-cdk#12359] opened 2021-01-05 17:14 UTC
I am trying to do step 2 of the tutorial.

### Reproduction Steps
  1. Add `publicReadAccess: true` to CDK S3 config
  2. Run `cdk diff`
  3. Recieve output:

```
cdk diff                                                                                          
Stack HelloCdkStack
IAM Statement Changes
config {
  border: {
    topBody: '\u001b[90m─\u001b[39m',
    topJoin: '\u001b[90m┬\u001b[39m',
    topLeft: '\u001b[90m┌\u001b[39m',
    topRight: '\u001b[90m┐\u001b[39m',
    bottomBody: '\u001b[90m─\u001b[39m',
    bottomJoin: '\u001b[90m┴\u001b[39m',
    bottomLeft: '\u001b[90m└\u001b[39m',
    bottomRight: '\u001b[90m┘\u001b[39m',
    bodyLeft: '\u001b[90m│\u001b[39m',
    bodyRight: '\u001b[90m│\u001b[39m',
    bodyJoin: '\u001b[90m│\u001b[39m',
    joinBody: '\u001b[90m─\u001b[39m',
    joinLeft: '\u001b[90m├\u001b[39m',
    joinRight: '\u001b[90m┤\u001b[39m',
    joinJoin: '\u001b[90m┼\u001b[39m'
  },
  columns: {
    '0': { width: 1, useWordWrap: true },
    '1': { width: 22, useWordWrap: true },
    '2': { width: 6, useWordWrap: true },
    '3': { width: 12, useWordWrap: true },
    '4': { width: 9, useWordWrap: true },
    '5': { width: 9, useWordWrap: true }
  },
  drawHorizontalLine: [Function: drawHorizontalLine]
}
errors [
  {
    dataPath: '/columns/0',
    message: 'should NOT have additional properties',
    params: { additionalProperty: 'useWordWrap' },
    schemaPath: '#/additionalProperties'
  },
  {
    dataPath: '/columns/1',
    message: 'should NOT have additional properties',
    params: { additionalProperty: 'useWordWrap' },
    schemaPath: '#/additionalProperties'
  },
  {
    dataPath: '/columns/2',
    message: 'should NOT have additional properties',
    params: { additionalProperty: 'useWordWrap' },
    schemaPath: '#/additionalProperties'
  },
  {
    dataPath: '/columns/3',
    message: 'should NOT have additional properties',
    params: { additionalProperty: 'useWordWrap' },
    schemaPath: '#/additionalProperties'
  },
  {
    dataPath: '/columns/4',
    message: 'should NOT have additional properties',
    params: { additionalProperty: 'useWordWrap' },
    schemaPath: '#/additionalProperties'
  },
  {
    dataPath: '/columns/5',
    message: 'should NOT have additional properties',
    params: { additionalProperty: 'useWordWrap' },
    schemaPath: '#/additionalProperties'
  }
]
Invalid config.
```

### Environment

  - **CDK CLI Version: ** 1.82.0 (build c445b89)
  - **Framework Version:  ** 1.82.0
  - **Node.js Version:** 12.20.0
  - **OS               :** macOS Big Sur
  - **Language (Version):** TypeScript 4.1.3

--- 

This is :bug: Bug Report

**Comment by radiosilence** [comment] 2021-01-05 17:36
Edit: Ok I think this happens only if you install aws-cdk with `yarn global add`. If you use `npm i -g aws-cdk` it works fine. So perhaps there's an issue with dependency resolution?

**Comment by gamerdonkey** [comment] 2021-01-05 19:53
I also had this problem with Homebrew-installed aws-cdk. Installing the npm version worked.

**Comment by MattReimer** [comment] 2021-01-05 20:48
I'd love to see a better error here.

all that stuff at the beginning:

```
config {
  border: {
    topBody: '\u001b[90m─\u001b[39m',
    topJoin: '\u001b[90m┬\u001b[39m',
    topLeft: '\u001b[90m┌\u001b[39m',
    topRight: '\u001b[90m┐\u001b[39m',
```

makes it really hard to figure out what the problem is.

**Comment by rix0rrr** [comment] 2021-02-08 13:43
Fixed by https://github.com/aws/aws-cdk/pull/12307

**Closed by rix0rrr** 2021-02-08 13:43 UTC
Labels: bug, needs-triage, package/tools
