### ISSUE TITLE
custom-resources: Incorrect prefix for SES actions in policy

### ISSUE THREAD

**Issue by markilott** [aws/aws-cdk#14360] opened 2021-04-24 08:30 UTC
When using AwsCustomResourcePolicy.fromStatements() to create policy for SES SDK actions, the resultant policy uses "email:" as the prefix, when it should actually be "ses:"

### Reproduction Steps

Create a CustomResource with any SES SDK action, and use AwsCustomResourcePolicy.fromStatements() to create policy.

```javascript
// example - get DKIM verification records
new AwsCustomResource(this, 'dkimIdentity', {
            onUpdate: {
                service: 'SES',
                action: 'verifyDomainDkim',
                parameters: {
                    Domain: 'mydomain.com',
                },
                physicalResourceId: {},
            },
            policy: AwsCustomResourcePolicy.fromSdkCalls({ resources: ['*']}),
});
```

### What did you expect to happen?

```json
{
"PolicyDocument": {
          "Statement": [
            {
              "Action": "ses:VerifyDomainDkim",
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        }
}
```

### What actually happened?

```json
{
"PolicyDocument": {
          "Statement": [
            {
              "Action": "email:VerifyDomainDkim",
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        }
}
```

### Environment

  - **CDK CLI Version:** 1.100
  - **Module Version:** 1.100
  - **Node.js Version:** 14.x
  - **Language:** Javascript

### Other

Appears to happen for any SES SDK call.

Workaround is to create policy manually:

```javascript
const statement = new iam.PolicyStatement({
            actions: [
              'ses:VerifyDomainDkim',
            ],
            resources: ['*'],
});

new AwsCustomResource(this, 'dkimIdentity', {
            onUpdate: {
                service: 'SES',
                action: 'verifyDomainDkim',
                parameters: {
                    Domain: 'mydomain.com',
                },
                physicalResourceId: {},
            },
            policy: AwsCustomResourcePolicy.fromStatements([statement]),
});
```

**Comment by jogold** [comment] 2021-04-26 13:13
Duplicate of #4533

**Comment by iliapolo** [comment] 2021-05-02 20:33
As @jogold mentioned, this is a duplicate. Closing

**Closed by iliapolo** 2021-05-02 20:33 UTC
Labels: @aws-cdk/aws-ses, @aws-cdk/aws-ses-actions, @aws-cdk/custom-resources, bug, needs-triage
