### ISSUE TITLE
Adding SAM Policy Templates Support to @aws-cdk/aws-sam package

### ISSUE THREAD

**Issue by simalexan** [aws/aws-cdk#2694] opened 2019-05-30 22:11 UTC
Hi there,

AWS SAM has a list of Policy Templates that are AWS Managed Scoped Policies.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html

These policy templates are really useful when building serverless applications, and they are the recommended approach for publishing serverless components to SAR (Serverless Application Repository). I've tried to use these policies with the current state of the aws-sam package in the `policies` attribute of a `CfnFunction` but in case of a string they are always assumed to be an ARN.

Example how a Policy Template is used:
https://github.com/simalexan/api-lambda-save-dynamodb/blob/master/template.yml#L31

As a potential starting solution, maybe it could be easy to accept simple strings as `policies` with the `aws-sam` package's `CfnFunction` and let the SAR validator do the validation? (I'm guessing no already but worth suggesting a half way to a proper solution to have them working)

Thank you for taking this into consideration.
I'd be keen on helping this out, not just "requesting". Thank you again!

**Comment by simalexan** [comment] 2019-05-30 22:12
btw, I was not sure if this was a feature request or a gap. To me it looked like a gap, I might be completely wrong, so sorry about this in advance.

**Comment by nija-at** [comment] 2019-11-26 15:42
Duplicate of https://github.com/aws/aws-cdk/issues/3896. 

+1 the issue there so we can record your interest. Thanks!

**Closed by nija-at** 2019-11-26 15:42 UTC
Labels: feature-request, package/sam

**Comment by simalexan** [comment] 2019-11-26 17:07
This issue was posted a while ago, but alright, it is the same topic.
