### ISSUE TITLE
[aws-stepfunctions-tasks] How can force stepfunction task which invokes lambda to not generate metadata along with result ?

### ISSUE THREAD

**Issue by devendra-kumar1** [aws/aws-cdk#9105] opened 2020-07-16 14:47 UTC
### The Question
How can force stepfunction task which invokes lambda to not generate metadata along with result ?

### Environment

  - **CDK CLI Version:** 1.51.0
  - **Module Version:** 
  - **Node.js Version:** 12
  - **OS:** Windows 10 
  - **Language (Version):**  TypeScript (3.8.3) 

### Other information
Hi,
I am having a step function which has lambda invocation taks. It is invoking lambda correctly once step function execution starts.
But in output i am getting metadata along with output in attribute called Payload.
So is there any way through which we can omit that.

Below is the snipped i am using to created task that invokes lambda function.

new Task(scope, taskName , {            
            task: new RunLambdaTask(lambdaFunction, {

            }),
            timeout: Duration.seconds(300),
            comment: comment
        })
P.S. : I can use OutputPath to keep out required attribute from output. But I wanted to know is there any configuration kind of stuff is there which helps to omit meta data part.

**Comment by shivlaks** [comment] 2020-07-16 17:30
closing this issue as it's a duplicate of #8943

@devendra-kumar1 - there's both a workaround and a PR in flight with a fix. feel free to continue the conversation in the related issue.

**Closed by shivlaks** 2020-07-16 17:30 UTC
Labels: @aws-cdk/aws-stepfunctions-tasks, guidance, needs-triage
