### ISSUE TITLE
(aws-lambda): Construct CfnFunction requires another id called `id_` in version 1.104

### ISSUE THREAD

**Issue by lukeseawalker** [aws/aws-cdk#14728] opened 2021-05-17 11:44 UTC
calling
```
aws_lambda.CfnFunction(
  scope=[...],
  id=[...],
  code=[...],
  role=[...],
)
```

doesn't work anymore using version 1.104. It was working up to version 1.103.
It now requires `id_` to be specified.

Constructor in 1.104 is
```
@jsii.implements(aws_cdk.core.IInspectable)
class CfnFunction(
    aws_cdk.core.CfnResource,
    metaclass=jsii.JSIIMeta,
    jsii_type="@aws-cdk/aws-lambda.CfnFunction",
):
    '''A CloudFormation ``AWS::Lambda::Function``.

    :cloudformationResource: AWS::Lambda::Function
    :link: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    '''

    def __init__(
        self,
        scope: aws_cdk.core.Construct,
        id_: builtins.str,
        *,
        code: typing.Union[aws_cdk.core.IResolvable, "CfnFunction.CodeProperty"],
        role: builtins.str,
        code_signing_config_arn: typing.Optional[builtins.str] = None,
        dead_letter_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.DeadLetterConfigProperty"]] = None,
        description: typing.Optional[builtins.str] = None,
        environment: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.EnvironmentProperty"]] = None,
        file_system_configs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, typing.Sequence[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.FileSystemConfigProperty"]]]] = None,
        function_name: typing.Optional[builtins.str] = None,
        handler: typing.Optional[builtins.str] = None,
        id: typing.Optional[builtins.str] = None,
        image_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.ImageConfigProperty"]] = None,
        kms_key_arn: typing.Optional[builtins.str] = None,
        layers: typing.Optional[typing.Sequence[builtins.str]] = None,
        memory_size: typing.Optional[jsii.Number] = None,
        package_type: typing.Optional[builtins.str] = None,
        reserved_concurrent_executions: typing.Optional[jsii.Number] = None,
        runtime: typing.Optional[builtins.str] = None,
        tags: typing.Optional[typing.Sequence[aws_cdk.core.CfnTag]] = None,
        timeout: typing.Optional[jsii.Number] = None,
        tracing_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.TracingConfigProperty"]] = None,
        vpc_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.VpcConfigProperty"]] = None,
    ) -> None:
```

In version 1.103 it was
```
@jsii.implements(aws_cdk.core.IInspectable)
class CfnFunction(
    aws_cdk.core.CfnResource,
    metaclass=jsii.JSIIMeta,
    jsii_type="@aws-cdk/aws-lambda.CfnFunction",
):
    '''A CloudFormation ``AWS::Lambda::Function``.

    :cloudformationResource: AWS::Lambda::Function
    :link: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    '''

    def __init__(
        self,
        scope: aws_cdk.core.Construct,
        id: builtins.str,
        *,
        code: typing.Union[aws_cdk.core.IResolvable, "CfnFunction.CodeProperty"],
        role: builtins.str,
        code_signing_config_arn: typing.Optional[builtins.str] = None,
        dead_letter_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.DeadLetterConfigProperty"]] = None,
        description: typing.Optional[builtins.str] = None,
        environment: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.EnvironmentProperty"]] = None,
        file_system_configs: typing.Optional[typing.Union[aws_cdk.core.IResolvable, typing.Sequence[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.FileSystemConfigProperty"]]]] = None,
        function_name: typing.Optional[builtins.str] = None,
        handler: typing.Optional[builtins.str] = None,
        image_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.ImageConfigProperty"]] = None,
        kms_key_arn: typing.Optional[builtins.str] = None,
        layers: typing.Optional[typing.Sequence[builtins.str]] = None,
        memory_size: typing.Optional[jsii.Number] = None,
        package_type: typing.Optional[builtins.str] = None,
        reserved_concurrent_executions: typing.Optional[jsii.Number] = None,
        runtime: typing.Optional[builtins.str] = None,
        tags: typing.Optional[typing.Sequence[aws_cdk.core.CfnTag]] = None,
        timeout: typing.Optional[jsii.Number] = None,
        tracing_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.TracingConfigProperty"]] = None,
        vpc_config: typing.Optional[typing.Union[aws_cdk.core.IResolvable, "CfnFunction.VpcConfigProperty"]] = None,
    ) -> None
```
--- 

This is :bug: Bug Report

**Comment by tomburge** [comment] 2021-05-18 20:20
I'm having this same issue. Code that worked with 1.102.0 isn't working with 1.104.0 and returns this error message.

**Comment by nija-at** [comment] 2021-05-21 13:48
CloudFormation seems to have [introduced this property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-id) recently, however, it is marked as not required.

This is correctly translated by the CDK into an optional [parameter `id`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.CfnFunctionProps.html#id).

Can you describe what doesn't work anymore?

**Comment by lukeseawalker** [comment] 2021-05-21 13:56
The change it's not backward compatible because code that was working up to `1.103.0` doesn't work anymore in `1.104`
```
aws_lambda.CfnFunction(
  scope=[...],
  id=[...],
  code=[...],
  role=[...],
)
```

Up to `1.103.0` there was just `id` that was required.
Since `1.103.0` id become optional and `id_` required. What is `id_`? Doc is confusing as well
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/CfnFunction.html

**Comment by tomburge** [comment] 2021-05-21 14:02
@nija-at The aws-lambda package will not synth 1.04.0 or above with this error:

(hlzenv) > cdk synth
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    org_lambda_stack = LambdaStack(app, 'hlz-lambda-stack',
  File "C:\repos\aws\healthcare-landing-zone-cdk\hlzenv\lib\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "C:\repos\aws\healthcare-landing-zone-cdk\hlz\lambda_stack.py", line 38, in __init__
    self.aws_org_create = faas.CfnFunction(self,
  File "C:\repos\aws\healthcare-landing-zone-cdk\hlzenv\lib\site-packages\jsii\_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'id_'
Subprocess exited with error 1

This doesn't occur with 1.103.0 and before. @lukeseawalker  showed code from the package where if you do a diff, it shows a change from id_ to id. If CloudFormation isn't requiring the id parameter, CDK still is because the templates won't synthesize.

**Comment by nija-at** [comment] 2021-05-24 13:13
I have this Python app which using CDK version `1.104.0` - 

```python
from aws_cdk import ( core, aws_lambda as lmbda, aws_iam as iam )

app = core.App()
stack = core.Stack(app)

role = iam.Role(stack, 'MyRole', 
    assumed_by=iam.ServicePrincipal('lambda.amazonaws.com')
)

fn = lmbda.CfnFunction(stack, 'MyFunction',
  code=lmbda.CfnFunction.CodeProperty(
      zip_file='foo'
  ),
  handler='index.handler',
  runtime='nodejs12.x',
  role=role.role_arn,
)

app.synth()
```

I am able to run `cdk synth` on this which generates the template with the snippet - 

```json
  "MyFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "ZipFile": "foo"
        },
        "Role": {
          "Fn::GetAtt": [
            "MyRoleF48FFE04",
            "Arn"
          ]
        },
        "Handler": "index.handler",
        "Runtime": "nodejs12.x"
      }
    }
```

I did not receive any error during synthesis regarding `id`.

@lukeseawalker / @tomburge - can one of you provide a similar example (http://sscce.org/) which I can use to reproduce this error?

**Comment by lukeseawalker** [comment] 2021-05-24 13:26
with 1.103.0

**Comment by nija-at** [comment] 2021-05-24 13:51
I see what's going on.

The CDK (in Python) historically has used the positional argument name `id` for its construct identifier. 
The CDK also use positional arguments for the properties that go into a resource, i.e. properties such as `runtime`, `handler`, etc. in the case of `CfnFunction`. 

Once Lambda [introduced a new property named `Id`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-id), this gets mapped to the positional argument `id`. 
Consequently, the jsii Python generator had to use `id_` as the positional argument for construct identifier, so as to not conflict with the existing `id`.

Your issue will go away if you remove the `id=` entirely or change it to `id_=`.

**Comment by eladb** [comment] 2021-05-24 14:00
Very tricky problem with JSII (copy @RomainMuller, @MrArnoldPalmer)

**Comment by lukeseawalker** [comment] 2021-05-25 14:06
Thanks for the explanation. This means that everywhere we use a keyword argument to set a CDK property, we are going to hit by this whenever Cloudformation adds a property with the same name: I'm thinking about `scope` for example.

I think we will refactor our code and use only positional arguments for the CDK properties and leave the keyword argument for CloudFormation ones.

It would have been nice if CDK properties name where defined with a prefix (e.g. `_id`, `_scope`, etc...) so that this conflicts could have been prevented.

Please also notice that the official doc it's not rendered correctly because of this issue https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_lambda/CfnFunction.html

Thanks

**Comment by nija-at** [comment] 2021-05-25 15:47
@rix0rrr @RomainMuller - the documentation is not reflecting the correct 'keyword' for the arguments to `CfnFunction`. Any idea why?

**Comment by RomainMuller** [comment] 2021-05-25 15:51
I'm going to venture this is because a trailing `_` on a label in ReST format has a specific meaning (and hence it does not get rendered in the HTML). Maybe we are missing an escape sequence somewhere or something like so...

**Comment by nirmash** [comment] 2021-05-25 18:10
Hey folks, we have identified the issue on our side and are in the process of deploying a fix that removes the Id property from the Lambda side. I will update here when deployment is done.
Apologies for the inconvenience.
Nir (Lambda team)

**Comment by nija-at** [comment] 2021-08-24 12:00
I believe this has since been fixed. Closing.

**Closed by nija-at** 2021-08-24 12:00 UTC
Labels: bug, p2, @aws-cdk/aws-lambda, needs-cfn
