### ISSUE TITLE
IPrincipal Interface support multi assumeRoleAction

### ISSUE THREAD

**Issue by muramasa64** [aws/aws-cdk#6699] opened 2020-03-12 15:58 UTC
The type of the property assumeRoleAction of the IPrincipal interface is string.

Now that ABAC is supported, assumeRoleAction must be a string[].

### Use Case

The following AWS Security Blog, which describes ABAC, contains the Role Trust Policy required for using ABAC.

https://aws.amazon.com/jp/blogs/security/rely-employee-attributes-from-corporate-directory-create-fine-grained-permissions-aws/

The Role Trust Policy is quoted below. The Action defined in the Statement has multiple entries.

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Principal": {
				"Federated": "arn:aws:iam::999999999999:saml-provider/ExampleCorpProvider"
			},
			"Action": [
				"sts:AssumeRoleWithSAML",
				"sts:TagSession"
			],
			"Condition": {
				"StringEquals": {
					"SAML:aud": "https://signin.aws.amazon.com/saml"
				},
				"StringLike": {
					"aws:RequestTag/project": "*",
					"aws:RequestTag/jobfunction": [
						"SystemsEngineer",
						"DatabaseEngineer"
					]
				}
			}
		}
	]
}

```

### Proposed Solution

Change the type of assumeRoleAction property of IPrincipal to string[].

### Other

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by redbaron** [comment] 2020-12-05 00:20
Looks like duplicate of https://github.com/aws/aws-cdk/issues/2041

**Comment by lkr2des** [comment] 2021-12-17 17:12
Seems similar issue.
I need to create a AssumeRolePolicyDocument  like below attached to a federated role, unable to do that today.Any ideas or help is appreciate.

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::xxxxxxxxxxxxxxxxx:saml-provider/okta-quicksight"
      },
      "Action": "sts:AssumeRoleWithSAML",
      "Condition": {
        "StringEquals": {
          "SAML:aud": "https://signin.aws.amazon.com/saml"
        }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::xxxxxxxxx:saml-provider/okta-quicksight"
      },
      "Action": "sts:TagSession",
      "Condition": {
        "StringLike": {
          "aws:RequestTag/Email": "*"
        }
      }
    }
  ]
}

**Comment by atpollmann** [comment] 2022-08-29 03:54
This is resolved with the `withSessionTags` method as described here https://github.com/aws/aws-cdk/pull/17689

**Comment by comcalvi** [comment] 2023-01-26 23:35
Resolved by #17689

**Closed by comcalvi** 2023-01-26 23:35 UTC
Labels: p1, feature-request, @aws-cdk/aws-iam, effort/medium
