### ISSUE TITLE
(aws-glue) add option to pass in more parameters (e.g. partition projection, regex serde, etc.)

### ISSUE THREAD

**Issue by naseemkullah** [aws/aws-cdk#16660] opened 2021-09-25 18:44 UTC
Hello,

In order to setup querying ALB logs  as described [here](https://aws.amazon.com/premiumsupport/knowledge-center/athena-analyze-access-logs/):

https://github.com/aws/aws-cdk/blob/2157acd4287dc9df1ae4642bbe049c181e3432b6/packages/%40aws-cdk/aws-glue/lib/table.ts#L263-L266

I'd like to pass in parameters for partition projection such as:

```
'projection.day.digits'='2',
'projection.day.range'='01,31',
'projection.day.type'='integer',
'projection.enabled'='true',
'projection.month.digits'='2',
'projection.month.range'='01,12',
'projection.month.type'='integer',
'projection.year.digits'='4',
'projection.year.range'='2020,2021',
'projection.year.type'='integer',
"storage.location.template" = "s3://my_log_bucket/AWSLogs/1111222233334444/elasticloadbalancing/us-east-1/${year}/${month}/${day}"
```

Workarounds have been shared in https://github.com/aws/aws-cdk/issues/3665 

https://github.com/aws/aws-cdk/blob/2157acd4287dc9df1ae4642bbe049c181e3432b6/packages/%40aws-cdk/aws-glue/lib/table.ts#L274-L276

Secondly I'd like to also pass in `TableInput.StorageDescriptor.SerdeInfo.Parameters`  (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-serdeinfo.html)

Would it be possible to add these config options to `Table` ?

**Comment by naseemkullah** [comment] 2021-09-28 17:27
friendly ping

**Comment by kaizen3031593** [comment] 2021-09-30 14:49
Hi @naseemkullah. I am closing this issue as a duplicate of #14159. You can add your +1 to that issue to show your support, but it has been marked as `p2`, which means that we are unable to work on it immediately. 

Your workaround ([link](https://github.com/aws/aws-cdk/issues/3665#issuecomment-752763570) to specific comment) is to use `CfnTable`, which is a good one. Generally, you can also use [escape hatches](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html) when a feature is available in CloudFormation but not in the CDK. That would look something like this:

```ts
const table = new glue.Table(...);
const cfnTable = table.node.defaultChild as glue.CfnTable;

cfnTable.tableInput.parameters = {
}
```

Hope this helps! You can do the same for serdeInfo.

**Closed by kaizen3031593** 2021-09-30 14:49 UTC
Labels: @aws-cdk/aws-glue, needs-triage

**Comment by naseemkullah** [comment] 2021-09-30 14:57
Ok, thanks @kaizen3031593
