### ISSUE TITLE
(aws-cdk.pipelines): API 2.0 - Adding a CodeBuildStep in an independent stage

### ISSUE THREAD

**Issue by jaidisido** [aws/aws-cdk#18041] opened 2021-12-15 15:04 UTC
### Description

As part of our migration to CDK V2, we are trying to move away from the original `pipelines` library and leverage the constructs in the Modern API instead.

One snag that we have hit however is an inability to add a `CodeBuildStep` as an independent stage in the CICD pipeline, i.e. without linking it to an application stage as a `pre` or `post` action. 

In the Original pipelines API, that could easily be done like this:
```
my_pipeline.add_stage("SecurityLint").add_actions(ShellScriptAction(action_name="Lint", commands=["./scan.sh"]))
```
which adds a CodeBuild stage that is independent from any application stage in the pipeline.

As far as I can tell, there is no equivalent method in the Modern API.

One "hack" we found is to abuse the `add_wave` method for that purpose, where a single action is supplied:
```
my_pipeline.add_wave(
            "SecurityLint",
            post=[
              ShellStep(
                      "Lint",
                      input=artifacts,
                      commands=["./scan.sh"],
                  ),
            ],
        )
```
But I don't believe that is the intent behind this method.

Another option could be to access the underlying CodePipeline instance and add actions to it which feels as much of a hack.

### Use Case

Some stages such as security checks, linting or tests are not linked to the application stages and we should have the ability to add them independently of a CFN deployment

### Proposed Solution

Replicate the `add_stage` method from the Original API which does not require passing an application stage

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by markusl** [comment] 2021-12-15 18:06
We encountered the same problem already in august and found out that it's not part of the design: https://github.com/aws/aws-cdk/issues/15945

It's not very clear to me why is that because it would make the API much more fluent if this was allowed.

**Comment by jaidisido** [comment] 2021-12-16 10:56
Thanks @markusl! Agreed, not sure why it's not part of the design. Adding an independent shell stage seems like a simple requirement any CICD pipeline should support

**Comment by rix0rrr** [comment] 2021-12-24 13:12
Duplicate of #15945

**Closed by rix0rrr** 2021-12-24 13:12 UTC
Labels: feature-request, needs-triage, @aws-cdk/pipelines
