### ISSUE TITLE
[aws-networkfirewall] Add support for AWS Network Firewall

### ISSUE THREAD

**Issue by bf-sodle** [aws/aws-cdk#11675] opened 2020-11-24 17:57 UTC
The new managed AWS Network Firewall service is now available, and has [CloudFormation support](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_NetworkFirewall.html).

### Use Case

Need to create a firewall.

### Proposed Solution

 CDK should incorporate L1 and eventually L2 constructs for the AWS Network Firewall.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by sciarrilli** [comment] 2020-12-05 15:22
@SomayaB I’m curious what the time frame is for this?

**Comment by codypenta** [comment] 2020-12-07 18:54
L1 constructs for Network firewall is included in the 1.77 release of CDK. Docs are still updating (Currently 1.76) but since it's L1, it just points to CFN docs: https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-networkfirewall

**Comment by SomayaB** [comment] 2020-12-07 22:55
@sciarrilli The L1 is awaiting release and was merged a few days after it was added to Cloudformation, which always happens automatically whenever a new resource is added to CFN. As far as an L2, we don't have a timeline right now but we welcome PRs, here's the [tracking issue for the L2](https://github.com/aws/aws-cdk/issues/11925).

**Closed by SomayaB** 2020-12-07 22:55 UTC
Labels: feature-request, needs-triage

**Comment by bf-sodle** [comment] 2020-12-08 23:07
@SomayaB I am unable to deploy the `CfnFirewallPolicy` construct included in this update. TypeScript sees the construct as valid, but CloudFormation raises the following validation errors:
```
Properties validation failed for resource firewallpolicy with message:
#/Tags: expected type: JSONArray, found: JSONObject
#/FirewallPolicy/StatelessDefaultActions: expected type: JSONArray, found: JSONObject
#/FirewallPolicy/StatelessFragmentDefaultActions: expected type: JSONArray, found: JSONObject
```

On further inspection of the CloudFormation documentation, I believe there is an inconsistency in the spec for this resource. The [specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-networkfirewall-firewallpolicy-statelessactions.html) seems to define `AWS::NetworkFirewall::FirewallPolicy.StatelessActions` as a nested object, but the [top-level example](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkfirewall-firewallpolicy.html#aws-resource-networkfirewall-firewallpolicy--examples) shows it as a simple list. I believe the CDK is synthesizing the nested object form, while CloudFormation is actually expecting the list form.

**Comment by skinny85** [comment] 2020-12-09 20:37
Thanks for reporting @bf-sodle . Confirmed I was able to reproduce the error. Working on a fix.

**Comment by bf-sodle** [comment] 2020-12-09 21:37
I've just reproduced it with the Tags property on CfnRuleGroup as well. Haven't tested other constructs yet.

**Comment by bf-sodle** [comment] 2020-12-09 21:37
Thank you for looking at this!

**Comment by SomayaB** [comment] 2020-12-10 02:56
I opened a new issue specifically for this bug [here](https://github.com/aws/aws-cdk/issues/11974).
