### ISSUE TITLE
(pipeline-actions): variables missing on CodeStarConnectionsSourceAction

### ISSUE THREAD

**Issue by drudderd** [aws/aws-cdk#17879] opened 2021-12-07 09:24 UTC
### Description

Different source-actions (like Github, Bitbucket) provide a variables property that can be used to pass variables as environment variable to a build step in a pipeline.

I am using aws-cdk v2 using a CodeStarConnectsionSourceAction to connect to Github, but the variables property is missing.

### Use Case

    const sourceAction = new codePipelineActions.CodeStarConnectionsSourceAction({
      actionName: 'Github-source',
      owner: '...',
      repo: '...',
      output: sourceOutput,
      connectionArn: codestarConnectionArn,
      variablesNamespace: 'SourceVariables',
      role: codePipelineRole
    });

    const sourceStage = pipeline.addStage({ stageName: "Source" });
    sourceStage.addAction(sourceAction);

    const buildAction = new codePipelineActions.CodeBuildAction({
      actionName: 'Build',
      project: project,
      input: sourceOutput,
      environmentVariables: {
        ECR_REPO: {
          value: codebuildStack.containerRepository.repositoryUri
        },
        COMMIT_ID: {
          value: sourceAction.variables.CommitId
        },
        BRANCH_NAME: {
          value: sourceAction.variables.BranchName
        }
      },
      role: codePipelineRole
    });

### Proposed Solution

I assume this can be implemented exactly the same way as the other implementations. 

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by skinny85** [comment] 2021-12-07 16:55
Hey @drudderd, thanks for opening the issue. I believe this is a duplicate of https://github.com/aws/aws-cdk/issues/17807, let's move the conversation there.

**Closed by skinny85** 2021-12-07 16:55 UTC
Labels: feature-request, needs-triage, @aws-cdk/aws-codepipeline-actions
