### ISSUE TITLE
(EventBridge): only first target of Rule get policy applied

### ISSUE THREAD

**Issue by larry-palmer** [aws/aws-cdk#12300] opened 2021-01-01 02:56 UTC
When adding more than one lambda to a EventBridge rule, either with successive .addTarget() calls, or by supplying an array of lambdas to the rule constructor, IAM policy is only generated to send to the first target

### Reproduction Steps

```TS
export function createEventRules(
  scope: cdk.Construct,
  eventBus: EventBus,
  targets: IRuleTarget[]
): void {
  const emailRule = new Rule(scope, "All-Emails", {
    description: "Matches all events for emails",
    enabled: true,
    eventBus: eventBus,
    eventPattern: {
      detailType: ["EmailEvent"],
    },
    targets: targets,
  });
}


createEventRules(this, eventBus, [
      new LambdaFunction(lambda1),
      new LambdaFunction(lambda2),
      ]);
```

### What did you expect to happen?

send the same event to two different lambdas

### What actually happened?

whichever lambda is in the list first gets a policy generated to allow EventBridge to send events to it; the second does not. Can see this by doing a deploy, rebuilding with the targets in the opposite order, and deploying again. It warns you that permissions are being removed from one lambda and applied to the other.
Subsequently, "aws lambda get-policy --function-name lambda1" and "aws lambda get-policy --function-name lambda2" will show the policy only on one of them.

### Environment

  - **CDK CLI Version  :** Brazil CDKBuild 2.x
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :** Amazon Linux 2
  - **Language (Version):** 

### Other

Problem seems to have appeared after upgrading to CDKBuild 2.x
```ts
    build-tools = {
        1.0 = {
            CDKBuild = 2.x;
            NodeJS = 12.x;
            NpmPrettyMuch = 1.0;
        };
    };
```

--- 

This is :bug: Bug Report

**Comment by mw-deb** [comment] 2021-02-10 13:16
me too

**Comment by udondan** [comment] 2021-02-10 13:46
Confirming this. In the rendered CFN template it looks like all the lambdas are set as targets, but only for a single Lambda the `AWS::Lambda::Permission` is defined, to allow the `InvokeFunction` action. Interestingly CFN doesn't complain during deployment. It silently skips the target which has no corresponding permission.

**Comment by JacobAMason** [comment] 2021-03-07 04:14
Looks like this has been solved in https://github.com/aws/aws-cdk/issues/13231

**Comment by ryparker** [comment] 2021-06-14 23:20
Hey @larry-palmer 

Thanks for bringing this to our attention. I spent some time attempting to reproduce this with the latest CDK package (Version 1.108.1). It's likely that this was fixed in a recent update. Could you confirm if this is still an issue?

Here's what I did to reproduce...


Code: 

```TS
import * as cdk from '@aws-cdk/core';
import { Rule, IRuleTarget } from '@aws-cdk/aws-events';
import { LambdaFunction } from '@aws-cdk/aws-events-targets';
import { EventBus } from '@aws-cdk/aws-events';
import * as lambda from '@aws-cdk/aws-lambda';

const app = new cdk.App();

const stack1 = new cdk.Stack(app, 'stack1');

const lambda1 = new lambda.Function(stack1, 'lambdaFunction1', {
  functionName: 'lambdaFunction1',
  code: lambda.Code.fromInline('whatever'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_10_X,
});

const lambda2 = new lambda.Function(stack1, 'lambdaFunction2', {
  functionName: 'lambdaFunction2',
  code: lambda.Code.fromInline('whatever'),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_10_X,
});

export function createEventRules(
  scope: cdk.Construct,
  eventBus: EventBus,
  targets: IRuleTarget[]
): void {
  const emailRule = new Rule(scope, 'All-Emails', {
    description: 'Matches all events for emails',
    enabled: true,
    eventBus: eventBus,
    eventPattern: {
      detailType: ['EmailEvent'],
    },
    targets: targets,
  });
}

const eventBus = new EventBus(stack1, 'eventBus');

createEventRules(stack1, eventBus, [
  new LambdaFunction(lambda1),
  new LambdaFunction(lambda2),
]);
```

Then I ran 

```shell
aws lambda get-policy --function-name lambdaFunction1
```

and compared that output with the output for the other lambda function's policy:

```shell
aws lambda get-policy --function-name lambdaFunction2
```

I noticed that both lambdas had different policies generated as expected.

Let me know if you're still running into this otherwise we'll go ahead and close this.

**Comment by peterwoodworth** [comment] 2021-07-07 23:53
Closing because the labels have been applied for more than two weeks. Ping us if you have additional problems with this issue!

**Closed by peterwoodworth** 2021-07-07 23:53 UTC
Labels: @aws-cdk/aws-events, bug, closing-soon, effort/medium, p1, response-requested
