### ISSUE TITLE
apigatewayv2: Add authorizer to Websocket API $connect

### ISSUE THREAD

**Issue by michaelgmcd** [aws/aws-cdk#14085] opened 2021-04-09 15:18 UTC
Currently, I'm making my websocket authorizer using `CfnAuthorizer` and `CfnPermission` (under development now, still not tested):
```
  new CfnAuthorizer(stack, 'WSAuthorizer', {
    name: 'wsAuthorizer',
    apiId: wsApi.apiId,
    authorizerType: 'REQUEST',
    authorizerUri: `arn:aws:apigateway:${constants.region}:lambda:path/2015-03-31/functions/${lambdas.wsAuth.functionArn}/invocations`,
    identitySource: ['route.request.querystring.token'],
  });

  new CfnPermission(stack, 'ConnectLambdaPermission', {
    action: 'lambda:InvokeFunction',
    functionName: lambdas.wsAuth.functionArn,
    principal: `apigateway.${stack.urlSuffix}`,
  });
```

### Use Case

I'd like to be able to use an authorizer without having to go into the AWS Console.

### Proposed Solution

TBD. Looking through the WebSocket API now.

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by michaelgmcd** [comment] 2021-04-09 17:53
I was able to get to to work with a patch:
```
const wsApi = new WebSocketApi(stack, 'wsApi', {
    routeSelectionExpression: '$request.body.action',
    disconnectRouteOptions: {
      integration: new LambdaWebSocketIntegration({
        handler: lambdas.wsDisconnect,
      }),
    },
    defaultRouteOptions: {
      integration: new LambdaWebSocketIntegration({
        handler: lambdas.wsDefault,
      }),
    },
  });

  new WebSocketStage(stack, 'wsStage', {
    webSocketApi: wsApi,
    stageName: 'ws',
    autoDeploy: true,
    domainMapping: { domainName: wsDomainName },
  });

  const wsAuthorizer = new CfnAuthorizer(stack, 'WSAuthorizer', {
    name: 'wsAuthorizer',
    apiId: wsApi.apiId,
    authorizerType: 'REQUEST',
    authorizerUri: `arn:aws:apigateway:${constants.region}:lambda:path/2015-03-31/functions/${lambdas.wsAuth.functionArn}/invocations`,
    identitySource: ['route.request.querystring.token'],
  });

  wsApi.addRoute('$connect', {
    // @ts-ignore
    authorizerId: wsAuthorizer.ref,
    authorizationType: 'CUSTOM',
    integration: new LambdaWebSocketIntegration({
      handler: lambdas.wsConnect,
    }),
  });
```

```
class WebSocketRoute extends core_1.Resource {
    /**
     * @experimental
     */
    constructor(scope, id, props) {
        super(scope, id);
        this.webSocketApi = props.webSocketApi;
        this.routeKey = props.routeKey;
        const config = props.integration.bind({
            route: this,
            scope: this,
        });
        const integration = props.webSocketApi._addIntegration(this, config);
        const route = new apigatewayv2_generated_1.CfnRoute(this, 'Resource', {
            apiId: props.webSocketApi.apiId,
            routeKey: props.routeKey,
            target: `integrations/${integration.integrationId}`,
            authorizerId: props.authorizerId, // <========================== Added this
            authorizationType: props.authorizationType, // <=================== Added this
        });
        this.routeId = route.ref;
    }
}
```

**Comment by nija-at** [comment] 2021-04-13 11:22
Duplicate of https://github.com/aws/aws-cdk/issues/13869

**Closed by nija-at** 2021-04-13 11:22 UTC
Labels: @aws-cdk/aws-apigatewayv2, feature-request, needs-triage
