### ISSUE TITLE
(pipelines) - pass cdk.json to the build stage. 

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk#12205] opened 2020-12-23 08:25 UTC
Either provide an optional parameter to specify the toolkit stack-name that gets used, so, you can use something other than the default, or provide the cdk.json to the deploy stage. 

### Use Case

I am in the situation where a managed service provider has installed a set of baseline-tools that overwrite the default cdk-bootstrapping daily if its been modifyied.  This is having the effect of going from bootstrap version 4 to version 0 each day. 

This has forced me to use a separate bootstrap toolkit. 

I have modifyed the projects cdk.json to include 
     "toolkitStackName": "fudawl"

This allowed me to do the initial deploy.     However the   'UpdatePipeline' Stage, was failing.    After some investigation we discovered that the cdk.json file is not being passed to the build phase., so it was trying to use the default bootstrap. 

My intial 'hack' was to change the buildspec for the stage,    I did this at teh console to see if it would work, and it did, but i could'nt find an easy way to modify it from the CF stack. 

```
{
  "version": "0.2",
  "phases": {
    "install": {
      "commands": "npm install -g aws-cdk"
    },
    "build": {
      "commands": [
        "cdk -a . deploy MyProject --require-approval=never --verbose"
      ]
    }
  }
} 
```

my co-worker was looking at the artifacts and discovered cdk.json was'tn being based to the build stage, and thought that we might be able to resolve this in a slightly different way, which we were able to.. 

```
pipeline = pipelines.CdkPipeline(self, project_name + 'Pipeline',
        cloud_assembly_artifact = cloud_assembly_artifact,
        pipeline_name = project_name,
        source_action=pipeline_source_action,
        synth_action=pipelines.SimpleSynthAction(
          source_artifact=source_artifact,
          cloud_assembly_artifact=cloud_assembly_artifact,
          install_command='npm install -g aws-cdk && pip install -r requirements.txt',
          #build_command='pytest unittests',
          synth_command='cdk synth && cp cdk.json cdk.out')
    )
```

Effectively what we've done here is pass an extra command on the synth command, which copied cdk.json into cdk.out.. When it deployed.. it used the took kit that was specified in cdk.json

I'm not entirely sure if a solution is in fact needed, as the 'work around' did the job. However it does not seem that good of a solution and it feels contrived.   The docs suggested that we could use another codepipeline, perhaps that is a way that we could code the various tweaks in for edge cases like this..     

Perhaps just providing an optional parameter in the cdkpipeline config..  

```
pipeline = pipelines.CdkPipeline(self, project_name + 'Pipeline',
        cloud_assembly_artifact = cloud_assembly_artifact,
        pipeline_name = project_name,
        source_action=pipeline_source_action,
        synth_action=pipelines.SimpleSynthAction(
          source_artifact=source_artifact,
          cloud_assembly_artifact=cloud_assembly_artifact,
          install_command='npm install -g aws-cdk && pip install -r requirements.txt',
          #build_command='pytest unittests',
          synth_command='cdk synth'),
          bootstrap_toolkit = something
          
    )
```

**Comment by rix0rrr** [comment] 2020-12-23 08:38
Duplicate of https://github.com/aws/aws-cdk/issues/9053

**Closed by rix0rrr** 2020-12-23 08:38 UTC
Labels: @aws-cdk/pipelines, feature-request, needs-triage
