### ISSUE TITLE
(Route 53): interface like IHostedZone should define construct specific methods

### ISSUE THREAD

**Issue by ap00rv** [aws/aws-cdk#15786] opened 2021-07-27 19:38 UTC
Interfaces like [`IHostedZone`](https://github.com/aws/aws-cdk/blob/2cefe57835391155aa01962f01fe13fbf7b85c3a/packages/%40aws-cdk/aws-route53/lib/hosted-zone-ref.ts#L6) do not define construct specific methods like `addVpc()` . Same thing applies for other interfaces in this construct like `IPublicHostedZone` and `IPrivateHostedZone`.   This prevents us from creating a construct by importing existing R53 hosted zone and then calling methods like `addVpc()` or `addDelegation()` on the construct. 

P.S. a workaround with type casting is available

### Reproduction Steps

write something like this : 

`PrivateHostedZone.fromPrivateHostedZoneId(this, 'hostedZoneID', hostedZoneId).addVpc(vpc)`

### What did you expect to happen?

`PrivateHostedZone.fromPrivateHostedZoneId(this, 'hostedZoneID', hostedZoneId).addVpc(vpc)` should work without compilation errors. 

### What actually happened?

This will give compilation error  :

`Property 'addVpc' does not exist on type 'IPrivateHostedZone'.`

The return type of `fromPrivateHostedZoneId()` method is `IPrivateHostedZone` , which does not have `addVpc()` method defined in itself or its [parent interface](https://github.com/aws/aws-cdk/blob/2cefe57835391155aa01962f01fe13fbf7b85c3a/packages/%40aws-cdk/aws-route53/lib/hosted-zone-ref.ts#L6). 

### Environment

  - **CDK CLI Version  :*1.101.0*
  - **Framework Version:*1.101.0*
  - **Node.js Version:**  14.x
  - **OS               :*Amazon Linux 2*
  - **Language (Version):**  TypeScript 4.2.3

### Other

Workaround by type casting:

`PrivateHostedZone.fromPrivateHostedZoneId(this, 'hostedZoneID', hostedZoneId) as PrivateHostedZone).addVpc(vpc)` 

--- 

This is :rocket: Feature Request

**Comment by ryparker** [comment] 2021-07-27 20:24
:wave: Hey @ap00rv 

Thanks for opening this issue. Because this functionality has not yet been implemented I am going to relabel this as a feature-request.

I'm also unassigning and marking this issue as p2 which means that we are unable to work on this immediately. I know the type casting is not ideal but it does serve as a workaround for the mean time. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md).)
🙏

**Comment by ryparker** [comment] 2021-07-30 22:53
@ap00rv

After some investigation the type returned by `PrivateHostedZone.fromPrivateHostedZoneId()` should not include methods such as `addVpc()` by design. Imported resources cannot be modified using the CDK. Even though the Typescript error is resolved with typecasting you'll notice that modifying the imported resource does not actually do anything.

See the "Importing existing external resources" section in the [CDK resource importing docs](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing)

>Although you can use an imported resource anywhere, you cannot modify the imported resource. For example, calling addToResourcePolicy (Python: add_to_resource_policy) on an imported s3.Bucket does nothing.

**Comment by ap00rv** [comment] 2021-08-16 17:19
> @ap00rv
> 
> After some investigation I've found that the type returned by `PrivateHostedZone.fromPrivateHostedZoneId()` should not include methods such as `addVpc()` by design. Imported resources cannot be modified using the CDK. Even though the Typescript error is resolved with typecasting you'll notice that modifying the imported resource does not actually do anything.
> 
> See the "Importing existing external resources" section in the [CDK resource importing docs](https://docs.aws.amazon.com/cdk/latest/guide/resources.html#resources_importing)
> 
> > Although you can use an imported resource anywhere, you cannot modify the imported resource. For example, calling addToResourcePolicy (Python: add_to_resource_policy) on an imported s3.Bucket does nothing.

Sounds good. I guess then this issue is not applicable ? Please feel free to close this. Thanks for your time.

**Closed** 2021-08-16 17:35 UTC
Labels: p2, closing-soon, feature-request, @aws-cdk/aws-route53, effort/small
