### ISSUE TITLE
There's no error by CDK when using expired temporary credentials and the system just hangs without feedback or errors thrown

### ISSUE THREAD

**Issue by UrfTheManatee** [aws/aws-cdk#15481] opened 2021-07-09 17:12 UTC
### The Question
The CDK just hangs at the "Reading existing template for stack" step when deploying with expired temporary credentials. 

### Environment

  - **CDK CLI Version:** 1.111.0 (build 556ca93)
  - **Module Version:** N.A.
  - **Node.js Version:**  v16.3.0
  - **OS:** MacOS
  - **Language:** all

### Other information
I would suggest to implement a check so that when deploying and the temporary credentials are incorrect that a descriptive error is thrown.

**Comment by peterwoodworth** [comment] 2021-07-12 21:17
I'll try and reproduce this then get back to you

**Comment by peterwoodworth** [comment] 2021-07-12 23:01
Yup, it's doing this for me as well. Thank you for reporting this!

**Comment by peterwoodworth** [comment] 2021-07-12 23:08
Ah, it looks like this is a duplicate issue. Closing in favor of #14109

**Closed by peterwoodworth** 2021-07-12 23:08 UTC
Labels: feature-request, feature/enhancement, p2, package/tools
