### ISSUE TITLE
Lambda Event Sources need to create a dependency to the OnFailure resource

### ISSUE THREAD

**Issue by xerofun** [aws/aws-cdk#6939] opened 2020-03-23 11:55 UTC
Without the dependsOn being generated in the CFT the EventSource can be generated with an empty OnFailure destination.

### Reproduction Steps

```typescript
import cdk = require('@aws-cdk/core');
import dynamodb = require('@aws-cdk/aws-dynamodb');
import eventSource = require('@aws-cdk/aws-lambda-event-sources');
import lambda = require('@aws-cdk/aws-lambda');
import sqs = require('@aws-cdk/aws-sqs');
import {Construct} from "@aws-cdk/core";

export class CdkTestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const table = new dynamodb.Table(this, 'table', {
      partitionKey: {
        name: 'pk',
        type: dynamodb.AttributeType.STRING
      },
      stream: dynamodb.StreamViewType.NEW_IMAGE
    });

    const testlambda = new lambda.Function(this, 'TestFunction', {
      code: lambda.Code.fromInline('handler = () => console.log("handled");'),
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'index.handler',
      description: 'Example function',
    });

    const sqsQueue = new sqs.Queue(this, 'sqsDLQ', {
    });

    testlambda.addEventSource(
        new eventSource.DynamoEventSource(table, {
          startingPosition: lambda.StartingPosition.TRIM_HORIZON,
          batchSize: 1,
          retryAttempts: 0,
          onFailure: new eventSource.SqsDlq(sqsQueue)
        })
    );
  }
}
```

### Environment

  - **CLI Version      : >1.29.0 **
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other
Register dependency on the DLQ with the EventSource when it is created.

Hack work around (added to stack):

```typescript
    let dynamoDBEventSource = {} as Construct;

    for (let i = 0; i < testlambda.node.children.length; i++) {
        if (testlambda.node.children[i].node.uniqueId.includes('DynamoDBEventSource')) {
            dynamoDBEventSource = testlambda.node.children[i] as Construct;
        }
    }

    dynamoDBEventSource.node.addDependency(sqsQueue);
```

--- 

This is :bug: Bug Report

**Comment by xerofun** [comment] 2020-03-23 11:56
Having written the offending code (and needing it!), I was going to get a PR out for this shortly

**Comment by nija-at** [comment] 2020-03-25 13:47
Thanks for filing this @xerofun. We would appreciate it if you can get a PR out for this.

To clarify - does this cause the CF to fail or that the SQS queue is silently not configured as a DLQ for the event source?

**Comment by xerofun** [comment] 2020-03-26 13:39
It causes it to silently not be configured.  It may be a race condition as it worked fine in our integration test, but when applying it to a more complicated stack it ended up missing the onFailure configuration in the event source although the generated CFT had it.

**Comment by nija-at** [comment] 2020-03-27 15:33
@xerofun -

I can't reproduce this error. I've taken your code snippet, adjusted it slightly as below -

<details>
<summary>CDK code</summary>

```ts
import { AttributeType, StreamViewType, Table } from '@aws-cdk/aws-dynamodb';
import { Code, Function, Runtime, StartingPosition } from '@aws-cdk/aws-lambda';
import { Queue } from '@aws-cdk/aws-sqs';
import { App, Stack } from '@aws-cdk/core';
import { DynamoEventSource, SqsDlq } from '@aws-cdk/aws-lambda-event-sources';

class TestStack extends Stack {
  constructor(scope: App, id: string) {
    super(scope, id);

    const table = new Table(this, 'table', {
      partitionKey: {
        name: 'pk',
        type: AttributeType.STRING
      },
      stream: StreamViewType.NEW_IMAGE
    });

    const sqsFn = new Function(this, 'SqsFunction', {
      code: Code.fromInline('handler = () => console.log("handled");'),
      runtime: Runtime.NODEJS_12_X,
      handler: 'index.handler',
    });

    const sqsQueue = new Queue(this, 'sqsDLQ');

    sqsFn.addEventSource(
      new DynamoEventSource(table, {
        startingPosition: StartingPosition.TRIM_HORIZON,
        onFailure: new SqsDlq(sqsQueue)
      })
    );
  }
}

const app = new App();
new TestStack(app, 'integ-eventsource-dlqdeps');
```

</details>

And this is the synthesized template -

<details>
<summary>Synthesized template</summary>

```json
{
  "Resources": {
    "table8235A42E": {
      "Type": "AWS::DynamoDB::Table",
      "Properties": {
        "KeySchema": [
          {
            "AttributeName": "pk",
            "KeyType": "HASH"
          }
        ],
        "AttributeDefinitions": [
          {
            "AttributeName": "pk",
            "AttributeType": "S"
          }
        ],
        "ProvisionedThroughput": {
          "ReadCapacityUnits": 5,
          "WriteCapacityUnits": 5
        },
        "StreamSpecification": {
          "StreamViewType": "NEW_IMAGE"
        }
      },
      "UpdateReplacePolicy": "Retain",
      "DeletionPolicy": "Retain",
      "Metadata": {
        "aws:cdk:path": "integ-eventsource-dlqdeps/table/Resource"
      }
    },
    "SqsFunctionServiceRole094426BD": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
              ]
            ]
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "integ-eventsource-dlqdeps/SqsFunction/ServiceRole/Resource"
      }
    },
    "SqsFunctionServiceRoleDefaultPolicyF634AC5F": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sqs:SendMessage",
                "sqs:GetQueueAttributes",
                "sqs:GetQueueUrl"
              ],
              "Effect": "Allow",
              "Resource": {
                "Fn::GetAtt": [
                  "sqsDLQ3C1253C0",
                  "Arn"
                ]
              }
            },
            {
              "Action": "dynamodb:ListStreams",
              "Effect": "Allow",
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    {
                      "Fn::GetAtt": [
                        "table8235A42E",
                        "Arn"
                      ]
                    },
                    "/stream/*"
                  ]
                ]
              }
            },
            {
              "Action": [
                "dynamodb:DescribeStream",
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator"
              ],
              "Effect": "Allow",
              "Resource": {
                "Fn::GetAtt": [
                  "table8235A42E",
                  "StreamArn"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "PolicyName": "SqsFunctionServiceRoleDefaultPolicyF634AC5F",
        "Roles": [
          {
            "Ref": "SqsFunctionServiceRole094426BD"
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "integ-eventsource-dlqdeps/SqsFunction/ServiceRole/DefaultPolicy/Resource"
      }
    },
    "SqsFunction1FCDD803": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "ZipFile": "handler = () => console.log(\"handled\");"
        },
        "Handler": "index.handler",
        "Role": {
          "Fn::GetAtt": [
            "SqsFunctionServiceRole094426BD",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x"
      },
      "DependsOn": [
        "SqsFunctionServiceRoleDefaultPolicyF634AC5F",
        "SqsFunctionServiceRole094426BD"
      ],
      "Metadata": {
        "aws:cdk:path": "integ-eventsource-dlqdeps/SqsFunction/Resource"
      }
    },
    "SqsFunctionDynamoDBEventSourceintegeventsourcedlqdepstable164A9205E85E8867": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "Properties": {
        "EventSourceArn": {
          "Fn::GetAtt": [
            "table8235A42E",
            "StreamArn"
          ]
        },
        "FunctionName": {
          "Ref": "SqsFunction1FCDD803"
        },
        "BatchSize": 100,
        "DestinationConfig": {
          "OnFailure": {
            "Destination": {
              "Fn::GetAtt": [
                "sqsDLQ3C1253C0",
                "Arn"
              ]
            }
          }
        },
        "StartingPosition": "TRIM_HORIZON"
      },
      "Metadata": {
        "aws:cdk:path": "integ-eventsource-dlqdeps/SqsFunction/DynamoDBEventSource:integeventsourcedlqdepstable164A9205/Resource"
      }
    },
    "sqsDLQ3C1253C0": {
      "Type": "AWS::SQS::Queue",
      "Metadata": {
        "aws:cdk:path": "integ-eventsource-dlqdeps/sqsDLQ/Resource"
      }
    }
  }
}
```

</details>

The `onFailure` section correctly shows the SQS queue.

**Comment by xerofun** [comment] 2020-03-27 16:49
It shows correctly in the CFT for me as well, but does not appear in the event source mapping that is deployed.  My suspicion is that there is a race condition due to the lack of dependency so the event source mapping is created before an ARN is available for the SQS queue.  Regardless of being able to consistently reproduce this, I *think* it's semantically correct to have this dependency explicitly defined.

Thoughts?

**Comment by nija-at** [comment] 2020-03-27 16:51
I see. Yes, it's semantically correct to have it defined, nevertheless.

**Comment by nija-at** [comment] 2020-03-27 17:09
@xerofun - thinking about this more, that's actually quite odd. 
Usually, when there is a missing resource dependency, the CF deployment will fail complaining that a resource specified was missing. It would be quite odd if CF deployment actually succeeded and the resource wasn't correctly configured.

I believe CF guarantees that when it *successfully* deploys that all resources are present and correctly configured according to the provided template.

I deployed the sample code that I pasted above (almost the same as yours) and everything looked correct -

```bash
⇒  aws lambda list-event-source-mappings --function-name integ-eventsource-dlqdeps-SqsFunction1FCDD803-38X0E1IV7N2S --query 'EventSourceMappings[].UUID'
[
    "76b03357-d406-40a1-9c84-106f6706c792"
]

⇒  aws lambda get-event-source-mapping --uuid 76b03357-d406-40a1-9c84-106f6706c792 --query 'DestinationConfig'
{
    "OnFailure": {
        "Destination": "arn:aws:sqs:eu-west-1:<redacted>:integ-eventsource-dlqdeps-sqsDLQ3C1253C0-1CYPZ7QNDEH9N"
    }
}
```

**Comment by xerofun** [comment] 2020-03-27 18:33
Really weird - I can fiddle with taking the dependency hack out of my project and see if it happens again if I remember

**Comment by skinny85** [comment] 2020-03-27 18:49
> Usually, when there is a missing resource dependency, the CF deployment will fail complaining that a resource specified was missing

I don't think CloudFormation does any sort of dependency checks. If a dependency that was supposed to be there is not, that means it's a race condition. Some deployments might succeed (if the order happens to be what is required), and others might fail (if the order is incorrect, and then some server-side operation fails because of that).

**Comment by nija-at** [comment] 2020-03-29 08:18
@skinny85 - To clarify, are you saying that it's possible for a CF deployment (specifically, stack create, not necessarily update) to succeed, even when not all resources specified by the template are created or configured per the template? 

I'm curious, can you state a situation that this can happen?

Now, let's apply this to what @xerofun has described in this issue.

In his case, the [`onFailure` property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-onfailure.html#cfn-lambda-eventsourcemapping-onfailure-destination) of `AWS::Lambda::EventSourceMapping` was not set to the SQS queue ARN on the event source mapping, while it was specified in the template. However, the CF deployment succeeded.

There are only 2 ways, AFAICT, this can occur -

1. CloudFormation, at the time of calling the [`CreateEventSourceMapping()` API](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-onfailure.html#cfn-lambda-eventsourcemapping-onfailure-destination), could not resolve the `Ref`, because the queue was not created yet or ready, and simply ignored this and called the API without this property.
  This seems quite unlikely. If a resource property is referenced, AFICT, CF consistently fails.

2. The correct API call was made to `CreateEventSourceMapping()` but the lambda backend could not find a ready SQS queue with the specified ARN, and simply ignored setting this up. 
  First, silently ignoring a property by an API is a bug and there's no evidence of this so far. Second, I suppose a race condition on the SQS read API may exist (eventual consistency) but feels quite obscure to have hit this.

Something I missed here?

**Comment by skinny85** [comment] 2020-03-30 17:08
> @skinny85 - To clarify, are you saying that it's possible for a CF deployment (specifically, stack create, not necessarily update) to succeed, even when not all resources specified by the template are created or configured per the template?

I believe it's not possible. I was replying to this statement:

> Usually, when there is a missing resource dependency, the CF deployment will fail complaining that a resource specified was missing.

A missing resource dependency might result in an error, or it might not, depending on what order the API calls happen during the CFN deployment (because it's a race condition).

**Comment by SomayaB** [comment] 2020-05-04 20:38
Closing this issue for now since there hasn't been a response in a while. Feel free to reopen.

**Closed by SomayaB** 2020-05-04 20:38 UTC
Labels: @aws-cdk/aws-lambda-event-sources, bug, closing-soon
