### ISSUE TITLE
Creating a Secret with KeyMaterial KeyPair value in secretStringTemplate

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#7676] opened 2020-04-29 14:12 UTC
### The Question

Hi !

Don't know if it's an issue but I'm creating a KeyPair with a CDK **CustomResource** & trying to put it in a Secret and I've a : 
_Failed to parse SecretStringTemplate as JSON_

Only for the **KeyMaterial**, wich is the Private Key like : 

> "KeyMaterial": "-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAoWVCG...."

No pb with the other values, they are correctly insert in the Secret; here the code : 
```
const KeyPair = new CustomResource.AwsCustomResource(...)

new secretsmanager.Secret(... , { ...
    generateSecretString: { ...
        secretStringTemplate: JSON.stringify({
          KeyMaterial: KeyPair.getResponseField('KeyMaterial'),
          KeyName: KeyPair.getResponseField('KeyName'),
          KeyPairId: KeyPair.getResponseField('KeyPairId'),
          KeyFingerprint: KeyPair.getResponseField('KeyFingerprint')
        }),
```

When I put (or not) the key in plaintext string in **KeyMaterial:** , it's working.

Any ideas ?

### Environment

  - **CDK CLI Version: CDK Version: 1.35.0 (build e0810c8)** 
  - **OS: all** 
  - **Language: TypeScript**

**Comment by skinny85** [comment] 2020-06-29 21:31
Hey @Cloudrage ,

can you show the CloudFormation template that you get when you `cdk synth` that code with:

```ts
          KeyName: KeyPair.getResponseField('KeyName'),
```

present?

Thanks,
Adam

**Comment by Cloudrage** [comment] 2020-07-02 10:00
Hi @skinny85 !

See the synth :
```
[...]
        SecretStringTemplate:
          Fn::Join:
            - ""
            - - '{"KeyMaterial":"'
              - Fn::GetAtt:
                  - KeyPairEcsHostIsB3C0B127
                  - KeyMaterial
              - '","KeyName":"'
              - Fn::GetAtt:
                  - KeyPairEcsHostIsB3C0B127
                  - KeyName
              - '","KeyPairId":"'
              - Fn::GetAtt:
                  - KeyPairEcsHostIsB3C0B127
                  - KeyPairId
              - '","KeyFingerprint":"'
              - Fn::GetAtt:
                  - KeyPairEcsHostIsB3C0B127
                  - KeyFingerprint
              - '"}'
[...]
```

**Comment by skinny85** [comment] 2020-07-02 16:57
Can you also show the JSON form? (You should find the template in the `cdk.out` directory)

**Comment by Cloudrage** [comment] 2020-07-03 09:30
```
[...]
          "SecretStringTemplate": {
            "Fn::Join": [
              "",
              [
                "{\"KeyMaterial\":\"",
                {
                  "Fn::GetAtt": [
                    "KeyPairEcsHostIsB3C0B127",
                    "KeyMaterial"
                  ]
                },
                "\",\"KeyName\":\"",
                {
                  "Fn::GetAtt": [
                    "KeyPairEcsHostIsB3C0B127",
                    "KeyName"
                  ]
                },
                "\",\"KeyPairId\":\"",
                {
                  "Fn::GetAtt": [
                    "KeyPairEcsHostIsB3C0B127",
                    "KeyPairId"
                  ]
                },
                "\",\"KeyFingerprint\":\"",
                {
                  "Fn::GetAtt": [
                    "KeyPairEcsHostIsB3C0B127",
                    "KeyFingerprint"
                  ]
                },
                "\"}"
              ]
            ]
          }
[...]
```

**Comment by njlynch** [comment] 2020-08-03 11:26
@Cloudrage  - Sorry for the delay in response here.

I was able to reproduce the issue on my end. The issue is that the output of the custom resource is referenced directly in the JSON template, and there isn't any good way on the CDK/CloudFormation side to escape the value. What worked for me, rather than changes on the CDK app end, was to escape the output of the custom resource. 

What worked for me was escaping the newlines in the private key:

```js
const privateKeyEscaped = privateKey.replace(/\n/g, '\\n');
```

Then I included that `privateKeyEscaped` value in the response of the custom resource. This allowed the secret to be created.

Can you give that a shot and see if it works for you?

**Comment by Cloudrage** [comment] 2020-08-04 16:01
Hello @njlynch and thank you for your reply.

But I'm not sure to understand exactly when you say `Then I included that privateKeyEscaped value in the response of the custom resource.`.

Actually, I'm creating, in order :
```
    const KeyPairEcsHostIs = new CustomResource.AwsCustomResource{...}

    const KeyPairEcsHostIsPrivateKeyEscaped = KeyPairEcsHostIs.getResponseField('KeyMaterial').replace(/\n/g, '\\n');
    
    const SecretsManagerKeyPairEcsHostIs = new secretsmanager.Secret(this, 'SecretsManagerKeyPairEcsHostIs', {
    ...
    secretStringTemplate: JSON.stringify({
          KeyMaterial: KeyPairEcsHostIsPrivateKeyEscaped,
          ...
```

But it's not what you're trying to do right ?
And it can't work that way anyway I'll have a : `Failed to parse SecretStringTemplate as JSON`

And don't forget that the PrivateKey musn't appear in the log of the CustomResource (Lambda).

**Comment by njlynch** [comment] 2020-08-04 16:24
What I was suggesting was to escape the private key _in the code of the custom resource_ itself. So this was a snippet of code from my Lambda CustomResource:

```js
    const { publicKey, privateKey } = generateKeyPairSync('rsa', {
        ...
    });
    const privateKeyEscaped = privateKey.replace(/\n/g, '\\n');
    ...
    responseData['KeyMaterial'] = privateKeyEscaped;
    return responseData;
```

In your above example, the KeyPairEscHostIs.getResponseField() returns a [Token](https://docs.aws.amazon.com/cdk/latest/guide/tokens.html), not the value itself, so it can't be manipulated or escaped within that context.

**Comment by Cloudrage** [comment] 2020-08-05 09:05
Indeed, but in that case I can't use **AwsCustomResource** but a **Provider** with a Lambda.
Or a **lambda.SingletonFunction** with a **cdk.CustomResource** for example.

I was trying a simplest way to do that, but seems not possible in your workaround : 
```
    const KeyPairEcsHostIs = new CustomResource.AwsCustomResource(this, 'KeyPairEcsHostIs', {
      onUpdate: {
        service: 'EC2',
        action: 'createKeyPair',
        parameters: {
          KeyName: EcsHostKeyPairIsName
        },
        physicalResourceId: CustomResource.PhysicalResourceId.fromResponse('KeyName') // Use the token returned by the call as physical id
      },
      onDelete: {
        service: 'EC2',
        action: 'deleteKeyPair',
        parameters: {
          KeyName: EcsHostKeyPairIsName
        }
      },
      policy: CustomResource.AwsCustomResourcePolicy.fromSdkCalls({resources: CustomResource.AwsCustomResourcePolicy.ANY_RESOURCE}),
      logRetention: logs.RetentionDays.ONE_DAY
    });
```

I have to write the Lambda in that case (or maybe you can provide your code to go faster and help other people if needed).

Thanks again !

**Comment by njlynch** [comment] 2020-08-10 09:30
This is the Lambda function I used; it's very simple but should be easily extended.

```js
exports.handler = function(event) {
    if (event.RequestType == "Delete") {
        return {
            PhysicalResourceId: event.PhysicalResourceId,
            Reason: 'Deleting (no-op)',
        };
    }

    var responseData = {};

    const { generateKeyPairSync } = require('crypto');
    const { publicKey, privateKey } = generateKeyPairSync('rsa', {
        modulusLength: 2048,
        publicKeyEncoding: {
          type: 'pkcs1',
          format: 'pem'
        },
        privateKeyEncoding: {
          type: 'pkcs1',
          format: 'pem',
        },
    });

    responseData['PublicKey'] = publicKey.replace(/\n/g, '\\n');
    responseData['PrivateKey'] = privateKey.replace(/\n/g, '\\n');
    return {
        Data: responseData,
    };
}
```

I used this in my stack like this:
```ts
export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const keyGenProvider = cdk.CustomResourceProvider.getOrCreate(this, 'KeyGenProvider', {
      codeDirectory: './lambda-pkg',
      runtime: cdk.CustomResourceProviderRuntime.NODEJS_12,
      timeout: cdk.Duration.seconds(10),
    });
    const keyPairResource = new cdk.CustomResource(this, 'KeyGen', { serviceToken: keyGenProvider });

    new sm.Secret(this, 'MyKeyPairSecret', {
      generateSecretString: {
        secretStringTemplate: JSON.stringify({
          KeyMaterial: keyPairResource.getAttString('PrivateKey'),
        }),
        generateStringKey: 'mySecret',
      },
    });
  }
}
```

I'm going to close this out for now, but feel free to re-open or comment back if you have any follow-ups.

**Closed by njlynch** 2020-08-10 09:30 UTC
Labels: @aws-cdk/aws-secretsmanager, guidance

**Comment by Cloudrage** [comment] 2020-08-13 11:58
Many thanks about that @njlynch :) 

But in my case, I have to create a Keypair, not generate private/public Keys.
So, I've updated the Lambda do be able to do that.

But !
With **cdk.CustomResourceProvider** we can't set environment variables and I want to give the _KeyName_ as an environment variable to the Lambda.
I've opened a feature request about that : #9668
A **logRetention** prop will be interesting too.

So, until it's not possible, I've created a **SingletonFunction**, example : 
```
exports.handler = function(event) {
    const AWS = require("aws-sdk");
    var ec2 = new AWS.EC2();
    let KeyPairName = process.env.KeyName;
    var responseData = {};
    var params = {
        KeyName: KeyPairName
       };
       ec2.createKeyPair(params, function(err, data) {
         if (err) console.log(err, err.stack); // an error occurred
        responseData['PrivateKey'] = data.KeyMaterial.replace(/\n/g, '\\n');
        responseData['KeyName'] = data.KeyName;
        responseData['KeyPairId'] = data.KeyPairId;
        responseData['KeyFingerprint'] = data.KeyFingerprint;
        return {
            Data: responseData,
        };
       });
}
```

**Comment by Cloudrage** [comment] 2020-08-14 12:37
It seems that I've done somthing wrong between Lambda<>CDK code because when updating the Stack I have an error when trying to retrieve attributes :
```
2:27:48 PM | UPDATE_FAILED        | AWS::SecretsManager::Secret               | SecretsManagerKeyPairEcsHostIs
CustomResource attribute error: Vendor response doesn't contain PrivateKey key in object arn:aws:cloudformation:eu-west-1:265564018801:stack/iris-dev-frontend/537b7440-8975-11ea-bb4d-027d0216890a|CustomLambdaSingletonKeypairProviderEcsHostIs|c3b419a8-2a78-4681-aa8d-975e6da5a2cf in S3 bucket cloudformation-custom-resource-storage-euwest1
2:27:48 PM | UPDATE_FAILED        | AWS::AutoScaling::LaunchConfiguration     | AutoScalingGroupEcsHostIs/LaunchConfig
CustomResource attribute error: Vendor response doesn't contain KeyName key in object arn:aws:cloudformation:eu-west-1:265564018801:stack/iris-dev-frontend/537b7440-8975-11ea-bb4d-027d0216890a|CustomLambdaSingletonKeypairProviderEcsHostIs|c3b419a8-2a78-4681-aa8d-975e6da5a2cf in S3 bucket cloudformation-custom-resource-storage-euwest1
```
In my SecretsManager Construct : 
```
secretStringTemplate: JSON.stringify({
          KeyMaterial: CustomLambdaSingletonKeypairProviderEcsHostIs.getAttString('PrivateKey'),
          KeyName: CustomLambdaSingletonKeypairProviderEcsHostIs.getAttString('KeyName'),
          KeyPairId: CustomLambdaSingletonKeypairProviderEcsHostIs.getAttString('KeyPairId'),
          KeyFingerprint: CustomLambdaSingletonKeypairProviderEcsHostIs.getAttString('KeyFingerprint')
```
AutoScaling : 
`keyName: CustomLambdaSingletonKeypairProviderEcsHostIs.getAttString('KeyName'),`

CustomResource  : 
```
    const CustomProviderSingletonKeypairProviderEcsHostIs = new CustomResource.Provider(this, 'CustomProviderSingletonKeypairProviderEcsHostIs', {
      onEventHandler: LambdaSingletonKeypairProviderEcsHostIs,
      logRetention: logs.RetentionDays.ONE_DAY   // default is INFINITE
    });
    const CustomLambdaSingletonKeypairProviderEcsHostIs = new cdk.CustomResource(this, 'CustomLambdaSingletonKeypairProviderEcsHostIs', {
      resourceType: 'Custom::KeypairProviderEcsHostIs',
      serviceToken: CustomProviderSingletonKeypairProviderEcsHostIs.serviceToken
    });
```

My Lambda Function is creating/deleting the Key successfully and values are returned in **Data** as expected (responseData).

Any ideas ?

**Comment by njlynch** [comment] 2020-08-14 14:30
I realize I had a typo in my above Lambda function; I suspect it caused the issue for you. Instead of:

```js
exports.handler = function(event) {
```

Try:

```js
exports.handler = async function(event) {
```

That will (hopefully) solve the issue.

**Comment by Cloudrage** [comment] 2020-08-14 14:43
Unfortunately no, I've tested that too without success :(

The Full Lambda : 
```
exports.handler = async function(event) {
    const id = event.PhysicalResourceId;
    const AWS = require("aws-sdk");
    var ec2 = new AWS.EC2();
    let KeyPairName = process.env.KeyName;
    var responseData = {};
    var params = {
        KeyName: KeyPairName
    };

    switch (event.RequestType) {
        case "Create":
            ec2.createKeyPair(params, function(err, data) {
                if (err) console.log(err, err.stack); // an error occurred
                else
                responseData['PrivateKey'] = data.KeyMaterial.replace(/\n/g, '\\n');
                responseData['KeyName'] = data.KeyName;
                responseData['KeyPairId'] = data.KeyPairId;
                responseData['KeyFingerprint'] = data.KeyFingerprint;
                return {
                    PhysicalResourceId: id,
                    Data: responseData
                };
            });
            respond('SUCCESS','Create OK');

        case "Delete":
            ec2.deleteKeyPair(params, function(err, data) {
                if (err) console.log(err, err.stack); // an error occurred
                else
                return {
                    PhysicalResourceId: id,
                };
            });
            respond('SUCCESS','Delete OK');
        }

    function respond(responseStatus, reason, physicalResourceId) {
        const responseBody = JSON.stringify({
            Status: responseStatus,
            Reason: reason,
            PhysicalResourceId: physicalResourceId,
            StackId: event.StackId,
            RequestId: event.RequestId,
            LogicalResourceId: event.LogicalResourceId,
        });
        console.log('Responding', responseBody);
    }
}

```

**Comment by njlynch** [comment] 2020-08-14 15:15
Ah, now I see. You're calling the "callback" versions of the SDK functions, which aren't guaranteed to return prior to you returning from the function. Try this:

```js
        case "Create":
            const keyPair = await ec2.createKeyPair(params).promise();
            responseData['PrivateKey'] = keyPair.KeyMaterial.replace(/\n/g, '\\n');
            responseData['KeyName'] = keyPair.KeyName;
            responseData['KeyPairId'] = keyPair.KeyPairId;
            responseData['KeyFingerprint'] = keyPair.KeyFingerprint;
            respond('SUCCESS','Create OK');
            return {
                PhysicalResourceId: id,
                Data: responseData
            };
```

Also, make sure your Lambda role has appropriate IAM policies to allow it to create key pairs.

**Comment by Cloudrage** [comment] 2020-08-14 15:46
Perfect, it's working now :)
Thanks again for your help @njlynch !

I've created a similar mecanism few years ago with Sceptre but in Python; now using CDK with TypeScript, let's say it's quite different ^^
I was at 2 fingers to reuse the Python code ;)

**Comment by markcarroll** [comment] 2021-01-14 23:48
@njlynch I am trying to use your example lambda that you posted on Aug 10 above.  The lambda fires and generates a key and I can send it to secrets manager, so I am sure it is working somewhat. However I get an error every time when trying to use that same key to create a CloudFront public key:

```ts
    const cfPublicKey = new cloudfront.CfnPublicKey(this, "cfPublicKey", {
      publicKeyConfig: {
        name: "CloudFrontSigningKey",
        encodedKey: keyPairResource.getAttString("PublicKey"),
        callerReference: Date.now().toString(),
      },
    });
```

I just error: `Invalid request provided: AWS::CloudFront::PublicKey`

The JSON generated is:
```json
    "cfPublicKey": {
      "Type": "AWS::CloudFront::PublicKey",
      "Properties": {
        "PublicKeyConfig": {
          "CallerReference": "1610667927610",
          "EncodedKey": {
            "Fn::GetAtt": [
              "KeyGen",
              "PublicKey"
            ]
          },
          "Name": "CloudFrontSigningKey"
        }
      },
      "Metadata": {
        "aws:cdk:path": "Dev/SharedServices/cfPublicKey"
      }
    },
```

What am I doing wrong?
