### ISSUE TITLE
ssm ssm.StringParameter.from_string_parameter_name fails 'Resource' object has no attribute 'string_value'

### ISSUE THREAD

**Issue by tarunaroraonline** [aws/aws-cdk#4985] opened 2019-11-12 16:06 UTC
When using ssm to retrieve the value by string parameter name it fails.

``` python

param = ssm.StringParameter.from_string_parameter_name(
              self,
              "ssmParam",
               string_parameter_name="parameterName",
             )
```

### Error Log

'Resource' object has no attribute 'string_value'
{'__jsii_ref__': ObjRef(ref='@aws-cdk/core.Resource@10522', interfaces=['@aws-cdk/aws-ssm.IStringParameter'])}

### Environment

  - **CLI Version      :1.15.0, 1.16.0, 1.16.2
  - **Framework Version: **
  - **OS               : Ubuntu 18.2
  - **Language         :Python

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment] 2019-11-12 19:38
Seems to be a duplicate of #4982

**Comment by eladb** [comment] 2019-11-12 20:05
Closing as duplicate

**Closed by eladb** 2019-11-12 20:05 UTC
Labels: bug, duplicate, language/python, p0, package/ssm, status/needs-triage
