### ISSUE TITLE
(@aws-cdk/aws-apigatewayv2-alpha): (OpenApi Definition)

### ISSUE THREAD

**Issue by EliasMehr** [aws/aws-cdk#20984] opened 2022-07-04 12:09 UTC
### Describe the feature

Add Open API Definition for alpha module

### Use Case

Right now we are using the @aws-cdk/aws-apigatewayv2-alpha module for using oauth through auth0. But i saw recently that the open api definition isn't available to the L2/L3 construct. We would really not wanna use L1 construct. Is this something that can be added to the package? 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

latest

### Environment details (OS name and version, etc.)

Windows 11 PRO

**Comment by peterwoodworth** [comment] 2022-07-28 23:13
Thanks for the request!

This seems to be a duplicate of https://github.com/aws/aws-cdk/issues/19190. Good news is that there's a PR in progress right now!

**Closed** 2022-08-05 14:48 UTC
Labels: duplicate, feature-request, @aws-cdk/aws-apigatewayv2
