### ISSUE TITLE
Race Issue when deploying multiple stacks in parallel

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#5820] opened 2020-01-15 20:46 UTC
I have a loop,
```
for stack in Stack1 Stack2 Stack3 
do
  cdk deploy $stack &
end
```

As written, the first one will sometimes die with this error:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new CloudAssembly (/Users/sblackstone/code/lotto/stacks/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.js:25:31)
    at CloudAssemblyBuilder.buildAssembly (/Users/sblackstone/code/lotto/stacks/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.js:193:16)
    at Function.synth (/Users/sblackstone/code/lotto/stacks/node_modules/@aws-cdk/core/lib/construct.js:72:24)
    at App.synth (/Users/sblackstone/code/lotto/stacks/node_modules/@aws-cdk/core/lib/app.js:71:52)
    at process.<anonymous> (/Users/sblackstone/code/lotto/stacks/node_modules/@aws-cdk/core/lib/app.js:45:51)
    at Object.onceWrapper (events.js:291:20)
    at process.emit (events.js:203:13)
Subprocess exited with error 1
```

Adding a `sleep 3` in that loop fixes the problem...

Thanks

### Environment

  - **CLI Version     1.20.0 (build 021c521) :**
  - **OS   OSX               :**
  - **Language Javascript         :**

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment] 2020-01-16 22:41
@sblackstone - is this a script you're using to deploy your cdk stacks?

I'm trying to repro, but maybe my stacks were too simple (1-2 resources each).

1. had they already been synthesized ahead of the deploy or is the deploy also taking care of that?
2. are they making any context provider service calls (lookup from vpc, etc)

**Comment by sblackstone** [comment] 2020-01-16 22:44
Ya, I was looking up Keys by ARN.

Oddly, I just went to look at my code again and apparently the sleep had been removed due to a git reset the other day, haven't noticed the problem since.  But it was very re-producible at one point...  

I'm afraid I don't have much more to add on this..

**Comment by shivlaks** [comment] 2020-01-21 04:49
@sblackstone thanks for confirming - I tried to set up a few more involved stacks, nested stacks, multiple context lookups and still haven't been able to reproduce this one.

Out of curiosity, what region were you trying to deploy in? Since IAM is global, I'm wondering if looking up a role or something was especially latent when you were attempting to deploy.

**Comment by sblackstone** [comment] 2020-01-21 13:22
Deploying to us-east-1.

The services I'm using are lambdas, buckets, ssm parameters, kms, iam, lambda events, and sqs.

I have 4 stacks defined in in my app file and they aren't using any shared resources.

This issue cropped up again for a few mins a couple days ago, but then went away - as I'm actively developing a product, i wasn't fully paying attention to what changed or the state of the stacks when it occurred.

Stephen

**Comment by richardhboyd** [comment] 2020-02-02 18:56
maybe I am missing something, but why not use `cdk deploy Stack*` and let CDK handle ordering/deploying them?

**Comment by shivlaks** [comment] 2020-05-16 14:20
resolving this as `cdk deploy '*'` will give you what you need as @richardhboyd mentioned.
please reopen if you're still running into issues here.

**Closed by shivlaks** 2020-05-16 14:20 UTC
Labels: bug, p2
