### ISSUE TITLE
TableV2: TableV2 Replica provides the incorrect TableStreamARN in CDK

### ISSUE THREAD

**Issue by kevinhuynh23** [aws/aws-cdk#31335] opened 2024-09-05 23:44 UTC
### Describe the bug

When using Global Tables with TableV2 in CDK, the replica tables aren't referenced properly with an output export like the primary Global Table Stream ARN. For example, we create a global table in us-east-1 with replicas in us-west-2 and eu-west-1.

When getting the Stream ARN for the primary global table, CDK will create reference the exact Stream ARN i.e. `arn:aws:dynamodb:us-east-1:123456789012:table/IndraMembershipDetails-Beta/stream/<timestamp>`. Where as in the replica tables when using `globalTable.replica("us-west-2")`, it'll get the correct replica table, but the Stream ARN provided is not the exact Stream ARN, but something like this instead: `arn:aws:dynamodb:us-west-2:123456789012:table/IndraMembershipDetails-Beta/stream/*`.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I would expect to use `globalTable.replica("us-west-2")` and retrieve the replica Stream ARN to as `arn:aws:dynamodb:us-west-2:123456789012:table/IndraMembershipDetails-Beta/stream/<timestamp>`.

### Current Behavior

When getting the Stream ARN for the primary global table, CDK will create reference the exact Stream ARN i.e. `arn:aws:dynamodb:us-east-1:123456789012:table/IndraMembershipDetails-Beta/stream/<timestamp>`. Where as in the replica tables when using `globalTable.replica("us-west-2")`, it'll get the correct replica table, but the Stream ARN provided is not the exact Stream ARN, but something like this instead: `arn:aws:dynamodb:us-west-2:123456789012:table/IndraMembershipDetails-Beta/stream/*`.

### Reproduction Steps

1. Create a Global Table configuration using TableV2
2. Configure replicas to be in two regions i.e. us-west-2 and eu-west-1
3. Get the replica in a region i.e. `globalTable.replica("us-west-2")`
4. Get the Stream ARN from the replica table

### CDK CLI Version

2.87.0

### Node.js Version

v20.17.0

### OS

Mac OS Sonoma 14.6.1

### Language

TypeScript

**Comment by khushail** [comment] 2024-09-06 22:34
Hi @kevinhuynh23 , Thanks for reaching out.

you seem to be using very old version of CDK. Could you please try running on the [latest CDK 2.156](https://docs.aws.amazon.com/cdk/api/v2/). Meanwhile I will also try to reproduce this on my end.

**Comment by kevinhuynh23** [comment] 2024-09-07 15:51
Hi @khushail, thanks for looking to this! We are stuck on CDK 2.87.0 due to some of our dependencies. We can look into upgrading to the latest version if there's a fix for it in the later versions!

Thanks!

**Comment by kevinhuynh23** [comment] 2024-09-07 16:31
Hi @khushail, I had sometime to work around the dependency and I tried testing the same thing on 2.155.0 and seeing the same result!

**Comment by khushail** [comment] 2024-09-16 22:34
Hi @kevinhuynh23 , thanks for replying back with your updates.
I tried to repro the situation with the latest CDK 2.158.0. Sharing my observations -
Code snippet -
```ts
//create  a global table with replica in other regions
    const globalTable = new cdk.aws_dynamodb.TableV2(this, 'MyTable', {
      tableName: 'MyTable',
      partitionKey: { name: 'id', type: cdk.aws_dynamodb.AttributeType.STRING },
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    //globaltable stream arn
    new cdk.CfnOutput(this, 'GlobalTableStreamArn', {
      value: globalTable.tableStreamArn!,
    });

    //add replicas to the table
    globalTable.addReplica({ region: 'us-west-1', deletionProtection: true });

    //get the streamarn for the replicat table from region us-west-1

    new cdk.CfnOutput(this, 'ReplicaTableArn', {
      value: globalTable.replica('us-west-1').tableStreamArn!,
    });
```

Here is the output  printed with incomplete arn -

<img width="1192" alt="Screenshot 2024-09-16 at 3 30 21 PM" src="https://github.com/user-attachments/assets/fcdb3123-f2ea-4d4b-be63-c2eadc1eb251">



As seen in the cdk code, this replica table is lazily created. 

https://github.com/aws/aws-cdk/blob/4b8714d7b499362f0b77ad9a615479227e339078/packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts#L545

I am still figuring out the root cause, will share updates soon. Thanks for having patience

**Comment by khushail** [comment] 2024-09-19 20:36
@kevinhuynh23 , here is my observation from the code which states the stream as `<steam>/*` -

This method adds replica in another region  with the stream arn ending with `*`-

https://github.com/aws/aws-cdk/blob/4b8714d7b499362f0b77ad9a615479227e339078/packages/aws-cdk-lib/aws-dynamodb/lib/table-v2.ts#L597

Linked PR - https://github.com/aws/aws-cdk/commit/e52acd8d449e491a60f5c78dbf7f00e333eb442c

RFC -https://github.com/aws/aws-cdk-rfcs/blob/main/text/0510-dynamodb-global-table.md
As per RFC, the reason for mentioning the stream with `*` as -
<img width="992" alt="Screenshot 2024-09-19 at 1 34 49 PM" src="https://github.com/user-attachments/assets/daca24e9-b98c-40de-bbb1-71b118aa36fb">

So It seems to be intentional the way replica arn is created.

Hope that would be helpful.
Please feel free to reach out in case of doubts. Thanks

**Comment by kevinhuynh23** [comment] 2024-09-19 21:26
@khushail Thanks for looking into this issue! 

The reason the above comment mentions an addition of a potential lookup function to determine the stream arn, are there any plans to implement this?

Also, are we not able to have the Replica Stream ARN be exported as a CloudFormation export value after the creation completes? Or does CFN have no ability to reference the value?

Thanks for the help!

**Comment by khushail** [comment] 2024-09-20 17:55
@kevinhuynh23 , I highly doubt if the stream ARN could be exported as value but will definitely keep looking and share here if I find anything.

Also, I did not find any such implementation plan for the mentioned function. However you could file a feature request with CDK, and get community upvotes.

**Comment by khushail** [comment] 2024-09-20 17:58
@kevinhuynh23 , I would be closing this issue for now.

If you need any other help/guidance, please feel free to re-open.

Thanks !

**Closed** 2024-09-20 17:58 UTC
Labels: p2, guidance, @aws-cdk/aws-dynamodb
