### ISSUE TITLE
this.node.addError does not cause `cdk diff` to fail

### ISSUE THREAD

**Issue by mipearson** [aws/aws-cdk#4700] opened 2019-10-26 23:20 UTC
## :question: General Issue

Not sure if this is a bug or a feature.

`cdk diff <stackname>` will succeed on a stack with errors, even though a `cdk deploy` or `cdk synth` will fail. The `cdk diff` does not show any indication of an error.

If this is intention it might be worth signposting it somehow.

### Environment

  - **CDK CLI Version:** `Unknown command: version` (but it's `1.14.0 (build 261a1bf)` if I run `cdk --version` instead)
  - **OS:** OSX Mojave
  - **Language:** Typescript, but suspect all as it's within the CDK CLI

**Comment by nmussy** [comment] 2019-10-27 10:28
The errors will be thrown in the `processMetadata` method:

https://github.com/aws/aws-cdk/blob/ba38b76b1e1103c9eb7eee683239a86344e04e6f/packages/aws-cdk/lib/api/cxapp/stacks.ts#L315-L317

Which is only called for the `synth` and `deploy` commands, like you've noticed:

https://github.com/aws/aws-cdk/blob/ba38b76b1e1103c9eb7eee683239a86344e04e6f/packages/aws-cdk/lib/cdk-toolkit.ts#L86

https://github.com/aws/aws-cdk/blob/4f765b2657ceae4a18c6cc62fe99393a03221a87/packages/aws-cdk/bin/cdk.ts#L297

Even if it was intended for `diff` not to throw, not seeing any warning or error until deployment is a little weird.

**Comment by shivlaks** [comment] 2019-12-11 21:38
fixed by #5284

**Closed by shivlaks** 2019-12-11 21:38 UTC
Labels: bug, good first issue, p2, package/tools, status/in-progress
