### ISSUE TITLE
Make cdk diff CI/CD friendly

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#5392] opened 2019-12-12 13:55 UTC
Related to: https://github.com/aws/aws-cdk/issues/1440

### Use Case

I want to run cdk diff in my CI/CD pipeline and if there is a change in the stack, I want the pipeline to succeed. If there is an error in trying to generate the diff, I want the pipeline to fail. (exit code > 0)

### Proposed Solution

Leave the cdk diff behaviour as is, but add a flag that can change the exit code behaviour as mentioned in the use case.

### Other

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by shivlaks** [comment] 2019-12-12 19:05
hey @abelmokadem - Is this a duplicate of #4721 ?

**Comment by abelmokadem** [comment] 2019-12-13 06:22
@shivlaks oops, didn't see this PR yet. Looking forward to seeing this get released :)

**Closed** 2019-12-13 06:22 UTC
Labels: feature-request, status/needs-triage
