### ISSUE TITLE
[api-gateway] Support body parameter in L2 construct

### ISSUE THREAD

**Issue by patapurv** [aws/aws-cdk#11373] opened 2020-11-09 15:45 UTC
Support adding openAPI schema to the HttpApi construct.

### Use Case

I want to use open API schema to generate AWS http API. The L2 construct does not support body in constructor or in a method to add open API schema. 

### Proposed Solution

Currently I am using escape hatches to add body parameter but ideally there should be a param for body. eg:

```
        const httpAPI = new HttpApi(this, props.serviceName, {});
        const httpApiResource = httpAPI.node.defaultChild as apigatewayv2.CfnApi;
        httpApiResource.addPropertyOverride("body", swaggerDef);

        httpAPI.addStage(props.stage, {
            autoDeploy: true,
            stageName: props.stage
        });

```

**Comment by peterwoodworth** [comment] 2022-07-28 23:14
Thanks for the request, I'm going to close as a duplicate of https://github.com/aws/aws-cdk/issues/19190 which has a PR in progress 🙂

**Closed by peterwoodworth** 2022-07-28 23:14 UTC
Labels: p2, feature-request, effort/medium, @aws-cdk/aws-apigatewayv2
