### ISSUE TITLE
aws-chatbot: make ISlackChannelConfiguration define addNotificationTopic(ITopic)

### ISSUE THREAD

**Issue by MayconFrr** [aws/aws-cdk#26391] opened 2023-07-17 13:59 UTC
### Describe the feature

Right now you can only add topics if you create the chatbot slack configuration in the stack. You can't add topics to existing chatbot resources because SlackChannelConfiguration.fromSlackChannelConfigurationArn(...) returns an ISlackChannelConfiguration, which doesn't define the method to do so

### Use Case

As a CDK developer
I want to add a notification topic to an existing chatbot slack resource through CDK
So that I don't have to manually add it using the AWS Console

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.87.0

### Environment details (OS name and version, etc.)

Windows 10 Home Single Language, Version 22H2

**Comment by khushail** [comment] 2023-07-17 18:43
Hi @MayconFrr , thanks for reaching out with this feature request. It might be a good feature to add to [ISlackChannelConfiguration](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_chatbot.ISlackChannelConfiguration.html). However if you would like to contribute, you could follow this [contributing guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on).

**Comment by khushail** [comment] 2023-07-17 18:53
Thanks @MayconFrr  for submitting this feature request. I am marking this as P2 but you are welcome to submit a PR. Here is the [contribution guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-1-find-something-to-work-on) to get started.

**Comment by peterwoodworth** [comment] 2023-07-17 19:49
Closing as duplicate of https://github.com/aws/aws-cdk/issues/21171

**Closed by peterwoodworth** 2023-07-17 19:49 UTC
Labels: duplicate, p2, feature-request, effort/medium, @aws-cdk/aws-chatbot
