### ISSUE TITLE
aws-codepipeline-actions: change default branch name to main in GithubSourceAction

### ISSUE THREAD

**Issue by tsahiduek** [aws/aws-cdk#15341] opened 2021-06-29 10:43 UTC
GitHub had changed its instructions of bootstrapping a new image to use the default branch name as `main`

Following guides (such as https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/), result in error since the default branch in CDK is `master`

### Proposed Solution

Change the default from `master` to `main` in https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-codepipeline-actions/lib/github/source-action.ts#L61

* [X] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

**Comment by skinny85** [comment] 2021-06-29 18:12
Hey @tsahiduek ,

thanks for opening the issue. It's a duplicate of https://github.com/aws/aws-cdk/issues/13335. Let's move the conversation there.

Thanks,
Adam

**Closed by skinny85** 2021-06-29 18:12 UTC
Labels: @aws-cdk/aws-codepipeline-actions, feature-request, needs-triage
