### ISSUE TITLE
cli-lib-alpha: bootstrap with bad argument name for trust and  trustForLookup

### ISSUE THREAD

**Issue by juanenriqueescobar** [aws/aws-cdk#30404] opened 2024-05-31 16:09 UTC
### Describe the bug

`trust` and `trustForLookup` options are overwriting `qualifier`, so it's impossible to bootstrap a new account.

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cli-lib-alpha/lib/cli.ts#L187C1-L190

### Expected Behavior

bootstrap a new account with custom options using `cli-lib-alpha`

### Current Behavior

qualifier is defined as array and bootstrap fail with: `failed bootstrapping: InvalidParameterType: Expected params.Parameters[6].ParameterValue to be a string`

### Reproduction Steps

```
 await cli.bootstrap({
    trust: '00000000000',
    trustForLookup: '11111111111111',
    qualifier: 'hnb659fds',
 })
```

trace show this:
```
"Parameters": [
        { "ParameterKey": "TrustedAccounts", "ParameterValue": "000000000," },
        { "ParameterKey": "TrustedAccountsForLookup", "ParameterValue": "" },
        {
            "ParameterKey": "CloudFormationExecutionPolicies",
            "ParameterValue": "arn:aws:iam::aws:policy/AdministratorAccess"
        },
        { "ParameterKey": "FileAssetsBucketName", "UsePreviousValue": true },
        { "ParameterKey": "FileAssetsBucketKmsKeyId", "UsePreviousValue": true },
        { "ParameterKey": "ContainerAssetsRepositoryName", "UsePreviousValue": true },
        { "ParameterKey": "Qualifier", "ParameterValue": ["hnb659fds", "0000000000000", "111111111111111"] },
        { "ParameterKey": "PublicAccessBlockConfiguration", "ParameterValue": "true" },
        { "ParameterKey": "InputPermissionsBoundary", "UsePreviousValue": true },
        { "ParameterKey": "UseExamplePermissionsBoundary", "UsePreviousValue": true },
        { "ParameterKey": "BootstrapVariant", "UsePreviousValue": true }
    ],
```

problem is in this line:
```
{ "ParameterKey": "Qualifier", "ParameterValue": ["hnb659fds", "0000000000000", "111111111111111"] },
```

### Possible Solution

fix parameter names for 

trust
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cli-lib-alpha/lib/cli.ts#L188

and trustForLookup
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/cli-lib-alpha/lib/cli.ts#L189

### CDK CLI Version

2.143.0

### Node.js Version

any

### OS

any

### Language

TypeScript

**Comment by khushail** [comment] 2024-07-16 23:48
Hi @juanenriqueescobar , thanks for reporting this. I am not able to repro the issue with the code as I am not much familar with cli-lib-alpha library here. sharing the code which I tried-

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as cli from '@aws-cdk/cli-lib-alpha';

export class ClialphaIssueStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const ClialphaIssueStack = cli.AwsCdkCli.fromCdkAppDirectory("/Users/khushail/clialphaIssue");

     ClialphaIssueStack.bootstrap
    ({
      trust: '00000000000',
      trustForLookup: '11111111111111',
      qualifier: 'hnb659fds',
    });
  
  }
}
```

after running `cdk synth --output "khushail/alialphaissue/cdk-app"`
getting this error --

```Error: Another CLI (PID=86992) is currently synthing to cdk.out. Invoke the CLI in sequence, or use '--output' to synth into different directories.```

**Comment by khushail** [comment] 2024-07-19 00:39
@juanenriqueescobar , although I see the qualifier in the code being overwritten, could you share some instructions to repro this?

**Comment by juanenriqueescobar** [comment] 2024-07-22 15:48
@khushail Hi!

I try to bootstrap my account, but get the error that I reported.

``` typescript
const cli = AwsCdkCli.fromCdkAppDirectory()
try {
    await cli.bootstrap({
        trust: '000000000000',
        trustForLookup: '000000000000',
    })
} catch (e) {
    process.exit(1)
}
```

**Comment by juanenriqueescobar** [comment] 2024-07-22 15:55
the `--qualifier` param is almost a constant, It's used to create the bucket, roles, ecr repositories, etc, I am not trying to change it, but when I try to bootstrap the account, the `cli-lib-alpha` try to change it.

**Comment by khushail** [comment] 2024-07-22 22:04
@juanenriqueescobar I agree with your point in saying that `qualifier` is being overwritten. The issue is being marked as P2 which means it won't be immediately worked upon by the team but would need sometime. However if you would like to fix the issue and submit a PR, please feel free to do so. Thanks!

**Closed** 2024-08-21 16:20 UTC
Labels: bug, p2, package/tools, effort/small, cli
