### ISSUE TITLE
C2 Reverse Zone/Subnet Naming 

### ISSUE THREAD

**Issue by robmoggach** [aws/aws-cdk#7032] opened 2020-03-26 22:23 UTC
Generated Subnet,Routing Tables etc. have somewhat counter-intuitive naming schemes for my tastes.

Given:

```yaml
VPC:
  - Name: Mgmt
    CIDR: 10.0.0.0/16
    AvailabilityZones:
    - Name: Zone1
      AvailabilityZone: us-east-2a
    - Name: Zone2
      AvailabilityZone: us-east-2b
  Subnets:
    - Name: PrivateSubnet1
      CIDR: 10.0.0.0/21
    - Name: PrivateSubnet2
      CIDR: 10.0.8.0/21
```

Instead of:

```
MgmtPrivateSubnet11RoutingTable
```

I would prefer:

```
MgmtZone1PrivateSubnet1RoutingTable
```

Some of it I can get define adequately programmatically but more automated methods give the odd names that aren't at once clear.

**Comment by rix0rrr** [comment] 2020-04-16 10:01
Not really something we can do anything about in the current state of things. You can rename logical IDs, or try to not care about the logical IDs.

Closing as a duplicate of https://github.com/aws/aws-cdk/issues/5927

**Closed by rix0rrr** 2020-04-16 10:01 UTC
Labels: feature-request, needs-triage, package/ec2
