### ISSUE TITLE
Make it easier to create a RecordTarget

### ISSUE THREAD

**Issue by mariusGundersen** [aws/aws-cdk#5357] opened 2019-12-10 11:10 UTC
Currently there are some static methods for creating `RecordTarget`, for example `fromAlias()`, `fromIpAddress()` and `fromValues()`, but there is no simple way to create a `RecordTarget` with just the `dnsName` and `hostedZoneId` set. 

### Use Case

I want to create an ARecord that points to an existing CloudFront distribution. Unfortunately this isn't really possible yet, unless i create the CloudFront distribution in the same stack. The workaround I currently have is this:

```ts
addCloudFrontRecord(zone: HostedZone, recordName: string, domainNameAliasTarget: string, ttl = DEFAULT_DURATION) {
  const target = RecordTarget.fromAlias({
    bind() {
      return {
        dnsName: domainNameAliasTarget,
        hostedZoneId: CLOUD_FRONT_ZONE
      }
    }
  });

  return new ARecord(zone.stack, `a-record-${recordName}`, {
    zone,
    recordName,
    target,
    ttl
  });
}
```

### Proposed Solution

It would be great to have a method like `RecordTarget.fromAlias({dnsName, hostedZoneId})`, since that is the only thing really needed to create the alias. 

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment] 2020-04-13 18:56
This is actually a duplicate of https://github.com/aws/aws-cdk/issues/6805 and will be resolved with https://github.com/aws/aws-cdk/issues/5607.

**Closed** 2020-04-13 20:40 UTC
Labels: effort/medium, feature-request, package/cloudfront, package/route53
