### ISSUE TITLE
[Python] Module README's in PyPi

### ISSUE THREAD

**Issue by jfuss** [aws/aws-cdk#2131] opened 2019-04-01 14:24 UTC
When initially trying to get started with CDK for Python, I went to CDK's [PyPi page](https://pypi.org/project/aws-cdk.cdk/) to read the Project Description. My hope was to get some basic understand and some python code snippets but instead got JavaScript. As CDK expands, it is important to give each language their own flavor of the README/Project Description. This will help customers that are already familiar with the language a default place to look for content. 

Something else to consider with this:
For Python at least, there are links for the Homepage and Source. For CDK, these link to the projects main github repo. Instead, I suggest updating these to be deep links to the modules (where the README/Project Description is). I got slightly disoriented when clicking the Source and not getting dropped into the modules themselves. Maybe this isn't a huge deal but is slightly inconsistent.

**Comment by eladb** [comment] 2019-04-03 07:30
We need to visit the README of the @aws-cdk/cdk module and make it a bit more presentable as an entry point or at least redirect explicitly to the main README/docs

**Comment by SomayaB** [comment] 2019-10-11 21:59
First part is a duplicate of #2758 (keeping the other one since there are more comments there).

Second part seems to be out of date now.

Closing this issue but feel free to reopen if your concerns haven't been addressed.

**Closed by SomayaB** 2019-10-11 21:59 UTC
Labels: docs/api-reference, feature-request, language/python, package/cdk-core
