### ISSUE TITLE
DnsValidatedCertificate is ignoring the region property given in props

### ISSUE THREAD

**Issue by m-mayank** [aws/aws-cdk#4824] opened 2019-11-02 13:23 UTC
My stack is created in **eu-west-1** region, however i am create a DnsValidatedCertificate specifically in **us-east-1** region. In CDK 1.15.0 version, it is giving the below error when i run cdk ls

_acmCertificate certficate must be in the us-east-1 region, got eu-west-1_

**The same is working in version <=1.14.0**

### Reproduction Steps

```
// Typescript code snippet for creating certificate in stack
const certificate = new acm.DnsValidatedCertificate(this, 'DomainCertificate', {
      domainName: this.domainName,
      hostedZone: this.hostedZone,
      region: 'us-east-1'
});

// Generated Resource in template json
    "DomainCertificateCertificateRequestorResourceAEE5562E": {
      "Type": "AWS::CloudFormation::CustomResource",
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "DomainCertificateCertificateRequestorFunction47AD3C81",
            "Arn"
          ]
        },
        "DomainName": "*****.*****.com",
        "HostedZoneId": "DUMMY",
        "Region": "us-east-1"
      },
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "WebStack/DomainCertificate/CertificateRequestorResource/Default"
      }
    }
```

### Error Log

On running cdk ls:
acmCertificate certficate must be in the us-east-1 region, got eu-west-1

### Environment

  - **CLI Version      :*1.15.0*
  - **Framework Version:*1.15.0*
  - **OS               :*Mac*
  - **Language         :*Typescript*

### Other

--- 

This is :bug: Bug Report

**Comment by nmussy** [comment] 2019-11-04 08:05
Duplicate of #4724

I've reverted the check, it should be out for the next release. Sorry about that

**Comment by m-mayank** [comment] 2019-11-06 03:40
@nmussy,  Many thanks.

**Comment by SomayaB** [comment] 2019-11-13 19:23
Closing since it's a duplicate.

**Closed by SomayaB** 2019-11-13 19:23 UTC
Labels: bug, duplicate, package/acm, status/in-progress
