### ISSUE TITLE
[aws-events] `cdk diff` shows difference, but `cdk deploy` tells no changes

### ISSUE THREAD

**Issue by civilizeddev** [aws/aws-cdk#10219] opened 2020-09-07 12:25 UTC
I'm not sure whether this issue is involved with `aws-events` or `cdk diff`.

### Reproduction Steps

I have deployed this resource:

```
import * as events from '@aws-cdk/aws-events'

new events.Rule(this, 'rule', {
  eventPattern: {
    detail: {
      type: ['대한민국'], // Any non-single byte characters
    },
  }
)
```

`cdk diff` always tells there is a difference even though it has been deployed.

```bash
$ cdk diff <stack>

Stack <stack>
Resources
[~] AWS::Events::Rule rule rule5EE78A73 
 └─ [~] EventPattern
     └─ [~] .detail:
         └─ [~] .type:
             └─ @@ -1,3 +1,3 @@
                [ ] [
                [-]   "????"
                [+]   "대한민국"
                [ ] ]
```

But when I tried to deploy again, it tells:

```bash
$ cdk deploy <stack>

<stack>
<stack>: deploying...
<stack>: creating CloudFormation changeset...

 ✅  <stack> (no changes)
```

### What did you expect to happen?

```bash
$ cdk diff <stack>

 ✅  <stack> (no changes)
```

### What actually happened?

```bash
$ cdk diff <stack>

Stack <stack>
Resources
[~] AWS::Events::Rule rule rule5EE78A73 
 └─ [~] EventPattern
     └─ [~] .detail:
         └─ [~] .type:
             └─ @@ -1,3 +1,3 @@
                [ ] [
                [-]   "????"
                [+]   "대한민국"
                [ ] ]
```

### Environment

  - **CLI Version      :** aws-cli/2.0.45 Python/3.8.5 Darwin/19.6.0 source/x86_6
  - **Framework Version:** aws-cdk 1.62.0
  - **Node.js Version:**  v14.9.0
  - **OS               :** macOS Catalina
  - **Language (Version):**  TypeScript 4.0.2

### Other

--- 

This is :bug: Bug Report

**Comment by shivlaks** [comment] 2020-09-24 07:24
@civilizeddev It could be a bug with `diff`, what happens if you try to `deploy` with `--force` - that should always deploy regardless of whether there's a change. Does the rendered template include your modified characters

Also, sanity check: these characters are valid in CloudFormation for an Events Rule right?

**Comment by civilizeddev** [comment] 2020-09-28 00:53
`EventPattern.detail` handles the user application's data. It can contain any type of data.

**Comment by shivlaks** [comment] 2020-10-22 23:34
@civilizeddev thanks for confirming that the input is valid / should be accepted, how did it go with `--force`?

**Comment by rtteal** [comment] 2020-11-28 01:43
I just ran into this issue following the "hello world" guide: https://docs.aws.amazon.com/cdk/latest/guide/hello_world.html. I created the stack and then updated the s3 bucket `removalPolicy: true`, but didn't change the `publicReadAccess`. `cdk diff` detected the change, but `cdk deploy` did not. `cdk deploy --force` also did not detect any changes. Updating `publicReadAccess: true` did allow the `cdk deploy` to detect the change and deploy.

**Comment by timasplin** [comment] 2020-12-03 12:12
I was facing the same issues on a different resource when trying to update the DeletionPolicy  - but I found this in the CloudFormation documentation: https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-get-template.html

> Important
You cannot update the CreationPolicy, DeletionPolicy or UpdatePolicy attribute by itself. You can update them only when you include changes that add, modify, or delete resources. For example, you can add or modify a metadata attribute of a resource.

**Comment by jdiegosierra** [comment] 2021-07-30 10:45
Same problem changing ONLY DeletionPolicy

**Comment by jpSimkins** [comment] 2022-04-05 18:10
I am experiencing issues where `deploy` is causing deletions that `diff` does not show... very scary on PROD

**Comment by honey-malviya** [comment] 2022-11-05 02:55
The problem is the encodings of the characters that you have `대한민국` these characters are not supported by cloudformation aparently and it shows the diff. How ever the services like cloutwatch supports it. which is why you see these  diff but nothing gets deployed. 

you can normalize these, which will fix the diff.

**Comment by honey-malviya** [comment] 2022-11-05 02:57
You will face same problem if you have characters like these `é, ì, ö, á, ä, ü, é` in your labels or names. can you normalize them to english equilavent which would fix the diff.

**Comment by peterwoodworth** [comment] 2023-06-09 00:51
Thanks all, closing in favor of #25309

**Closed by peterwoodworth** 2023-06-09 00:51 UTC
Labels: bug, p2, @aws-cdk/aws-events, effort/medium
