### ISSUE TITLE
[aws-eks]  `ec2:DescribeVpcs` permission is missing when creating clusters

### ISSUE THREAD

**Issue by ten-lac** [aws/aws-cdk#11515] opened 2020-11-17 14:22 UTC
I'm running into the same issue as described here in [Issue #9027](https://github.com/aws/aws-cdk/issues/9027).

### Reproduction Steps
Using an account with `AdministratorAccess` managed policy role.  Trying to boot up a new cluster.

Creating a new EKS cluster with a new VPC.

### What did you expect to happen?
I expected no errors and the cluster to be created.

### What actually happened?

```
Failed to create resource. IAM role's policy must include the `ec2:DescribeVpcs` action Logs: /aws/lambda/Tenna-K8S-stg-awscdkawseksC-OnEventHandler42BEBAE0-1RVRE3JUJLLUZ at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/req
```

### Environment

  - **CDK CLI Version  :** 1.73
  - **Framework Version:** 1.73
  - **Node.js Version:**  Nodejs 12.x
  - **OS               :** MacOS
  - **Language (Version):**  Javascript

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2020-11-22 20:37
Closing as duplicate of the [issue](https://github.com/aws/aws-cdk/issues/9027) you mentioned. Please let us know if you feel this needs a separate issue.

**Closed by iliapolo** 2020-11-22 20:37 UTC
Labels: @aws-cdk/aws-eks, bug, needs-triage
