### ISSUE TITLE
(pipelines): generate shell script and call that in assets instead of requiring self mutation

### ISSUE THREAD

**Issue by Hi-Fi** [aws/aws-cdk#19136] opened 2022-02-24 12:59 UTC
### Description

Currently asset stage command are directly at the build spec. Those include e.g. image hashes, that require self mutation to get new image published.

If synth would just generate command to shell script and asset stage call that shell script (as it already get the input from cdk.out) purely application updates woudn't require self mutation.

### Use Case

- Simplifies and speeds up running
- No need to have self mutation enabled

### Proposed Solution

- generate shell script to cdk.out during synth that handles the `cdk-assets` calls
- Call "statically" that shell script so that self mutate step doesn't need to be updated all the time

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment] 2022-02-24 13:06
Duplicate of https://github.com/aws/aws-cdk/issues/9080

**Closed by rix0rrr** 2022-02-24 13:06 UTC
Labels: feature-request, needs-triage, @aws-cdk/pipelines

**Comment by hoegertn** [comment] 2022-02-24 15:10
Using `publishAssetsInParallel: false` on the pipeline you can achieve this to some degree
