### ISSUE TITLE
(aws-lambda-python-alpha): docker build for every code change

### ISSUE THREAD

**Issue by avandekleut** [aws/aws-cdk#24680] opened 2023-03-18 03:06 UTC
### Describe the bug

I have a `PythonFunction`:
```typescript
const pythonEntry = ... // location of pyproject.toml and poetry.lock + index.py

new PythonFunction(scope,  "Function", {
  entry: pythonEntry,
  runtime: Runtime.PYTHON_3_8
}
```

Any time I change `index.py` the entire thing needs to be rebuilt, dependencies and all.

### Expected Behavior

The docker building process should cache installed requirements instead of re-installing them each time.

### Current Behavior

```sh
npm run cdk deploy

> cdk@0.1.0 cdk
> cdk deploy

[+] Building 0.4s (6/6) FINISHED                                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.2s
 => => transferring dockerfile: 37B                                                                                                                                                                    0.1s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for public.ecr.aws/sam/build-python3.8:latest                                                                                                                             0.0s
 => [1/2] FROM public.ecr.aws/sam/build-python3.8                                                                                                                                                      0.0s
 => CACHED [2/2] RUN     python -m venv /usr/app/venv &&     mkdir /tmp/pip-cache &&     chmod -R 777 /tmp/pip-cache &&     pip install --upgrade pip &&     mkdir /tmp/poetry-cache &&     chmod -R   0.0s
 => exporting to image                                                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                                                0.0s
 => => writing image sha256:18270de7bbefc0043702b4ec74cdefb310286d620e26b3ce26f6a66c0ede6ee2                                                                                                           0.0s
 => => naming to docker.io/library/cdk-fe9b6ea07cdf294b7090426e8c0c270227448544e2c1d28463febc5af38db91c                                                                                                0.0s
Bundling asset <asset>
sending incremental file list
<a bunch of files in the entry>
<pip installation logs>
Installing collected packages: <packages
Successfully installed <packages>
```

### Reproduction Steps

To be honest it's not clear if this is the normal behaviour. If it is, waiting 3-4 minutes compared to 3-4 seconds for `esbuild` to bundle NodeJS dependencies is pretty brutal.

### CDK CLI Version

2.69.0

### Node.js Version

v19.7.0

### OS

MacOS

### Language

Typescript

### Language Version

4.9.5

**Comment by peterwoodworth** [comment] 2023-03-30 01:34
Yes, closing as duplicate of #23829

**Closed by peterwoodworth** 2023-03-30 01:34 UTC
Labels: p2, feature-request, effort/medium, @aws-cdk/aws-lambda-python
