### ISSUE TITLE
‼️ NOTICE: last modified date does not match with the last modified date of the retrieved parameters

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#14629] opened 2021-05-11 00:36 UTC
Please add your +1 👍 to let us know you have encountered this
---

### Overview:
 Cloudformation recently deployed a change to allow [dynamic references to ssm parameters](https://aws.amazon.com/about-aws/whats-new/2021/04/now-reference-latest-aws-systems-manager-parameter-values-in-aws-cloudformation-templates-without-specifying-parameter-versions/) within templates without needing to provide a version. This allows always referencing the latest value of a parameter within your template. This change had a bug that caused change set creation to fail when the parameter value was updated.
 
 This breakage was caused by the references resolving to a version of the parameter that include a timestamp. Upon changeset creation, if the parameter has been updated, cloudformation sees the parameter name and the previously resolved timestamped version as different values and fails to update. They have since changed logic so that the strings resolved do not include timestamps, however if a template was successfully deployed during the time that the timestamp was being appended, a stack cannot be updated via changeset while referencing a dynamic parameter.
 
 UPDATE:
 
 It is clear that removing all dynamic ssm references doesn't cause users to get unstuck. Users have to manually deploy their stacks without a changeset to get past this. That being the case, for users with lots of stacks updating each manually is a pain. We are considering adding an option to the CLI to skip a changeset if this error occurs during deploy.
 
#### Complete Error Message:
```
Parameters: [PARAMETER_NAME] last modified date does not match with the last modified date of the retrieved parameters.
```

### Workaround:
Attempt the following steps in order as a workaround:

1. Upgrade **both your CLI and all your @aws-cdk/xyz modules** to v1.103.0 - This removes dynamic SSM references and goes back to referencing them via CFN parameters.

2. Delete your stack and redeploy - If you are unable to do so because this is a production stack, and upgrading to v1.103 didn't fix the issue, please comment here with the following information and try number 3.
    - The name of the parameter causing the failure
    - An example of how you are referencing that parameter in code, IE through an enum value, manually specifying the param name etc.

3. Run `cdk synth` and then manually deploy this stack using the the aws cli or cfn console - This is not an ideal workaround for users who may have a lot of different stacks that need updating but in the meantime, this can unblock you if you need a stack deployed. We are working on figuring out another option that will allow skipping changeset creation via the aws cli.

### Solution:
This issue only shows up for users who deployed stacks during a short period of time before cloudformation fixed some of these bugs. Because of that, it is hard for us to test ourselves if removal of dynamic param references (https://github.com/aws/aws-cdk/pull/14527) solves this. If it doesn't, another solution mentioned [here](https://github.com/aws/aws-cli/issues/6106#issuecomment-825275055) is to update your stack without creating a changeset. We may be able to provide an option in the CLI to skip a changeset if this error is encountered. Since we don't have broken stacks to test this with, please let us know if this is or an additional fix is needed.

### Related Issues:
https://github.com/aws/aws-cdk/issues/14467
https://github.com/aws/aws-cli/issues/6106

**Comment by hermes-z** [comment] 2021-05-11 06:52
I have had this problem twice and after upgrading to v1.103 it seems to be solved. Thank you very much.

**Comment by nirradi** [comment] 2021-05-11 13:04
I have this issue, and I'm on 1.103

**Comment by eladb** [comment] 2021-05-11 13:28
@nirradi two quick things to validate:
1. Are you using both CLI version 1.103 and @aws-cdk/xxx 1.103?
2. Can you please share your CFN template that was synthesized

**Comment by nirradi** [comment] 2021-05-11 14:47
> @nirradi two quick things to validate:
> 
> 1. Are you using both CLI version 1.103 and @aws-cdk/xxx 1.103?
> 2. Can you please share your CFN template that was synthesized

I see now that the two systems which I work on differ by the version. Its working on  1.101 (both python packages and cli)
and its not working on 1.103 (both python packages and cli)

I'm not inclined to share the entire cfn, here are the diffs between 1.101 and 1.103
```
111c111,113
<         "ImageId": "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}",
---
>         "ImageId": {
>           "Ref": "SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter"
>         },
567a572,577
>   },
>   "Parameters": {
>     "SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter": {
>       "Type": "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>",
>       "Default": "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
>     }
569c579
```

**Comment by MrArnoldPalmer** [comment] 2021-05-12 00:02
@rsyabuta to clarify, cdk deploy on v1.103.0 was still failing with the param issue and required deploying without a change set?

**Comment by nirradi** [comment] 2021-05-12 07:19
> cdk ls -v

@MrArnoldPalmer 
```
CDK toolkit version: 1.103.0 (build bc13a66)
Command line arguments: {
  _: [ 'ls' ],
  v: 1,
  verbose: 1,
  lookups: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  debug: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  fail: false,
  long: false,
  l: false,
  '$0': 'cdk'
}
cdk.json: {
  "app": "python3 app.py"
}
cdk.context.json: {
  "availability-zones:account=********:region=eu-west-1": [
    "eu-west-1a",
    "eu-west-1b",
    "eu-west-1c"
  ]
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  context: {},
  debug: false,
  assetMetadata: true,
  toolkitBucket: {},
  staging: true,
  bundlingStacks: [],
  lookups: true
}
Determining if we're on an EC2 instance.
Looks like an EC2 instance.
Toolkit stack: CDKToolkit
Setting "CDK_DEFAULT_REGION" environment variable to ap-northeast-2
Resolving default credentials
Looking up default account ID from STS
Default account ID: ******
Setting "CDK_DEFAULT_ACCOUNT" environment variable to ******
context: {
  'availability-zones:account=*******:region=eu-west-1': [ 'eu-west-1a', 'eu-west-1b', 'eu-west-1c' ],
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
  'aws:cdk:version-reporting': true,
  'aws:cdk:bundling-stacks': []
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'ap-northeast-2',
  CDK_DEFAULT_ACCOUNT: '******',
  CDK_CONTEXT_JSON: '{"availability-zones:account=*****:region=eu-west-1":["eu-west-1a","eu-west-1b","eu-west-1c"],"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true,"aws:cdk:version-reporting":true,"aws:cdk:bundling-stacks":[]}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '11.0.0',
  CDK_CLI_VERSION: '1.103.0'
}
```

**Comment by Malanius** [comment] 2021-05-12 07:25
As I've mentioned in https://github.com/aws/aws-cdk/issues/14467#issuecomment-833323448, I encounter this in the `ec2.BastionHostLinux` construct. Still present after an update to 1.103.0. Stack is in `eu-west-1` region.

The reference in the stack is simple:

```typescript
this.bastion = new ec2.BastionHostLinux(this, `Bastion`, {
      vpc: props.vpc,
      instanceName: `${props.name}-bastion`,
      securityGroup: bastionSg,
      subnetSelection: {
        subnetType: ec2.SubnetType.PUBLIC,
      },
    });
```

Diff for the stack:

```bash
cdk diff vpc

Stack vpc (vpc)
Parameters
[+] Parameter SsmParameterValue:--aws--service--ami-amazon-linux-latest--amzn2-ami-hvm-x86_64-gp2:C96584B6-F00A-464E-AD19-53AFF4B05118.Parameter SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter: {"Type":"AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>","Default":"/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"}

Resources
[~] AWS::EC2::Instance Bastion/Bastion/Resource BastionBastion34649AD2 replace
 └─ [~] ImageId (requires replacement)
     └─ @@ -1,1 +1,3 @@
        [-] "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
        [+] {
        [+]   "Ref": "SsmParameterValueawsserviceamiamazonlinuxlatestamzn2amihvmx8664gp2C96584B6F00A464EAD1953AFF4B05118Parameter"
        [+] }
[~] AWS::EC2::EIP Bastion/BastionEIP BastionBastionEIP54D072EC may be replaced
 └─ [~] InstanceId (may cause replacement)
     └─ [~] .Ref:
         ├─ [-] BastionBastion34649AD2
         └─ [+] BastionBastion34649AD2 (replaced)
```

Fails with:

```bash
vpc (vpc): deploying...
vpc: creating CloudFormation changeset...

 ❌  vpc (vpc) failed: Error: Failed to create ChangeSet cdk-deploy-change-set on -vpc: FAILED, Parameters: [ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2:45:1619654085749] last modified date does not match with the last modified date of the retrieved parameters.
    at /home/malanius/.nvm/versions/node/v16.0.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:227:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at waitFor (/home/malanius/.nvm/versions/node/v16.0.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:188:20)
    at Object.waitForChangeSet (/home/malanius/.nvm/versions/node/v16.0.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:213:15)
    at Object.deployStack (/home/malanius/.nvm/versions/node/v16.0.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:260:32)
    at CdkToolkit.deploy (/home/malanius/.nvm/versions/node/v16.0.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/home/malanius/.nvm/versions/node/v16.0.0/lib/node_modules/aws-cdk/bin/cdk.ts:209:9)
Failed to create ChangeSet cdk-deploy-change-set on -vpc: FAILED, Parameters: [ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2:45:1619654085749] last modified date does not match with the last modified date of the retrieved parameters.
```

The workaround with manually updating stack from generated template by 1.103.0 worked for me. Probably just temporarily deleting the offending bastion resource could work as well, but this way I at least avoided updating all the stacks where Bastion is mentioned.

**Comment by cseickel** [comment] 2021-05-12 12:05
I had this issue repeatedly on 1.101 and 1.102 and my solution was to delete and redeploy the stack when it happened. The problem went away on it's own before this issue was opened without me having to upgrade. I believe the last time I hit it was May 6. I have deployed at least 20 updates in the last few days on that 1.102 stack with no issues.

**Comment by mark-ship-it** [comment] 2021-05-12 19:00
We are having this issue with cdk 1.103 and DMS.  CF is similar to below:

```
    "SourceEndpoint": {
      "Type": "AWS::DMS::Endpoint",
      "Properties": {
        "EndpointType": "source",
        "EngineName": "postgres",
        "DatabaseName": "dB",
        "EndpointIdentifier": "someid",
        "ExtraConnectionAttributes": "",
        "KmsKeyId": {
          "Ref": "Key123456"
        },
        "Password": "{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:secret0::}}",
        "Port": 5432,
        "ServerName": "{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:secret1::}}",
        "Username": "{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:secret2::}}"
      },
      "Metadata": {
        "aws:cdk:path": "App/SourceEndpoint"
      }
    },
```

**Comment by blaenk** [comment] 2021-05-13 04:05
Does the new `2.0.0-rc.3` include the fix in 1.103? I have `cdk` and `aws-cdk-lib` updated to it, but I'm still running into the issue.

Error:

```
 ❌  Control failed: Error: Failed to create ChangeSet cdk-deploy-change-set on Control: FAILED, Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:59:1619746225127] last modified date does not match with the last modified date of the retrieved parameters.
```

I think the parameter in question is this one:

```
[~] AWS::AutoScaling::LaunchConfiguration Cluster/Capacity/LaunchConfig ClusterCapacityLaunchConfigC44566A4 replace
 ├─ [~] ImageId (requires replacement)
 │   └─ @@ -1,1 +1,3 @@
 │      [-] "{{resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id}}"
 │      [+] {
 │      [+]   "Ref": "SsmParameterValueawsserviceecsoptimizedamiamazonlinux2recommendedimageidC96584B6F00A464EAD1953AFF4B05118Parameter"
 │      [+] }
```

However, I'm not explicitly referencing this myself AFAIK. Just double checked and I can't see anywhere where I am referencing anything like this.

I tried updating the stack via the web console, using the existing template without making any changes at all (is that the right process?) but I got the error:

```
Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:59:1619746225127] were updated before values were used
```

**Comment by TLadd** [comment] 2021-05-13 14:02
Also ran into this with the `ec2.BastionHostLinux` construct. Since we only use this for connecting to resources within our vpc and it's not actively receiving usage all the time, I was able to comment it out, deploy, add it back, deploy and the issue went away.

**Comment by MrArnoldPalmer** [comment] 2021-05-13 23:11
Updated the issue to include manually deploying your stack without a changeset as a workaround while we figure out if/how to allow users to do this via CDK. For users who have CI/CD deploying a high volume of stacks this obviously isn't ideal and we are figuring out if we want to add a way for the CDK CLI to deploy without a changeset and if that is good enough. If people are using the codepipeline stack deploy actions with a changeset this won't cover them and I'm not sure if there is another way to let them easily workaround this.

**Comment by andreialecu** [comment] 2021-05-14 08:46
In my case I just upgraded to `1.103.0` earlier today, and noticed a diff like the one mentioned in: https://github.com/aws/aws-cdk/issues/14629#issuecomment-840278777

The deployment finished fine. However, the very next deployment failed.

```
  EcsCluster failed: Error: Failed to create ChangeSet cdk-deploy-change-set on EcsCluster: FAILED, Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:59:1619744777312] last modified date does not match with the last modified date of the retrieved parameters.
```

So it seems that actually upgrading to `1.103.0` broke this.

Note that this stack hasn't been deployed/updated since March so the mention in the OP that this was a bug in a certain time window seems suspect. See timestamps:
<img width="1117" alt="Screenshot 2021-05-14 at 11 43 34" src="https://user-images.githubusercontent.com/697707/118245530-9eb3fa80-b4a9-11eb-861d-343f5ef1fab3.png">

The "faulty" parameter seems to be added automatically as part of creating an ECS cluster. It is not something I'm adding.

**Comment by sundeqvist** [comment] 2021-05-14 12:06
We are running into this after upgrading to 1.103.0 today, seemingly caused by usage of `EcsOptimizedImage.amazonLinux2`. 
We've run several deploys over the last few days with no errors until we upgraded to 1.103.0.


Error is `FAILED, Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:59:1619744777312] last modified date does not match with the last modified date of the retrieved parameters`.

**Comment by MrArnoldPalmer** [comment] 2021-05-14 16:37
@andreialecu I don't see how that is possible. What version were you on when the stack was last deployed? Can you also verify that you were using both the CLI and @aws-cdk/* libraries with version 1.103.0? It appears that not only dynamic references were broken, but all SSM param references including those passed via CFN parameters. If that is the case, the timing of the breakage could be based purely on when these parameters were updated in relation to when stack updates occurred and when the feature was rolled out on CFN's side. This makes it really hard for us to figure out what users are affected and how exactly.

Are you able to attempt updating your stack manually as mentioned in the issue to workaround? I'm curious if that helps in your case.

**Comment by andreialecu** [comment] 2021-05-14 17:38
@MrArnoldPalmer we were on 1.100.0 but the affected stack did not have any changes made to it since March. (As can be seen from the screenshot)

It was only after updating to 103 that the diff appeared, as mentioned in my previous comment. Deploying it the first time worked. But any subsequent deploys have failed. 

I haven't yet tried manually deploying.

**Comment by andreialecu** [comment] 2021-05-14 18:25
Oops. My screenshot does show that it was actually previously deployed on the 5th of May, probably using 1.100.0. NOT in March. Sorry about that. Had a mental hiccup, I thought 05.05 was today 🤦🏻‍♂️

**Comment by andreialecu** [comment] 2021-05-14 19:59
@MrArnoldPalmer I can confirm that manually updating the stack using the AWS console did work.

**Comment by MrArnoldPalmer** [comment] 2021-05-14 20:10
Thank you @andreialecu for investigating!

Anyone else that is still blocked and having trouble with the workarounds please keep letting us know.

**Comment by seawatts** [comment] 2021-05-15 16:44
> Updated the issue to include manually deploying your stack without a changeset as a workaround while we figure out if/how to allow users to do this via CDK. For users who have CI/CD deploying a high volume of stacks this obviously isn't ideal and we are figuring out if we want to add a way for the CDK CLI to deploy without a changeset and if that is good enough. If people are using the codepipeline stack deploy actions with a changeset this won't cover them and I'm not sure if there is another way to let them easily workaround this.

Thanks for the response @MrArnoldPalmer 😃 I am using the CI/CD AWS CDK Pipeline to deploy my stacks. Just confirming what you're saying here. There is not currently a workaround? Would rolling back the cdk version work?

**Comment by cseickel** [comment] 2021-05-17 14:24
I managed to go long time without this issue but it came back today. I upgraded from 1.101.0 to 1.104.0 but it did not fix it. This is for an ECS cluster and the parameter is implicit in the construct as opposed to anything I create in my own code:
`Failed to create ChangeSet cdk-deploy-change-set on alfresco-app-dev: FAILED, Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:60:1620247830216] last modified date does not match with the last modified date of the retrieved parameters.`

I used the workaround of cdk synth and manually uploaded the template via the console and that is working.

**Comment by clemans** [comment] 2021-05-17 22:40
> I used the workaround of cdk synth and manually uploaded the template via the console and that is working.

Upgrading from 1.102.0 to 1.104.0 did not solve my issue but the workaround provided by @cseickel worked.

**Comment by MrArnoldPalmer** [comment] 2021-05-17 22:59
@seawatts unfortunately no, this isn't casued by anything in the CDK it's caused by an issue on the cloudformation side. The only workaround is to run `cdk synth` and then manually deploy the contents of `cdk.out` using the CLI or clouformation console. Doing so will allow you to skip changeset creation. Otherwise you would have to change your codepipeline actions to be `CREATE_UPDATE` instead of `CHANGE_SET_REPLACE` + `CHANGE_SET_EXECUTE`.

**Comment by rahulpshah** [comment] 2021-05-18 07:49
Is the upgrade to cdk 1.103 necessary for the workaround? Would simply running `cdk synth` and applying the output of cdk.out on the UI work?
Current version: 1.101

**Comment by kastningj** [comment] 2021-05-18 14:05
Unfortunately, none of the suggestions in this and other linked tickets have worked for me. I've tried:

1) upgrading cli and modules (currently on v1.104.0)
 `Error: Failed to create ChangeSet cdk-deploy-change-set on my-stack-name: FAILED, Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:60:1620247830216] last modified date does not match with the last modified date of the retrieved parameters.`

2) calling update-stack (without a change set):
`An error occurred (ValidationError) when calling the UpdateStack operation: Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:60:1620247830216] were updated before values were used`

3) running cdk synth and then manually deploy my stack using the the aws cli
`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:60:1620247830216] last modified date does not match with the last modified date of the retrieved parameters.`

Code:
`        EcsOptimizedImage ecsOptimizedImage = EcsOptimizedImage.amazonLinux2();
        AutoScalingGroup asg = new AutoScalingGroup(this, name + "-asg", AutoScalingGroupProps.builder()
                .instanceType(instanceType)
                .machineImage(ecsOptimizedImage)
                .blockDevices(blockDevices)
                .desiredCapacity(minCapacity)
                .maxCapacity(maxCapacity)
                .minCapacity(minCapacity)
                .keyName(clusterName)
                .groupMetrics(metrics)
                .vpc(vpc)
                .instanceMonitoring(isProduction ? Monitoring.DETAILED : Monitoring.BASIC)
                .allowAllOutbound(true)
                .role(createEC2InstanceRole(name + "-ec2-instance"))
                .build());`

Are there any other suggestions to try other than deleting/recreating stacks?

**Comment by clemans** [comment] 2021-05-18 14:12
> Are there any other suggestions to try other than deleting/recreating stacks?
@kastningj  I have a similar CDK project using `EcsOptimizedImage.amazonLinux2()` and `AutoScalingGroup`. 
Uploading the `cdk synth > cloudformation.yaml` template in the AWS Management Console worked for me and I hope it does for you as well.

**Comment by kastningj** [comment] 2021-05-18 15:26
@clemans Thanks! Your reply made me realize I hadn't tried uploading via the AWS Management Console, only command line. The upload via the console worked! Saves me from deleting / recreating stacks. Appreciate the help!

**Comment by MrArnoldPalmer** [comment] 2021-05-18 16:49
@kastningj the workaround is deploy without creating a changeset, it looks like when you were using the CLI you were still going through changeset creation when what is required is doing `update-stack` directly. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html

Glad the console resolved this though that seems like the easiest if you only need to do a couple of stacks.

**Comment by MrArnoldPalmer** [comment] 2021-05-18 16:50
> Is the upgrade to cdk 1.103 necessary for the workaround? Would simply running `cdk synth` and applying the output of cdk.out on the UI work? Is it possible to roll back to known version?
> Current version: 1.101

@rahulpshah updating is not required to do the workaround, but it may prevent you from needing it as some users report v1.103.0 fixing the issue for them.

**Comment by FlorinAsavoaie** [comment] 2021-05-27 17:23
Also getting this issue for `obtainDefaultFluentBitECRImage` from `@aws-cdk/aws-ecs`... This is really frustrating.

**Comment by skotadia** [comment] 2021-06-13 16:37
I am using AWS SAM template. I believe, underneath, it is using aws cdk. I am getting same issue. I don't have an option of deletion of the stack or doing it manual. Do we have any workaround for aws sam CLI? Thanks

**Comment by AbdoNile** [comment] 2021-06-28 15:28
I managed to find a fix for this with @Shogan . It is a "surgical" workaround , but will allow you to get the stack in an "updateable" state using CDK without recreating it.

1. get the new ssm parameter last modified date time stamp from aws console or using ssm cli get-parameter
2. convert the time into Unix format including milliseconds . I used https://time.lol for this. You should end up with something that looks like "1616080117000"
3. In AWS Console cloudformation screen , open the stack , click on "edit in designer"
4. the lower pan of the designed contains the template in YAML format
5. find and replace all instances of ""{{resolve:ssm:/ssm_parameter_name:1:OLD_TIME_STAMP}}" with ""{{resolve:ssm:/ssm_parameter_name:1:NEW UNIX_TIME_STAMP}}"
6. Save the template to a local YAML file to your computer
7. Close the Designer
8. From CloudFormation Console again , Click on Update Stack , Replace Existing stack , upload your template file that you downloaded from the designer.
9. Follow the wizard until the stack update is completed.

If all goes well , you should be able to deploy the stack using cdk going forward.

**Comment by FlorinAsavoaie** [comment] 2021-06-28 17:02
I did something similar to @AbdoNile but simply replaced the parameters with the actual values. After that succeeded, I deployed again through CDK and it worked.

**Comment by rix0rrr** [comment] 2022-02-14 16:11
This issue was a notification for a transient error. Due to the lack of recent engagement, I'll assume most people that were affected by this managed to unstick themselves by now. Closing.

**Closed by rix0rrr** 2022-02-14 16:11 UTC
Labels: management/tracking, p0, @aws-cdk/core, @aws-cdk/aws-ssm
