### ISSUE TITLE
[lambda] Can't use imported lambda with ELBv2

### ISSUE THREAD

**Issue by stevensu1977** [aws/aws-cdk#8597] opened 2020-06-17 01:53 UTC
### The Question
I need create ALB with lambda , when I create new Lambda , I use `add_permission `give lambda resource policy , it's work, but when I use `from_function_arn` load exits lambda , get:
```console
"No child with id: 'InvokeServicePrincipal(elasticloadbalancing.amazonaws.com)'" error
```

```py
        # create new lambda , it's work
        # my_lambda = _lambda.Function(
        #     self, 'HelloHandler',
        #     runtime=_lambda.Runtime.PYTHON_3_7,
        #     code=_lambda.Code.asset('lambda'),
        #     handler='hello.handler',
        # )

        #load exits lambda not work
        my_lambda = _lambda.Function.from_function_arn(self,"HelloHandler","arn:aws:lambda:us-east-1:596030579944:function:hello-envoy-lambda")

```

### Environment

  - **CDK CLI Version:**  1.45.0 (build 0cfab15)
  - **Module Version:**  1.45.0
  - **Node.js Version:**  12.4
  - **OS:** OSX 
  - **Language (Version):** Python (3.7.3)

### Other information
```conslole
jsii.errors.JSIIError: No child with id: 'InvokeServicePrincipal(elasticloadbalancing.amazonaws.com)'
```

**Comment by stevensu1977** [comment] 2020-06-19 01:38
Final found this issue because IFunction have no grantInvoke() method ,  may be we can add method , thanks @pahud comments , 

//Pahud's example code .
export class ImportedLambdaTarget implements elbv2.IApplicationLoadBalancerTarget {

  constructor(private readonly fn: lambda.IFunction) {
  }

  public attachToApplicationTargetGroup(targetGroup: elbv2.IApplicationTargetGroup): elbv2.LoadBalancerTargetProps {
    const permission = new lambda.CfnPermission(cdk.Stack.of(this.fn), 'GrantInvoke', {
      action: 'lambda:InvokeFunction',
      principal: 'elasticloadbalancing.amazonaws.com',
      functionName: this.fn.functionArn,
    });
    targetGroup.node.addDependency(permission)
    
    return {
      targetType: elbv2.TargetType.LAMBDA,
      targetJson: { id: this.fn.functionArn },
    };
  }
}


https://github.com/aws/aws-cdk/blob/4b68655eefc5f82af0ef1d90f1ba96e01b0e902b/packages/%40aws-cdk/aws-elasticloadbalancingv2-targets/lib/lambda-target.ts#L21

**Comment by BaluVyamajala** [comment] 2020-08-01 23:30
Is there a work around for this? I ran into exact same issue.

**Comment by cprice404-aws** [comment] 2020-08-13 23:31
I ran into this too.  Until the bug is fixed, I was able to work around it with lambda.CfnPermission:

```
    const myLambda = lambda.Function.fromFunctionArn(this, 'MyLambda', myLambdaArn)

    const myRule = new events.Rule(this, 'MyRule', {
      schedule: events.Schedule.rate(cdk.Duration.seconds(60)),
      targets: [new targets.LambdaFunction(myLambda)]
    })

      new lambda.CfnPermission(this, 'MyRule_MyLambda_InvokePermission', {
          action: 'lambda:InvokeFunction',
          functionName: myLambda.functionArn,
          principal: 'events.amazonaws.com',
          sourceArn: myRule.ruleArn
      })
```

**Comment by njlynch** [comment] 2020-08-25 09:32
Closing out as a duplicate of two existing bugs: #7588 and #9883.

**Closed by njlynch** 2020-08-25 09:32 UTC
Labels: @aws-cdk/aws-elasticloadbalancingv2, @aws-cdk/aws-lambda, bug, effort/medium, p1

**Comment by pcolazurdo** [comment] 2020-09-30 16:17
This bug is specific to how the aws-elasticloadbalancingv2 tries to manage the permissions of "imported" Lambdas. The workaround doesn't work in this case.

The error displayed is:

```
No child with id: 'InvokeServicePrincipal(elasticloadbalancing.amazonaws.com)'

/home/ec2-user/environment/monolithic-modernization-lab/root-endpoint/node_modules/@aws-cdk/core/lib/private/synthesis.ts:151
    throw new Error(`Validation failed with the following errors:\n  ${errorList}`);
          ^
Error: Validation failed with the following errors:
  [RootEndpointStack/LB/Listener] Listener needs at least one default action or target group (call addTargetGroups or addAction)
    at validateTree (/home/ec2-user/environment/monolithic-modernization-lab/root-endpoint/node_modules/@aws-cdk/core/lib/private/synthesis.ts:151:11)
    at Object.synthesize (/home/ec2-user/environment/monolithic-modernization-lab/root-endpoint/node_modules/@aws-cdk/core/lib/private/synthesis.ts:25:5)
    at App.synth (/home/ec2-user/environment/monolithic-modernization-lab/root-endpoint/node_modules/@aws-cdk/core/lib/stage.ts:175:23)
    at process.App.process.once (/home/ec2-user/environment/monolithic-modernization-lab/root-endpoint/node_modules/@aws-cdk/core/lib/app.ts:112:45)
    at Object.onceWrapper (events.js:286:20)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
    at process.emit (/home/ec2-user/environment/monolithic-modernization-lab/root-endpoint/node_modules/source-map-support/source-map-support.js:495:21)
    at process.topLevelDomainCallback (domain.js:126:23)
```

The code is:
```
    const lb = new elbv2.ApplicationLoadBalancer(this, 'LB', {
      vpc,
      internetFacing: false
    });

    const listener = lb.addListener('Listener', {
      port: 80,
    });

    const fn = lambda.Function.fromFunctionArn(this, 'myFunction', functionARN)

    listener.addTargets('Target', {
      port: 80,
      targets: [new targets.LambdaTarget(fn)]
    });
    
    // @aws-cdk/aws-elasticloadbalancingv2-targets.LambdaTarget
    const lambdaTarget = new targets.LambdaTarget(fn);
    
    new lambda.CfnPermission(this, 'MyRule_MyLambda_InvokePermission', {
          action: 'lambda:InvokeFunction',
          functionName: fn.functionArn,
          principal: 'elasticloadbalancing.amazonaws.com',
          sourceArn: listener.listenerArn
      })
    
    listener.addTargets('Target', {
      port: 80,
      targets: [lambdaTarget]
    })

    listener.connections.allowDefaultPortFromAnyIpv4('test');
```
