### ISSUE TITLE
S3 bucket notifications not being updated correctly when changing from Lambda to SNS Topic destination

### ISSUE THREAD

**Issue by floehopper** [aws/aws-cdk#1894] opened 2019-02-26 17:18 UTC
Steps to reproduce using v0.24.1:

1. Create a stack from scratch with an S3 bucket and a lambda function listening for object created events from the S3 bucket.

```typescript
export class AwsCdkInsertingSnsTopicStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const myBucket = new s3.Bucket(this, 'myBucket');

    const myFunctionOne = new lambda.Function(this, 'myFunctionOne', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'index.handler',
      code: lambda.Code.inline(`
        exports.handler = async (event, context) => { console.log(event) }
      `)
    });

    myBucket.onObjectCreated(myFunctionOne);
  }
}
```

2. Upload a file to the S3 bucket and observe that a `ObjectCreated:Put` event is logged by the lambda function.

3. Add an SNS Topic to the stack to listen for the object created events for the S3 bucket and subscribe the lambda function to the Topic.

```typescript
export class AwsCdkInsertingSnsTopicStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const myBucket = new s3.Bucket(this, 'myBucket');

    const myTopic = new Topic(this, 'myTopic');
    myBucket.onObjectCreated(myTopic);

    const myFunctionOne = new lambda.Function(this, 'myFunctionOne', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'index.handler',
      code: lambda.Code.inline(`
        exports.handler = async (event, context) => {
          console.log(JSON.parse(event.Records[0].Sns.Message))
        }
      `)
    });

    myTopic.subscribeLambda(myFunctionOne);
  }
}
```

4. Upload a file to the S3 bucket and observe that a `ObjectCreated:Put` event is logged by the lambda function.

5. Create a new stack from scratch with two S3 buckets and two lambda functions listening for object created events from the S3 buckets.

```typescript
export class AwsCdkInsertingSnsTopicStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const myBucketOne = new s3.Bucket(this, 'myBucketOne');

    const myFunctionOne = new lambda.Function(this, 'myFunctionOne', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'index.handler',
      code: lambda.Code.inline(`
        exports.handler = async (event, context) => { console.log(event) }
      `)
    });

    myBucketOne.onObjectCreated(myFunctionOne);

    const myBucketTwo = new s3.Bucket(this, 'myBucketTwo');

    const myFunctionTwo = new lambda.Function(this, 'myFunctionTwo', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'index.handler',
      code: lambda.Code.inline(`
        exports.handler = async (event, context) => { console.log(event) }
      `)
    });

    myBucketTwo.onObjectCreated(myFunctionTwo);
  }
}
```

6. Upload a file to each of the S3 buckets and observe that a `ObjectCreated:Put` event is logged by each of the lambda functions.

7. Add two SNS Topics to the stack to listen for the object created events for each S3 bucket and subscribe the lambda functions to the relevant Topic.

```typescript
export class AwsCdkInsertingSnsTopicStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const myBucketOne = new s3.Bucket(this, 'myBucketOne');

    const myTopicOne = new Topic(this, 'myTopicOne');
    myBucketOne.onObjectCreated(myTopicOne);

    const myFunctionOne = new lambda.Function(this, 'myFunctionOne', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'index.handler',
      code: lambda.Code.inline(`
        exports.handler = async (event, context) => {
          console.log(JSON.parse(event.Records[0].Sns.Message))
        }
      `)
    });

    myTopicOne.subscribeLambda(myFunctionOne);

    const myBucketTwo = new s3.Bucket(this, 'myBucketTwo');

    const myTopicTwo = new Topic(this, 'myTopicTwo');
    myBucketTwo.onObjectCreated(myTopicTwo);

    const myFunctionTwo = new lambda.Function(this, 'myFunctionTwo', {
      runtime: lambda.Runtime.NodeJS810,
      handler: 'index.handler',
      code: lambda.Code.inline(`
        exports.handler = async (event, context) => {
          console.log(JSON.parse(event.Records[0].Sns.Message))
        }
      `)
    });

    myTopicTwo.subscribeLambda(myFunctionTwo);
  }
}
```

8. Upload a file to each of the S3 buckets and observe that **no** `ObjectCreated:Put` events are logged by either of the lambda functions.

9. Also notice that neither of the S3 buckets have any active notifications showing up in the AWS web console.

The output from the `cdk deploy` command in step 7 is:

```
AwsCdkInsertingSnsTopicStack: deploying...
AwsCdkInsertingSnsTopicStack: creating CloudFormation changeset...
  0/16 | 16:20:55 | CREATE_IN_PROGRESS   | AWS::SNS::Topic               | myTopicTwo (myTopicTwoE53F3302)
  0/16 | 16:20:55 | CREATE_IN_PROGRESS   | AWS::SNS::Topic               | myTopicOne (myTopicOne2F094366)
  0/16 | 16:20:55 | CREATE_IN_PROGRESS   | AWS::SNS::Topic               | myTopicTwo (myTopicTwoE53F3302) Resource creation Initiated
  0/16 | 16:20:55 | CREATE_IN_PROGRESS   | AWS::SNS::Topic               | myTopicOne (myTopicOne2F094366) Resource creation Initiated
  0/16 | 16:20:55 | UPDATE_IN_PROGRESS   | AWS::Lambda::Function         | myFunctionOne (myFunctionOne1B801B46)
  1/16 | 16:20:56 | UPDATE_COMPLETE      | AWS::Lambda::Function         | myFunctionOne (myFunctionOne1B801B46)
  1/16 | 16:20:56 | UPDATE_IN_PROGRESS   | AWS::CDK::Metadata            | CDKMetadata
  1/16 | 16:20:56 | UPDATE_IN_PROGRESS   | AWS::Lambda::Function         | myFunctionTwo (myFunctionTwo5DB4B9BF)
  2/16 | 16:20:56 | UPDATE_COMPLETE      | AWS::Lambda::Function         | myFunctionTwo (myFunctionTwo5DB4B9BF)
  3/16 | 16:20:57 | UPDATE_COMPLETE      | AWS::CDK::Metadata            | CDKMetadata
  4/16 | 16:21:05 | CREATE_COMPLETE      | AWS::SNS::Topic               | myTopicTwo (myTopicTwoE53F3302)
  5/16 | 16:21:05 | CREATE_COMPLETE      | AWS::SNS::Topic               | myTopicOne (myTopicOne2F094366)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::SNS::Subscription        | myFunctionTwo/myTopicTwoSubscription (myFunctionTwomyTopicTwoSubscriptionD071B8C4)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::SNS::TopicPolicy         | myTopicTwo/Policy (myTopicTwoPolicy4EDFC3F3)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::SNS::Subscription        | myFunctionOne/myTopicOneSubscription (myFunctionOnemyTopicOneSubscriptionA41AA0A8)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::Lambda::Permission       | myFunctionOne/myTopicOne (myFunctionOnemyTopicOneF622DE18)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::Lambda::Permission       | myFunctionTwo/myTopicTwo (myFunctionTwomyTopicTwo7971BB17)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::Lambda::Permission       | myFunctionOne/myTopicOne (myFunctionOnemyTopicOneF622DE18) Resource creation Initiated
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::SNS::TopicPolicy         | myTopicOne/Policy (myTopicOnePolicy1581081F)
  5/16 | 16:21:08 | CREATE_IN_PROGRESS   | AWS::Lambda::Permission       | myFunctionTwo/myTopicTwo (myFunctionTwomyTopicTwo7971BB17) Resource creation Initiated
  5/16 | 16:21:09 | CREATE_IN_PROGRESS   | AWS::SNS::TopicPolicy         | myTopicTwo/Policy (myTopicTwoPolicy4EDFC3F3) Resource creation Initiated
  5/16 | 16:21:09 | CREATE_IN_PROGRESS   | AWS::SNS::Subscription        | myFunctionTwo/myTopicTwoSubscription (myFunctionTwomyTopicTwoSubscriptionD071B8C4) Resource creation Initiated
  6/16 | 16:21:09 | CREATE_COMPLETE      | AWS::SNS::TopicPolicy         | myTopicTwo/Policy (myTopicTwoPolicy4EDFC3F3)
  6/16 | 16:21:09 | CREATE_IN_PROGRESS   | AWS::SNS::Subscription        | myFunctionOne/myTopicOneSubscription (myFunctionOnemyTopicOneSubscriptionA41AA0A8) Resource creation Initiated
  7/16 | 16:21:09 | CREATE_COMPLETE      | AWS::SNS::Subscription        | myFunctionOne/myTopicOneSubscription (myFunctionOnemyTopicOneSubscriptionA41AA0A8)
  8/16 | 16:21:09 | CREATE_COMPLETE      | AWS::SNS::Subscription        | myFunctionTwo/myTopicTwoSubscription (myFunctionTwomyTopicTwoSubscriptionD071B8C4)
  8/16 | 16:21:09 | CREATE_IN_PROGRESS   | AWS::SNS::TopicPolicy         | myTopicOne/Policy (myTopicOnePolicy1581081F) Resource creation Initiated
  9/16 | 16:21:09 | CREATE_COMPLETE      | AWS::SNS::TopicPolicy         | myTopicOne/Policy (myTopicOnePolicy1581081F)
  9/16 | 16:21:11 | UPDATE_IN_PROGRESS   | Custom::S3BucketNotifications | myBucketTwo/Notifications (myBucketTwoNotificationsF9280AC6)
  9/16 | 16:21:12 | UPDATE_IN_PROGRESS   | Custom::S3BucketNotifications | myBucketOne/Notifications (myBucketOneNotificationsD2261A45)
  9/16 | 16:21:14 | UPDATE_IN_PROGRESS   | Custom::S3BucketNotifications | myBucketTwo/Notifications (myBucketTwoNotificationsF9280AC6) Requested update required the provider to create a new physical resource
 10/16 | 16:21:14 | UPDATE_COMPLETE      | Custom::S3BucketNotifications | myBucketTwo/Notifications (myBucketTwoNotificationsF9280AC6)
 10/16 | 16:21:18 | UPDATE_IN_PROGRESS   | Custom::S3BucketNotifications | myBucketOne/Notifications (myBucketOneNotificationsD2261A45) Requested update required the provider to create a new physical resource
 11/16 | 16:21:18 | UPDATE_COMPLETE      | Custom::S3BucketNotifications | myBucketOne/Notifications (myBucketOneNotificationsD2261A45)
 12/16 | 16:21:18 | CREATE_COMPLETE      | AWS::Lambda::Permission       | myFunctionOne/myTopicOne (myFunctionOnemyTopicOneF622DE18)
 13/16 | 16:21:19 | CREATE_COMPLETE      | AWS::Lambda::Permission       | myFunctionTwo/myTopicTwo (myFunctionTwomyTopicTwo7971BB17)
 13/16 | 16:21:21 | UPDATE_COMPLETE_CLEA | AWS::CloudFormation::Stack    | AwsCdkInsertingSnsTopicStack
 13/16 | 16:21:22 | DELETE_IN_PROGRESS   | AWS::CloudFormation::CustomResource | myBucketOne/Notifications (myBucketOneNotificationsD2261A45)
 13/16 | 16:21:23 | DELETE_IN_PROGRESS   | AWS::CloudFormation::CustomResource | myBucketTwo/Notifications (myBucketTwoNotificationsF9280AC6)
 14/16 | 16:21:25 | DELETE_COMPLETE      | AWS::CloudFormation::CustomResource | myBucketOne/Notifications (myBucketOneNotificationsD2261A45)
 15/16 | 16:21:25 | DELETE_COMPLETE      | AWS::CloudFormation::CustomResource | myBucketTwo/Notifications (myBucketTwoNotificationsF9280AC6)
 15/16 | 16:21:26 | DELETE_IN_PROGRESS   | AWS::Lambda::Permission       | myFunctionOneAllowBucketNotificationsFromAwsCdkInsertingSnsTopicStackmyBucketOneEF5E592A629D2DD9
 15/16 | 16:21:26 | DELETE_IN_PROGRESS   | AWS::Lambda::Permission       | myFunctionTwoAllowBucketNotificationsFromAwsCdkInsertingSnsTopicStackmyBucketTwo1F5B640810D7806B

 ✅  AwsCdkInsertingSnsTopicStack

Stack ARN:
arn:aws:cloudformation:eu-west-2:687105911108:stack/AwsCdkInsertingSnsTopicStack/280f9c40-39e0-11e9-814c-06afee4bb078
```

Am I doing something wrong? Does anyone know why the notifications are broken after the changes in step 7?

**Comment by rix0rrr** [comment] 2019-02-27 08:58
Could this be related to either of these issues?

https://github.com/awslabs/aws-cdk/issues/1539
https://github.com/awslabs/aws-cdk/issues/1566

**Comment by floehopper** [comment] 2019-02-27 13:42
@rix0rrr:

> Could this be related to either of these issues?
>
> #1539
> #1566

Possibly, although both of those look like they are related to renaming resources which I'm not doing in my example.

**Comment by floehopper** [comment] 2019-02-27 13:49
I've done a bit more investigation. Reading [the documentation for PUT Bucket notification][1], I saw this note:

> The PUT notification is an atomic operation. For example, suppose your notification configuration includes SNS topic, SQS queue, and Lambda function configurations. When you send a PUT request with this configuration, Amazon S3 sends test messages to your SNS topic. If the message fails, the entire PUT operation will fail, and Amazon S3 will not add the configuration to your bucket.

I was concerned that the code in my lambda functions was raising an error when it received the `s3:TestEvent` message and thus was causing the entire PUT operation to fail. However, I have now confirmed that this isn't a problem. So not really any further forward, but at least I've ruled that out.

[1]: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html

**Comment by OKDuncan** [comment] 2019-06-19 08:47
anything happen to this? receiving a similar error:

CREATE_FAILED      S3Bucket                                                         AWS::S3::Bucket            Wed Jun 19 2019 01:41:22 GMT-0700 (Pacific Daylight Time) amplify-auth-web926add26939f434f876a59074af9c727-plzthnx already exists

**Comment by floehopper** [comment] 2019-06-19 09:47
@OKDuncan 

I worked around the problem by explicitly sending SNS messages rather than relying on S3 object events. So as far as I'm aware the issue as I described it is still a problem.

What makes you think your issue is the same? I don't think I was seeing any `CREATE_FAILED` log statements - it was just that none of the S3 object events were being received by the lambda functions.

**Comment by TheRealAmazonKendra** [comment] 2023-01-24 23:08
Closing due to being unable to reproduce. If this issue occurs again, please feel free to open a new issue for it.

**Closed by TheRealAmazonKendra** 2023-01-24 23:08 UTC
Labels: bug, p2, @aws-cdk/aws-s3, effort/medium
