### ISSUE TITLE
inflight@1.0.6: This modules is not supported, and leaks memory. Do not use it. glob@7.2.3: Glob versions prior to v9 are no longer supported

### ISSUE THREAD

**Issue by sholtomaud** [aws/aws-cdk#32071] opened 2024-11-09 00:04 UTC
### Describe the bug

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No warnings allowed in production

### Current Behavior

Modules are not supported

### Reproduction Steps

npx cdk init app --language=typescript

### CDK CLI Version

cdk@2.166.0

### Node.js Version

20

### OS

macos

### Language

TypeScript

**Comment by ashishdhingra** [comment] 2024-11-11 18:45
@sholtomaud Good morning. This is a duplicate of https://github.com/aws/aws-cdk/issues/31420. Could you please add 👍 to the other issue?

Closing this since https://github.com/aws/aws-cdk/issues/31420 is already tiraged.

**Closed by ashishdhingra** 2024-11-11 18:45 UTC
Labels: bug, duplicate, p2, package/tools
