### ISSUE TITLE
(@aws-cdk/aws-s3-deployment): wrong MIME type for WebAssembly files

### ISSUE THREAD

**Issue by maapteh** [aws/aws-cdk#14956] opened 2021-06-02 15:44 UTC
When using the BucketDeployment we have small options to include and exclude. Somehow we are not getting it right. The origin lays in the fact that aws s3 is serving .wasm files as wrong MIME type namely `content-type: binary/octet-stream` while it should be `content-type: application/wasm`.

Im wondering why feature requests like:
https://github.com/aws/aws-cdk/issues/7090
https://github.com/aws/aws-cdk/issues/4687

Don't have any traction, since our old s3 cp task could do this simply in a heartbeat. 

Is it possible to fix this [mime type](https://github.com/aws/aws-cli/blob/master/awscli/customizations/s3/utils.py#L340), or for consumers to alter headers per file type OR patterns in a simple way without first including part x then excluding part y then including part y excluding part z. It's not readable and not maintainable.

**Comment by otaviomacedo** [comment] 2021-06-03 12:40
Hi, @maapteh. Thanks for raising this.

As you point out, this problem is being tracked by two other issues and prioritized accordingly against our backlog.

Having said that, do you think there is anything specific about WebAssembly? In other words, if we add support for file name patterns in general, would it solve your specific problem?

**Comment by maapteh** [comment] 2021-06-03 12:45
Yes for WebAssembly it would fix our main issue currently, since streaming compilation failed which makes it slower for the devices. So that's why we needed the feature, but if you can look in the rootcause why by default it gives the wrong MIME type that would be perfect!

```
streaming compile failed. Falling back to ArrayBuffer instantiation (this will make things slower)
```

**Comment by otaviomacedo** [comment] 2021-06-03 13:30
The root cause is that Python's [mimetypes] library (that the AWS CLI relies on to guess the MIME type) doesn't have a mapping for WebAssembly. You can try to send a pull request to them with a new entry:

```
'.wasm'    : 'application/wasm',
```

[mimetypes]: https://github.com/python/cpython/blob/cedc9b74202d8c1ae39bca261cbb45d42ed54d45/Lib/mimetypes.py#L402-L530

**Comment by maapteh** [comment] 2021-06-03 13:54
It has:

https://github.com/python/cpython/blob/main/Lib/mimetypes.py#L444

**Comment by otaviomacedo** [comment] 2021-06-03 15:28
In that case, I'm closing this issue as a duplicate of the other two. Feel free to +1 them, which helps us prioritize our work.

**Closed by otaviomacedo** 2021-06-03 15:28 UTC
Labels: @aws-cdk/aws-s3-deployment, bug, needs-triage
