### ISSUE TITLE
Update default `buildImage` of CDK pipeline `BuildEnvironment`

### ISSUE THREAD

**Issue by vumdao** [aws/aws-cdk#24487] opened 2023-03-07 04:53 UTC
### Describe the feature

The default image build of CDK pipeline is LinuxBuildImage.STANDARD_1_0 which is far from the latest unsupported version STANDARD_5_0 
```
export interface BuildEnvironment {
    /**
     * The image used for the builds.
     *
     * @default LinuxBuildImage.STANDARD_1_0
     */
    readonly buildImage?: IBuildImage;
```

Announcement from AWS: We are reaching out to you because you ran a build using the Ubuntu standard 5.0 [1] Docker Image, Amazon Linux 2 ARM standard 1.0 [2], or Amazon Linux 2 standard 3.0 [3] in the last 30 days. Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.  You may continue using these images for your builds, but you will notice an increase in provisioning latency after March 30, 2023.

### Use Case

I would like to use the default buildImage from `aws-codebuild` so the default version should be the supported one 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.67.0

### Environment details (OS name and version, etc.)

macOS Ventura 13.2.1

**Comment by markusl** [comment] 2023-03-07 07:34
Is this same as #16707 ?

**Comment by pahud** [comment] 2023-03-07 15:31
Yes we noticed some related issues regarding the build image. I'll discuss with the team internally.

**Comment by mrrzest** [comment] 2023-03-08 14:50
Looks like https://github.com/aws/aws-cdk/issues/23617 is also related.

**Comment by peterwoodworth** [comment] 2023-03-08 21:01
Thanks for the request,

Closing as duplicate of #16707

**Closed by peterwoodworth** 2023-03-08 21:01 UTC
Labels: feature-request, investigating, @aws-cdk/pipelines
