### ISSUE TITLE
Allow VPCs to have a default gateway via VPN gateway

### ISSUE THREAD

**Issue by MentalPower** [aws/aws-cdk#7918] opened 2020-05-11 21:35 UTC
### Use Case

You can currently create a VPC with isolated subnets and a VPN Gateway via something like:

```ts
const vpc = new ec2.Vpc(this, 'Vpc' {
  vpnGatewayAsn: 1234,
  vpnGateway: true,
  subnetConfiguration: [{
    subnetType: ec2.SubnetType.ISOLATED,
    name: "",
  }],
}); 
```

However, there's currently no way for those isolated subnets to treat the VPN gateway as their default route. This case is common in setups where all internet-bound traffic goes through another account/VPC.

### Proposed Solution

```ts
const vpc = new ec2.Vpc(this, 'Vpc' {
  vpnGatewayAsn: 1234,
  vpnGateway: true,
  subnetConfiguration: [{
    subnetType: ec2.SubnetType.ISOLATED,
    name: "",
  }],
  vpnDefaultGateway: [{
    subnetType: ec2.SubnetType.ISOLATED,
  }],
}); 
```

This configuration will then call the existing [`subnet.addDefaultInternetRoute()`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1490) method (currently only used for Internet Gateways) passing in the selected subnets and the newly created VPNGW attachment.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2020-05-13 09:36
I'm wary of adding more bells and whistles to the existing VPC class.

Treating this as duplicate of https://github.com/aws/aws-cdk/issues/5927

**Closed by rix0rrr** 2020-05-13 09:36 UTC
Labels: @aws-cdk/aws-ec2, feature-request, needs-triage
