### ISSUE TITLE
(@aws-cdk/pipelines): Stages with cross-region stacks fail when crossAccountKeys is true

### ISSUE THREAD

**Issue by andcea** [aws/aws-cdk#12780] opened 2021-01-29 20:12 UTC
If I define stacks with different regions part of the same Stage and crossAccountKeys is true, synth fails with:
`Error: Stack "MyPipelineStack" cannot consume a cross reference from stack "cross-region-stack-111111111111:ca-central-1". Cross stack references are only supported for stacks deployed to the same environment or between nested stacks and their parent stack`

If I set crossAccountKeys to false, it synths and deploys fine.

### Reproduction Steps

Change `crossAccountKeys` to `true` below for synth to fail.

```
#!/usr/bin/env node
import * as codepipeline from '@aws-cdk/aws-codepipeline'
import * as codepipeline_actions from '@aws-cdk/aws-codepipeline-actions'
import * as cdk from '@aws-cdk/core'
import { App, CfnOutput, Construct, SecretValue, Stack, StackProps, Stage, StageProps } from '@aws-cdk/core'
import { CdkPipeline, SimpleSynthAction } from '@aws-cdk/pipelines'
import 'source-map-support/register'

export class MyStack extends Stack {
  constructor(scope: cdk.Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    new CfnOutput(this, `${id}Output`, {
      value: `${id}Value`,
    })
  }
}

class MyApplication extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    super(scope, id, props)

    // Stacks in different regions
    new MyStack(this, 'MyStack1')
    new MyStack(this, 'MyStack2', { env: { region: 'ca-central-1' } })
  }
}

class MyPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    const sourceArtifact = new codepipeline.Artifact()
    const cloudAssemblyArtifact = new codepipeline.Artifact()

    const pipeline = new CdkPipeline(this, 'Pipeline', {
      crossAccountKeys: false, // 👈 Changing this to true will cause synth to fail
      cloudAssemblyArtifact,
      sourceAction: new codepipeline_actions.GitHubSourceAction({
        actionName: 'GitHub',
        output: sourceArtifact,
        oauthToken: SecretValue.secretsManager('GITHUB_TOKEN_NAME'),
        owner: 'OWNER',
        repo: 'REPO',
        branch: 'main',
      }),

      synthAction: SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        buildCommand: 'npm run build',
      }),
    })

    pipeline.addApplicationStage(new MyApplication(this, 'Prod', { env: { region: 'us-east-2' } }))
  }
}

const app = new App()
new MyPipelineStack(app, 'MyPipelineStack', { env: { account: '111111111111', region: 'us-east-2' } })
```

### What did you expect to happen?

Synth to succeed, and the pipeline to deploy the stacks to multiple regions.

### What actually happened?

Synth failed with error.

### Environment

  - **CDK CLI Version  :** 1.87.1
  - **Framework Version:** 1.87.1
  - **Node.js Version:** v12.20.1
  - **OS               :** macOS 11.1
  - **Language (Version):**  TypeScript 4.1.3

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-02-08 14:12
Duplicate of #12741. Also this I cannot reproduce :/

**Closed by rix0rrr** 2021-02-08 14:12 UTC
Labels: @aws-cdk/pipelines, bug, needs-triage
