### ISSUE TITLE
(aws-cdk): (Ability to view Nested stack changeset details through AWS Codepipeline action)

### ISSUE THREAD

**Issue by jeetjain2284** [aws/aws-cdk#29571] opened 2024-03-21 17:07 UTC
### Describe the feature

The proposed feature aims to enhance the functionality of the AWS CDK API, specifically the **_CloudFormationCreateReplaceChangeSetAction_** within CodePipeline. The feature request seeks to introduce the capability to review changesets for nested stacks before applying them.

### Use Case

Enhance the functionality of the AWS CDK API referenced [here](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_codepipeline_actions/CloudFormationCreateReplaceChangeSetAction.html) to support the creation of changesets for nested stacks when using the **CloudFormationCreateReplaceChangeSetAction** in CodePipeline.

Currently, when using this action, changesets are only created for the root stack, and nested stack changes are not visible. It would be beneficial to allow changesets for nested stacks to be viewable, similar to the manual creation of changesets through the AWS console. This enhancement would provide users with a comprehensive view of changes being made across all nested stacks within the application.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.133.0

### Environment details (OS name and version, etc.)

Ubuntu 22.04.2 LTS

**Comment by tim-finnigan** [comment] 2024-03-25 16:02
Hi @jeetjain2284, thanks for the feature request. However it looks like this is a duplicate of https://github.com/aws/aws-cdk/issues/15787. Please 👍 that issue and track the request there going forward.

**Closed by tim-finnigan** 2024-03-25 16:02 UTC
Labels: feature-request, investigating, @aws-cdk/aws-codepipeline
