### ISSUE TITLE
ecs-patterns: Allow reusing an existing LoadBalancer/Listener combination for multiple FargateServices

### ISSUE THREAD

**Issue by schoeneu** [aws/aws-cdk#5502] opened 2019-12-20 14:04 UTC
Currently, *LoadBalancedFargateService allows specifying a loadBalancer in its props. This can be used to configure the LB more freely.
However, it can't use an existing LB/the created LB can't be shared between multiple *LoadBalancedFargateService as the pattern always tries to add a new listener.

I'd like to have an option to use an existing LB/Listener, and only adding new targets when creating a *LoadBalancedFargateService.

### Use Case

Reuse existing ALBs. For small microservices, which are a prime use case for the pattern, having an ALB instance for every service becomes expensive.

### Proposed Solution

if a special flag is given, creation of listeners could be skipped. This would also skip creation of certificates, and raise an error if trying to reuse a listener but still trying to configure a certificate.

What would need a little more thought is how to add the rules to the existing listener.
If a hostname is configured for the LoadBalancedFargateService pattern, then a new top-prio rule could be added to route to the new target group.

In a first implementation, an error could be thrown if trying to use an existing listener without specifying a host name.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

I don't think that breaking changes would be necessary, but am happy to hear from those more familiar with the code.

---

This is a :rocket: Feature Request

**Comment by pkandasamy91** [comment] 2019-12-20 17:19
Duplicate of https://github.com/aws/aws-cdk/issues/5209

**Closed by pkandasamy91** 2019-12-20 17:19 UTC
Labels: feature-request, status/needs-triage

**Comment by schoeneu** [comment] 2019-12-24 18:49
@pkandasamy91 I disagree. #5209 is an issue with the types in the Java library. What I'm suggesting here is that the current code doesn't allow sharing an LB between multiple FargateServices, which is a completely diffenet issue. Can you please reopen this?

**Comment by pkandasamy91** [comment] 2019-12-24 19:28
@schoeneu the issue described by the user is not Java specific but rather an issue with the implementation of the construct. The fix is to allowing the IApplicationLoadBalancer to be passed in, instead of the ApplicationLoadBalancer. 

By allowing an IApplicationLoadBalancer to be passed in, you can import an existing load balancer and pass it in. Thus allowing you to share a single LB across services.

**Comment by schoeneu** [comment] 2019-12-24 19:31
@pkandasamy91 Thanks for your quick response! It seems I misunderstand something here - surely the implementation can be changed to allow IApplicationLoadBalancer, but just doing that will still leave the problem that the construct tries to add a new Listener on port 80 or 443 - which will not work when another service has already added a Listener on the same port?

**Comment by pkandasamy91** [comment] 2019-12-24 19:41
If you're looking to change the listener port, you can actually pass it in as an input prop.

**Comment by schoeneu** [comment] 2019-12-24 20:05
The feature I'm suggesting is this:

I'm looking to add additional services to the same LB via the FargateService construct, *without* changing the listener ports. A new service using an existing LB should not add a new listener, but only a new ListenerRule to a new target, selected by a Host-header listener rule.
