### ISSUE TITLE
CloudFormationInit support for LaunchTemplate

### ISSUE THREAD

**Issue by enrico-usai** [aws/aws-cdk#13351] opened 2021-03-02 19:09 UTC
Hi,

It seems to me that `CloudFormationInit` is supported for [Instances](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ec2-readme.html#configuring-instances-using-cloudformation-init-cfn-init) and for [ASG](https://github.com/aws/aws-cdk/pull/9674) but it's not yet supported for [`CfnLaunchTemplate`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.CfnLaunchTemplate.LaunchTemplateDataProperty.html) (I didn't find `init` parameter there).

I'd like to add `CloudFormationInit.from_config_sets` to a `CfnLaunchTemplate`, as requested in https://github.com/aws/aws-cdk/issues/11021 
How can I do it?

Thanks

**Comment by peterwoodworth** [comment] 2021-08-17 22:38
Hey @enrico-usai,

Sorry for the long response time here. Unfortunately, there is no way to use the `CloudFormationInit` class with a Launch Template. You'll have to submit a feature request if you'd like to be able to do this with the `LaunchTemplate` class. 
If you need to be able to use cfn-init for the launch template, you'll have to find a way to workaround that. I'm not too sure what the best workaround (if there are any) would be, but I can research that if you want.

**Comment by enrico-usai** [comment] 2021-08-18 10:36
Hi @peterwoodworth thanks for your answer.
I'm currently using the workaround of adding `CloudFormation::Init` as a raw metadata:
```python
my_launch_template = ec2.CfnLaunchTemplate(
   self,
   "MyLaunchTemplate",
   launch_template_data=ec2.CfnLaunchTemplate.LaunchTemplateDataProperty(
   [...]

    cfn_init = {
       "configSets": {
            "default": [
                "deployConfigFiles",
                "chefPrepEnv",
                "shellRunPreInstall",
                "chefConfig",
                "shellRunPostInstall",
                "chefFinalize",
            ],
        },
        "deployConfigFiles": {
       [...]

my_launch_template.add_metadata("AWS::CloudFormation::Init", cfn_init)
```

Anyway it would be good to have it natively supported.

**Comment by peterwoodworth** [comment] 2021-08-18 16:52
@enrico-usai have you been successfully deploying and using this workaround @enrico-usai?

**Comment by enrico-usai** [comment] 2021-08-20 08:20
I know about that comment but I didn't have any alternative.

Yes the workaround is working correctly, we're using it for AWS ParallelCluster: https://github.com/aws/aws-parallelcluster/blob/develop/cli/src/pcluster/templates/cluster_stack.py#L1174

**Comment by peterwoodworth** [comment] 2021-09-02 20:16
Converted this into a feature request, I can try to submit a PR for this at some point.

**Comment by peterwoodworth** [comment] 2021-12-28 00:16
Closing as duplicate of https://github.com/aws/aws-cdk/issues/6734

**Closed by peterwoodworth** 2021-12-28 00:16 UTC
Labels: p2, feature-request, @aws-cdk/aws-ec2, effort/medium, feature/enhancement
