### ISSUE TITLE
sagemaker: domains fail to deploy in either govcloud region.

### ISSUE THREAD

**Issue by RossMeyers** [aws/aws-cdk#31055] opened 2024-08-07 19:54 UTC
### Describe the bug

When trying to deploy a new sagemaker domain into aws-gov-west-1 or aws-gov-east-1, I get an Internal Error message. I confirmed that deploying the domain as is in us-east-1 works without issue.

### Expected Behavior

sagemaker domain is created successfully from cdk code.

### Current Behavior

domain fails to create with `Internal Failure` error.

### Reproduction Steps

1. Define domain resource
```
      const sagemakerDomain = new sagemaker.CfnDomain(this, 'SandboxDomain1', {
        authMode: 'IAM',
        domainName: 'sandbox-domain',
        defaultUserSettings: {
            executionRole: domainRole.roleArn,
        }, 
        subnetIds: [privateSubnetId0, privateSubnetId1],
        vpcId: vpcId
        });
    }
```

2. cdk synth
3. cdk deploy

### CDK CLI Version

2.151.0 

### Node.js Version

v22.5.

### OS

macos 

### Language

TypeScript

**Comment by ashishdhingra** [comment] 2024-08-07 20:30
@RossMeyers Good afternoon. Thanks for opening the issue. Could you please share the following:
- Does `cdk synth` command generates CF template successfully?
- Does error occurs after running `cdk deploy`? Is the error reported by CloudFormation?
- Is it possible to share the error log? Please try to add `-v` flag while running `cdk deploy` to emit verbose error message.

Thanks,
Ashish

**Comment by RossMeyers** [comment] 2024-08-07 20:39
@ashishdhingra  - 
1. `cdk synth` does successfully generate CF template.
2. The error is reported by CloudFormation. 
3. No, the deployment was never working in either Govcloud Region, only to `us-east-1`.
4. I don't see anything new when asking `-v`:
```
SandboxSagemakerStack | 1/3 | 4:38:16 PM | CREATE_IN_PROGRESS   | AWS::SageMaker::Domain | SandboxDomain1 
SandboxSagemakerStack | 1/3 | 4:38:17 PM | CREATE_FAILED        | AWS::SageMaker::Domain | SandboxDomain1 Internal Failure
SandboxSagemakerStack | 1/3 | 4:38:17 PM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | SandboxSagemakerStack The following resource(s) failed to create: [SandboxDomain1]. Rollback requested by user.
[16:38:26] Stack SandboxSagemakerStack has an ongoing operation in progress and is not stable (ROLLBACK_IN_PROGRESS)
[16:38:31] Stack SandboxSagemakerStack has an ongoing operation in progress and is not stable (ROLLBACK_IN_PROGRESS)
[16:38:37] Stack SandboxSagemakerStack has an ongoing operation in progress and is not stable (ROLLBACK_IN_PROGRESS)
```

**Comment by ashishdhingra** [comment] 2024-08-07 20:56
@RossMeyers Thanks for your response. The same CDK stack works fine in `us-east-1` region but fails to deploy in GovCloud region. Since `cdk synth` runs fine and Internal Failure is returned by CloudFormation, so most likely the error is not on the CDK side. To troubleshoot further:
- Please refer https://repost.aws/knowledge-center/cloudformation-internal-failure-error and help isolate the exact error in by examining CloudTrail logs, is any.
- Share the minimal self-contained CDK code to reproduce the issue.
- If possible, share the synthesized CDK stack on the above self-contained code (with sensitive information removed)

Thanks,
Ashish

**Comment by RossMeyers** [comment] 2024-08-10 14:20
@ashishdhingra 

1. I am not seeing anything in CloudTrail that points to more detail on the error. 
2. I have attached the CFN output for the supporting network stack and sagemaker stack where I am trying to create the domain. 

[SandboxNetworkStack.assets.json](https://github.com/user-attachments/files/16569869/SandboxNetworkStack.assets.json)
[SandboxNetworkStack.template.json](https://github.com/user-attachments/files/16569870/SandboxNetworkStack.template.json)
[SandboxSagemakerStack.assets.json](https://github.com/user-attachments/files/16569872/SandboxSagemakerStack.assets.json)
[SandboxSagemakerStack.template.json](https://github.com/user-attachments/files/16569873/SandboxSagemakerStack.template.json)

**Comment by ashishdhingra** [comment] 2024-08-14 17:06
Created internal ticket with CloudFormation team: P148328805

**Comment by ashishdhingra** [comment] 2024-10-09 16:36
Ticket to Sagemaker team: V1490394553

**Comment by ashishdhingra** [comment] 2024-10-09 16:37
Closing this issue since assistance is awaited from Sagemaker team.

**Closed by ashishdhingra** 2024-10-09 16:37 UTC
Labels: bug, p2, effort/medium, @aws-cdk/aws-sagemaker
