### ISSUE TITLE
aws_appsync.AuthorizationConfig does not support AWS_IAM

### ISSUE THREAD

**Issue by mostafafarzane** [aws/aws-cdk#6849] opened 2020-03-19 22:14 UTC
I do not see a way to set default_authorization of AuthorizationConfig to AWS_IAM.
I am using aws_cdk:1.30 in python.

**Comment by 0xdevalias** [comment] 2020-04-02 06:35
dupe of https://github.com/aws/aws-cdk/issues/6772

**Comment by MrArnoldPalmer** [comment] 2020-04-07 16:44
Closing in favor of #6772

**Closed by MrArnoldPalmer** 2020-04-07 16:44 UTC
Labels: feature-request, needs-triage, package/appsync
