### ISSUE TITLE
(golang): cdk CLI cmds embedded into binary

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-cdk#17972] opened 2021-12-11 22:30 UTC
### Description

Currently when creating a cdk application in golang, you write the code in golang and then use the cdk CLI to synthesize the go code. This requires two dependencies at deployment time and could be a smoother experience wrt to CLI versioning w/ the CDK application stack code. 

### Use Case

I'd like to be able to distribute a single go binary to a CI/CD system to synthesize a cdk go application without installing the CDK CLI separately which is cumbersome since I need to install npm. 

### Proposed Solution

Embed the CDK CLI into the go binary so that I can `go build ./... -o mycdk` and be able to: `./mycdk synth`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment] 2021-12-24 13:19
The CDK framework needs Node as well, so it's not just the CLI. 

Ultimately a duplicate of https://github.com/aws/jsii/issues/91

**Closed by rix0rrr** 2021-12-24 13:19 UTC
Labels: feature-request, package/tools, needs-triage
