### ISSUE TITLE
(core): CDK analytics string with a tiny different between Mac and Linux

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#16298] opened 2021-08-31 16:05 UTC
I am seeing a tiny difference in the CDK analytics string between Mac and Linux.

Mac: 

```
-------------------------------v
Mac   v2:deflate64:H4sIAAAAAAAAEzWOzQrCMBCEn8V7um1U8Kot9Cz1CeJ2LelPAtlEkZB3t2nxNN/ADDMS5LGC6nBVHy6wn8qI1hHEh1c4iRsz+RUHbQbRWMPeBfSieZmO2AaHlEQuxlktz15BbINBr63JkT8nodUCsbMzbc2sdztr/Ga7UxJ8KlReY9hGVw91wIl8rZhSEsb2BCOXb3kGeVkfj6x14YLxeiHodv0BEsSu7c4AAAA=`
Linux v2:deflate64:H4sIAAAAAAAAAzWOzQrCMBCEn8V7um1U8Kot9Cz1CeJ2LelPAtlEkZB3t2nxNN/ADDMS5LGC6nBVHy6wn8qI1hHEh1c4iRsz+RUHbQbRWMPeBfSieZmO2AaHlEQuxlktz15BbINBr63JkT8nodUCsbMzbc2sdztr/Ga7UxJ8KlReY9hGVw91wIl8rZhSEsb2BCOXb3kGeVkfj6x14YLxeiHodv0BEsSu7c4AAAA=
-------------------------------^
```

Weirdly, they both translate to this:

```
Mac   1.120.0!@aws-cdk/{core.{Stack,AssetStaging,Construct,CfnResource},aws-{lambda.{Function,CfnFunction},iam.{Role,CfnRole,Policy,CfnPolicy},s3-assets.Asset,s3.BucketBase}},node.js/v14.17.0!jsii-runtime.Runtime%`
Linux 1.120.0!@aws-cdk/{core.{Stack,AssetStaging,Construct,CfnResource},aws-{lambda.{Function,CfnFunction},iam.{Role,CfnRole,Policy,CfnPolicy},s3-assets.Asset,s3.BucketBase}},node.js/v14.17.0!jsii-runtime.Runtime%`
```

### Reproduction Steps

See this [build](https://github.com/eladb/cdk-pipelines-github-example/runs/3474462120)

### What did you expect to happen?

Since all versions are the same, I'd expect the same analytics string.

### What actually happened?

There's a diff.

### Environment

  - **CDK CLI Version  :** 1.119.0
  - **Framework Version:** 1.119.0
  - **Node.js Version:** v14.17.0
  - **OS               :** Mac/Linux
  - **Language (Version):** all

### Other

I suspect this might be related to hashing/gzip behavior that's different between the two systems.

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment] 2021-08-31 16:07
Duplicate of #15322.

**Closed by njlynch** 2021-08-31 16:07 UTC
Labels: bug, @aws-cdk/core, needs-triage
