### ISSUE TITLE
(lambda-python): `requirements.txt` created in the entry folder when using Poetry

### ISSUE THREAD

**Issue by gshpychka** [aws/aws-cdk#20296] opened 2022-05-11 15:20 UTC
### Describe the bug

`lambda-python` supports `requirements.txt`, `poetry.lock` and `pipfile` to define the function dependencies. If using `poetry.lock`, a `requirements.txt` file is created in the entry folder after bundling. This is an unexpected side effect.

### Expected Behavior

`cdk synth` does not modify the contents of the function entry folder.

### Current Behavior

`requirements.txt` is created in the entry folder alongside `pyproject.toml` and `poetry.lock`.

### Reproduction Steps

Create a `PythonFunction` that points to a directory with `pyproject.toml` and `poetry.lock`. Run `cdk synth`. Inspect the contents of the directory.

### Possible Solution

Don't create files in the entry directory, or clean them up after bundling. Or better yet, do the packaging in a docker container. Unless this is already supposed to be happening?

### CDK CLI Version

2.23.0

### Framework Version

2.23.0

### Node.js Version

18.1.0

### OS

Linux

### Language

Python

### Other information

The [docs](https://github.com/aws/aws-cdk/blob/30e223333fef0b0d7f12287dab170a34e092d7fa/packages/%40aws-cdk/aws-lambda-python/README.md) mention this somewhat:

> Packaging is executed using the Packaging class, which:

> Infers the packaging type based on the files present.
> If it sees a Pipfile or a poetry.lock file, it exports it to a compatible requirements.txt file with credentials (if they're available in the source files or in the bundling container).
> Installs dependencies using pip.
> Copies the dependencies into an asset that is bundled for the Lambda package.

I believe the code that does this is here: https://github.com/aws/aws-cdk/blob/c3c4a97e65071fcab35212be82dea7b29454786f/packages/%40aws-cdk/aws-lambda-python/lib/packaging.ts#L49

**Comment by corymhall** [comment] 2022-05-16 18:23
duplicate of https://github.com/aws/aws-cdk/issues/19231

**Closed by corymhall** 2022-05-16 18:23 UTC
Labels: bug, needs-triage, @aws-cdk/aws-lambda-python
