### ISSUE TITLE
NetworkLoadBalancedFargateService > loadBalancer

### ISSUE THREAD

**Issue by tomred-net** [aws/aws-cdk#5265] opened 2019-12-01 03:31 UTC
### The Question
I am attempting to configure the NetworkLoadBalancedFargateService the configuration parameter for Cluster, VPC and domainZone all utilise interface references but the loadBalancer construct prop requires a concrete instance of a loadBalancer. Is there another way that I can set this as I have imported dependencies such as Cluster and domainZone but I cannot utilise the load balancer in the same way. 

Ideally I would be able to pass a [INetworkLoadBalancer ](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-elasticloadbalancingv2.INetworkLoadBalancer.html) which is what is returned from NetworkLoadBalancer.fromNetworkLoadBalancerAttributes. 

Can you advise if I am missing something here?

Importing is necessary as the 200 resource limit gets hit pretty quickly when you have several apps deployed and I was advised the only way around was to use NestedStacks and exports.

### Environment

  - **CDK CLI Version:** 1.18.0
  - **Module Version:** 1.18.0
  - **OS:** Windows 10 | Ubuntu
  - **Language:** Java

**Comment by pkandasamy91** [comment] 2019-12-11 18:13
@tomred-net Thanks for raising this issue. The initial usecase was to create a load balancer with custom properties and pass it in, but I do see the need for allowing imported load balancers as well. 

I will resolve this issue as a duplicate of https://github.com/aws/aws-cdk/issues/5209, but we are working on resolving this issue. Feel free to follow the status of that issue.

**Closed by pkandasamy91** 2019-12-11 18:13 UTC
Labels: feature-request, package/ecs-patterns
