### ISSUE TITLE
[aws-elasticloadbalancingv2] Imported listener `conditions` attribute is ignored

### ISSUE THREAD

**Issue by danilo-valente** [aws/aws-cdk#9643] opened 2020-08-12 16:24 UTC
This bug is related to #8328, but instead occurs only to existing (imported) listeners.

When attempting to add a rule to an **importer** listener on an application load balancer, it is not possible to specify multiple conditions with the `addTargetGroups` helper, because it ignores the conditions array of the input.

Workarounds:
- Use deprecated attributes like `hostHeader`
- Construct the new ApplicationListenerRule directly

### Reproduction Steps

Check file [application-listener.ts](https://github.com/aws/aws-cdk/blob/v1.57.0/packages/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.ts) on release v1.57.0. Look for method `addTargetGroups` of class `ImportedApplicationListener` and you will note that a `conditions` attribute is not passed to `new ApplicationListenerRule`:

```
  /**
   * Load balance incoming requests to the given target groups.
   *
   * It's possible to add conditions to the TargetGroups added in this way.
   * At least one TargetGroup must be added without conditions.
   */
  public addTargetGroups(id: string, props: AddApplicationTargetGroupsProps): void {
    checkAddRuleProps(props);

    if (props.priority !== undefined) {
      // New rule
      new ApplicationListenerRule(this, id, {
        listener: this,
        hostHeader: props.hostHeader,
        pathPattern: props.pathPattern,
        pathPatterns: props.pathPatterns,
        priority: props.priority,
        targetGroups: props.targetGroups,
      });
    } else {
      throw new Error('Cannot add default Target Groups to imported ApplicationListener');
    }
  }
```

### What did you expect to happen?

To properly use `conditions` attribute of a target group on existing listeners.

### What actually happened?

`conditions` is ignored and if no other attribute (like `hostHeader`) is provided it throws an error: `At least one of 'conditions', 'hostHeader', 'pathPattern' or 'pathPatterns' is required when defining a load balancing rule.`.

### Environment

  - **CLI Version      :** 1.57.0
  - **Framework Version:** 1.57.0
  - **Node.js Version:** 14.4.0
  - **OS               :** 10.14.5
  - **Language (Version):** 3.9.6

### Other

This bug is related to #8328 and was probably left behind by #8385.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-08-17 09:16
Duplicate of https://github.com/aws/aws-cdk/issues/9262

**Closed** 2020-08-18 17:26 UTC
Labels: @aws-cdk/aws-elasticloadbalancingv2, bug, duplicate, effort/small, good first issue, p1
