### ISSUE TITLE
(cognito): better support for using SES for email delivery when creating a Cognito user pool

### ISSUE THREAD

**Issue by natesilva** [aws/aws-cdk#12367] opened 2021-01-06 04:53 UTC
The curated Cognito construct (`@aws-cdk/aws-cognito`) should support using SES for email in addition to the default setting where Cognito sends email.

### Use Case

In the AWS Console, there is a prominent warning that having Cognito send emails goes against best practice, and suggests switching to SES.

![Warning message shown in the AWS Console](https://user-images.githubusercontent.com/160467/103728336-8fb8bb00-4f92-11eb-866d-ff86b4e44fa0.png)
_User pool created using @aws-cdk/aws-cognito_

### Proposed Solution

The `cognito.UserPoolProps` should support the `emailSendingAccount` and `sourceArn` properties from CloudFormation.

### Other

Workaround: The workaround is to use [CfnUserPool](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.CfnUserPool.html) (the “Level 1 AWS CloudFormation-only construct”).

---

This is a :rocket: Feature Request

**Comment by straygar** [comment] 2021-01-06 09:12
I think this is a duplicate of: https://github.com/aws/aws-cdk/issues/6768

**Comment by nija-at** [comment] 2021-01-07 15:49
Duplicate of https://github.com/aws/aws-cdk/issues/6768

**Closed by nija-at** 2021-01-07 15:49 UTC
Labels: @aws-cdk/aws-cognito, feature-request, needs-triage
