### ISSUE TITLE
(iot): TopicRule action for OpenSearch in AWS IoT

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk#17702] opened 2021-11-25 12:08 UTC
### Description

The CDK has no support to writes data to an Amazon OpenSearch Service via AWS IoT Rule.

### Use Case

Adding the action that writes data to an Amazon OpenSearch Service to AWS IoT topic rule.

### Proposed Solution

Implementing action class.

Probably, following PRs help coding.

- https://github.com/aws/aws-cdk/pull/17503
- https://github.com/aws/aws-cdk/pull/17466
- https://github.com/aws/aws-cdk/pull/17307

### Other information

Follofing documentation will be help.

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-opensearchaction.html

It will be good first issue for learning implement feature in CDK!

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ConorShirren** [comment] 2022-11-22 13:09
Hi 🙂 Looking to contribute here if this feature is still required? Looks like the issue is ~12 months old.

**Comment by skinny85** [comment] 2022-11-22 17:35
@ConorShirren go ahead - looks like the only movement on this issue was https://github.com/aws/aws-cdk/pull/21823, which was closed by its author without a review months ago.

**Comment by ConorShirren** [comment] 2022-11-22 18:57
@skinny85 Thanks for getting back to me! 
Been looking at the API Ref for the OpenSearch Service and there doesn't seem to be any action that allows data to be written to an OpenSearch Domain: [API Docs Here](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_Operations.html)
There are options to `CreateDomain` and `CreatePackage` - but they don't seem applicable here?

**Comment by skinny85** [comment] 2022-11-22 19:29
The PR description contains the link to the relevant CloudFormation docs (specifically, https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-opensearchaction.html).

**Comment by GavinZZ** [comment] 2024-01-15 22:39
Going to give this an attempt to add support for OpenSearch action in IoT.

**Closed** 2024-01-23 01:52 UTC
Labels: good first issue, p2, feature-request, effort/small, @aws-cdk/aws-iot, feature/service-integration
