### ISSUE TITLE
ec2: VPC recreation will fail due to missing NAT property "dependsOn IGW"

### ISSUE THREAD

**Issue by max-allan-surevine** [aws/aws-cdk#18434] opened 2022-01-14 14:34 UTC
### What is the problem?

Deploy a VPC with a NAT gateway.
Update the VPC definition so that it needs to create a new VPC and attempt to redeploy.
The deploy will fail to create a NAT gateway because the Internet gateway is not listed as a dependency.

### Reproduction Steps

Deploy this template and then change the CIDR to 10.2.0.0/16. Deploy the changed template.
```
import * as cdk from '@aws-cdk/core';
import * as ec2 from '@aws-cdk/aws-ec2';
export class VpcbugStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const vpc = new ec2.Vpc(this, 'VPC', {
            cidr: "10.1.0.0/16",
            maxAzs: 2,
            subnetConfiguration: [
                {
                    cidrMask: 24,
                    name: 'ingress1',
                    subnetType: ec2.SubnetType.PRIVATE_WITH_NAT
                },
                {
                    cidrMask: 24,
                    name: 'public',
                    subnetType: ec2.SubnetType.PUBLIC,
                }
            ],
            natGateways: 1,
         });
  }
}
```
    
    

    
  
  

### What did you expect to happen?

The new VPC to be created with an IGW and NAT and the old one to be deleted.

### What actually happened?

An error :
NatGateway nat-0022a2... is in state failed and hence failed to stabilize. Detailed failure message: Network vpc-0b3e1... has no Internet gateway attached

### CDK CLI Version

1.133.0

### Framework Version

1.139.0

### Node.js Version

16.3.0

### OS

OSX

### Language

Typescript

### Other information

In the resulting Cloudformation, the NAT GW should have a `dependsOn: !Ref IGWAttachment` inserted so that the IGW is connected before the NAT created.

**Comment by max-allan-surevine** [comment] 2022-01-14 14:46
Oh, it is worse than that. You can't update the IGW because there is an EIP allocated to the old network. Maybe this is a CFN bug that it shoud create a new IGW not update the old one...

**Comment by njlynch** [comment] 2022-02-02 16:02
Thanks for the bug report. We're marking this as "needs CloudFormation" attention. Have you found a reasonable workaround you can post for others who might be similarly impacted?

**Comment by max-allan-surevine** [comment] 2022-02-03 13:56
Not really. I think I tore it all down and rebuilt in the end.

**Comment by peterwoodworth** [comment] 2022-06-21 22:26
If we'd like to see support for this - I recommend opening an issue in the [CloudFormation coverage roadmap](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues) to gain visibility from the CFN team. Thanks!

**Comment by MrArnoldPalmer** [comment] 2023-01-27 21:09
This looks like a duplicate of https://github.com/aws/aws-cdk/issues/16869. Closing this in favor of tracking there.

**Closed by MrArnoldPalmer** 2023-01-27 21:09 UTC
Labels: bug, p2, @aws-cdk/aws-ec2, effort/small, needs-cfn
