### ISSUE TITLE
ECS - Allow customisation of container name in Load-Balanced-FargateService

### ISSUE THREAD

**Issue by DavidChristiansen** [aws/aws-cdk#2639] opened 2019-05-25 23:31 UTC
Currently, the taskdefinition defines the container name as 'web',  It would be nice to override this property via configuration.

Example
```ts
const container = taskDefinition.addContainer('web', {
      image: props.image,
      logging: optIn ? this.createAWSLogDriver(this.node.id) : undefined,
      environment: props.environment
    });
```

See - https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/load-balanced-fargate-service.ts#L97

**Comment by pkandasamy91** [comment] 2019-08-06 04:16
Container name is a prop in LoadBalancedServiceBaseProps. @DavidChristiansen can this be resolved?

**Comment by pkandasamy91** [comment] 2019-08-06 17:35
Duplicate of https://github.com/aws/aws-cdk/issues/2751 and this issue is resolved.

**Closed by pkandasamy91** 2019-08-06 17:35 UTC
Labels: feature-request, service/ecs
