### ISSUE TITLE
ClassCastException when attempting to iterate through IVpc.privateSubnets/publicSubnets list

### ISSUE THREAD

**Issue by astuckey123** [aws/aws-cdk#5279] opened 2019-12-03 07:06 UTC
IVpc.getPrivateSubnets() and IVpc.getPublicSubnets() should return: 
`List<ISubnet>`

However on any attempt to iterate through this list, the following exception ocurrs:
```
Exception in thread "main" java.lang.ClassCastException: software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet
```

### Reproduction Steps

With CDK version 1.15.0, this issue does not occur.

- Fresh project (cdk init --language java)
- Set environment variables for CDK_DEFAULT_ACCOUNT & CDK_DEFAULT_REGION
- Modify existing sample code to the below:

```
package com.myorg;

import software.amazon.awscdk.core.App;

import java.util.Arrays;
import software.amazon.awscdk.core.Environment;
import software.amazon.awscdk.core.StackProps;
public class BugApp {
    public static void main(final String[] args) {
        App app = new App();

        new BugStack(app, "BugStack", StackProps.builder()
                .env(Environment.builder()
                        .account(System.getenv("CDK_DEFAULT_ACCOUNT"))
                        .region(System.getenv("CDK_DEFAULT_REGION"))
                        .build())
                .build());

        app.synth();
    }
}
```

```
package com.myorg;

import software.amazon.awscdk.core.Construct;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.core.StackProps;
import software.amazon.awscdk.services.ec2.IVpc;
import software.amazon.awscdk.services.ec2.Vpc;
import software.amazon.awscdk.services.ec2.VpcLookupOptions;

public class BugStack extends Stack {
    public BugStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public BugStack(final Construct scope, final String id, final StackProps props) {
        super(scope, id, props);

        // The code that defines your stack goes here
        String vpcId = "vpc-xxxxxxxxxx";
        IVpc vpc = Vpc.fromLookup(this,"VPC", VpcLookupOptions.builder()
                .vpcId(vpcId)
                .build());

        vpc.getPrivateSubnets().forEach(System.out::println);

    }
}
```

### Error Log

```
Exception in thread "main" java.lang.ClassCastException: software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet
```

### Environment

  - **CLI Version      :** 1.18.0 (anything > 1.15.0 has this issue)
  - **Framework Version:** 1.18.0 (pom.xml CDK import version)
  - **OS               :** Manjaro Linux
  - **Language         :** 1.8.0_231

### Other

```
$ cdk ls
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project bug: An exception occured while executing the Java class. software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project bug: An exception occured while executing the Java class. software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:339)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.ClassCastException: software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.ec2.ISubnet
    at java.util.ArrayList.forEach (ArrayList.java:1257)
    at java.util.Collections$UnmodifiableCollection.forEach (Collections.java:1082)
    at com.myorg.BugStack.<init> (BugStack.java:24)
    at com.myorg.BugApp.main (BugApp.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Subprocess exited with error 1
```

--- 

This is :bug: Bug Report

**Comment by PurdueHuayuZhou** [comment] 2020-01-03 22:25
Also got a similar issue while using CDK 1.18.0

Exception in thread "main" java.lang.ClassCastException: software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to software.amazon.awscdk.services.s3.IBucket

**Comment by SomayaB** [comment] 2020-01-15 21:14
Hi @astuckey123 and @PurdueHuayuZhou, thanks for reporting this. We will update this issue when there is movement.

**Comment by RomainMuller** [comment] 2020-01-16 12:07
The cause of this issue has been identified & is tracked at aws/jsii#1196. Thank you very much for reporting this problem, and sorry for not having given this traction earlier!

**Comment by pkspks** [comment] 2020-02-09 22:36
@RomainMuller , The JSII issue seems to be merged. Can we hope to see this fixed in CDK soon? It's blocking us from upgrading.

**Comment by pkspks** [comment] 2020-02-11 02:50
This also seems to be happening with #tryFindChild calls. 

`Exception in thread "main" java.lang.ClassCastException: class software.amazon.awscdk.core.Resource$Jsii$Proxy cannot be cast to class software.amazon.awscdk.services.kms.IKey`

Not sure if there is any other way to get a resource in the template.

**Comment by rix0rrr** [comment] 2020-04-28 12:44
Fix has long since been released

**Closed by rix0rrr** 2020-04-28 12:44 UTC
Labels: bug, in-progress, language/java, p1, package/vpc
