### ISSUE TITLE
npm error trying to init in node 15.0.1

### ISSUE THREAD

**Issue by mindejulian** [aws/aws-cdk#11238] opened 2020-11-01 07:21 UTC
Initializing a new project `cdk init app --language typescript` fails on macOS 10.15.7 using node 15.0.1 and npm 7.0.3 with error "Cannot read property 'matches' of undefined". 

### Reproduction Steps

Running node 15.0.1 and npm 7.0.3 on macOS 10.15.7
`npm i -g aws-cdk`
`cd empty-folder`
`cdk init app --language typescript`

### What did you expect to happen?

Project initialised without errors

### What actually happened?

Output error "Cannot read property 'matches' of undefined" in console, and the following in debug log
 ```
291 verbose stack TypeError: Cannot read property 'matches' of undefined
291 verbose stack     at Arborist.[canPlaceDep] (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1284:15)
291 verbose stack     at Arborist.[placeDep] (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:36)
291 verbose stack     at Arborist.[placeDep] (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1212:41)
291 verbose stack     at /Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:766:46
291 verbose stack     at Array.map (<anonymous>)
291 verbose stack     at Arborist.[buildDepStep] (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:766:8)
291 verbose stack     at async Arborist.buildIdealTree (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:202:7)
291 verbose stack     at async Promise.all (index 1)
291 verbose stack     at async Arborist.reify (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:121:5)
291 verbose stack     at async install (/Users/julianminde/.nvm/versions/node/v15.0.1/lib/node_modules/npm/lib/install.js:40:5)
292 verbose cwd /Users/julianminde/aws/hello-cdk
293 verbose Darwin 19.6.0
294 verbose argv "/Users/julianminde/.nvm/versions/node/v15.0.1/bin/node" "/Users/julianminde/.nvm/versions/node/v15.0.1/bin/npm" "install"
295 verbose node v15.0.1
296 verbose npm  v7.0.3
297 error Cannot read property 'matches' of undefined
298 verbose exit 1
```

### Environment

  - **CLI Version      :** aws-cli/2.0.56 Python/3.7.4 Darwin/19.6.0 exe/x86_64
  - **Framework Version:** 1.71.0 (build 953bc25) 
  - **Node.js Version:** 15.0.1
  - **OS               :** macOS 10.15.7
  - **Language (Version):** 

### Other

I still fear this being a problem with my environment, however I have tried installing node both from brew and using nvm with the same results, and when I use nvm with node version 14.15.0 it seems to work fine.

--- 

This is :bug: Bug Report

**Comment by sannies** [comment] 2020-11-01 11:19
I ran into the same bug. After ` npm install -g npm@latest` I could no longer reproduce. Perhaps you want to give it a try.

**Comment by pgollucci** [comment] 2020-11-01 17:10
This is an npm 7.x issue. npm@latest is still on 6.x

**Comment by SomayaB** [comment] 2020-11-02 20:11
Hi @mindejulian, it looks like this is an issue with npm like @pgollucci mentioned. I'm seeing a few bug reports on the npm repo: 
- https://github.com/npm/cli/issues/2080 
- https://github.com/npm/cli/issues/1989

Hopefully this issue gets resolved soon. In the meantime, I would use 6.x versions as mentioned above.
I will close this issue since it's not actionable from the CDK side.

**Closed by SomayaB** 2020-11-02 20:11 UTC
Labels: guidance, needs-triage, third-party

**Comment by fc** [comment] 2022-01-15 19:43
In my case, I resolved this error with:
```
nvm use 14
```
