### ISSUE TITLE
[ecs-patterns] ApplicationLoadBalancedEc2Service with httpToHttps mechanics 

### ISSUE THREAD

**Issue by logemann** [aws/aws-cdk#8775] opened 2020-06-28 21:48 UTC
In the vein of having useful patterns for every day problems, i wonder if it wouldnt be useful to have a property like **redirectToHttps: true|false**  in the properties of ApplicationLoadBalancedEc2Service.

### Use Case

I think that most of the usage patterns of ApplicationLoadBalancedEc2Service is having a internet facing LoadBalancer for something like web applications. For that, you definitely need a redirect http to https feature. 

### Proposed Solution

enhance ApplicationLoadBalancedEc2Service with the mentioned property like this:

```
ApplicationLoadBalancedEc2Service(this, "id", {
   ...
   certificate: someCert,
   redirectToHttps: true|false
});

```

With that property set, the ApplicationLoadBalancedEc2Service would also create a HTTP Listener (besides the HTTPS listener) with a RedirectAction ascociated  which looks basically like this:

```
    private createEverythingElseTo443Action(): RedirectOptions {
        return {
            protocol: "HTTPS",
            host: "#{host}",
            port: "443",
            path: "/#{path}",
            query: "#{query}"
        }
    }
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by MrArnoldPalmer** [comment] 2020-06-29 18:12
Hey there, this has been discussed a lot in a few other issues.

https://github.com/aws/aws-cdk/issues/5583 discusses how users can accomplish this today creating their own listener.

https://github.com/aws/aws-cdk/issues/8488 - tracks the implementation of some convenience property like `forceHttps` similar to what you're describing.

Gonna close this as a duplicate of #8488. Feel free to reopen if you think this includes something else.

**Closed by MrArnoldPalmer** 2020-06-29 18:12 UTC
Labels: @aws-cdk/aws-ecs-patterns, feature-request, needs-triage

**Comment by logemann** [comment] 2020-06-29 18:39
sorry for not checking if related issue exist

**Comment by MrArnoldPalmer** [comment] 2020-06-29 21:40
No worries, good to know others are wanting this! 😄
