### ISSUE TITLE
Pipeline tries to recreate already existing KMS keys and aliases and fails

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#4374] opened 2019-10-04 10:03 UTC
When CDK creates a pipeline, it also sets up KMS encryption of the buckets it uses. If the stack subsequently is destroyed, the KMS key and alias will remain as they have a minimum expiration time of 7 days. Then, if the stack is redeployed, an error will be raised as the KSM key already exists. The only solution AFAIK is to change the logical name of the pipeline from 'Pipeline' to 'Pipeline1' or similar. This clearly is problematic.

Is this the intended behaviour? It seems as if CDK should try to create new KMS keys and aliases only if they don't already exist, re-using them if possible.

### Reproduction Steps

1. Create a pipeline. It will use some kind of bucket which CDK will create, plus KMS infrastructure (master key, alias)
2. Deploy it.
3. Destroy it.
4. Deploy it again - it will bomb.

### Error Log

```
 21/32 | 11:47:01 | CREATE_IN_PROGRESS   | AWS::S3::Bucket             | Pipeline1/ArtifactsBucket (Pipeline1ArtifactsBucketB1DD85BA) Resource creation Initiated
 21/32 | 11:47:02 | CREATE_IN_PROGRESS   | AWS::KMS::Alias             | Pipeline1/ArtifactsBucketEncryptionKeyAlias (Pipeline1ArtifactsBucketEncryptionKeyAlias22E569FB) 
 22/32 | 11:47:05 | CREATE_FAILED        | AWS::KMS::Alias             | Pipeline1/ArtifactsBucketEncryptionKeyAlias (Pipeline1ArtifactsBucketEncryptionKeyAlias22E569FB) alias/codepipeline-pipelinestaginguspipeline19f36b130 already exists
        new Alias (/Users/peter.bengtson/Projects/xxxxxxxx/ts.out/cdk/node_modules/@aws-cdk/aws-kms/lib/alias.ts:153:22)
        \_ new Pipeline (/Users/peter.bengtson/Projects/xxxxxxxx/ts.out/cdk/node_modules/@aws-cdk/aws-codepipeline/lib/pipeline.ts:233:7)
        \_ new PipelineStack (/Users/peter.bengtson/Projects/xxxxxxxx/src/cdk/stacks/pipeline-stack.ts:132:22)
        \_ Object.<anonymous> (/Users/peter.bengtson/Projects/xxxxxxxx/src/cdk/email-connect.ts:85:32)
        \_ Module._compile (internal/modules/cjs/loader.js:936:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
        \_ Module.load (internal/modules/cjs/loader.js:790:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:703:12)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
        \_ internal/main/run_main_module.js:17:11
 23/32 | 11:47:05 | CREATE_FAILED        | AWS::S3::Bucket             | Pipeline1/ArtifactsBucket (Pipeline1ArtifactsBucketB1DD85BA) Resource creation cancelled
```

### Environment

  - **CLI Version      : aws-cli/1.16.208 Python/2.7.10 Darwin/18.7.0 botocore/1.12.198
  - **Framework Version: 1.9.0 (and later)
  - **OS               :Mac
  - **Language         :TS

--- 

This is :bug: Bug Report

**Comment by PeterBengtson** [comment] 2019-10-04 11:36
The problem is aggravated by the fact that there is no way in CDK to specify the KMS key or aliases, thus they can't be put in, say, SSM. We're entirely in the hands of CDK's extra abstractions here.

**Comment by PeterBengtson** [comment] 2019-10-04 11:38
Also, should deployment fail _for any reason_, the stacks and their associated buckets must be deleted, then the pipeline logical name changed, synthesis must be redone before the stack can be redeployed. Should it fail again – rinse and repeat.

**Comment by skinny85** [comment] 2019-10-04 15:15
This is a duplicate of #4336 . Let's move the conversation there.

Just one point:

> The problem is aggravated by the fact that there is no way in CDK to specify the KMS key or aliases for the Pipeline construct, thus KMS ids can't be put in, say, SSM. We're entirely in the hands of CDK's extra abstractions here.

That is absolutely not the case. You have full control over both the Key, and the Alias:

```ts
const key = new kms.Key(this, 'Key');
const myArtifactBucket = new s3.Bucket(this, 'Bucket', {
  encryptionKey: key, // no Alias here!
  // ...
});

const pipeline = new codepipeline.Pipeline(this, 'Pipeline', {
  artifactBucket: myArtifactBucket.
  // ...
});
```

**Closed by skinny85** 2019-10-04 15:15 UTC
Labels: bug, status/needs-triage
