### ISSUE TITLE
(autoscaling): EbsDeviceVolumeType.IO2 is not a valid CloudFormation value

### ISSUE THREAD

**Issue by jumic** [aws/aws-cdk#16027] opened 2021-08-12 21:12 UTC
AWS::AutoScaling::LaunchConfiguration BlockDevice supports the following values for property VolumeType (see [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-template.html#cfn-as-launchconfig-blockdev-template-volumetype)):

> Valid Values: standard | io1 | gp2 | st1 | sc1 | gp3

In CDK, values IO2 is also defined as a possible value in [enum EbsDeviceVolumeType](https://github.com/aws/aws-cdk/blob/bb5d5874098b4b1047a29b6697e5e3a65f349ff0/packages/%40aws-cdk/aws-autoscaling/lib/volume.ts#L188).

However, this value is not valid at the moment and should be removed.

### Reproduction Steps

```ts
const vpc = ec2.Vpc.fromLookup(this, 'MyVPC', {
  isDefault: true,
})

new autoscaling.AutoScalingGroup(this, 'MyAutoScalingGroup', {
  blockDevices: [
    {
      deviceName: '/dev/sda1',
      volume: {
        ebsDevice: {
          deleteOnTermination: true,
          volumeType: autoscaling.EbsDeviceVolumeType.IO2,
        }
      },
    }
  ],
  vpc,
  instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL),
  machineImage: new ec2.AmazonLinuxImage(),
});
```

### What did you expect to happen?

Deployment of AutoScalingGroup should be successfully.

### What actually happened?

Deployment failed with error:

> io2 is invalid. Valid volume types are: standard, io1, gp2, st1, sc1, gp3 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: e5dd0928-b959-4e36-beed-91b7b2ba1f6a; Proxy: null)

### Environment

  - **CDK CLI Version  : 1.118.0
  - **Framework Version: 1.118.0
  - **Node.js Version: v14.16.0
  - **OS               :  macOS
  - **Language (Version):  all

### Other

Originally mentioned in issue #14685. I will submit a short PR and remove value IO2 as proposed for GP3 in the original issue.

--- 

This is :bug: Bug Report

**Comment by peterwoodworth** [comment] 2021-08-12 21:48
Thanks for the submission! But this isn't something we want to do. The EBSDeviceVolumeType is also used for [an EC2 Volume](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Volume.html#volumetype) which [does support io2](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#cfn-ec2-ebs-volume-volumetype)

**Comment by peterwoodworth** [comment] 2021-08-12 21:50
Looks like Neta didn't catch this when she labelled the `gp3` issue as a p1, good thing no one ended up making a PR for that!

**Comment by jumic** [comment] 2021-08-13 17:00
@peterwoodworth It's fine for me to keep this value. Maybe it will be added to Auto Scaling in the feature, too.

There's one thing I want to mention if somebody has a look at this issue later:
In my opinion, it is possible to support different volume types in autoscaling and ec2. Enum EbsDeviceVolumeType exists twice in CDK, is available in [autoscaling](https://github.com/aws/aws-cdk/blob/1b29ca8e8805fe47eb534d2f564d18ca297e956f/packages/%40aws-cdk/aws-autoscaling/lib/volume.ts#L174) and [ec2](https://github.com/aws/aws-cdk/blob/1b29ca8e8805fe47eb534d2f564d18ca297e956f/packages/%40aws-cdk/aws-ec2/lib/volume.ts#L170) as separate enums. Therefore, it should be possible to add a new volume type only in the module where it is supported.

**Comment by peterwoodworth** [comment] 2021-08-13 17:13
Thanks for pinging me about this @jumic, I didn't catch that there are two different enums. I'm looking back into the PR which merged the change right now, that PR was probably a mistake

**Comment by peterwoodworth** [comment] 2021-08-13 17:22
There's no mention in any of the original issues about Autoscaling, and Autoscaling has never supported io2. The PR seems to have just included the autoscaling enum as well even though autoscaling doesn't support io2 

I wonder if the Autoscaling volume type lags behind the ec2 volume type. In other words, I wonder if io2 will be supported soon for Autoscaling like gp3 was.

For now, I can confirm your PR is safe to merge. I'll look into if io2 will be an option for autoscaling and if I can't find anything about that I will go ahead and merge your change :)

**Closed** 2021-09-07 14:08 UTC
Labels: bug, p2, @aws-cdk/aws-autoscaling, effort/small
