### ISSUE TITLE
aws_wafv2: Unable to add certain IP Addresses to CfnIPSet

### ISSUE THREAD

**Issue by tomeszmh** [aws/aws-cdk#20003] opened 2022-04-21 06:35 UTC
### Describe the bug

I tried to add IP addresses to allowed rules in WAF, but we have issues with 4 IPs. If I remove these from the IP set everything is working properly, but with these the response during cdk deploy is `"WAFInvalidParameterException: Error reason: The parameter contains formatting that is not valid., field: IP_ADDRESS, parameter: 195.178.188.66/29"`. It's strange that another /29 subnet is valid for WAF. I tried to add from AWS console, but got the same result. All IPs are valid subnets. 
Invalid IPs: "91.183.105.163/29""94.79.144.98/29", "94.79.134.162/29","195.178.188.66/29"

### Expected Behavior

Able to add all of our valid IP addresses.

### Current Behavior

```sh
WAFInvalidParameterException: Error reason: The parameter contains formatting that is not valid., field: IP_ADDRESS, parameter: 195.178.188.66/29
```

### Reproduction Steps

```python
import aws_cdk.core
from aws_cdk.aws_wafv2 import CfnWebACL, CfnIPSet, CfnRuleGroup


class Waf(CfnWebACL):
    # TODO: "91.183.105.163/29""94.79.144.98/29", "94.79.134.162/29","195.178.188.66/29" Cannot add these IPs to WAF Ipset (InvalidParameterException)

    def __init__(self, scope_: aws_cdk.core.Construct) -> None:
        ipv4_set = CfnIPSet(scope_=scope_, ip_address_version='IPV4', scope="REGIONAL",
                            id="allowed-ipv4-addresses",
                            addresses=["212.85.78.240/28", "62.84.200.16/29", "80.169.184.136/29", "195.178.188.66/29","158.174.162.104/30",
                                       "158.174.216.244/30", "83.145.205.32/32", "194.251.122.24/29",
                                       "88.116.109.68/30", "213.61.234.0/28", "217.110.197.224/28",
                                       "62.96.146.96/29"])

        super().__init__(scope_=scope_, id='waf-appsync',
                         default_action=CfnWebACL.DefaultActionProperty(block={}),
                         scope='REGIONAL',
                         visibility_config=CfnWebACL.VisibilityConfigProperty(
                             cloud_watch_metrics_enabled=True,
                             sampled_requests_enabled=True,
                             metric_name='test',
                         ), name='test1',
                         rules=[CfnWebACL.RuleProperty(name="whitelist-ipv4-rule",
                                                       priority=0,
                                                       statement=CfnWebACL.StatementProperty(
                                                           ip_set_reference_statement=CfnWebACL.IPSetReferenceStatementProperty(
                                                               arn=ipv4_set.attr_arn)),
                                                       action=CfnWebACL.RuleActionProperty(allow={}),
                                                       visibility_config=CfnWebACL.VisibilityConfigProperty(
                                                           cloud_watch_metrics_enabled=True,
                                                           metric_name="whitelist-ipv4-rule-metric",
                                                           sampled_requests_enabled=False)
                                                       )
                                ])
```

### CDK CLI Version

2.15.0 (build 151055e)

### Node.js Version

12.21.0

### OS

Mac OS 12.3.1

### Language

Python

**Comment by indrora** [comment] 2022-04-26 00:42
Looking at the IP addresses that you've listed, it would appear that WAFv2 is expecting that the network address that you provide is actually the network address in that CIDR range:

Doing the math, we can see this:


The following won't add and cause an error:
```
91.183.105.163/29:	net 91.183.105.160	broadcast 91.183.105.167	with 6 hosts
94.79.144.98/29:	net 94.79.144.96	broadcast 94.79.144.103	with 6 hosts
94.79.134.162/29:	net 94.79.134.160	broadcast 94.79.134.167	with 6 hosts
195.178.188.66/29:	net 195.178.188.64	broadcast 195.178.188.71	with 6 hosts
```

The following work without error:
```
212.85.78.240/28:	net 212.85.78.240	broadcast 212.85.78.255	with 14 hosts
62.84.200.16/29:	net 62.84.200.16	broadcast 62.84.200.23	with 6 hosts
80.169.184.136/29:	net 80.169.184.136	broadcast 80.169.184.143	with 6 hosts
158.174.162.104/30:	net 158.174.162.104	broadcast 158.174.162.107	with 2 hosts
158.174.216.244/30:	net 158.174.216.244	broadcast 158.174.216.247	with 2 hosts
83.145.205.32/32:	net 83.145.205.32	broadcast 83.145.205.32	with 1 hosts
194.251.122.24/29:	net 194.251.122.24	broadcast 194.251.122.31	with 6 hosts
88.116.109.68/30:	net 88.116.109.68	broadcast 88.116.109.71	with 2 hosts
213.61.234.0/28:	net 213.61.234.0	broadcast 213.61.234.15	with 14 hosts
217.110.197.224/28:	net 217.110.197.224	broadcast 217.110.197.239	with 14 hosts
62.96.146.96/29:	net 62.96.146.96	broadcast 62.96.146.103	with 6 hosts
```

**Comment by indrora** [comment] 2022-04-26 00:42
Sorry, didn't mean to close the issue.

**Comment by indrora** [comment] 2022-04-29 19:14
We're tracking this to make sure this isn't a WAFv2 issue.

**Comment by peterwoodworth** [comment] 2022-06-17 23:13
Have we confirmed the root cause of this issue?

**Comment by indrora** [comment] 2022-06-20 05:23
I've confirmed with the WAFv2 team that they expect network addresses in the CIDR definitions.

**Comment by peterwoodworth** [comment] 2022-06-20 22:56
If that's the case then I think we can close this issue. If we need to make documentation more clear, then we will need to raise those requests to the necessary teams since our docs are autogenerated here.

**Closed** 2022-10-18 17:27 UTC
Labels: p2, @aws-cdk/aws-wafv2, service-api

**Comment by Nevon** [comment] 2023-03-24 10:34
I just ran into this issue as well, and as far as I can tell this is the only place that mentions that the CIDR definition has to use the network address, unlike for example security groups which do not have that limitation. It would be great if you could raise a request to the necessary teams to mention this limitation for example [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-ipset.html) and [here](https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateIPSet.html#WAF-CreateIPSet-request-Addresses)

**Comment by 1sth1sth1ng0n** [comment] 2024-08-01 16:13
It needs to be specified in [the documentation](https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateIPSet.html#WAF-CreateIPSet-request-Addresses) that the configuration requires an array of network addresses not just random IP addresses in CIDR form as @Nevon has stated.
