### ISSUE TITLE
(cnf-include): cdk diff shows creation of new resources when they are actually updated on deployment

### ISSUE THREAD

**Issue by Nehaparakh95** [aws/aws-cdk#19426] opened 2022-03-16 18:16 UTC
### What is the problem?

While deploying a stack consisting of lambdas and Even source Mapping as well as Lambda aliases, these lambdas are getting replaced after running the cdk diff command and shows that new lambdas will be created. The same does not happen for a stack consisting of S3s, DDBs etc. On deploying, it shows that the UPDATE is COMPLETE. Moreover, the diff does not show addition of any CDKMetadata but on deployment the metadata is in fact added to the stack.

### Reproduction Steps

Create a CFN stack consisting of lambdas, even source mapping and aliased and try converting it into CDKStack using CfnInclude

### What did you expect to happen?

The diff should not show some resources are replaced and CDKMetadata should show up as one of the resources when running the diff command and all the logical Ids of the resources should be preserved

### What actually happened?

Diff did not have CDKMetadata
LogicalIds got replaced

### CDK CLI Version

1.145.0 (build 9f96380)

### Node.js Version

    NodeJS = 12.x;

### OS

macOS Cataline 10.15.7 (19H1715)

### Language

Typescript

**Comment by ryparker** [comment] 2022-03-16 20:34
This is a duplicate of https://github.com/aws/aws-cdk/issues/19415

**Closed by ryparker** 2022-03-16 20:34 UTC
Labels: bug, package/tools, needs-triage
