### ISSUE TITLE
aws_events.Rule doesn't accept aws_events_targets.SfnStateMachine as a target

### ISSUE THREAD

**Issue by oleksii-donoha** [aws/aws-cdk#4538] opened 2019-10-16 16:08 UTC
When trying to add a target to an event in Python, following error is produced on `synth`:

```
Error: Resolution error: Supplied properties not correct for "CfnRuleProps"
  targets: element 0: supplied properties not correct for "TargetProperty"
    arn: required but missing.
```
Rule is `aws_events.Rule` object, and target is `aws_events_targets.SfnStateMachine`.

### Reproduction Steps

```
event = aws_events.Rule(
            self,
            id="Scheduled event",
            enabled=True,
            schedule=aws_events.Schedule.expression(app_config["event_schedule"])
)
event.add_target(aws_events_targets.SfnStateMachine(machine=state_machine))
```

### Error Log

```
/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/resolvable.js:51
            throw e;
            ^

Error: Resolution error: Supplied properties not correct for "CfnRuleProps"
  targets: element 0: supplied properties not correct for "TargetProperty"
    arn: required but missing.
Object creation stack:
  at new Intrinsic (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/private/intrinsic.js:20:44)
  at new PostResolveToken (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/util.js:72:9)
  at CfnRule._toCloudFormation (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/cfn-resource.js:167:39)
  at elements.map.e (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/stack.js:547:60)
  at Array.map (<anonymous>)
  at Stack._toCloudFormation (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/stack.js:547:36)
  at Stack.synthesize (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/stack.js:500:42)
  at Function.synth (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/construct.js:65:27)
  at App.synth (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/app.js:71:52)
  at process.App.process.once (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/app.js:45:51)
  at Object.onceWrapper (events.js:286:20)
  at process.emit (events.js:198:13)
    at ValidationResult.assertSuccess (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/runtime.js:126:19)
    at cfnRulePropsToCloudFormation (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/aws-events/lib/events.generated.js:165:39)
    at CfnRule.renderProperties (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/aws-events/lib/events.generated.js:214:16)
    at PostResolveToken.ret.Resources.util_1.PostResolveToken.props [as processor] (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/cfn-resource.js:178:52)
    at PostResolveToken.postProcess (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/util.js:80:21)
    at Object.postProcess (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/private/resolve.js:30:82)
    at DefaultTokenResolver.resolveToken (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/resolvable.js:42:38)
    at resolve (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/private/resolve.js:94:33)
    at Object.resolve (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/private/resolve.js:28:33)
    at resolve (/tmp/jsii-kernel-8Mu6hw/node_modules/@aws-cdk/core/lib/private/resolve.js:111:43)
```

### Environment

  - **CLI Version      :** 1.13.1 (build 96cfc63)
  - **Framework Version:** 1.13.1 
  - **OS               :** Fedora
  - **Language         :** Python

### Other

This happens in all following cases:

- By supplying `targets` keyword in rule constructor
- By using `add_target()` on rule object
- By using `bind(rule_obj)` on target object

I also checked target type `LambdaFunction`, but it works (aside from type mismatch, target is based on `object` instead of implementing `IRuleTarget` expected by rule object)

--- 

This is :bug: Bug Report

**Comment by oleksii-donoha** [comment] 2019-10-17 08:12
@SomayaB I might be out of the loop, but shouldn't label "package/events" be more appropriate?

**Comment by SomayaB** [comment] 2019-10-17 21:56
@oleksii-donoha You're totally right! Wrong autocomplete when typing Cloud! Thanks for letting me know! 👍

**Comment by oleksii-donoha** [comment] 2019-10-18 08:06
Current workaround is to create lambda function to launch SFN and use it as a target for rule. 
I'll try to dig out the problem on my own, but cannot guarantee anything because of time and the fact that my JS/Typescript knowledge is not up to snuff.

**Comment by oleksii-donoha** [comment] 2019-10-18 14:32
I can confirm that this is not an issue for Typescript:

```
import cdk = require('@aws-cdk/core');
import events = require('@aws-cdk/aws-events');
import targets = require('@aws-cdk/aws-events-targets');
import sfn = require('@aws-cdk/aws-stepfunctions');
import sfn_tasks = require('@aws-cdk/aws-stepfunctions-tasks');

export class CdkTestSfnStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const job = new sfn.Succeed(this, 'Empty');
    const chain = sfn.Chain.start(job);
    const machine = new sfn.StateMachine(this, 'Test machine', {
      definition: chain
    });

    const rule = new events.Rule(this, 'Rule', {
      schedule: events.Schedule.expression('cron(0 6 * * ? *)')
    });

    rule.addTarget(new targets.SfnStateMachine(machine));
  }
}
```
This code passes synth.

**Comment by rix0rrr** [comment] 2019-10-22 15:21
Sounds like a jsii issue then. Assigning @RomainMuller

**Comment by RomainMuller** [comment] 2019-11-14 08:25
Does this still happen with cdk 1.16.x ?

**Comment by oleksii-donoha** [comment] 2019-11-21 14:37
@RomainMuller as of 1.17.1, this still happens.

**Comment by oleksii-donoha** [comment] 2019-11-21 16:01
I also want to check if this applies to regular state machine. I've been using CFN variant because there were some unsupported or buggy features to map state at that moment.

**Comment by RomainMuller** [comment] 2019-11-29 11:36
I am unable to reproduce this issue with `1.18.0`, using the following "complete" reproduction stack:

```python
from aws_cdk import core, aws_events, aws_events_targets, aws_lambda, aws_stepfunctions, aws_stepfunctions_tasks


class Issue4538Stack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # The code that defines your stack goes here
        dummy_lambda = aws_lambda.Function(
            self,
            "Function",
            runtime= aws_lambda.Runtime.NODEJS_10_X,
            handler="index.handler",
            code=aws_lambda.Code.from_inline("export.handler = () => {  };")
        )

        invoke_task = aws_stepfunctions_tasks.InvokeFunction(dummy_lambda)

        state_machine = aws_stepfunctions.StateMachine(
            self,
            "State Machine",
            definition=aws_stepfunctions.Task(self, "InvokeTask", task=invoke_task)
        )

        event = aws_events.Rule(
            self,
            "Scheduled Event",
            enabled=True,
            schedule=aws_events.Schedule.rate(core.Duration.hours(1))
        )
        event.add_target(aws_events_targets.SfnStateMachine(machine=state_machine))
```

Your [last comment](https://github.com/aws/aws-cdk/issues/4538#issuecomment-557151098) makes me wonder if you're trying to pass a `CfnStateMachine` for the `machine` parameter... This wouldn't be supported (this type is not accepted by `SfnStateMachine` as far as I can tell).

**Comment by oleksii-donoha** [comment] 2019-11-29 12:34
@RomainMuller well it's even in the title that I used `CfnStateMachine`...
My use case was that CloudFormation had introduced Map state, but it wasn't supported by CDK yet, and after getting added there were blocker bugs. So I had to resort to CFN object. 
I admit that this is quite narrow use case, but it might happen in the future with some new feature as well and it would be logical that both CFN and regular object implement some common interface and event object expects that interface.
You can close this issue in principle.

**Comment by RomainMuller** [comment] 2019-11-29 13:11
Right - yeah. I agree that inter-operability would be desirable, but might be difficult to achieve in practice. Don't hesitate if you wish to file a feature request towards this goal!

Meanwhile, I am resolving this issue.

**Closed by RomainMuller** 2019-11-29 13:11 UTC
Labels: bug, language/python, p1, package/events, status/needs-repro
