### ISSUE TITLE
Accentuation fail every time after cdk deploy with cdk diff

### ISSUE THREAD

**Issue by webysther** [aws/aws-cdk#8528] opened 2020-06-12 22:52 UTC
When I write some text in Portuguese that contains an accentuation the cdk diff breaks and shows differences every time.

### Reproduction Steps

- Create a app
- Add description com accent: 'maçã'
- Run `cdk diff; cdk deploy`
- Run again `cdk diff`

### Environment

  - **CLI Version      :** 1..45.0 (build 0cfab15)
  - **Node.js Version:** v12.18.0
  - **OS               :** Ubuntu 18.04 LTS
  - **Language (Version):** Python 3.6.9

--- 

This is :bug: Bug Report

**Comment by RomainMuller** [comment] 2020-06-15 09:57
Hey @webysther,

Would you be able to provide an example, so we can easily reproduce? If you can include the `\u####` notation for the accented character as well, this will help make sure we are not falling victim to browsers or anything re-encoding it away from us...

**Comment by shivlaks** [comment] 2020-06-16 06:09
marking this as a `p2` for now, but will bump up if we have a min repro that affects a larger set of scenarios/use cases

**Comment by webysther** [comment] 2020-06-16 20:04
@RomainMuller @shivlaks error sample repo, please follow the README.md instructions:

https://github.com/webysther/test-description-error-sample

**Comment by RomainMuller** [comment] 2020-06-22 12:47
Turns out the problem is that CloudFormation itself mis-encodes your description and replaces both non-ASCII characters with `?`s. It doesn't look like it's anything of CDK's doing.

The CDK is producing a JSON template including a correctly encoded UTF8 representation of your description. I am trying o engage with the CloudFormation service team to understand if this is a bug on their end.

**Comment by RomainMuller** [comment] 2020-06-22 12:59
Alright I have filed an internal enquiry with CloudFormation to understand whether this is expected behavior / raise their attention to this problem.

Internal tracking number is `V215733201`.

**Comment by rix0rrr** [comment] 2020-08-13 14:49
Second internal reference: V137767984 (as we filed something that was closed as a duplicate).

This is not an action item for CDK, so I'm closing it.

**Closed by rix0rrr** 2020-08-13 14:49 UTC
Labels: bug, needs-cfn, p2, package/tools

**Comment by webysther** [comment] 2020-08-13 15:03
Sorry @rix0rrr, can you be more clear?

**Comment by RomainMuller** [comment] 2020-08-17 08:27
@rix0rrr is saying that the bug report I filed to CloudFormation was closed as duplicate of this other internal reference ID he's reported against.

Since this is an issue in CloudFormation, there is nothing we need to do in the CDK directly, besides waiting for them to fix this.
