### ISSUE TITLE
(aws-events-targets): Circular Dependency between IAM Role and SfnStateMachine

### ISSUE THREAD

**Issue by jsunico** [aws/aws-cdk#13464] opened 2021-03-08 09:05 UTC
I'm building a state machine with a custom role. The plan is for the state machine to execute when an event has been received. The same role as the state machine would be used as the executor in the event bridge.

### Reproduction Steps

```
    this.roleStateMachine = new iam.Role(scope, 'IamRoleStateMachine', {
      assumedBy: new iam.ServicePrincipal('states.amazonaws.com'),
      roleName: `StateMachineRole`
    })

    this.stateMachine = new sFn.StateMachine(this, 'StateMachine', {
      definition,
      stateMachineName: MyStateMachine`,
      stateMachineType: sFn.StateMachineType.STANDARD,
      role: this.roleStateMachine,
      tracingEnabled: true,
    })

    this.targetStepFunction = new eventsTargets
      .SfnStateMachine(this.stateMachine, {
        input: events.RuleTargetInput.fromEventPath('$.detail'),
        role: this.roleStateMachine
      })

```

Not passing the role will generate a new role for the event bridge rule.

The codes that I sent belongs to the same stack.

Also tried to add a dependency but didn't work.

```
    const stateMachineRoleDependency = new ConcreteDependable()
    stateMachineRoleDependency.add(this.roleStateMachine)

    this.targetStepFunctionMps.machine.node
      .addDependency(stateMachineRoleDependency)
```

### What did you expect to happen?

I expect that the statement is added to the role and no circular dependency is raised.

### What actually happened?

Circular dependency error.

### Environment

  - **CDK CLI Version  :** 1.91.0
  - **Framework Version:** None
  - **Node.js Version:** v14.15.4
  - **OS               : **WSL
  - **Language (Version):** ~4.1.3

### Other

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-03-08 10:49
Using the same role for both can't really work anyway (at least not as written), as:

```
      assumedBy: new iam.ServicePrincipal('states.amazonaws.com'),
```

Prevents EventBridge from assuming the role.

It's typical in AWS to give every resource that needs an execution role its own Role, and not to combine roles in the way you are planning to do. Can you tell me why you want to do this?

**Comment by jsunico** [comment] 2021-03-08 12:00
I checked the role that was automatically created by cdk. It was still set to `states.amazonaws.com`. I think the event bridge uses PassRole.

https://docs.aws.amazon.com/eventbridge/latest/userguide/iam-identity-based-access-control-eventbridge.html
iam:PassRole - This permission is used so that you can pass to EventBridge an Invocation role to Invoke Rule Targets.

But wouldn't it be the same case if say I want another role but manually created? I assume it will be the same error. Would this still be a valid bug then?

```
    this.roleEventBridge = new iam.Role(scope, 'IamRoleEventBridge', {
      assumedBy: new iam.ServicePrincipal('events.amazonaws.com'),
      roleName: `StateMachineRole`
    })

    this.targetStepFunction = new eventsTargets
      .SfnStateMachine(this.stateMachine, {
        input: events.RuleTargetInput.fromEventPath('$.detail'),
        role: this.roleEventBridge 
      })
```

**Comment by rix0rrr** [comment] 2021-03-09 09:43
> I assume it will be the same error

I assume it won't :). Have you tried?

In fact, you don't usually need to create and pass Roles at all--CDK will automatically create them for you.

**Comment by jsunico** [comment] 2021-03-10 04:23
Hi @rix0rrr,

I tested this now.

I created a new role just for invoking the event (the usual use case) and it's fine. Even tried squeezing in adding a policy statement in between but it still works.

> In fact, you don't usually need to create and pass Roles at all--CDK will automatically create them for you.
> It's typical in AWS to give every resource that needs an execution role its own Role, and not to combine roles in the way you are planning to do

Yeah, I understand this better now. The reason I attempted to do this is to simplify the access. It feels right to me that the state machine could/should be able to start itself so if event bridge is going to assume/pass the role, why not just use the same role? But as you say, it's not really how we typically set up the roles for different resources.

If you don't agree with my reason. I'm happy to move on and close the issue. :) Thank you for your time! 

```
    const role = new iam.Role(scope, 'IamRoleInvokeStateMachine', {
      assumedBy: new iam.ServicePrincipal('events.amazonaws.com'),
      description: `Test custom role`,
      roleName: `StateMachineInvokerRole`
    })

    role.addToPrincipalPolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      actions: ['lambda:InvokeFunction'],
      resources: [lambdaInitializeOrderArn]
    }))

    this.targetStepFunctionMps = new eventsTargets
      .SfnStateMachine(this.stateMachine, {
        input: events.RuleTargetInput.fromEventPath('$.detail'),
        role
      })
```

**Comment by rix0rrr** [comment] 2021-03-15 10:49
>  It feels right to me that the state machine could/should be able to start itself

But that's not what's happening though. **AWS EventBridge** is starting the State Machine, and needs permissions to do so.

You *could* have a State Machine recursively invoke itself, and if you tried to do that, it would automatically get permissions to start itself. But that's a different case.

THis is not a bug. Closing.

**Closed by rix0rrr** 2021-03-15 10:49 UTC
Labels: @aws-cdk/aws-events-targets, @aws-cdk/aws-iam, bug, needs-triage
