### ISSUE TITLE
Issue using "AwsCustomResourcePolicy" auto-generate IAM Policy for SES custom-resources

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#8398] opened 2020-06-05 13:19 UTC
### Reproduction Steps

I'm creating a CustomResource to validate a Domain for SES, here my snippet : 
```
new CustomResource.AwsCustomResource(this, 'VerifyDomainIdentity', {
      onCreate: {
        service: 'SES',
        action: 'verifyDomainIdentity',
        parameters: {
          Domain: R53DomainSes
        },
        physicalResourceId: CustomResource.PhysicalResourceId.fromResponse('VerificationToken')
      },
      policy: CustomResource.AwsCustomResourcePolicy.fromSdkCalls({resources: CustomResource.AwsCustomResourcePolicy.ANY_RESOURCE}),
```
When I'm launching CDK to deploy the Stack, it show me these informations : 
```
├───┼─────────────────────────────────────────────────────────────────┼────────┼───────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────┼───────────┤
│ + │ *                                                               │ Allow  │ email:VerifyDomainIdentity                        │ AWS:${AWS679f53fac002430cb0da5b7982bd2287/ServiceRole}          │           │
│ + │ *                                                               │ Allow  │ logs:DeleteRetentionPolicy                        │ AWS:${LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a/ServiceRole} │           │
│   │                                                                 │        │ logs:PutRetentionPolicy                           │                                                                 │           │
└───┴─────────────────────────────────────────────────────────────────┴────────┴───────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────┴───────────┘
```
We can see **email:VerifyDomainIdentity**; unfortunatly, it's **ses:VerifyDomainIdentity** who is needed.

### Error Log

So of course, I have that error : 
`[...] is not authorized to perform: ses:VerifyDomainIdentity`

### Environment

  - **CLI Version      : CDK 1.42.1 (build a4797b4)**
  - **Framework Version: 6.14.5**
  - **Node.js Version: v12.15.0** 
  - **OS               : Linux**
  - **Language (Version): TypeScript** 

--- 

This is :bug: Bug Report

**Comment by Cloudrage** [comment] 2020-06-05 15:10
Same with : **verifyDomainDkim**
_email:VerifyDomainIdentity_ instead of _ses:VerifyDomainIdentity_

I've created my own **PolicyStatement** to bypass that pb; waiting for a fix now.

**Comment by jogold** [comment] 2020-06-05 22:03
Duplicate of #4533

**Comment by SomayaB** [comment] 2020-06-08 20:30
Closing this issue since it is a duplicate of #4533

**Closed by SomayaB** 2020-06-08 20:30 UTC
Labels: @aws-cdk/custom-resources, bug, needs-triage

**Comment by Cloudrage** [comment] 2020-06-09 06:57
Yep you're right; but don't forget **verifyDomainDkim** who is not mentioned in #4533.

And to fix that of course, for almost 1 year ^^
