### ISSUE TITLE
docdb: Cannot delete the subnet group because at least one database cluster 

### ISSUE THREAD

**Issue by rantoniuk** [aws/aws-cdk#29122] opened 2024-02-15 17:55 UTC
### Describe the bug

Stack deployed from:

```ts
export class MongoDbStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: MongoStackProps) {
    super(scope, id, props);

    new docdb.DatabaseCluster(this, 'MongoCluster', {
      dbClusterName: 'MongoCluster',
      masterUser: {
        username: `${props.envv.db.mongo.dbUserName}`,
        excludeCharacters: "\"@/:!^;,~%+&()?<>*[]{}_-.#?'`\\|",
      },
      instanceType: ec2.InstanceType.of(props.envv.db.mongo.instance, props.envv.db.mongo.instanceSize),
      // instances: 1,
      vpc: props.vpc,
      securityGroup: props.dbSecurityGroup,
      storageEncrypted: true,
      deletionProtection: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
    });

  }
}

```

Now, there are two bugs here:
- instances are supposed to be by default == 1 , but when `instances: 1` is commented out, the cluster is created without any instances
- when I try to destroy the stack, I get:
```
6:47:47 PM | DELETE_FAILED        | AWS::DocDB::DBSubnetGroup                   | MongoClusterSubnets57E68960
Got InvalidDBInstanceStateException with error: Cannot delete the subnet group 'mongoclustersubnets57e68960-jxuv00nfliql' because at least one database cluster: mongocluster is still using
it.

```

### Expected Behavior

as above.

### Current Behavior

as above.

### Reproduction Steps

As above.

### CDK CLI Version

2.128.0 (build d995261)

### Node.js Version

v18.18.2

### OS

MacOS

### Language

TypeScript

**Comment by tim-finnigan** [comment] 2024-02-15 23:11
It looks like the second issue is a duplicate of a one opened last week: https://github.com/aws/aws-cdk/issues/29054. There is already a PR up to fix it: https://github.com/aws/aws-cdk/pull/29059. Regarding the first issue - it looks like the [logic here](https://github.com/aws/aws-cdk/blob/869412535f564d5b36cf7cc5356aa38a381d02f1/packages/aws-cdk-lib/aws-docdb/lib/cluster.ts#L502) doesn't allow for deploying less than one instance.

**Comment by rantoniuk** [comment] 2024-02-15 23:25
Well, maybe the logic doesn't allow, but Cloudformation apparently does. My AWS Console shows 0/0 instances in that cluster ;-)

**Closed** 2024-02-16 12:26 UTC
Labels: bug, p2, @aws-cdk/aws-docdb
