### ISSUE TITLE
(asset-staging): local bundling fails inside a docker container with non-existent user

### ISSUE THREAD

**Issue by akuntsch** [aws/aws-cdk#15415] opened 2021-07-05 07:01 UTC
We run our CDK scripts inside a Node.js docker container inside a Jenkins pipeline. Jenkins runs docker containers with the host user (`docker run -u ...`) which does not necessarily exist inside the docker container. Bundling fails inside the Jenkins pipeline because CDK tries to read the user from `/etc/passwd`, even though the user is not used when using local asset bundling.

### Reproduction Steps

Run CDK code with local asset bundling inside a docker container with non-existent user (e.g. `docker run -u 1234:1234`).

### What did you expect to happen?

Local asset bundling works inside a docker container with non-existent user.

### What actually happened?

Asset bundling fails with the following error:

```
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
```

### Environment

  - **CDK CLI Version  :** 1.108.0 (build b23f781)
  - **Framework Version:** 1.108.0 
  - **Node.js Version:** v14.17.0
  - **OS               :** Docker on Linux (node:14 docker image)
  - **Language (Version):** TypeScript (4.3.4)

### Other

Should be fixed by #15313.

--- 

This is :bug: Bug Report

**Comment by serverhorror** [comment] 2021-09-02 12:02
@peterwoodworth, @akuntsch I think I just ran into this same issue, could there be a regression/edge case?

This happens inside of OpenShift where the user doesn't exist. Only a UID. It doesn't happen when it runs with a user that is actually visible via e.g. `getent passwd ...`

Runing a plain `cdk version` fails miserably:

```
cdk version
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:347:11)
    at cdkHomeDir (/opt/node/lib/node_modules/aws-cdk/lib/util/directories.ts:7:21)
    at Object.cdkCacheDir (/opt/node/lib/node_modules/aws-cdk/lib/util/directories.ts:11:20)
    at new AccountAccessKeyCache (/opt/node/lib/node_modules/aws-cdk/lib/api/aws-auth/account-cache.ts:25:44)
    at Object.<anonymous> (/opt/node/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk.ts:51:42)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

Same for `cdk synth`

```
cdk synth --context vpc-id=vpc-0123456789 --context irods-ami-id=ami-0123456789 iRods
os.js:347

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:347:11)
    at cdkHomeDir (/opt/node/lib/node_modules/aws-cdk/lib/util/directories.ts:7:21)
    at Object.cdkCacheDir (/opt/node/lib/node_modules/aws-cdk/lib/util/directories.ts:11:20)
    at new (/opt/node/lib/node_modules/aws-cdk/lib/api/aws-auth/account-cache.ts:25:44)
    at Object.<anonymous> (/opt/node/lib/node_modules/aws-cdk/lib/api/aws-auth/sdk.ts:51:42)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

Environment
* CDK CLI Version : 1.121.0 (build 026cb8f)
* Framework Version: 1.108.0
* Node.js Version: v14.17.0
* OS : RedHat OpenShift 3.11 (node v14.17.5, based on `docker.io/amazon/aws-cli:2.2.33` )
* Language (Version): Python 3.7.10

**Comment by peterwoodworth** [comment] 2021-09-02 20:03
Thanks for the ping, I've reopened the issue for investigation

**Comment by a-h** [comment] 2022-01-12 15:12
I'm encountering this with CDK 1.138.2, deploying inside the node:16  Docker container inside Github Actions.

**Comment by adambro** [comment] 2022-03-22 08:18
Try setting `CDK_HOME=/tmp` as I did in #19401 that should do the trick for asset building. For running a CDK Pipelines like in #19401 issue it might not be enough, due to bug in `safeUsername()` function.

**Comment by TheRealAmazonKendra** [comment] 2023-01-26 23:22
Looks like this was fixed in https://github.com/aws/aws-cdk/pull/20188. If that is not correct and there are still issues around this, please open a new issue.

**Closed by TheRealAmazonKendra** 2023-01-26 23:22 UTC
Labels: bug, p2, package/tools, effort/medium
