### ISSUE TITLE
aws_events_targets : EcsTarget can't be set to `latest` revision

### ISSUE THREAD

**Issue by eliyasmeth** [aws/aws-cdk#21711] opened 2022-08-22 18:06 UTC
### Describe the feature

I have this code which creates a target rule for an ECSTask and sets the current revision of the task deployed by CDK. But I'd like to have a way to set to the `latest` revision like the way you can do it on the AWS Console.

```processOutputRule.addTarget(
      new targets.EcsTask({
        cluster,
        taskDefinition,
        containerOverrides: [
          {
            containerName: container.containerName,
            environment: [
              {
                name: "MEETING",
                value: EventField.fromPath("$.detail.meetingId"),
              },
            ],
          },
        ],
      })
    );
```

### Use Case

I want to just run one time the CDK deploy in order to build the infrastructure, and then only update the code on the ECR and the update a new TaskDefinition. So whenever this happen the ECSTarget on the event always take the `latest` revision deployed without caring about the specific revision number.

### Proposed Solution

I have seen on the [ECS Target documentation](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_events_targets.EcsTask.html) but there is no way to set the `latest` revision, maybe a property or a flag to indicate that you want to set to the `latest` revision.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.13.0

### Environment details (OS name and version, etc.)

Windows 10 Pro x64

**Comment by peterwoodworth** [comment] 2022-08-26 20:41
Closing as duplicate of #21782

**Closed by peterwoodworth** 2022-08-26 20:41 UTC
Labels: feature-request, @aws-cdk/aws-events-targets
