### ISSUE TITLE
Adding a description to database secret

### ISSUE THREAD

**Issue by abelmokadem** [aws/aws-cdk#4483] opened 2019-10-12 08:03 UTC
### The Question
Hi all, I'm trying to add a description to our database secrets in order to keep a clear overview of the secrets we have in secrets manager. 

Right now the code I'm using is this:
```
const databaseSecret = databaseInstance.node.findChild("Secret") as DatabaseSecret;
const secret = databaseSecret.node.defaultChild! as CfnSecret;
secret.addPropertyOverride("Description", `Hello description`);
```

Can we add an option to add a description to database secrets? Either via a method on the database instance or via the props. I can imagine that this is probably the same for `DatabaseCluster`. What would be the right way to implement this?

### Environment

  - **CDK CLI Version:** 1.12.0
  - **Module Version:** 1.12.0
  - **OS:** OSX
  - **Language:** TypeScript

**Comment by nmussy** [comment] 2019-10-14 06:58
Currently, only the `masterUsername` and `secretKmsKey` properties are exposed:
https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-rds/lib/instance.ts#L733-L739

`DatabaseSecret` is missing the `description` and `secretName` fields from `ssm.Secret`, which will need to be added.

For `DatabaseInstance`, instead of exposing those two missing fields directly, it might be cleaner to add a `secret` property.

```ts
new rds.DatabaseInstance(stack, 'Instance', {
  vpc,
  instanceClass,
  masterUsername: 'admin',
  secretDescription: 'description',
  secretName: 'name',
});

new rds.DatabaseInstance(stack, 'Instance', {
  vpc,
  instanceClass,
  secret: {
    username: 'admin',
    description: 'description',
    name: 'name',
  }
});
```

Thoughts?

**Comment by jogold** [comment] 2019-10-14 10:19
Related https://github.com/aws/aws-cdk/issues/4144

**Comment by SomayaB** [comment] 2019-10-14 17:40
Hi @abelmokadem, thanks for submitting a feature request! We will look into this and someone will update this issue when there is movement.

**Comment by cseickel** [comment] 2019-10-30 02:56
I would like to have this as well.  I personally ended up creating a separate secret and passing in the secret value for the master password so that I could have more control over the secret.

I think the ideal situation would be to accept the entire SecretProps interface as an optional "secret" object in the DatabaseInstanceProps as @nmussy suggested.  I would be willing to take a shot at implementing this if the team is interested in making his change.

I know that there is currently a DatabaseSecret subclass being used internally, but it doesn't seem to do much other than specifying some default values.  That DatabaseSecret class would need to expose all of the underlying SecretProps if it was kept around, but I'm not sure it is really necessary.

**Comment by Artmobile** [comment] 2019-12-03 13:39
+1

**Comment by nija-at** [comment] 2020-02-17 17:54
Duplicate of https://github.com/aws/aws-cdk/issues/4144

**Closed by nija-at** 2020-02-17 17:54 UTC
Labels: feature-request, package/rds
