### ISSUE TITLE
‼️ (iam): OpenIdConnectProvider defaults to first thumbprint instead of root CA thumbprint

### ISSUE THREAD

**Issue by bleish** [aws/aws-cdk#8607] opened 2020-06-17 21:11 UTC
Please add your +1 👍 to let us know you have encountered this
---

### Overview:

The `iam.OpenIdConnectProvider` resource contains logic that dynamically fetches the certificate thumbprint required to [create an OpenID Connect provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html). However, as of now, it mistakenly fetches the leaf certificate of the provider, instead of the root one. 

As long as the leaf certificate is valid, this doesn't have an impact your applications. However, once the certificate is rotated, your application will fail to use the provider to authenticate against AWS services. Since leaf certificates are rotated frequently, you are in danger of disruption. This will probably manifest in `Access Denied` errors. 

### Workaround:

If you are using the `iam.OpenIdConnectProvider` construct in conjunction with an EKS cluster:

```ts
import * as iam from `aws-cdk-lib/aws-iam`;
import * as eks from `aws-cdk-lib/aws-eks`;

const cluster = new eks.Cluster(this, "EKSCluster", {
  version: eks.KubernetesVersion.V1_21,
});

new iam.OpenIdConnectProvider(this, "OIDCProvider", {
  url: cluster.clusterOpenIdConnectIssuerUrl,
});
```

Switch to use the `OpenIdConnectProvider` construct from the EKS library:

```ts
import * as eks from `aws-cdk-lib/aws-eks`;

const cluster = new eks.Cluster(this, "EKSCluster", {
  version: eks.KubernetesVersion.V1_21,
});

new eks.OpenIdConnectProvider(this, "OIDCProvider", {
  url: cluster.clusterOpenIdConnectIssuerUrl,
});
```

The reason this works is because the `eks.OpenIdConnectProvider` [hardcodes](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-eks/lib/oidc-provider.ts#L49) the correct thumbprint for EKS.

If you are using the `iam.OpenIdConnectProvider` in conjunction with other services, make sure you pass the thumbprint explicitly to the construct, instead of relying on its dynamic fetching capabilities.

```ts
import * as iam from `aws-cdk-lib/aws-iam`;

new iam.OpenIdConnectProvider(this, "OIDCProvider", {
  url: cluster.clusterOpenIdConnectIssuerUrl,
    clientIds: ["sts.amazonaws.com"],
    thumbprints: ['<pass-thumbprint-here>'],
});
```

To obtain the correct thumbprint for your provider, follow these [instructions](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html). 

### Solution:

We are working on a fix to the `iam.OpenIdConnectProvider` construct so that if correctly fetches the root certificate thumbprint. See [PR](https://github.com/aws/aws-cdk/pull/22802). Once it is merged, the fix will be available in the following CDK release, at which point a simple deployment will fix the issue in your environment. 

---------------------------------------

*Originally reported as*

When deploying an OpenIdConnectProvider construct using the oidc issuer url retrieved from an EKS cluster (the domain is oidc.eks.us-west-2.amazonaws.com) and no value for the `thumbprints` property, the resulting auto-obtained thumbprint doesn't match the one I get from following the steps provided [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html).

### Reproduction Steps

```
const cluster = new eks.Cluster(this, "EKSCluster");

new iam.OpenIdConnectProvider(this, "EKSOIDCProvider", {
    url: cluster.clusterOpenIdConnectIssuerUrl,
    clientIds: ["sts.amazonaws.com"]
});
```

### Error Log

See Other for a related error.

### Environment

  - **CLI Version      :** 1.45.0
  - **Framework Version:**
  - **Node.js Version:** 14.4.0
  - **OS               :** Windows 10 (10.0.18363 Build 18363)
  - **Language (Version):**  TypeScript (3.7.2)

### Other

If I try to deploy a cluster autoscaler to my EKS cluster using a service account role tied to that provider, the pod enters a CrashLoopBackOff state with the error message:
> F0617 20:04:12.561996       1 aws_cloud_provider.go:376] Failed to create AWS Manager: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
        status code: 400, request id: 00ec5e59-3672-4264-b5d4-c44f573ff50c

If I instead follow the [guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html) to retrieve the correct thumbprint via openssl and provide that to the OpenIdConnectProvider construct, the cluster autoscaler successfully deploys.

--- 

This is :bug: Bug Report

**Comment by sogos** [comment] 2020-06-20 22:27
Same problem observed in CLI Version: 1.46.0

**Comment by eladb** [comment] 2020-06-24 06:35
@bleish @sogos can you use `cluster.addServiceAccount()` instead of explicitly creating the OIDC provider (see [docs](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-eks#service-accounts))?

**Comment by sogos** [comment] 2020-06-24 11:18
Hello @eladb ,

That seem to work perfectly :+1: 
 
Tested with alb-ingress-controller:
https://gitlab.com/thibault.cordier1/cdk-eks-fargate/-/blob/master/lib/eks-stack.ts#L68

But i don't understand why the thumbprint on the identity provider is false.
I use the command: 
```
openssl s_client -servername oidc.eks.eu-west-1.amazonaws.com -showcerts -connect oidc.eks.eu-west-1.amazonaws.com:443 | openssl x509  -fingerprint -noout
```

**Comment by eladb** [comment] 2020-06-24 11:54
Glad to hear that `addServiceAccount()` worked for you. We need to investigate why the default behavior of the `iam.OpenIdConnectProvider` resource is unable to extract the correct thumbprint from EKS. The current implementation in @aws-cdk/aws-eks actually hard codes the thumbprint ([ref](https://github.com/aws/aws-cdk/blob/6166a70800caff8530f55a14fd8e71ca9dd4e9f8/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L711)).

**Comment by eladb** [comment] 2020-06-24 11:56
Our EKS code currently has the following comment:

```
For some reason EKS isn't validating the root certificate but a intermediat certificate
which is one level up in the tree. Because of the a constant thumbprint value has to be
stated with this OpenID Connect provider. The certificate thumbprint is the same for all the regions.
```

https://github.com/aws/aws-cdk/blob/6166a70800caff8530f55a14fd8e71ca9dd4e9f8/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L711

**Comment by eladb** [comment] 2020-06-24 11:56
Routing to IAM

**Comment by bleish** [comment] 2020-06-24 14:47
It looks like the lambda is using the `tlsSocket.getPeerCertificate` method to retrieve the intermediate certificate. By default, that only retrieves the first certificate in the chain. If you pass `true` to the method it'll return the full chain, linked by the `issuerCertificate` property. You can follow the chain until you reach the root CA, after which `issuerCertificate` becomes a cyclical reference. I just tried this and was able to get the proper certificate and thumbprint. In my case (issuer host = oidc.eks.us-west-2.amazonaws.com) the chain was: 

*.execute-api.us-west-2.amazonaws.com -> Amazon -> Amazon Root CA 1 -> Starfield Services Root Certificate Authority - G2 

The last giving the expected thumbprint of `9e99a48a9960b14926bb7f3b02e22da2b0ab7280`.

The [Node.js TLS documentation for getPeerCertificate](https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed) gives more info that could be useful in implementing this.

**Comment by eladb** [comment] 2020-06-24 22:34
@bleish wow thanks so much for the detailed explanation. Would you say the preferred behavior for the OIDC provider resource is to always use the root CA thumbprint?

**Comment by bleish** [comment] 2020-06-24 23:33
@eladb 
It seems so. According to their [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html):
> When you create an OpenID Connect (OIDC) identity provider in IAM, you must supply a thumbprint. IAM requires the thumbprint for the root certificate authority (CA) that signed the certificate used by the external identity provider (IdP). The thumbprint is a signature for the CA's certificate that was used to issue the certificate for the OIDC-compatible IdP. When you create an IAM OIDC identity provider, you are trusting identities authenticated by that IdP to have access to your AWS account.

One gotcha I ran into when testing the `getPeerCertificate(true)` method was that the certificate chain contained one more certificate beyond the root CA.  When following the openssl steps from the documentation above, I get a chain of 4 certificates, and the last certificate in that chain (Starfield Services Root Certificate Authority - G2) returns the expected `9e99a48a9960b14926bb7f3b02e22da2b0ab7280` thumbprint. However, using `getPeerCertificate(true)` I get one more certificate beyond that, but it has no Common Name value and is self-signed (so `issuerCertificate` is circular at that point). I don't know what this certificate is, as the openssl method didn't contain it. Maybe self-signed certs aren't included in the openssl chain? Someone more knowledgable in this area than I am might understand what's going on.

**Comment by bleish** [comment] 2020-06-25 00:04
It looks like openssl s_client [doesn't always return the full certificate chain](https://github.com/openssl/openssl/issues/4933).  The [documentation](https://www.openssl.org/docs/man1.0.2/man1/openssl-s_client.html) for the `-showcerts` flag on s_client states:
> Displays the server certificate list as sent by the server: it only consists of certificates the server has sent (in the order the server has sent them). It is not a verified chain.

Using `getPeerCertificate(true)` does appear to return the full chain, so it seems the Open ID Connect Identity Provider doesn't necessarily expect the absolute root of the chain, but the last certificate provided by the server (Starfield Services Root Certificate Authority - G2 in this case). If that's true, then I'm not sure how, using the tls module, to ensure the correct thumbprint is being obtained.

**Comment by pevers** [comment] 2022-05-17 08:23
We deployed the OIDC using:

```
new iam.OpenIdConnectProvider(this, "EKSOIDCProvider", {
    url: cluster.clusterOpenIdConnectIssuerUrl,
    clientIds: ["sts.amazonaws.com"]
});
```

And the thumbprint expired last Sunday leading to all our apps not being able to access AWS resources. 

Would it be an idea to document this a bit more in the `iam.OpenIdConnectProvider` constructor? Like adding a note that if you are creating an `OpenIdConnectProvider` for an EKS cluster you should use `eks.OpenIdConnectProvider`?

**Comment by chrisjgray** [comment] 2022-10-13 16:42
My organization is also having this same issue. Can this get prioritized?

**Comment by comcalvi** [comment] 2022-10-31 17:22
We're working on a fix for this issue right now. If you can't upgrade to the CDK version that contains the fix, you can workaround this issue on an old version by changing any `iam.OpenIdConnectProvider`s that use an EKS Cluster's `clusterOpenIdConnectIssuerUrl` to use the `OpenIdConnectProvider` from `aws-eks` like so:

```
import * as iam from `aws-cdk-lib/aws-iam`;
import * as eks from `aws-cdk-lib/aws-eks`;

const cluster = new eks.Cluster(this, "EKSCluster", {
  version: eks.KubernetesVersion.V1_21,
});

new eks.OpenIdConnectProvider(this, "OIDCProvider", {
  url: cluster.clusterOpenIdConnectIssuerUrl,
});
```

Or, if you prefer to use aws-iam, you can hardcode the thumbprint to that of the root certificate (which is exactly what the `aws-eks` module does), but be aware that EKS will eventually rotate the root certificate as well:
```
import * as iam from `aws-cdk-lib/aws-iam`;
import * as eks from `aws-cdk-lib/aws-eks`;

const cluster = new eks.Cluster(this, "EKSCluster", {
  version: eks.KubernetesVersion.V1_21,
});

new iam.OpenIdConnectProvider(this, "OIDCProvider", {
  url: cluster.clusterOpenIdConnectIssuerUrl,
    clientIds: ["sts.amazonaws.com"],
    thumbprints: ['9e99a48a9960b14926bb7f3b02e22da2b0ab7280'],
});
```

**Comment by iliapolo** [comment] 2022-11-06 23:05
Reopening. See https://github.com/aws/aws-cdk/pull/22802

**Closed** 2022-11-12 22:49 UTC
Labels: bug, management/tracking, p0, @aws-cdk/aws-eks, @aws-cdk/aws-iam, effort/medium

**Comment by drankard** [comment] 2022-11-21 12:09
if this is Closed, shouldn't notice 8607 be removed ? or do i still have to acknowledge it even thoug its fixed by a release?

**Comment by mrgrain** [comment] 2022-12-02 17:01
> if this is Closed, shouldn't notice 8607 be removed ? or do i still have to acknowledge it even thoug its fixed by a release?

Apologies for this. We had an issue that wrongly showed to notice for non affected versions. This should be fixed now.

**Comment by fadinasr** [comment] 2022-12-08 23:55
@mrgrain I have CDK v2.51.1 (build 3d30cdb) and I still got the notice also.

**Comment by mrgrain** [comment] 2022-12-09 11:12
@fadinasr Thanks for letting me know. I can't reproduce this. We do cache the notice data, but not for very long. Maybe that's it.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/379814/206689145-202ee330-7435-4d04-9766-7cf6db78fddb.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/379814/206689380-f49d6e76-2679-45a7-a3eb-090fbb1846f3.png">
