### ISSUE TITLE
(aws-ec2): unable to create 2x ASGs in one stack where a common InitFile filename is used.

### ISSUE THREAD

**Issue by neilferreira** [aws/aws-cdk#17583] opened 2021-11-19 08:28 UTC
### What is the problem?

To place a file on an EC2 instance that is provisioned through an Auto Scaling Group the recommended approach (to my knowledge) is to use CloudFormationInit to place the file(s) on the server.  Affects version 1.132.0 as of writing.

When configuring more than one ASG in a stack (in my instance, one for on-demand and one for spot instances) where the same file is required on the server, this raised a CDK error saying a construct with that filename already exists.

Example:
```

    const vpc = new ec2.Vpc(this, "Vpc");

    const signals = autoscaling.Signals.waitForMinCapacity({
      timeout: cdk.Duration.minutes(10),
    });
    const init = ec2.CloudFormationInit.fromConfigSets({
      configSets: {
        default: ["config"],
      },
      configs: {
        config: new ec2.InitConfig([
          ec2.InitFile.fromAsset(
            "/home/ec2-user/test.sh",
            __dirname + "/test.sh"
          ),
          ec2.InitCommand.shellCommand("/bin/bash /home/ec2-user/test.sh"),
        ]),
      },
    });

    const configuration = [
      {
        name: "ondemand",
        spotPrice: undefined,
      },
      {
        name: "spot",
        spotPrice: undefined,
      },
    ];

    configuration.forEach((config) => {
      new autoscaling.AutoScalingGroup(this, `${config.name}ASG`, {
        vpc,
        instanceType: new ec2.InstanceType("t3.nano"),
        machineImage: ec2.MachineImage.latestAmazonLinux(),
        minCapacity: 1,
        maxCapacity: 1,
        init,
        signals,
        spotPrice: config.spotPrice,
      });
    });
```

Raises:

```

node_modules/constructs/src/construct.ts:381
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name '--home--ec2-user--test.shAsset' in TestStack [TestStack]
    at Node.addChild (node_modules/constructs/src/construct.ts:381:13)
    at new Node (node_modules/constructs/src/construct.ts:58:22)
    at new ConstructNode (node_modules/@aws-cdk/core/lib/construct-compat.ts:184:24)
    at Object.createNode (node_modules/@aws-cdk/core/lib/construct-compat.ts:55:11)
    at new Construct (node_modules/constructs/src/construct.ts:409:26)
    at new Construct (node_modules/@aws-cdk/core/lib/construct-compat.ts:52:5)
    at new Asset (node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:65:5)
    at Object._doBind (node_modules/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts:290:23)
    at Object._bind (node_modules/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts:335:17)
    at node_modules/@aws-cdk/aws-ec2/lib/cfn-init.ts:224:54
```

I cannot find a workaround here, tired:
* Not re-using the `init` variable, re-defining it in each AutoScalingGroup

### Reproduction Steps

```
npx cdk init app --language typescript

npx cdk bootstrap
npx cdk deploy
```

```
    const vpc = new ec2.Vpc(this, "Vpc");

    const configuration = [
      {
        name: "ondemand",
        spotPrice: undefined,
      },
      {
        name: "spot",
        spotPrice: undefined,
      },
    ];

    configuration.forEach((config) => {
      let signals = autoscaling.Signals.waitForMinCapacity({
        timeout: cdk.Duration.minutes(10),
      });
      let init = ec2.CloudFormationInit.fromConfigSets({
        configSets: {
          default: ["config"],
        },
        configs: {
          config: new ec2.InitConfig([
            ec2.InitFile.fromAsset(
              "/home/ec2-user/test.sh",
              __dirname + "/test.sh"
            ),
            ec2.InitCommand.shellCommand("/bin/bash /home/ec2-user/test.sh"),
          ]),
        },
      });

      new autoscaling.AutoScalingGroup(this, `${config.name}ASG`, {
        vpc,
        instanceType: new ec2.InstanceType("t3.nano"),
        machineImage: ec2.MachineImage.latestAmazonLinux(),
        minCapacity: 1,
        maxCapacity: 1,
        init,
        signals,
        spotPrice: config.spotPrice,
      });
    });
```

```
{
  "name": "initdataa",
  "version": "0.1.0",
  "bin": {
    "initdataa": "bin/initdataa.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/assertions": "1.132.0",
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "aws-cdk": "1.132.0",
    "ts-node": "^9.0.0",
    "typescript": "~3.9.7"
  },
  "dependencies": {
    "@aws-cdk/aws-ec2": "1.132.0",
    "@aws-cdk/aws-autoscaling": "1.132.0",
    "@aws-cdk/core": "1.132.0",
    "source-map-support": "^0.5.16"
  }
}

```

### What did you expect to happen?

I expected 2 auto-scaling groups to be provisioned, when each ASG starts an EC2 instance, it should place a file called 'test.sh' in the home directory of `ec2-user`

### What actually happened?

```
node_modules/constructs/src/construct.ts:381
      throw new Error(`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`);
            ^
Error: There is already a Construct with name '--home--ec2-user--test.shAsset' in TestStack [TestStack]
    at Node.addChild (node_modules/constructs/src/construct.ts:381:13)
    at new Node (node_modules/constructs/src/construct.ts:58:22)
    at new ConstructNode (node_modules/@aws-cdk/core/lib/construct-compat.ts:184:24)
    at Object.createNode (node_modules/@aws-cdk/core/lib/construct-compat.ts:55:11)
    at new Construct (node_modules/constructs/src/construct.ts:409:26)
    at new Construct (node_modules/@aws-cdk/core/lib/construct-compat.ts:52:5)
    at new Asset (node_modules/@aws-cdk/aws-s3-assets/lib/asset.ts:65:5)
    at Object._doBind (node_modules/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts:290:23)
    at Object._bind (node_modules/@aws-cdk/aws-ec2/lib/cfn-init-elements.ts:335:17)
    at node_modules/@aws-cdk/aws-ec2/lib/cfn-init.ts:224:54
```

### CDK CLI Version

1.132.0

### Node.js Version

v16.13.0

### OS

MacOS Big Sur

### Language

Typescript

### Language Version

~3.9.7

**Comment by njlynch** [comment] 2021-12-08 16:57
Thanks for the detailed bug report. I'm marking this as a duplicate of https://github.com/aws/aws-cdk/issues/16891, which I believe is the exact same issue.

**Closed by njlynch** 2021-12-08 16:57 UTC
Labels: bug, p2, @aws-cdk/aws-ec2, needs-triage
