### ISSUE TITLE
(CDK Bootstrap): By default there is no lifecycle policy to manage the storage in CDK asset bucket

### ISSUE THREAD

**Issue by harshitjain99** [aws/aws-cdk#23801] opened 2023-01-23 23:42 UTC
### Describe the feature

The CDK asset S3 bucket in default bootstrap template for the CDK Toolkit has no default lifecycle policy which leads to cumulative increase in storage over a period of time and not cost optimized solution for a customer.

### Use Case

Customer created the CDK Toolkit stack with default bootstrap template have to incur the cost of the cumulative storage in the CDK asset S3 bucket over a period of time. This is not a cost effective solution.
 

### Proposed Solution

There should be a default lifecycle policy enabled on CDK S3 bucket to manage the storage size.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2

### Environment details (OS name and version, etc.)

NA

**Comment by ByronBecker** [comment] 2023-02-11 22:42
It looks like for each stack a `zip` and `json` file get uploaded, but each of these files a named with a hash so if you have multiple stacks that you deploy independently there's not a good way to determine which json & zip pertain to which stack, and what is the most recent deployment "version" of that stack.

**Comment by tim-finnigan** [comment] 2023-02-15 18:22
Hi @harshitjain99 thanks for the feature request. This seems to overlap with a recent issue (https://github.com/aws/aws-cdk/issues/21928) which was closed as a duplicate of https://github.com/aws/aws-cdk/issues/6692. In the [most recent comment](https://github.com/aws/aws-cdk/issues/6692#issuecomment-1412627406) on that latter issue the following is mentioned:
>No updates currently but there is a third party construct to help enable this for those that need something in the interim https://constructs.dev/packages/cloudstructs/v/0.6.18/api/ToolkitCleaner?lang=typescript
>
>For tracking a built in solution https://github.com/aws/aws-cdk-rfcs/issues/64 is the place to watch.

I think we should continue tracking this feature request in https://github.com/aws/aws-cdk/issues/6692 and close this as a duplicate for the sake of consolidating issues. If there are any distinctions you'd like to clarify please let us know. 

We also recommend adding a 👍 to existing feature requests to show your support, and encourage you to leave comments there if you have any additional related use cases to share.

**Closed by tim-finnigan** 2023-02-15 18:22 UTC
Labels: feature-request, package/tools, needs-triage
