### ISSUE TITLE
Autoscale Group: Can't Set block_device_mappings 

### ISSUE THREAD

**Issue by actiontofu** [aws/aws-cdk#3524] opened 2019-08-02 20:12 UTC
In cloud formation, we can set the block_device_mappings directly for nodes in an autoscale group, but can't access this property through CDK.

On line 403 of auto-scaling-group.ts, the CfnLaunchConfiguration for the group is created but not exposed as a public member. 

CfnLaunchConfiguration has an exposed option to set block_device_mappings, but it can't be set through AutoscalingGroup. 

Requesting that either we can provide block_device_mappings through the AutoscaleGroup constructor, or expose the CfnLaunchConfiguration for modification.

**Comment by eladb** [comment] 2019-08-13 10:08
I believe this is a duplicate of #3622

**Closed** 2019-08-13 12:17 UTC
Labels: service/ec2
