### ISSUE TITLE
Resources created by CDK missing in console

### ISSUE THREAD

**Issue by eiva** [aws/aws-cdk#8346] opened 2020-06-03 16:41 UTC
Not sure who is responsible for this bug: CloudFormation or CDK, but this is super annoying:

CDK runs into permanent state when any creation of resource **with name** reported as Successful while there is no any resource is created.

### Reproduction Steps
1. Define Activity CDK (also works for IAM roles, StepFunctions):
    ```
    val activity = Activity.Builder.create(this, "FirstName").activityName("FirstName").build()
    ```
    Make sure that deployment passed correctly and there activity is actually exists
2. Delete it from CDK
    Make sure that CF report that deletion succeeded.
    Verify that resource is actually gone.
3. Add it back
    ```
    val activity = Activity.Builder.create(this, "FirstName").activityName("FirstName").build()
    ```
    Run deployment
    Check console:
    ```
     9/44 | 4:25:25 PM | CREATE_COMPLETE      | AWS::StepFunctions::Activity     | FirstName (FirstName306E36D3)
    ```
    - Open CloudFormation template and see: `CREATE_COMPLETE`
       Check that there is everything green in event log - all green and reports as resource creted.
    - Click on *Physical ID* and enjoy **404 resource not found**.
    - Check that there is no anything in activities list.
4. Try to delete, change properties etc runs into error that there is no such resource.
   
### Error Log

No errors. All Green.
Resource is not created.

### Environment

  - **CLI Version      :** 1.23?
  - **Framework Version:** 1.23
  - **Node.js Version:** 12.18.0
  - **OS               :** linux
  - **Language (Version):**  Java (8)

### Other

--- 

This is :bug: Bug Report

**Comment by eiva** [comment] 2020-06-03 16:53
Additional observation: If I use `Cfn*` analog (not high level CDK) I can`t reproduce same problem.

**Comment by am29d** [comment] 2020-06-15 13:50
The resource link for an Activity in CloudFormation console is pointing to "Tasks" which redirects to the service /homepage.

The resource id link is:

https://eu-central-1.console.aws.amazon.com/states/home?region=eu-central-1#/tasks

but it should be 

https://eu-central-1.console.aws.amazon.com/states/home?region=eu-central-1#/activities

Apart from that I could not reproduce the issue in my build, used same version, just running on macOs Catalina. I could see the activity in stepfunctions console and fetch the list via aws cli :/

**Comment by shivlaks** [comment] 2020-07-29 06:57
@am29d  thanks for logging this issue! I don't believe this is a CDK bug as it appears to be an incorrect link generated in the CloudFormation console.

I'll find the stakeholders that can address this issue. For now I'm marking this as guidance instead of a bug.

**Comment by PatMyron** [comment] 2020-09-29 05:17
see https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/139 if this is just an incorrect console link

**Comment by rix0rrr** [comment] 2021-01-26 14:32
Not really actionable for us. Sorry.

**Closed by rix0rrr** 2021-01-26 14:32 UTC
Labels: blocked, bug, needs-cfn, package/tools
