### ISSUE TITLE
aws_cdk.aws_lambda_python_alpha: Standard Docker image for building PythonLayerVersion

### ISSUE THREAD

**Issue by lordsilver** [aws/aws-cdk#24862] opened 2023-03-30 00:17 UTC
### Describe the feature

I'd like to ask why there's the need to create a new Docker image for every time you execute `cdk synth`? They look to be the exact same Docker image, sharing the exact same layers, so I don't understand. Wouldn't be possible to have a standard Docker build image similarly to SAM `amazon/aws-sam-cli-build-image-python3.9`? Also, is this Docker image that gets used to zip your `PythonLayerVersion `defined in any module?

![cdk-docker-images](https://user-images.githubusercontent.com/10464497/228695916-5eafb066-4eed-4b77-8df4-4a9e3e35affc.png)

### Use Case

Avoid proliferation of Docker images when building `PythonLayerVersion`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.70.0

### Environment details (OS name and version, etc.)

Windows 11 22H2

**Comment by peterwoodworth** [comment] 2023-03-30 01:42
Thanks for the request! We actually have a request open already to address docker running every time, I'll be closing this issue as a duplicate of that https://github.com/aws/aws-cdk/issues/23829

Also, you can view the dockerfile used here https://github.com/aws/aws-cdk/blob/v2.72.0/packages/%40aws-cdk/aws-lambda-python/lib/Dockerfile

**Closed by peterwoodworth** 2023-03-30 01:42 UTC
Labels: duplicate, feature-request, @aws-cdk/aws-lambda-python
