### ISSUE TITLE
(cdk): Race condition and ChangeSetNotFound when using cdk deploy --no-execute

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#13187] opened 2021-02-22 03:12 UTC
When you use `cdk deploy --no-execute` to create a ChangeSet, and immediately execute the new ChangeSet e.g. from an EventBridge listener, CloudFormation immediately deletes the executed ChangeSet and confuses CDK. Apparently CDK tries to load the ChangeSet after creating it and throws an error when it doesn't exist any more. This doesn't happen every time and seems like it's a race condition.

### Reproduction Steps

Use the --no-execute option and immediately execute the created ChangeSet so that it disappears from CloudFormation before CDK has finished running. I'm running CDK in a Lambda function which may make it run a bit slower:

```
  await cdkToolkit.deploy({
    stackNames: [stackName],
    usePreviousParameters: true,
    requireApproval: RequireApproval.Never,
    execute: false,
  })
```

### What did you expect to happen?

CDK should realize that if the ChangeSet disappears after creating it, it has already been executed by some other process in the background. CDK should then return successfully instead of throwing an error.

### What actually happened?

CDK throws an error like this:

```
ChangeSetNotFound: ChangeSet [cdk-deploy-change-set] does not exist
```

### Environment

  - **CDK CLI Version  :** 1.90.1
  - **Framework Version:** 1.90.1
  - **Node.js Version:** v12.20.1
  - **OS               :** Linux
  - **Language (Version):** TypeScript

### Other

I didn't actually debug the deploy() method to see what it does while running. The problem doesn't occur every time so I assume it's a race condition that occurs randomly.

The race condition probably happens between calling `createChangeSet` and `waitForChangeSet`: https://github.com/aws/aws-cdk/blob/6aac3b6a9bb1586ee16e7a85ca657b544d0f8304/packages/aws-cdk/lib/api/deploy-stack.ts#L243-L257

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-02-23 08:26
This could be true, and is probably due to the time between `createChangeSet` and `describeChangeSet`.

We did make changes there recently but I don't see how they could have caused this behavior. This must have been in there for a while already.

> CDK should realize that if the ChangeSet disappears after creating it, it has already been executed by some other process in the background. CDK should then return successfully instead of throwing an error.

Not sure that I agree with this statement. CDK CLI is fundamentally a single-threaded program, and it is reasonable for it to assume it's the only tool operating on the change sets it is producing until it has finished. Executing `cdk deploy` should be considered an atomic action (from the PoV of the CDK CLI). If we can't make those kinds of assumptions, it will be nigh impossible to build any kind of reliable system from small self-contained parts.

For your use case, how about adding either a sleep, or creating the change set yourself without the involvement of the CDK CLI?

**Comment by kennu** [comment] 2021-02-23 14:58
I understand CDK CLI is single-threaded, but that doesn't preclude the possibility of using e.g. AWS EventBridge events to automatically execute the ChangeSet created by CDK CLI. I can of course add a delay to the event handler Lambda function, but delays are not a great way to solve race conditions; they just make them more rare.

Is there any particular reason why CDK CLI could not function the way I suggested, by assuming that if the changeset disappears after calling CreateChangeSet, it has already been executed by another process?

**Comment by kennu** [comment] 2021-02-23 15:22
To add another solution note, since CDK_CHANGE_SET_NAME is now a fixed name, it's possible to also wait for the CDK CLI deploy command to complete and then execute the ChangeSet programmatically. I will probably do it like that, if I can't trust the EventBridge event handler. However, I'm predicting that eventually someone will run into the same race condition in a CI context.

**Comment by rix0rrr** [comment] 2021-02-24 11:00
I have to say I don't really understand the event-driven use case. 

Doing a `cdk deploy --no-execute && execute-change-set-using-custom-process`, I *do* understand and that's why I think the fixed CS name will provide a superior experience for those use cases.

I would say the latter is the recommended way to do it (in my mind), and that's what the `--no-execute` flag was designed for.

**Comment by kennu** [comment] 2021-02-24 15:37
In my particular case, I'm running CDK in a Lambda, and I don't want to wait for the entire ChangeSet execution to complete inside the Lambda. So I used EventBridge to automatically execute the ChangeSet once it appears (triggered by CreateChangeSet), and I then track completion with Step Functions (triggered by ExecuteChangeSet or CreateStack). 

In other words, my plan was to have a short-lived Lambda that only runs  CDK deploy --no-execute to create the ChangeSet, and from there on use AWS eventing features to execute and track the ChangeSet.

I thought this was a nice, clean event-driven way to do it, but the race condition got in the way. So now I need to work around it by also executing the ChangeSet inside the Lambda.

I know it's not a huge deal, but the principle bothers me. I think it would be fair to assume that once you get the CreateChangeSet event from EventBridge, you can act on it right away, instead of separately also waiting for CDK to complete.

**Comment by rix0rrr** [comment] 2021-02-24 15:46
Your setup does sound kind of fun.

I *guess* it's not infeasible. The CLI now does 2 things after creating the change set:

* Waiting for it to become ready.
* Checking if its empty, and returning that value to the caller

The first one is easy enough to kind of shrug our shoulders and go "fine" if the change set disappears while we're waiting for it and we don't plan to execute anyway (printing an appropriate message).

The second step is a little tougher; we'd have to look at how the return values are used to see if it's safe to just slam any old value in there (`true` or `false`) or whether we need to resort to an honest-to-goodness "I don't know" return value.

If you feel like going in there and making those changes, I will support them. We're unlikely to pick this up ourselves though.

**Comment by kennu** [comment] 2021-02-24 15:58
Thanks @rix0rrr. My use case also involves decdk and https://github.com/aws/aws-cdk/issues/12349 which makes it very slow to run the Lambda function in the first place (several minutes). I'll go forward with my own development and workarounds/optimizations, and I'll see if I can contribute something useful later on. I don't know if you want to keep this issue open or closed, but I'm happy the topic got acknowledged.

**Comment by rix0rrr** [comment] 2021-02-24 17:53
I will close it then, in a vain bid to keep our backlog under control. Good luck with your workarounds.

**Closed by rix0rrr** 2021-02-24 17:53 UTC
Labels: bug, needs-triage, package/tools
