### ISSUE TITLE
Nested stacks do not handle IAM role created in parent stack    

### ISSUE THREAD

**Issue by wimzyLive** [aws/aws-cdk#4779] opened 2019-10-31 09:11 UTC
### Description 
When creating nested stack which depends on IAM Role created by parent stack with default policy, cloudformation deployment fails.

Role is created by parent stack with default policy, so Nested stack adds Depends on attribute for role and default policy. Role and Default Policy are declared in separate stack, so while deploying nested stack cloudformation errors with `Template format error: Unresolved resource dependencies [RoleDefaultPolicyxxxx, Rolexxxx] in the Resources block of the template` , but synth works perfectly fine.
.

### Reproduction Steps
For example consider below `Parent` and `Child` stacks.
```typescript
import { Role, ServicePrincipal, IRole } from '@aws-cdk/aws-iam';
import { NestedStack, NestedStackProps } from '@aws-cdk/aws-cloudformation';
import { Pipeline, Artifact } from '@aws-cdk/aws-codepipeline';
import { Bucket } from '@aws-cdk/aws-s3';
import { Construct, Stack, App, StackProps } from '@aws-cdk/core';
import { ManualApprovalAction, S3SourceAction, S3Trigger } from '@aws-cdk/aws-codepipeline-actions';
interface ChildStackProps extends NestedStackProps {
  pipelineRole: IRole;
}
class ChildStack extends NestedStack {
  constructor(scope: Construct, id: string, props: ChildStackProps) {
    super(scope, id, props);

    const sourceOutput = new Artifact();
    new Pipeline(this, 'Pipeline', {
      role: props.pipelineRole,
      stages: [
        {
          stageName: 'first',
          actions: [
            new S3SourceAction({
              runOrder: 1,
              actionName: 'Checkout',
              bucket: Bucket.fromBucketName(this, 'bucket', 'some-bucket'),
              bucketKey: 'some-key',
              output: sourceOutput,
              trigger: S3Trigger.POLL
            })
          ]
        },
        {
          stageName: 'second',
          actions: [
            new ManualApprovalAction({
              runOrder: 1,
              actionName: 'Approve'
            })
          ]
        }
      ]
    });
  }
}

class ParentStack extends Stack {
  constructor(scope: App, id: string, props: StackProps) {
    super(scope, id, props);

    const pipelineRole = new Role(this, 'PipelineRole', {
      assumedBy: new ServicePrincipal('codepipeline.amazonaws.com')
    });

    new ChildStack(this, 'ChildStack', {
      pipelineRole
    });
  }
}

const app = new App();
new ParentStack(app, 'ParentStack', {
  stackName: 'parent-stack-with-one-child-stack'
});
app.synth();

```

### Error Log

`Template format error: Unresolved resource dependencies [PipelineRoleDefaultPolicyxxxx, PipelineRolexxxx] in the Resources block of the template`

### Environment

  - **CLI Version      : *1.15.0 (build bdbe3aa)*
  - **Framework Version: *1.15.0*
  - **OS               :*MacOs*
  - **Language         :*Typescript*

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2019-11-01 09:02
Duplicate of https://github.com/aws/aws-cdk/issues/4406

**Closed by rix0rrr** 2019-11-01 09:02 UTC
Labels: bug, package/iam, status/needs-triage
