### ISSUE TITLE
 Step Machine definition lacks proper formatting

### ISSUE THREAD

**Issue by kristianpaul** [aws/aws-cdk#7900] opened 2020-05-11 00:06 UTC
The synthesized Cloudformation from of a step-machine cdk definition lacks formatting.

State machine ( `AWS::StepFunctions::StateMachine`) JSON Strings (`DefinitionString`) is generated in a single line, new lines characters  (\n) and spaces could be added to provide proper visualization in the AWS Console since this is still used to check step-machine execution steps. Been able to visualize the step machine code properly helps the *Developer User Experience.* Currently this is an undesired outcome.

There is a  **workaround** to fix this and consists in Editing State machine definition and formatting it from the AWS Console.

### Reproduction Steps
Create CDK Typescript App with following code:
```
import * as cdk from '@aws-cdk/core';
import * as sfn from '@aws-cdk/aws-stepfunctions';

export class CdkWorkshopStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const pass = new sfn.Pass(this, 'Pass');

    const step_definition = pass;

    new sfn.StateMachine(this, 'StateMachine', {
      definition: step_definition,
      timeout: cdk.Duration.seconds(30)
    });
  }
}
```
### Comparison

Generated cloudformation resource property for the `AWS::StepFunctions::StateMachine` type:

`DefinitionString: '{"StartAt":"Pass","States":{"Pass":{"Type":"Pass","End":true}},"TimeoutSeconds":30}'`

Expected output:

`DefinitionString":"{\n  \"StartAt\": \"Pass\",\n  \"States\": {\n    \"Pass\": {\n      \"Type\": \"Pass\",\n      \"End\": true\n    }\n  },\n  \"TimeoutSeconds\": 30\n}"`

### Environment

  - **CLI Version      :*1.38.0 (build d5fa31f)*
  - **Framework Version:**
  - **OS               :*Ubuntu 20.04*
  - **Language         :*en*

### Other

Side comparison of AWS Console.
Default:

![image](https://user-images.githubusercontent.com/326463/81513411-eb408500-92ed-11ea-8c58-d695a4a88200.png)

Expected:

![image](https://user-images.githubusercontent.com/326463/81513417-fdbabe80-92ed-11ea-9fee-d036f989a465.png)

**With lager state machine definition the cumbersome is to visualize it in the editor*

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-05-13 10:38
Hello @kristianpaul -

Thanks for filing this issue. While this is not a desirable outcome, this is not a bug. We don't expect customers to edit the state machine definition after generating it out of the CDK. 
However, this is a reasonable request given that the CloudFormation template we generate is well formatted.

I've re-marked this as a feature request, instead of a bug.

**Comment by kristianpaul** [comment] 2020-05-13 18:29
@nija-at  Agree. I don't expect customer editing the state machine editor but at least been able to visualize it properly since is there going to be some interaction expected from the AWS Console having the json un-formatted doesn't help much.

**Comment by erik-telesoftas** [comment] 2020-05-22 03:13
If you edit state machine in AWS Console there is option to format JSON there.

I would not expect CDK to output formatted JSON, which takes more bandwidth and increases template size.

**Comment by kristianpaul** [comment] 2020-05-22 04:30
@erik-telesoftas Your comment is actually described as workaround already as part of the description of this issue.

About the JSON template size isnt your concern applicable when definiting other resources anyway? Whats the difference here?

**Comment by wong-a** [comment] 2020-06-17 22:22
@kristianpaul By "visualize" you're just referring to viewing the JSON in the Step Functions console, right? Whether the definition is in a single line or pretty-printed has no effect on the rendering of the graph. Pretty-printing the definition without having to edit is something we could add to the Step Functions console. 

I don't think the CDK should do this by default for the reasons others already mentioned. State machines and CFN templates have size limits. Existing stacks could exceeded these limits if they became the default. I don't see any concerns in making formatting optional though.

Do you look at the JSON definition in any place besides the console?

**Comment by kristianpaul** [comment] 2020-06-18 02:05
> Pretty-printing the definition without having to edit is something we could add to the Step Functions console.

Please

> I don't see any concerns in making formatting optional though.

That works also. I wouldn’t bother asking for this if I haven’t had to use the console but as of right now I cant easily visualize step function execution by CLI only.

> Do you look at the JSON definition in any place besides the console?

Just the console.

**Comment by wong-a** [comment] 2020-06-18 03:47
@kristianpaul As an alternative to the console, you can visualize the graph (and format the code) in VS Code using the [AWS Toolkit](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode).

See:
* https://aws.amazon.com/blogs/compute/aws-step-functions-support-in-visual-studio-code/
* https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode

![img](https://d2908q01vomqb2.cloudfront.net/1b6453892473a467d07372d45eb05abc2031647a/2020/04/01/state-machine-preview-1.png)

**Comment by shivlaks** [comment] 2020-06-18 06:26
discussed this with @wong-a earlier today, and I think the issue has been described and summarized nicely already, but I'll recap just in case.

We are going to shoot for improving this experience by formatting the state definition string in the Step Functions console so it's human readable.

This solution will not require CDK customers to make any code changes, upgrade their versions, and most importantly does not run the risk of bloating template sizes beyond their limits.
Optimizing for downstream rendering at the CDK layer is not the right place to address the issue for the reasons mentioned in this thread.

Internal tracking issue: SFNDX-1378

**Comment by kristianpaul** [comment] 2020-06-19 02:45
@wong-a I’m fully aware of vscode + aws toolkit capabilities (.asl file creation and visualizing among others) and i don’t see the relation of those features with the cdk feature request described here. Both cdk and vscode + aws toolkit offers their own ways to model aws step functions. I’m not looking to compare or replace each with the other but rather focusing on the usability of resources generated by cdk through the development process of a step function.

**Comment by wong-a** [comment] 2020-06-19 15:32
@kristianpaul I understand that and supporting formatting the JSON definition in CDK and the Step Functions console are not mutually exclusive. I suggested the AWS Toolkit only as an alternative to the console for visualizing existing state machines created through the CDK, not as a replacement for creating resources. This was in response to your [previous reply](https://github.com/aws/aws-cdk/issues/7900#issuecomment-645724589).

**Comment by peterwoodworth** [comment] 2021-04-15 15:51
Closing this issue as no changes will be (or were) made to the CDK for this

**Closed by peterwoodworth** 2021-04-15 15:51 UTC
Labels: @aws-cdk/aws-stepfunctions, effort/medium, feature-request, in-progress, p2

**Comment by kristianpaul** [comment] 2021-04-16 15:47
> Closing this issue as no changes will be (or were) made to the CDK for this

So this is not something you guys plans to work on?

**Comment by wong-a** [comment] 2021-04-22 17:46
@kristianpaul The Step Functions console automatically pretty-prints the JSON in Definition tab on the state machine details page now. A minified definition created with CDK will be displayed with indentation. 

Did you want an option in CDK to generate formatted JSON with newline and space characters when the console displays it with indentation?
