### ISSUE TITLE
(pipelines): Aspect errors registered in Application Stacks not Failing the Synth 

### ISSUE THREAD

**Issue by stlserverless** [aws/aws-cdk#12200] opened 2020-12-22 16:06 UTC
It appears that CDK Pipelines is not working as expected with Aspects.  When an aspect registers an error while traversing the application stack construct tree, it doesn’t fail the synth as expected. In a standalone CDK app with the identical application stack, `cdk synth` fails when the same aspect registers the error. 

### Reproduction Steps

1. Set up a generic CDK Pipeline.
2. Add an aspect that ends up registering an error when walking nodes in the application stack
3. Register that aspect in the application stack
3. Run cdk synth

Here’s a public gist for a CDK Pipeline using the example code from the docs, but also including Aspects: https://gist.github.com/stlserverless/9ff5251113097d92d732db906ecf6b02

### What did you expect to happen?

While walking the CDK construct tree in a CDK application, if an aspect registers an error, the cdk synth fails.

### What actually happened?

While walking the CDK construct tree in a CDK Pipeline, if an aspect is registered in the application stack, while walking the nodes in the application stack during a synth, the aspect registers the error, but the cdk synth does not fail.

### Environment

  - **CDK CLI Version  :** 1.78.0
  - **Framework Version:** Not sure what framework you're asking about
  - **Node.js Version:** v12.16.2
  - **OS               :** MacOS 10.15.7
  - **Language (Version):** TypeScript 3.9.7

### Other

I moved the registration of the aspects around to different parts of the pipeline; i.e. pipeline stack, stage, application stack. In my testing, I found the following:

- If the aspect is registered in the CdkPipelineStack (e.g. `cdk.Aspects.of(this).add(new SomeAspect())`), the application stack nodes do not seem to be walked. However, construct nodes defined in the pipeline stack are walked.
   
- If the aspect is registered in the Stage or application stack, the application stack nodes are walked, but the errors they reproduce do not get "counted" so the `cdk synth` for the pipeline app does not fail. Of course, this means the CDK Pipeline would proceed past the build phase and onto deployment even with Aspect errors occurring in the application stack(s).

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-01-05 10:11
Duplicate of #11631

**Closed by rix0rrr** 2021-01-05 10:11 UTC
Labels: @aws-cdk/pipelines, bug, needs-triage
