### ISSUE TITLE
Return concrete values for physical names and ARNs if explicitly stated

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#4093] opened 2019-09-16 11:59 UTC
### Description

When a user specified an explicit physical name for an AWS resource, the corresponding attributes should also return a concrete name.

For example, if I define a bucket with a `bucketName`:

```ts
const bucket = new s3.Bucket(this, 'MyBucket', { bucketName: 'hello' });
```

Then, I would expect `bucket.bucketName` to return `hello` and not a token that resolves to `{ "Fn::GetAtt": [ ... ] }`

❗️There is a problem: CloudFormation references implicitly indicate that there is a dependency between the consuming resource and the referenced resource. If we return a concrete name (string), this dependency will now be lost forever. Is there anything we can do about it? (@rix0rrr?)

**Comment by rix0rrr** [comment] 2019-09-16 12:11
Doesn't/shouldn't this already work today by means of the `PhysicalName` machinery? As in, if you specify a physicalName, then `bucket.bucketName` already returns the configured value?

If it doesn't work for some particular resource, it's a bug in the implementation of that resource, rather than the system.

Re: recording the implicit reference: tokens can easily be made to do this, with a little extension on what `CfnReference` does today. They have all the required information. However, we'd lose the property that `bucket.bucketName === "hello"`, we'd be back to `bucket.bucketName === "${Token[Bucket.Ref.123]}"`, with the difference that in the template that Token would resolve to a literal instead instead of an intrinsic.

Seems good enough to me, but YMMV?

**Comment by skinny85** [comment] 2019-09-17 18:38
This is a duplicate of #928 . Same reasons posted there apply here as well.

**Closed** 2020-08-17 09:30 UTC
Labels: effort/medium, feature-request, package/awscl
