### ISSUE TITLE
‼️ NOTICE: 'Error: ENOTDIR invalid cwd' on `cdk deploy` in 1.90.0

### ISSUE THREAD

**Issue by qs-wang** [aws/aws-cdk#13131] opened 2021-02-18 07:22 UTC
Please add your +1 👍 to let us know you have encountered this
---

### Update

Version `1.90.1` which includes a fix is released.
 
------ 

There is an issue with the way the CDK assets mechanism identifies already `.zip` file. Currently it will try to zip the already zipped file that will throw an error. We are working on a fix.

### Workaround 
**TL;DR:** delete the `cdk.out` folder before executing `cdk deploy`

The issue occurs when executing `cdk deploy` when there is a `.zip` file in the `cdk.out` folder. This happens when executing `cdk synth` - which creates the `cdk.out` folder, followed by `cdk deploy` (which is a completely normal cdk flow). To workaround this, delete the `cdk.out` folder before executing `cdk deploy`. 

### Repro

Any application which includes an asset with a `.zip` file will fail to deploy:

```ts
new lambda.Function(this, 'MyLambda', {
      code: lambda.Code.fromAsset(path.join(__dirname, '../my-zip.zip')),
      handler: 'index.handler',
      runtime: lambda.Runtime.NODEJS_12_X
 })
```

**important:** execute `cdk synth` **before** executing `cdk deploy`

`cdk deploy` will throw:

```
UnhandledPromiseRejectionWarning: Error: ENOTDIR invalid cwd 
```
### Overview:

When running `cdk deploy` in version `1.90.0` on a Stack that contains assets, you might see an error like `'Error: ENOTDIR invalid cwd`.

#### Complete Error Message:

```
$ npx cdk deploy --require-approval=never 
Bug13131Stack: deploying...
[0%] start: Publishing e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68:current
(node:81012) UnhandledPromiseRejectionWarning: Error: ENOTDIR invalid cwd /Users/adamruka/workplace/cdk/on-call/bug-13131/cdk.out/asset.e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68.zip
    at GlobSync._readdirError (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/glob/sync.js:324:21)
    at GlobSync._readdir (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/glob/sync.js:290:10)
    at GlobSync._processGlobStar (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/glob/sync.js:350:22)
    at GlobSync._process (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/glob/sync.js:130:10)
    at new GlobSync (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/glob/sync.js:48:10)
    at Function.globSync [as sync] (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/glob/sync.js:26:10)
    at Promise (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/archive.ts:17:24)
    at new Promise (<anonymous>)
    at Object.zipDirectory (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/archive.ts:7:10)
    at FileAssetHandler.packageFile (/Users/adamruka/workplace/cdk/on-call/bug-13131/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/handlers/files.ts:78:13)
(node:81012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:81012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

-----------------------------

##### Original bug report

My CDK script was all right, but was failing with the latest 1.90.0 version

###### Reproduction Steps

Run the CDK script via gitlab pipeline

###### What did you expect to happen?

No errors
###### What actually happened?

See the error message as below:

```
xxxx- infra-Dev: deploying...
[0%] start: Publishing 45f6bfc57a7695260616f2916fbef2dd77200af18743d956a59c8db9c3816b3f:current
(node:55) UnhandledPromiseRejectionWarning: Error: ENOTDIR invalid cwd /builds/xxxx/cdk.out/asset.45f6bfc57a7695260616f2916fbef2dd77200af18743d956a59c8db9c3816b3f.sh
    at GlobSync._readdirError (/usr/local/lib/node_modules/aws-cdk/node_modules/glob/sync.js:324:21)
    at GlobSync._readdir (/usr/local/lib/node_modules/aws-cdk/node_modules/glob/sync.js:290:10)
    at GlobSync._processGlobStar (/usr/local/lib/node_modules/aws-cdk/node_modules/glob/sync.js:350:22)
    at GlobSync._process (/usr/local/lib/node_modules/aws-cdk/node_modules/glob/sync.js:130:10)
    at new GlobSync (/usr/local/lib/node_modules/aws-cdk/node_modules/glob/sync.js:48:10)
    at Function.globSync [as sync] (/usr/local/lib/node_modules/aws-cdk/node_modules/glob/sync.js:26:10)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/archive.ts:17:24
    at new Promise (<anonymous>)
    at Object.zipDirectory (/usr/local/lib/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/archive.ts:7:10)
    at FileAssetHandler.packageFile (/usr/local/lib/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/handlers/files.ts:78:13)
(node:55) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:55) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

##### Environment

  - **CDK CLI Version  :** 1.90.0
  - **Framework Version: **1.90.0
  - **Node.js Version: **12
  - **OS               :** Docker
  - **Language (Version):**  Python (3.8) 

###### Other
Rollback to 1.89.0 fixed the problem

--- 

This is :bug: Bug Report

**Comment by SachinSureshLondhe** [comment] 2021-02-18 13:48
I am also experiencing the same with latest cdk version.

**Comment by mohdwasee** [comment] 2021-02-18 14:02
Facing same issue with me as well

**Comment by morgler** [comment] 2021-02-18 16:56
I get the same error when trying to deploy a simple static website:

```
const deployment = new s3deploy.BucketDeployment(this, 'DeployFrontend', {
      sources: [s3deploy.Source.asset('./frontend/dist')],
      destinationBucket: siteBucket,
      distribution,
      distributionPaths: ['/*']
    })
```

Version is also 1.90.0

**Comment by bigkraig** [comment] 2021-02-18 18:10
I've noticed the same problem when using a BucketDeployment. The zip exists at the path and contains awscli.

```
Do you wish to deploy these changes (y/n)? y
cwf-kraig-f9aca73e: deploying...
[0%] start: Publishing e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68:739368017290-us-west-2

/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:324
        var error = new Error(er.code + ' invalid cwd ' + this.cwd)
                    ^
Error: ENOTDIR invalid cwd /Users/kamador/src/service/sysops/cdk/cdk.out/asset.e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68.zip
    at GlobSync._readdirError (/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:324:21)
    at GlobSync._readdir (/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:290:10)
    at GlobSync._processGlobStar (/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:350:22)
    at GlobSync._process (/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:130:10)
    at new GlobSync (/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:48:10)
    at Function.globSync [as sync] (/Users/kamador/src/service/sysops/cdk/node_modules/glob/sync.js:26:10)
    at /Users/kamador/src/service/sysops/cdk/node_modules/cdk-assets/lib/private/archive.ts:17:24
    at new Promise (<anonymous>)
    at Object.zipDirectory (/Users/kamador/src/service/sysops/cdk/node_modules/cdk-assets/lib/private/archive.ts:7:10)
    at FileAssetHandler.packageFile (/Users/kamador/src/service/sysops/cdk/node_modules/cdk-assets/lib/private/handlers/files.ts:78:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by skinny85** [comment] 2021-02-18 18:26
Confirming I was able to reproduce this. We're working on a fix.

**Comment by michaelbrewer** [comment] 2021-02-18 21:57
Are we missing some test cases to prevent this from happening again?

**Comment by NetaNir** [comment] 2021-02-18 22:03
If everyone (or some) who are seeing this issue can comment with the node version they are using, it will help us debug it. Thanks!

**Comment by mark-ship-it** [comment] 2021-02-18 22:20
I am using node v14.15.0

**Comment by AjkayAlan** [comment] 2021-02-18 22:36
Node v14.15.5 for us, which is the latest default node version on GitHub Actions Linux Agents and Azure DevOps Linux Agents (per https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md).

**Comment by w601sxs** [comment] 2021-02-18 23:00
Help! Using Cloud9 to deploy this stack fails https://github.com/aws-samples/faropt

worked until last week and have tested in few regions now

Node v10.23.3
CDK 1.89.0 (build df7253c)

Trace is 

Do you wish to deploy these changes (y/n)? y
faropt: deploying...
[0%] start: Publishing 4b6bf88ce4fd3e5943d206b3300f8d5846e09675d09aae093934d92df866158c:current
[16%] success: Published 4b6bf88ce4fd3e5943d206b3300f8d5846e09675d09aae093934d92df866158c:current
[16%] start: Publishing 8c227cb226e60cc02fb88f016ad06f18182fae243c2aac8a27e023431583d22a:current
(node:6971) UnhandledPromiseRejectionWarning: **Error: ENOTDIR invalid cwd /home/ec2-user/environment/faropt/cdk.out/asset.8c227cb226e60cc02fb88f016ad06f18182fae243c2aac8a27e023431583d22a.zip**
    at GlobSync._readdirError (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/glob/sync.js:324:21)
    at GlobSync._readdir (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/glob/sync.js:290:10)
    at GlobSync._processGlobStar (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/glob/sync.js:350:22)
    at GlobSync._process (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/glob/sync.js:130:10)
    at new GlobSync (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/glob/sync.js:48:10)
    at Function.globSync [as sync] (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/glob/sync.js:26:10)
    at Promise (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/archive.ts:17:24)
    at new Promise (<anonymous>)
    at Object.zipDirectory (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/archive.ts:7:10)
    at FileAssetHandler.packageFile (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/cdk/node_modules/aws-cdk/node_modules/cdk-assets/lib/private/handlers/files.ts:78:13)
(node:6971) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:6971) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NetaNir** [comment] 2021-02-18 23:02
@w601sxs an you verify the CDK version? and that you are not using 1.90, which we suspect have the bug?

**Comment by bigkraig** [comment] 2021-02-18 23:08
im using v15.8.0, after also seeing this problem with a brew installed node v14

**Comment by NetaNir** [comment] 2021-02-18 23:18
@bigkraig which CDK version?

**Comment by bigkraig** [comment] 2021-02-18 23:24
my bad, 1.90.0

**Comment by NetaNir** [comment] 2021-02-18 23:28
@bigkraig would you mind verifying that it works with 1.89? I suspect it will not, and the problem is actually in one of our transient dependencies

**Comment by bigkraig** [comment] 2021-02-19 00:06
@NetaNir i actually had tried to do that right away but ran into a NPM dependency nightmare that i ultimately didn't have time to keep beating my head against, vowing to wait until this PR was resolved. i'll see if i can get some time to look at this again but it might not be until my lunch tomorrow.

**Comment by mark-ship-it** [comment] 2021-02-19 00:10
@NetaNir , I can confirm my deployment worked with 1.89

**Comment by NetaNir** [comment] 2021-02-19 01:24
Probably related: https://github.com/aws/aws-cdk/issues/12536

**Comment by ccaaau** [comment] 2021-02-19 02:10
I think @NetaNir is right that it has something to do with dependencies.

Notes:

* Wont allow upgrade from 1.89 to 1.90
* Modifies dependencies so that @aws-cdk/aws-ec2 is 1.90 but others are 1.89 - almost as if it stops updating dependencies there
* Will generate all sorts of compatibility errors including type errors
* Affects not only parent project but its module folders (makes it complicated to cleanup)
* Delete of node modules folder will require a clear of cache
* Breaks after issuing update command multiple times (works only first time)
* Even if resolved in project scope will generate an error because chances are global installs of modules need to be resolved also
* Even after conflicts are resolved it will error as @bigkraig noted

**Comment by cod3monk3y** [comment] 2021-02-19 02:54
> 
> 
> @bigkraig would you mind verifying that it works with 1.89? I suspect it will not, and the problem is actually in one of our transient dependencies

I'm seeing the error with:

node v14.15.5
cdk 1.89.0 (build df7253c)

**Comment by NetaNir** [comment] 2021-02-19 02:57
> cdk 1.89.0 

Can you verify that this is in fact the version of the CDK CLI (aws-cdk) used? `cdk --version`. All reports we have seen so far only see the problem in version `1.90.0`

**Comment by ccaaau** [comment] 2021-02-19 02:58
Anyone using cdk-assume-role-credential-plugin ?

**Comment by cod3monk3y** [comment] 2021-02-19 02:59
> 
> 
> > cdk 1.89.0
> 
> Can you verify that this is in fact the version of the CDK CLI (aws-cdk) used? `cdk --version`. All reports we have seen so far only see the problem in version `1.90.0`

Yes, that is how I got the version numbers.

```
(.venv) ...>node --version
v14.15.5

(.venv) ...>cdk --version
1.89.0 (build df7253c)
```

**Comment by cod3monk3y** [comment] 2021-02-19 03:13
Repro

```
from aws_cdk import (
    aws_s3 as s3,
    aws_s3_deployment as s3_deploy,
    aws_s3_assets as s3_assets,
    core
)
import os.path
_DIRNAME = os.path.dirname(__file__)


class MyStack(core.Stack):

    def __init__(self, scope: core.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        website_bucket = s3.Bucket(
            self, "WebsiteBucket",
            website_index_document="index.html",
            public_read_access=True
        )
        s3_deploy.BucketDeployment(
            self, "DeployWebsite",
            sources=[
                s3_deploy.Source.asset("./web/static")
            ],
            destination_bucket=website_bucket,
            destination_key_prefix="web/static"
        )
```

Contents of web/static is just a single simple index.html file.

```
(.venv) ...>node --version
v14.15.5

(.venv) ...>cdk --version
1.89.0 (build df7253c)
```

And deploy response (redacted)...

```
(.venv) E:\******>cdk deploy
This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

...

Do you wish to deploy these changes (y/n)? y
REDACTED: deploying...
[0%] start: Publishing XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:current
(node:23728) UnhandledPromiseRejectionWarning: Error: ENOTDIR invalid cwd E:\******\cdk.out\asset.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.zip
    at GlobSync._readdirError (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\glob\sync.js:324:21)
    at GlobSync._readdir (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\glob\sync.js:290:10)
    at GlobSync._processGlobStar (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\glob\sync.js:350:22)
    at GlobSync._process (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\glob\sync.js:130:10)
    at new GlobSync (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\glob\sync.js:48:10)
    at Function.globSync [as sync] (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\glob\sync.js:26:10)
    at C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\cdk-assets\lib\private\archive.ts:17:24
    at new Promise (<anonymous>)
    at Object.zipDirectory (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\cdk-assets\lib\private\archive.ts:7:10)
    at FileAssetHandler.packageFile (C:\Users\********\AppData\Roaming\npm\node_modules\aws-cdk\node_modules\cdk-assets\lib\private\handlers\files.ts:78:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (re
jection id: 1)
(node:23728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the exact same code as listed in the official docs for [aws_s3_deployment](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3_deployment/README.html#aws-s3-deployment-construct-library)

**Comment by cod3monk3y** [comment] 2021-02-19 03:16
Update: `cdk --version` is `1.89.0`, but `pip list` shows `aws-cdk.*` as Version `1.90.0`

**Comment by ccaaau** [comment] 2021-02-19 03:33
Updating package configuration from:

"@aws-cdk/aws-ec2": "^1.89.0",
"@aws-cdk/aws-elasticbeanstalk": "^1.89.0",
"@aws-cdk/aws-s3-assets": "^1.89.0",

to

"@aws-cdk/aws-ec2": "1.89.0",
"@aws-cdk/aws-elasticbeanstalk": "1.89.0",
"@aws-cdk/aws-s3-assets": "1.89.0",

Fixed the problem for me. I'm not sure which is the culprit. Using the ^ (Compatible with version) seems to have something to do with it. Has to be specifically 1.89.0 - though I have not tried this fix with 1.90.0...

**Comment by michaelbrewer** [comment] 2021-02-19 04:25
> Are we missing some test cases to prevent this from happening again?

For me it was: 
* node: `v12.20.2`
* cdk: `1.90.0`
* stacks written in kotlin on `1.90.0`

Otherwise, would there be a version that does not rely on node being installed? And can the cdk team include real end to end test cases deploying to a dummy aws account for stable releases?

**Comment by NetaNir** [comment] 2021-02-19 05:03
Thanks everyone, we found the problem and we are working on a fix. The problem was introduced in version `1.90.0` and affect all node version. We are on it

**Comment by eladb** [comment] 2021-02-19 07:15
Revert https://github.com/aws/aws-cdk/pull/13145

**Comment by NetaNir** [comment] 2021-02-19 08:20
opening issue until we release the patch

**Comment by NetaNir** [comment] 2021-02-19 08:34
Added a workaround to the issue description, **TL;DR**: delete the `cdk.out` folder before executing `cdk deploy`.

A patch is on the way!

**Comment by jogold** [comment] 2021-02-19 09:12
@NetaNir @eladb found the bug and running `synth` two times with also reproduce it.

After the first `synth` the `manifest.json` correctly sets the `packaging` to `file` in the `manifest.json`. But then the asset cache comes into play and the second time it runs `packaging` is now set to `zip` in the `manifest.json`.

This is because staging doesn't rerun:
https://github.com/aws/aws-cdk/blob/cd7a3ed333570a3b26446e1e3a054ca886cd3906/packages/%40aws-cdk/core/lib/asset-staging.ts#L191
and the `FileAssetPackaging` is set in the staging private methods not in the constructor.

On it.

This is only #13076.

**Comment by eladb** [comment] 2021-02-19 09:22
Thanks @jogold. No rush. We reverted the other commit just because there were some merge conflicts.

**Comment by eke-bb** [comment] 2021-02-19 18:19
Using node v14.15.5

**Comment by w601sxs** [comment] 2021-02-19 18:50
> @w601sxs an you verify the CDK version? and that you are not using 1.90, which we suspect have the bug?

Yes, I can confirm it's 1.89

**Comment by baumannalexj** [comment] 2021-02-19 21:16
> If everyone (or some) who are seeing this issue can comment with the node version they are using, it will help us debug it. Thanks!

node v12.20.1

**Closed** 2021-02-20 00:14 UTC
Labels: bug, management/tracking, p0

**Comment by pandrel** [comment] 2021-03-02 16:55
Deleting cdk.out directory did not work 

```
❯ node --version
v15.5.0
```

cdk and module versions

```
├── @aws-cdk/assert@1.90.1
├── @aws-cdk/aws-dynamodb@1.90.1
├── @aws-cdk/aws-ec2@1.90.1
├── @aws-cdk/aws-glue@1.90.1
├── @aws-cdk/aws-lambda@1.90.1
├── @aws-cdk/aws-redshift@1.90.1
├── @aws-cdk/aws-s3-deployment@1.90.1
├── @aws-cdk/aws-s3@1.90.1
├── @aws-cdk/aws-secretsmanager@1.90.1
├── @aws-cdk/aws-ssm@1.90.1
├── @aws-cdk/aws-stepfunctions-tasks@1.90.1
├── @aws-cdk/aws-stepfunctions@1.90.1
├── @aws-cdk/core@1.90.1
├── @types/jest@26.0.20
├── @types/node@10.17.27
├── aws-cdk@1.90.1
├── jest@26.6.3
├── source-map-support@0.5.19
├── ts-jest@26.5.2
├── ts-node@9.1.1
└── typescript@3.9.9
```
