### ISSUE TITLE
eks: lambda handler are attached to VPC

### ISSUE THREAD

**Issue by galsasi1989** [aws/aws-cdk#21122] opened 2022-07-13 15:20 UTC
### Describe the bug

Hi, 

I am trying to create Eks cluster in a private VPC without access to the internet. As far as I understood it's not possible to create the cluster with all the addons(specifically load-balancer controller addon) if I would like to have only private endpoint to the control-plane.
So, at the moment, the access endpoint was configured to be PUBLIC and PRIVATE so all the lambda handlers will be able to communicate with the control-plane. Because my VPC does not have any access to the internet(no public subnets/NAT/IGW), I saw that by default all the lambda handlers should not be attached to the VPC unless I set the parameter placeClusterHandlerInVpc to true(which is not the case).
But, In fact, one lambda function is attached to the VPC - the kubectl handler. This lambda function is responsible for running kubectl/helm commands. Because it's attached to the VPC it can't pull the helm chart of the load-balancer controller, so it's stuck for 15 minutes until timeout exception is thrown.

Is it intentional? It seems like a bug because once I detached the handler from the VPC before it was triggered, the lambda worked as expected.

Eks cluster: v1.21
cdk version: 2.25.0
Language: typescript

### Expected Behavior

Kubectl handler must be detached from the VPC

### Current Behavior

kubectl handler is attached to the VPC

### Reproduction Steps

Need to create an Eks cluster in a private, fully isolated VPC(without public subnets, NAT, IGW etc), including the albcontroller as part of the Cluster construct parameters and follow the kubectl handler lambda function. 

### CDK CLI Version

2.25.0

### Node.js Version

14.18.2

### OS

Ubuntu 20.04(WSL)

### Language

Typescript

**Comment by indrora** [comment] 2022-09-22 21:37
This is a limitation of EKS. Closing as dupe of #12171

**Closed by indrora** 2022-09-22 21:37 UTC
Labels: bug, @aws-cdk/aws-eks, needs-triage
