### ISSUE TITLE
aws-codebuild: Module in node_modules includes both ts and declaration files

### ISSUE THREAD

**Issue by nathanyocum-ridgeline** [aws/aws-cdk#13796] opened 2021-03-25 17:30 UTC
### Reproduction Steps

`yarn add @aws-cdk/aws-codebuild`

`ls node_modules/@aws-cdk/aws-codebuild/node_modules/@aws-cdk/yaml-cfn/lib`

### What did you expect to happen?

the bundled `node_modules/@aws-cdk/aws-codebuild/node_modules/@aws-cdk/yaml-cfn` should be even with `node_modules/@aws-cdk/yaml-cfn`

### What actually happened?

`node_modules/@aws-cdk/aws-codebuild/node_modules/@aws-cdk/yaml-cfn` includes both the declaration files and the `.ts` files, instead of what's in `@aws-cdk/yaml-cfn@1.95.0`

### Environment

  - **CDK CLI Version  :  ** 1.95.0
  - **Framework Version: **
  - **Node.js Version:** 12.19.1
  - **OS               :** OSX
  - **Language (Version):** typescript 4.1.3
### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment] 2021-03-25 17:58
Related: https://github.com/aws/aws-cdk/issues/13795

**Comment by christophgysin** [comment] 2021-03-25 19:00
Seems to be caused by: https://github.com/aws/aws-cdk/commit/182685df16e5c108abb65f878ced63b7d5c3bd4f

**Comment by christophgysin** [comment] 2021-03-26 12:30
This is a duplicate of #13795 and should be closed.

**Closed** 2021-03-26 15:45 UTC
Labels: @aws-cdk/aws-codebuild, bug, needs-triage
