### ISSUE TITLE
(aws-cloudfront): Restrict Viewer Access (aka use signed urls) is missing from distribution behaviour config

### ISSUE THREAD

**Issue by okonon** [aws/aws-cdk#12584] opened 2021-01-19 04:19 UTC
I am trying to create a CF distribution with not publicly accessible S3 bucket Origin using AWS CDK Typescript specifically. I need to configure CloudFront distribution to Restrict Viewer Access using `@aws-cdk/aws-cloudfront` package and i can't seem to find the parameter for that. 

Weird thing is that `smoothStreaming` option is present but Restrict Viewer Access is missing, however these two options are right next to each other in Edit Behavior page of the web console:
![image](https://user-images.githubusercontent.com/1832398/104986121-63fcf280-59e0-11eb-8a2c-695f87283b97.png)

### Reproduction Steps

Create a dist with bucket origin and there is no option to restrict viewer access in default behaviour:
```
    new Distribution(this, `${STAGE}Dist`, {
      defaultBehavior: {
        origin: new S3Origin(this.ref),
        allowedMethods: AllowedMethods.ALLOW_ALL,
        viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        smoothStreaming: true
      }
    });
```

### What did you expect to happen?

I was expecting to pass an option to restrict viewer access right below `smoothStreaming` 

### What actually happened?
There is no such option to pass.

### Environment

  - **CDK CLI Version:**  1.85.0
  - **Framework Version:**  1.85.0
  - **Node.js Version:** v12.16.3
  - **OS               :** MacOS 11.1
  - **Language (Version):** TypeScript (4.1.2)
### Other

This is :bug: Bug Report

**Comment by njlynch** [comment] 2021-01-26 18:00
This seems like a duplicate of #11791.

**Closed by njlynch** 2021-01-26 18:00 UTC
Labels: @aws-cdk/aws-cloudfront, bug, needs-triage
