### ISSUE TITLE
(dynamodb-global): More than 10 global tables breaks service linked polic

### ISSUE THREAD

**Issue by jercra** [aws/aws-cdk#17404] opened 2021-11-08 21:47 UTC
### What is the problem?

CDK creates a policy for each DDB table being provisioned to assign to the service linked policy.  Service linked policies can have a maximum of 10 policies so any stack with more than 10 DDB tables fails to create/update if replication regions are specified.

### Reproduction Steps

Create a stack with > 10 DDB tables with region replication enabled

### What did you expect to happen?

Trying to enable global tables for > 10 DDB tables

### What actually happened?
```sh
11:40:15 AM | CREATE_FAILED        | AWS::IAM::ManagedPolicy             | <TableName>
Cannot exceed quota for PoliciesPerRole: 10 (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded;
Request ID: b811f50d-ee75-400c-b528-30fed2d01180; Proxy: null)

        new ManagedPolicy (/tmp/jsii-kernel-OqDwOA/node_modules/@aws-cdk/aws-iam/lib/managed-policy.js:37:26)
        \_ new SourceTableAttachedPolicy (/tmp/jsii-kernel-OqDwOA/node_modules/@aws-cdk/aws-dynamodb/lib/table.js:1083:24)
        \_ Table.createReplicaTables (/tmp/jsii-kernel-OqDwOA/node_modules/@aws-cdk/aws-dynamodb/lib/table.js:898:38)
        \_ new Table (/tmp/jsii-kernel-OqDwOA/node_modules/@aws-cdk/aws-dynamodb/lib/table.js:494:18)
        \_ /tmp/gsqjdn34.czx/lib/program.js:8432:58
        \_ Kernel._wrapSandboxCode (/tmp/gsqjdn34.czx/lib/program.js:8860:24)
        \_ Kernel._create (/tmp/gsqjdn34.czx/lib/program.js:8432:34)
        \_ Kernel.create (/tmp/gsqjdn34.czx/lib/program.js:8173:29)
        \_ KernelHost.processRequest (/tmp/gsqjdn34.czx/lib/program.js:9757:36)
        \_ KernelHost.run (/tmp/gsqjdn34.czx/lib/program.js:9720:22)
        \_ Immediate._onImmediate (/tmp/gsqjdn34.czx/lib/program.js:9721:46)
        \_ processImmediate (node:internal/timers:464:21)
```
### CDK CLI Version

1.130.0

### Node.js Version

v16.3.0

### OS

Linux LHQ004957310657 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Language

.NET

### Language Version

.NET Core 3.1

**Comment by skinny85** [comment] 2021-11-09 03:13
Hi @jercra,

thanks for opening the issue. This is a duplicate of https://github.com/aws/aws-cdk/issues/13671, check out that issue for some possible workarounds.

Thanks,
Adam

**Closed by skinny85** 2021-11-09 03:13 UTC
Labels: bug, p1, effort/small, needs-reproduction, @aws-cdk/aws-dynamodb-global
