### ISSUE TITLE
[aws-eks] `ec2:DescribeVpcs` permission is missing when creating clusters

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#9027] opened 2020-07-12 11:16 UTC
Today I've also gotten the same error but on the `ec2:DescribeVpcs` permission. This was not the case on Friday because I rolled out an EKS cluster with a CDK build done from the master branch. Adding the DescribeVpcs permission solved the problem, same as the PR in #8859 

Seems like AWS is changing stuff on their end that requires more permissions?

_Originally posted by @jargelo in https://github.com/aws/aws-cdk/issues/8574#issuecomment-654241149_

**Comment by jargelo** [comment] 2020-07-14 12:52
Thanks @eladb , I was about to raise a new issue for this since I wasn't sure you seen my comment.

**Comment by stefanolczak** [comment] 2020-08-24 13:23
I've got the issue when deploying CDK app from scratch ( VPC and EKS as seperate stacks ). Deployment of EKS stack failed with the same error. During redeploy it worked fine. I am using CDK 1.60

**Comment by iliapolo** [comment] 2020-08-24 14:13
@stefanolczak Can you share the code? Thanks

**Comment by stefanolczak** [comment] 2020-08-24 15:12
```
#!/usr/bin/env python3

from aws_cdk import (
    core,
    aws_ec2,
    aws_eks
)


class VpcStack(core.Stack):

    def __init__(self, app: core.App) -> None:
        super().__init__(app, 'vpc-stack')

        self.vpc = aws_ec2.Vpc(
            scope=self,
            id='vpc'
        )


class EksStack(core.Stack):
    def __init__(self, app: core.App, vpc: aws_ec2.Vpc) -> None:
        super().__init__(app, 'eks-stack')

        aws_eks.Cluster(
            scope=self,
            id='eks',
            cluster_name='eks-cluster',
            default_capacity=0,
            version=aws_eks.KubernetesVersion.V1_17,
            vpc=vpc,
            endpoint_access=aws_eks.EndpointAccess.PRIVATE
        )


app = core.App()
vpc_stack = VpcStack(app)
EksStack(app, vpc_stack.vpc)

app.synth()
```

The issue reproduces only on empty AWS account or on AWS account where CDK wasn't used for a while. I'm investigating it more why it does matter.

**Comment by stefanolczak** [comment] 2020-08-24 15:17
I'm almost sure I have once seen other issue ( also with IAM policy ) related to deploying EKS that was fixed by redeploy so I'm guessing there is some global problem in that matter.

**Comment by sandeep-balouria** [comment] 2020-08-24 22:44
Upgraded to 1.60.0 
Tried deploying to fresh aws account and failed with this

Failed to create resource. IAM role's policy must include the `ec2:DescribeVpcs` action

redeploy goes through fine.

**Comment by kossmoboleat** [comment] 2020-10-08 08:41
@eladb This issue might have to be reopened. I've had the same issue with CDK 1.66.0 yesterday when trying to deploy a stack from scratch too.

The first try to deploy fails with the mentioned error message but a re-deploy works. Seems the CDK cannot clean up all created stacks/resources and then those are re-used and it succeeds.

I've also checked and the creation role now has the necessary permissions. So I'm speculating the policy is added to late with the changes in the MR when deploying from scratch.

**Comment by iliapolo** [comment] 2020-10-08 08:47
Hi @kossmoboleat - Thanks, yeah looks like there is still something here. Re-opening and we'll investigate.

**Comment by scalasm** [comment] 2020-10-11 20:37
I've got the same issue with CDK 1.67.0 . If you need a simple test project, just use [this on on GitHub](https://github.com/scalasm/aws-k8s-infrastructure-as-code).

You can see the file log in aws-cdk-issue-9027.log . I can confirm what @kossmoboleat: if I run 'cdk deploy' just after this error, then the deploy is succesful :|

**Comment by PerArneng** [comment] 2020-10-15 10:43
I also ran in to this problem when setting up a test cluster. https://github.com/PerArneng/eks-cdk-test/tree/issue_9027 . I ran it against a blank account and then it worked on the second attempt. I also got an email from AWS saying that i was granted access to AWS resources  `You recently requested an AWS Service that required additional validation. Your request has now been validated for AWS Europe (Stockholm) region(s)`

**Comment by aakrem** [comment] 2020-12-06 12:09
Still happening with 1.76.0 and redeploying the stack fixed it

**Comment by iliapolo** [comment] 2020-12-06 15:02
Managed to reproduce this on a blank account as well, and also got the email that @PerArneng mentioned.

I believe the error is coming from a validation that EKS makes on the cluster role, and not necessarily from an operation that requires this action.

What happens is that the cluster role we pass gets created by default like so:

https://github.com/aws/aws-cdk/blob/8216738dc4a496a4114bad46b4a11bc1e205d8bc/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L911-L916

This `AmazonEKSClusterPolicy` **does** contain the `ec2:DescribeVpcs` action, but I suspect that on a blank account, granting usage of a managed policy is what requires this additional validation. 

I'll do some internal investigation to see what the best path forward here.

**Comment by kay-is** [comment] 2020-12-16 12:53
I got the same problem.

A deployment takes 30minutes, so re-deploying isn't a viable workaround for me.

Any other solutions?

**Comment by iliapolo** [comment] 2021-01-03 11:18
We are still investigating the exact set of conditions where this would happen, and how one can avoid it.

**Comment by sunny0826** [comment] 2021-01-05 02:25
I had the same problem with CDK version: `1.80.0 (build 31132ca)`

**Comment by bhargav18** [comment] 2021-01-27 03:40
Same issue with CDK 1.86 on blank account.

**Comment by fspaniol** [comment] 2021-02-09 16:50
Same issue with 1.87.1. Re-deploy did the trick

**Comment by rafaelpereyra** [comment] 2021-02-12 21:23
Hello,

I was able to reproduce this (several times) using a tool that vends new accounts for training. Manually adding a policy to the synthesized CloudFormation Template to the role created by CDK fixed the issue for me:

```
  custernameCreationRole942A9DDE:
    Type: AWS::IAM::Role
    Properties:
      Policies: 
        - PolicyName: PatchForEKSIssues
          PolicyDocument:
            Statement:
              - Action: ec2:Describe*
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
```

**Comment by iliapolo** [comment] 2021-02-17 11:08
I was able to reproduce this multiple times in a single account by manually deleting the `AWSServiceRoleForAmazonEKS` SLR before each deployment. In this scenario (which simulates a blank account) - EKS will create the SLR upon first cluster deployment, and use it for all subsequent deployments as well.

However, seems like there might be an issue with this first deployment flow - which I am following up on internally. 
In the meantime, I can verify that the patch policy @rafaelpereyra suggested solves the issue, and I've created a [PR](https://github.com/aws/aws-cdk/pull/13103) to include it in the default policy of the creation role.

**Closed** 2021-02-18 07:08 UTC
Labels: @aws-cdk/aws-eks, bug, effort/small, investigating, p1

**Comment by dennisvang** [comment] 2024-08-14 17:17
Unrelated to the original post, but it may be useful for people ending up here based on the title: 

`ec2:DescribeVpcs` permission errors may also arise if you try to deploy a cdk-pipeline stack that includes vpc/subnets, without first running `cdk synth` locally and [commiting][1] the resulting `cdk.context.json`.

[1]: https://docs.aws.amazon.com/cdk/v2/guide/context.html#context_construct
