### ISSUE TITLE
(aws-cdk): deployments hanging with macos Big Sur 11.3

### ISSUE THREAD

**Issue by jsauter** [aws/aws-cdk#15278] opened 2021-06-23 17:46 UTC
## :question: General Issue

We have been experiencing consistent application deployment hangs after upgrading to Big Sur 11.3.

### The Question

Since upgrading to Big Sur 11.3 (still an issue in 11.4) we have been having ECONNRESET failures when deploying CDK applications.  This has occurred on 3 macbooks and leaves us in a state where we cannot deploy our applications unless we use docker (using centos).

Templates deploy OK until we hit a certain size.  This was established by removing portions of the template and adding them back until failure.  This was done via adding portions of our init metadata back to the template.  

I have included two templates, one works with 24 metadata items, the other fails at 25 metadata items.

Test results from these:

macos Catalina 10.15.7: 24 metadata items works, 25 metadata items works, and creates the change set right away
macos Big Sur 11.4: 24 metadata items works, 25 metadata items fails with ECONNRESET error after hanging for a very long time

### Environment

  - **CDK CLI Version:** 1.109.0
  - **Module Version:** n/a
  - **Node.js Version:** 12.22.1
  - **OS:** macos Big Sur 11.3/11.4
  - **Language (Version):** Typescript

**Comment by jsauter** [comment] 2021-06-23 17:47
Here are the two test cases, the 25 one fails on Big Sur 11.4

[failat25.txt](https://github.com/aws/aws-cdk/files/6703924/failat25.txt)
[workat24.txt](https://github.com/aws/aws-cdk/files/6703926/workat24.txt)

**Comment by jsauter** [comment] 2021-06-23 17:48
Code used to reproduce this error.

`import * as cdk from '@aws-cdk/core';
import * as s3 from '@aws-cdk/aws-s3';
import * as asg from '@aws-cdk/aws-autoscaling';
import * as ec2 from '@aws-cdk/aws-ec2';
import initMetadata = require('@shaw-cdk/ec2service');
import path = require('path');
import { AssetStaging } from '@aws-cdk/core';


export class BigcdktestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const bucket = new s3.Bucket(this, 'MyBucket', {
      bucketName: 'jsauter-my-bucket',
      versioned: true
    });

    const vpc = ec2.Vpc.fromLookup(this, 'myVpc', {
      vpcId: 'vpc-894b89ef'
    });

    const autoscalinggroup = new asg.AutoScalingGroup(this, 'ASG', {
      vpc,
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T2, ec2.InstanceSize.MICRO),
      machineImage: new ec2.AmazonLinuxImage(),
    });


    const builder = new initMetadata.CfnInitMetadataBuilder(autoscalinggroup, 'configset1')

    for (let i = 0; i <25; i++) {
      const file = new initMetadata.CfnInitScriptAsset(this, `${i}testScript`, {
        friendlyName: `${i}-testScript`,
        shouldExecute: false,
        destinationPath: '\\temp\\scripts\\',
        destinationFileName: `${i}testScript`,
        path: path.join(__dirname, '../scripts/testScript.sh'),
        env: {
          ITERATION: `${i}`
        },
      });
  
      builder
        .withScript(file)  
    }

    
    
    builder.build();

  }
}
`

**Comment by jsauter** [comment] 2021-06-23 17:49
Code to reproduce the error:

[bigcdktest.zip](https://github.com/aws/aws-cdk/files/6703944/bigcdktest.zip)

**Comment by NetaNir** [comment] 2021-06-23 18:34
could be duplicate of: https://github.com/aws/aws-cdk/issues/15278

**Comment by jsauter** [comment] 2021-06-23 20:11
> could be duplicate of: #15278

15278 is this issue... is there another one I missed?

**Comment by peterwoodworth** [comment] 2021-06-24 17:57
This is the dup #15231 😄

**Closed by peterwoodworth** 2021-06-24 17:57 UTC
Labels: guidance, needs-triage
