### ISSUE TITLE
Bug on IAM policy generation for AwsCustomResource

### ISSUE THREAD

**Issue by loutente** [aws/aws-cdk#6807] opened 2020-03-19 06:43 UTC
When creating a custom resource with AWSSdkCall on service SES and action createConfigurationSetEventDestination the generated policy is wrong.

actual email:CreateConfigurationSetEventDestination
expected ses:CreateConfigurationSetEventDestination

### Reproduction Steps

```
AwsCustomResource(self,
                  id='SNSCfnConfigurationSetEventDestination',

                  on_create=AwsSdkCall(
                      service='SES',
                      action='createConfigurationSetEventDestination',
                      parameters=process_parameters(configuration_set.name, 'ses_sns_destination', topic.topic_arn),
                      physical_resource_id=PhysicalResourceId.of(id='ses_sns_destination')
                  ),
                  on_update=AwsSdkCall(
                      service='SES',
                      action='updateConfigurationSetEventDestination',
                      parameters=process_parameters(configuration_set.name, 'ses_sns_destination', topic.topic_arn),
                      physical_resource_id=PhysicalResourceId.of(id='ses_sns_destination')
                  ),
                  on_delete=AwsSdkCall(
                      service='SES',
                      action='deleteConfigurationSetEventDestination',
                      parameters={'ConfigurationSetName': configuration_set.name, 'EventDestinationName': 'ses_sns_destination'},
                      physical_resource_id=PhysicalResourceId.of(id='ses_sns_destination'),
                  ),
                  policy=AwsCustomResourcePolicy.from_sdk_calls(resources=AwsCustomResourcePolicy.ANY_RESOURCE)

```

### Error Log
No Log errors

### Environment

  - **CLI Version      : 1.18.19
  - **Framework Version: 1.27.0
  - **OS               : Mac OS
  - **Language         : Python/3.6.8

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment] 2020-03-31 08:41
@jogold can you take a look?

**Comment by jogold** [comment] 2020-03-31 09:33
@eladb 

Duplicate of #4513 

The problem lies in the json of the SDK: https://github.com/aws/aws-cdk/issues/4533#issuecomment-543048436

Do you want to handle this special case in https://github.com/aws/aws-cdk/blob/934d58e966a7ff99dfcff5a479dc75549b248c6f/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L381?

**Comment by eladb** [comment] 2020-03-31 09:37
> @eladb 
> 
> 
> 
> Duplicate of #4513 
> 
> 
> 
> The problem lies in the json of the SDK: https://github.com/aws/aws-cdk/issues/4533#issuecomment-543048436
> 
> 
> 
> Do you want to handle this special case in https://github.com/aws/aws-cdk/blob/934d58e966a7ff99dfcff5a479dc75549b248c6f/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L381?

Maybe we can patch the json during build? Kind of like we do with the cfn spec.

**Comment by eladb** [comment] 2020-03-31 09:39
Closing as duplicate

**Closed by eladb** 2020-03-31 09:39 UTC
Labels: bug, needs-triage, p1, package/custom-resources, package/iam
