### ISSUE TITLE
SubnetSelection "OnePerAZ" adds more than one per AZ

### ISSUE THREAD

**Issue by githubnoobieme** [aws/aws-cdk#6217] opened 2020-02-11 10:53 UTC
Hello,

when I try to use SubnetSelection and the option "OnePerAZ" it just creates a template of all subnets that are attached to the vpc and not only 1 per AZ

This is the code Iam using

`vpc1.add_interface_endpoint('SSMEndpoint', service=ec2.InterfaceVpcEndpointAwsService('ssm'), subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE, one_per_az=True))`

And this is my output

> > VPC2SSMEndpoint635B3888:
>     Type: AWS::EC2::VPCEndpoint
>     Properties:
>       ServiceName:
>         Fn::Join:
>           - ""
>           - - com.amazonaws.
>             - Ref: AWS::Region
>             - .ssm
>       VpcId: vpc-0756804582992c518
>       PrivateDnsEnabled: true
>       SecurityGroupIds:
>         - Fn::GetAtt:
>             - VPC2SSMEndpointSecurityGroupC16A4318
>             - GroupId
>       SubnetIds:
>         - subnet-02763f47226fccxxx
>         - subnet-0c2af8bb871b359x
>         - subnet-0099cf88bcb36222
>         - subnet-0000db6c52c8ddc22
>         - subnet-0fb87224a65d3842
>         - subnet-0ed2bf836eb579c22
>       VpcEndpointType: Interface

Not sure if Iam doing something wrong or this option is not working properly

**Comment by rix0rrr** [comment] 2020-02-14 09:23
Duplicate of https://github.com/aws/aws-cdk/issues/3126, fixed in upcoming release.

**Closed by rix0rrr** 2020-02-14 09:23 UTC
Labels: bug, package/ec2, status/needs-triage
