### ISSUE TITLE
[@aws-cdk/aws-lambda-nodejs] Bad performance on deployment of NodejsFunction construct, compared to plain Function construct

### ISSUE THREAD

**Issue by Dzhuneyt** [aws/aws-cdk#9639] opened 2020-08-12 15:28 UTC
Whenever I try to deploy a stack that's based mainly on Lambdas, as part of a relatively sized project (20-30 Lambdas), I am faced with a terrible development experience when using a fairly common combination of:
* AWS CDK
* The NodejsFunction construct by the @aws-cdk/aws-lambda-nodejs package
* TypeScript based Lambdas
* A Mac laptop

To demonstrate the magnitude of the issue, I created a simple CDK app with a simple CDK stack with 10 identical (almost empty of logic) Lambdas.
In the first scenario, I deploy the stack using .js files and the standard new lambda.Function() construct. 
In the second scenario I deploy the stack using .ts files and the new NodejsFunction() construct.

The time difference between both deployments (always starting from a non-existing stack in CloudFormation) is the following:
* lambda.Function construct deployment time for a stack of 10 Lambdas: 71 seconds
* NodejsFunction construct deployment time for a stack of 10 Lambdas: 330 seconds

To help mitigate it to some degree, I contributed a pull request a while ago (https://github.com/aws/aws-cdk/issues/8544) which adds a ":delegated" flag to Docker volumes that build the Lambda inside the NodejsFunction construct. However, apparently, this optimization is not enough for real life development and deployment.

I might be interested in contributing to the solution of this problem, but currently - I'm a bit out of ideas on how to approach it. Suggestions are welcome.

---

Minimum reproducable code pushed to this temporary repo: https://github.com/Dzhuneyt/aws-cdk-nodejs-function-performance-test

**Comment by jogold** [comment] 2020-08-12 15:35
Duplicate of #9120 

See #9632 for a WIP to solve this (and #9564) by bundling locally instead of in Docker

Could you try your app with the code in #9632? You will need to have Parcel v2 installed in your project: `yarn add parcel@2.0.0-beta.1` or `npm i parcel@2.0.0-beta.1`

**Comment by Dzhuneyt** [comment] 2020-08-12 16:22
I tried, but wasn't able to change the @aws-cdk/aws-lambda-nodejs to refer to your pull request due to various cross-package version dependencies, etc. Do you know of an easy way to attach a specific commit of a specific package of @aws-cdk to an existing CDK project?

**Comment by jogold** [comment] 2020-08-13 07:50
@Dzhuneyt starting from v1.58.0, replace the files in `node_modules/@aws-cdk/aws-lambda-nodejs/lib/bundling.js` and `node_modules/@aws-cdk/aws-lambda-nodejs/lib/util.js` with the files provided here https://gist.github.com/jogold/63e5f315aefb8a0bb88477caaa10d826

**Comment by eladb** [comment] 2020-08-17 09:38
Duplicate #9632

**Closed by eladb** 2020-08-17 09:38 UTC
Labels: @aws-cdk/aws-lambda-nodejs, duplicate, guidance, in-progress
