### ISSUE TITLE
(autoscaling): Support Launch Template

### ISSUE THREAD

**Issue by leimd** [aws/aws-cdk#13513] opened 2021-03-10 02:12 UTC
Now that we have added L2 construct for Launch Template in #12385, can we consider add support to define and pass Launch Template into AutoScaling Group?  It sounds pretty straight forward, if you guys are okay I can submit a PR to give it a try.

### Use Case

Define Autoscaling group with launch template.

### Proposed Solution
**Option 1**
Create new concrete L2 Construct `class AutoScalingGroupWithLaunchTemplate extends AutoScalingGroupBase`.
The new class takes `launchTemplate` as  a props and constructs an asg with launch template.
Later, if possible, rename `AutoScalingGroup` to `AutoScalingGroupWithLaunchLaunchConfiguration`, but that would be a breaking change.

**Option 2 (Less Preferred)**

Add an additional prop 'launchTemplate' to `packages/@aws-cdk/aws-autoscaling/lib/auto-scaling-group.ts`, this has to be an instance of `ILaunchTemplate`.

Add additional validation logic to make sure the `launchTemplate` and following props cannot co-exist:

- machineImage
- userData
- keyName
- instanceType
- instanceMonitoring
- instanceProfile
- role

Some of these props are really LaunchConfiguration props, so alternatively we can also create an L2 construct for LaunchConfiguration, and refactor this class to take either launchTemplate or launchConfiguration, but not both.

### Other

Let me know what do you guys think, I'm fairly familiar with Typescript and has made small contributions to CDK in the past. I would love to implement this since this is something my current organization could use right away.

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by peterwoodworth** [comment] 2021-06-28 23:54
Hey @leimd, sorry for the slow response here. Is this still something you'd like to see, or have you made any progress on a PR for this yet?

**Comment by peterwoodworth** [comment] 2021-06-29 01:14
Closing as duplicate of #6734, referencing @rix0rrr and @njlynch who have been looking at this recently

**Closed by peterwoodworth** 2021-06-29 01:14 UTC
Labels: @aws-cdk/aws-autoscaling, effort/large, feature-request, feature/coverage-gap, feature/pfr
