### ISSUE TITLE
(AppMesh): How to create two virtual service/node with bidirectional backend without circular dependencies

### ISSUE THREAD

**Issue by FranzBusch** [aws/aws-cdk#17322] opened 2021-11-04 07:30 UTC
### What is the problem?

I am currently setting up a CDK stack using ECS and AppMesh to create a micro service environment. In this micro service environment, every service should be able to talk to every other service. What I am trying to do is create a VirtualNode & Service per micro service and then call `addBackend` for each of these services and add all other services. However, this creates a cyclic dependencies for all services.

I haven't found a way yet to create this bidirectional backend setup without creating cyclic dependencies inside the CDK.

### Reproduction Steps

```ts
        // Inside 1 stack
        const node1 = new appmesh.VirtualNode(stack1, 'node1', {
            virtualNodeName: 'Node1',
            mesh: props.mesh,
            listeners: [appmesh.VirtualNodeListener.grpc({
                port: 8080,
                healthCheck: appmesh.HealthCheck.grpc({
                    healthyThreshold: 2,
                    interval: cdk.Duration.seconds(5),
                    timeout: cdk.Duration.seconds(2),
                    unhealthyThreshold: 3,
                }),
            })],
            accessLog: appmesh.AccessLog.fromFilePath('/dev/stdout'),
        });

        const service1 = new appmesh.VirtualService(stack2, 'Service1', {
            virtualServiceName:  'Service1',
            virtualServiceProvider: appmesh.VirtualServiceProvider.virtualNode(node1),
        });

       // Inside stack 2
        const node2 = new appmesh.VirtualNode(this, 'node2', {
            virtualNodeName: 'Node2',
            mesh: props.mesh,
            listeners: [appmesh.VirtualNodeListener.grpc({
                port: 8080,
                healthCheck: appmesh.HealthCheck.grpc({
                    healthyThreshold: 2,
                    interval: cdk.Duration.seconds(5),
                    timeout: cdk.Duration.seconds(2),
                    unhealthyThreshold: 3,
                }),
            })],
            accessLog: appmesh.AccessLog.fromFilePath('/dev/stdout'),
        });

        const service2 = new appmesh.VirtualService(this, 'Service2', {
            virtualServiceName: 'Service2',
            virtualServiceProvider: appmesh.VirtualServiceProvider.virtualNode(node2),
        });

      // Added afterwards via Aspect
      node1.addBackend(service2);
      node2.addBackend(service1)
```

### What did you expect to happen?

I expected there to be a way to create a bidirectional connection between backend services.

### What actually happened?

It always creates a circular dependency and I can't see any escape hatch

### CDK CLI Version

1.130.0

### Node.js Version

9.0.0

### OS

MacOS BigSur

### Language

Typescript

**Comment by Seiya6329** [comment] 2021-11-04 16:31
Hello @FranzBusch and thank you very much for submitting your issue. We will be looking into this and get back to you as soon as possible.

**Comment by Seiya6329** [comment] 2021-11-10 18:09
Hello @FranzBusch, sorry for the late response. We are still investigating this issue

**Comment by ashanpw** [comment] 2021-11-17 19:03
Thanks for the info. We are able to reproduce the issue and are now figuring out how to fix this or provide a workaround.

**Comment by PhilippBs** [comment] 2022-01-09 20:31
I was also running into the same issue and sadly I think the merged code is not fixing this. The fix is when the backend of a virtual node is also the virtual service itself where it is provider. However, the issue above mentions that if we have two virtual nodes which have a virtual service respectively and we wanna create a bidirectional backend setup between them.

This is still running into circular dependencies for me and something that is super important to have in a micro service setup. The test code should look like this:

```
        // GIVEN
         const stack = new cdk.Stack();

         // WHEN
         const mesh = new appmesh.Mesh(stack, 'mesh', {
           meshName: 'test-mesh',
         });

         const node1 = new appmesh.VirtualNode(stack, 'test-node1', {
           mesh,
           serviceDiscovery: appmesh.ServiceDiscovery.dns('test1'),
         });

         const myVirtualService1 = new appmesh.VirtualService(stack, 'service-1', {
           virtualServiceProvider: appmesh.VirtualServiceProvider.virtualNode(node1),
           virtualServiceName: 'service1.domain.local',
         });

         const node2= new appmesh.VirtualNode(stack, 'test-node2', {
           mesh,
           serviceDiscovery: appmesh.ServiceDiscovery.dns('test2'),
         });

         const myVirtualService2 = new appmesh.VirtualService(stack, 'service-2', {
           virtualServiceProvider: appmesh.VirtualServiceProvider.virtualNode(node2),
           virtualServiceName: 'service2.domain.local',
         });

         node1.addBackend(appmesh.Backend.virtualService(myVirtualService2));
         node2.addBackend(appmesh.Backend.virtualService(myVirtualService1));
```

cc @ashanpw @Seiya6329

**Comment by Seiya6329** [comment] 2022-01-10 05:29
@PhilippBs - Thanks for reporting the issue. We will further validate if the issue is still reproducible.

@FranzBusch - Please also let us know if you are experiencing the same issue.

**Comment by wplucinsky** [comment] 2022-01-10 22:36
@PhilippBs The latest version of `@aws-cdk/aws-appmesh` has not been published yet to NPM so the issue will persist until the CDK team publishes a new version. They do this every week around Wednesday. I will comment when it is updated. In the meantime you can use the [link-all utility](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#linking-against-this-repository) to pull in the latest changes.

You can tell the new vs old version by inspecting the CloudFormation template generated using `cdk synth`.

Old:
```
Backends:
  - VirtualService:
      VirtualServiceName:
        Fn::GetAtt:
          - service27C65CF7D
          - VirtualServiceName
```

New:
```
Backends:
  - VirtualService:
      VirtualServiceName: service1.domain.local
````

**Comment by wplucinsky** [comment] 2022-01-13 16:29
A new version of `@aws-cdk/aws-appmesh` has been published to NPM. Versions >= 1.139.0 contain the fix.

**Closed** 2022-01-13 17:42 UTC
Labels: bug, p1, effort/small, needs-reproduction, @aws-cdk/aws-appmesh
