### ISSUE TITLE
(Glue Crawler): unable to pass sqs_queue_arn to S3 target for S3 Event notification crawler

### ISSUE THREAD

**Issue by denys-tyshetskyy** [aws/aws-cdk#17763] opened 2021-11-29 22:54 UTC
### What is the problem?

For the CRAWL_EVENT_MODE of the recrawl_policy, there is no was at the moment to pass the sqs_queue_arn into s3Targets.
Cloud formation throws the error without it - _Event queue ARN is required when event crawler is selected._

### Reproduction Steps

Create glue crawler with recrawl property as following:
```python
recrawl_policy = glue.CfnCrawler.RecrawlPolicyProperty(recrawl_behavior='CRAWL_EVENT_MODE')
```

### What did you expect to happen?

There should be the "event_queue_arn" parameter in the CfnCrawler.S3TargetProperty that would accept the sqs arn. At the moment there is non

### What actually happened?

Cloud formation throws the error without sqs arn - _Event queue ARN is required when event crawler is selected._

### CDK CLI Version

1.134.0

### Node.js Version

v14.17.6

### OS

windows

### Language

Python

### Language Version

3.9.7

**Comment by kaizen3031593** [comment] 2021-12-14 02:52
Hi @denys-tyshetskyy! I'm not able to reproduce your bug with the information you've provided. Can you please provide a code sample so I can have a better idea of what you are doing?

Taking a shot in the dark at what I think you might be doing: the line you provided would not create a crawler. You need to use `glue.CfnCrawler(this, 'id', {...}` to create one. From there, there should be a property called `recrawlpolicy` (where you can provide the line above) and a property called `targets` where you can provide an `s3target`.

Hope that helps. If not, please provide a full code snippet so I can understand what the issue is.

**Comment by denys-tyshetskyy** [comment] 2021-12-14 02:58
Hi @kaizen3031593 , thank you for reply. I have only provided the snippet of the recrawl_policy config that I have used.
`        crawler_raw = glue.CfnCrawler(
            self,
            'Raw-Crawler',
            name='Raw-Crawler',
            role=glue_crawler_role.role_arn,
            database_name=database_name,
            targets={
                's3Targets': [{"path": f"s3://{bucket_name}/"}]
            },
            configuration="{\"Version\":1.0,\"Grouping\":{\"TableGroupingPolicy\":\"CombineCompatibleSchemas\",\"TableLevelConfiguration\":2},\"CrawlerOutput\": {\"Partitions\": {\"AddOrUpdateBehavior\": \"InheritFromTable\"}}}",
            schema_change_policy=schema_change_policy,
            recrawl_policy = glue.CfnCrawler.RecrawlPolicyProperty(recrawl_behavior='CRAWL_EVENT_MODE')
        )`
After doing more research I have found out that at the moment CloudFormation doesn't support the sqs_queue_arn parameter for the s3_target so basically there is no was to add the sqs arn to crawler in the automated way to point at the queue where s3 notifications are being stored. So it is not a cdk issue per se but not yet implemented feature in CF

**Comment by kaizen3031593** [comment] 2021-12-14 03:12
If you can do it via CLI or SDK call, then you can do it in CDK via [Custom Resources](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html). Other then that, it does look like this is missing cfn.

**Comment by cj-taylor** [comment] 2022-01-27 03:01
Looks like CFN support just landed. 

https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/947

**Comment by denys-tyshetskyy** [comment] 2022-01-27 03:30
Thanks @cj-taylor! I wonder if it is related or not to this but I noticed that our c3 notification based crawler suddenly stopped working few days ago. Might have been impacted by the release

**Comment by peterwoodworth** [comment] 2022-06-21 22:37
Implemented in CFN - Please ping a maintainer if this is not the case

**Closed by peterwoodworth** 2022-06-21 22:37 UTC
Labels: p2, effort/small, @aws-cdk/aws-glue, needs-cfn
