### ISSUE TITLE
certificatemanager.DnsValidatedCertificate has too low timeout

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cdk#5835] opened 2020-01-16 13:41 UTC
When creating a DnsValidatedCertificate currently in the us-east-1 region my stack creation fails due to not being able to validate the certificate in time. It's set to 15 minutes currently:

https://github.com/aws/aws-cdk/blob/e3305d8d09b3fd87a0609606c3638332c4eeef33/packages/%40aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts#L65

The AWS console reminds that it can take up to 30mins. Since DnsValidatedCertificate is creating a new certificate in a new stack all the time, it is (at least currently) not possible to create a stack with a DnsValidatedCertificate in us-east-1.

### Reproduction Steps

```typescript
        const hostedZone = HostedZone.fromLookup(this, 'HostedZone', {
            domainName: 'example.com',
        })

        const certificate = new DnsValidatedCertificate(this, 'Certificate', {
            'example.com',
            subjectAlternativeNames: [
                '*.example.com',
            ],
            hostedZone: hostedZone,
        })
```

### Error Log

```
50/55 | 2:29:40 PM | CREATE_FAILED        | AWS::CloudFormation::CustomResource         | client-tracking-listener-us/Certificate/CertificateRequestorResource/Default (CertificateCertificateRequestorResource2890C6B7) Failed to create resource. Resource is not in the state certificateValidated
        new CustomResource (/Users/kjakobi/workspace/infrastructure/tracking/node_modules/@aws-cdk/aws-cloudformation/lib/custom-resource.ts:163:21)
    \_ new DnsValidatedCertificate (/Users/kjakobi/workspace/infrastructure/tracking/node_modules/@aws-cdk/aws-certificatemanager/lib/dns-validated-certificate.ts:81:29)
    \_ new TrackingListenerStack (/Users/kjakobi/workspace/infrastructure/tracking/lib/tracking-listener-stack.ts:72:29)
    \_ Object.<anonymous> (/Users/kjakobi/workspace/infrastructure/tracking/bin/tracking.ts:40:1)
    \_ Module._compile (internal/modules/cjs/loader.js:1144:30)
    \_ Module.m._compile (/Users/kjakobi/workspace/infrastructure/tracking/node_modules/ts-node/src/index.ts:536:23)
    \_ Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    \_ Object.require.extensions.<computed> [as .ts] (/Users/kjakobi/workspace/infrastructure/tracking/node_modules/ts-node/src/index.ts:539:12)
    \_ Module.load (internal/modules/cjs/loader.js:993:32)
    \_ Function.Module._load (internal/modules/cjs/loader.js:892:14)
    \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    \_ main (/Users/kjakobi/workspace/infrastructure/tracking/node_modules/ts-node/src/bin.ts:212:14)
    \_ Object.<anonymous> (/Users/kjakobi/workspace/infrastructure/tracking/node_modules/ts-node/src/bin.ts:470:3)
    \_ Module._compile (internal/modules/cjs/loader.js:1144:30)
    \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    \_ Module.load (internal/modules/cjs/loader.js:993:32)
    \_ Function.Module._load (internal/modules/cjs/loader.js:892:14)
    \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    \_ /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
```

### Environment

  - **CLI Version      :** 1.21.0
  - **Framework Version:** 1.21.0
  - **OS               :** osx
  - **Language         :** typescript

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-01-17 09:02
A solution would be to switch to the new custom resource provider framework.

**Comment by Dzhuneyt** [comment] 2020-03-22 07:44
Duplicate of https://github.com/aws/aws-cdk/issues/5831.

**Comment by sdegutis** [comment] 2020-04-23 06:02
Getting the exact same error message using custom resource (for [SES domain validation](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#verify-a-domain-with-ses)) while creating a stack.

**Closed** 2020-07-10 09:57 UTC
Labels: @aws-cdk/aws-certificatemanager, bug, in-progress, p2
