### ISSUE TITLE
aws-cloudfront-origins : Setting S3 origin results in `The parameter origin name cannot contain a colon` Error

### ISSUE THREAD

**Issue by ETisREAL** [aws/aws-cdk#25110] opened 2023-04-13 16:51 UTC
### Describe the bug

Hi, I've been trying to set up an origin for my website bucket to connect to cloudfront. I've actually done this before with the *exact same set up* and never incurred in any issue. I'm assuming there's been some inadverted change in the code.

Here is the CDK code:

```
const tournamentsWebAppBucket = Bucket.fromBucketName(this, 'tournamentsWebAppBucket', config.tournamentsWebAppBucketName)

        const qlashMainApiGatewayOrigin = new origins.HttpOrigin(props.apiGatewayUrl, {
            protocolPolicy: OriginProtocolPolicy.MATCH_VIEWER
        })

        const cloudFrontDist = new Distribution(this, 'tournamentsWebAppDistribution', {
            defaultRootObject: 'index.html',
            domainNames: config.cloudfrontDomainNames,
            certificate: acm.Certificate.fromCertificateArn(this, "tlsCertificate", config.certificateArn),
            defaultBehavior: {
                origin: new origins.S3Origin(tournamentsWebAppBucket, {
                    originAccessIdentity: new OriginAccessIdentity(this, 'tournamentsWebAppBucketOAI', {
                        comment: 'OAI for web application cloudfront distribution'
                    })
                }),
                allowedMethods: AllowedMethods.ALLOW_GET_HEAD_OPTIONS,
                viewerProtocolPolicy: ViewerProtocolPolicy.ALLOW_ALL,
            }
        })

        cloudFrontDist.addBehavior('/*', qlashMainApiGatewayOrigin, {
            viewerProtocolPolicy: ViewerProtocolPolicy.ALLOW_ALL,
            allowedMethods: AllowedMethods.ALLOW_ALL
        })
```

### Expected Behavior

It should set up the origins as it used to

### Current Behavior

This is the error message I get:

AWS::CloudFront::Distribution
| tournamentsWebAppDistribution3FD75C72
Resource handler returned message: "Invalid request provided: AWS::CloudFront::
Distribution: The parameter origin name cannot contain a colon. (Service: Cloud
Front, Status Code: 400, Request ID: 3d6fa22e-fe1d-4e59-8a64-75d2250fe098)" (Re
questToken: 8324c49a-3736-d3fe-ec70-875aaab2e17e, HandlerErrorCode: InvalidRequ
est)

### Reproduction Steps

I've tried it calling an existing bucket and also creating a brand new one, but to no success

### CDK CLI Version

2.73.0

### Node.js Version

v18.15.0

### OS

Linux - Ubuntu

### Language

Typescript

**Comment by indrora** [comment] 2023-04-13 22:34
This looks like a duplicate of #1882. 

What's the value of `config.CloudfrontDomainNames`? It should be a list of FQDNs, not URIs.

**Comment by peterwoodworth** [comment] 2023-04-13 22:51
```
        const qlashMainApiGatewayOrigin = new origins.HttpOrigin(props.apiGatewayUrl, {
            protocolPolicy: OriginProtocolPolicy.MATCH_VIEWER
        })
```

HttpOrigin takes in a domain name, not a URL. Please try passing in the domain name here

**Comment by ETisREAL** [comment] 2023-04-14 12:37
> This looks like a duplicate of #1882.
> 
> What's the value of `config.CloudfrontDomainNames`? It should be a list of FQDNs, not URIs.

Yes the values were a list of FQDNs. The problem was in the HttpOrigin

**Comment by ETisREAL** [comment] 2023-04-14 12:39
> ```
>         const qlashMainApiGatewayOrigin = new origins.HttpOrigin(props.apiGatewayUrl, {
>             protocolPolicy: OriginProtocolPolicy.MATCH_VIEWER
>         })
> ```
> 
> HttpOrigin [takes in a domain name, not a URL](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront_origins.HttpOrigin.html). Please try passing in the domain name here

Right, this did it!! In my mind I was assuming this was the way to pass HTTP API Gateway as an origin (facepalm).
Thank you!

**Comment by peterwoodworth** [comment] 2023-04-18 16:02
Glad it worked!

**Closed by peterwoodworth** 2023-04-18 16:02 UTC
Labels: bug, @aws-cdk/aws-cloudfront-origins

**Comment by brycehanscomb** [comment] 2024-08-12 11:34
Please see also this solution posted here: https://stackoverflow.com/a/72010828
