### ISSUE TITLE
CDK CodePipeline: cdk deploy replaces existing, unrelated pipeline

### ISSUE THREAD

**Issue by Haga14** [aws/aws-cdk#13452] opened 2021-03-07 04:49 UTC
I created a new codepipeline stack and when I attempted to deploy it the command prints out all the resources used by the other pipeline in red, indicating deletion, and new resources with the names matching the new pipeline in green, indicating replacement of deleted pipeline.

In short, instead of creating new pipeline, it takes an existing pipeline in another repo on my machine and it replaces it with the new pipeline.

Additionally, when it deploys this, the new pipeline gets stuck on "CreateChangeSet" action of the "Dev" stage until it fails about an hour of being stuck on here and the console gives the following description: "waiting for current change set operation"

### Reproduction Steps

```ts
import * as cdk from '@aws-cdk/core';
import s3 = require('@aws-cdk/aws-s3');
import codecommit = require('@aws-cdk/aws-codecommit');
import codepipeline = require('@aws-cdk/aws-codepipeline');
import codepipeline_actions = require('@aws-cdk/aws-codepipeline-actions');
import codebuild = require('@aws-cdk/aws-codebuild');

export class PipelineStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here

    const artifactsBucket = new s3.Bucket(this, "******");

    // Pipeline creation starts
    const pipeline = new codepipeline.Pipeline(this, '***********', {
      artifactBucket: artifactsBucket
    });

    // Declare source code as an artifact
    const sourceOutput = new codepipeline.Artifact();

    // Add source stage to pipeline
    const sourceAction = new codepipeline_actions.GitHubSourceAction({
      actionName: 'GitHub_Source',
      owner: 'Haga14',
      repo: '********************',
      oauthToken: ****************************,
      output: sourceOutput,
      branch: '************', // default: 'master'
    });
    pipeline.addStage({
      stageName: 'Source',
      actions: [sourceAction],
    });


    // Declare build output as artifacts
    const buildOutput = new codepipeline.Artifact();

    // Declare a new CodeBuild project
    const buildProject = new codebuild.PipelineProject(this, 'Build', {
      environment: { buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_2 },
      environmentVariables: {
        'PACKAGE_BUCKET': {
          value: artifactsBucket.bucketName
        }
      }
    });

    // Add the build stage to our pipeline
    pipeline.addStage({
      stageName: 'Build',
      actions: [
        new codepipeline_actions.CodeBuildAction({
          actionName: 'Build',
          project: buildProject,
          input: sourceOutput,
          outputs: [buildOutput],
        }),
      ],
    });

    // Deploy stage
    pipeline.addStage({
      stageName: 'Dev',
      actions: [
        new codepipeline_actions.CloudFormationCreateReplaceChangeSetAction({
          actionName: 'CreateChangeSet',
          templatePath: buildOutput.atPath("packaged.yaml"),
          stackName: '******',
          adminPermissions: true,
          changeSetName: '*****************',
          runOrder: 1
        }),
        new codepipeline_actions.CloudFormationExecuteChangeSetAction({
          actionName: 'Deploy',
          stackName: '***************',
          changeSetName: '*************',
          runOrder: 2
        }),
      ],
    });
  }
}
```

### Environment

  - **CDK CLI Version  :1.92.0
  - **Framework Version:**
  - **Node.js Version:12.21.0
  - **OS               : Ubuntu
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment] 2021-03-08 19:58
Hello @Haga14 ,

the CDK does not care about your other repositories. What it _does_ care about are other resources in the same AWS account and region that you had before.

Perhaps you used the same Stack name in this new application that you used for a previous CDK application, and that's why it gets picked up?

Thanks,
Adam

**Comment by Haga14** [comment] 2021-03-09 16:31
Hi @skinny85 ,

Thanks for the response. That resolved my issue. 

But I do have another issue: Once I the pipeline completes the build step, it gets stuck in the deploy step for about an hour before it fails. During this time, it gets stuck on the "CreateChangeSet" action with the message "Waiting for current change set operation".

Any what this issue is? You can refer to the code I pasted in above.

Thanks again

**Comment by skinny85** [comment] 2021-03-09 16:48
When you say "deploy" step - do you mean the self-mutation step, or the actual deployment of your Stack(s)?

**Comment by Haga14** [comment] 2021-03-09 17:10
The actual deployment of stack via git push

**Comment by skinny85** [comment] 2021-03-09 17:23
Did you perform the new bootstrapping of the environment that the Stack is deployed to, like is described in the [ReadMe of the Pipelines module](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html)?

**Comment by skinny85** [comment] 2021-03-09 17:24
Specifically: https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#cdk-environment-bootstrapping

**Comment by Haga14** [comment] 2021-03-09 19:20
No, I didn't do that. 

In previous pipeline deployments, it worked fine without me ever having to do those steps. Is this something new?

**Comment by skinny85** [comment] 2021-03-09 21:11
No, sorry - I thought you were using the CDK Pipelines module, but apparently you're using pure CodePipeline.

Perhaps the ChageSet name between the `CloudFormationCreateReplaceChangeSetAction` and `CloudFormationExecuteChangeSetAction` you give is not the same?

**Comment by skinny85** [comment] 2021-03-09 21:12
Also, is this:

```
templatePath: buildOutput.atPath("packaged.yaml"),
```

correct? How do you generate this `packaged.yaml` file in the build step?

**Comment by Haga14** [comment] 2021-03-09 23:16
The names are the same.

As for the file, it's aut-generated in the build step.

For reference, here are the instructions are I followed: https://medium.com/perils-of-a-programmer/aws-sam-setting-up-a-cicd-pipeline-with-github-a7ee2e374759

**Comment by skinny85** [comment] 2021-03-10 00:38
> As for the file, it's aut-generated in the build step.

Can you show the buildspec you're using?

**Comment by Haga14** [comment] 2021-03-10 22:43
yes, here it is

`
# ~/environment/sam-app/buildspec.yml

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      # Installing project dependencies
      - cd src
      - npm install
  
  pre_build:
    commands:
      # Run tests, lint scripts or any other pre-build checks.
      #- npm run test

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd ..
      - sam build

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml

artifacts:
  discard-paths: yes
  files:
    # List of local artifacts that will be passed down the pipeline
    - packaged.yaml

`

**Comment by skinny85** [comment] 2021-03-10 23:12
Yep, that all looks correct...

Is the `stackName` the same between the 2 CloudFormation Actins?

I'm struggling to see any problems with this setup... any chance you can push your code to GitHub, so I can try to deploy the CodePipeline myself?

**Comment by Haga14** [comment] 2021-03-11 02:06
the names are all the same

I created a repo that contains the two files needed to create the pipeline and a sample AWS SAM app. This pipeline was made for an AWS SAM app, so it would be best if you used that as the deployment code.

I've included some instructions in the readme.

Here is the repo

https://github.com/Haga14/code-pipeline-exampe

**Comment by skinny85** [comment] 2021-03-11 22:07
Sorry @Haga14 , I followed your instructions, and this is what I see:

![Screen Shot 2021-03-11 at 2 06 00 PM](https://user-images.githubusercontent.com/460937/110861435-fa2bf700-8272-11eb-9696-34ecf65ea9af.png)

I've uploaded a complete example to GitHub if you want to re-create it: https://github.com/skinny85/sam-example-cdk-codepipeline

Perhaps try and analyze what's different between the code I've posted above, and your local code.

**Comment by Haga14** [comment] 2021-03-12 01:11
Thanks @skinny85 

I will do the analysis, hopefully I will find something

**Comment by skinny85** [comment] 2021-03-12 16:41
Sounds good! I'm resolving this one, please comment if there's anything else we can help you with on this matter.

**Closed by skinny85** 2021-03-12 16:41 UTC
Labels: @aws-cdk/aws-codepipeline, guidance

**Comment by Haga14** [comment] 2021-03-16 00:23
@skinny85  

Thanks for your help, I appreciate your time.

After investigating for a while, I was able to eventually get the two pipelines up and running.

The issue, which surfaces sometimes and doesn't other times: having hyphens  in the stackname and the code build project name results in the deployment getting stuck in the deploy stage.

**Comment by skinny85** [comment] 2021-03-16 00:40
I'm glad @Haga14 , but wow, is it really hyphens in the name that's causing these errors??

Hyphens are allowed for Stack names in CloudFormation... example from my account:

<img width="552" alt="Screen Shot 2021-03-15 at 5 39 09 PM" src="https://user-images.githubusercontent.com/460937/111239003-87de4e00-85b5-11eb-82cf-0daf23a35814.png">

**Comment by Haga14** [comment] 2021-03-16 21:38
It's not the pipeline stackname that's declared in "pipeline.ts" but the various names provided in the "pipeline-stack.ts"

**Comment by skinny85** [comment] 2021-03-16 21:40
Can you elaborate which ones?

**Comment by Haga14** [comment] 2021-03-16 21:47
The ***** fields in these lines


I'll investigate it in more depth once I get a chance, but the only thing I changed was remove the hyphens from all of these. 

```
    const pipeline = new codepipeline.Pipeline(this, '****************', {
      artifactBucket: artifactsBucket
    });

    const buildProject = new codebuild.PipelineProject(this, '*************', {
      environment: { buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_2 },
      environmentVariables: {
        'PACKAGE_BUCKET': {
          value: artifactsBucket.bucketName
        }
      }
    });

    pipeline.addStage({
      stageName: 'Deploy',
      actions: [
        new codepipeline_actions.CloudFormationCreateReplaceChangeSetAction({
          actionName: 'CreateChangeSet',
          templatePath: buildOutput.atPath("packaged.yaml"),
          stackName: '***************************',
          adminPermissions: true,
          changeSetName: 'dev-changeset',
          runOrder: 1
        }),
        new codepipeline_actions.CloudFormationExecuteChangeSetAction({
          actionName: 'Deploy',
          stackName: '*****************************',
          changeSetName: 'dev-changeset',
          runOrder: 2
        }),
      ],
    });

```

**Comment by skinny85** [comment] 2021-03-16 23:44
I feel like that's very unlikely. Like we established, dashes are allowed in Stack names, and CDK automatically strips the dashes from the logical IDs (which is what the `********` in `Pipeline` and `PipelineProject` are).

I would really like to hear if you manage to 100% confirm the problem is caused by the dashes in either of those 2 places!
