### ISSUE TITLE
secretsmanager: secretString should be specified directly.

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#6378] opened 2020-02-20 06:30 UTC
This should work:

```javascript
new secretsmanager.Secret(this, 'TemplatedSecret', {
    secretString: 'hoge',
});
```

The document explains why not that "this will almost always lead to the secret being surfaced in plain text and possibly committed to your source control".

But I think not "almost always". I think the one of benefits of CDK is we can do what we want programmatically in deployment process, unlike other YAML solutions. We can prepare secret string from environment variable, API response, user prompting and so on.

**Comment by skinny85** [comment] 2020-03-11 19:49
Duplicate of #5810

**Closed by skinny85** 2020-03-11 19:49 UTC
Labels: effort/small, feature-request, needs-triage, package/secretsmanager
