### ISSUE TITLE
(cdk/Typescript): Documentation page is blank for may resources (mostly Cfn)

### ISSUE THREAD

**Issue by fabianmartins** [aws/aws-cdk#14257] opened 2021-04-19 17:33 UTC
- https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-kinesisfirehose/cfndeliverystream.html#aws_kinesisfirehose_CfnDeliveryStream
- https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-cognito/cfnidentitypool.html#aws_cognito_CfnIdentityPool
- https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-ssm/cfnassociation.html#aws_ssm_CfnAssociation
- 

The documentation page is blank for many resources. Some examples provided.

---

This is a 📕 documentation issue

**Comment by rix0rrr** [comment] 2021-04-21 12:31
Duplicate of #4046.

**Closed by rix0rrr** 2021-04-21 12:31 UTC
Labels: documentation, feature-request, needs-triage
