### ISSUE TITLE
[lambda] Starting in 1.68.0 lambda Function.addPermission() incorrectly tries to add permission resource to remote functions

### ISSUE THREAD

**Issue by peterb154** [aws/aws-cdk#11278] opened 2020-11-04 00:15 UTC
### The Question
This change https://github.com/aws/aws-cdk/pull/10622 created a situation where cdk tries to addPermission to a lambda imported from a remote account. 

```console
User: arn:aws:sts::XXXXX:assumed-role/1111/22222-session is not authorized to perform: lambda:AddPermission on resource: 
arn:aws:lambda:us-east-1:YYYYY:function:ZZZZZ (Service: AWSLambda; Status Code: 403; Error Code: 
AccessDeniedException; Request ID: 3d57926c-986b-404f-88be-448dd359ca72; Proxy: null)
```
### Environment

cdk version 1.68.0+

### Example app.py
```py
import aws_cdk.core as core
import aws_cdk.aws_lambda as aws_lambda
import aws_cdk.aws_config as config

REMOTE_ACCOUNT = '123456789012'
REMOTE_FUNCTION = 'MyFunction'

class ExampleStack(core.Stack):
    def __init__(self, scope: core.Construct, id: str):
        super().__init__(scope, id)
        lambda_function = aws_lambda.Function.from_function_arn(
           self, "MyFunction",
           function_arn=f"arn:aws:lambda:{core.Aws.REGION}:{REMOTE_ACCOUNT}:function:{REMOTE_FUNCTION}"
        )

        # Create the custom rule construct
        config.CustomRule(
            self, "MyRule",
            config_rule_name="MyRule",
            lambda_function=lambda_function,
            configuration_changes=True
        )

app = core.App()
ExampleStack(app, "ExampleStack", )
app.synth()
```

### Example requirements.txt
```
aws-cdk.core==1.67.0
aws-cdk.aws-config==1.67.0
aws-cdk.aws-lambda==1.67.0
```

### Demonstration of the problem
v1.67.0 and prior returns the expected number (0) of AWS::Lambda::Permissions resources
```bash
$ sed -i txt s/68/67/ requirements.txt && pip install -qr requirements.txt && cdk synth --app "python app.py"  | grep -c Permission

0
```

But upgrade to 1.68.0 (or higher)
```bash
$ sed -i txt s/67/68/ requirements.txt && pip install -qr requirements.txt && cdk synth --app "python app.py"  | grep -c Permission

4
```
Returns 4 AWS::Lambda::Permissions resources. (should have none)

### Source
configRule runs addPermission() on the  ILambda here
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-config/lib/rule.ts#L356-L358

and Function.addPermission changed with this change https://github.com/aws/aws-cdk/pull/10622/files which was included in 1.68.0.

I believe this change is what caused the problem. 
![image](https://user-images.githubusercontent.com/989984/98054373-6186f580-1e00-11eb-845c-36b413f23377.png)

**Comment by peterb154** [comment] 2020-11-04 14:45
Thinking more about this. The assumption made by the recent change is that if either the `this.stack.account` or `this.function` are unresolved it is assumed that the function is "local" to the stack. I think this might be too assumptive.

**Comment by nija-at** [comment] 2020-11-09 12:24
Hey @peterb154 - this is indeed a problem and your assessment is correct. 

This is a duplicate of https://github.com/aws/aws-cdk/issues/11141

**Closed by nija-at** 2020-11-09 12:24 UTC
Labels: @aws-cdk/aws-lambda, bug, needs-triage
