### ISSUE TITLE
(aws-iam): (importedRoleStackSafeDefaultPolicyName Feature flag generates Policy names that are over 128 characters)

### ISSUE THREAD

**Issue by zeyad001** [aws/aws-cdk#24441] opened 2023-03-03 13:13 UTC
### Describe the bug

I am using the CrossZoneDelegation construct to delegate between 2 hosted Zones that are in different accounts. When I use the importedRoleStackSafeDefaultPolicyName feature flag the policy names that are generated that contain the path are targer than 128 characters which causes the stack to fail to deploy.

### Expected Behavior

The policy names need to be trimmed to fit within 128 characters when using this feature flag.

### Current Behavior

Adding the full construct path to the policy can lead to the polices becoming too to large.

### Reproduction Steps

- Create a new stack with a long name
- Create a Hosted Zone in that account
- Create another stack with a long name
- Create a DNS delegation roles
- Create a Hosted Zone in another account
- Use CrossAccount Delegation between the hosted zones
- Enable the importedRoleStackSafeDefaultPolicyName feature flag
- Attempt to deploy
- Stack fails because of policy name being too long and containing the entire construct path.

### Possible Solution

- Trim the policy name
- Find another uuid to generate default policy names instead of appending the construct path

### CDK CLI Version

2.66.0

### Node.js Version

16

### OS

Amazon Linux 2

### Language

Typescript

### Language Version

4.9.5

**Comment by pahud** [comment] 2023-03-03 17:01
Thank you for your report. I guess we probably need to trim the policy name with [cdk.Names.UniqueResourceName()](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Names.html#static-uniquewbrresourcewbrnameconstruct-options) with [maxLength](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.UniqueResourceNameOptions.html#maxlength) property specified. Making this a p2 bug and any PR submission would be appreciated!

**Comment by peterwoodworth** [comment] 2023-10-16 21:04
Closing as duplicate of #27409

**Closed by peterwoodworth** 2023-10-16 21:04 UTC
Labels: bug, p2, @aws-cdk/aws-iam, effort/medium
