### ISSUE TITLE
(pipelines): Malformed YAML during stage deployment

### ISSUE THREAD

**Issue by straygar** [aws/aws-cdk#12372] opened 2021-01-06 09:35 UTC
Not 100% sure if this is a CDK, CodePipeline or CloudFormation bug.

It appears that CloudFormation bug (https://github.com/aws/aws-cdk/issues/11910) that has blocked our deployments for a few weeks was fixed! 🎉 

However, trying to deploy the same stack to our first application stage now results in the following:
```
Template format error: YAML not well-formed. (line 5034, column 88) (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 6c5ea7db-4315-4f03-9b58-97af912c627a)
```

Which is odd - if I synthesize that stack locally, the YAML produced is only ~3000 lines long. Not really sure what I can do on my side to pinpoint the syntax error, if there is one.

### Reproduction Steps
1. Add a few resources (a composite alarm, a few normal ones, some metrics) to a stack, that already has a lot of monitoring resources
2. Push the change, triggering the CDK pipeline

### What did you expect to happen?
The stack to be deployed successfully in all application stages.

### What actually happened?
The prepare step for the stack in the first stage fails with the error:
```
Template format error: YAML not well-formed. (line 5034, column 88) (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 6c5ea7db-4315-4f03-9b58-97af912c627a)
```

### Environment

  - **CDK CLI Version  :** 1.82.0
  - **Framework Version:** 1.82.0
  - **Node.js Version:** 14.13.0
  - **OS               :** Ubuntu 20.04
  - **Language (Version):** TypeScript 

### Other
- Region: `eu-north-1`
- Pipeline execution ID: `f1bed18e-5916-44ef-acf0-edb3215d8c74` 
- CloudFormation request ID: `6c5ea7db-4315-4f03-9b58-97af912c627a`

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-01-06 09:48
If you go into the artifacts of the CodePipeline and you look at the YAML template there, what does it look like?

You will find them by going to the Synth CodeBuild project, finding the latest successful build and clicking build details:

![image](https://user-images.githubusercontent.com/524162/103754361-89672500-500c-11eb-96ce-e2f1bf277a5e.png)

NOTE: This may require you to extend permissions on the KMS Key that's used to encrypt the CodePipeline artifact bucket, because by default your IAM User/Role probably won't be allowed to read those CodePipeline artifacts otherwise. Add `kms:Decrypt` to the statement that has your account ID in it:

![image](https://user-images.githubusercontent.com/524162/103754504-badff080-500c-11eb-881c-1a16e7179017.png)

**Comment by hoegertn** [comment] 2021-01-06 10:34
I assume this error means your template is bigger than 51200 bytes which is the max size in codepipeline. 

You have to split your template

**Comment by straygar** [comment] 2021-01-06 12:59
Thx for the detailed instructions, @rix0rrr!

@hoegertn Possibly, do you have a doc link to this limit/quota? Do you mean 512'000 bytes or 51'200 bytes? If it's the latter, my template is 156KB, but I also have another 110KB one that has been deploying successfully.

The line CFN is complaining about is the `AssertDescription` one in this block:
```
"Rules": {
  "CheckBootstrapVersion": {
    "Assertions": [
      {
        "Assert": {
          "Fn::Not": [
            {
              "Fn::Contains": [
                [
                  "1",
                  "2",
                  "3"
                ],
                {
                  "Ref": "BootstrapVersion"
                }
              ]
            }
          ]
        },
        "AssertDescription": "CDK bootstrap stack version 4 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI."
      }
    ]
  }
}
```

I can try splitting it up though. Are there any best practices of how to do this in CDK? I'm considering of moving the heavier bits into a `NestedStack`.

**Comment by hoegertn** [comment] 2021-01-06 13:05
see https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CloudFormation.html under TemplatePath. CodePipeline uses the direct call instead of S3 apparently.

I hit this exact error some days ago. The error message looked familiar but is completely useless for this underlying error.

**Comment by rix0rrr** [comment] 2021-01-06 15:03
This is pretty dang nasty.

Putting all of your infra in a single nested stack will solve it though. That way the "parent" stack is < 50kB and we defer for the actual template to our usual asset system.

**Comment by rix0rrr** [comment] 2021-01-06 15:05
> I also have another 110KB one that has been deploying successfully

Has this been deploying successfully via CDK Pipelines?

**Comment by rix0rrr** [comment] 2021-01-06 15:07
> The line CFN is complaining about is the AssertDescription one in this block, which doesn't make a lot of sense...
> 
>``` 
> "Rules": {
> ```

Well... this is a somewhat non-standard CloudFormation feature. It's still weird that it would affect you here, since afaik we put this into all templates and it's normally fine. 

But it could still totally be the rule we're synthesizing here?

**Comment by straygar** [comment] 2021-01-06 15:16
OK, it turns out that the size was the issue - extracting the bulkiest set of resources into a nested stack (just to have a slightly nicer hierarchy/resource dependencies in my case) did the trick.

> Has this been deploying successfully via CDK Pipelines?
Yes. I have no idea how the 110KB stack deploys though, while a 156KB one doesn't...

**Comment by rix0rrr** [comment] 2021-01-06 15:21
Hm. Maybe CloudFormation raised their service call limits from 50kB (old limit) to 100-something kB (new limit) ? And the docs just haven't caught up yet?

**Comment by straygar** [comment] 2021-01-06 15:30
Yup, that was my thought. Feel free to resolve this , if you think it's technically not a CDK issue.

But a more descriptive error would be amazing in this case! :) And if possible, using a `TemplateURL` for CloudFormation calls to allow for bigger templates (although I can see how this could be more complicated, due to S3 cross account permissions, unless you use can use a pre-signed URL?).

**Comment by hoegertn** [comment] 2021-01-06 15:35
> Putting all of your infra in a single nested stack will solve it though. That way the "parent" stack is < 50kB and we defer for the actual template to our usual asset system.

That is actually a great idea and use case for nested stacks. Currently, I try to avoid them.

**Comment by hoegertn** [comment] 2021-01-06 15:35
> OK, it appears that the size was the issue - at least extracting the bulkiest set of resources into a nested stack (just to have a slightly nicer hierarchy/resource dependencies in my case) did the trick.
> 
> > Has this been deploying successfully via CDK Pipelines?
> 
> Yes. I have no idea how the 110KB stack deploys though, while a 156KB one doesn't...

Are you sure this stack is deployed using the CloudFOrmation actions and not using cdk deploy?

**Comment by hoegertn** [comment] 2021-01-06 15:36
> Hm. Maybe CloudFormation raised their service call limits from 50kB (old limit) to 100-something kB (new limit) ? And the docs just haven't caught up yet?
> 
> EDIT: Hmm not documented: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

I hit it some days ago with 70K so no raise here.

**Comment by hoegertn** [comment] 2021-01-06 15:37
> Yup, that was my thought. Feel free to resolve this , if you think it's technically not a CDK issue, even though the CFN limit isn't clear.
> 
> But a more descriptive error would be amazing in this case! :) And if possible, using a `TemplateURL` for CloudFormation calls to allow for bigger templates (although I can see how this could be more complicated, due to S3 cross account permissions).

I am in contact next week with the CodePipeline team to discuss this. This is ridiculous in my opinion.

**Comment by rix0rrr** [comment] 2021-01-07 14:21
I've a feeling this might yet be something else than simply template size. Keeping this open so Thorsten has a place to share his findings next week.

**Comment by antikvarBE** [comment] 2021-01-27 20:19
Experiencing the same validation error asking me to switch to version 4. Running `cdk bootstrap` doesn't make any changes.

**Comment by straygar** [comment] 2021-02-05 11:19
> 
> 
> > Putting all of your infra in a single nested stack will solve it though. That way the "parent" stack is < 50kB and we defer for the actual template to our usual asset system.
> 
> That is actually a great idea and use case for nested stacks. Currently, I try to avoid them.

Yeah... the biggest downside I saw in this case is loss of snapshots for nested stack contents(now the only snapshot change is the asset hash/location of the nested stack template).

Is there something in `@aws-cdk/assert` I can use to recursively cover nested stacks in my snapshots?

**Comment by rix0rrr** [comment] 2021-02-08 13:44
> Is there something in `@aws-cdk/assert` I can use to recursively cover nested stacks in my snapshots?

Not out of the box I don't think. You can build something though.

**Comment by hoegertn** [comment] 2021-02-19 15:13
So the error could not be traced internally, but the limitation of the template size was indeed just a docs bug. So bigger templates are allowed.

Whenever somebody hits this issue again please ping me and we will dive into the generated output to track it down and give the CFN team some reproducible snippets.

Can this ticket be set to "need investigation" or sth like that?

**Comment by bweigel** [comment] 2021-03-12 13:36
@hoegertn we have just hit this problem.
We are deploying via CdkPipelines. The prepare step fails:

![image](https://user-images.githubusercontent.com/6681272/110946029-b30b3800-833e-11eb-9cbf-2754e131fc26.png)

This is curious, since during prepare the pipeline just creates a CFN Changeset. 
I **can** download the artifact and **create the changeset manually** however:

![image](https://user-images.githubusercontent.com/6681272/110947173-1b0e4e00-8340-11eb-8df9-5c2380540461.png)


As you can see the template is 56,1 kB.

**Comment by hoegertn** [comment] 2021-03-12 15:38
Can you send the account id and executions ids via dm? I will forward it to the respective teams for inspection.

**Comment by bweigel** [comment] 2021-03-23 09:00
> Hm. Maybe CloudFormation raised their service call limits from 50kB (old limit) to 100-something kB (new limit) ? And the docs just haven't caught up yet?
> 
> EDIT: Hmm not documented: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

@rix0rrr Interestingly the documentation for the [Cloudformation Action](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CloudFormation.html) states:

![image](https://user-images.githubusercontent.com/6681272/112120378-73561300-8bbe-11eb-979b-14f532ef6316.png)

**Comment by hoegertn** [comment] 2021-03-23 09:05
Yeah, so they updated this. I am in contact with the team about this issue. It is not the size but sth weird.

**Comment by straygar** [comment] 2021-05-05 10:32
Got a different flavour of a similar problem (failure in the prepare step:
```
Template format error: JSON not well-formed. (line 4212, column 4) (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: b6dd7fb1-865a-4b65-aba6-a2d73393d70b; Proxy: null)
```

- Region: `eu-north-1`
- Pipeline execution ID: `66a7ef6b-6ae4-4f29-9331-4cb2ebb3a732`
- Template size: 137KB

**Comment by rix0rrr** [comment] 2021-05-06 12:37
It's probably not. You should be able to look at the actual template if you download the artifacts from the CodePipeline S3 bucket, rename the file to `.zip` and extract it. 

Does the file look broken?

**Comment by straygar** [comment] 2021-05-23 07:23
@rix0rrr No, it seemed perfectly fine. :/ 

I worked around it by pulling some resources into a nested stack.

**Comment by bweigel** [comment] 2021-06-03 16:33
@hoegertn did you hear back from the CFN team yet?

**Comment by hoegertn** [comment] 2021-06-03 18:33
Unfortunately not. I sent them another occurrence too. In this case I found out it was a resource type that was not supported in that region. 

So currently I suspect that this error means "something went wrong" but we have no idea what.

**Comment by markokan** [comment] 2021-06-28 07:18
@hoegertn Hi, we have same problem when using  AWS Pipelines. If I do directly from my computer using `cdk deploy` no problems occured and everything is fine. 

`Template format error: JSON not well-formed. (line 2454, column 1) (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: c08894e6-4398-4441-b83f-c3b60ed5c4f1; Proxy: null)`

Template info:
- Size is `85kb`
- Lines `2454`
- Region: `eu-west-1`

I changed resources to minimize a template size. After change Codepipeline success if I decrease template size under 51kb.
Solved this size issue (ValidationError) using nested stacks and keeping all of those templates size under 51kb. 

Hopefully they are making better error messages or changing those limits much bigger.

**Comment by ajolma** [comment] 2021-12-11 10:15
Working with the same repository as @markokan above and adding more resources. The best solution seems to put _everything_ into a single nested stack. I don't understand why this repository is a problem as we have others which have a bigger main assembly template and they go through the last pipeline step fine. BTW, I confirmed that it is the size issue as when I minimized (removed whitespace) the main template json in the S3 zip, and rerun the last step it went through fine.

**Comment by stekern** [comment] 2021-12-17 13:47
We are currently experiencing the same issue with one of our stacks. We made a change in our code that increased the size of the respective template from 77472 to 78841 bytes. We're able to deploy the stack locally (`$ npx cdk deploy ...`), but it fails on the `Prepare` step when trying to deploy it through CDK Pipelines.

I find it a bit surprising that the error message mentions YAML, while the `TemplatePath` is a JSON template. Is there some kind of preprocessing happening behind-the-scenes by CloudFormation? If so, that makes it even harder to debug wrt. the reported offending line and column number.

Full error message:
```
Template format error: YAML not well-formed. (line 2449, column 2) (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: <redacted>; Proxy: null)
```

**Comment by rtaylor-logitech** [comment] 2021-12-18 14:28
We're also experiencing the same issue as stekern. I hit this error if I use the `λ` character in cloudwatch dashboard labels. If I remove all uses of the λ character, the pipeline deploys my stacks correctly without error.

**Comment by nodesmichael** [comment] 2022-01-07 13:01
We are also experiencing this issue:

We have ~30 inter-dependent stacks that we've been deploying successfully though a single `cdk deploy` call for the past couple of years and CloudFormation wasn't complaining for any of them.

We are now trying to do the same via a Pipeline, and all stacks over 51KB seem to be failing with the error mentioned above.

Actually the first stack that failed happened to contain email templates as @stekern and @rtaylor-logitech above. And the error was mentioning YAML. We replaced the templates with dummy templates to ensure no weird characters where included. Then we got the JSON-flavor of the error as the size of the template was still over 51KB. Reducing it to just under 51KB resulted in the stack's Prepare step to pass.

What is the suggested workaround again?

We would need for all the resources that are in our current stacks to continue having the same names. i.e. We do not afford for resources to be deleted/recreated as some of them contain data e.g. a Cognito UserPool.

Is it maybe that the CDK pipeline is trying to run something equivalent to [aws cloudformation validate-template](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/validate-template.html) with `--template-body` instead of `--template-url`? Because according to the documentation the former has a limit of 51,200 bytes while the latter 460,800 bytes).

Surely if `cdk deploy` and CloudFormation can handle the size of a particular template CDK Pipelines should too, no?

**Comment by v1pz3n** [comment] 2022-02-24 17:31
We are also experiencing this issue [2]

**Comment by ghdoergeloh** [comment] 2022-03-24 09:57
I got the same error and I was also experiencing that my smallest template was working:

- 119.8 kB (not working)
- 116.2 kB (not working)
-  98.9 kB (working)

I first tried to understand the error by just doing what the pipeline tried. So I downloaded the Artifacts from the Build Action and took a look into the CloudFormation Action. I copied all of the configurations into a aws cli command and tried to execute it manually:

```bash
aws --region eu-west-1 cloudformation create-change-set \
--stack-name MyStack \
--change-set-name PipelineChange \
--template-body file://./cdk.out/assembly-PipelineStack-DevDeploy/PipelineStackDevDeployStackXXXXXXXX.template.json \
--role-arn arn:aws:iam::000000000000:role/cdk-hnb659fds-cfn-exec-role-000000000000-eu-west-1 \
--capabilities CAPABILITY_NAMED_IAM
```
This gave me the same error as the `validate-template` or the `update-stack` command:

`An error occurred (ValidationError) when calling the CreateChangeSet|UpdateStack|ValidateTemplate operation: 1 validation error detected: Value '{<template>}' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200`

so I thought, okay, that should not be the problem because the artifact is stored inside a s3 bucket. So I uploaded the file to the assets s3 Bucket and executed it again:

```bash
aws --region eu-west-1 cloudformation create-change-set \
--stack-name MyStack \
--change-set-name PipelineChange \
--template-url https://cdk-hnb659fds-assets-000000000000-eu-west-1.s3.eu-west-1.amazonaws.com/test/PipelineStackDevDeployStackXXXXXXXX.template.json \
--role-arn arn:aws:iam::000000000000:role/cdk-hnb659fds-cfn-exec-role-000000000000-eu-west-1 \
--capabilities CAPABILITY_NAMED_IAM
```

This time it worked.

So the size seems to be the only realistic explanation.

So as far as I can see there are currently these possibilities to work around:

- Using Nested Stacks (because they are in the asset s3 Bucket)
- Use a BuildProject and call `cdk deploy`
- Publish the template like all the other assets and execute the cloudformation command via cli

It would be great if AWS could improve the CloudFormation action in CodePipeline so it would upload the template first and then execute the change set creation or at least make this possible for cdk by accepting a s3 url as parameter.

**Comment by AKoetsier** [comment] 2022-06-02 08:37
Experienced the same issue. I did some tests and it seems a combination of both size and special characters in the template.

A template of around 285KB deploys ok without any special characters. After adding unicode characters to an SES template it started failing with JSON (or sometimes YAML) not well-formed. Downloading the template from the synth output in S3 and deploying it directly with Cloudformation works.

To test a bit more I removed a lot of the resources from the project and just deployed the templates with unicode characters using the pipeline which worked correctly.

So from what I can make of it the issue seems to be triggered by a combination of a large template like @ghdoergeloh also mentioned, in combination with unicode characters (in my case in an SES template).

**Comment by kashi238** [comment] 2022-06-02 11:27
I am experiencing the same issue in our environment.
If does not occur when the size of the template is up to 51KB, but it does occur when the size exeeed 57KB.
Even if the error occurs, if I get generated template directly from s3 and run it a new stack, it works fine.
It also seems to work if all Japanese characters are removed.

* python3.8
aws-cdk 1.158.0
* CDK-CLI
2.26.0
* Node.js
16.15.1

**Comment by miekassu** [comment] 2022-06-16 03:06
We are experiencing this issue after template size exceeded `57KB`

**Comment by nschwellnus** [comment] 2022-07-25 08:31
We were also experiencing the issue. In our case it was a combination of size and non-ascii characters. After increasing the size of the Stack the Prepare Step failed with "Template format error: JSON not well-formed". After removing non-ascii characters (ü in our case) the stack could be deployed via the pipeline normally.
24KB with non-ascii characters -> Working
98KB with non-ascii characters -> Not Working (JSON not well-formed Error)
98KB without non-ascii characters -> Working

**Comment by MrtMonet** [comment] 2022-08-02 11:55
I'm currently experiencing the same issiue with one of my stacks.  I'm getting the "Template format error: JSON not well-formed. (line 1883, column 3)" But when I validate from the cli the templates is fine.  The file size is quite big though 85KB.

**Comment by SchollSimon** [comment] 2022-08-15 06:47
> Experienced the same issue. I did some tests and it seems a combination of both size and special characters in the template.
> 
> A template of around 285KB deploys ok without any special characters. After adding unicode characters to an SES template it started failing with JSON (or sometimes YAML) not well-formed. Downloading the template from the synth output in S3 and deploying it directly with Cloudformation works.
> 
> To test a bit more I removed a lot of the resources from the project and just deployed the templates with unicode characters using the pipeline which worked correctly.
> 
> So from what I can make of it the issue seems to be triggered by a combination of a large template like @ghdoergeloh also mentioned, in combination with unicode characters (in my case in an SES template).

Picking up on that, i have a stack around ~ 100kb, only containing around 8 email templates. Deploying locally works fine, in pipeline it always prints
`Template format error: YAML not well-formed.` 

Therefore i checked if my email html templates contain non ascii characters and the answer is: yes.

So hope for a fix soon.

**Comment by HeskethGD** [comment] 2022-11-15 10:48
Is anyone actively looking at this issue? It has blocked our deployment pipelines and has been really difficult to debug. After finding this thread I tried to search the cf template for non ascii characters and found that \ufeff is being inserted before the word schema in the appsync definition in the template and it is not yet clear if we put it there or aws processing did. For what it's worth as some mentioned size above, the template is too big to be evaluated on file and has to be uploaded to s3 to run validation tests. Any idea how we may remove this character? If this wont be fixed we would need to add tests somehow to check for such characters when using cdk pipelines/codepipeline but this is made difficult because the code compiles and can be deployed by cdk deploy outside of cdk pipelines/codepipeline. This seems like a significant problem. Is there a work around for CI/CD in AWS with cdk that wouldn't experience this?
<img width="512" alt="Screenshot 2022-11-15 at 10 32 33" src="https://user-images.githubusercontent.com/29961970/201901059-69dc73d0-66c4-4df3-bd06-0ea9c8384494.png">

**Comment by rix0rrr** [comment] 2023-01-05 16:56
I created an internal ticket to the CodePipeline team for this, but that's unfortunately the best we can do. 

Internal reference: D68266996

**Comment by Pharrox** [comment] 2023-01-18 21:51
May as well add my notes here.

We've been dealing with this for a few months, but I finally got a chance to dig into this today. The error always happens when trying to deploy email templates containing non-standard characters. As noted by everyone else, it works whenever CodePipeline isn't involved.

Was able to gather enough information to make some assumptions about the nature of the issue by poking at CloudTrail:
* The error specifically happens during `cloudformation:CreateChangeSet` operations called by CodePipeline in the _Prepare_ step.
* When the template file is small enough, CodePipeline embeds the template in the `CreateChangeSet` call itself. Others have noted that for small enough files it works fine, this is probably why (none of our templates containing special characters are small enough to be deployed this way).
* When the template is too large to be included in the `CreateChangeSet` call, it is uploaded to S3 and `CreateChangeSet` is passed a pre-signed `templateURL`.
* The S3 bucket where the template is uploaded is *not* owned by the account doing the deployment. It is not the CodePipeline artifacts bucket, nor is it any bucket related to CDK. For `us-east-1`, the bucket it uses is called `cloudformation-codepipeline-largetemplate-bucket-useast1`. This appears to be an internal AWS bucket used by CodePipeline. I couldn't find any mention or documentation of this bucket online.
* The pre-signed URL has the format: `https://${INTERNAL_BUCKET}.s3.amazonaws.com/${DATE}/${HOUR}/${UUID}`
* My best guess is that something related to the upload to this bucket is the source of the problem. Possibly something in the bucket or built into the action pre-upload is set up to sanitize uploaded templates (given it seems to be a single bucket shared by all accounts deploying CloudFormation through CodePipeline). The sanitization is too aggressive and can mangle valid templates. This results in the JSON/YAML not well formed errors for templates that we know should be valid as they can be deployed by any other means.
* We can see the pre-signed URL's for templates used to successfully create ChangeSets by pulling them out of CloudTrail (provided they aren't expired). Unfortunately, if a `cloudformation:CreateChangeSet` operation fails with the errors reported here then the `requestParameters` for the call are not captured by CloudTrail and there is no way to retrieve the template to view what, if anything, may have been changed to produce the error.

**Comment by goranopacic** [comment] 2023-01-19 23:07
there is clearly a problem with non-ASCII characters. Here is what I did on Mac OS X:
1. Install pcre
$ brew install pcre
...
2. search for non ascii characters
$ pcregrep --color='auto' -n "[\x80-\xFF]" lib/*
lib/schema.graphql:1:���schema {

I've found this at the beginning of graphql.schema file which was imported as asset in cdk.
This same file was in use for some time and caused no issues till we added some new resources and size of the stack got bigger than 50kb. Now, after removing these characters stack size is bigger than 50kb and it is not a problem again.
So, obviously, there is some problem with non-ASCII characters causing cf prepare step to fail validation.
Equivalent linux command to check for non-ascii chars is:
grep --color='auto' -P -n "[\x80-\xFF]" lib/*

**Comment by HeskethGD** [comment] 2023-01-19 23:13
> there is clearly a problem with non-ASCII characters. Here is what I did on Mac OS X:
> 
> 1. Install pcre
>    $ brew install pcre
>    ...
> 2. search for non ascii characters
>    $ pcregrep --color='auto' -n "[\x80-\xFF]" lib/*
>    lib/schema.graphql:1:���schema {
> 
> I've found this at the beginning of schema.graphql file which was imported as asset in cdk. This same file was in use for some time and caused no issues till we added some new resources and size of the stack got bigger than 50kb. Now, after removing these characters stack size is bigger than 50kb and it is not a problem again. So, obviously, there is some problem with non-ASCII characters causing cf prepare step to fail validation. Equivalent linux command to check for non-ascii chars is: grep --color='auto' -P -n "[\x80-\xFF]" lib/*

This is the same as my issue above. How did you remove the character from the graphQL schema in the cloudformation template? In my case this was being put there when they were generated by CDK.

**Comment by goranopacic** [comment] 2023-01-19 23:17
I recreated the schema file (simple copy/paste) and after build and synth cfn template was cleared of non-ascii characters. just to mention that cdk deploy worked fine all the time. cdk pipelines couldn't pass that CFN prepare phase.

**Comment by hoegertn** [comment] 2023-02-07 23:03
I hit this error again as my template contains German umlauts (on purpose). So, in this case, there is no way around it, as these characters need to be in the template.

I pinged the CodePipeline team again. Is there anything else we can do to escalate this? UTF-8 is no new thing

**Comment by kimmoahokas** [comment] 2023-02-09 14:57
Not related to CDK, but I stumbled into this issue while debugging same error message. Our CF template is about 81KB. It had character `ä` in one comment. Removing that solved the issue.

**Closed** 2023-03-08 09:20 UTC
Labels: bug, p1, effort/large, @aws-cdk/pipelines
