### ISSUE TITLE
Adding Lambda permission for Lambda imported by ARN does not work

### ISSUE THREAD

**Issue by ErkoKnoll** [aws/aws-cdk#8494] opened 2020-06-11 09:52 UTC
When I'm trying to add a permission for Lambda via ARN (defined in another stack) then CDK ignores it (synth does not generate any statements).

Code to reproduce:
```
const lambda = Function.fromFunctionArn(this, 'LambdaFunction', 'ARN');

lambda.addPermission(`LambdaPermission`, {
    principal: new ServicePrincipal('apigateway.amazonaws.com'),
    sourceArn: `arn:aws:execute-api:${Aws.REGION}:${Aws.ACCOUNT_ID}:12345/*/*/*`
});
```

CDK version: 1.45.0

**Comment by ErkoKnoll** [comment] 2020-06-11 10:04
As a workaround this low level API works:
```
new CfnPermission(this, 'LambdaPermission', {
    action: 'lambda:InvokeFunction',
    functionName: 'ARN',
    principal: 'apigateway.amazonaws.com',
    sourceArn: `arn:aws:execute-api:${Aws.REGION}:${Aws.ACCOUNT_ID}:12345/*/*/*`
});
```

But would be nice if the high level API worked too.

**Comment by nija-at** [comment] 2020-06-12 08:18
Duplicate of https://github.com/aws/aws-cdk/issues/7588. Please 👍 the linked issue.

**Closed by nija-at** 2020-06-12 08:18 UTC
Labels: @aws-cdk/aws-lambda, bug, needs-triage
