### ISSUE TITLE
[aws-ecr-assets] Unable to provide secrets to DockerImageAsset build from SSM

### ISSUE THREAD

**Issue by markusl** [aws/aws-cdk#11623] opened 2020-11-22 18:15 UTC
It is common to include company internal artifacts or require some other integrations when running Docker asset builds.
In our case, we just want to simply install some internal NPM packages when building the components.

Using `buildArgs` of `DockerImageAsset` for reading parameters from the SSM Secure Strings does not seem to be supported?

This is also somewhat related to #10151 as the internal repositories can only be accessed via VPC connections.

### Workaround

The pipeline setup contains:

```typescript
    synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
      environment: { privileged: true },
      sourceArtifact,
      cloudAssemblyArtifact,

      buildCommand: 'npm run build',
      subdirectory: 'cdk',
      environmentVariables: {
        NPM_TOKEN: {
          type: codebuild.BuildEnvironmentVariableType.PARAMETER_STORE,
          value: 'company-internal-artifactory-token'
        },
      }
    }),
```

The asset image build uses the provided NPM_TOKEN:

```typescript
  const dockerAsset = new assets.DockerImageAsset(scope, 'app', {
    directory: '../app',
    buildArgs: {
      NPM_TOKEN: process.env.NPM_TOKEN ?? ''
    }
  });
```

### What did you expect to happen?

We'd like to have a documented way of providing some secrets to the DockerImageAsset.

### What actually happened?

The provided secret is printed to the build log without masking it, which is not optimal.
```
verbose: [0%] debug: docker build --build-arg NPM_TOKEN=xxxxxxxxxx== --tag cdkasset-257bfb6650e113016f7693018e8213ccb5b96188bec5ddeaa4ca282485a31d63 .
```

### Environment

  - **CDK CLI Version  :** 1.74.0 (build e86602f)
  - **Framework Version:** 1.74.0 (build e86602f)
  - **Node.js Version:** v14.15.0
  - **OS               :** macOs
  - **Language (Version):** TypeScript 4

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-01-07 14:55
Duplicate of https://github.com/aws/aws-cdk/issues/10999

**Closed by rix0rrr** 2021-01-07 14:55 UTC
Labels: @aws-cdk/aws-ecr-assets, bug, effort/medium, p1

**Comment by ColeMurray** [comment] 2021-03-13 05:52
@markusl,

You can use the ```EnvironmentVariableType.SECRETS_MANAGER``` type to overcome this.

Example:
```
const synthAction = SimpleSynthAction.standardNpmSynth({
            sourceArtifact,
            cloudAssemblyArtifact,
            installCommand: "npm install -g npm && npm ci",
            buildCommand: 'npm run build',
            rolePolicyStatements: [new iam.PolicyStatement({
                resources: ["*"],
                actions: ["secretsmanager:GetSecretValue"]
            })],
            subdirectory: './deployment',
            environment: {
                privileged: true,
                environmentVariables: {
                    NPM_TOKEN:  {
                        value: '<YOUR VALUE NAME HERE>',
                        type: BuildEnvironmentVariableType.SECRETS_MANAGER
                    }
                }

            },

        });
```
