### ISSUE TITLE
aws-cloudfront-origins : The parameter origin name cannot contain a colon.

### ISSUE THREAD

**Issue by ettore-pelosato** [aws/aws-cdk#25118] opened 2023-04-13 20:36 UTC
### Describe the bug

Hi. There's been a bug since the recent update. S3Origins raise the following error when deploying a cloudfront distribution:
Error: The stack named STG-TournamentsWebAppStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CloudFront::Distribution: The parameter origin name cannot contain a colon. (Service: CloudFront, Status Code: 400, Request ID: 355634cf-27de-4c71-bb9c-72426e4a509c)" (RequestToken: a3b7bcbc-d052-78a6-9370-451216b4a55e, HandlerErrorCode: InvalidRequest)

### Expected Behavior

I am literally following the instructions as in the CDK guide...

const cloudFrontDist = new Distribution(this, 'tournamentsWebAppDistribution', {
            defaultRootObject: 'index.html',
            domainNames: config.cloudfrontDomainNames,
            certificate: acm.Certificate.fromCertificateArn(this, "tlsCertificate", config.certificateArn),
            defaultBehavior: {
                origin: new origins.S3Origin(tournamentsWebAppBucket, {
                    originAccessIdentity: new OriginAccessIdentity(this, 'tournamentsWebAppBucketOAI'),
                allowedMethods: AllowedMethods.ALLOW_GET_HEAD_OPTIONS,
                viewerProtocolPolicy: ViewerProtocolPolicy.ALLOW_ALL,
            }
        })

### Current Behavior

Despite having deployed distribution with this exact setup before, after the recent update this is now failing with the provided error message

### Reproduction Steps

Simply define a distribution using an S3Origin and deploy the stack

### Possible Solution

I am guessing there is some issue in the cloudformation template rendering. The CDK is probably not stripping the S3 resource of https::.....

### CDK CLI Version

2.70.0

### Node.js Version

v18.15.0

### OS

iOS

### Language

Typescript

**Comment by khushail** [comment] 2023-04-13 20:46
Hi @ettore-pelosato , this issue seems to be duplicate of [this](https://github.com/aws/aws-cdk/issues/25110) one. So closing this one for now.

**Closed** 2023-04-13 20:47 UTC
Labels: bug, needs-triage, @aws-cdk/aws-cloudfront-origins
