### ISSUE TITLE
 Fn.conditionIf is not usable in s3 module.

### ISSUE THREAD

**Issue by Arsen-Uulu** [aws/aws-cdk#20551] opened 2022-05-31 03:54 UTC
### Describe the bug

I am using `software.amazon.awscdk.services.s3.CfnBucket`,  to create my S3 bucket and configure my replication Configuration, but when I  use software.amazon.awscdk.core.Fn `Fn.conditionIf` in 
`.replicationConfiguration()` object returned from  `Fn.conditionif` re-writers  the properties of `ReplicationConfigurationProperty`. The first letter of the property names is lower case instead of capital, then CFN return this error 
```
Bucket: UPDATE_FAILED - Encountered unsupported property "rules"
``` 
supposed to be "Rules"
```
Code block:
.replicationConfiguration(
    Fn.conditionIf(
         "ReplicationEnabled",
         replicationCofigurationPropetry
         Fn.ref("AWS:NoValue")
        )
    )
```

If I remove `Fn.conditionIf` everything works just fine.

### Expected Behavior

Expected `Fn.conditionIf` returned Object to be not modified

### Current Behavior

`Fn.conditionif` re-writers  the properties of `ReplicationConfigurationProperty`. The first letter of the property names is lower case instead of capital, then CFN return this error 

### Reproduction Steps

```
Code block:
.replicationConfiguration(
    Fn.conditionIf(
         "ReplicationEnabled",
         replicationCofigurationPropetry
         Fn.ref("AWS:NoValue")
        )
    )
```

### CDK CLI Version

software.amazon.awssdk:s3:2.17.41,software.amazon.awscdk:core:1.110.1'

### Node.js Version

v18.0.0

### OS

Mac OS

### Language

Java

**Comment by peterwoodworth** [comment] 2022-06-10 01:49
Thanks for the report, I or someone else on the team will try to reproduce this and get back to you at some point, but maybe not soon unfortunately. We appreciate the patience 🙂

**Comment by comcalvi** [comment] 2023-01-27 22:16
Duplicate of #8396.

**Closed by comcalvi** 2023-01-27 22:16 UTC
Labels: bug, p2, @aws-cdk/aws-s3, effort/small, needs-reproduction
