### ISSUE TITLE
[sqs] Circular dependency between resources when encrypting sqs queue with kms and assigning target to rule

### ISSUE THREAD

**Issue by prabint** [aws/aws-cdk#11158] opened 2020-10-27 21:04 UTC
I am setting up an event bridge rule that will forward events from Macie to sqs. Everything works fine until I add `encryptionMasterKey` to the queue. I either have to remove the `.encryptionMasterKey` or remove the `.target()` to avoid circular dependency error.

### Reproduction Steps

   ```
   val queue = Queue.Builder.create(scope, "MacieReportQueue")
                .queueName("MacieReportQueue")
                // TODO: FIXME: KMS Circular dependency error when combined with target
                //  https://github.com/aws/aws-cdk/issues/3067
                .encryption(QueueEncryption.KMS)
                .encryptionMasterKey(key)
                .build()

        val target = SqsQueue.Builder.create(queue).build()

        val rule = Rule.Builder.create(scope, "MacieToSqsEventBridgeRule")
                .ruleName("MacieToSqsEventBridgeRule")
                .description("Sends messages to SQS if Macie finds sensitive information")
                .targets(listOf(target))
                .eventPattern(EventPattern.builder()
                        .source(listOf("aws.macie"))
                        .build()
                )
                .build()
```

[CF Graph](https://ibb.co/JqQq8J6)
### What did you expect to happen?

No circular dependency error. Queue should be encrypted.

### What actually happened?

```
Circular dependency between resources: [MacieReportQueue7D1A954B, MacieReportQueuePolicy84D89C73, MacieToSqsEventBridgeRule498CF606, MacieReportQueueKeyAliasA0A0C899, MacieReportQueueKeyF608AAD8]
```

### Environment

  - **CLI Version      :*1.67.0 (build 2b4dd71)*
  - **Framework Version:*1.67.0*
  - **Node.js Version:**  v14.13.1
  - **OS               :**  Mac 10.14.6
  - **Language (Version):**  Java 8

### Other

--- 

This is :bug: Bug Report

**Comment by jamesholmes-linktree** [comment] 2020-11-13 06:43
I hit the same issue with an encrypted queue. The issue is this addition to the Key Policy when the target is created:

```
{
              "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*"
              ],
              "Condition": {
                "ArnEquals": {
                  "aws:SourceArn": {
                    "Fn::GetAtt": [
                      "Rule123456",
                      "Arn"
                    ]
                  }
                }
              },
              "Effect": "Allow",
              "Principal": {
                "Service": "events.amazonaws.com"
              },
              "Resource": "*"
            }
```

The Key now depends on the Rule ARN as a condition; the rule depends on the queue ARN as a target and; the queue depends on the key ARN to encrypt it. There's the circle.

**Comment by rix0rrr** [comment] 2020-12-24 16:33
This is pretty much unfixable by design the way Key Policies work in KMS, as long as this is not implemented: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/322

**Comment by rix0rrr** [comment] 2020-12-24 16:34
I would be okay dropping the `Condition` and just trusting AWS Events wholesale. Looping in @njlynch as the master of KMS.

**Comment by rix0rrr** [comment] 2020-12-24 16:35
Think I disagree with priority as well. This should work and there's no workaround.

**Comment by element7771** [comment] 2020-12-24 17:15
+1

Faced this problem on project. Still present in cdk 1.80.0.
It will be nice, if you are able to fix it in the nearest versions.

Thanks!

**Comment by njlynch** [comment] 2021-02-11 11:28
Missed this mention over the holidays... I agree that removing the condition is likely the simplest approach here.

**Comment by sudopla** [comment] 2021-02-12 06:31
Running into this same problem. Removing the condition would be great

**Comment by Rajesh734** [comment] 2021-02-16 13:19
I am having the exact same issue with my cdk project. I created a SQS queue with masterkey and created EventBridge Target. By default AWS-CDK adds SQSQueuePolicy which I can't alter and remove the condition defined in the Policy. Hence, can't remove the circular dependency. 

How can this be fixed in aws cdk project?


I am using: Nodejs, aws-cdk

**Comment by sudopla** [comment] 2021-02-16 19:53
I'm using the CFN class to circumvent this problem for now. 
```
const cfnRule = eventRule.node.defaultChild as events.CfnRule
cfnRule.targets = [
    {
        arn: queue.queueArn,
        id: 'EventQueue-Target',
    }
]
```

You will also need to define the following permissions

```
// Gives EventBridge rule permission to send message to queue target            
queue.addToResourcePolicy(new iam.PolicyStatement({
    actions: ['sqs:SendMessage'],
    resources: [queue.queueArn],
    principals: [new iam.ServicePrincipal('events.amazonaws.com')],
    conditions: {
        'ArnEquals': {'aws:SourceArn': eventRule.ruleArn}
    }
}))
```
```
// Give EventBridge access to KMS key
sqsKmsKey.addToResourcePolicy(new iam.PolicyStatement({
    principals: [new iam.ServicePrincipal('events.amazonaws.com')],
    actions: ['kms:Decrypt', 'kms:GenerateDataKey'],
    resources: ['*']
}))
```

**Comment by Rajesh734** [comment] 2021-02-18 09:44
> I'm using the CFN class to circumvent this problem for now.
> 
> ```
> const cfnRule = eventRule.node.defaultChild as events.CfnRule
> cfnRule.targets = [
>     {
>         arn: queue.queueArn,
>         id: 'EventQueue-Target',
>     }
> ]
> ```
> 
> You will also need to define the following permissions
> 
> ```
> // Gives EventBridge rule permission to send message to queue target            
> queue.addToResourcePolicy(new iam.PolicyStatement({
>     actions: ['sqs:SendMessage'],
>     resources: [queue.queueArn],
>     principals: [new iam.ServicePrincipal('events.amazonaws.com')],
>     conditions: {
>         'ArnEquals': {'aws:SourceArn': eventRule.ruleArn}
>     }
> }))
> ```
> 
> ```
> // Give EventBridge access to KMS key
> sqsKmsKey.addToResourcePolicy(new iam.PolicyStatement({
>     principals: [new iam.ServicePrincipal('events.amazonaws.com')],
>     actions: ['kms:Decrypt', 'kms:GenerateDataKey'],
>     resources: ['*']
> }))
> ```

Didn't think about CFN class. Thank you @sudopla !

**Comment by madeline-k** [comment] 2021-05-10 15:14
Taking a look at this one. I'm planning to remove the condition from being added here: https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-events-targets/lib/sqs.ts#L58-L60 in the case where the queue is encrypted.

**Closed** 2021-05-13 09:29 UTC
Labels: @aws-cdk/aws-sqs, bug, effort/small, good first issue, p1

**Comment by ryparker** [comment] 2021-11-30 20:54
Ran into this when troubleshooting a [similar issue on StackOverflow](https://stackoverflow.com/questions/62979608/how-to-solve-circular-dependency-between-aws-resources-using-aws-cdk)

[Repro code](https://github.com/techcoderunner/s3-sqs-kms-sample)

A circular dependency error is thrown when using a KMS key for encrypting an S3 bucket and an SQS queue, then setup a notification on the S3 bucket to message the SQS queue.

It looks like the root problem is that the following condition is added to the KMS key:

```json
{
	  "Action": [
	 	 "kms:Decrypt",
	 	 "kms:Encrypt",
		  "kms:ReEncrypt*",
		  "kms:GenerateDataKey*"
	  ],
	  "Condition": {
	  "ArnLike": {
	    "aws:SourceArn": {
	      "Fn::GetAtt": [
	        "ssls3bucketrawkms4B1E1122",
	        "Arn"
	      ]
	    }
	  }
  },
```

### Workaround

I was able to deploy the stack after using escape hatches to delete the condition:

```python
# Delete the circular reference
cfn_kms_key = kms_key.node.default_child
cfn_kms_key.add_property_deletion_override("KeyPolicy.Statement.1")
```

[workaround code available here](https://github.com/ryparker/aws-cdk-python-sample-kms)
