### ISSUE TITLE
(aws-cognito): Cannot re-use same lambda as lambdaTriggers for different Cognito

### ISSUE THREAD

**Issue by jerome-comtylink** [aws/aws-cdk#15933] opened 2021-08-07 09:35 UTC
Hi there,

I'm currently using CDK in typescript, but have some issues with lambdaTriggers.

My project is using multiple cognito user pools in order to manage multi-tenancy.

In order to manage the multi-tenancy, I need to override the JWT token key generated by Cognito, for that I would like to use the preTokenGeneration trigger.

I created my lambda in CDK and can easily attach it to one cognito user pool

However, it fails when I try to attach the same lambda to different cognito user pools.

### Reproduction Steps

You can find my code to reproduce the issue here

https://github.com/jerome-comtylink/cdk-cognito-lambda

Or the code used in order to reproduce the issue

```

    const fn = new Function(this, 'MyFunction', {
      runtime: Runtime.NODEJS_12_X,
      handler: 'index.handler',
      code: Code.fromInline('exports.handler = function(event, ctx, cb) { return cb(null, "hello world"); }')
    });

    new UserPool(this, `userpool-1`, {
      userPoolName: 'userpool',
      accountRecovery: AccountRecovery.EMAIL_ONLY,
      autoVerify: {
        email: true,
      },
      lambdaTriggers: {
        preTokenGeneration: fn,
      },
    });
    

    const userPool = new UserPool(this, `userpool-2`, {
      userPoolName: 'userpool',
      accountRecovery: AccountRecovery.EMAIL_ONLY,
      autoVerify: {
        email: true,
      },
      lambdaTriggers: {
        preTokenGeneration: fn,
      },
    });
```

### What did you expect to happen?

Be able to attach the same lambda to multiple user pools

### What actually happened?

`cdk synth` is failing with the following error message

```
There is already a Construct with name 'PreTokenGenerationCognito' in Function [MyFunction]
Subprocess exited with error 1
```

### Environment

- cdk version: 1.117.0 (build 0047c98)
- node: v12.22.1
- OS: Mac OS
- Typescript: Version 4.2.4
- 
--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2021-08-12 12:05
The bug is in the call to `addPermission()` here - 

https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-cognito/lib/user-pool.ts#L738.

Instead of just using the trigger type as the second (`name`) parameter, it needs to include a unique identifier of the user pool as well.

Marking this as a p2 since we have a workaround. The workaround is to use a different lambda function.
Let us know if you think this workaround is not applicable to you, or makes things significantly worse. 
We also accept contributions.

**Comment by jaresuth** [comment] 2021-09-30 01:38
@nija-at - Can you take a look and see what you think of the approach here?  UserPool attribute tokens don't seem to work here for a good match. The only way I was thinking of for uniqueness is to take the parent constructor.  Let me know what you think of this approach.  Thank you!

**Comment by sashee** [comment] 2022-10-14 08:47
It's still an issue

**Comment by jeve7** [comment] 2023-02-28 15:48
The issue is still there. Do we have plans to fix it?

**Comment by paulhcsun** [comment] 2023-12-09 00:46
This issue has been fixed in CDK v2 (https://github.com/aws/aws-cdk/pull/22444) so switching imports from `@aws-cdk` to `aws-cdk-lib` should resolve this issue.

**Closed by paulhcsun** 2023-12-09 00:46 UTC
Labels: bug, good first issue, p2, @aws-cdk/aws-cognito, effort/small
