### ISSUE TITLE
(core): NodejsFunction causes failure in `cdk ls`

### ISSUE THREAD

**Issue by smaxwell-amazon** [aws/aws-cdk#12467] opened 2021-01-12 10:01 UTC
Using NodejsFunction to create a Lambda Authorizer, `cdk synth` works as expected and a ZIP file is created and referenced in my build/cdk.out folder.

When I do `cdk ls`, the lambda references `build/cdk.out/<The entire path to my root folder>.zip` instead of the bundle.

## app.ts

```
import * as cdk from 'monocdk';
import * as lambda from 'monocdk/aws-lambda-nodejs';

const app = new cdk.App();

class ServiceInfraStack extends Stack {
  constructor(parent: cdk.Construct, name: string, props: DeploymentStackProps) {
    super(parent, name, props);
    new lambda.NodejsFunction(this, 'secret-key-auth');
  }
}

new ServiceInfraStack(app, 'beta', {
  stackName: `Test-Infra`,
});
```

## app.secret-key-auth.ts
```
exports.handler = async (event: any) => {
  return {
    principalId: 'user',
    policyDocument: {
      Version: '2012-10-17',
      Statement: [
        {
          Action: 'execute-api:Invoke',
          Effect: event.headers.serverapikey === 'ok' ? 'Allow' : 'Deny',
          Resource: event.routeArn,
        },
      ],
    },
  };
};
```

## cdk.json

```
{
  "app": "node dist/lib/app",
  },
  "output": "build/cdk.out"
}
```

### What did you expect to happen?

Expected `cdk ls` to show the name of the stack.

### What actually happened?

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'build/cdk.out/Volumes/workspaces/Showrunner/src/P10ShowrunnerDataServiceCDKCopy.zip'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (/Volumes/workspaces/Showrunner/src/P10ShowrunnerDataServiceCDKCopy/node_modules/@amzn/pipelines/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
    at WriteStream.onerror (/Volumes/workspaces/Showrunner/src/P10ShowrunnerDataServiceCDKCopy/node_modules/@amzn/pipelines/node_modules/readable-stream/lib/_stream_readable.js:704:47)
    at WriteStream.emit (events.js:314:20)
    at /Volumes/workspaces/Showrunner/src/P10ShowrunnerDataServiceCDKCopy/node_modules/@amzn/pipelines/node_modules/graceful-fs/graceful-fs.js:303:14
    at /Volumes/workspaces/Showrunner/src/P10ShowrunnerDataServiceCDKCopy/node_modules/@amzn/pipelines/node_modules/graceful-fs/graceful-fs.js:333:16
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'build/cdk.out/Volumes/workspaces/Showrunner/src/P10ShowrunnerDataServiceCDKCopy.zip'
}
```

### Environment

  - **CDK CLI Version  : 1.83.0**
  - **Framework Version: 1.81.0**
  - **Node.js Version: v12.20.0**
  - **OS               : MacOS 10.15.7**
  - **Language (Version): TypeScript 3.9.7 **

### Other

I have found that I can prevent this by hacking:
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/asset-staging.ts#L166

I replace `skip` with `false` and `cdk ls` now behaves properly.

--- 

This is :bug: Bug Report

**Comment by ryparker** [comment] 2021-06-03 21:23
Hey @smaxwell-amazon 👋🏻 

I noticed that you're passing in the the entry path as the `id` argument of the NodejsFunction constructor.

Check out these docs: [NodejsFunction class](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-lambda-nodejs/nodejsfunction.html#aws_lambda_nodejs_NodejsFunction) | [NodejsFunction props](https://docs.aws.amazon.com/cdk/api/latest/typescript/api/aws-lambda-nodejs/nodejsfunctionprops.html#aws_lambda_nodejs_NodejsFunctionProps)

To fix your example. change your `app.ts` initalization of `lambda.NodejsFunction` from:

```ts
new lambda.NodejsFunction(this, 'secret-key-auth');
```

To:

```ts
new lambda.NodejsFunction(this, 'desired-lambda-id', {
	entry: 'secret-key-auth'
});
```

Please let me know if this fixes your problem.

**Comment by peterwoodworth** [comment] 2021-06-11 20:39
Closing because the bot missed this, please ping me or ryan if you need more help with this!

**Closed by peterwoodworth** 2021-06-11 20:39 UTC
Labels: @aws-cdk/core, guidance

**Comment by wimlewis-amazon** [comment] 2021-07-29 21:20
@ryparker @peterwoodworth We're running into this problem as well. For us at least, adding `entry:` doesn't affect the problem (and that key is documented as optional-with-a-reasonable-default anyway, so even if that were a fix, this would still be a bug).

I think it's also significant that the path it's looking for is bonkers — there's no reason that the CDK should ever be assembling a path that looks like that in the first place.

**Comment by ryparker** [comment] 2021-07-29 22:49
Hey @wimlewis-amazon 

You may want to open a new issue with this as i'm unable to reproduce the original bug from this issue using the latest CDK. Are you using the latest version?

**Comment by wimlewis-amazon** [comment] 2021-07-31 00:40
@ryparker I can't reproduce the bug in the top comment either, whether in the current version or the version it was reported against. Can you reproduce it in an earlier version of the CDK? I'm beginning to think that the problem is actually in one of the non-CDK subclasses of `Stage` that both @smaxwell-amazon and I are using (check the pre-edit version of the issue submission), not with the code in the CDK.
