### ISSUE TITLE
(decdk): Performance issues in decdk renderFullSchema

### ISSUE THREAD

**Issue by kennu** [aws/aws-cdk#12349] opened 2021-01-05 09:45 UTC
On my computers **decdk** takes over two minutes to build a simple hello-world stack, which seems a bit excessive.

Most of the effort appears to be spent in [`renderFullSchema()`](https://github.com/aws/aws-cdk/blob/master/packages/decdk/lib/cdk-schema.ts#L17), which iterates through a lot of CPU-intensive loops while calling [`schemaForTypeReference()`](https://github.com/aws/aws-cdk/blob/master/packages/decdk/lib/jsii2schema.ts#L89). Perhaps all this looping could be improved by building some lookup hash tables or other similar solutions?

It also seems that the rendered schema could be easily loaded from cdk.schema.json instead of generating it from scratch every time in the [`DeclarativeStack constructor`](https://github.com/aws/aws-cdk/blob/master/packages/decdk/lib/declarative-stack.ts#L20).

**Comment by ryparker** [comment] 2021-06-15 18:52
Hey @kennu :wave:

Thanks for opening this issue. This definitely looks like a good opportunity for optimization. 

I just wanted to follow up here and let you know that this is still on our radar. The issue is labelled as p2 which means that we are unable to work on this immediately. However we use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR (please make sure to follow our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md?rgh-link-date=2021-03-25T10%3A42%3A16Z).)

**Comment by kennu** [comment] 2021-06-15 20:20
Thanks for the note @ryparker. I'll take this opportunity to ask about decdk contributions in general:

1) How strict is the tests-required policy on decdk?
2) I have been unable to successfully run decdk tests on my own computer; will GitHub run them if I make a pull request?

I've been working on making fromConstructArn() work and thinking about making a PR of that.

**Comment by ryparker** [comment] 2021-06-16 20:58
> 1. How strict is the tests-required policy on decdk?

Checkout the ["Work your magic" section](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#step-3-work-your-magic) of the contribution guide for details but here's an outline:
- A unit test is required for every change. 
- If you are working on a new feature that is using previously unused CloudFormation resource types, or involves configuring resource types across services, you need to write integration tests that use these resource types or features.
- include a section in the integration test file that specifies how the successfully deployed stack can be verified for correctness. 

> 2. I have been unable to successfully run decdk tests on my own computer; will GitHub run them if I make a pull request?

Yes, after opening a PR you should notice one of our bots will post a comment with a link to the GitPod editor. However we recommend getting implementing the fix/feat locally before pushing a PR since GitPod instances will spin down after limited amount of time (50hrs/month). [More details on GitPod here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md#gitpod-alternative)

**Comment by Chriscbr** [comment] 2022-02-14 23:59
Transferred to https://github.com/cdklabs/decdk/issues/7

**Closed by Chriscbr** 2022-02-14 23:59 UTC
Labels: p2, feature-request, effort/medium, package/decdk
