### ISSUE TITLE
EKS: Helm Pull on `eks.HelmChart` does not work for non-ECR OCI Charts.

### ISSUE THREAD

**Issue by elamaran11** [aws/aws-cdk#24710] opened 2023-03-21 00:59 UTC
### Describe the bug

We are trying to install an OCI helm chart from [ghcr.io](http://ghcr.io/) (public chart) for Grafana operator using CDK and it consistently fails, while manual installation succeeds with helm (no authn necessary).

CDK Install using:

```typescript
eks.HelmChart with 
    name: 'grafana-operator',
    chart: 'grafana-operator',
    namespace: 'grafana-operator',
    repository: 'oci://ghcr.io/grafana-operator/helm-charts/grafana-operator',
    version: 'v5.0.0-rc0',
    release: 'grafana-operator'
```

Helm install manual (succeeds):
```bash
helm upgrade grafana-operator ./grafana-operator --install --repo oci://ghcr.io/grafana-operator/helm-charts/grafana-operator --version v5.0.0-rc0
```

Error:
```
Error: b'Release "grafana-operator" does not exist. Installing it now.\nError: path "/tmp/tmpb1ykx
ljl/grafana-operator" not found\n'
```

Looks like the bug is in `return os.path.join(tmpdir, repository.rpartition('/')[-1])` the parameter for the chart where CDK passes tmp dir and chart name (we used ./grafana-operator).

### Expected Behavior

Successful installation of non-ECR OCI Helm charts using below 

```typescript
eks.HelmChart with 
    name: 'grafana-operator',
    chart: 'grafana-operator',
    namespace: 'grafana-operator',
    repository: 'oci://ghcr.io/grafana-operator/helm-charts/grafana-operator',
    version: 'v5.0.0-rc0',
    release: 'grafana-operator'
```

### Current Behavior

Error:
```
Error: b'Release "grafana-operator" does not exist. Installing it now.\nError: path "/tmp/tmpb1ykx
ljl/grafana-operator" not found\n'
```

Looks like the bug is in the parameter for the chart where CDK passes tmp dir and chart name (we used ./grafana-operator) .
The issue is in `return os.path.join(tmpdir, repository.rpartition('/')[-1])`

### Reproduction Steps

Please run the cdk script at https://github.com/aws-samples/containers-blog-maelstrom/blob/main/grafana-operator-AMG/bin/grafana-operator-amg.ts uncommenting line 26 `// new GrafanaOperatorHelmAddon(),` and you will see the Grafana Operator installation failing.

### Possible Solution

The issue is in `return os.path.join(tmpdir, repository.rpartition('/')[-1])` It should return right first parameter instead of `tmpdir`.

### CDK CLI Version

2.67

### Node.js Version

v19.6.0

### OS

Mac/Ubuntu

### Language

Typescript

**Comment by pahud** [comment] 2023-03-21 01:48
According to this: 

https://github.com/aws/aws-cdk/blob/3b7431b6ac27f8557c22a8959ae1ce431f6d2167/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L119-L120

If oci:// prefix comes with non-ecr-public or non-ecr-private repos, it simply run helm pull followed by [helm upgrade](https://github.com/aws/aws-cdk/blob/3b7431b6ac27f8557c22a8959ae1ce431f6d2167/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L88), rather than `helm upgrade` against the oci:// URL directly:

>helm upgrade grafana-operator ./grafana-operator --install --repo oci://ghcr.io/grafana-operator/helm-charts/grafana-operator --version v5.0.0-rc0

I'm making it p2 bug. Any PR contributions is highly welcome and appreciated.

**Comment by shapirov103** [comment] 2023-03-21 03:44
@pahud `helm pull` works fine in the lambda function code, the following `helm upgrade` however, fails with directory not found.

I was able to reproduce this bug and one potential root cause is that the code allocates a temporary directory variable within an `if` scope [here](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-eks/lib/kubectl-handler/helm/__init__.py#L84), but once it gets out of scope (before helm upgrade) it is cleaned up automatically. 

```python
 if repository is not None and repository.startswith('oci://'):
            tmpdir = tempfile.TemporaryDirectory()
            chart_dir = get_chart_from_oci(tmpdir.name, repository, version)
            chart = chart_dir  
            # End of scope for tmpdir forcing runtime to clean it up

# tmpdir  is gone already, but the passed chart variable still contains the path to the clean up dir
helm('upgrade', release, chart, repository, values_file, namespace, version, wait, timeout, create_namespace)
```

**Comment by gbvanrenswoude** [comment] 2023-03-21 08:45
Both these situations run into similar issue: ```        this.helmChart = new eks.HelmChart(this, 'polarisHelmChart', {
            timeout: Duration.minutes(5),
            cluster: props.cluster,
            chart: 'polaris', // fairwinds-stable/polaris
            repository: 'oci://<account-nr>.dkr.ecr.eu-west-1.amazonaws.com/charts/polaris', // polaris
            namespace: polarisNamespace,
            version: '5.4.2',
        });

        this.helmChart = new eks.HelmChart(this, 'polarisHelmChart', {
            timeout: Duration.minutes(5),
            cluster: props.cluster,
            namespace: polarisNamespace,
            chart: 'fairwinds-stable/polaris', // note the slash here
            createNamespace: false,
            wait: false,
            release: 'polaris',
            repository: 'https://charts.fairwinds.com/stable', 
            values,
        });```.

**Comment by pahud** [comment] 2023-03-21 15:13
@shapirov103 Thank you for your valuable insight. This helps a lot!

In this case we probably should consider to use [mkstemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) and [mkdtemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp) instead followed by manual cleanup as the doc described [here](https://docs.python.org/3/library/tempfile.html).

**Comment by shapirov103** [comment] 2023-03-21 17:45
@pahud 

From the performance perspective, if we already pulled the chart, it makes sense to reuse it without an extra lookup, so I would say approach 1 is beneficial. mkdtemp() will work, or just scoping the tmpdir variable with `with`  - I can see that it may need slight refactoring of that code though.

**Comment by elamaran11** [comment] 2023-03-28 01:28
@pahud Do we know when this will be implemented.

**Comment by pahud** [comment] 2023-04-18 17:46
@elamaran11 Unfortunately this bug is currently labeled as p2 which means the core team maintainers will not be able to address it. But we will be glad to review any PRs from the community to get it fixed.

**Closed** 2023-04-24 13:41 UTC
Labels: bug, p2, @aws-cdk/aws-eks, effort/medium
