### ISSUE TITLE
IAM permission boundaries

### ISSUE THREAD

**Issue by abhishekjawali** [aws/aws-cdk#5222] opened 2019-11-27 16:42 UTC
This was originally about EKS, but we think there's a general use case here to be able to specify an IAM permission boundary at the stack level and perhaps generally have Stack-level control over IAM roles/policies created within a stack.

See thread below.

-------

When creating the cluster using "@aws-cdk/aws-eks" module, the CloudFormation template is generated with implicit lambda function. This lambda function is executing a python script for cluster creation.
A lambda service role is also created. However, when permission boundary is enforced in AWS account, creation of lambda service role fails, as permission boundary will not be attached implicitly.

Provide an option to specify these roles explicitly.

### Use Case
In some AWS tenancies, permission boundary can be enforced when creation any IAM roles. With this, implicit IAM roles cannot be created as they will not be attached with permission boundary. 

In such AWS account, creation of EKS cluster using CDK fails as the lambda service role which is generated by CDK is not associated with permission boundary. 

### Proposed Solution

Specify permission boundary to be attached to implicit IAM roles that CDK creates
```
new eks.Cluster(this, "hello-eks", {
      clusterName: "test-eks-cdk",
      permissionBoundary: <ARN-OF-PERMISSION-BOUNDARY>
}
```
The permission boundary defined, will get assigned to the lambda IAM role.

**Comment by eladb** [comment] 2019-11-27 18:20
I am wondering if we should allow specifying a permission boundary at the stack level which will automatically apply to all IAM roles defined within this stack. Would that make sense for your use case? @rix0rrr, @RomainMuller what do you guys think?

**Comment by abhishekjawali** [comment] 2019-11-28 03:03
@eladb, Yes, this makes more sense. I feel having the option to attach permission boundary at stack level, will apply to any IAM roles that are created explicitly inside the stack as well as the roles that are created implicitly. And this covers uses cases beyond EKS as well. 

On a similar note, I also feel that we should be provided with options to attach some IAM policies to implicitly created roles as well. At account level, there could be some IAM policies that has to be attached to IAM role always. These policies provide finer level of control on IAM roles. So if we have an option to specify what IAM policies have to be attached to stack level, then these will be attached to all IAM roles that gets created, either explicitly or implicitly. 

Let me know your thoughts on this.

**Comment by eladb** [comment] 2019-11-28 07:34
OK, I am repurposing this issue to that effect.

**Comment by rix0rrr** [comment] 2019-11-28 09:57
Feels like it could/should be an aspect?

**Comment by eladb** [comment] 2019-11-28 14:31
Aspects are an implementation mechanism, not an API. It's definitely possible that it can be implemented using aspects, but we still need to support this as a first class API of the CDK (like Tags).

**Comment by rix0rrr** [comment] 2019-11-28 20:01
Sure. So then I guess my response is: I agree with the premise that it would be useful to be able to define permission boundaries for a (potentially large) set of roles.

 I reserve future judgement once the API has been crystallized out more :)

**Comment by pepastach** [comment] 2019-11-29 22:43
I have implemented permission boundary for all roles created by CDK as an aspect. Not pretty, bot works fine. I'd appreciate the first class support though.

https://gitlab.com/josef.stach/aws-cdk-permission-boundary-aspect

**Comment by eladb** [comment] 2019-11-30 14:35
Thanks for sharing!

**Comment by rix0rrr** [comment] 2020-01-23 12:58
Duplicate of https://github.com/aws/aws-cdk/issues/3242 ?

**Closed** 2020-08-12 12:43 UTC
Labels: @aws-cdk/aws-iam, effort/medium, feature-request
