### ISSUE TITLE
(aws-ecs):  BaseService should allow cloudMapService to be assigned rather than automatically created inside

### ISSUE THREAD

**Issue by linyaoli** [aws/aws-cdk#12283] opened 2020-12-30 10:33 UTC
Propose to alternatively allow assigning a cloudMapService instance.

https://github.com/aws/aws-cdk/blob/e8801a0ddb04e75de87ba34f3a58b1adebae5301/packages/%40aws-cdk/aws-ecs/lib/base/base-service.ts#L532

### Use Case

In my case, when I have to assign the same namespace to mesh and service stack, they share a common cloudmap service, but a Fargate service also creates a new cloudmap service with cloudMapOptions.

### Proposed Solution

A shallow method to take in cloudMapService is good enough.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by piradeepk** [comment] 2021-02-03 15:34
Resolving as duplicate of https://github.com/aws/aws-cdk/issues/10057

**Comment by SoManyHs** [comment] 2021-03-09 02:09
Closing this as a duplicate of https://github.com/aws/aws-cdk/issues/10057

**Closed by SoManyHs** 2021-03-09 02:09 UTC
Labels: @aws-cdk/aws-ecs, effort/medium, feature-request, p2
