### ISSUE TITLE
cognito user pools - support SES integration

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cdk#6768] opened 2020-03-17 12:56 UTC
AWS Docs to the feature: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html#user-pool-email-developer

CloudFormation properties: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-emailconfiguration.html

---

This is a :rocket: Feature Request

**Comment by rehanvdm** [comment] 2020-03-24 08:32
+1

**Comment by tom139** [comment] 2020-04-07 16:31
Hi, I did some research I would like to share:
There are 3 possible sender configuration:
- __default__ use default with an address similar to _noreply@verificationemail.com_ and the ability to set the `replyTo` property;
- __Cognito__ sender: this allow to specify a custom sender address (via a verified identity in SES) and set the `from` field (with both `email` and `name`);
- __SES__ sender: this has the same properties as the above cognito sender plus the ability to set a _ConfigurationSet_ to better track sent emails.

The default should be initiable with empty props:
```typescript
let sender = new DefaultSender({
  replyTo?: "replyToAddress",
});
```

If the user wish to use cognito must specify all required fields
```typescript
let emailSender = new CognitoSender({
  from: {
    email: "testaddress@example.com",
    name: "Test Address",
  },
  replyTo: "info@example.com"
  sourceArn: "arn for source"
});
```

Finally, if the user wants to use SES the user can specify the optional _configurationSet_ property.
```typescript
let emailSender = new SESSender({
  configurationSet?: "String"
  from: {
    email: "testaddress@example.com",
    name: "Test Address",
  },
  replyTo: "info@example.com"
  sourceArn: "arn for source"
});
```

As you can see I propose to split the _From_ property in two, allowing better check of correctness (and helping the user understand how to use the field.
```typescript
/**
 * Represents the From field.
 * If only email is set the output value should be the email address, otherwise
 * the outcome should be `name <email>` (i.e. Test User `<testuser@acme.com>`)
 */
export interface FromEmailAddress {
    /**
     * The email for the From field.
     *
     * @example testuser@example.com
     */
    readonly email: string

    /**
     * The optional sender's name
     *
     * @example Test User
     */
    readonly name?: string
}
```

### To Do

 * [ ] check if some role is created and if cdk should perform some operation (e.g. to allow Cognito to use the identity specified in SourceArn);
 * [ ] check if some SES resource could be used to auto populate some fields in Cognito and SES senders:
    - `CfnConfigurationSet` could be accepted in the _configurationSet_ property

---

I will start working soon on a PR.

**Comment by asterikx** [comment] 2020-05-31 08:37
Is it possible to import/lookup `sourceArn` of a verified email address by its, e.g. `verified@exmaple.com`?

Ideally, it should be possible to specify any "from" email, and, if unverified, `cdk deploy` triggers verification and blocks until the user has received and confirmed the verification email (similarly to the `DnsCertificate` construct).

**Comment by rinde** [comment] 2020-07-02 10:23
Is there a reason why this issue is not marked as required for graduation in [this overview](https://github.com/aws/aws-cdk/issues/8629)? According to the [Cognito limits](https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html) that come with the default settings, maximum 50 emails can be sent per day, severely limiting the number of people that can use my service. Therefore, I think this is an important feature to have in the CDK.

Is there currently a workaround for a UserPool that is configured using the CDK high level constructs to enable email sending via SES? Or is the only way to rewrite my stack using the lower level CloudFormation constructs for UserPool?

**Comment by asterikx** [comment] 2020-07-02 10:56
@rinde The workaround is quite easy.

Just change the `emailConfiguration` by modifying the CFN resource encapsulated by the CDK UserPool construct (see CDK Developer Guide [here](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource)):

```ts
const cfnUserPool = userPool.node.defaultChild as cognito.CfnUserPool;

cfnUserPool.emailConfiguration = {
  emailSendingAccount: 'DEVELOPER',
  from: `Someone from MyService <${fromEmailAddress}>`,
  sourceArn: `arn:aws:ses:eu-west-1:${this.account}:identity/${fromEmailAddress}`, // SES integration is only available in us-east-1, us-west-2, eu-west-1
};
```

I agree that these SES configurations should be added to the CDK construct since almost every customer-facing app requires SES instead of Cognito's built-in email capabilities.

Note that the sending email address (`fromEmailAddress` above) must be verified in SES (see [SES Developer Guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html)) and the SES account must be moved out of the SES Sandbox to send emails to unverified email addresses (your customers). See the SES Developer Guide [here](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html) and [here](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html?icmpid=docs_ses_console) for more details.

**Comment by gregorypierce** [comment] 2020-08-14 05:57
I'd specifically like Pinpoint integration. If I've already got a Pinpoint app, I already have a MANAGED mechanism to send emails, texts, etc. I wouldn't want to create a new channel to support Cognito "just because".

**Comment by nija-at** [comment] 2020-08-14 10:11
As far as I can tell, Pinpoint is an analytics system. This issue is regarding sending emails and integrating SES with user pools. Please open a separate issue, if you're interested in a different feature.

**Comment by gregorypierce** [comment] 2020-08-14 22:57
I'll open a different issue, but Pinpoint isn't (specifically) an analytics system. It's an aggregation of all the messaging channels for SMS, Voice, Email, Push Notifications, Messaging campaigns, etc. It's closer to Mailchimp than it is anything specifically related to analytics.

**Comment by apoorvmote** [comment] 2020-09-22 10:10
Is there any workaround for adding custom cloudformation include for ses support?

I was learning cloudformation but when I found out about CDK then I abandoned cloudformation and completely forgot everything I learned about cloudformation. I am actually looking for excuse to actually finish learning cloudformation.

But if I learned cloudformation then can I fill gaps of CDK? or I cannot override CDK code with custom cloudformation?

**Comment by ricardosllm** [comment] 2020-10-05 09:07
+1

**Comment by wichert** [comment] 2020-12-31 15:11
@asterikx Your workaround only works if you use TypeScript as far as I can see? I don't see how you can do the same thing from Python.

**Comment by straygar** [comment] 2021-01-04 11:51
@wichert Please check [the docs on Escape Hatches ](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) for how to modify the CFN layer in other CDK languages. :)

**Comment by Elegie** [comment] 2021-01-05 15:44
Hello. I've tried using @asterikx 's workaround, but it seems to require one of the following regions:  `us-east-1`, `us-west-2`, `eu-west-1`. I think it might be a hard-coded obsolete check, because SES is now available in other regions as well (I'm working in `ap-southeast-1` (Singapore), where SES has been made available since summer '20).

Is there another workaround? I'm working with the latest version of CDK, and don't know about Cloudformation (yet). Cheers.

**Comment by asterikx** [comment] 2021-01-05 16:01
@Elegie While SES is available in many regions, Cognito integration with SES is only supported in `us-east-1`, and `us-west-2`, `eu-west-1`, AFAIK.

The [English docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html#user-pool-email-developer) state:
> Available regions for Amazon SES are US East (N. Virginia)us-east-1, US West (Oregon) us-west-2, and Europe (Ireland)eu-west-1.

The [German docs](https://docs.aws.amazon.com/de_de/cognito/latest/developerguide/user-pool-email.html#user-pool-email-developer) has additional information: 
> Available regions for Amazon SES are US East (N. Virginia)us-east-1, US West (Oregon) us-west-2, and Europe (Ireland)eu-west-1. Amazon SES does not support receiving emails in the following regions: Asia Pacific (Mumbai), Asia Pacific (Sydney), Canada (Central), Europe (Frankfurt), Europe (London), South America (São Paulo), and AWS GovCloud (USA).

So, I guess, you will need to use one of `us-east-1`, `us-west-2`, or `eu-west-1` to be able to receive emails (which is important for bounces). I'm guessing here, though.

**Comment by misterjoshua** [comment] 2021-01-13 19:38
> Hello. I've tried using @asterikx 's workaround, but it seems to require one of the following regions: `us-east-1`, `us-west-2`, `eu-west-1`. I think it might be a hard-coded obsolete check, because SES is now available in other regions as well (I'm working in `ap-southeast-1` (Singapore), where SES has been made available since summer '20).
> 
> Is there another workaround? I'm working with the latest version of CDK, and don't know about Cloudformation (yet). Cheers.

@Elegie Unless you're restricted by some other policy, you can set up a sender identity in one of those supported regions and use it from a user pool in a different region. But, you'll need to make sure you have SES production access in the SES region.

Here's what I've done in my case - my user pool is in `ca-central-1`, but I'm using an SES sender identity in `us-east-1`.
![image](https://user-images.githubusercontent.com/644092/104500508-c21e7580-559b-11eb-89f4-5bda4caf8af3.png)

**Comment by Elegie** [comment] 2021-01-14 08:16
Hi @misterjoshua and @asterikx , thanks for your comments. I have access to all regions in my context, so have set up Cognito and SES as you two suggested. I could not test it yet, but given that it was correctly provisioned by Cloudformation I'm rather confident it'll work. I think it's a very reasonable solution. Cheers.

**Comment by grouchal** [comment] 2021-03-04 19:37
:+1:

**Comment by douglasnaphas** [comment] 2021-03-06 17:29
@misterjoshua I have attempted to use the workaround from @asterikx using your advice.

My from-address is in `us-east-1`, a supported region for SES integration. My Cognito user pool is in `us-west-1`.

I am getting the following error when I `cdk deploy`:

> Invalid EmailConfiguration.SourceArn. Provided SourceArn must be in the us-west-1 SES region. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException;

My from-address is not yet enabled for production sending, but I would not expect that to lead to this error.

The portion of my code in `lib/` where I attempt to implement the workaround is:

```ts
    let cfnUserPool;
    if (props?.sesVerificationConfig) {
      cfnUserPool = userPool.node.defaultChild as cognito.CfnUserPool;
      cfnUserPool.emailConfiguration = {
        emailSendingAccount: "DEVELOPER",
        from: `Mad Liberation Verification <${props?.sesVerificationConfig?.fromAddress}>`,
        sourceArn:
          // SES integration is only available in us-east-1, us-west-2, eu-west-1
          `arn:aws:ses:${props?.sesVerificationConfig?.fromRegion}` +
          `:${this.account}:identity/` +
          `${props?.sesVerificationConfig?.fromAddress}`,
      };
    }
```

`props.sesVerificationConfig.fromRegion` is `us-east-1`.

@misterjoshua, @asterikx, or others, any insight into how I might resolve this error would be greatly appreciated.

**Comment by misterjoshua** [comment] 2021-03-06 18:17
> @misterjoshua, @asterikx, or others, any insight into how I might resolve this error would be greatly appreciated.

@douglasnaphas Haha. This problem is a little slippery. I did manage to get something to deploy in `us-west-1`, but not with a cross-region sender identity.

```ts
new cognito.CfnUserPool(this, 'UserPool', {
  emailConfiguration: {
    emailSendingAccount: 'DEVELOPER',
    // Verified email address instead of domain sender identity.
    sourceArn: 'arn:aws:ses:us-west-1:11111111111111:identity/xxxx@xxxxxxxxx.com',
    from: 'My email <xxxx@xxxxxxxxx.com>',
  },
});
```

This is what it's looking like in the user pool in us-west-1:

![image](https://user-images.githubusercontent.com/644092/110216617-4d660a00-7e6d-11eb-8d69-51368b3b0308.png)

**Comment by viventra** [comment] 2021-03-11 06:35
> @wichert Please check [the docs on Escape Hatches ](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html#cfn_layer_resource) for how to modify the CFN layer in other CDK languages. :)

I am trying to specify SES configuration in CDK in C#.NET.

```
            var cfnUserPool = userPool.Node.DefaultChild as CfnUserPool;
            cfnUserPool.EmailConfiguration = new Amazon.CDK.CfnResource(this, "userPoolEmailConfig", new Amazon.CDK.CfnResourceProps() {
                Type = "AWS::Cognito::UserPool.EmailConfiguration",
                Properties = new Dictionary<string, object> {
                    ["EmailSendingAccount"] = "DEVELOPER",
                    ["From"] = $"Support <{support_email}>",
                    ["SourcArn"] = $"arn:aws:ses:{this.Region}:{this.Account}:identity/{support_email}"
                }
            });
```

But, I get the following error:

```
D:\src\Api>cdk deploy
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Resolution error: Resolution error: Unable to resolve object tree with circular reference. Path: /Resources/${Token[ApiStack.userpool.Resource.LogicalID.1042]}/Properties/emailConfiguration/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node/host/node..
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()

   ... (repetitions elided) ...

   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.TryDeserialize[TResponse](String responseJson)
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Invoke(InvokeRequest request)
   at Amazon.JSII.Runtime.Services.Client.Invoke(ObjectReference objectReference, String method, Object[] arguments)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<>c__DisplayClass17_0`1.<InvokeInstanceMethod>b__1(IClient client, Object[] args)     
   at Amazon.JSII.Runtime.Deputy.DeputyBase.<InvokeMethodCore>g__GetResult|18_0[T](<>c__DisplayClass18_0`1& )
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeMethodCore[T](JsiiMethodAttribute methodAttribute, Object[] arguments, Func`3 beginFunc, Func`3 invokeFunc)
   at Amazon.JSII.Runtime.Deputy.DeputyBase.InvokeInstanceMethod[T](Type[] parameterTypes, Object[] arguments, String methodName) 
   at Amazon.CDK.Stage.Synth(IStageSynthesisOptions options)
   at Api.Program.Main(String[] args) in D:\src\Api\Program.cs:line 14
Subprocess exited with error 3762504530

```

Please help. Also, my REGION is ap-south-1. The verified email Arn is 

arn:aws:ses:{this.Region}:{this.Account}:identity/{support_email}

Should I be verifying the email address with SES in one of the SES integration supported regions (say us-west-1) in addition to verifying it in ap-south-1 and use the ARN of the us-west-1 verified address?

**Comment by viventra** [comment] 2021-03-11 07:03
I figured it out. I used the Amazon.CDK.AWS.Cognito.CfnUserPool.EmailConfigurationProperty type.

            cfnUserPool.EmailConfiguration = new Amazon.CDK.AWS.Cognito.CfnUserPool.EmailConfigurationProperty() {
                EmailSendingAccount = "DEVELOPER",
                From = $"Support <{support_email}>",
                SourceArn = $"arn:aws:ses:{this.Region}:{this.Account}:identity/{support_email}"
            };

**Comment by mikerudge** [comment] 2021-04-09 17:36
+1

**Comment by sdeby** [comment] 2021-04-15 13:33
+1

**Comment by BinyominCohen** [comment] 2021-06-30 19:32
+1

**Comment by spifd** [comment] 2021-07-20 15:29
> If you would like this to be implemented, give this issue a +1. Until then, you can use the cfn layer to configure this.
+1

**Comment by RigoIce** [comment] 2021-07-29 16:58
+1

**Comment by alehatsman** [comment] 2021-08-14 12:19
+1

**Comment by guzmonne** [comment] 2021-08-18 18:01
+1

**Comment by vramanlal** [comment] 2021-08-20 23:17
+1

**Comment by bykka** [comment] 2021-09-12 19:20
+1

**Comment by bndkt** [comment] 2021-09-15 03:09
+1

**Comment by OuFinx** [comment] 2021-09-16 13:39
+1

**Comment by myron-semack** [comment] 2021-09-22 14:23
+1

**Comment by giomarino** [comment] 2021-09-29 12:49
+1

**Closed** 2021-11-15 20:53 UTC
Labels: p1, feature-request, @aws-cdk/aws-cognito, effort/medium
