### ISSUE TITLE
aws-lambda: add permissions to imported functions

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#8726] opened 2020-06-24 23:31 UTC
```typescript
const destFunc = lambda.Function.fromFunctionArn(arn);
new logs.SubscriptionFilter(this, `subscriptionFilter`, {
  destination: new logsDestinations.LambdaDestination(destFunc),
  filterPattern,
  logGroup,
});
```

This causes an error in deployment, `Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.`.

Normally such permission should be created in [`LambdaDestination.bind()`](https://github.com/aws/aws-cdk/blob/5091333/packages/@aws-cdk/aws-logs-destinations/lib/lambda.ts#L16-L22). But don't for imported function because of [here](https://github.com/aws/aws-cdk/blob/5091333/packages/@aws-cdk/aws-lambda/lib/function-base.ts#L203-L206).

AWS CDK: 1.46.0
OS: Linux
Language: TypeScript 3.9.5

**Comment by rix0rrr** [comment] 2020-07-08 10:03
I'm wondering why we don't add permissions to an imported function. Looks like we totally could.

**Comment by nija-at** [comment] 2020-07-08 10:34
Duplicate of https://github.com/aws/aws-cdk/issues/7588

**Closed by nija-at** 2020-07-08 10:34 UTC
Labels: @aws-cdk/aws-lambda, @aws-cdk/aws-logs, feature-request, needs-triage
