### ISSUE TITLE
StepFunction Service Integration with DynamoDb

### ISSUE THREAD

**Issue by sacag** [aws/aws-cdk#5782] opened 2020-01-13 21:22 UTC
### Description
Seems like the service integration between step function and dynamodb api is missing? Or is it lack of documentation? See the below code snippet which works for publishing to SNS from step-function task. Cannot find anything to do the same for dynamodb. 

```csharp
var snsTopicTask = new Task(this, "snsTopicTask", new TaskProps
            {
                InputPath = "$",
                Task = new PublishToTopic(snsTopic, new PublishToTopicProps
                {
                    IntegrationPattern = ServiceIntegrationPattern.FIRE_AND_FORGET,
                    Message = TaskInput.FromDataAt("$.lambdaResult"),
                    Subject = $"Test subject"
                })
            });
```

### Reproduction Steps

Cannot find a similar way to interact with Dynamodb in the step function task as you can see above for SNS (PublishToTopic).

### Environment

  - **CLI Version:**
  - **Framework Version:** 1.20
  - **OS:** Windows
  - **Language:** C#

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment] 2020-01-13 22:52
Hi @sacag thanks for reporting this bug. In order to understand the issue better could you give us a full description of the issue you're encountering. You can just edit your initial post and add a description under the first section. Thanks!

**Comment by sacag** [comment] 2020-01-14 01:09
@SomayaB - Sorry, missed the bug description. Should be there now. Basically, there doesn't seem to be a way to access the dynamodb api from step functions in C# CDK. Although, the documentation says otherwise.

**Comment by sacag** [comment] 2020-01-15 00:57
@SomayaB - Any update on this issue?

**Comment by SomayaB** [comment] 2020-01-15 19:35
Thanks for adding a description @sacag! We're looking into this and will update this issue when there is movement.

**Comment by rix0rrr** [comment] 2020-01-16 12:34
You are right that there are no pre-built constructs that expose this functionality right now. You can implement it yourself by implementing `IStepFunctionsTask` and returning the right fields.

**Comment by sacag** [comment] 2020-01-16 14:56
@rix0rrr - As of now we are creating a lambda function which interacts with the dynamodb and passes on the result to next task. Is there a timeline when a pre-built construct for this will be available for .NET?

**Comment by ayush987goyal** [comment] 2020-04-03 11:36
Hi @nija-at , Is this issue a duplicate of #6468 ?

**Comment by nija-at** [comment] 2020-04-03 12:39
Looks like it. Thanks for fishing this out. 

Resolving, @ayush987goyal has implemented this and will be available in the next CDK release.

**Closed** 2020-04-03 12:40 UTC
Labels: effort/medium, feature-request, package/stepfunctions
