### ISSUE TITLE
[docdb] DatabaseInstance is not properly setting default autoMinorVersionUpgrade

### ISSUE THREAD

**Issue by ddneilson** [aws/aws-cdk#9503] opened 2020-08-07 02:42 UTC
Quite simple, really. [This line](https://github.com/aws/aws-cdk/blob/1de9dc86a7990e8bd7c026bde59a02ecf0582616/packages/%40aws-cdk/aws-docdb/lib/instance.ts#L206) should be setting `autoMinorVersionUpgrade` to `true` when the value is not provided in the properties. See: https://github.com/aws/aws-cdk/blob/1de9dc86a7990e8bd7c026bde59a02ecf0582616/packages/%40aws-cdk/aws-docdb/lib/instance.ts#L144

### Reproduction Steps

Create any DocDB database cluster using the L2 construct.

### What did you expect to happen?

Instances within the cluster have `autoMinorVersionUpgrade` set to true so that they automatically get security patches and such that are pushed out by the DocumentDB team.

### What actually happened?

`autoMinorVersionUpgrade` is set to `false` as per the docdb `describe-db-instances` API

### Environment

  - **CLI Version      :** 1.52.0
  - **Framework Version:** 1.52.0
  - **Node.js Version:** any
  - **OS               :** any
  - **Language (Version):** any

### Other

By way of more detail, the implementation for the `DatabaseInstance` seems to be relying on the default behavior of the DBInstance as documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbinstance.html#cfn-docdb-dbinstance-autominorversionupgrade

However, there appears to be a bug with either that documentation or the DocDB service (that I've also reported now) in that the resulting instance does not actually have that value set properly. 

My generated CloudFormation was:
```json
    "DocDBClusterInstance15E47FA80": {
      "Type": "AWS::DocDB::DBInstance",
      "Properties": {
        "DBClusterIdentifier": {
          "Ref": "DocDBCluster37494708"
        },
        "DBInstanceClass": "db.r5.xlarge"
      },
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "DocDBStorageTier/DocDBCluster/Instance1"
      }
    }
```

and the describe API indicates:
```json
$ aws docdb describe-db-instances --db-instance-identifier docdbclusterinstance...f --output json
{
    "DBInstances": [
        {
...
            "EngineVersion": "3.6.0",
            "AutoMinorVersionUpgrade": false,
            "PubliclyAccessible": false,
...
}
```

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2020-08-09 10:33
Closing as duplicate of https://github.com/aws/aws-cdk/issues/9494

**Closed by iliapolo** 2020-08-09 10:33 UTC
Labels: @aws-cdk/aws-docdb, bug, in-progress, needs-triage
