### ISSUE TITLE
AWS SSO Named Profiles Support

### ISSUE THREAD

**Issue by vikyol** [aws/aws-cdk#5455] opened 2019-12-17 14:50 UTC
AWS CLI v2 supports [AWS SSO named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html). 

However, CDK CLI cannot resolve SSO named profiles yet.

```
$ cdk deploy --profile sso-named-profile

Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
```

Without this feature,  users have to login to SSO user portal and [fetch credentials for command line and CLI access](https://aws.amazon.com/blogs/security/aws-single-sign-on-now-enables-command-line-interface-access-for-aws-accounts-using-corporate-credentials/), which needs to be repeated every time the credentials expire. 

Even though CLI v2 is still in preview, it would be good to have this feature implemented for early adopters.  

### Use Case
- Simplify deployments to multiple-accounts for AWS SSO users.

### Proposed Solution

- Read sso_start_url, sso_role_name and sso_account_id from ~/.aws/config file.
- Fetch the accessToken in ~/.aws/sso/cache/ matching sso_start_url.
- Fetch temporary credentials from STS using SSO.get-role-credentials() with accessToken, sso_account_id and sso_role_name parameters.

---

This is a :rocket: Feature Request

**Comment by excavador** [comment] 2020-04-17 23:41
+1

**Comment by Douglas-Scott** [comment] 2020-04-17 23:43
+1

**Comment by shivlaks** [comment] 2020-04-18 00:02
@excavador @Douglas-Scott can you please represent your `+1` as a reaction to the feature request to capture your interest in this being implemented. It helps make it searchable and doesn't clutter up the thread.

**Comment by ReidWeb** [comment] 2020-04-20 21:50
Given the CLI is now GA, and it seems a number of other users are facing this issue would it be possible to at least add a note to the docs indicating the lack of support at this time?

**Comment by ibex-dev** [comment] 2020-05-06 18:11
As a temporary workaround, you can use the `aws sso login` feature to authenticate your CLI and export the retrieved access key ID, secret access key and session token as environment variable (json saved by default under ~/.aws/cli/cache/).
I wrote a quick bash wrapper for `aws sso login` that takes care of that. I invoke it once a day. If you don't feed a profile to CDK, it will look next for your env variables, so that does the trick.

**Comment by brainstorm** [comment] 2020-05-27 00:28
@ibex-dev Would you mind sharing that bash wrapper here? :)

**Comment by nspottsie** [comment] 2020-06-20 23:47
The mention from @victorskl above suggests using [yawsso](https://github.com/victorskl/yawsso) as a work around to sync the SSO credentials from ~/.aws/cli/cache to ~/.aws/credentials and it worked for me.

**Comment by beuleal** [comment] 2020-06-25 08:20
I know its a bit old, but I'd like to contribute too.

I was facing the following error:
_Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment_

I did a wrap for deploy into multiples account:

`
...
  console.log(` Setting Profile: ${account.name}`);
  let access_key = execSyncCmd(
    `aws configure get aws_access_key_id --profile ${account.name}`
  );

  let aws_secret_access_key = execSyncCmd(
    `aws configure get aws_secret_access_key --profile ${account.name}`
  );

  console.log(access_key);
  console.log(aws_secret_access_key);

  execSyncCmd(
    `aws configure set aws_access_key_id ${access_key} --profile default`
  );

  execSyncCmd(
    `aws configure set aws_secret_access_key ${aws_secret_access_key} --profile default`
  );

  execSyncCmd(`aws configure set region us-east-1 --profile default`);

  console.log(`[OK] Profile Set!`);

  execSyncCmd(`cdk deploy <stack-name> `);
...
`

**Comment by mateja82** [comment] 2020-06-25 15:45
Not sure if this helps anyone, but in my organization we use AWS SSO, with over 90 AWS Accounts, with MFA, so it was impossible to manage CDK without AWS SSO support. I found a way to solve it, so till its officially relesed, you can use this, it works quite all right: [MatsCloud blog - CDK with AWS SSO multi account multi profile](https://www.matscloud.com/blog/2020/06/25/how-to-use-aws-cdk-with-aws-sso-profiles/)

**Comment by gnomeria** [comment] 2020-08-01 04:48
Actually when this issue => https://github.com/aws/aws-cdk/issues/1656 been resolved based on https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html, at least we have a more proper workaround. Been using https://github.com/benkehoe/aws-sso-credential-process to get the credential_process for deploying through terraform

**Comment by shortjared** [comment] 2020-10-21 15:04
Howdy all, we solved this with exactly the following for AWS SSO... apologies for the copypaste from our internal docs but it is the quickest way to share.

The primary way you’ll likely interact with your CDK apps and AWS is through the CLI.

We’ll need a few things installed in order for a smooth process, once you do this once, you are set up for life (or until you need a new machine, whichever comes first.)

- [install / update brew](https://brew.sh)

Run these commands
```shell
brew install pipx
pipx ensurepath
pipx install aws-sso-credential-process
pipx install aws-export-credentials
```

[Install AWS CLI v2](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html)… the v2 part is very important.

Add the following to you .zshrc or bash or whatever.

```bash
export AWS_CONFIGURE_SSO_DEFAULT_SSO_START_URL=https://stedi-sso.awsapps.com/start
export AWS_CONFIGURE_SSO_DEFAULT_SSO_REGION=us-east-1
sso(){
  unset AWS_PROFILE
  export AWS_PROFILE=$1
  aws sts get-caller-identity &> /dev/null || aws sso login || (unset AWS_PROFILE && aws-configure-sso-profile --profile $1)
  eval $(aws-export-credentials --env-export)
}
```

Usage

In a new shell (after you’ve added the sso function), do a simple `sso {yourteam}-dev`. On the first time you do this for any new “profile” name, it will say it isn’t found and step you through an SSO process that will interact with your default browser. 

The command will walk you through a series of questions that will allow the AWS profile to be configured locally. 

The first thing you will see is something like “There are [some number] AWS accounts available to you. At some point, your browser will load a series of signin screens. Enter your password, etc. if you are not already authenticated. Once you are done, return to the CLI, where you will click the account that you would like to use. If there are multiple roles available to you, you will be asked to select a role.

Once you configure this for a profile, you never have to walk through the config process again. You have to log in once every X hours for a given role (depending on your org settigns), otherwise, the `sso {yourteam}-dev` will just drop right into those creds as well as source them into your environment.

Test that you are authenticated properly by issuing the following AWS command: `aws s3 ls`

Behind the scenes, this process is adding an entry to `~/.aws/config`. You can always drop into that file with your favorite text editor and modify the configuration. If you later discover that you chose the wrong account or role you can remove the profile from this configuration file and repeat the above process again.

**Comment by pahud** [comment] 2020-10-21 16:14
@shortjared Instead of exposing the credentials in env var, I have another preferable approach to generate or refresh the `~/.aws/credentials` instead.

https://github.com/pahud/gitpod-workspace/blob/main/utils/refresh_credentials.sh

And I use this approach to create [my gitpod workspaces](https://github.com/pahud/gitpod-workspace) for aws cdk development with aws sso support.

**Comment by redbaron** [comment] 2020-11-28 12:05
It is possible to have "native" integration with the help of [aws2-wrpa](https://pypi.org/project/aws2-wrap/)

Here is my `~/.aws/config` :

```
[profile mycorp-sso]
sso_start_url = https://d-*******.awsapps.com/start
sso_region = eu-west-1
sso_account_id = 99999999999
sso_role_name = AWSAdministratorAccess
region = eu-west-2

[profile mycorp]
credential_process = aws2-wrap --process --profile mycorp-sso
region = eu-west-1
```

You then use `mycorp` profile with CDK and visual studio code.

**Comment by ryan-mars** [comment] 2020-12-07 20:07
I started using `aws-sso-util` which supersedes `aws-sso-credential-process` as recommended by @shortjared. 

It is made by @benkehoe. 
https://github.com/benkehoe/aws-sso-util

**Comment by urz9999** [comment] 2021-01-14 11:15
In case like this one or other similar cases where AWS SSO result in incompatibilities with your library and you don't want to play with workarounds or complicated fixes, maybe you can give a try to our open-source project: [https://github.com/Noovolari/leapp](https://github.com/Noovolari/leapp). It deals with AWS SSO authentication and accounts/roles retrieval then it creates short-lived temporary credentials in .aws/credentials to maximize compatibility with third party tools / sdks.

**Comment by Stf-F** [comment] 2021-03-16 17:54
Hi, is there any plan to have a native support of AWS SSO with the CDK?
I used @redbaron recommendation and it worked like a charm but still feels like a hacky workaround. 
Cheers

**Comment by hoegertn** [comment] 2021-03-16 19:44
AFAIK the JS SDK does not support SSO so CDK cannot do it either. Credentials process is the only solution today to solve this.

**Comment by benkehoe** [comment] 2021-03-17 14:08
The JS SDK v3 [implemented support for AWS SSO](https://github.com/aws/aws-sdk-js-v3/pull/2055) but as far as I can tell [it has not shipped yet](https://github.com/aws/aws-sdk-js-v3/blob/master/CHANGELOG.md)

**Comment by wolverian** [comment] 2021-03-17 16:53
@benkehoe you're looking in the wrong branch - `main` has it: https://github.com/aws/aws-sdk-js-v3/blob/main/CHANGELOG.md

**Comment by benkehoe** [comment] 2021-03-17 16:57
Aha! That's good (though as they changed the name of the default branch, I would have assumed they would have removed the previous default). So the point is, _if_ the CDK moved to JS SDK v3, they'd gain support for SSO profiles.

**Comment by polothy** [comment] 2021-04-29 18:00
Is it possible to get this in for CDK v2? Unsure how risky it is to upgrade JS SDK to v3.

**Comment by gergnz** [comment] 2021-05-07 01:23
Gah. You can't even jump via another role. This is quite infuriating.

**Comment by bzivic** [comment] 2021-05-20 03:58
> Gah. You can't even jump via another role. This is quite frustrating.

@shortjared comment from earlier really worked a treat.

https://github.com/aws/aws-cdk/issues/5455#issuecomment-713643500

If SDK v3 is used, well all be fine 🙏

**Comment by danielsharvey** [comment] 2021-06-01 05:29
My suggested workaround is to use the [AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/), specifically the [AWS Credential Provider for Node.JS](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_provider_node.html) which supports SSO credentials from the token cache.

So with an AWS SSO profile configured:
```
$ aws configure sso
SSO start URL [None]: https://xxx.awsapps.com/start
SSO Region [None]: ap-southeast-2
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.ap-southeast-2.amazonaws.com/

Then enter the code:

BXVX-XXXX
The only AWS account available to you is: 99999999999
Using the account ID 99999999999
The only role available to you is: MyPermissionSetRole
Using the role name "MyPermissionSetRole"
CLI default client Region [ap-southeast-2]:
CLI default output format [json]:
CLI profile name [MyPermissionSetRole-99999999999]:

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile MyPermissionSetRole-99999999999
```

(written to `~/.aws/config`)

Now use the following to obtain the session token etc to execute the CDK:
```
import { defaultProvider } from '@aws-sdk/credential-provider-node';
...
async function getCredentialsEnv(awsDeploymentProfile: string) {
  const credentials = await defaultProvider({ profile: awsDeploymentProfile })();
  return {
    AWS_ACCESS_KEY_ID: credentials.accessKeyId,
    AWS_SECRET_ACCESS_KEY: credentials.secretAccessKey,
    AWS_SESSION_TOKEN: credentials.sessionToken,
  };
}
...
await spawnP(
  'npm', [ 'run', 'cdk', ...cdkArgs ],
  {
    stdio: 'inherit',
    env: {
      ...process.env,
      ...await getCredentialsEnv('MyPermissionSetRole-99999999999'),
    },
  }
);
```

**Comment by aaronbrighton** [comment] 2021-06-29 22:19
For whatever reason, even with all the suggestions above I had quite a bit of trouble getting this working the way I wanted (setting an SSO-enabled named profile as the default).  Here is what I did to get this to work, hopefully it helps others:

Run AWS CLI V2's SSO configuration wizard:

```
$ aws configure sso
SSO start URL [None]: https://d-9*******9c.awsapps.com/start                                                                                                                                                       
SSO Region [None]: us-east-1                                                                                                                                                                                       
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-1.amazonaws.com/

Then enter the code:

P***-***P
There are 3 AWS accounts available to you.
Using the account ID 9149412*****
The only role available to you is: AWSAdministratorAccess
Using the role name "AWSAdministratorAccess"
CLI default client Region [None]: us-east-1                                                                                                                                                                        
CLI default output format [None]:          
CLI profile name [AWSAdministratorAccess-9149412*****]: Dev
To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile Dev
```

Set the AWS_PROFILE environment variable to the same as what you set above (Dev):

```
$ export AWS_PROFILE=Dev 
```
(you may want to add to .bashrc or some where else to persist)

Install **aws-sso-util**:

```
$ python3 -m pip install --user pipx
$ python3 -m pipx ensurepath
$ pipx install aws-sso-util
```

Use **aws-sso-util** to reconfigure the Dev profile:

```
$ aws-sso-util configure profile Dev
```
(there should be no output)

**Important:** You need to ensure `~/.aws/credentials` exists, otherwise CDK will fail with the following error when following the **AWS_PROFILE** environment variable: `Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment`

```
$ touch ~/.aws/credentials
```

You can confirm this is working by running:

```
$ cdk bootstrap
 ⏳  Bootstrapping environment aws://9149412*****/us-east-1...
 ✅  Environment aws://9149412*****/us-east-1 bootstrapped (no changes).
```

**Comment by benkehoe** [comment] 2021-07-01 19:50
If you're already going to install `aws-sso-util`, you can use `aws-sso-util configure profile Dev` as the first step, which will invoke `aws configure sso --profile Dev` when it sees that the profile is not configured.

**Comment by bernard-kowalski** [comment] 2021-10-01 22:36
When the problem with SSO named profiles will be resolved? Is it really CDK production ready? I cannot believe that it does not support SSO yet...

**Comment by mrpackethead** [comment] 2021-11-06 19:47
As it sits for me, all the workarounds for SSO, are significant friction, making it really unuseable.

**Comment by dbartholomae** [comment] 2021-11-07 11:07
For me, this got solved via [AWS vault](https://github.com/99designs/aws-vault).

**Comment by chrichts** [comment] 2021-11-19 02:24
@ericzbeard - is this something that's being considered at all? Are there blockers for implementing this that we just aren't aware of? This issue has been open for 2 years, so I just want to know if we should be looking for a more permanent workaround or if we can expect this to be implemented in the foreseeable future

**Comment by atkinson** [comment] 2021-11-28 11:56
CDK isn't usable without SSO support. 

At present, it's completely incompatible with orgs that use AWS Control Tower.

**Comment by mbergkvist** [comment] 2021-11-28 12:24
> CDK isn't usable without SSO support. 

Sync your profiles with e.g. yawsso. Slightly inconvenient, but usable.

**Comment by paulrob-100** [comment] 2022-01-10 12:16
@rix0rrr please could you help us understand where this is on the various roadmaps? 
I can see it in the [CLI project](https://github.com/aws/aws-cdk/projects/11) in the "Needs RFC" column  

I was hoping the CDK v2 would take the opportunity to upgrade to the AWS CDK for Javascript v3 which includes SSO support (see https://github.com/aws/aws-cdk/issues/5455#issuecomment-801111128), however it's still using aws-sdk v2.
I'm assuming that's why the effort is marked as large here. 

Could you indicate [which of the RFCs](https://github.com/aws/aws-cdk-rfcs), if any, plan to upgrade the SDK to v3? 
Please could you help with the visibility of this feature request on the main roadmap? :pray:

**Comment by rob3c** [comment] 2022-01-10 15:31
We've switched away from the IaC-unfriendly, rather opaque and inflexible Control Tower headache to the much nicer [org-formation](https://github.com/org-formation/org-formation-cli) project for easier AWS Organizations multi-account management using IaC. It works well with SSO, and although it's originally (and still primarily) a direct CloudFormation tool, it has CDK support.

We deploy the CDK bootstrap template across org accounts using its declarative OrganizationBinding syntax, and there's an [update-cdk](https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#update-cdk) task that deploys according to declared org account/OU patterns, applies temporary SSO credentials as the standard AWS environment variables, and lets you set parameters from across the org as CDK context variables. It also has the option of using custom deploy and remove commands if the defaults aren't sufficient.

 If you're missing CDK SSO support and also looking for a nice, compliance-friendly way to manage your organization using Infrastructure-as-Code, it may be worth taking a look. It doesn't require a greenfield project, so you can also just point it at an existing org and give it a try.

**Comment by dannysteenman** [comment] 2022-01-23 07:55
I wrote a small shell function that exports the temp credentials using `aws-vault` (`brew install aws-vault`) so you can run cdk commands using your sso profile. Just add the following function in your `.zshrc:

```zsh
# AWS Switch Profile
function awsprofile {
  if [[ -z "$1" ]]; then
    unset AWS_SDK_LOAD_CONFIG
    unset AWS_DEFAULT_PROFILE AWS_PROFILE AWS_EB_PROFILE
    unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_SESSION_EXPIRATION
    echo AWS Profile cleared.
    return
  fi

  export AWS_SDK_LOAD_CONFIG=true
  export AWS_DEFAULT_PROFILE=$1
  export AWS_PROFILE=$1
  export AWS_EB_PROFILE=$1

  creds=$(mktemp -d)/creds.json
  aws-vault exec ${AWS_PROFILE} -- env | grep AWS >$creds
  export AWS_ACCESS_KEY_ID=$(cat ${creds} | grep "AWS_ACCESS_KEY_ID" | cut -d '=' -f 2)
  export AWS_SECRET_ACCESS_KEY=$(cat ${creds} | grep "AWS_SECRET_ACCESS_KEY" | cut -d '=' -f 2)
  export AWS_SESSION_TOKEN=$(cat ${creds} | grep "AWS_SESSION_TOKEN" | cut -d '=' -f 2)
  export AWS_SESSION_EXPIRATION=$(cat ${creds} | grep "AWS_SESSION_EXPIRATION" | cut -d '=' -f 2)
  echo "Switched to AWS Profile: ${AWS_PROFILE}"
}
```

Then just run the following in your shell:
```zsh
awsprofile <sso_profile_name>
```

To stop your session run `awsprofile`.

If you're using a prompt like `starship` then it will also show the remaining time of the active credentials:

```zsh
$ awsprofile test-account
Opening the SSO authorization page in your default browser (use Ctrl-C to abort)
Switched to AWS Profile: test-account
~ on  test-account (eu-west-1) [59m34s] took 14s
```

**Comment by RichiCoder1** [comment] 2022-01-23 19:30
> I wrote a small shell function that exports the temp credentials using `aws-vault` (`brew install aws-vault`) so you can run cdk commands using your sso profile. Just add the following function in your `.zshrc`:

It's worth noting one of the reasons AWS Vault doesn't enable something like this by default is to not expose credentials unnecessarily. As mentioned above, the best (current) solution is SSO profiles combined with `aws-vault`'s [`credential_process`](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process) support which accomplishes effectively the same thing 😄.

**Comment by automartin5000** [comment] 2022-01-24 04:23
> > I wrote a small shell function that exports the temp credentials using `aws-vault` (`brew install aws-vault`) so you can run cdk commands using your sso profile. Just add the following function in your `.zshrc`:
> 
> It's worth noting one of the reasons AWS Vault doesn't enable something like this by default is to not expose credentials unnecessarily. As mentioned above, the best (current) solution is SSO profiles combined with `aws-vault`'s [`credential_process`](https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-credential_process) support which accomplishes effectively the same thing 😄.
> 
> ```ini
> [profile administrator-sso]
> sso_start_url=https://aws-sso-portal.awsapps.com/start
> sso_region=eu-west-1
> sso_account_id=123456789012
> sso_role_name=Administrator
> 
> [profile administrator]
> credential_process = aws-vault exec administrator-sso --json
> ```
> 
>  ```shell
> export AWS_PROFILE=administrator # or $env:AWS_PROFILE="administrator" for pwsh
> cdk deploy
> ```

Just tried this, and while I was able to get `aws-vault exec` working with AWS SSO, I couldn't get `credential_process` working. Kept getting `The provided token has expired`. Any ideas?

**Comment by RichiCoder1** [comment] 2022-01-24 05:22
> Just tried this, and while I was able to get `aws-vault exec` working with AWS SSO, I couldn't get `credential_process` working. Kept getting `The provided token has expired`. Any ideas?

I don't know what does or doesn't cause aws-vault to automatically kick of the interactive login, but the fix for this is to `aws sso login --profile <name-of-sso-profile>` so the `--profile administrator-sso` in this example. It's because the aws sso profile in question [doesn't have cached credentials yet]( https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#:~:text=Running%20a%20command%20with%20your%20AWS%20SSO%20enabled%20profile). 

It's worth noting these cached credentials will also last for an hour by default, which you can tweak if you need via the `duration_seconds` configuration option: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#:~:text=credential_source%20%3D%20Ec2InstanceMetadata-,duration_seconds,-Specifies%20the%20maximum (you'd be setting this on the sso profile)

**Comment by spence95** [comment] 2022-02-04 16:45
I was evaluating using CDK but due to this issue, I'm dumping it and just going back to plain CloudFormation.
This needs to be implemented natively with CDK.

**Comment by PatrykMilewski** [comment] 2022-02-04 17:07
> I was evaluating using CDK but due to this issue, I'm dumping it and just going back to plain CloudFormation. This needs to be implemented natively with CDK.

Lol man, don't do it to yourself, tools like Serverless Framework are way better for a lot of use cases comparing to CDK and in 2022 there is no valid argument to use plain CloudFormation

**Comment by automartin5000** [comment] 2022-02-04 17:54
Yeah seems kinda extreme to completely dump a tool just avoid an extra npm install

**Comment by andreacavagna01** [comment] 2022-02-04 18:20
> I was evaluating using CDK but due to this issue, I'm dumping it and just going back to plain CloudFormation.
> 
> This needs to be implemented natively with CDK.

You can still use it by managing ur profiles and everything with Leapp https://github.com/Noovolari/leapp

**Comment by spence95** [comment] 2022-02-04 18:43
>  in 2022 there is no valid argument to use plain CloudFormation

There's at least one, it integrates with SSO and lets you use --profile out of the box 
¯\_(ツ)_/¯

**Comment by alistairstead** [comment] 2022-02-04 18:50
I switched to using aws-vault and this limitation is resolved

**Comment by ReidWeb** [comment] 2022-02-04 18:51
Can I suggest folks start a discussion if they're going to start debating the validity of approaches and alternatives, you're sending emails to at least 42 people every time you comment on this, and I really don't care for any opinions at this point

**Comment by polothy** [comment] 2022-03-14 21:27
`aws-sdk-js` just released support for SSO: https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#210930

Hopefully that means CDK just needs to upgrade to this version for SSO support vs upgrading to v3.

**Comment by ann8ty** [comment] 2022-03-23 16:35
To overcome the issue, I have a cdk-login-env.sh script for every environment that looks kind of like this...the key for this problem is use of yawsso to copy the creds over.  

`COLOR='\033[1;32m'
NC='\033[0m'

CDK_PROFILE_NAME='userconfigured'

echo "${COLOR}SSO Login for ${CDK_PROFILE_NAME} ${NC}"
aws sso login --profile $CDK_PROFILE_NAME

echo "${COLOR}Copy to v1 credentials with yawsso${NC}"
yawsso -p $CDK_PROFILE_NAME

echo "${COLOR}CDK Bootstrap confirmation${NC}"
cdk bootstrap --profile $CDK_PROFILE_NAME

echo "${COLOR}CDK Diff - Testing credential and stacks${NC}"
cdk diff --all --profile $CDK_PROFILE_NAME`

**Comment by ChristopheBougere** [comment] 2022-03-23 16:38
> Hey guys! We recently moved to AWS SSO and are now encountering this issue.
> 
> The workarounds suggested are fine, but missing native support in CDK for SSO profiles is a huge oversight in my opinion.
> 
> Now that V2 of the AWS JS SDK supports SSO, hopefully this feature can get implemented soon!

It looks like SSO support has been merged 2 days ago in PR https://github.com/aws/aws-cdk/pull/19454

I'd say we can expect it to be available for the next release 🤞

**Comment by jessecollier** [comment] 2022-03-29 14:04
This was just released in 2.18.0 and 1.150.0. Confirmed it's working for me now!

**Comment by peterwoodworth** [comment] 2022-03-29 15:15
Thanks @jessecollier, you're right! Here's the PR https://github.com/aws/aws-cdk/pull/19454

**Closed by peterwoodworth** 2022-03-29 15:15 UTC
Labels: p1, feature-request, package/tools, effort/large

**Comment by LarsFronius** [comment] 2022-11-18 11:22
> @shortjared Thanks for the sharing.
> 
> Instead of exposing the credentials in env var, I have another preferable approach to generate or refresh the `~/.aws/credentials` instead.
> 
> https://github.com/pahud/gitpod-workspace/blob/main/utils/refresh_credentials.sh


FYI: Any of the workarounds that continue to use the implicit trust behaviour of SSO created roles don't work anymore with new roles and will stop to work by 15th of February 2023 due to https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/
