### ISSUE TITLE
(cli):  VpcNetworkContextProviderPlugin doesn't assume roles when doing cross account deploys

### ISSUE THREAD

**Issue by redbaron** [aws/aws-cdk#14673] opened 2021-05-13 07:37 UTC
### Reproduction Steps

This stack fails to `cdk synth` when called with credentials from account other than XYZ.

```
const app = new cdk.App();
new InfraStack(app, 'InfraStack', {
  env: { account: 'XYZ', region: 'eu-west-2' },
});

class InfraStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    ec2.Vpc.fromLookup(this, "primary", { vpcName: "primary" });
  }
}
```

### What did you expect to happen?

Lookup succeeds.

### What actually happened?

When running `cdk synth --profile ABC` following error happens during lookup:

```
[Error at /InfraStack] Need to perform AWS calls for account XYZ, but the current credentials are for ABC
  Annotations.addMessage (/home/mivanov/localrepos/user/infra/node_modules/@aws-cdk/core/lib/annotations.ts:92:25)
  Annotations.addError (/home/mivanov/localrepos/user/infra/node_modules/@aws-cdk/core/lib/annotations.ts:51:10)
  Function.getValue (/home/mivanov/localrepos/user/infra/node_modules/@aws-cdk/core/lib/context-provider.ts:106:31)
  Function.fromLookup (/home/mivanov/localrepos/user/infra/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1077:66)
  new InfraStack (/home/mivanov/localrepos/user/infra/lib/infra-stack.ts:11:24)
  Object.<anonymous> (/home/mivanov/localrepos/user/infra/bin/infra.ts:7:1)
  Module._compile (internal/modules/cjs/loader.js:1063:30)
  Module.m._compile (/home/mivanov/localrepos/user/infra/node_modules/ts-node/src/index.ts:1056:23)
  Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  Object.require.extensions.<computed> [as .ts] (/home/mivanov/localrepos/user/infra/node_modules/ts-node/src/index.ts:1059:12)
  Module.load (internal/modules/cjs/loader.js:928:32)
  Function.Module._load (internal/modules/cjs/loader.js:769:14)
  Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  main (/home/mivanov/localrepos/user/infra/node_modules/ts-node/src/bin.ts:198:14)
  Object.<anonymous> (/home/mivanov/localrepos/user/infra/node_modules/ts-node/src/bin.ts:288:3)
  Module._compile (internal/modules/cjs/loader.js:1063:30)
  Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  Module.load (internal/modules/cjs/loader.js:928:32)
  Function.Module._load (internal/modules/cjs/loader.js:769:14)
  Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  /usr/lib64/node_modules/npm14/node_modules/libnpx/index.js:268:14
Found errors
```

### Environment

  - **CDK CLI Version  :** 1.103.0
  - **Framework Version:** 1.103.0

### Other

When doing cross accounts deploys cdk CLI normally assumes role in the target account. It looks like context providers do not assume role:

https://github.com/aws/aws-cdk/blob/9a4d6243ae009dc02949dd2cf415523dbf582678/packages/aws-cdk/lib/context-providers/vpcs.ts#L17

```SdkProvider.forEnviornment``` support `assumeRoleArn` property, but VPC context provider doesn't pass it.

--- 

This is :bug: Bug Report

**Comment by redbaron** [comment] 2021-05-13 08:02
Probably first step would be to grant read only privileges to `cdk-hnb659fds-deploy-role-{ACCOUNT_ID}-{REGION}` deploy role. Currently it can't do much beyond calling Cloudformation, if it could do lookups too, then context providers can be changed to assume that role.

**Comment by rix0rrr** [comment] 2021-05-18 14:39
Duplicate of #8905

**Closed by rix0rrr** 2021-05-18 14:39 UTC
Labels: bug, needs-triage, package/tools
