### ISSUE TITLE
aws-auth: sdk-provider uses os.userInfo() which fails in containers without a home directory

### ISSUE THREAD

**Issue by Tanemahuta** [aws/aws-cdk#17454] opened 2021-11-10 15:14 UTC
### What is the problem?

When running CDK in a container for a user not having a home directory, it fails.

### Reproduction Steps

- create a container image with cdk and a simple stack (I used alpine and switched the user to 1001 in the Dockerfile)
- run the image with an entrypoint deploying the stack

Kindly note:
- newStyleStackSynthesis is activated
- pod has an IAM role attached (thus, role will be assumed)

### What did you expect to happen?

all should work fine.

#### Summary 
CDK errored.

#### Stacktrace
```sh
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at new SystemError (internal/errors.js:217:5)
    at new NodeError (internal/errors.js:302:7)
    at Object.userInfo (os.js:347:11)
    at safeUsername (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:440:13)
    at SdkProvider.withAssumedRole (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:318:37)
   at SdkProvider.forEnvironment (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/lib/api/aws-auth/sdk-provider.ts:159:28)
    at CloudFormationDeployments.prepareSdkFor (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:270:22)
    at CloudFormationDeployments.deployStack (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:190:70)
    at CdkToolkit.deploy (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
    at initCommandLine (/var/lib/cdk/inbound/node_modules/.pnpm/aws-cdk@1.130.0/node_modules/aws-cdk/bin/cdk.ts:225:9)
```

#### The line in question is:
https://github.com/aws/aws-cdk/blob/5c758919e6751f31143fa0979fdc1e040a6c6d11/packages/aws-cdk/lib/api/aws-auth/sdk-provider.ts#L440

#### Related Issue
- https://github.com/aws/aws-cdk/issues/7937

### CDK CLI Version

v1.132.0

### Node.js Version

14.18.1

### OS

alpine 3.14

### Language

Typescript

**Comment by rix0rrr** [comment] 2021-11-22 13:21
As you yourself pointed out, this is a duplicate of #17454

**Closed by rix0rrr** 2021-11-22 13:21 UTC
Labels: bug, p2, @aws-cdk/aws-iam, effort/medium
