### ISSUE TITLE
(@aws-cdk/aws-ec2): Proposed, Separate the "vpc" construct to each resource such as subnets, routes, nat-gateway.

### ISSUE THREAD

**Issue by wsscc2021** [aws/aws-cdk#14318] opened 2021-04-22 02:32 UTC
### Proposed
Separate the "vpc" construct to each resource such as subnets, routes, nat-gateway.

### Reason
The "vpc" construct is abstract to 3-tier architecture include aws resources such as vpc and subnet and nat-gateway and etc.
so if it use, can easily write code to provisioning 3-tier architecture and useful to mostly architecture.
However, I sometimes need to special architecture due to business constraint. in this case, it is difficult to modify detailed settings such as subnets and NATs. 
so I hope separate the "vpc" construct to each resource such as subnets, routes, nat-gateway and get a tenderness by de-couple each resource dependency.

### Proposed Solution
for example,
| construct name | description |
| --- | --- |
| vpc | Create only "vpc" |
| eip | Create only eip |
| nat-gateway | Create only nat-gateway |
| subnets | Create only subnets (there is already.) |
| ... | ... |

```
vpc = aws_ec2.vpc(self, "vpc"
    cidr_block="10.0.0.0/16",
    enable_dns_hostnames=True,
    enable_dns_support=True,
)

subnet['public'][0] = aws_ec2.Subnets(
    self, "public0",
    cidr_block="10.0.0.0/24",
    vpc_id=vpc.id,
    availability_zone="us-east-1a",
    map_public_ip_on_launch=True
)
subnet['public'][1] = aws_ec2.Subnets(
    self, "public1",
    cidr_block="10.0.1.0/24",
    vpc_id=self.vpc.id,
    availability_zone="us-east-1b",
    map_public_ip_on_launch=True
)
subnet['private'][0] = aws_ec2.Subnets(
    self, "private0",
    cidr_block="10.0.2.0/24",
    vpc_id=self.vpc.id,
    availability_zone="us-east-1a",
    map_public_ip_on_launch=True
)
subnet['private'][1] = aws_ec2.Subnets(
    self, "private1",
    cidr_block="10.0.3.0/24",
    vpc_id=self.vpc.id,
    availability_zone="us-east-1b"
)
...
```

**Comment by rix0rrr** [comment] 2021-05-10 11:18
Feels like a duplicate of #5927.

**Closed by rix0rrr** 2021-05-10 11:18 UTC
Labels: @aws-cdk/aws-ec2, feature-request, needs-triage
