### ISSUE TITLE
aws-logs.SubscriptionFilter does not add correct Lambda permissions

### ISSUE THREAD

**Issue by arnab** [aws/aws-cdk#7328] opened 2020-04-13 06:21 UTC
## Context

I am using [@aws-cdk/aws-logs.SubscriptionFilter](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs.SubscriptionFilter.html) to create a **CW Logs Subscription Filter** that invokes a **Lambda function**. 

CDK helpfully creates the Lambda permission bits ([@aws-cdk/aws-lambda.Permission](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Permission.html)) as part of this higher-order construct implicitly (as an underlying separate CF resource **AWS::Lambda::Permissions**).

This is done via `LambdaDestination#bind` in: https://github.com/aws/aws-cdk/blob/d7c40c5e6209de320d2b89f27e8684bebce35cf0/packages/%40aws-cdk/aws-logs-destinations/lib/lambda.ts#L13-L24

## Problem

The permission policy applied appears to be incorrect. CloudFormation deployment fails (for the SubscriptionFilter resource) with:

```
Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function. 
(Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: <REDACTED>)
```

Looking at the CW Logs docs (see **aws lambda add-permission** [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html)), the `sourceArn` needs to be `CwLogGroupArn:*` (note the **`:*`**). The above code sets it to be just the ARN of the logGroup (but not streams or other objects within it).

Manually adding another resource like this (source in Kotlin below) fixes the problem (verifying that it is indeed this permissions specification of the ARN that's wrong):

```kt
        val allowCwLogsToInvokeLambdaFn = Permission.Builder()
                .scope(lambdaFn)
                .action("lambda:invokeFunction")
                .principal(ServicePrincipal("logs.amazonaws.com"))
                .sourceArn("${myLogGroup.logGroupArn}:*")
                .build()
        lambdaFn.addPermission(lambdaPermissionId, allowCwLogsToInvokeLambdaFn)
```

**Comment by rix0rrr** [comment] 2020-04-16 09:17
Is your log group imported, by any chance? If so, this is a duplicate of https://github.com/aws/aws-cdk/issues/7096

**Comment by arnab** [comment] 2020-04-16 19:27
@rix0rrr ah yes, indeed it is imported. I get it using `LogGroup.fromLogGroupName`.

**Comment by rix0rrr** [comment] 2020-04-17 07:27
Alright, thanks. Closing as a dupe then.

**Closed by rix0rrr** 2020-04-17 07:27 UTC
Labels: bug, package/logs
