### ISSUE TITLE
(CodePipeline-Actions): Event created from ECR-Action does not use the default value the ECR-Action is using

### ISSUE THREAD

**Issue by Kruspe** [aws/aws-cdk#13818] opened 2021-03-26 15:57 UTC
When creating an ECR Action, CDK creates an CloudWatch event. I was expecting it to only listen on PutImage events for the `latest` tag since that is the default value provided by the docs and.

Instead the event listens on every tag.

### Reproduction Steps

``` TS
new EcrSourceAction({
      actionName: 'Image',
      repository,
      output: imageArtifact,
      variablesNamespace: 'ImageVariables',
    });
```
Creates an event that triggers for all PutImages regardless of the tag.
### What did you expect to happen?

``` TS
new EcrSourceAction({
      actionName: 'Image',
      repository,
      output: imageArtifact,
      variablesNamespace: 'ImageVariables',
      imageTag: 'latest',
    });
```
The event created by this check only the `latest` tag but I only inserted the tag that is provided by default.

### What actually happened?

The CW event listens for all PutImage calls regardless of the tag.

### Environment

  - **CDK CLI Version  : 1.95.1 (build ed2bbe6)**
  - **Framework Version: 1.95.1**
  - **Node.js Version: 15.12.0**
  - **OS               : BigSur 11.2.3**
  - **Language (Version): TypeScript (3.8.3)**

### Other
If the described behaviour is the desired one I can create a PR for it. :)

This is :bug: Bug Report

**Comment by skinny85** [comment] 2021-03-26 19:41
Hey @Kruspe ,

thanks for opening the issue. I wonder if this could be related to https://github.com/aws/aws-cdk/issues/10901?

Thanks,
Adam

**Comment by Kruspe** [comment] 2021-03-26 20:31
Hey @skinny85,

This seems to be unrelated. It might be connected but on my end the event does trigger an execution but simply not as I would expect it.

The event created by CDK is missing the tag information and thus triggers an execution for every new tag created through `PutImage`. Since the default value is `latest` I would expect the event to also only trigger an execution when an image with the `latest` tag is pushed.

Max

**Comment by skinny85** [comment] 2021-03-26 23:00
Yep @Kruspe, I think you're right.

I suspect the problem is here: https://github.com/aws/aws-cdk/blob/6743e3bb79a8281a4be5677fff018d702c85038d/packages/%40aws-cdk/aws-codepipeline-actions/lib/ecr/source-action.ts#L98-L98

We send the `props.imageTag` to the API that creates the Event, but we don't default it to 'latest' there, which is why it triggers for every push.

Let me work on a quick fix for this.

In the meantime, you should be able to work around this by explicitly passing `latest` as the `imageTag` property when creating the `EcrSourceAction`, like you posted.

Thanks,
Adam

**Comment by Kruspe** [comment] 2021-03-27 12:23
Sounds good.
Let me know if you need me to do anything on this :)

**Closed** 2021-04-02 22:35 UTC
Labels: @aws-cdk/aws-codepipeline-actions, bug, effort/small, in-progress, p1

**Comment by sparten11740** [comment] 2021-10-29 18:18
@skinny85 that sounds reasonable

**Comment by skinny85** [comment] 2021-10-29 23:20
@sparten11740 any chance you would be willing top open us a PR adding this feature? It should be relatively straightforward. Check out our ["Contributing guide"](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for some info on how to get started with CDK development.

**Comment by sparten11740** [comment] 2021-11-02 09:07
@skinny85 only today found the time to work on this, opened a PR with a proposed solution
