### ISSUE TITLE
[cli] Cloud assembly schema version mismatch

### ISSUE THREAD

**Issue by mydarpa** [aws/aws-cdk#11494] opened 2020-11-16 15:35 UTC
### The Question

I installed aws-cdk.aws-athena. Now the stack is not able to be synthesized with the following error:

`This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 6.0.0, but found 7.0.0)`

I tried `npm install -g aws-cdk` to upgrade the CDK CLI but the error remains. 

### Environment

  - **CDK CLI Version:**  1.72.0 
  - **Node.js Version:**  v15.2.0
  - **OS:**  OSX

**Comment by nemanjko** [comment] 2020-11-17 11:29
Same here. CDK version 1.73.0 (build eb6f3a9).

**Comment by nemanjko** [comment] 2020-11-17 15:30
Removed it all, updated aws-cdk, npm, node and now it works. Weird mismatch between package versions.

**Comment by hvpareja** [comment] 2020-11-17 16:18
Hi @nemanjko, what did you mean by "all" in removing? Did you have to uninstall npm, node and aws-cdk?

A colleague of me found the same solution as you, but I'd like to get a more elegant fix. I don't understand what is causing the issue.

Regards

**Comment by nemanjko** [comment] 2020-11-17 16:45
> Hi @nemanjko, what did you mean by "all" in removing? Did you have to uninstall npm, node and aws-cdk?

I first deleted my full CDK project. Pulled down again everything from CodeCommit, updated npm, node and aws-cdk to the latest versions. Then it worked again. 

No idea what the issue is and what was causing it. I just know that each time I would run "npm run cdk synth -- -o dist" I would get that error. Interestingly "cdk synth" on its own was working fine. 

Let me know if you find more elegant solution to fix it.

**Comment by hvpareja** [comment] 2020-11-18 11:52
Hi @nemanjko - Thanks for the challenge. I have some results, but I am not sure if we still can qualify them as "elegant". 

Refusing to start removing all, I wanted to explore what could be causing the issue. The error message says that you need to upgrade your CDK CLI, but we both did it and the error persisted.

What I have seen in my case is, even if I ran:

```
npm -i --force -g aws-cdk
```

and got a successful installation of **v1.74.0**, the output of ```cdk --version``` was still **v.1.72.0**. What was happening was that the symbolic link was pointing to a wrong path (I don't know why).

They way I fixed the problem was:

```
CDK_PATH=`which cdk`
rm $CDK_PATH
CDK_NODE_PATH=`npm get prefix 2> /dev/null`/bin/cdk
ln -s $CDK_NODE_PATH $CDK_PATH
```

I hope this brings some information to find the root cause (points to NPM though) and help other people.

**Comment by LeviSchuck** [comment] 2020-11-18 23:49
I ran into this issue, turns out my cdk install is from homebrew. Updating it via brew worked.

**Comment by rix0rrr** [comment] 2020-11-23 13:37
Doesn't seem to be actionable for us, closing this.

**Closed by rix0rrr** 2020-11-23 13:37 UTC
Labels: guidance, needs-triage, package/tools

**Comment by jaystary** [comment] 2020-12-05 09:58
Had the same issue - for me, this fixed the issue:
npm install -g aws-cdk

**Comment by brianfoody** [comment] 2021-01-20 03:11
Happens when there's a mismatch between global cdk and local cdk version. Upgrade all of 'em to resolve

**Comment by victormwenda** [comment] 2021-02-14 10:24
Faced the same issue. Fixed by : `pip install -r requirements.txt`

**Comment by adamdmarshall** [comment] 2021-05-24 11:23
I had to uninstall all aws global and local modules, remove the directory shown by "which cdk", remove node_modules, then re-install the lot. Very boring.

**Comment by Willooz** [comment] 2021-06-17 15:04
I solved this by upgrading my version of node from 12 to 14 (with nvm) for cdk 1.109.0.

`This CDK CLI is not compatible with the CDK library used by your application.` This might somehow mean your local version of node is too old for your cdk config...

**Comment by Raketenpete** [comment] 2021-06-18 12:01
> Happens when there's a mismatch between global cdk and local cdk version. Upgrade all of 'em to resolve

Saved our friday! Thank you<3

**Comment by mrglover** [comment] 2021-09-13 17:05
> Hi @nemanjko - Thanks for the challenge. I have some results, but I am not sure if we still can qualify them as "elegant".
> 
> Refusing to start removing all, I wanted to explore what could be causing the issue. The error message says that you need to upgrade your CDK CLI, but we both did it and the error persisted.
> 
> What I have seen in my case is, even if I ran:
> 
> ```
> npm -i --force -g aws-cdk
> ```
> 
> and got a successful installation of **v1.74.0**, the output of `cdk --version` was still **v.1.72.0**. What was happening was that the symbolic link was pointing to a wrong path (I don't know why).
> 
> They way I fixed the problem was:
> 
> ```
> CDK_PATH=`which cdk`
> rm $CDK_PATH
> CDK_NODE_PATH=`npm get prefix 2> /dev/null`/bin/cdk
> ln -s $CDK_NODE_PATH $CDK_PATH
> ```
> 
> I hope this brings some information to find the root cause (points to NPM though) and help other people.

This resolved the problem for me! thank you so much!

**Comment by jangroth** [comment] 2021-11-20 01:34
My cdk installation was borked as well. After uninstalling and confirming `npm list -g` showed no installed `cdk`, I still had the binary in the path under `/user/local/bin`/`user/local/lob` (ubuntu 20.04)

I resolved this manually.
