### ISSUE TITLE
(secretsmanager): using replicated secrets (permissions)

### ISSUE THREAD

**Issue by vespertilian** [aws/aws-cdk#17382] opened 2021-11-07 10:18 UTC
### General Issue

cannot grant access in both primary and replicated regions 

### The Question

Enjoying CDK thanks. 

I have created a secret via the CDK and I want to grant read access to it in lamdas that are deployed as part of the same app to different regions. 

### App looks something like this
```ts
const stage = 'dev'
const tableName = 'test-api-dynamo-table';
const primaryDomain = 'dev.mydomain.com'
const replicaRegions = ['ap-southeast-2'] // 1 for now more in the future

const dynamo = new DynamoStack(app, `${stage}-dynamo-db`, {
  replicaRegions,
  stage,
  env: usEast1Env,
  tableName
})

const secretStack = new SecretsManagerStack(app, `${stage}-secret`, {
  secretName: 'AuthToken',
  env: usEast1Env,
  replicaRegions,
  rotateInDays: 15
})

const apiStackUSEast = new ApiStack(app, `${stage}-${usEast1Env.region}-api`, {
  stage,
  env: usEast1Env,
  dynamoTable: dynamo.dynamoTable,
  tableName,
  primaryDomain,
  secret: secretStack.secret
});

const apiStackAPSouthEast2 = new ApiStack(app, `${stage}-${apSouthEast2Env.region}-api`, {
  stage,
  env: apSouthEast2Env,
  dynamoTable: dynamo.dynamoTable,
  tableName,
  primaryDomain,
  secret: secretStack.secret
})

```

### 1st attempt

I tried passing the secret in from the secret stack to my Api stack and grant access using the method found in the docs

```ts
   ... this code lives in an API stack that is deployed to multiple regions including the region the primary secret is deployed in
    const secret: Secret = props.secret

    // 1st attempt does not work in replicated zones
    const nameOnly = new lambda.Function(this, 'NameOnly', {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'name-only.handler',
      code: lambda.Code.fromAsset('name-only'),
      layers: [apiLayer],
      environment: {
        TABLE_NAME: props.tableName,
        AUTH_TOKEN_SECRET_KEY_ARN: secret.secretArn
      }
    })
    secret.grantRead(nameOnly)
```

The issue here is it only works for the primary region, not the replicated regions. 

### 2nd attempt

```ts
   ... this code lives in an API stack that is deployed to multiple regions including the region the primary secret is deployed in
    // 2nd attempt create the secret in the region from the secret name
    const secretInRegion = secretsmanager.Secret.fromSecretNameV2(this, 'secret', props.secret.secretName)

    const nameOnly = new lambda.Function(this, 'NameOnly', {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'name-only.handler',
      code: lambda.Code.fromAsset('name-only'),
      layers: [apiLayer],
      environment: {
        TABLE_NAME: props.tableName,
        AUTH_TOKEN_SECRET_KEY_ARN: secretInRegion.secretArn
      }
    })
    secretInRegion.grantRead(nameOnly)

``` 

The issue here is that this only works in the replicate regions :s,

#### policy generated in the replicated regions deployed api (works)

```json 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret"
            ],
            "Resource": "arn:aws:secretsmanager:us-east-1:477532313330:secret:AuthToken-??????",
            "Effect": "Allow"
        }
    ]
}
```

#### policy generated in the primary deployed api (does not work)

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret"
      ],
      "Resource": "arn:aws:secretsmanager:us-east-1:477532313330:secret:AuthToken-1aoeve-??????",
      "Effect": "Allow"
    }
  ]
}
```

The problem with the primary region now is that it includes both ???? and the random key (bug?)

Not sure if this is a bug or feature request, I feel like my second attempt should have worked. Would be great if there was a set way to grant access to the secret even in replicated regions. I feel like this would be possible to add as a feature. 

Maybe I missed something and there is a better way. 

Thanks in advance! 

### CDK CLI Version

1.130.0

### Node.js Version

14

### OS

OSX

### Language

Typescript

### Language Version

4.3.5

**Comment by pahud** [comment] 2021-11-08 04:08
Are you trying to reference stack across regions in the same cdk app?

<img width="940" alt="圖片" src="https://user-images.githubusercontent.com/278432/140682864-c9b3e879-be48-4adc-8bec-94fbf5f42603.png">

**Comment by vespertilian** [comment] 2021-11-08 04:52
Yes, 

> deployed as part of the same app to different regions.

This is why the first attempt did not work. 
This is why in my second attempt I create the secret from the secret name. Which almost works. 

```
  // 2nd attempt create the secret in the region from the secret name
    const secretInRegion = secretsmanager.Secret.fromSecretNameV2(this, 'secret', props.secret.secretName)
```

Again the second attempt does not work with the primary region, only the seconday regions. 

It would be nice if there was a method to get the secret regardless of if it is the primary or a replicated secret, and then be able to use it, as you would any other secret, in the context of the deployed region.

```
   const secret = secretsmanager.Secret.regionSpecificSecret(this, primarySecret) // get the region from `this` context
   secret.grantRead(myLambda)
```

This should be possible as replicated secrets have the same ARN just with a different region, and again it almost works with my second method.

**Comment by kimisme9386** [comment] 2021-11-08 05:02
AWS Secrets Manager has supported to replicate secrets on multiple Regions. See below:

Blog
https://aws.amazon.com/tw/blogs/security/how-to-replicate-secrets-aws-secrets-manager-multiple-regions/

CDK document
https://docs.aws.amazon.com/cdk/api/latest/docs/aws-secretsmanager-readme.html#replicating-secrets

@vespertilian

**Comment by pahud** [comment] 2021-11-08 05:11
> Again the second attempt does not work with the primary region, only the seconday regions.
> 
> It would be nice if there was a method to get the secret regardless of if it is the primary or a replicated secret, and then be able to use it, as you would any other secret, in the context of the deployed region.
> 
> ```
>    const secret = secretsmanager.Secret.regionSpecificSecret(this, primarySecret) // get the region from `this` context
>    secret.grantRead(myLambda)
> ```
> 
> This should be possible as replicated secrets have the same ARN just with a different region, and again it almost works with my second method.

This is interesting. I can reproduce it from my end even just print the `secretArn`.

<img width="1120" alt="圖片" src="https://user-images.githubusercontent.com/278432/140687519-d4617ebb-871c-4937-b461-5530b74bf5a0.png">

Looking into it now.

**Comment by pahud** [comment] 2021-11-08 05:19
According to this, `fromSecretNameV2().secretArn` actually returns `this.partialArn`, and will not be able to return `secretFullArn`: 

https://github.com/aws/aws-cdk/blob/ea40cfe1b85ce4aee9c8f871de08d3c3739589d1/packages/%40aws-cdk/aws-secretsmanager/lib/secret.ts#L382-L404

I wrote a tiny CDK sample app:

```ts
import { App, CfnOutput, Construct, Stack, StackProps } from '@aws-cdk/core';
import * as secrets from '@aws-cdk/aws-secretsmanager'

/**
 * This stack creates the secrets in Primary region
 */
export class SecretStack extends Stack {
  readonly secretName: string;
  readonly secret: secrets.ISecret;
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    this.secretName = 'AuthToken'

    this.secret = new secrets.Secret(this, 'MySecret', {
      secretName: this.secretName,
    })

    new CfnOutput(this, 'SecretArnOutput', { value: this.secret.secretArn })
    // define resources here...
  }
}

/**
 * The App stack. 
 */
export interface AppStackProps extends StackProps {
  readonly secretName: string;
}

export class AppStack extends Stack {
  constructor(scope: Construct, id: string, props: AppStackProps) {
    super(scope, id, props);

    const importedSecret = secrets.Secret.fromSecretNameV2(this, 'ImportedSecret', props.secretName)

    new CfnOutput(this, 'importedSecretArnOutput', { value: importedSecret.secretArn })
  }
}

const secretEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: 'ap-northeast-1'
};

const appJPEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: 'ap-northeast-1',
};

const appUSEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: 'us-east-1',
};

const app = new App();

const secretStack = new SecretStack(app, 'my-secret-stack', {env: secretEnv } )

// create the app stack in JP
new AppStack(app, 'my-app-stack-jp', { 
  env: appJPEnv,
  secretName: secretStack.secretName,
});

// create the app stack in US
new AppStack(app, 'my-app-stack-us', { 
  env: appUSEnv,
  secretName: secretStack.secretName,
});

app.synth();
```

<img width="1201" alt="圖片" src="https://user-images.githubusercontent.com/278432/140688162-92331880-7615-4a4e-9f17-7977b36985cc.png">

**Comment by pahud** [comment] 2021-11-08 05:59
OK I think I figured it out.

To make the `secret.grantRead()` work, first it must have the full secretArn including the random suffix. The random suffix will only be known when the secretStack is provisioned and only can be referenced by other stacks in the same account & region. 

`Secret.fromSecretNameV2()` can only construct partial ARN. The random suffix will not be included hence partial ARN only.

`Secret.fromSecretCompleteArn()` can construct ISecret with full arn but only in stacks from the same account & region.

**Comment by vespertilian** [comment] 2021-11-08 09:10
@kimisme9386 thanks, I am already replicating the secrets, that part works fine **it's using the replicated secrets** that's the issue, I assumed you would have some standard way to use them once you create them :) .  Do you have some sample code for using the replicated secrets? Say allowing a lambda to read them?

@pahud 

First, up your app needs to create some replicated regions.
Then the secret does exist, because that's what the replication does, and the ARNs are the same except for the region. 

This is what it looks like when deployed.

![secrets-manager](https://user-images.githubusercontent.com/441418/140697882-86f4a7af-0959-4967-a131-99727f954bd4.png)

```ts
import { App, CfnOutput, Construct, Stack, StackProps } from '@aws-cdk/core';
import * as secrets from '@aws-cdk/aws-secretsmanager'

/**
 * This stack creates the secrets in Primary region
 */
export class SecretStack extends Stack {
  readonly secretName: string;
  readonly secret: secrets.ISecret;
  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    this.secretName = 'AuthToken'
    this.secret = new secrets.Secret(this, 'MySecret', {
      secretName: this.secretName,
      replicatedRegions: [{region: 'us-east-1'}] // <<<<< create replicated region
    })

    new CfnOutput(this, 'SecretArnOutput', { value: this.secret.secretArn })
    // define resources here...
  }
}

/**
 * The App stack. 
 */
export interface AppStackProps extends StackProps {
  readonly secretName: string;
}

export class AppStack extends Stack {
  constructor(scope: Construct, id: string, props: AppStackProps) {
    super(scope, id, props);

    const importedSecret = secrets.Secret.fromSecretNameV2(this, 'ImportedSecret', props.secretName)

    new CfnOutput(this, 'importedSecretArnOutput', { value: importedSecret.secretArn })
  }
}

const secretEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: 'ap-northeast-1'
};

const appJPEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: 'ap-northeast-1',
};

const appUSEnv = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: 'us-east-1',
};

const app = new App();

const secretStack = new SecretStack(app, 'my-secret-stack', {env: secretEnv } )

// create the app stack in JP
new AppStack(app, 'my-app-stack-jp', { 
  env: appJPEnv,
  secretName: secretStack.secretName,
});

// create the app stack in US
new AppStack(app, 'my-app-stack-us', { 
  env: appUSEnv,
  secretName: secretStack.secretName,
});

app.synth();
```



> To make the `secret.grantRead()` work, first it must have the full secretArn including the random suffix

This totally works without the full secretArn, otherwise what is the point of `Secret.fromSecretNameV2`?
You can test out a policy like the one below. 

policy generated in the replicated regions deployed api (works)

```ts
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret"
            ],
            "Resource": "arn:aws:secretsmanager:us-east-1:477532313330:secret:AuthToken-??????",
            "Effect": "Allow"
        }
    ]
}
```

The issue I had is the Secret.fromSecretNameV2 appends both the random suffix **and** the ??????. 
policy generated in the primary deployed api (does not work)

```ts
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret"
      ],
      "Resource": "arn:aws:secretsmanager:us-east-1:477532313330:secret:AuthToken-1aoeve-??????",
      "Effect": "Allow"
    }
  ]
}
```

### moving forwards

We have all the info needed after you create the secret to create a region-specific ARN as we just have to swap the region and we have the region from the deployed stack context, we just need a function to do this. 

I have been trying this and I tested teh formatting function which seems to do what I want but I was getting an error when I try to deploy.

```
    const primaryArnSecretParts = Arn.split(props.secret.secretName, ArnFormat.COLON_RESOURCE_NAME)
    const regionSpecificArn = Arn.format({
      ...primaryArnSecretParts,
      region: this.region,
      account: this.account
    }, this)

    const secretInRegion = secretsmanager.Secret.fromSecretCompleteArn(this, 'secret', regionSpecificArn)
    const nameOnly = new lambda.Function(this, 'NameOnly', {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'name-only.handler',
      code: lambda.Code.fromAsset('name-only'),
      layers: [apiLayer],
      environment: {
        TABLE_NAME: props.tableName,
        AUTH_TOKEN_SECRET_KEY_ARN: secretInRegion.secretArn
      }
    })
    secretInRegion.grantRead(nameOnly)
```

**Comment by pahud** [comment] 2021-11-08 11:45
In this case I personally prefer save the secret full arn to the parameter store and let other stacks from other regions read from the parameter store with custom resource you mentioned in option 1 or use [pahud/cdk-remote-stack](https://github.com/pahud/cdk-remote-stack).

I had a sample for this scenario here https://github.com/pahud/cross-regional-secrets/blob/main/src/main.ts

**Comment by vespertilian** [comment] 2021-11-08 12:36
@pahud Yeah, ok that looks super helpful. I'm on other things this week but I will try to get to it this weekend. Thanks!

**Comment by pahud** [comment] 2021-11-08 12:38
Hi @vespertilian 

Let me clarify it:

1.  You have SecretStack in `us-east-1` and ApiStack in `us-east-1` and `ap-southeast-2`
2.  Secret was created in `us-east-1` and replicated to `ap-southeast-2` and their ARNs look like this

```
arn:aws:secretsmanager:us-east-1:XXXXXXXXXXXX:secret:AuthToken-tlyQdp
arn:aws:secretsmanager:ap-southeast-2:XXXXXXXXXXXX:secret:AuthToken-tlyQdp
```

3. You need grant the read privileges to the lambda principal role in 
4. And you noticed that the policy generated for the replicated region(ap-southeast-2) is correct but not in `us-east-1`

Is it correct? I can try write a little sample to for this scenario and see how it works from my end.

@neilkuan @kimisme9386 any interest to join with me?

**Comment by vespertilian** [comment] 2021-11-08 12:54
@pahud 

Yes that is correct. I am using the

**Comment by vespertilian** [comment] 2021-11-08 13:05
Yes. 

This works in the replicated region, but not in the primary region. 

```ts
const secretInRegion = secretsmanager.Secret.fromSecretNameV2(this, 'secret', props.secret.secretName)
secret.grantRead(lambda) // works replicated ap-southeast-2
```

`fromSecretName` returns an invalid arn for the primary region `arn:aws:secretsmanager:us-east-1:477532313330:secret:AuthToken-1aoeve-??????` it has both 1aoeve and ????? but it should just have one or the other. 

So it's not consistent for all regions, also it suffers from the fact it uses the partial ARN, as that is what fromSecretNameV2 returns.

I could probably get what I had to work by just checking if I am in the primary region, and using the standard secret in that region, and fromSecretName in the others. The SSM store and specific ARNs for all regions feel like it might be better.

**Comment by kimisme9386** [comment] 2021-11-09 02:43
@vespertilian I try to reproduce your scenario. The whole sample code is [here](https://github.com/kimisme9386/cross-regional-secrets). I use `ap-northeast-1` for primary region and `us-east-1` for replicated region.  The snippet code is [here](https://github.com/kimisme9386/cross-regional-secrets/blob/main/src/main.ts#L18-L21)

Next, I write a simple lambda to get secret manager for testing permission.  The both of primary region and replicated region use the same method to get secret. like below:

```ts
const secretInRegion = secrets.Secret.fromSecretNameV2(this, `secret${region}`, secret.secretName);
secretInRegion.grantRead(lambdaFunc);
```
snippet code is [here](https://github.com/kimisme9386/cross-regional-secrets/blob/main/src/main.ts#L105-L106)

After deploying it, the lambda permission looks like the screenshot

primary  region (`ap-northeast-1`)

![secret-arn-ap-northeast-1](https://user-images.githubusercontent.com/7465652/140850561-f2cb53c2-d47b-4f90-8784-cc0f67c17d98.jpg)

replicated  region (`us-east-1`)

![secret-arn-us-east-1](https://user-images.githubusercontent.com/7465652/140850759-385bc2b5-7cd9-4264-970e-7e4c6176f92a.jpg)

Both of them get the same suffix granted resource `-??????` . According  @pahud  explain it in below https://github.com/aws/aws-cdk/issues/17382#issuecomment-962822084, I think it make sense.

Finally, the result of lambda execution work fine.

primary  region (`ap-northeast-1`)

![lambda-ap-northeast-1-primary](https://user-images.githubusercontent.com/7465652/140851361-165541d2-c332-45f5-b28a-033455387113.jpg)

replicated  region (`us-east-1`)

![lambda-us-east-1-relica](https://user-images.githubusercontent.com/7465652/140851372-e1f1a209-0418-4f0e-81d7-6eb9368434ca.jpg)

According my lab, the granted resource is partial arn. it contains six `?` mark which `?` mark in arn is wildcard character.  The document is [here](https://docs.aws.amazon.com/quicksight/latest/APIReference/qs-arn-format.html). So I think it make sense and work fine.

But I don't know why your primary region doesn't work. Maybe reference my repository to check it. If the question still occur, I hope you can offer more sample code. thanks.

**Comment by vespertilian** [comment] 2021-11-09 12:19
@kimisme9386 Yes yours works, but mine still fails. Weird. I will look into it more this weekend.

**Comment by vespertilian** [comment] 2021-11-14 10:37
Ok, so I found the issue, it took me a while, I was missing a feature flag that was turned on in your CDK example, as I am building this in nrwl nx project not in a CDK init app. 

@pahud @kimisme9386  https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html << this talks about how you can use a partial ARN but they **recommend the complete ARN**. 

So should I just use the  `.fromSecretName` solution or should I try to use @pahud cross region reference solution? 

Thank you for all your help! 

Feature flag below. Hopefully this thread is useful for others.

```ts
/**
 * Secret.secretName for an "owned" secret will attempt to parse the secretName from the ARN,
 * rather than the default full resource name, which includes the SecretsManager suffix.
 *
 * If this flag is not set, Secret.secretName will include the SecretsManager suffix, which cannot be directly
 * used by SecretsManager.DescribeSecret, and must be parsed by the user first (e.g., Fn:Join, Fn:Select, Fn:Split).
 */
export const SECRETS_MANAGER_PARSE_OWNED_SECRET_NAME = '@aws-cdk/aws-secretsmanager:parseOwnedSecretName';
```

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/cx-api/lib/features.ts

**Comment by kimisme9386** [comment] 2021-11-14 15:00
@vespertilian 

Thank you for your feedback. I try to set false for `@aws-cdk/aws-secretsmanager:parseOwnedSecretName` in the cdk.json. I got the result below:

![IAM_Management_Console](https://user-images.githubusercontent.com/7465652/141685291-02d20e0b-f17c-4822-aa6c-ab40edc612f4.jpg)

The resource name contains full arn and it has unnecessary `-??????` suffix.

So you found the root cause. I'm good to know as I learned the feature of `@aws-cdk/aws-secretsmanager:parseOwnedSecretName`.

In my opinion, Both  `fromSecretNameV2` or  @pahud [cdk-remote-stack](https://awscdk.io/packages/cdk-remote-stack@0.1.136/#/) work fine.  

The code very simply for using `fromSecretNameV2` because it can use like `secretInRegion.grantRead(lambdaFunc)`.
When use [cdk-remote-stack](https://awscdk.io/packages/cdk-remote-stack@0.1.136/#/), it need to combine policy yourself that like `lambdaFunc.role?.addManagedPolicy`.

@pahud any suggestion ?

**Comment by pahud** [comment] 2021-11-15 00:59
Looks like we should simply enable `@aws-cdk/aws-secretsmanager:parseOwnedSecretName` as `true` because it's the default value when we `cdk init`. And just use the partial ARN in the policy.  I don't see any reason we have to use `cdk-remote-stack` to get the full ARN from remote. Thoughts?

**Comment by pahud** [comment] 2021-12-01 02:05
Looks like we can close this issue now. Good to dive deep this with you. Thanks!!

**Closed** 2021-12-01 02:40 UTC
Labels: closing-soon, guidance, @aws-cdk/aws-secretsmanager
