### ISSUE TITLE
@aws-cdk/aws-backup: BackupPlan - support AdvancedBackupSettings

### ISSUE THREAD

**Issue by MauriceBrg** [aws/aws-cdk#15246] opened 2021-06-22 09:49 UTC
The AdvancedBackupSettings of the underlying CloudFormation resource are currently not available in the BackupPlan construct.
These are required in order  to turn on VSS-support for Windows Backups.

### Use Case

Backups of Windows instances benefit from VSS support.

### Proposed Solution

Currently this seems to be the only advanced setting, maybe a toggle to turn it on/off?

I'm currently using this workaround to enable it:

```typescript
const defaultPlan = new BackupPlan(
      this,
      "backup-plan", {
      backupPlanName: "my-name",
      backupVault: defaultVault,
})

const cfnDefaultRetentionBackupPlan = defaultPlan.node.defaultChild as CfnBackupPlan

cfnDefaultRetentionBackupPlan.addOverride(
    "Properties.BackupPlan.AdvancedBackupSettings",
    [{"ResourceType": "EC2", "BackupOptions": {"WindowsVSS": "enabled"}}]
)
```

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by BenChaimberg** [comment] 2021-06-22 20:59
duplicate of #14803

**Closed by BenChaimberg** 2021-06-22 20:59 UTC
Labels: @aws-cdk/aws-backup, feature-request, needs-triage
