### ISSUE TITLE
Command '['python3', '/var/task/aws', 's3', 'sync', '--delete', '/tmp/tmpfn1apb9u/contents', 's3://app-sales-appbucket8349d24e-zfpzz0t4gbik/', "--cache-control 'max-age=28800, proxy-revalidate'", '--metadata-directive', 'REPLACE']' returned non-zero exit status 255.

### ISSUE THREAD

**Issue by pocesar** [aws/aws-cdk#5269] opened 2019-12-02 06:01 UTC
Tried to do a BucketDeployment using Cloudfront, took almost 15 minutes and failed... now rolling back! 😞 

### Reproduction Steps

```ts
  new BucketDeployment(stack, 'app-deployment', {
    destinationBucket: bucket,
    sources: [ Source.asset(join(__dirname, 'build')) ],
    distribution: cloudfront,
    cacheControl: [
      CacheControl.maxAge(cdk.Duration.hours(8)),
      CacheControl.proxyRevalidate()
    ]
  })
```

### Error Log

```
Command '['python3', '/var/task/aws', 's3', 'sync', '--delete', '/tmp/tmpfn1apb9u/contents', 's3://app-sales-appbucket8349d24e-zfpzz0t4gbik/', "--cache-control 'max-age=28800, proxy-revalidate'", '--metadata-directive', 'REPLACE']' returned non-zero exit status 255.
Traceback (most recent call last):
  File "/var/task/index.py", line 101, in handler
    s3_deploy(s3_source_zips, s3_dest, user_metadata, system_metadata)
  File "/var/task/index.py", line 134, in s3_deploy
    aws_command("s3", "sync", "--delete", contents_dir, s3_dest, *create_metadata_args(user_metadata, system_metadata))
  File "/var/task/index.py", line 176, in aws_command
    subprocess.check_call(["python3", aws] + list(args))
  File "/var/lang/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3', '/var/task/aws', 's3', 'sync', '--delete', '/tmp/tmpfn1apb9u/contents', 's3://app-sales-appbucket8349d24e-zfpzz0t4gbik/', "--cache-control 'max-age=28800, proxy-revalidate'", '--metadata-directive', 'REPLACE']' returned non-zero exit status 255.
```

### Environment

  - **CLI Version      : 1.18.0 (build bc924bc)**
  - **Framework Version: 1.18.0**
  - **OS               : Windows 10**
  - **Language         : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by jatsrt** [comment] 2020-01-02 03:40
Still an issue in 1.19.0.  Any update on a workaround or if this is being addressed?

**Comment by jatsrt** [comment] 2020-01-02 14:40
So, this is the same issue as:
https://github.com/aws/aws-cdk/issues/4665
https://github.com/aws/aws-cdk/pull/4697

The PR is closed, though it was never merged and fixed.  It is just a problem around the cache control meta data being passed to the Lambda `aws s3 sync` command.

Removing cache-control will deploy, but less than optimal if you need caching.

**Comment by eladb** [comment] 2020-01-05 10:53
Closing as duplicate of #4665

**Closed by eladb** 2020-01-05 10:53 UTC
Labels: bug, p1, package/cloudfront, status/needs-triage

**Comment by AllanOricil** [comment] 2024-04-27 06:21
Could you please reopen it. I just had this issue.

**Comment by AllanOricil** [comment] 2024-04-27 08:21
The worst part is that this error takes more than 20 min for the ROLLBACK to finish. It is insane!
