### ISSUE TITLE
[cli] errors/warnings in nested assemblies are not respected

### ISSUE THREAD

**Issue by jessecollier** [aws/aws-cdk#9799] opened 2020-08-18 15:50 UTC
I'm using the new `pipelines` module to deploy a stack in another account.
In order to validate my code changes, I've implemented various `addWarning` and `addError` annotations.

However, when I run `cdk synth --strict` everything is synthesized without warnings, errors or exiting non-zero.

### Reproduction Steps

```typescript
export class VpcStack extends cdk.Stack {
    public readonly vpc: ec2.IVpc;

    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);
        Annotations.of(this).addWarning('This warning will not');
        this.vpc = new ec2.Vpc(this, 'Network');
    }
}

export class AppStage extends cdk.Stage {
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);
      Annotations.of(this).addWarning('This warning will appear');
      const vpc = new VpcStack(this, 'VpcStack');
    }
  }

export class CdkPipelineStack extends cdk.Stack {
    public readonly pipeline: pipelines.CdkPipeline;
  
    constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);

      const sourceArtifact        = new codepipeline.Artifact();
      const cloudAssemblyArtifact = new codepipeline.Artifact();
  
      this.pipeline = new pipelines.CdkPipeline(this, 'CDKPipelines', {
        pipelineName: 'CDKPlatform',
        cloudAssemblyArtifact,
        sourceAction: new codepipeline_actions.GitHubSourceAction({
            actionName: 'Github',
            output: sourceArtifact,
            oauthToken: cdk.SecretValue.secretsManager('example_github_token'),
            trigger: codepipeline_actions.GitHubTrigger.POLL,
            owner: 'org', // Case sensitive
            repo: 'repo',
            branch: 'typescript'
          }),
        synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
          sourceArtifact,
          cloudAssemblyArtifact,
          buildCommand: 'npm run build'
        })
      });
  
      this.pipeline.addApplicationStage(
        new AppStage(this, 'myApp', {
          env: {
            account: '1234567890',
            region: 'us-east-1'
          }
        })
      )
    }
}
```

### What did you expect to happen?

```
$ cdk synth --strict
[Warning at /CDKPlatform/myApp] This warning will appear
[Warning at /CDKPlatform/myApp/VpcStack] This warning will not
Found warnings (--strict mode)
```

### What actually happened?

```
$ cdk synth --strict
[Warning at /CDKPlatform/myApp] This warning will appear
Found warnings (--strict mode)
```

### Environment

  - **CLI Version      :** aws cli 1.18.97
  - **Framework Version:** 1.59.0
  - **Node.js Version:** v12.18.2
  - **OS               :** OSX 10.15.5
  - **Language (Version):** TypeScript (3.9.7)

### Other

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-08-24 09:35
Duplicate of #8676

**Closed by rix0rrr** 2020-08-24 09:35 UTC
Labels: @aws-cdk/core, bug, needs-triage, package/tools
