### ISSUE TITLE
UNKNOWN error when trying to use NodejsFunction

### ISSUE THREAD

**Issue by NightWatchman** [aws/aws-cdk#7683] opened 2020-04-29 18:01 UTC
Every time I try to use `new NodejsFunction` I get a spawnSync error that seems to be related to aws-lambda-nodejs not being able to succesfully execute the parcel command, but I can't figure out exactly why. Running the parcel command manually works fine.

### Reproduction steps

Run the cdk deploy command

### Error Log

Error: Failed to build file at C:\Developer\My.Project\stacks\api\requests\put-ad\put-ad-states\base64-decode-lambda\index.ts: Error: spawnSync C:\Developer\My.Project\node_modules\parcel-bundler\bin\cli.js UNKNOWN

at Builder.build (C:\Developer\My.Project\node_modules\@aws-cdk\aws-lambda-nodejs\lib\builder.ts:107:17)
    at new NodejsFunction (C:\Developer\My.Project\node_modules\@aws-cdk\aws-lambda-nodejs\lib\function.ts:98:13)
    at R.pipe.aws_stepfunctions_1.Task.task (C:\Developer\My.Project\stacks\api\requests\put-ad\put-ad-states\state-machine.ts:24:12)
    at C:\Developer\My.Project\node_modules\ramda\src\internal\_pipe.js:3:27
    at C:\Developer\My.Project\node_modules\ramda\src\internal\_pipe.js:3:27
    at C:\Developer\My.Project\node_modules\ramda\src\internal\_arity.js:11:19
    at Object.exports.submitAdStateMachine (C:\Developer\My.Project\stacks\api\requests\put-ad\put-ad-states\state-machine.ts:103:21)
    at new DigiknowApp (C:\Developer\My.Project\bin\app.ts:43:48)
    at Object.<anonymous> (C:\Developer\My.Project\bin\app.ts:61:1)

### Environment

  - **CLI Version:** aws-cli/1.16.307 Python/3.6.0 Windows/10 botocore/1.13.43
  - **Framework Version:**  1.36.0
  - **OS:**  Windows 10
  - **Language:** en-us

### Other

Running the command `.\node_modules\.bin\parcel build C:\Developer\My.Project\stacks\api\requests\put-ad\put-ad-states\base64-decode-lambda\index.ts --out-dir .build --out-file index.js --global handler --target node --bundle-node-modules --log-level 2 --no-minify` manually builds the file with no issues

--- 

This is :bug: Bug Report

**Comment by jogold** [comment] 2020-04-29 20:54
Seems from the stack trace that the error comes from [ramda](https://github.com/ramda/ramda)? Do you still see the error when removing this dependency? Can you share a reproductible example?

**Comment by NightWatchman** [comment] 2020-05-04 18:18
I'll look into it more and see if I can come up with a minimal project that reproduces it.

**Comment by eladb** [comment] 2020-05-07 07:30
Closing for now

**Closed by eladb** 2020-05-07 07:30 UTC
Labels: @aws-cdk/aws-lambda-nodejs, bug, needs-triage

**Comment by d2kx** [comment] 2020-05-08 13:05
Same problem here, with all release up to 1.38.0

![image](https://user-images.githubusercontent.com/4834966/81408312-4f701700-913d-11ea-82f0-da724c52d738.png)

Only on Windows 10, works with with WSL2.

**Comment by jogold** [comment] 2020-05-08 13:21
You need docker with v1.38.0.

**Comment by d2kx** [comment] 2020-05-08 13:46
Thank you. That also does not work

![image](https://user-images.githubusercontent.com/4834966/81411402-9ca2b780-9142-11ea-85d8-434c88d51b05.png)

Docker is asking for an absolute path but getting a relative one it looks like, but I'll try to look into it and file another new issue later.

Not sure I'll want to have Docker installed just for this library, so I'll likely switch back to the regular @aws-cdk/aws-lambda library and build the function myself in the future.

**Comment by jogold** [comment] 2020-05-22 18:11
The problem on Windows should be fixed with #8140.
