### ISSUE TITLE
CloudFrontWebDistribution external import method missing

### ISSUE THREAD

**Issue by nbaillie** [aws/aws-cdk#3606] opened 2019-08-09 18:25 UTC
CloudFrontWebDistribution currently does not have an external import method like S3 and Repository.

my thought is that it should support something like:
`cloudfront.CloudFrontWebDistribution.from_distribution_arn(self,<ID>,<ARN>)`

**Comment by nmussy** [comment] 2019-08-10 10:34
I'm going to make a PR for it 👍

**Comment by oleksandr-yefremov** [comment] 2020-02-11 17:09
Is there any other way to import `CloudFrontWebDistribution` currently? I am missing this API

**Comment by iliapolo** [comment] 2020-04-13 21:15
duplicate of https://github.com/aws/aws-cdk/issues/5607

**Closed by iliapolo** 2020-04-13 21:15 UTC
Labels: effort/small, feature-request, in-progress, package/cloudfront
