### ISSUE TITLE
[EC2] Consider providing CIDR in ISubnet

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#9891] opened 2020-08-21 14:00 UTC
### Use Case

Since few months, I use a workaround with a CustomResource to get Subnets CIDR because iSubnet doesn't provide a CidrBlock : 
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.ISubnet.html

It's an AWS CustomResource to make a simple **describeSubnets** when getting the prop **subnetId** from iSubnet.

### Proposed Solution

Like #2211 , can you provide a simple way to get those CIDRs ?

Often needed when creating some resources like SGR when you want to allow specific, like Private Subnets for example.

### Other

Today, when updating (CDK 1.60.0) a backend Stack with multiple RDS (to finally add `rds: CloudWatch logs exports for DB clusters (#9772) (118e5c6), closes #7810`), my CustomResource has been updated (? Probably due to `custom-resources: optional latest SDK installation for AwsCustomResource (#9515) (effdd3c), closes #9289 #9322`) and I've got an error : **Response object is too long.**

Actually I don't have solve the pb because of the timeout of CFN (1h) on a failed CustomResource...

Maybe you have a simplyest way to get those CIDRs for each Subnets ?

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2020-08-24 11:42
Duplicate of #3951, duplicate of #2211, keep in mind for #5927.

**Closed by rix0rrr** 2020-08-24 11:42 UTC
Labels: @aws-cdk/aws-ec2, feature-request, needs-triage
