### ISSUE TITLE
(aws-cdk/lib/api/garbage-collection): (Garbage collection for ECR prints incorrect number of assets/images deleted and runs indefinitely)

### ISSUE THREAD

**Issue by tainsworth102** [aws/aws-cdk#32498] opened 2024-12-12 12:36 UTC
### Describe the bug

When running cdk gc for ECR, the number of assets is misprinted and the files scanned exceeds the number in the bootstrap repository. This results in the percentage of files scanned exceeding 100.00% and therefore command runs indefinitely. Additionally, images are not being tagged in any attempted run, it is jumping straight to deleting the a random number of unused images which is not reflected in the print statement.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The printed output should have stated:
[100.00%] 136 files scanned: 3 assets (0.56 GiB) tagged, 0 assets (0.00 GiB) deleted.

### Current Behavior
[735.29%] 1000 files scanned: 0 assets (0.00 GiB) tagged, 30 assets (5.63 GiB) deleted.
![image](https://github.com/user-attachments/assets/c9669e66-8aef-4f29-8d4d-fd9ae19deb94)

The printed output was incorrect and rather than tagging it began deleting straight away.

### Reproduction Steps

cdk gc aws://`<my-account-id>`/`<my-only-used-region>` --type ecr --unstable=gc --created-buffer-days 0 --action full --confirm=true

### Additional Information/Context

When running this for an account which has an ECR repo with ~8000 images the progression printing is again displayed incorrectly. As the progression cycled and increased with the loop, the number progression progression prints for each progression iteration double and the number of images deleted cumulatively decreases until it deletes no images for each iteration.

### CDK CLI Version

2.172.0

### Node.js Version

v20.11.1

### OS

Ubuntu 22.04.4 LTS

### Language

Python

**Comment by khushail** [comment] 2024-12-13 23:36
Hi @tainsworth102 , thanks for reaching out.

I tried to reproduce the issue. Although I did not have those many images, i tried with a small set.Here is a snippet (since I had only 2 images, it asked for deletion and then deleted)-

<img width="801" alt="Screenshot 2024-12-13 at 2 37 49 PM" src="https://github.com/user-attachments/assets/6ab04994-4377-47c3-8edd-0b000bac2aa0" />

**Comment by khushail** [comment] 2024-12-20 20:08
@tainsworth102 , I tried deleting images in other region and got this -
```
⏳  Garbage Collecting environment aws://<<ACCOUNT-ID>>/us-west-2...
Found 1 assets to delete based off of the following criteria:
- assets have been isolated for > 0 days
- assets were created > 0 days ago

Delete this batch (yes/no/delete-all)? yes
[100.00%] 1 files scanned: 0 assets (0.00 MiB) tagged, 1 assets (103.23 MiB) deleted.
```

Seems like there is an issue with tagging ,  which are deleted. However I am not sure of whether in situation where many 1000 images exist, how the percentage would be displayed.

I am marking this issue as P2 which means it would be on team's radar , won't be immediately addressed by the team. However contributions reg the resolution, are welcome from the community as well team. 

Hope that is helpful.

**Comment by sakurai-ryo** [comment] 2024-12-28 08:28
I was able to reproduce the bug, and I'll open a PR to fix it.

**Closed** 2024-12-29 20:12 UTC
Labels: bug, p1, package/tools, effort/small
