### ISSUE TITLE
(cli): An automation API to support CDK wrapper tooling

### ISSUE THREAD

**Issue by stevehodgkiss** [aws/aws-cdk#16163] opened 2021-08-22 12:16 UTC
CDK CLI contains all the necessary logic to synthesise and deploy CDK apps. It can also be used as a library to build CDK CLI wrappers, but this isn't a supported/first class concern. This request is about making that a supported feature.

Pulumi has an [Automation API](https://www.pulumi.com/docs/guides/automation-api/) with a similar feature and has a good description of the use cases involved.

I wasn't able to find an open related feature request in a quick search, so apologies if this is a duplicate.

### Use Case

Companies often have opinionated sensible defaults and wrap those up with internal tooling. We have done this, but it relies on unsupported exported functions that could break our tooling in any release.

If all the deployment functionality in aws-cli was exposed as a supported code API, wrapper tools with similar functionality to AWS copilot could be built using AWS CDK in a supported way.

Example from our internal tooling running a deployment:

<img width="1287" alt="Screen Shot 2021-08-22 at 3 44 56 pm" src="https://user-images.githubusercontent.com/62331/130354060-997cae47-3ae8-401f-abbc-7ece5f7601cb.png">

### Proposed Solution

Build and expose an Automation API with synth & deployment functionality to enable usage by third party CDK/CLI wrappers.

There are 2 aspects to this:

- A supported way to trigger `cdk synth` and interrogate the CloudAssembly output for custom metadata. Our internal CLI tooling uses metadata added to stacks to "know" about the various deployable services defined in the CDK App (it reads from the `CloudAssembly` / `StackCollection` objects).
- A supported way to trigger `cdk deploy|destroy|diff` from code, using the already synthesised `cdk.out` output. It's important to be able to trigger change set creation and execution separately (i.e. `--no-execute`), to allow for building custom review workflows into external tools. Although if change set review gets added to cdk deploy this is less important.

We currently wrap "CDK CLI" using this wrapper class, and an internal plugin that provides change set reviews to `cdk deploy`: https://gist.github.com/stevehodgkiss/b12899f0a668954c0eea817166e3b78f

For context, the CDK App side of our tooling looks like this, and adds metadata for the CLI to know about the various services/tasks defined in the CDK App.

```typescript
const app = new cdk.App();

class MyApp extends ShuttleApplication { // a cdk.Stage
  static applicationName = 'myapp'

  constructor(scope: cdk.Construct, id: string, props: MyAppProps) {
    super(scope, id, props);

    this.addDeployRole({
      deployers: [
        EnvatoArns.aDeployArn,
      ],
    });

    // metadata is added with each service definition so the CLI knows about what's defined in the CDK App and is deployable
    this.addWebService('web', {
      command: ['bundle', 'exec', 'rails', 'server'],
      environment: {},
      taskDefinition: {
        memoryLimitMiB: 512,
        cpu: 256
      }
    });

    this.addBackendService('sidekiq', {
      command: ['bundle', 'exec', 'sidekiq']
      environment: {}
    });
  }
}

new MyApp(app, 'development', {
  env: { region: 'eu-west-2', account: '...' },
  network: {
    vpc: {
      natGateways: 1,
      cidr: '10.0.0.0/21'
    }
  },
  application: {
    hostedZoneDomainName: '...',
    parentHostedZoneName: '...'
  },
});
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2021-08-24 08:25
For some reason the issue has been moved to the RFCs repository.

Duplicate of https://github.com/aws/aws-cdk-rfcs/issues/300

**Closed by rix0rrr** 2021-08-24 08:25 UTC
Labels: feature-request, package/tools, needs-triage
