### ISSUE TITLE
aws-elasticloadbalancingv2: cannot create lambda TargetGroup

### ISSUE THREAD

**Issue by pradeepviswanathan** [aws/aws-cdk#17261] opened 2021-11-01 16:09 UTC
### What is the problem?

Cannot create  lambda TargetGroup as the created cfn template has `stickiness.enabled` set as true in TargetGroupAttributes. Seems like this attribute is not expected for lambda based target groups.

### Reproduction Steps

const lambdaTargetGroup = new ApplicationTargetGroup(this, `TargetGroup`, {
       targets: [new targets.LambdaTarget(lambdaFunction)],
    });

You should be able to see `stickiness.enabled` set in cfn template. During deployment , deployment fails with 

`The provided target group attribute is not supported (Service: AmazonElasticLoadBalancing; Status Code: 400`

### What did you expect to happen?

Target group with lambda targets getting created successfully

### What actually happened?

Target group with lambda targets are not getting created

### CDK CLI Version

1.130

### Node.js Version

17.0.1

### OS

macos 11.3.1

### Language

Typescript

**Comment by topecongiro** [comment] 2021-11-02 02:49
For reproduction, run `mkdir cdk-issue && cd cdk-issue && cdk init app --language typescript`, apply the following patch and run `npm i && cdk deploy`:

```patch
diff --git a/bin/cdk-issue.ts b/bin/cdk-issue.ts
index eb0c70e..fa0d52c 100644
--- a/bin/cdk-issue.ts
+++ b/bin/cdk-issue.ts
@@ -11,7 +11,7 @@ new CdkIssueStack(app, 'CdkIssueStack', {
 
   /* Uncomment the next line to specialize this stack for the AWS Account
    * and Region that are implied by the current CLI configuration. */
-  // env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },
+  env: { account: process.env.CDK_DEFAULT_ACCOUNT, region: process.env.CDK_DEFAULT_REGION },
 
   /* Uncomment the next line if you know exactly what Account and Region you
    * want to deploy the stack to. */
diff --git a/lib/cdk-issue-stack.lambda.ts b/lib/cdk-issue-stack.lambda.ts
new file mode 100644
index 0000000..46a7acb
--- /dev/null
+++ b/lib/cdk-issue-stack.lambda.ts
@@ -0,0 +1,5 @@
+export async function handler(
+    event: any,
+): Promise<any> {
+    return {};
+}
\ No newline at end of file
diff --git a/lib/cdk-issue-stack.ts b/lib/cdk-issue-stack.ts
index aa6e79e..864ac2e 100644
--- a/lib/cdk-issue-stack.ts
+++ b/lib/cdk-issue-stack.ts
@@ -1,9 +1,24 @@
 import * as cdk from '@aws-cdk/core';
+import * as ec2 from '@aws-cdk/aws-ec2';
+import * as lb from '@aws-cdk/aws-elasticloadbalancingv2';
+import * as targets from '@aws-cdk/aws-elasticloadbalancingv2-targets';
+import * as lambda from '@aws-cdk/aws-lambda-nodejs';
 
 export class CdkIssueStack extends cdk.Stack {
   constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
     super(scope, id, props);
 
-    // The code that defines your stack goes here
+    const alb = new lb.ApplicationLoadBalancer(this, 'lb', {
+      vpc: ec2.Vpc.fromLookup(this, 'vpc', { isDefault: true }),
+    });
+    const listener = alb.addListener('Listener', {
+      port: 80
+    });
+    listener.addTargets('Target', {
+      port: 80,
+      targets: [
+        new targets.LambdaTarget(new lambda.NodejsFunction(this, 'lambda')),
+      ],
+    });
   }
 }
diff --git a/package.json b/package.json
index 236f05f..cc6e0e4 100644
--- a/package.json
+++ b/package.json
@@ -14,13 +14,18 @@
     "@aws-cdk/assert": "1.130.0",
     "@types/jest": "^26.0.10",
     "@types/node": "10.17.27",
+    "aws-cdk": "1.130.0",
     "jest": "^26.4.2",
     "ts-jest": "^26.2.0",
-    "aws-cdk": "1.130.0",
     "ts-node": "^9.0.0",
     "typescript": "~3.9.7"
   },
   "dependencies": {
+    "@aws-cdk/aws-ec2": "^1.130.0",
+    "@aws-cdk/aws-elasticloadbalancingv2": "^1.130.0",
+    "@aws-cdk/aws-elasticloadbalancingv2-targets": "^1.130.0",
+    "@aws-cdk/aws-lambda-nodejs": "^1.130.0",
     "@aws-cdk/core": "1.130.0",
     "source-map-support": "^0.5.16"
   }
```

**Comment by PascalPflaum** [comment] 2021-11-02 09:16
I can confirm this issue. Had to pin "1.129.0" to keep CDK avoiding this bug. The issue seems to be related with #17111.

**Comment by spg** [comment] 2021-11-02 18:16
Temporary workaround:
```typescript
    const defaultTargetGroupFunc = new lambda.Function(this, 'DefaultTargetGroupFunc', {
      runtime: lambda.Runtime.NODEJS_12_X,
      handler: 'index.handler',
      code: lambda.Code.fromInline(
        'exports.handler = async function (event, context) {console.log(JSON.stringify(event));}'
      ),
      logRetention: logs.RetentionDays.ONE_WEEK,
    })
    const defaultFuncPermission = new lambda.CfnPermission(this, 'perm', {
      action: 'lambda:InvokeFunction',
      functionName: defaultTargetGroupFunc.functionName,
      principal: 'elasticloadbalancing.amazonaws.com',
    })

    const lambdaTarget = new elbv2Targets.LambdaTarget(defaultTargetGroupFunc)
    const defaultTargetGroup = new alb.ApplicationTargetGroup(this, 'DefaultTargetGroup', {
      targetType: alb.TargetType.LAMBDA,
      targets: [lambdaTarget],
    })
    const cfnDefaultTargetGroup = defaultTargetGroup.node.defaultChild as alb.CfnTargetGroup
    cfnDefaultTargetGroup.addDependsOn(defaultFuncPermission)

    // TODO: remove this once https://github.com/aws/aws-cdk/issues/17261 is fixed
    cfnDefaultTargetGroup.addDeletionOverride('Properties.TargetGroupAttributes')
```

**Comment by peterwoodworth** [comment] 2021-11-03 00:28
Thanks all for clearly describing the issue and providing a workaround, much appreciated 😄 I can confirm the behavior described here

**Comment by gov-sanap** [comment] 2021-11-08 10:08
Facing similar issue in python. Can anyone provide temporary fix for python also? That will be really appreciated. Thank you

**Comment by gov-sanap** [comment] 2021-11-08 11:14
Got it after trying few things. Following is snippet of what I did.

`elbv2.CfnTargetGroup.add_deletion_override(tg1.node.default_child, 'Properties.TargetGroupAttributes')`

In the above code tg1 is object of elbv2.ApplicationTargetGroup. 
Add tg1 to listener using listener.add_target_groups or using any other way.

**Comment by gburke-ppb** [comment] 2021-11-11 12:19
Any idea when this issue will be fixed?  There have been 2 releases of the CDK since it was introduced and it's still present...

**Comment by adriantaut** [comment] 2021-11-17 10:16
Also affected by this 😨

**Comment by VladimirGrenaderov** [comment] 2021-11-23 17:13
Much simple workaround - 'listener.addTargets(...).setAttribute('stickiness.enabled', undefined)'

**Comment by David-Tamrazov** [comment] 2021-11-23 21:27
> Much simple workaround - 'listener.addTargets(...).setAttribute('stickiness.enabled', undefined)'

imo this is great cause its an easy half-a-line fix and outlines exactly which properties are problematic with a direct fix 👍

**Comment by PascalPflaum** [comment] 2021-11-25 09:24
#17271 seems to be ready to be merged and included in next release. Any update on this?

**Closed** 2021-11-29 16:02 UTC
Labels: bug, p1, effort/small, @aws-cdk/aws-elasticloadbalancingv2

**Comment by stewberticus** [comment] 2021-12-06 21:24
A target group with HTTPS protocol does not support the attribute stickiness.enabled

adding the exact error text so this thread is more easily searched from google
