### ISSUE TITLE
(cli): CLI not compatible with the CDK library even though they are in the same version

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#14845] opened 2021-05-24 08:02 UTC
I am receiving the error `CLI is not compatible with the CDK library` even though `cdk --version` returns the same version as the library.

### Reproduction Steps

The CDK CLI 1.102.0 was installed on my machine, and I upgraded it to 1.105.0 using `npm install -g aws-cdk`. Then, I created  a new CDK app. 

When I executed `cdk synth` the following error was printed:

```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 10.0.0, but found 11.0.0)
```

Running `cdk --version` returned:

```
1.105.0
```

### What did you expect to happen?

I expected `cdk synth` to print the synthesized cloudformation template.

### What actually happened?

I received the above error.

### Environment

  - **CDK CLI Version  :** 1.105.0
  - **Framework Version:** 1.105.0
  - **Node.js Version:**  v14.15.4 (npm 7.13.0)
  - **OS               :** Mac
  - **Language (Version):** all

### Other

I looked at the globally installed CLI, and it seems like `@aws-cdk/cloud-assembly-schema` was not upgraded to the newer version, which explains this error, but I am not sure how this could happen since the CLI's `package.json` has a pinned requirement on the cloud-assembly-schema.

Could this be an npm bug?

### Workaround

Uninstall and install CDK CLI:

```shell
npm uninstall -g aws-cdk && npm install -g aws-cdk
```

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2021-05-24 09:02
Duplicate of https://github.com/aws/aws-cdk/issues/14738

**Closed by nija-at** 2021-05-24 09:02 UTC
Labels: bug, needs-triage, package/tools
