### ISSUE TITLE
Add familyName to LoadBalancedFargateService

### ISSUE THREAD

**Issue by stephenh** [aws/aws-cdk#3980] opened 2019-09-06 21:51 UTC
### General Information

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

### Description

I'm using physical names for my ECS cluster/service/etc. to make wiring things up across aws-cdk + CI/etc. (yeah, yeah, I'm not yet using aws-cdk for the CI pipeline :-).

I'd like to have the task definition family name be non-random, which I _believe_ can be done via the existing `CommonTaskDefinitionProps.family` property, but it's not exposed in the `LoadBalancedFargateService` props.

(I'm not really sure why the `CommonTaskDefinitionProps` prop is not `familyName`, so maybe I'm wrong on that being the right/existing approach.)

**Comment by pkandasamy91** [comment] 2019-10-08 15:27
Duplicate of https://github.com/aws/aws-cdk/issues/4414

**Closed by pkandasamy91** 2019-10-08 15:27 UTC
Labels: feature-request, package/ecs-patterns

**Comment by stephenh** [comment] 2019-10-08 15:42
...damn it, I can't believe I filed my own dup. :-/ I swear I looked for open issues. Thanks!
