### ISSUE TITLE
[lambda] lambda.Code.FromAsset Golang bundling permission denied at execution

### ISSUE THREAD

**Issue by strongishllama** [aws/aws-cdk#10776] opened 2020-10-07 23:48 UTC
### The Question
I've been trying to deploy a Lambda function written in Go using lambda.Code.fromAsset and the experimental BundlingOptions inside the AssetOptions parameter. I'm able to deploy the stack with no issues at all but I get a permission denied error on the Lambda when trying to execute it.
```json
{
  "errorMessage": "fork/exec /var/task/hello-world: permission denied",
  "errorType": "PathError"
}
```
When I download the zipped source from S3 to look at the binaries permissions it should be able to execute it.
```
total 13808
drwxrwxrwx 1 strongishllama strongishllama     512 Oct  8 10:31 ./
drwxrwxrwx 1 strongishllama strongishllama     512 Oct  8 10:23 ../
-rwxrwxrwx 1 strongishllama strongishllama 9291301 Oct  8 10:23 hello-world*
```
Here's the Lambda function snippet from CDK.
```ts
    const handler = new lambda.Function(this, `HelloWorld-${props.suffix}`, {
      runtime: lambda.Runtime.GO_1_X,
      code: lambda.Code.fromAsset("assets/lambdas/hello-world", {
        bundling: {
          image: lambda.Runtime.GO_1_X.bundlingDockerImage,
          command: [
            "bash", "-c", [
              "go build -o /asset-output/hello-world*.go",
              "chmod +x /asset-output/hello-world"
            ].join(" && ")
          ],
          user: "root"
        }
      }),
      handler: "hello-world"
    });
```
I've also tried building and zipping locally then uploading it manually to the existing Lambda function and it works as expected.

Any help would be appreciated. Thanks!

### Environment

  - **CDK CLI Version:** 1.67.0 (build 2b4dd71)
  - **Module Version:** 1.67.0
  - **Node.js Version:** v14.10.1
  - **OS:** Windows 10 Home
  - **Language (Version):** TypeScript (4.0.3)

**Comment by strongishllama** [comment] 2020-10-08 20:32
I just tried this on my Ubuntu machine and it works fine, the environment is as follows.

  - **CDK CLI Version:** 1.67.0 (build 2b4dd71)
  - **Module Version:** 1.67.0
  - **Node.js Version:** v10.19.0
  - **OS:** Ubuntu 20.04.1 LTS
  - **Language (Version):** TypeScript (3.9.7)

**Comment by NGL321** [comment] 2020-10-30 18:05
Hi @strongishllama!

Unfortunately I __WAS__ able to reproduce this on Windows and had no issues on OSX, so I think this is likely a bug with the way asset bundling works on Windows. I have changed the labels so that it gets the attention of the relevant dev.

Are you able to run your builds on Ubuntu as mentioned above while this is pending? If not, the best other workaround would be to create a small secondary pipeline stack in CodePipeline to run the deployment from a Codebuild unix environment.

Let me know if that workaround works for you!

😸 😷

**Comment by strongishllama** [comment] 2020-10-30 19:11
My primary development device is Ubuntu so all good. Thanks!

**Comment by pfried** [comment] 2020-11-02 10:39
Related https://github.com/aws/aws-cdk/issues/7749

The issue ( most likely only on windows) is that files which are bundled will loose their permissions (like beeing executable). As long as seen from inside the container the permissions are correctly set within the `asset-output` directory.

Inside the container:
![image](https://user-images.githubusercontent.com/1744875/97858047-de31ab00-1cfe-11eb-9287-4d0cd75dae3e.png)

After running the cdk bundling the permissions are gone:

Outside the container:
![image](https://user-images.githubusercontent.com/1744875/97858153-06210e80-1cff-11eb-840e-08e2ca43b5a3.png)

It seems to me that the files are actually "recreated" somehow since the seem to have a default mask applied to them. The permissions issue is already present on the output folder, hence it has nothing to do with the zip file creation.

As docker volumes are tricky I suspect an issue with using volumes or the `fs` operations.

**Comment by pfried** [comment] 2020-11-04 14:57
Something I noticed: The permissions in Windows are different from the ones seen from inside the docker container. (Most likely due to filesystem differences), propably the permissions simply get lost when moving the file from the container to windows. One idea could be to require the user to zip inside the docker container (thats what I now do manually as a workaround)

**Comment by pfried** [comment] 2020-12-09 07:30
@eladb Since you are assigned to this, would it be possible to add an option like `outputFile` where it would skip the [archiving](https://github.com/aws/aws-cdk/blob/d9cba8d16f0c60018ce7e9718479680910ae169c/packages/cdk-assets/lib/private/archive.ts#L33) and just use the given output file if it exists?

I guess this packaging will never work properly on windows since it will loose the permissions set inside the container. I would suggest a config property which points to a single file in the output directory making it the users responsibility to provide the zip file.

Besides that there should be a warning at https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-assets-readme.html#asset-bundling that bundling on windows might fail (if the file needs e.g. executable permissions).

**Comment by eladb** [comment] 2020-12-09 07:33
@pfried sounds like a good direction. @jogold what do you think?

**Comment by jogold** [comment] 2020-12-10 08:56
> @pfried sounds like a good direction. @jogold what do you think?

You still don't want to do this automagically if the content in `/asset-output` is a single archive file?

**Comment by pfried** [comment] 2020-12-10 09:10
Would also be a good idea, I wonder if there should be an example in the docs how to create a zip archive

**Comment by pfried** [comment] 2021-02-03 09:25
I would like to get back to this, I would be fine with both approaches

**Comment by eladb** [comment] 2021-02-15 08:46
@jogold I am okay with doing this automatically if `/asset-output` includes a single `.zip` file, but let's add an option to disable this behavior (in case for some odd reason users want to create a bundle that contains a single zip file *inside the bundle*).

**Comment by jogold** [comment] 2021-02-16 12:29
> @jogold I am okay with doing this automatically if `/asset-output` includes a single `.zip` file, but let's add an option to disable this behavior (in case for some odd reason users want to create a bundle that contains a single zip file _inside the bundle_).

@eladb started the work in #13076, how would you call this option? `alwaysArchive` which defaults to `false`?

**Comment by eladb** [comment] 2021-02-16 12:39
> @eladb started the work in #13076, how would you call this option? `alwaysArchive` which defaults to `false`?

I'd probably go with an enum with three options:

1. Always zip
2. Never zip (fail if the output directory does not contain a single zip file)
3. Auto

 It sure about the names...

**Closed** 2021-02-17 19:20 UTC
Labels: @aws-cdk/assets, bug, effort/small, os/windows, p1
