### ISSUE TITLE
CDK CLI errors when run as a non-existent user

### ISSUE THREAD

**Issue by jonathanmorley** [aws/aws-cdk#7937] opened 2020-05-12 18:57 UTC
A regression in 1.37 means that the CDK CLI will error out if it is run by a user not in /etc/passwd

### Reproduction Steps

```sh
npx cdk init app --language=typescript
npm install
docker run -u 502:502 -v $(pwd):/app -w /app node ./node_modules/.bin/cdk list
```

### Error Log

```
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:268:11)
    at cdkHomeDir (/app/node_modules/aws-cdk/lib/util/directories.ts:7:21)
    at Object.cdkCacheDir (/app/node_modules/aws-cdk/lib/util/directories.ts:11:20)
    at new AccountAccessKeyCache (/app/node_modules/aws-cdk/lib/api/aws-auth/account-cache.ts:25:44)
    at Object.<anonymous> (/app/node_modules/aws-cdk/lib/api/aws-auth/sdk.ts:38:42)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
```

### Environment

  - **CLI Version      :** >= 1.37
  - **Framework Version:**
  - **OS               :** Tested in Docker on MacOS
  - **Language         :** Typescript

--- 

This is :bug: Bug Report

**Comment by jonathanmorley** [comment] 2020-05-12 18:59
The error goes away if you mount an /etc/passwd containing a user with UID 502

```
❯ docker run -it -u 502:502 -v $(pwd)/etc_passwd:/etc/passwd -v $(pwd):/app -w /app node ./node_modules/.bin/cdk list
CdkTempStack
```

**Comment by shivlaks** [comment] 2020-05-12 19:36
I think this is because of the fix we introduced in #7674 which addressed the issue of a bug where `CDK_HOME` not being consistently honored.

Otherwise since this is an opportunistic cache, we also simply shouldn't fail if we can't create the dir. can you run your cdk command with `-v` to get to the point of failure? 

I can't quite tell if this is expected or another bug just yet.

**Comment by jonathanmorley** [comment] 2020-05-14 19:09
Running `./node_modules/.bin/cdk list -v` returns the same stacktrace as above

```
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:268:11)
    at cdkHomeDir (/app/node_modules/aws-cdk/lib/util/directories.ts:7:21)
    at Object.cdkCacheDir (/app/node_modules/aws-cdk/lib/util/directories.ts:11:20)
    at new AccountAccessKeyCache (/app/node_modules/aws-cdk/lib/api/aws-auth/account-cache.ts:25:44)
    at Object.<anonymous> (/app/node_modules/aws-cdk/lib/api/aws-auth/sdk.ts:38:42)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
```

**Comment by shivlaks** [comment] 2020-05-14 20:30
@jonathanmorley - gotcha, haven't had a chance to take a deeper look but will get to it this week. 

What's the expected behaviour when used with a non-existent user? I'll run through the repro steps as a starting point. Although it's a regression from previous versions, I want to dig into whether the previous behavior had the limitations of not honoring `CDK_HOME`

**Comment by jonathanmorley** [comment] 2020-05-15 15:12
expected behaviour is that it would be successful. We have not been setting `CDK_HOME` (or relying on any files in a 'HOME' directory)

**Comment by mitchlloyd** [comment] 2020-05-29 19:44
Just running into this error in a Jenkins build while upgrading from CDK 1.18 -> 1.42.

**Comment by mb-dev** [comment] 2021-09-25 03:28
duplicate of #15415 ?

I am running into the same issue in jenkins / docker.

**Comment by dennispost** [comment] 2022-02-17 08:08
Any news on this? Hit this error with CDK v2.12.0.

@mitchlloyd to which path did you set `CDK_HOME`?

**Comment by adambro** [comment] 2022-03-18 14:21
As reported in #19401 it's just small function that needs change. By looking at code of `safeUsername()` function it's just used  as part of `RoleSessionName` name. It could have a nice fallback to i.e. `$USER` env var or just predefined default value. The function is very simple:
```js
function safeUsername() {
    return os.userInfo().username.replace(/[^\w+=,.@-]/g, '@');
}
```

**Comment by zhukovsd** [comment] 2022-04-26 20:20
I had this problem while running CDK with Jenkins/Docker.

Jenkins runs the pipeline script inside of a Docker agent container with user id 1024. This user, by default, has no name, which causes the problem.

As a workaround, I created a user for id 1024:
```
echo "jenkins:x:1024:1024:default:/:/bin/bash" >> /etc/passwd
```

**Closed** 2022-07-07 19:30 UTC
Labels: bug, p1, package/tools, effort/small
