### ISSUE TITLE
StringParameter.from_string_parameter_attributes returns 'Resource' instead of 'IStringParameter'

### ISSUE THREAD

**Issue by Marty-Me** [aws/aws-cdk#4982] opened 2019-11-12 15:46 UTC
After the 1.16.0 release of this morning the synthesizing of our infrastructure started failing.
It seems like the `StringParameter.from_string_parameter_attributes` method provides the wrong return type (it states `IStringParameter` but the actual type is `Resource`.

### Reproduction Steps

```python

from aws_cdk import core
from aws_cdk.aws_ssm import StringParameter
from aws_cdk.core import Stack

APP = core.App()

STACK_WITH_ISSUE = Stack(APP, 'StackWithIssue')
FAILING_SSM_PARAMETER = StringParameter.from_string_parameter_attributes(STACK_WITH_ISSUE, 'FailingSSMParameter',
                                                                         parameter_name='param-name')

print(FAILING_SSM_PARAMETER)
print(FAILING_SSM_PARAMETER.string_value)

APP.synth()

```

### Error Log

```
<aws_cdk.core.Resource object at 0x1103cf9d0>
Traceback (most recent call last):
  File "infrastructure/IssueStack.py", line 12, in <module>
    print(FAILING_SSM_PARAMETER.string_value)
AttributeError: 'Resource' object has no attribute 'string_value'
```

### Environment

  - **CLI Version      : ** 1.16.2 (build 5893301)
  - **Framework Version: ** 1.16.2
  - **OS               :** macOS Catalina version 10.15 (19A583)
  - **Language         :** Python

--- 

This is :bug: Bug Report

**Comment by Marty-Me** [comment] 2019-11-12 15:55
A temporary fix is calling `_physical_name` on `FAILING_SSM_PARAMETER` as this does return the correct value.

**Comment by skinny85** [comment] 2019-11-12 19:44
Could this be a different manifestation of this: #4966 ?

**Comment by RomainMuller** [comment] 2019-11-12 19:53
Definitely is.

**Comment by eladb** [comment] 2019-11-12 19:53
Sounds like Jsii. Reassigning to @RomainMuller

**Comment by eladb** [comment] 2019-11-12 20:06
Closing as duplicate of https://github.com/aws/aws-cdk/issues/4966

**Closed by eladb** 2019-11-12 20:06 UTC
Labels: bug, language/python, p0, package/ssm, status/needs-triage
