### ISSUE TITLE
ImportError: cannot import name '_Union' from 'typing' 

### ISSUE THREAD

**Issue by superdba111** [aws/aws-cdk#11102] opened 2020-10-25 22:45 UTC
please see the following errors, it looks python 3.9 with cdk version issue
```console
~/aws/DevOps/hello/hello-cdk master* .env ❯ cdk ls
Traceback (most recent call last):
  File "/Users/yli/aws/DevOps/hello/hello-cdk/app.py", line 3, in <module>
    from aws_cdk import core
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/aws_cdk/core/__init__.py", line 904, in <module>
    import jsii
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/jsii/__init__.py", line 4, in <module>
    from ._runtime import (
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/jsii/_runtime.py", line 10, in <module>
    from ._kernel import Kernel
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 15, in <module>
    from .providers import BaseProvider, ProcessProvider
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/jsii/_kernel/providers/__init__.py", line 2, in <module>
    from .process import ProcessProvider
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 15, in <module>
    import cattr  # type: ignore
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/Users/yli/aws/DevOps/hello/hello-cdk/.env/lib/python3.9/site-packages/cattr/_compat.py", line 87, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py)
Subprocess exited with error 1
~/aws/DevOps/hello/hello-cdk master* .env ❯ 
```

**Comment by superdba111** [comment] 2020-10-25 22:48
google it, the issue happened @python3.8 before, and now 3.9; why did the same issue happen again?

**Comment by SomayaB** [comment] 2020-10-26 20:37
Duplicate of #11043

**Closed by SomayaB** 2020-10-26 20:37 UTC
Labels: bug, needs-triage

**Comment by superdba111** [comment] 2020-10-27 04:52
when will you fix the issue?
