### ISSUE TITLE
(@aws-cdk/aws-pipeline): CDKPipelines permissions issue to deploy Infrastructure

### ISSUE THREAD

**Issue by sahilpalvia** [aws/aws-cdk#14334] opened 2021-04-22 18:34 UTC
## :question: General Issue

We are trying to deploy infrastructure using CDKPipeline. We keep on running into the issue where the `UpdatePipeline` stage fails due to insufficient permissions. The exception that we see is

```
 ❌  Stack failed: AccessDenied: User: arn:aws:sts::ACCOUNT:assumed-role/ROLE is not authorized to perform: cloudformation:GetTemplate on resource: arn:aws:cloudformation:REGION:ACCOUNT:stack/ROLE
```

We believe this is due to the way we are taking dependencies on stacks.

```js
class SomeStack extends Stack {
    public readonly someresource;
    ...
}

class SomeOtherStack extends Stack {
    public constructor() {
        ...
        somestack.someresource
        ...
    }
}
```

When deploying SomeOtherStack normally, SomeStack is first deployed and then SomeOtherStack. This is our pipeline definition

```js
const sourceArtifact = new Artifact();
const cloudAssemblyArtifact = new Artifact();
new CdkPipeline(this, 'CDKPipeline', {
    pipelineName: 'PIPELINE',
    cloudAssemblyArtifact: cloudAssemblyArtifact,
    sourceAction: new CodeCommitSourceAction({
        ...
    }),
    synthAction: SimpleSynthAction.standardNpmSynth({
        environment: {
            buildImage: LinuxBuildImage.STANDARD_5_0
        },
        sourceArtifact: sourceArtifact,
        cloudAssemblyArtifact: cloudAssemblyArtifact,
        installCommand: 'npm install',
        buildCommand: 'npm run build',
        rolePolicyStatements: [new PolicyStatement({
            resources: [
                ...
            ],
            actions: [
                ...
            ],
        })]
    }),
    selfMutating: true,
});
```

We tried to look into providing more permissions to the `UpdatePipeline` stage, but could find a way to do so.

### The Question

Is this something that is supported or has a way around? Also is CDKPipeline the correct construct just for deploying infrastructure and not code?

### Environment

  - **CDK CLI Version:** 1.99.0
  - **Module Version:** 
  - **Node.js Version:** 
  - **OS:** CodeBuild Linux
  - **Language (Version):** TypeScript

**Comment by NGL321** [comment] 2021-05-20 22:42
Hey @sahilpalvia,

I have tried to reproduce this, but have been unable to (I was working with the given information, but since it was unclear how you are actually structuring the deployment I made the assumption that you were passing the `sharedresource` between the stacks via override props and deploying the stacks through independent stages). 

Sharing resources across stacks should have no impact on the pipeline used to deploy those stacks. Additionally, the only possible reason I can think of for encountering permissions issues is your block of explicit policy-statement declaration. My first recommendation is to try broadening the scope of those statements and seeing if that resolves your permissions issue, otherwise I think it is fair to say this bug is likely unrelated to the pipeline itself and has to do with your account configuration.

Sorry I cant offer more at this time, I hope this at least points you in the right direction.


😸 😷

**Comment by sahilpalvia** [comment] 2021-05-20 23:12
Hi @NGL321 

Could you share how you made things work for you? We tried doing * permissions on explicit policy-statement but it still didn't work.

**Comment by NGL321** [comment] 2021-05-21 17:14
Hey @sahilpalvia,

This is the pipeline stack I used for repro:
```ts
export class PipepermsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const src = new Repository(this, 'SrcRepo', {
      repositoryName: 'PipePermsRepo'
    });

    const sourceArtifact = new Artifact();
    const cloudAssemblyArtifact = new Artifact();

    const pipeline = new CdkPipeline(this, 'Pipeline', {
      cloudAssemblyArtifact,
      sourceAction: new CodeCommitSourceAction({
        actionName: 'CodeCommitSource',
        repository: src,
        output: sourceArtifact
      }),
      synthAction: SimpleSynthAction.standardNpmSynth({
        environment: {
          buildImage: LinuxBuildImage.STANDARD_5_0
        },
        sourceArtifact,
        cloudAssemblyArtifact,
        installCommand: 'npm install',
        buildCommand: 'npm run build',
        rolePolicyStatements: [new PolicyStatement({
          resources: [
            '*'
          ],
          actions: [
            '*'
          ]
        })]
      }),
      selfMutating: true
    });

    const firstStage = new PipelineFirstStage(this, 'Stage1');
    const secondStage = new PipelineSecondStage(this, 'Stage2', {
      sharedResource: firstStage.sharedResource
    });
    pipeline.addApplicationStage(firstStage);
    pipeline.addApplicationStage(secondStage);
  }
}
```

The stacks and stages are themselves pretty empty.

😸 😷

**Comment by sahilpalvia** [comment] 2021-05-21 17:41
@NGL321 Thanks for sharing this. Just had a follow up question, did you have this setup in the same account? Did you try the pipeline across accounts?

**Comment by NGL321** [comment] 2021-05-21 18:35
@sahilpalvia,

Based on our conversation I am going to share the same guidance here for posterity and then close the issue. If the guidance ends up being incorrect, please feel free to reopen this issue (however, after repro I have been unable to reproduce so it may require a little more info).

Essentially the missing component that could cause an AccessDenied role error across is a trusted role in each account that allows data transfer. The CDK can automate this role creation while bootstrapping using the `--trust` flag (as shown in the [CDKPipelines docs](https://docs.aws.amazon.com/cdk/api/latest/docs/pipelines-readme.html#cdk-environment-bootstrapping)).

Here is an example:
```
$ env CDK_NEW_BOOTSTRAP=1 npx cdk bootstrap \
    --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
    --trust 11111111111 \
    aws://222222222222/us-east-2
```

I hope this is enough to help resolve!


😸 😷

**Closed by NGL321** 2021-05-21 18:35 UTC
Labels: closing-soon, guidance
