### ISSUE TITLE
aws-ecs: LogDriver automatically creates log-resource-policies, exhausting unmodifiable resource limit

### ISSUE THREAD

**Issue by trks1970** [aws/aws-cdk#22307] opened 2022-09-30 12:01 UTC
### Describe the bug

We are running 12 Fargate containers, each of them logging to CloudWatch via LogDriver, creare with cdk.

However, the last 2 fails to deploy, due to
` "Resource limit exceeded. (Service: CloudWatchLogs, Status Code: 400,`

which I understand is fixed at 10 and that is it. No way to change.

However, it looks like log-resource-policy is created automaticall by LogDriver, which uses up the amount.

### Expected Behavior

It is not possible a) not to create a policy or b) reuse a policy

### Current Behavior

A log-resource-policy is created with each LogDriver.awsLogs call.

### Reproduction Steps

Deploy 10 Containers with LogDriver

### CDK CLI Version

2.40.0 (build 56ba2ab)

### Framework Version

aws-cdk-lib:2.27.0

### Node.js Version

16.15.1

### OS

Win10

### Language

Java

### Language Version

Kotlin

**Comment by trks1970** [comment] 2022-11-27 13:17
Will take some time to provide an example.

**Comment by mvs5465** [comment] 2023-02-08 21:09
Hi @pahud we are running into this too with some CDK-created CloudWatch log group policies:

Example 1, sending cloudtrail events to eventbridge and logging the events:
```
const loginEvent = aws_cloudtrail.Trail.onEvent(this, 'login-event', {
  eventPattern: {
    source: ['aws.signin'],
    detailType: ['AWS Console Sign In via CloudTrail'],
  },
});

loginEvent.addTarget(new targets.CloudWatchLogGroup(new logs.LogGroup(this, 'login-event-logs')));
```

Example 2, creating an OpenSearch domain:
```
new aws_opensearchservice.Domain(this, 'domain', {
  // Specifically enabling logging here
  logging: {
    slowSearchLogEnabled: true
          appLogEnabled: true,
    slowIndexLogEnabled: true,
  },
});
```

**Comment by pahud** [comment] 2023-02-09 20:17
@mvs5465 

Are you having the Resource limit exceeded error just with this? Can you provide a full sample that reproduces this error?

```ts
const loginEvent = aws_cloudtrail.Trail.onEvent(this, 'login-event', {
  eventPattern: {
    source: ['aws.signin'],
    detailType: ['AWS Console Sign In via CloudTrail'],
  },
});

loginEvent.addTarget(new targets.CloudWatchLogGroup(new logs.LogGroup(this, 'login-event-logs')));
```

**Comment by mvs5465** [comment] 2023-02-09 20:22
@pahud We already have 10 cloudwatch log group policies in our account. Running the code you mentioned will create one more, and thus the error.

**Comment by pahud** [comment] 2023-02-09 20:40
OK I see.

Looking at this https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/aws-ecs/lib/log-drivers/aws-log-driver.ts#L119

When we new AwsLogDriver() for a container definition, there will always be a grantWrite() execution, adding a new log group policy to this log group resource.

https://github.com/aws/aws-cdk/blob/be97e4e5006990c7340025618b03f5d5eacda253/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L194 

I don't have immediate workaround and I am making it p1 here for more visibility. Meanwhile I will try reproduce this in my account by creating 10 containers with the same log group.

**Comment by pahud** [comment] 2023-02-09 22:48
>We already have 10 cloudwatch log group policies in our account. Running the code you mentioned will create one more, and thus the error.

@mvs5465 Can you help me clarify this? Sounds like you have an IAM role with 10 IAM policies attached already and the statement below is going to create an additional iam policy for the existing role and this hits the limit. Is it correct?

```ts
loginEvent.addTarget(new targets.CloudWatchLogGroup(new logs.LogGroup(this, 'login-event-logs')));
```

To help me reproduce your use case, can you provide a full code that I can run and produce the error in my account?

**Comment by pahud** [comment] 2023-02-09 22:49
@trks1970 

I was trying to create 10 containers with 2 approaches below and I didn't hit the error you mentioned.

```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';

export class EcsTsStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const logGroup = new cdk.aws_logs.LogGroup(this, 'LG')
    const task = new cdk.aws_ecs.FargateTaskDefinition(this, 'Task', {
      cpu: 512,
      memoryLimitMiB: 4096,
    });

    const task2 = new cdk.aws_ecs.FargateTaskDefinition(this, 'Task2', {
      cpu: 512,
      memoryLimitMiB: 4096,
    });

    // this works
    for (let x = 0; x < 10; x++) {
      task.addContainer(`nginx${x}`, {
        image: cdk.aws_ecs.ContainerImage.fromRegistry('nginx:latest'),
        memoryLimitMiB: 256,
        logging: new cdk.aws_ecs.AwsLogDriver({
          logGroup,
          streamPrefix: 'demo-',
        })
      });
    };

    // this works as well
    for (let x = 0; x < 10; x++) {
      task2.addContainer(`nginx${x}`, {
        image: cdk.aws_ecs.ContainerImage.fromRegistry('nginx:latest'),
        memoryLimitMiB: 256,
        logging: new cdk.aws_ecs.AwsLogDriver({
          logGroup: new cdk.aws_logs.LogGroup(this, `LG${x}`),
          streamPrefix: 'demo-',
        })
      });
    };

  }
}

```


Can you provide me with the full cdk code that reproduces your error?

**Comment by pahud** [comment] 2023-02-09 23:12
OK I can reproduce this as below:

```ts
    // create 10 events each having a loggroup as the event target
    for (let x = 0; x < 10; x++) {
      const loginEvent = cdk.aws_cloudtrail.Trail.onEvent(this, `login-event${x}`, {
        eventPattern: {
          source: ['aws.signin'],
          detailType: ['AWS Console Sign In via CloudTrail'],
        },
      });
      
      loginEvent.addTarget(new cdk.aws_events_targets.CloudWatchLogGroup(
        new cdk.aws_logs.LogGroup(this, `login-event-logs${x}`),
      ));
    }
```

This will create 10 cloudwatch logs resource policies and according to the [doc](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) the hard limit is 10 thus causes error.

The resources can be listed with `aws logs describe-resource-policies`.

**Comment by vinayak-kukreja** [comment] 2023-05-16 13:49
Similar Issue: https://github.com/aws/aws-cdk/issues/20313

**Comment by marinecode** [comment] 2023-11-01 10:52
I have come up with a possible workaround. 
When I moved LogGroup creation to the separate stack, ResourcePolicy was not created. 
In the TaskDefinition stack, I referenced created LogGroup by arn via `LogGroup.from_log_group_arn()`.

**Comment by mramirez-fdb** [comment] 2023-12-13 18:27
Any Update on this?

**Comment by XiaowenMaoA** [comment] 2023-12-26 22:45
@sakurai-ryo just seeing pull request on this. when do we expect this change to available?  any local workaround we can have? Thanks

**Comment by sakurai-ryo** [comment] 2023-12-27 01:40
@XiaowenMaoA 
The CDK core team is currently on vacation, so the review will be done after the vacation.
Please check the other issues for workarounds.
https://github.com/aws/aws-cdk/issues/20313#issuecomment-1861126356

If this doesn't work, please send me the code and I may be able to suggest a workaround.

**Comment by XiaowenMaoA** [comment] 2023-12-27 05:06
@sakurai-ryo  we are not inside ECS task. create OS domain logic is like following.
we have TenantNames over 10. 

```
import { Domain, EncryptionAtRestOptions, EngineVersion } from 'aws-cdk-lib/aws-opensearchservice';

export class OpenSearchClusterStack extends DeploymentStack {
  public kmsKey: KmsKey;
  public cloudwatchPolicy: PolicyStatement;

  constructor(parent: App, name: string, props: OpenSearchClusterStackProps) {
    super(parent, name, {
      env: props.env,
      softwareType: SoftwareType.LONG_RUNNING_SERVICE,
      stackName: props.stackName,
      tags: props.tags,
    });

    vpc = Utils.getVpc(this, this.region);

    const securityGroup = this.createSecurityGroup(vpc, props);

    this.kmsKey = this.createKmsKey(vpc, props);

    this.cloudwatchPolicy = new PolicyStatement({
      actions: ['logs:CreateLogStream', 'logs:PutLogEvents'],
      resources: [
        '*',
      ],
      effect: Effect.ALLOW,
      principals: [new ServicePrincipal('es.amazonaws.com')],
    });

  // create OS domain for each TenantName 
    Object.values(TenantNames).forEach((tenantNameStr) => {
      const tenantName = tenantNameStr as TenantNames;
      const clusterConfig = props.stage.clusterConfigByTenant[tenantName];
      const globaltenantConfig = TENANT_CONFIG[tenantName];
      const domainName = Utils.generateName(globaltenantConfig.clusterName, props.isOnebox)
        .toLowerCase();

      const domainAppLogGroupName = `${Utils.generateName(`${Constants.Resource.PREFIX}-OSDomain-AppLogGroup`, props.isOnebox)}-${domainName}`;
      const domainAppLogGroup = new LogGroup(this, domainAppLogGroupName, {
        logGroupName: domainAppLogGroupName,
        retention: RetentionDays.TEN_YEARS,
        removalPolicy: RemovalPolicy.RETAIN_ON_UPDATE_OR_DELETE,
      });

      const domain = this.createDomain(
        domainName,
        { enabled: true, kmsKey: this.kmsKey.key },
        domainAppLogGroup,
        vpc,
        securityGroup,
        props,
        clusterConfig,
      );
      domain.addAccessPolicies(this.cloudwatchPolicy);
    });
  }

  private createDomain(
    domainName: string,
    encryptionProperties: EncryptionAtRestOptions,
    appLogGroup: LogGroup,
    vpc: IVpc,
    securityGroup:SecurityGroup,
    props: OpenSearchClusterStackProps,
    clusterConfig: ClusterConfig,
  ) {

    return new Domain(this, domainName, {
      domainName,
      version: EngineVersion.OPENSEARCH_1_1,
      vpc,
      zoneAwareness: {
        enabled: true,
        availabilityZoneCount: vpc.privateSubnets.length,
      },
      capacity: {
        masterNodes:  clusterConfig.masterNodeCount,
        masterNodeInstanceType: clusterConfig.masterNodeType,
        dataNodes: clusterConfig.instanceCount,
        dataNodeInstanceType: clusterConfig.instanceType,
      },
      ebs: {
        volumeSize: clusterConfig.instanceVolumeSize,
        volumeType: clusterConfig.ebsVolumeType,
        iops: 18000,
      },
      securityGroups: [securityGroup],
      nodeToNodeEncryption: true,
      encryptionAtRest: encryptionProperties,
      enforceHttps: true,
      logging: {
        appLogEnabled: true,
        appLogGroup,
      },
      removalPolicy: RemovalPolicy.RETAIN_ON_UPDATE_OR_DELETE,
    });
  }
  ```

**Comment by sakurai-ryo** [comment] 2023-12-27 06:41
Thanks @XiaowenMaoA 

Looking at this part of the code, it appears that we are currently using CustomResource to create the ResourcePolicy for the logs.
https://github.com/aws/aws-cdk/blob/9c0fecf9a5cc26416e814ae4754729b54c827b9d/packages/aws-cdk-lib/aws-opensearchservice/lib/domain.ts#L1717

Since CustomResource is executed by CloudFormation after `cdk deploy`, it is difficult to remove the ResourcePolicy in the CDK code, for example by using the `tryRemoveChild` method.
It may be possible to work around this by using a new custom resource and rewriting or deleting the ResourcePolicy, though.

The PR I created is an ECS fix, and even if it were merged, it would not solve the problem on the OpenSearch side.
Would you be so kind as to create a new issue for us to discuss this matter further?
In addition to the fact that ResourcePolicy can currently be created in CloudFormation without the custom resource, ResourcePolicy should be reused as described in this document.
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createdomain-configure-slow-logs.html#:~:text=name%22%0A%20%20%20%20%7D%0A%7D-,Important,-CloudWatch%20Logs%20supports

**Comment by XiaowenMaoA** [comment] 2024-01-10 19:49
@sakurai-ryo  i found one related issue created before, https://github.com/aws/aws-cdk/issues/23637 
Can we use this to track log-resource-policy in OpenSearch case?
this is blocked our prod readiness coz we are scaling up to > 10 domain for sure. 

i can not find a way to pass the shared ResourcePolicy and with logging enabled. Is there any possible workaround?

**Closed** 2024-01-10 23:23 UTC
Labels: p1, feature-request, @aws-cdk/aws-cloudwatch, @aws-cdk/aws-ecs

**Comment by sakurai-ryo** [comment] 2024-01-11 09:23
@XiaowenMaoA 
Yes, of course.
As I mentioned in my previous comment, it may be difficult to avoid this problem.
I would consider a PR to solve this problem.

**Comment by stoicad** [comment] 2024-05-09 08:56
Any update on this? we don't want to add policies on our roles, but we are forced to do it when defining the logs..

**Comment by sakurai-ryo** [comment] 2024-05-09 13:11
Hi @stoicad.
Do you still have this problem when using aws-log-driver?

**Comment by stoicad** [comment] 2024-05-10 08:21
Hi @sakurai-ryo, yes we do. We are not allowed to touch the existing roles via CDK, but when defining this one: 
```
public createContainer(taskDefinition: FargateTaskDefinition): void {
    //TODO: fix logging on container
    //Log Group ARN: "arn:aws:logs:us-east-1::log-group:/ecs/web-taskdefinition:*"
    //logging: LogDrivers.awsLogs({ streamPrefix: `sap-interfaces-${this.ecsContextParams.environment}-web` })

    var container = taskDefinition.addContainer(`umpg-sap-interfaces-${this.ecsContextParams.environment}-web-container`, {
      image: ContainerImage.fromRegistry(this.envConfig.WEB_ECS_IMAGE)
    });

    container.addPortMappings({ containerPort: 80 });
    container.addPortMappings({ containerPort: 443 });
  }
```
it tries to add permissions to the role attached to the ECS (as a separate policy), although the logs:* is already available on the role.

**Comment by sakurai-ryo** [comment] 2024-05-10 09:02
Thanks @stoicad.
Does the existing roles refer to the ECS execution role?
Could you share the entire code and errors to help us pinpoint the problem?

**Comment by mxthxngx** [comment] 2025-01-10 18:08
i faced a similar issue for opensearch, and had to create a lambda that makes sdk calls to update the policy. 
i wrote an article on the same:  https://dev.to/math16/solved-resource-limit-exceeded-2np6 -- might be helpful for someone facing this issue
