### ISSUE TITLE
SES autogenerated receiptRuleName invalid

### ISSUE THREAD

**Issue by gbooth27** [aws/aws-cdk#5780] opened 2020-01-13 18:33 UTC
When deployed with a stackname of `Devjames--outlinex-serve-restructureEmailStack` the autogenerated `receiptRuleName` for an SES rule created by the stack was: `DevjamesoutlinexserverestructureEmailStackRules16A3-n9dMSUm45PxG` which resulted in a failure when deploying the stack, as the name is over the 64 character limit imposed by SES

### Reproduction Steps

The code that generated this error was: 
```
const rules = new ses.ReceiptRule(this, `${this.stackName}Rules`, {
            ruleSet: ses.ReceiptRuleSet.fromReceiptRuleSetName(
                this,
                `${this.stackName}DefaultRuleset`,
                'default-rule-set'
            ),
            recipients: [`${user}@incoming-email.${props.emailDomain}`],
            actions: [
                new actions.S3({
                    bucket: emailBucket,
                    objectKeyPrefix: 'emails/',
                }),
                new actions.Lambda({
                    function: emailLambda.lambda,
                    invocationType: actions.LambdaInvocationType.EVENT,
                }),
            ],
        })
```
the stack was named `Devjames--outlinex-serve-restructureEmailStack` and was attempted to be deployed with CDK 1.19.0

### Error Log

The relevant error log is:
```
2020-01-13T00:01:46.8967287Z  7/9 | 12:01:46 AM | CREATE_IN_PROGRESS   | AWS::SES::ReceiptRule         | Devjames--outlinex-serve-restructureEmailStackRules (DevjamesoutlinexserverestructureEmailStackRules16A3540C) 
2020-01-13T00:01:52.0396058Z  8/9 | 12:01:48 AM | CREATE_FAILED        | AWS::SES::ReceiptRule         | Devjames--outlinex-serve-restructureEmailStackRules (DevjamesoutlinexserverestructureEmailStackRules16A3540C) Not a valid ruleName: DevjamesoutlinexserverestructureEmailStackRules16A3-n9dMSUm45PxG (Service: AmazonSimpleEmailService; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 47e2b80e-f454-4e43-bdd3-165bd25c4d09)
2020-01-13T00:01:52.0397133Z 	new ReceiptRule (/home/runner/work/outline2.0/outline2.0/infra/corestack/node_modules/@aws-cdk/aws-ses/lib/receipt-rule.ts:121:22)
2020-01-13T00:01:52.0398253Z 	\_ new EmailStack (/home/runner/work/outline2.0/outline2.0/infra/corestack/lib/email-stack.ts:78:23)
2020-01-13T00:01:52.0398649Z 	\_ Object.<anonymous> (/home/runner/work/outline2.0/outline2.0/infra/corestack/bin/corestack.ts:249:33)
2020-01-13T00:01:52.0399112Z 	\_ Module._compile (internal/modules/cjs/loader.js:959:30)
2020-01-13T00:01:52.0399843Z 	\_ Module.m._compile (/home/runner/work/outline2.0/outline2.0/infra/corestack/node_modules/ts-node/src/index.ts:806:23)
2020-01-13T00:01:52.0400230Z 	\_ Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-01-13T00:01:52.0400845Z 	\_ Object.require.extensions.<computed> [as .ts] (/home/runner/work/outline2.0/outline2.0/infra/corestack/node_modules/ts-node/src/index.ts:809:12)
2020-01-13T00:01:52.0401196Z 	\_ Module.load (internal/modules/cjs/loader.js:815:32)
2020-01-13T00:01:52.0401498Z 	\_ Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-01-13T00:01:52.0401779Z 	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
2020-01-13T00:01:52.0402378Z 	\_ main (/home/runner/work/outline2.0/outline2.0/infra/corestack/node_modules/ts-node/src/bin.ts:226:14)
2020-01-13T00:01:52.0402995Z 	\_ Object.<anonymous> (/home/runner/work/outline2.0/outline2.0/infra/corestack/node_modules/ts-node/src/bin.ts:485:3)
2020-01-13T00:01:52.0403350Z 	\_ Module._compile (internal/modules/cjs/loader.js:959:30)
2020-01-13T00:01:52.0403660Z 	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-01-13T00:01:52.0403927Z 	\_ Module.load (internal/modules/cjs/loader.js:815:32)
2020-01-13T00:01:52.0404226Z 	\_ Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-01-13T00:01:52.0404489Z 	\_ Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
2020-01-13T00:01:52.0404792Z 	\_ /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
2020-01-13T00:01:52.0405814Z  8/9 | 12:01:49 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack    | Devjames--outlinex-serve-restructureEmailStack The following resource(s) failed to create: [DevjamesoutlinexserverestructureEmailStackRules16A3540C]. . Rollback requested by user.
```

### Environment

  - **CLI Version      : 1.19.0**
  - **Framework Version: 1.19.0**
  - **OS               :  ubuntu-bionic-18.04-amd64-server**
  - **Language         : Typescript**

### Other

We are confident that the issue is that CDK is autogenerating a name for the rule that exceeds the 64 char limit imposed by SES (when we used the autogenerated name to manually create the rule in the console we saw this: 
![Screen Shot 2020-01-13 at 9 43 46 AM](https://user-images.githubusercontent.com/13037196/72281793-12ad6c80-35f0-11ea-93b5-58a31b8612ff.png)

--- 

This is :bug: Bug Report

**Comment by jogold** [comment] 2020-01-14 06:07
Can you share the generated CF template?

**Comment by gbooth27** [comment] 2020-01-27 20:12
@jogold sorry have been out the past 2 weeks. do you still need the generated CF template?

**Comment by jogold** [comment] 2020-01-28 06:10
Yes, it will help debugging this.

**Comment by gbooth27** [comment] 2020-01-29 23:54
@jogold 
`Resources:
  DevjamesoutlinexserverestructureEmailStackEmailLambdaServiceRole553B499E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackEmailLambda/Devjames--outlinex-serve-restructureEmailStackEmailLambda/ServiceRole/Resource
  DevjamesoutlinexserverestructureEmailStackEmailLambda076B076C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8aS3BucketCB0A1AEF
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8aS3VersionKey4E5269A7
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8aS3VersionKey4E5269A7
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - DevjamesoutlinexserverestructureEmailStackEmailLambdaServiceRole553B499E
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          API_URL: https://james--outlinex-serve-restructure.outl.in/api
      Timeout: 60
    DependsOn:
      - DevjamesoutlinexserverestructureEmailStackEmailLambdaServiceRole553B499E
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackEmailLambda/Devjames--outlinex-serve-restructureEmailStackEmailLambda/Resource
      aws:asset:path: asset.058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8a
      aws:asset:property: Code
  DevjamesoutlinexserverestructureEmailStackEmailLambdasesInvoke7E83DE63:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DevjamesoutlinexserverestructureEmailStackEmailLambda076B076C
          - Arn
      Principal: ses.amazonaws.com
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackEmailLambda/Devjames--outlinex-serve-restructureEmailStackEmailLambda/sesInvoke
  DevjamesoutlinexserverestructureEmailStackEmailLambdaAllowSes6169F861:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DevjamesoutlinexserverestructureEmailStackEmailLambda076B076C
          - Arn
      Principal: ses.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackEmailLambda/Devjames--outlinex-serve-restructureEmailStackEmailLambda/AllowSes
  DevjamesoutlinexserverestructureEmailStackEmailLambdalambaLogGroupE60D418C:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - /aws/lambda/
            - Ref: DevjamesoutlinexserverestructureEmailStackEmailLambda076B076C
      RetentionInDays: 731
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackEmailLambda/lambaLogGroup/Resource
  DevjamesoutlinexserverestructureEmailStackEmailLambdalambaLogGrouplambdaSubscription2378C527:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn:
        Fn::ImportValue: Corestack-dd-lambda-arn
      FilterPattern: ""
      LogGroupName:
        Ref: DevjamesoutlinexserverestructureEmailStackEmailLambdalambaLogGroupE60D418C
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackEmailLambda/lambaLogGroup/lambdaSubscription/Resource
  DevjamesoutlinexserverestructureEmailStackRules16A3540C:
    Type: AWS::SES::ReceiptRule
    Properties:
      Rule:
        Actions:
          - S3Action:
              BucketName:
                Fn::ImportValue: Corestack-email-bucket-name
              ObjectKeyPrefix: emails/
          - LambdaAction:
              FunctionArn:
                Fn::GetAtt:
                  - DevjamesoutlinexserverestructureEmailStackEmailLambda076B076C
                  - Arn
              InvocationType: Event
        Enabled: true
        Recipients:
          - james--outlinex-serve-restructure-submit@incoming-email.outl.in
      RuleSetName: default-rule-set
    DependsOn:
      - DevjamesoutlinexserverestructureEmailStackEmailLambdaAllowSes6169F861
    Metadata:
      aws:cdk:path: Devjames--outlinex-serve-restructureEmailStack/Devjames--outlinex-serve-restructureEmailStackRules/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.19.0,@aws-cdk/assets=1.19.0,@aws-cdk/aws-applicationautoscaling=1.19.0,@aws-cdk/aws-autoscaling=1.19.0,@aws-cdk/aws-autoscaling-common=1.19.0,@aws-cdk/aws-autoscaling-hooktargets=1.19.0,@aws-cdk/aws-certificatemanager=1.19.0,@aws-cdk/aws-cloudformation=1.19.0,@aws-cdk/aws-cloudwatch=1.19.0,@aws-cdk/aws-codebuild=1.19.0,@aws-cdk/aws-codepipeline=1.19.0,@aws-cdk/aws-codepipeline-actions=1.19.0,@aws-cdk/aws-ec2=1.19.0,@aws-cdk/aws-ecr=1.19.0,@aws-cdk/aws-ecr-assets=1.19.0,@aws-cdk/aws-ecs=1.19.0,@aws-cdk/aws-elasticloadbalancingv2=1.19.0,@aws-cdk/aws-events=1.19.0,@aws-cdk/aws-events-targets=1.19.0,@aws-cdk/aws-iam=1.19.0,@aws-cdk/aws-kms=1.19.0,@aws-cdk/aws-lambda=1.19.0,@aws-cdk/aws-logs=1.19.0,@aws-cdk/aws-logs-destinations=1.19.0,@aws-cdk/aws-rds=1.19.0,@aws-cdk/aws-route53=1.19.0,@aws-cdk/aws-route53-targets=1.19.0,@aws-cdk/aws-s3=1.19.0,@aws-cdk/aws-s3-assets=1.19.0,@aws-cdk/aws-sam=1.19.0,@aws-cdk/aws-secretsmanager=1.19.0,@aws-cdk/aws-servicediscovery=1.19.0,@aws-cdk/aws-ses=1.19.0,@aws-cdk/aws-ses-actions=1.19.0,@aws-cdk/aws-sns=1.19.0,@aws-cdk/aws-sns-subscriptions=1.19.0,@aws-cdk/aws-sqs=1.19.0,@aws-cdk/aws-ssm=1.19.0,@aws-cdk/core=1.19.0,@aws-cdk/cx-api=1.19.0,@aws-cdk/region-info=1.19.0,jsii-runtime=node.js/v12.10.0
Parameters:
  AssetParameters058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8aS3BucketCB0A1AEF:
    Type: String
    Description: S3 bucket for asset "058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8a"
  AssetParameters058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8aS3VersionKey4E5269A7:
    Type: String
    Description: S3 key for asset version "058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8a"
  AssetParameters058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8aArtifactHashC9AB149D:
    Type: String
    Description: Artifact hash for asset "058f3c69c5607ff87ca32cf58f950542dcc66bb13cafd2d45774f890d1f7ad8a"
`

**Comment by jogold** [comment] 2020-02-04 08:15
From your template we can see that the [`AWS::SES::ReceiptRule`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptrule.html) resource doesn't specify the [`Name`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-receiptrule-rule.html#cfn-ses-receiptrule-rule-name) property. This is the expected behavior from a CDK perspective.

When no `Name` is specified, CloudFormation is supposed to generate it and I would expect it to be valid. This looks like a CloudFormation bug.

**Comment by shivlaks** [comment] 2020-02-04 23:59
@jogold thanks for helping triage this one. It does look like a CloudFormation bug. It might be a good idea to log the issue in the [CloudFormation coverage map repo](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new)

dropping the bug label for now and marking this as `needs-cfn`

**Comment by iliapolo** [comment] 2020-03-12 19:22
@gbooth27 Im closing this issue since it isn't actionable on the CDK side. 

We encourage you to open a an issue on the [CloudFormation coverage map repo](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/new) and keep tracking it there.

**Closed by iliapolo** 2020-03-12 19:22 UTC
Labels: bug, needs-cfn, package/ses
