### ISSUE TITLE
(assertions): support `stringLike` in `haveOutput`

### ISSUE THREAD

**Issue by kadishmal** [aws/aws-cdk#11759] opened 2020-11-28 02:40 UTC
I'm using `haveOutput` in order to assert the value of the `Output` structure. It accepts an exact value and doesn't seem to accept the return value of the `stringLike` function.

### Reproduction Steps

The actual output template is:

    "Outputs": {
      "RootHostedZoneID": {
        "Value": {
          "Ref": "RootHostedZone29FAB053"
        },
        "Export": {
          "Name": "RootHostedZoneID"
        }
      }
    }

Here is an example that **doesn't** work:

    expectCDK(stack).to(haveOutput({
      outputName: 'RootHostedZoneID',
      exportName: 'RootHostedZoneID',
      outputValue: {
        Ref: stringLike('RootHostedZone*')
      }
    }));

Here is an example that **does** work:

    expectCDK(stack).to(haveOutput({
      outputName: 'RootHostedZoneID',
      exportName: 'RootHostedZoneID',
      outputValue: {
        Ref: 'RootHostedZone29FAB053'
      }
    }));

### What did you expect to happen?

I expect the return value of `stringLike('RootHostedZone*')` to have been accepted and correctly asserted.

### What actually happened?

The assertion fails:

```
...
      "Outputs": {
        "RootHostedZoneID": {
          "Value": {
            "Ref": "RootHostedZone29FAB053"
          },
          "Export": {
            "Name": "RootHostedZoneID"
          }
        }
      }
    } does not match output with name 'RootHostedZoneID', export name "RootHostedZoneID", value {"Ref":{"$stringContaining":"RootHostedZone*"}}

      55 |     const rootHostedZoneIDExportName = 'RootHostedZoneID';
      56 |
    > 57 |     expectCDK(stack).to(haveOutput({
         |                      ^
      58 |       outputName: rootHostedZoneIDExportName,
      59 |       exportName: rootHostedZoneIDExportName,
      60 |       outputValue: {

      at HaveOutputAssertion.assertOrThrow (node_modules/@aws-cdk/assert/lib/assertion.ts:18:13)
      at StackInspector._to (node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (test/domains.test.ts:57:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.142 s, estimated 6 s
```

### Environment

  - **CDK CLI Version :** 1.75.0 (build 7708242)
  - **Framework Version:** 1.75.0
  - **Node.js Version:** v14.15.1
  - **OS               :** macOS 10.15.7
  - **Language (Version):** TypeScript 4.1.2

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-12-08 14:30
Marking this as a feature request.

**Comment by kaizen3031593** [comment] 2022-01-03 21:57
Calling this a duplicate of #18051 since that issue is more aligned with the new `assertions` library.

**Closed by kaizen3031593** 2022-01-03 21:57 UTC
Labels: p2, feature-request, effort/small, @aws-cdk/assertions

**Comment by stevehodgkiss** [comment] 2022-02-07 08:32
@kaizen3031593 I think this should be reopened because it's still an issue and #18051 hasn't solved it AFAICT. `haveOutput` doesn't support `stringLike` presumably because it compares using `JSON.stringify` https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/assert-internal/lib/assertions/have-output.ts#L46
