### ISSUE TITLE
StackOverflow testing the "Accessing Resources in a Different Stack" in deepCopy

### ISSUE THREAD

**Issue by lanwen** [aws/aws-cdk#6628] opened 2020-03-09 00:37 UTC
Have a resource in one stack, following the https://docs.aws.amazon.com/cdk/latest/guide/resources.html
Just want to test the dependent stack with `@aws-cdk/assert`

And getting 
```
RangeError: Maximum call stack size exceeded
```

### Reproduction Steps

```javascript
const { expect, matchTemplate, MatchStyle } = require('@aws-cdk/assert');
const cdk = require('@aws-cdk/core');
const s3 = require('@aws-cdk/aws-s3');
const iam = require('@aws-cdk/aws-iam');

test('Test Stack', () => {
    const app = new cdk.App();
    // WHEN
    const bucketStack = new BucketStack(app, "Bucket");
    const stack = new DependentStack(app, 'MyTestStack', {
        bucket: bucketStack.bucket,
    });
    // THEN (anything to trigger)
    expect(stack).to(matchTemplate({
      "Resources": {}
    }, MatchStyle.EXACT))
});

class BucketStack extends cdk.Stack {
    constructor(scope, id, props) {
        super(scope, id, props);
        this.bucket = new s3.Bucket(this, "bucket");
    }
}

class DependentStack extends cdk.Stack {
    constructor(scope, id, props) {
        super(scope, id, props);
        props.bucket.grantRead(new iam.AnyPrincipal())
    }
}
```

### Error Log

```
RangeError: Maximum call stack size exceeded

at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:168:18)
at Array.map (<anonymous>)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:170:14)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
at deepCopy (/<path>/node_modules/@aws-cdk/cloudformation-diff/lib/diff-template.ts:176:18)
at Array.map (<anonymous>)
...
```

### Environment

  - **CLI Version      :*1.27.0*
  - **Framework Version:*1.27.0*
  - **OS               :*mac*
  - **Language         :*javascript*

### Other

--- 

This is :bug: Bug Report

**Comment by eladb** [comment] 2020-03-12 15:46
We are unable to reproduce this based on your example.

**Comment by eladb** [comment] 2020-03-19 15:11
Closing. Reopen if still relevant.

**Closed by eladb** 2020-03-19 15:11 UTC
Labels: bug, needs-triage, package/assert
