### ISSUE TITLE
[aws-redshift] Redshift cluster failing to update when adding a role

### ISSUE THREAD

**Issue by diondree** [aws/aws-cdk#11382] opened 2020-11-10 00:10 UTC
In my current cdk project, I previously created a redshift cluster but at the time I did not specify a role for the cluster. Upon trying to later add the role, I received an error. 

### Reproduction Steps

1. Create a redshift cluster without assigning any roles
2. Create a role and try to assign it to the already existing cluster
3. Attempt to deploy these new changes.

```ts
const redshiftRole = new Role(this, `myRedshiftRole`, {
      roleName: 'redshift-role',
      assumedBy: new ServicePrincipal('redshift.amazonaws.com'),
});

const redshiftS3Permission = new PolicyStatement({
      effect: Effect.ALLOW,
      actions: ['s3:Get*', 's3:List*'],
      resources: ['*'],
});
redshiftRole.addToPolicy(redshiftS3Permission);

new RedShiftCluster(
      this,
      `myRedshiftCluster`,
      {
         clusterName: `my-redshift-cluster`,
         defaultDatabaseName: `dev`,
         masterUser: {
           masterUsername: 'admin',
         },
         vpc,
         publiclyAccessible: true,
         roles: [redshiftRole],
       }
);
```

### What did you expect to happen?
I expected the cluster to be updated in the console with the IAM role assigned to it.

### What actually happened?
I received the following error:

```bash
MyStack: deploying...
[0%] start: Publishing 6af711c7088ddddcec2612c999791a45af5c84b03f0328107f142f22e648ff4c:current
[16%] success: Published 6af711c7088ddddcec2612c999791a45af5c84b03f0328107f142f22e648ff4c:current
[16%] start: Publishing dfb0913e88c6ad6adfa9e0c26eecf89152670197c6940d0ce7f03127a2f7a266:current
[33%] success: Published dfb0913e88c6ad6adfa9e0c26eecf89152670197c6940d0ce7f03127a2f7a266:current
[33%] start: Publishing 0cff118bc8c75bf2e99eb742c360336bbd0b6c58cd687687685ac35f3974e52d:current
[50%] success: Published 0cff118bc8c75bf2e99eb742c360336bbd0b6c58cd687687685ac35f3974e52d:current
[50%] start: Publishing cb6db5784120018db963e246354d73c07655575fcc799bf7dff37745082c06cc:current
[66%] success: Published cb6db5784120018db963e246354d73c07655575fcc799bf7dff37745082c06cc:current
[66%] start: Publishing 781afe3ce585d258fe7673c5b609c394e303ddd63d958233b8864153f8cca16d:current
[83%] success: Published 781afe3ce585d258fe7673c5b609c394e303ddd63d958233b8864153f8cca16d:current
[83%] start: Publishing 71f17014c12fdd3fa3984387f4845ffc569966de4c71ae67cfa63a26fe1c2487:current
[100%] success: Published 71f17014c12fdd3fa3984387f4845ffc569966de4c71ae67cfa63a26fe1c2487:current
MyStack: creating CloudFormation changeset...
[███████████████████████▏··································] (2/5)

7:45:37 PM | UPDATE_FAILED        | AWS::Redshift::Cluster                      | myRedshiftCluster
Cluster not found: myRedshiftCluster (Service: AmazonRedshift; Status Code: 404; Error Code: ClusterNotFound; Request ID: 9c732b0e-fd0e-444b-9f14-1ee34f46804a; Proxy: null)
7:45:39 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack                  | MyStack
The following resource(s) failed to update: [myRedshiftClusterC1D12244].
```

### Environment

  - **CDK CLI Version:** 1.72.0
  - **Framework Version:** 1.72.0
  - **Node.js Version:** v15.1.0
  - **OS:** Mac OS 11.0
  - **Language (Version):** TypeScript (3.9.7) 

--- 

This is :bug: Bug Report

**Comment by njlynch** [comment] 2020-11-11 13:53
Hm.. adding and removing roles shouldn't require any interruption, and certainly should be possible.

Did anything else about the cluster change (e.g., its name, logical ID)? Can you share the output from `cdk diff`?

**Comment by diondree** [comment] 2020-11-11 14:06
@njlynch I'm currently trying to do that but I'm seeing a lot of changes for some reason I'm seeing a lot of changes

**Comment by njlynch** [comment] 2020-11-17 17:29
@diondree - I haven't been able to reproduce this behavior, either on my own or using your repro steps. 

I noted that in an earlier (edited) comment, you said "I'm currently trying to do [show the diff] but I'm seeing a lot of changes for some reason". I'm wondering if there were other (unrelated) changes that caused the issue. Can you still reliably reproduce this?

**Comment by diondree** [comment] 2020-11-17 17:55
@njlynch Hi thats very strange. The changes you would be seeing there is only related to me altering the names of the stack and resources.

After not finding a solution or a workaround, I have since decided to remove the cluster from the stack and orphan it.

**Comment by diondree** [comment] 2020-11-17 18:03
@njlynch no I would’ve only renamed it in what I posted on GitHub

**Comment by njlynch** [comment] 2020-11-18 11:24
Given I have been unable to reproduce given the above reproduction steps -- or via a few other attempts building on the above steps -- and you have since orphaned the cluster and cannot reproduce, I'm going to close this out. Feel free to reopen if a set of reproducible steps are found, or if you (or anyone else) hits the same issue again and can provide more details in terms of the generated CloudFormation template and/or diff.

**Closed by njlynch** 2020-11-18 11:24 UTC
Labels: @aws-cdk/aws-redshift, bug, needs-triage
