### ISSUE TITLE
(ec2): Subnet and ISubnet variable naming causes Pylance type error

### ISSUE THREAD

**Issue by jakestambaugh** [aws/aws-cdk#20125] opened 2022-04-28 17:41 UTC
### Describe the bug

The L2 construct `Subnet` doesn't use the same method parameter names as `ISubnet` in `associate_network_acl`. This makes Pylance believe that `Subnet` does not implement the interface `ISubnet`, causing it to raise warnings.

### Expected Behavior

Pylance would understand that "Subnet" implements "ISubnet" and not raise errors.

### Current Behavior

```sh
(variable) subnet: Subnet
Argument of type "list[Subnet]" cannot be assigned to parameter "subnets" of type "Sequence[ISubnet] | None" in function "__init__"
  Type "list[Subnet]" cannot be assigned to type "Sequence[ISubnet] | None"
    TypeVar "_T_co@Sequence" is covariant
      "Subnet" is incompatible with protocol "ISubnet"
        "associate_network_acl" is an incompatible type
          Type "(id: str, network_acl: INetworkAcl) -> None" cannot be assigned to type "(id: str, acl: INetworkAcl) -> None"
```

### Reproduction Steps

In VS Code with the "Pylance" language server extension enabled, add this stack to a CDK project and look for the red squiggly lines in the `SubnetSelection` constructor.

```python
from aws_cdk import (
    # Duration,
    Stack,
    aws_ec2 as ec2,
)
from constructs import Construct


class ReproStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        vpc = ec2.Vpc(self, "vpc")
        subnet = ec2.Subnet(
            self,
            "subnet",
            availability_zone="us-east-1a",
            vpc_id=vpc.vpc_id,
            cidr_block="10.0.0.0/16",
        )

        subnet_filter = ec2.SubnetSelection(subnets=[subnet])
```

### Possible Solution

Change the parameter name for the `INetworkAcl` type to be consistent across `Subnet` and `ISubnet`.

https://github.com/aws/aws-cdk/blob/f199faddc0b8e565aa413e480e51d25fed5321bf/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L61

https://github.com/aws/aws-cdk/blob/f199faddc0b8e565aa413e480e51d25fed5321bf/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1757

### CDK CLI Version

2.22.0 (build 1db4b16)

### Framework Version

Pylance v2022.4.3

### Node.js Version

v16.14.2

### OS

Ubuntu 20.04.4 LTS (WSL 2)

### Language

Python

### Language Version

3.10.4

**Comment by jakestambaugh** [comment] 2022-05-03 19:10
I think that I installed Pylance as a dependency of the "Python" package (https://marketplace.visualstudio.com/items?itemName=ms-python.python). It could be that the default Pylance extension settings don't configure linting.

FWIW, I was able to reproduce this on a fresh Ubuntu installation with the Python extension.

If you want to add this to the `.vscode/extensions.json` file it will suggest the Python plugin:

```json
{
    "recommendations": [
        "ms-python.python"
    ]
}
```

**Comment by gshpychka** [comment] 2022-09-07 14:34
This happens in a lot of constructs and is being tracked here: https://github.com/aws/aws-cdk/issues/15584 and https://github.com/aws/jsii/issues/2927

**Comment by skalinets** [comment] 2022-10-14 09:57
Are there any workarounds available? Like muting pyright warnings etc. The issues from previous comment are more than one year old :) Just wondering how people work with python CDK.

**Comment by gshpychka** [comment] 2022-10-14 10:10
> Are there any workarounds available? Like muting pyright warnings etc. The issues from previous comment are more than one year old :) Just wondering how people work with python CDK. 

yes, the current workaround is to use typing.cast to satisfy the type checker.

**Comment by MrArnoldPalmer** [comment] 2023-01-27 21:59
Closing this as a duplicate of https://github.com/aws/aws-cdk/issues/15584 track there for updates/comments.

**Closed by MrArnoldPalmer** 2023-01-27 21:59 UTC
Labels: bug, p1, language/python, @aws-cdk/aws-ec2
