### ISSUE TITLE
lambda.Function allow undefined as values for environment

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#5124] opened 2019-11-20 06:55 UTC
It will be useful to be able to pass in `undefined` as a value for `environment` when defining a `lambda.Function`, in which case the key will not be added.

### Use Case

To allow "default" to be propagated to a Lambda handler without needing to conditionally define the environment variable or pass an empty string.

For example, say I have a construct defined like this:

```ts
interface MyConstructProps {
  readonly optionalEnvValue?: string;
}

class MyConstruct extends Construct {
  constructor(scope: Construct, id: string, props: MyConstructProps) {
    super(scope, id);
  }
}
```

Now, say I want to delegate `props.optionalEnvValue` to a lambda handler. Today, I would have to do something like this:

```ts
const handler = new lambda.Function(this, 'Handler', {
  environment: {
    OPTIONAL_ENV_VALUE: props.optionalEnvValue || '' // otherwise the compiler will yell
  }
}
```

This will result in an env var with an empty string (not the end of the world, but in some cases could be an issue).

or, use `addEnvironment` surrounded by a condition:

```ts
if (props.optionalEnvValue) {
  handler.addEnvironment('OPTIONAL_ENV_VALUE', props.optionalEnvValue);
}
```

I want to be able to do this:

```ts
const handler = new lambda.Function(this, 'Handler', {
  environment: {
    OPTIONAL_ENV_VALUE: props.optionalEnvValue
  }
}
```

If `optionalEnvValue` is not defined, the variable will not be added, otherwise it will be assigned.

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment] 2020-02-05 16:09
Duplicate of https://github.com/aws/aws-cdk/issues/4085

**Closed by nija-at** 2020-02-05 16:09 UTC
Labels: effort/small, feature-request, good first issue, package/lambda
