### ISSUE TITLE
`aws_cloudwatch`, `aws_secretsmanager`: `SyntaxWarning: invalid escape sequence '\|'`

### ISSUE THREAD

**Issue by garysassano** [aws/aws-cdk#29518] opened 2024-03-16 14:55 UTC
### Describe the bug

```sh
❯ pj deploy
👾 deploy | cdk deploy
/home/user/github/cdk-aws-app/.venv/lib/python3.12/site-packages/aws_cdk/aws_cloudwatch/__init__.py:1: SyntaxWarning: invalid escape sequence '\|'
  '''
/home/user/github/cdk-aws-app/.venv/lib/python3.12/site-packages/aws_cdk/aws_secretsmanager/__init__.py:1: SyntaxWarning: invalid escape sequence '\`'
  '''
```

### Expected Behavior

No warnings displayed when using `cdk deploy`.

### Current Behavior

Warnings are displayed for the `aws_cloudwatch` and `aws_secretsmanager` packages.

### Reproduction Steps

`cdk deploy`

### CDK CLI Version

2.127.0

### Node.js Version

20.11.1

### OS

Ubuntu 22.04.3 LTS

### Language

Python

### Language Version

3.12.1

**Comment by tim-finnigan** [comment] 2024-03-18 16:47
Thanks for reaching out. This looks like a duplicate of https://github.com/aws/aws-cdk/issues/24746. I think [this comment](https://github.com/aws/aws-cdk/issues/24746#issuecomment-1579208884) may have identified the underlying issue:
>This seems to be caused by the generated code that puts the documentation at the top of the module (so maybe this is really a [jsii issue](https://github.com/aws/jsii)?). The fix seems to be as simple as putting an `r` at the top before the `'''`, i.e. make it a raw string, so that way Python doesn't try to interpret the backslashes as escape characters.

This needs further review but I think we should continue tracking in https://github.com/aws/aws-cdk/issues/24746 going forward to consolidate the investigation and discussion.

**Closed** 2024-03-18 16:48 UTC
Labels: bug, duplicate, @aws-cdk/aws-cloudwatch
