### ISSUE TITLE
Unable to use aws_cdk.aws_lambda_event_sources 

### ISSUE THREAD

**Issue by shriraja** [aws/aws-cdk#6793] opened 2020-03-18 15:16 UTC
I am trying to setup S3 trigger for Lambda and imported the aws_cdk.aws_lambda_event_sources but getting cannot find reference.

### Reproduction Steps

Specify this line "from aws_cdk.aws_lambda_event_sources import S3EventSource" and you will get reference error.

### Environment

  - **CLI Version      : 1.28.0
  - **Framework Version:**
  - **OS               : MAC
  - **Language         : Python 3.7

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-03-20 09:44
Cannot reproduce. I am able to successfully synthesize the following code, using version `1.30.0` - 

```python
#!/usr/bin/env python3

from aws_cdk import core
from aws_cdk.aws_s3 import Bucket, EventType
from aws_cdk.aws_lambda_event_sources import S3EventSource

from hello_cdk_python.hello_cdk_python_stack import HelloCdkPythonStack


app = core.App()
stack = core.Stack(app, "mystack")
bucket = Bucket(stack, "mybucket")
eventsource = S3EventSource(bucket, events=[EventType.OBJECT_CREATED])

app.synth()
```

Check if you have followed the correct procedure of installing your dependencies. If you used `cdk init` to initialize your CDK app, 
1. make sure you have `aws-cdk.aws-lambda-event-sources` as an entry under `install_requires` in `setup.py`
2. Then make sure you install the dependencies by running `pip install -r requirements.txt'

Thanks.

**Comment by nija-at** [comment] 2020-03-25 15:57
Closing this for now. Please re-open when you have updates here.

**Closed by nija-at** 2020-03-25 15:57 UTC
Labels: guidance, package/lambda, response-requested
