### ISSUE TITLE
(aws-lambda-python): skip build lambda for all  cdk commands

### ISSUE THREAD

**Issue by rtrive** [aws/aws-cdk#12684] opened 2021-01-24 21:14 UTC
Is it possible to avoid to rebuild lambda at every cdk diff or cdk deploy if no updates are made on them?

### Use Case

Every time that i need to change a single configuration parameter on a stack, all lambdas are rebuilt with docker and it takes too much time to deploy a single stack

### Proposed Solution

Implement an hash check between lambda version or a flag that enable or disable lambda build

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by risenberg-cyberark** [comment] 2021-01-25 08:54
a must have  feature IMHO

**Comment by AnatoliiHanziuk** [comment] 2021-01-25 17:50
And why does cdk for aws-lambda-python requires docker?  
When I write `const fn = new PythonFunction(this, "Test", {entry:"",});` then after running `cdk synth` i receive error `Cannot connect to the Docker daemon`. It means that if I want to execute `cdk synth` for any other stack I need to have docker installed and running.

**Comment by eladb** [comment] 2021-02-15 08:57
This is technically a duplicate of #12770

**Comment by NGL321** [comment] 2021-12-17 06:13
Reopening as an internal support request noted that this behavior still occurs. I have reproduced this behavior in the latest release. According to the PS engineer:

> The `bundling.ts` irrespective of changes to the entry code or stack code, it will call the `cdk.DockerImage.fromBuild` and generate the `tagHash` and do `dockerExec`. I think this is needed cause we are not sure if the build happened on the machine already but at the same I kinda see why cx doesn't want this to happen if they didn't touch any of the lambda stuff.

Since this is non-blocking and doesnt significantly impact performance I am leaving as a feature-request and setting priority to low.

**Comment by corymhall** [comment] 2022-03-08 19:59
This should be fixed with a combination of #19143 and #18082

**Closed by corymhall** 2022-03-08 19:59 UTC
Labels: p2, feature-request, @aws-cdk/aws-lambda-python
