### ISSUE TITLE
cdk deploy method instead of cli?

### ISSUE THREAD

**Issue by eakrum** [aws/aws-cdk#5715] opened 2020-01-08 16:28 UTC
Maybe this exists already but wondering if there is a workaround or possibility to incorporate a `cdk deploy` method instead of deploying resources via cli?

### Use Case

```
    app = core.App()
    MyTestStack(app, "RdsTest")
    app.synth()
    app.deploy()
```

**Comment by saltman424** [comment] 2020-01-14 19:15
+1

**Comment by shivlaks** [comment] 2020-02-24 16:07
Duplicate of #601

**Closed by shivlaks** 2020-02-24 16:07 UTC
Labels: feature-request, package/tools, status/needs-triage
