### ISSUE TITLE
[lambda-nodejs] Multiple Parcel Builds Long Build Times

### ISSUE THREAD

**Issue by quantumew** [aws/aws-cdk#10589] opened 2020-09-29 13:27 UTC
## :question: General Issue

We are utilizing the NodejsFunction construct to build out our Nodejs bundles for lambda. We have services with up to 20 functions. The build time on these stacks is long. We are considering going back to Webpack so we can group all of the entries into a single build and save a load of time. We have also found that parcel's cache is helping very minimally. These build times effect our tests as well, which makes it much harder to endure.

### The Question

Is there a way to combine Parcel builds? Or generally speed up build times?

### Environment

  - **CDK CLI Version:** 1.64.1
  - **Module Version:** 1.64.1
  - **Node.js Version:** v12.18.3
  - **OS:** OSX
  - **Language (Version):** 4.0.2 
  - **Parcel version:** 2.0.0-beta.1

### Other information

Asked the question on Gitter. Someone recommended splitting up our stacks. This could help when making small changes but it also increases complexity a lot and in the end all will be run anyways.

**Comment by Dzhuneyt** [comment] 2020-10-28 13:21
I just tested https://github.com/floydspace/aws-lambda-nodejs-esbuild (which uses the `esbuild` packages), and it seems to be magnitudes faster than the current Parcel implementation.

Any chance we can bring this to AWS CDK core?

**Comment by NGL321** [comment] 2020-10-28 22:41
Hey @quantumew,

After reviewing both issues, it seems like you are doing everything correctly within the currently available constructs, so this is really a bug report about poor performance of the `aws-lambda-nodejs`. So I am going to call this a duplicate of #10286 as mentioned by @jaapvanblaaderen.

If you disagree with the assessment, feel free to reopen the issue and say why its different.

If you are not the OP and are tracking this, please upvote the linked issue so we push it higher in priorities!

😸 😷

**Closed by NGL321** 2020-10-28 22:41 UTC
Labels: @aws-cdk/aws-lambda-nodejs, duplicate, guidance
