### ISSUE TITLE
[lambda] Expose function's log group as property

### ISSUE THREAD

**Issue by Shahab96** [aws/aws-cdk#4348] opened 2019-10-02 19:26 UTC
Exposing the log group created by cdk for a lambda function as a property.

### Use Case

When making metrics to monitor lambda memory consumption, the only way to do it currently is by using a metric filter on the cloudwatch logs. However the metric filter requires a log group object to apply the filter on and in order to get the log group object currently, we need to parse the arn of the generated log group and use that to capture the ILogGroup object which we would use to apply metric filters.

### Proposed Solution
Expose the log group that cdk creates for the lambda function as a property

Proposed solution:
```Typescript
public logGroup: ILogGroup;
constructor(scope: Construct, id: string, props: FunctionProps) {
    ...
    this.logGroup = logs.LogGroup.fromLogGroupArn(scope, id, parsedLogGroupArn);
}
```

Expected result:
```Typescript
const func = new lambda.Function(...someArgumentsHere);
const logGroup = func.logGroup;
```

### Other
* [x] :wave: I may be able to implement this feature request

This is a :rocket: Feature Request

**Comment by NGL321** [comment] 2019-10-03 19:52
Hey @Shahab96,

Thank you for commenting! This seems like a reasonable feature request. We can definitely look into it, however if you would like to see this fast, your best bet is submitting a PR yourself!

Either way, someone will comment here to let you know when there is an update!

😸

**Comment by nija-at** [comment] 2019-10-18 16:06
Related https://github.com/aws/aws-cdk/issues/667 & https://github.com/aws/aws-cdk/issues/3838

**Comment by nija-at** [comment] 2019-10-18 16:10
Duplicate of https://github.com/aws/aws-cdk/issues/3838

**Closed by nija-at** 2019-10-18 16:10 UTC
Labels: feature-request, package/lambda
