### ISSUE TITLE
(aws-s3-deployment): cr-owned is changed each time when dynamic stacks are created

### ISSUE THREAD

**Issue by Dreamescaper** [aws/aws-cdk#17987] opened 2021-12-13 11:55 UTC
### What is the problem?

We create feature environments using CDK (i.e. application, which is separate for each feature branch). But some resources are shared across all feature environments. In CDK project that is represented by two stack - SharedResourcesStack (which is same for all environments) and EnvSpecificStack (which is parametrized and separate for each environment).

S3 bucket is shared resource, and BucketDeployment is env-specific resource.

Problem is that after https://github.com/aws/aws-cdk/pull/17530 shared stack always contains changes for `cr-owned` tag, even if nothing is changed in the stack itself.

### Reproduction Steps

[CdkRepro.zip](https://github.com/aws/aws-cdk/files/7703434/CdkRepro.zip)

1. Extract repro archive.
2. Run 'cdk deploy --all'
3. Run 'cdk diff --all'

### What did you expect to happen?

Since SharedResourcesStack is not changed, I expect diff to be empty.

### What actually happened?

Diff:
```
Resources
[~] AWS::S3::Bucket shared-bucket sharedbucket8A4E9AC1
 └─ [~] Tags
     └─ @@ -8,11 +8,11 @@
        [ ]   "Value": "true"
        [ ] },
        [ ] {
        [-]   "Key": "aws-cdk:cr-owned:51595d88b7784df2a0bf266a3bf2f4cd:302cf9db",
        [+]   "Key": "aws-cdk:cr-owned:f7af6da9c32a47ff9eb98d4e6fb12607:64c90823",
        [ ]   "Value": "true"
        [ ] },
        [ ] {
```

### CDK CLI Version

2.1.0 (build f4f18b1)

### Node.js Version

v14.17.3

### OS

Windows 10

### Language

.NET

### Other information

I was able to workaround that by adding something like that to EnvSpecificStack, but not sure about this:
```csharp
            bucket = Bucket.FromBucketArn(this, "imported-bucket", bucket.BucketArn);
```

**Comment by Dreamescaper** [comment] 2021-12-13 14:24
Yeah, but we _do_ have stacks with non-constant names.

**Comment by corymhall** [comment] 2021-12-14 19:42
@Dreamescaper this is expected behavior with the `BucketDeployment` construct. 

When you use the `BucketDeployment` and "attach" it to a bucket, you are essentially giving it access to manage some of the "state" in the Bucket. And you can have multiple BucketDeployment constructs that all manage some of that state (even overlapping state). We are using the bucket tags to manage this "attachment". 

For example, and the reason this was implemented in the first place, if the BucketDeployment custom resource were to be replaced (and you had `retainOnDelete: false`) you would see:

1. New resource creation which would cause the BucketDeployment to sync files to the Bucket.
2. Old resource deletion which would cause the BucketDeployment to delete files in the Bucket.

In this scenario we do not want to delete any files so we query the bucket tags to see if the state of this bucket+prefix is current "owned" by any BucketDeployment resource and if it is then we do _not_ delete any files.

The Bucket itself is the source of truth on what BucketDeployment resources are attached, so when we change the BucketDeployment resource (or add/remove one) the Bucket needs to be updated as well.

**Comment by Dreamescaper** [comment] 2021-12-14 19:44
@corymhall 
Thanks for an explanation!
I'm curious, how is that going to work with imported Bucket?

**Comment by corymhall** [comment] 2021-12-20 14:14
@Dreamescaper that is a good callout, currently this does not work with imported buckets. That is definitely something that we should look at implementing though.

**Comment by Dreamescaper** [comment] 2021-12-20 15:06
Thanks!)
Would be great if it would be able to handle setup like ours, with bucket in shared stack :)

**Comment by comcalvi** [comment] 2023-01-27 21:53
Looks like this has been resolved and that there's no need for further discussion, so I'm closing this one. Feel free to reopen if more discussion is needed

**Closed by comcalvi** 2023-01-27 21:53 UTC
Labels: bug, p1, @aws-cdk/aws-s3, @aws-cdk/aws-s3-deployment

**Comment by jgoux** [comment] 2023-06-23 08:37
Hello team 👋,

I'm in the same situation as @Dreamescaper, the fact that the tag has to be updated makes CloudFormation spend ~80s on my stack where the bucket lives. I know in advance that I will never need this tag because all my environment stacks live in their key prefix.

I'd like to suggest adding an option such as `exclusive: boolean` to `BucketDeployment` which would simply skip this code: https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-s3-deployment/lib/bucket-deployment.ts#L413-L466

Correct me if I'm wrong but I think it's all that is needed to prevent the stack where the bucket lives to be updated for users in our cases who knows that an overlap isn't possible.
