### ISSUE TITLE
[ECS] Cluster.AddCapacity recreating ASG often

### ISSUE THREAD

**Issue by nikola197** [aws/aws-cdk#9705] opened 2020-08-14 16:47 UTC
### The Question
Why this snippet often recreate ECS ASG?

```python
        self.ecs_cluster = ecs.Cluster(self, 'EcsCluster',
                                                        cluster_name=f'ecs-cluster-{params.env}',
                                                        container_insights=True,
                                                        vpc=self.vpc)
        app_subnets = ec2.SubnetSelection(subnets=self.vpc.private_subnets,
                                                                   availability_zones=self.vpc.availability_zones,
                                                                   one_per_az=True)
        ecs_ec2_type = ec2.InstanceType(instance_type_identifier=params.ecs_ec2_instance_type)
        ecs_ami = ecs.EcsOptimizedAmi(generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2,
                                                             hardware_type=ecs.AmiHardwareType.STANDARD)
        self.ecs_asg = self.ecs_cluster.add_capacity('EcsAsg',
                                                                                can_containers_access_instance_role=True,
                                                                                associate_public_ip_address=False,
                                                                                health_check=aws_as.HealthCheck.ec2(grace=core.Duration.minutes(1)),
                                                                                key_name=params.ec2_key_pair_name,
                                                                                resource_signal_count=0,
                                                                                vpc_subnets=app_subnets,
                                                                                instance_type=ecs_ec2_type,
                                                                                machine_image=ecs_ami,
                                                                                desired_capacity=params.ecs_cluster_desired_size,
                                                                                min_capacity=params.ecs_cluster_min_size,
                                                                                max_capacity=params.ecs_cluster_max_size)
```

### Environment

  - **CDK CLI Version:** 1.53.0
  - **Module Version:** 1.53.0
  - **Node.js Version:** 12.16.1
  - **OS:** Ubuntu
  - **Language (Version):** Python 3.7.6

**Comment by SoManyHs** [comment] 2021-05-10 23:05
Hi @nikola197, sorry for the delay in response. Are you still experiencing this issue? What do you mean by recreating the ASG often?

**Comment by nikola197** [comment] 2021-05-18 12:13
Hi @SoManyHs,

I am not eorking on that project anymore.

But the situation was like that:
- I would deploy and it worked.
- After a few revisions and deploys (new resources) it would pop error that ASG needs to be recreated even though it was not changed.-

**Comment by peterwoodworth** [comment] 2021-08-04 23:11
Hmm, I'm unable to reproduce this. If you come back to this project and are still experiencing the issue, feel free to open up a bug report. Since you're not working on the project anymore I will close this issue.

**Closed by peterwoodworth** 2021-08-04 23:11 UTC
Labels: @aws-cdk/aws-ecs, guidance, needs-reproduction
