### ISSUE TITLE
(cli): Mac Homebrew-installed Node interferes with Python CDK applications

### ISSUE THREAD

**Issue by whoami-defnotme** [aws/aws-cdk#15813] opened 2021-07-29 08:38 UTC
### Bug

I have a basic Python CDK application with all the dependencies installed inside a Python virtual env. From the CLI while inside the virtual env, I can `cdk synth` my app successfully and `cdk deploy` correctly starts the deployment process. However, using a `cdk-deploy-to` script from [here](https://docs.aws.amazon.com/cdk/latest/guide/environments.html), which calls `npx cdk deploy`, I get the following error:

```
Traceback (most recent call last):
  File "/REMOVED/app.py", line 4, in <module>
    from aws_cdk import (
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1
```

Calling `npx cdk deploy` yields the same error. Somehow invoking `cdk` through `npx` is using a different environment.

### Environment

  - **CDK CLI Version:** `1.116.0 (build d04661d)`
  - **Node.js Version:** `v14.13.1`
  - **OS               :** `macOS 11.5.1`
  - **Language (Version):** `Python 3.7`

--- 

This is :bug: Bug Report

**Comment by whoami-defnotme** [comment] 2021-08-02 07:54
Felt like this might be a Node issue, so I filed [this](https://github.com/nodejs/node/issues/39625) as well.

**Comment by whoami-defnotme** [comment] 2021-08-03 03:51
Bone-headedly filed that mentioned Node issue in the wrong repo. Now it's [here](https://github.com/npm/cli/issues/3599).

**Comment by peterwoodworth** [comment] 2021-08-06 20:45
I can't reproduce this when following the same steps as you @whoami-defnotme, have you been able to reproduce this on a fresh build?

**Comment by whoami-defnotme** [comment] 2021-08-14 03:25
@peterwoodworth - I'll try to repro again this week but this has been a persistent issue for me even after upgrades or in new projects.

**Comment by peterwoodworth** [comment] 2021-08-16 05:11
If it's persistent for you no need to try and repro again. I'll set some time this week to try and reproduce it again

**Comment by peterwoodworth** [comment] 2021-08-16 21:20
I'm still unable to reproduce this. Am I trying to reproduce this properly?

1. `cdk init --language python`
2. Start virtual environment
3. install dependencies
4. Run the following script:
```sh
#!/usr/bin/env bash
if [[ $# -ge 2 ]]; then
    export CDK_DEPLOY_ACCOUNT=$1
    export CDK_DEPLOY_REGION=$2
    shift; shift
    npx cdk deploy "$@"
    exit $?
else
    echo 1>&2 "Provide account and region as first two args."
    echo 1>&2 "Additional args are passed through to cdk deploy."
    exit 1
fi
```

After running this script am I expected to run into the error you posted?
```
Traceback (most recent call last):
  File "/REMOVED/app.py", line 4, in <module>
    from aws_cdk import (
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1
```

**Comment by mgrabenstein** [comment] 2021-12-10 00:35
@peterwoodworth I am running into the same issue. I get the error after running your bash script above:
$ bash cdk_script.sh 1234567890 "us-east-2"                   
Traceback (most recent call last):
  File "/<path>/app.py", line 4, in <module>
    from aws_cdk import core as cdk
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1

Currently have 
$ cdk --version    
1.134.0 (build dd5e12d)

Python:
aws-cdk.core                        1.134.0

Tried python 3.8.11 and 3.10.

Trying on my Macbook pro M1x:
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559

Also the generated app.py has these lines:
`...
from aws_cdk import core as cdk

# For consistency with TypeScript code, `cdk` is the preferred import name for
# the CDK's core module.  The following line also imports it as `core` for use
# with examples from the CDK Developer's Guide, which are in the process of
# being updated to use `cdk`.  You may delete this import if you don't need it.
from aws_cdk import core

app = core.App()
...`

**Comment by peterwoodworth** [comment] 2021-12-10 00:52
The second import is there by default - Here's our init template for python (with a comment explaining why there are two imports) https://github.com/aws/aws-cdk/blob/42cf1861c1b493be7fd5ec0d6d7e8fc64987cacd/packages/aws-cdk/lib/init-templates/v1/app/python/%25name.PythonModule%25/%25name.PythonModule%25_stack.template.py#L1-L10

Thanks for pinging me and letting me know, I've reopened the issue. I'll attempt to reproduce again

**Comment by mgrabenstein** [comment] 2021-12-10 00:53
What you read comments?
lol

**Comment by mgrabenstein** [comment] 2021-12-10 00:56
Also had CDK v2.1.0 installed. Not your exact steps, but received the error on that as well.

**Comment by kbakk** [comment] 2021-12-10 20:01
I am able to reproduce this as well (seeing the same on Ubuntu and MacOS – both `2.1.0 (build f4f18b1)` and `1.134.0 (build dd5e12d)`).

```
$ which python
/root/cdk_workshop/.venv/bin/python
$ npx cdk@2.x ls
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import aws_cdk as cdk
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error
```

If I `deactivate` the venv, and do `pip install` (to the non-venv Python, not really a workaround) and runs `cdk ls`, it works. If I again do `source .venv/bin/activate` and run `cdk ls` I still see the error. Not quite sure what's going on.

**Comment by kbakk** [comment] 2021-12-10 20:20
Reproducer with Docker:

```
# start a docker container
docker run --rm -it --workdir /cdk_workshop python:3.9-bullseye bash
# past this:

curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
python3 --version
node --version
npx -y cdk@2 --version
npx cdk@2 init sample-app --language python
. .venv/bin/activate
which python3
npx cdk@2 ls
```

**Comment by mgrabenstein** [comment] 2021-12-11 06:33
@kbakk , @peterwoodworth ,
I think there are two issues here. One Kristoff has found the best reproducer for. Which is the venv is not being respected by CDK. 

Which I am seeing as well through a different set of events. For MacOS, I am using brew to install. I have used it to install miniforge (v3.9) and have built all the packages there. I later installed yamllint which requires python 3.10. Brew installs that along with it. It does not update the preferred python v3.9. 
Everywhere I inspect for the version of python to find in the PATH shows v3.9 is being used.
Adding this above the import to aws_cdk in app.py:
```
import sys
print(sys.path)
```
Then running cdk bootstrap ... Shows the python path to be 3.10. 
Whatever Node or CDK is using to determine the appropriate Python is failing and picking the latest, which is not the primary in my case.

Kristoff, if you add those lines to the app.py in your reproduction do you see the include path you expect, or a different Python path that is installed?
I am expecting the latter.

**Comment by peterwoodworth** [comment] 2021-12-13 21:33
Thanks for the reproducer @kbakk and your investigation @mgrabenstein, it's very much appreciated.

I'm not sure if there's anything the CDK can do about this, it seems to me like this is a Python venv and npx issue. @rix0rrr what do you think might be causing this?

**Comment by krzysztof-slowinski** [comment] 2021-12-16 08:33
I have the same issue running with node `v16.13.1` - I downgraded to `v14.18.2` where it works.

**Comment by kbakk** [comment] 2021-12-16 15:01
I'm wondering if I missed a step in the reproducer, that's causing this issue – `pip install -r requirements.txt`. 

Changing to this, it works:

```
curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
npx cdk@2 init sample-app --language python
. .venv/bin/activate
which python3
pip install -r requirements.txt  # <-----
npx -y cdk@2 ls
```

Output:

```
<snip>
cdk-workshop
```

**Comment by kbakk** [comment] 2021-12-17 21:27
I am still seeing this on MacOS though. 

Added `import sys;print(sys.path)` as suggested by @mgrabenstein above, got this:

```
cdk ls
['/Users/krisb/Code/temp/cdk_workshop', '/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python310.zip', '/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10', '/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages']
Traceback (most recent call last):
  File "/Users/krisb/Code/temp/cdk_workshop/app.py", line 4, in <module>
    import aws_cdk as cdk
ModuleNotFoundError: No module named 'aws_cdk'
Subprocess exited with error 1
```

Found a workaround with `export PYTHONPATH=<absolute path to .venv parent>/.venv/lib/python3.10/site-packages`.  I've added this to the `.venv/bin/activate` script. 

It then works:

```
cdk ls
CdkWorkshopStack
```

**Comment by kbakk** [comment] 2021-12-17 21:51
Playing some more around with this, I tried changing cdk.json:

```diff
-  "app": "python3 app.py",
+  "app": "python app.py",
```

That results in `cdk ls` working as well. 

Finding this a bit strange, as this command works:

```
python3 -c 'import aws_cdk; print(aws_cdk)'
<module 'aws_cdk' from '/Users/krisb/Code/temp/cdk_workshop/.venv/lib/python3.10/site-packages/aws_cdk/__init__.py'>
```

Vastly prefer this over the other workaround I mention above. Curious if this works for others here.

**Comment by kbakk** [comment] 2021-12-17 22:54
Changed the cdk executable (`$(which cdk)`) to include
```diff
#!/usr/bin/env node
+  console.log("PATH: " + process.env.PATH);
require('./cdk.js');
```

Output of `cdk ls`: `PATH: /usr/local/opt/python@3.10/bin:/usr/local/Cellar/node@16/16.13.1/bin:/Users/krisb/Code/temp/cdk_workshop/.venv/bin:.<snip>`. 

The output is the same when running `node -e "console.log(process.env.PATH)"`. So this doesn't seem to be caused by the CDK CLI, but rather Node. 

Node on my MacOS is managed via Brew:

```
ls -l $(which /usr/local/bin/node)
lrwxr-xr-x  1 krisb  admin  34 Dec 10 19:58 /usr/local/bin/node -> ../Cellar/node@16/16.13.1/bin/node
```

I guess it's some brew magic going on here:

```
cat $(which /usr/local/bin/node)
#!/bin/bash
PATH="/usr/local/opt/python@3.10/bin:/usr/local/Cellar/node@16/16.13.1/bin:${PATH}" exec "/usr/local/Cellar/node@16/16.13.1/libexec/node"  "$@"
```

**Comment by automartin5000** [comment] 2021-12-19 07:19
> Playing some more around with this, I tried changing cdk.json:
> 
> ```diff
> -  "app": "python3 app.py",
> +  "app": "python app.py",
> ```
> 
> That results in `cdk ls` working as well.
> 
> Finding this a bit strange, as this command works:
> 
> ```
> python3 -c 'import aws_cdk; print(aws_cdk)'
> <module 'aws_cdk' from '/Users/krisb/Code/temp/cdk_workshop/.venv/lib/python3.10/site-packages/aws_cdk/__init__.py'>
> ```
> 
> Vastly prefer this over the other workaround I mention above. Curious if this works for others here.

This worked for me too. I was having this problem with both using `npx cdk synth` and just `cdk synth`.
Running:
M1 Pro MacBook Pro
Node 16
Homebrew Python 3.10
Python venv

**Comment by kbakk** [comment] 2021-12-19 17:24
@automartin5000 you may have some luck changing from `python3` to `.venv/bin python3` instead.

**Comment by automartin5000** [comment] 2021-12-19 18:03
> @automartin5000 you may have some luck changing from `python3` to `.venv/bin python3` instead.

Ok, yeah, setting app.py to `.venv/bin/python3` does work.

**Comment by kbakk** [comment] 2021-12-19 21:22
I assume you use brew managed node? I think this is caused by the way brew installs node.

So you have some options:

- Remove the modification to PATH in `/usr/local/bin/node` done by the brew install script (tested with  node v16.x, not sure what this potentially breaks)
- Don't use the brew installed node, install via nvm or some other tools (haven't tested)

**Comment by automartin5000** [comment] 2021-12-21 22:15
Thanks @kbakk! Just decided to use a standard Node 16 install for now instead of a brew managed one.

**Comment by kbakk** [comment] 2022-01-16 18:37
It looks like this has been resolved in the Homebrew issue tracker – https://github.com/Homebrew/homebrew-core/issues/92116, via commit https://github.com/Homebrew/homebrew-core/commit/4d2c0d05743627f01d3ca9dbfc6f298c4906e12b. 

Tried upgrading node@16 and running:

```
cdk init sample-app --language python
source .venv/bin/activate
pip install -r requirements.txt
cdk ls
```

It now works 🙂

**Comment by automartin5000** [comment] 2022-01-16 23:09
Just tried it and it seems to be working for me too.

**Comment by peterwoodworth** [comment] 2022-01-18 19:25
Seems like the root of the issue has been fixed via homebrew, please ping me if anyone continues to experience this issue

**Closed by peterwoodworth** 2022-01-18 19:25 UTC
Labels: bug, p2, package/tools, effort/medium
