### ISSUE TITLE
Trigger: Token strings not resolving

### ISSUE THREAD

**Issue by Daniel-ZA** [aws/aws-cdk#28017] opened 2023-11-15 22:14 UTC
### Describe the bug

Hi Team,

Just opening this ticket where the "Token" strings are not resolving during deployment and stays as "Token" strings `${Token[TOKEN.664]}`. This results in the error below:

```
 "3 validation errors detected: Value '${Token[TOKEN.664]}' at 'tags.1.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]*;
```

The error above is thrown against the "AWS::IAM::Role" which the `Trigger` construct creates because the value of its tag is a token string `${Token[TOKEN.664]}` which did not resolve during deployment and is not a valid value for a Tag.

For context, the setup here is that stack-level tags are being applied to the resources in the CDK stack (see code below) where its Tag value is retrieved from a resolvable token SSM parameter.

```
    const stringValue = ssm.StringParameter.fromStringParameterAttributes(this, 'MyValue', {
      parameterName: 'StringParameter',
      // 'version' can be specified but is optional.
    }).stringValue;

    const func = new lambda.Function(this, 'MyFunction', {
      handler: 'index.handler',
      runtime: lambda.Runtime.NODEJS_18_X,
      code: lambda.Code.fromInline('foo'),
    });
    
    const trigger = new triggers.Trigger(this, 'MyTrigger', {
      handler: func,
      timeout: cdk.Duration.minutes(10),
      invocationType: triggers.InvocationType.EVENT,
    });

    # Apply stack-level tags where value come from the SSM parameter
    cdk.Tags.of(this).add("test", stringValue)

```

The value of these tags come from an SSM parameter `stringValue` which is a resolvable token. This error seems to occur when creating the IAM role that the parent construct `Trigger` creates:

        * AWS::IAM::Role
        * AWS::Lambda::Version
        * AWS::Lambda::Function
        * Custom::Trigger

Comparing this with a similar parent construct `AwsCustomResource`, the token strings are resolving during deployment and the tags are appropriately propagating to its child resources (AWS::IAM::Role, AWS::Lambda::Function).

```
    const stringValue = ssm.StringParameter.fromStringParameterAttributes(this, 'MyValue', {
      parameterName: 'StringParameter',
      // 'version' can be specified but is optional.
    }).stringValue;

    const getParameter = new cr.AwsCustomResource(this, 'GetParameter', {
      onUpdate: { // will also be called for a CREATE event
        service: 'SSM',
        action: 'getParameter',
        parameters: {
          Name: 'my-parameter',
          WithDecryption: true,
        },
        physicalResourceId: cr.PhysicalResourceId.of(Date.now().toString()), // Update physical id to always fetch the latest version
      },
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
        resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
      }),
    });

    cdk.Tags.of(this).add("test", stringValue)
```

Hence, I'm presuming there is an issue with the `Trigger` construct such that token strings passed to its child resources are not resolving during deployment. I also noticed within the template that the "Tags" are not propagating to the child resources (Role, Lambda Function) during synthesis when compared to `AwsCustomResources` where "Tags" are visible in the synthesized template.

I also did some additional testing and this time just passing tag values as a simple string instead of SSM parameters and the deployment went through for `Trigger` and propagated the tags to the child resources but this wasn't still visible in the template.

Are you able to give me an idea to why this happens, perhaps there is a gap with the `Trigger` construct? Is this a bug?

### Expected Behavior

Token strings of stack-level tags applied on child resources of Trigger not resolved during deployment

### Current Behavior

Token strings of stack-level tags applied on child resources of Trigger to be resolved during deployment

### Reproduction Steps

-

### CDK CLI Version

2.88.0

### Node.js Version

v18.7.0

### OS

Windows

### Language

TypeScript

### Language Version

TypeScript

**Comment by pahud** [comment] 2023-11-16 21:25
Yes I can reproduce this but can't find the root cause off the top of my head. We'll review this issue in the next few days.

**Comment by sheridansmall** [comment] 2023-12-21 09:50
I get the same issue adding the parameter `cleanup=aws_synthetics.Cleanup.LAMBDA` to `aws_synthetics.Canary()` with a tag added from a SSM parameter.

**Comment by aodale** [comment] 2024-04-12 03:12
Any updates on this issue version 2.137


 Member must satisfy regular expression pattern:


 CREATE_FAILED        | AWS::IAM::Role                            | Custom::S3AutoDeleteObjectsCustomResourceProvider/Role (CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092) Resource handler returned message: "1 validation error detected: Value '${Token[AWS.Region.11]}' at 'tags.3.member.value' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{Z}\p{N}_.:/=+\-@]* (Service: Iam, Status Code: 400, ...)

**Comment by comcalvi** [comment] 2024-09-12 22:35
This is not an issue with triggers, it's a duplicate of https://github.com/aws/aws-cdk/issues/29424. 

The culprit is

```
cdk.Tags.of(this).add("test", stringValue)
```

The `this` references the entire stack, meaning that this gets added as a stack tag. The problem is that stack tags cannot be resolved by CloudFormation, because they are passed over the SDK call as parameters to `UpdateStack` or `CreateStack`. The CLI makes that call, which means it would have to resolve that token; but it can't, only CFN does that (outside of hotswapping), so this will not work.

**Comment by comcalvi** [comment] 2024-09-12 22:37
You can reference the SSM parameter value in a tag if you apply it at the construct level, and not on the stack itself.

**Comment by comcalvi** [comment] 2024-09-12 22:39
We also can't throw an error here, because users could have unresolved stack tags on stacks that have resources that happen to allow unresolved tokens.

**Comment by rix0rrr** [comment] 2024-09-13 11:51
The behavior of stack tags is undesirable. Let's fix it.

**Closed** 2024-09-25 13:22 UTC
Labels: bug, p1, @aws-cdk/core, effort/medium, @aws-cdk/triggers
