### ISSUE TITLE
"Error: EOF: end of file, read" in jsii after upgrading aws cdk to 1.71.0

### ISSUE THREAD

**Issue by jorgenfroland** [aws/aws-cdk#11232] opened 2020-10-31 07:43 UTC
Hi,

After upgrading aws cdk to 1.71.0 I started getting the error below from jsii.

### Reproduction Steps

Upgrade aws cdk to 1.71.0. It will install version 1.14.0 of jsii which it depends on.

Trying to downgrade jsii to version 1.13.0 with aws cdk 1.71.0 returns:

`aws-cdk-core 1.71.0 depends on jsii<2.0.0 and >=1.14.0`

_(jsii 1.14.0 was released on 29th of Oct 2020)_

### What did you expect to happen?

I expected bootstrap to complete without errors.

### What actually happened?

```
(.env) PS C:\Users\jfroland\Documents\code\cdk\push-app-stats> cdk bootstrap
C:\Users\jfroland\Documents\code\cdk\push-app-stats\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13295
                    throw e;
                    ^

Error: EOF: end of file, read
    at Object.readSync (fs.js:568:3)
    at SyncStdio.readLine (C:\Users\jfroland\Documents\code\cdk\push-app-stats\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13278:33)
    at InputOutput.read (C:\Users\jfroland\Documents\code\cdk\push-app-stats\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13203:34)
    at KernelHost.run (C:\Users\jfroland\Documents\code\cdk\push-app-stats\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13021:32)
    at Immediate.<anonymous> (C:\Users\jfroland\Documents\code\cdk\push-app-stats\.env\lib\site-packages\jsii\_embedded\jsii\jsii-runtime.js:13029:37)
    at processImmediate (internal/timers.js:456:21) {
  errno: -4095,
  syscall: 'read',
  code: 'EOF'
}
 ⏳  Bootstrapping environment aws://<account_id>/<region>...
CDKToolkit: creating CloudFormation changeset...
 ✅  Environment aws://<account_id>/<region> bootstrapped (no changes).
(.env) PS C:\Users\jfroland\Documents\code\cdk\push-app-stats>
```

### Environment

  - **Framework Version:** 1.71.0
  - **Node.js Version:** v12.18.3
  - **OS               :** Win10
  - **Python (Version):** 3.6.8

### Other

--- 

This is :bug: Bug Report

**Comment by jorgenfroland** [comment] 2020-10-31 07:46
A temporary workaround is to downgrade aws cdk to 1.70.0 and jsii to 1.13.0.

**Comment by paujim** [comment] 2020-10-31 21:19
I get the same error after the upgrade (1.71.0)

**Comment by nbmha1** [comment] 2020-11-03 18:23
Also seeing this.  However, I noticed that if I removed my import of `pydantic` (above 1.5.0) it went away.

**Comment by RomainMuller** [comment] 2020-11-06 08:55
Can you confirm whether this is still an issue? There was a problem with Python 3.6 (see #11255) in `jsii 1.14.0` which has been fixed in. `jsii 1.14.1`. This might be what caused your problems here.

**Comment by MrMoose** [comment] 2020-11-06 12:27
I have this issue as well and just tested it with jsii 1.14.1 and cdk 1.72.0 on windows.

The problem still occurs and doesn't seem to be fixed.

**Comment by crudemandarin** [comment] 2020-11-06 21:24
Experiencing the same issue. I downgraded to aws-cdk to 1.70.0 and jsii to 1.13.0, however I get the following message:

`ERROR: constructs 3.2.15 has requirement jsii<2.0.0,>=1.14.1, but you'll have jsii 1.13.0 which is incompatible.`

Problem is not fixed

**Comment by paujim** [comment] 2020-11-06 22:30
> Can you confirm whether this is still an issue? There was a problem with Python 3.6 (see #11255) in `jsii 1.14.0` which has been fixed in. `jsii 1.14.1`. This might be what caused your problems here.

I still see the issue in cdk 1.72.0 (windows) and python 3.8

**Comment by jorgenfroland** [comment] 2020-11-07 14:48
> Can you confirm whether this is still an issue? There was a problem with Python 3.6 (see #11255) in `jsii 1.14.0` which has been fixed in. `jsii 1.14.1`. This might be what caused your problems here.

I also see the issue using cdk 1.72.0, jsii version 1.14.1 and Python 3.6.8.

**Comment by RomainMuller** [comment] 2020-11-09 09:24
The `Error: EOF: end of file, read` is in fact caused by incorrect (in light of the documentation) behavior of `fs.readSync` of `node` on Windows, when `STDIN` is wired to a socket (this is the case when `node` is spawned as a sub-process with "piped" IOs).

This is effectively a duplicate of (actually duplicated by, but the other somehow got my attention first) #11314. I'll resolve this as you can follow the proceedings in #11314.

**Closed by RomainMuller** 2020-11-09 09:24 UTC
Labels: bug, jsii, needs-triage, p1
