### ISSUE TITLE
Subnet CIDR ranges can only be retrieved for IPv6 ranges, not for IPv4

### ISSUE THREAD

**Issue by PeterBengtson** [aws/aws-cdk#5716] opened 2020-01-08 16:44 UTC
<img width="348" alt="Screenshot 2020-01-08 at 17 40 40" src="https://user-images.githubusercontent.com/3897/71997456-2d719100-323e-11ea-9ce7-c44576f4fdc6.png">

It's possible to retrieve the IPv6 CIDR ranges, but not any IPv4 CIDR ranges. 

### Use Case

Eeeh... Isn't that obvious? Working with NACLs, for instance.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by ialford** [comment] 2020-01-09 14:10
👋 If someone is needed to work on this, I would be happy to give it a shot.

**Comment by SomayaB** [comment] 2020-01-15 22:22
@ialford Go for it! It would be greatly appreciated! 👍

**Comment by rix0rrr** [comment] 2020-01-23 13:11
Duplicate of https://github.com/aws/aws-cdk/issues/3951

**Comment by ialford** [comment] 2020-01-23 13:16
@rix0rrr Do you know if anyone is working on #3951 currently? I don't want to duplicate any efforts but am still comfortable taking a stab at this.

**Comment by SomayaB** [comment] 2020-01-28 00:48
@ialford There doesn't seem to be any PRs out right now addressing this issue. Thanks again for being willing to work on this.

**Closed** 2020-08-12 12:38 UTC
Labels: @aws-cdk/aws-ec2, duplicate, effort/medium, feature-request
