### ISSUE TITLE
(aws-rds): Unable to use CfnParameter as port

### ISSUE THREAD

**Issue by Lewenhaupt** [aws/aws-cdk#17948] opened 2021-12-10 12:02 UTC
### What is the problem?

CfnParameters cannot be used for the port value of a DatabaseInstance in aws-rds. The value requires only a number and valueAsNumber on a CfnParameter doesn't produce a valid number on synthesis.
`"Port": "-1.8881545897088186e+289"`
instead of
`"ToPort": {
          "Ref": "DBPort"
        }` (as it becomes for a security group)
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseInstance.html

### Reproduction Steps

```ts
const dbPort = new CfnParameter(this, 'DBPort', {
  type: 'Number',
  default: 5432
})

const postgresDb = new rds.DatabaseInstance(this, 'PostgresDb', {
      port: dbPort.valueAsNumber,
})
```

### What did you expect to happen?

Expected that the generated cfn-template would have the port parameter as a reference to the cfn parameter

### What actually happened?

The port parameter was set to a static value: -1.8881545897088186e+289

### CDK CLI Version

2.0.0 (build 4b6ce31)

### Node.js Version

v16.9.1

### OS

mac os

### Language

Typescript

**Comment by skinny85** [comment] 2021-12-10 21:35
@ryparker you want to try and reproduce this one?

**Comment by skinny85** [comment] 2021-12-10 22:47
Thnx!

**Comment by jumic** [comment] 2021-12-11 09:44
From my point of view, this is caused by `props.port?.toString()` in [Instances.ts](https://github.com/aws/aws-cdk/blob/4e7a2758eec6999aee5432b3e9e6bbe7626a2d6b/packages/%40aws-cdk/aws-rds/lib/instance.ts#L749). We should replace it by `Tokenization.stringifyNumber(props.port)`.

@skinny85 Are you working on it (because this issue is assigned to you)? If not, I can fix it and submit a PR.

**Comment by skinny85** [comment] 2021-12-13 05:36
That would be awesome if you could work on this @jumic!

**Closed** 2021-12-15 00:30 UTC
Labels: bug, p1, @aws-cdk/aws-rds, effort/small
