### ISSUE TITLE
(ecr-assets): confusing docs on  Grant Permissions to DockerImageAsset

### ISSUE THREAD

**Issue by davidhessler** [aws/aws-cdk#11859] opened 2020-12-03 20:16 UTC
Link to reference doc page: [aws-ecr-assets.DockerImageAsset](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecr-assets.DockerImageAsset.html#repositoryspan-classapi-icon-api-icon-experimental-titlethis-api-element-is-experimental-it-may-change-without-noticespan)

Describe your issue: 

It is not clear how to grant permissions to a `DockerImageAsset`.  Buried in the python comments is the following remark:

```
### Pull Permissions

Depending on the consumer of your image asset, you will need to make sure
the principal has permissions to pull the image.

In most cases, you should use the `asset.repository.grantPull(principal)`
method. This will modify the IAM policy of the principal to allow it to
pull images from this repository.

If the pulling principal is not in the same account or is an AWS service that
doesn't assume a role in your account (e.g. AWS CodeBuild), pull permissions
must be granted on the **resource policy** (and not on the principal's policy).
To do that, you can use `asset.repository.addToResourcePolicy(statement)` to
grant the desired principal the following permissions: "ecr:GetDownloadUrlForLayer",
"ecr:BatchGetImage" and "ecr:BatchCheckLayerAvailability".
"""
``` 

For cases where task definitions cannot be create in CDK (for example they are created later by lambda), it is still beneficial to declare the container in CDK.  Especially with CDKPipelines now in preview.

This language is found at the Overview level, however, a nod in the class page would be helpful or we could alias the function.

```python
def grant_pull(self, grantee: aws_cdk.aws_iam.IGrantable) -> aws_cdk.aws_iam.Grant:
   self.repository.grant_pull(grantee)
```

---

This is a 📕 documentation issue

**Comment by eladb** [comment] 2020-12-08 10:01
Sounds like adding `grantPull` to `DockerImageAsset` should be fairly straightforward. Contributions are welcome!

**Comment by eladb** [comment] 2021-03-02 13:28
Duplicate of #13327

**Closed by eladb** 2021-03-02 13:28 UTC
Labels: @aws-cdk/aws-ecr-assets, documentation, effort/small, feature-request, good first issue, p2
