### ISSUE TITLE
There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer

### ISSUE THREAD

**Issue by vbudilov** [aws/aws-cdk#7327] opened 2020-04-13 04:15 UTC
I'm trying to reuse the same ALB for two Fargate services but I'm getting the following exception whenever I declare the second **ApplicationLoadBalancedFargateService** :

_There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer_

Whenever I remove the second ApplicationLoadBalancedFargateService declaration and rerun the cdk commands everything works as it should. 

Also, when I remove `.loadBalancer(lb)` and include the second `ApplicationLoadBalancedFargateService` then everything works as well, but 2 ALBs are declared. 

Am I implementing this correctly or is this a bug? 

### Reproduction Steps

```
   public EcsFargateStack(final Construct scope, final String id, final StackProps props) throws IOException {
        super(scope, id, props);
        Vpc vpc = Vpc.Builder.create(this, "TickerVPC")
                .build();

        Cluster cluster = Cluster.Builder.create(this, "TickerFargateCluster")
                .clusterName("TickerFargateCluster")
                .build();

        ApplicationLoadBalancer lb =
                ApplicationLoadBalancer.Builder.create(this, "TickerALB")
                        .vpc(vpc)
                        .internetFacing(Boolean.TRUE)
                        .loadBalancerName("ticker")
                        .build();

        // Create a load-balanced Fargate service and make it public
        albService = ApplicationLoadBalancedFargateService.Builder.create(this, "MyFargateService")
                .cluster(cluster)           // Required
                .cpu(512)                   // Default is 256
                .desiredCount(2)            // Default is 1
                .loadBalancer(lb)
                .serviceName("TickerService")
                .taskImageOptions(ApplicationLoadBalancedTaskImageOptions.builder()
                        .image(ContainerImage.fromRegistry("amazon/amazon-ecs-sample"))
                        .build()
                )
                .memoryLimitMiB(1024)       // Default is 512
                .publicLoadBalancer(true)   // Default is false
                .build();

        albService2 = ApplicationLoadBalancedFargateService.Builder.create(this, "MyFargateService2")
                .cluster(cluster)           // Required
                .cpu(512)                   // Default is 256
                .desiredCount(2)            // Default is 1
                .loadBalancer(lb)
                .serviceName("TickerService2")
                .taskImageOptions(ApplicationLoadBalancedTaskImageOptions.builder()
                        .image(ContainerImage.fromRegistry("amazon/amazon-ecs-sample"))
                        .build()
                )
                .memoryLimitMiB(1024)       // Default is 512
                .publicLoadBalancer(true)   // Default is false
                .build();

    }
```

### Error Log

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project cdk: An exception occured while executing the Java class. There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer [TickerALB]
[ERROR] Error: There is already a Construct with name 'PublicListener' in ApplicationLoadBalancer [TickerALB]
[ERROR]     at Node.addChild (/tmp/jsii-kernel-3WVeYj/node_modules/constructs/lib/construct.js:420:19)
[ERROR]     at new Node (/tmp/jsii-kernel-3WVeYj/node_modules/constructs/lib/construct.js:32:28)
[ERROR]     at new ConstructNode (/tmp/jsii-kernel-3WVeYj/node_modules/@aws-cdk/core/lib/construct-compat.js:138:28)
[ERROR]     at Object.createNode (/tmp/jsii-kernel-3WVeYj/node_modules/@aws-cdk/core/lib/construct-compat.js:28:42)
[ERROR]     at new Construct (/tmp/jsii-kernel-3WVeYj/node_modules/constructs/lib/construct.js:464:32)
[ERROR]     at new Construct (/tmp/jsii-kernel-3WVeYj/node_modules/@aws-cdk/core/lib/construct-compat.js:26:9)
[ERROR]     at new Resource (/tmp/jsii-kernel-3WVeYj/node_modules/@aws-cdk/core/lib/resource.js:13:9)
[ERROR]     at new BaseListener (/tmp/jsii-kernel-3WVeYj/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/shared/base-listener.js:10:9)
[ERROR]     at new ApplicationListener (/tmp/jsii-kernel-3WVeYj/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.js:23:9)
[ERROR]     at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime12181023463244660700/jsii-runtime.js:8316:19)
[ERROR]     at Kernel._create (/tmp/jsii-java-runtime12181023463244660700/jsii-runtime.js:7853:26)
[ERROR]     at Kernel.create (/tmp/jsii-java-runtime12181023463244660700/jsii-runtime.js:7600:21)
[ERROR]     at KernelHost.processRequest (/tmp/jsii-java-runtime12181023463244660700/jsii-runtime.js:7388:28)
[ERROR]     at KernelHost.run (/tmp/jsii-java-runtime12181023463244660700/jsii-runtime.js:7328:14)
[ERROR]     at Immediate._onImmediate (/tmp/jsii-java-runtime12181023463244660700/jsii-runtime.js:7331:37)
[ERROR]     at processImmediate (internal/timers.js:456:21)

```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

--- 

This is :bug: Bug Report

**Comment by bvtujo** [comment] 2020-04-15 23:02
Hi Vladimir, using the ApplicationLoadBalanced*Service ecs-patterns constructs to share a load balancer is currently out of scope of the pattern. You can work around this quite easily by creating your own service and target group and adding it as a listener target to the listener created by the patterns construct. The following code snippet should illustrate the principle (apologies that this is in typescript; it's the easiest for me to rapidly develop CDK code in)

```typescript
import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';
import * as ecs from '@aws-cdk/aws-ecs';
import * as ec2 from '@aws-cdk/aws-ec2';

// create LB, vpc, cluster, service1 as above

// create our task definition, container, and add port mappings
const taskDefinition = new ecs.FargateTaskDefinition(this, "Service2TaskDef");
const container = taskDefinition.addContainer("Service2Container", {
    image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
    environment: {"MY_ENVIRONMENT_VAR": "FOO"},
    memoryLimitMiB: 1024,
    cpu: 512,
});
container.addPortMappings({containerPort: 80})

// Create a service -- this instance isn't particularly complex, since we only have
// one container image per service that we need to worry about.
// We'll reuse the cluster from our first service but use our newly created
// security group for this purpose.
const service2 = new ecs.FargateService(this, "tickerService2", {
    cluster: cluster,
    taskDefinition: taskDefinition,
    desiredCount: 2,
});

// Set up security group ingress/egress between LB and new service
service2.connections.allowFrom(lb, ec2.Port.tcp(80));
lb.connections.allowTo(service2, ec2.Port.tcp(80));
// Allow connections between services if necessary. 
// albservice.service.connections.allowFrom(service2, ec2.Port.tcp(80));
// albservice.service.connections.allowTo(service2, ec2.Port.tcp(80));

// Create a new target group for the service and add it to the listener, specifying
// a path, host, or IP pattern and a priority.
const tg = new elbv2.ApplicationTargetGroup(this, "service2targetgroup", {
    targets: [service2],
    protocol: elbv2.ApplicationProtocol.HTTP,
    vpc,
});

lbservice.listener.addTargetGroups("targetgroup", {
    targetGroups: [tg],
    pathPattern: "/app2/*",
    priority: 100
});
```

Please let me know if you need any additional information.

**Closed by bvtujo** 2020-04-15 23:02 UTC
Labels: bug, needs-triage, package/ecs-patterns

**Comment by vbudilov** [comment] 2020-04-16 16:08
Here's what it would look like in Java:

```
    public EcsFargateStack(final Construct scope, final String id, final StackProps props) throws IOException {
        super(scope, id, props);
        Number cpu = 512;
        Number memory = 1024;

        Vpc vpc = Vpc.Builder.create(this, "TickerVPC")
                .build();

        ApplicationLoadBalancer alb = ApplicationLoadBalancer.Builder.create(this, "TickerALB")
                .vpc(vpc)
                .internetFacing(Boolean.TRUE)
                .loadBalancerName("ticker")
                .build();

        Cluster cluster = Cluster.Builder.create(this, "TickerFargateCluster")
                .vpc(vpc)
                .clusterName("TickerFargateCluster")
                .build();

        FargateTaskDefinition taskDefinition = new FargateTaskDefinition(this, "TickersTaskDefinition", FargateTaskDefinitionProps.builder()
                .cpu(cpu)
                .memoryLimitMiB(memory)
                .build());

        ContainerDefinition container = taskDefinition.addContainer("DataIngestGatewayContainer", ContainerDefinitionOptions.builder()
                .image(ContainerImage.fromEcrRepository(EcrStack.dataIngestGateway))
                .environment(Map.of("test", "test"))
                .memoryLimitMiB(memory)
                .cpu(cpu)
                .build());
        container.addPortMappings(PortMapping.builder()
                .containerPort(8080)
                .hostPort(8080)
                .protocol(Protocol.TCP)
                .build());
        FargateService tickerGatewayService = new FargateService(this, "TickerGatewayFargateService", FargateServiceProps.builder()
                .cluster(cluster)
                .taskDefinition(taskDefinition)
                .desiredCount(2)
                .serviceName("tickerGatewayService")
                .build());

        tickerGatewayService.getConnections().allowFrom(alb, Port.tcp(80));
        alb.getConnections().allowTo(tickerGatewayService, Port.tcp(8080));

        ApplicationTargetGroup tg = new ApplicationTargetGroup(this, "TickerIngestGatewayTG", ApplicationTargetGroupProps.builder()
                .targets(List.of(tickerGatewayService))
                .port(8080)
                .protocol(ApplicationProtocol.HTTP)
                .vpc(vpc)
                .build());

        alb.addListener("GatewayListener", BaseApplicationListenerProps.builder()
                .port(80)
                .defaultTargetGroups(List.of(tg))
                .build());

    }

```

**Comment by bvtujo** [comment] 2020-04-16 16:53
Thanks for the translation!

The problem is that as implemented, ApplicationLoadBalanced*Service constructs assume that they will be used to spin up all properties of the load balancer, listener, and service target groups. That means that the pattern tries to create a new listener on either port 80 or 443. If the pattern has previously been used to create a listener/target group pair, then subsequent attempts to create a listener will fail, as you saw when you tried to use two ALBFargateServices. 

We'll consider adding this support in the future if there's a demonstrated need not covered by the workaround above, but for the time being the pattern's scope remains creating a single service behind a load balancer, with additional customizations done by the user as above.

**Comment by vbudilov** [comment] 2020-04-16 18:00
Got it. BTW, in my example, how do I set the path for the listener? I can't figure that out for now. The only way I see is to add a target (which allows for the path to be set), but then there would be 2 target groups there and the CDK install would fail. 

```
        listener.addTargets("TickerIngestGatewayTarget", AddApplicationTargetsProps.builder()
                .port(80)
                .pathPatterns(List.of("/ingest"))
                .priority(1)
                .targetGroupName(tickerIngestGatewayTG.getTargetGroupName())
                .healthCheck(HealthCheck.builder()
                        .enabled(true)
                        .path("/ping")
                        .build())
                .build());


```

**Comment by bvtujo** [comment] 2020-04-16 18:47
Hmm, this is a very good question, and one that we need to make some movement on. The ALB*Service constructs don't surface the pathPattern or hostHeader properties of the AddTargetsProps, which would allow you to configure the rule for the first service. 

Not doing this sort of limits the usefulness of this construct as a way to set up initial infrastructure (security groups, lb, listener, service, etc) and I think this will be a pretty useful feature for customers who want to use the patterns to set up their infra with some customization potential. 

I've documented this issue in #7388 and will start work on a fix. 

In the meantime, a possible workaround is to follow the method outlined in [this comment](https://github.com/aws/aws-cdk/issues/7266#issuecomment-614317682) on #7266. this involves creating the ALBService construct using a default container over HTTP with a desired count of 0, adding a new listener on HTTPS, then adding both services via the method above as targets of that listener.

This will allow you to set the path patterns, health check, and priority, and add a listener rule to redirect HTTP/80 traffic to HTTPS:443 on your LB.

**Comment by vbudilov** [comment] 2020-04-16 19:07
Agreed...unless I switch ports I can only register one service so I'm back where I started :)

**Comment by vbudilov** [comment] 2020-04-16 19:08
BTW this is the Stack: https://github.com/vbudilov/aws-cdk-starter/blob/master/src/main/java/com/budilov/cdk/ecs/EcsFargateStack.java

**Comment by vbudilov** [comment] 2020-04-20 02:53
Should I create an issue/feature request for this?

**Comment by bvtujo** [comment] 2020-04-20 15:27
Thanks for the context there. Unfortunately, upon further discussion it seems that the patterns construct was initially conceptualized only as a way to quickly stand up one service behind a load balancer, and because of the complexity involved in already supporting HTTP and HTTPS, EC2 and Fargate, we can't adequately support a multiple service/multiple target group model. 

We currently support a single service/multiple target group model in the *LoadBalancedMultipleTargetGroup*Service constructs.

For your situation, I think the only way to use the pattern as a workaround to rolling your own infrastructure is to deploy the pattern with an HTTP listener and a single 256/256 fargate task, then create an HTTPS listener and add your ingestion apps as target groups behind that listener. 

Alternatively, you could use the code in the constructors of ApplicationLoadBalancedServiceBase and ApplicationLoadBalancedFargateService as an initial template, which you then modify as you like to suit your specific situation.

**Comment by jordanbice** [comment] 2023-10-19 19:29
> Hi Vladimir, using the ApplicationLoadBalanced*Service ecs-patterns constructs to share a load balancer is currently out of scope of the pattern. You can work around this quite easily by creating your own service and target group and adding it as a listener target to the listener created by the patterns construct. The following code snippet should illustrate the principle (apologies that this is in typescript; it's the easiest for me to rapidly develop CDK code in)
> 
> ```ts
> import * as elbv2 from '@aws-cdk/aws-elasticloadbalancingv2';
> import * as ecs from '@aws-cdk/aws-ecs';
> import * as ec2 from '@aws-cdk/aws-ec2';
> 
> // create LB, vpc, cluster, service1 as above
> 
> // create our task definition, container, and add port mappings
> const taskDefinition = new ecs.FargateTaskDefinition(this, "Service2TaskDef");
> const container = taskDefinition.addContainer("Service2Container", {
>     image: ecs.ContainerImage.fromRegistry("amazon/amazon-ecs-sample"),
>     environment: {"MY_ENVIRONMENT_VAR": "FOO"},
>     memoryLimitMiB: 1024,
>     cpu: 512,
> });
> container.addPortMappings({containerPort: 80})
> 
> // Create a service -- this instance isn't particularly complex, since we only have
> // one container image per service that we need to worry about.
> // We'll reuse the cluster from our first service but use our newly created
> // security group for this purpose.
> const service2 = new ecs.FargateService(this, "tickerService2", {
>     cluster: cluster,
>     taskDefinition: taskDefinition,
>     desiredCount: 2,
> });
> 
> // Set up security group ingress/egress between LB and new service
> service2.connections.allowFrom(lb, ec2.Port.tcp(80));
> lb.connections.allowTo(service2, ec2.Port.tcp(80));
> // Allow connections between services if necessary. 
> // albservice.service.connections.allowFrom(service2, ec2.Port.tcp(80));
> // albservice.service.connections.allowTo(service2, ec2.Port.tcp(80));
> 
> // Create a new target group for the service and add it to the listener, specifying
> // a path, host, or IP pattern and a priority.
> const tg = new elbv2.ApplicationTargetGroup(this, "service2targetgroup", {
>     targets: [service2],
>     protocol: elbv2.ApplicationProtocol.HTTP,
>     vpc,
> });
> 
> lbservice.listener.addTargetGroups("targetgroup", {
>     targetGroups: [tg],
>     pathPattern: "/app2/*",
>     priority: 100
> });
> ```
> 
> Please let me know if you need any additional information.

This approach only works if you create the load balancer in the same place that each service is created. My use case is the following:
(1) One sub-repo creates ECS cluster, loadbalancer
(2) N number of sub-repos register their service with existing loadbalancer

This doesn't work because the lookup for a loadbalancer returns an `IApplicationLoadBalancer` which does not include the "allowTo" method that is found on `ApplicationLoadBalancer` type which is returned from the constructor.
