### ISSUE TITLE
Kotlin language support

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk#557] opened 2018-08-14 07:20 UTC
+1 if you would like to see Kotlin support for the CDK

**Comment by digitalsanctum** [comment] 2018-12-04 16:20
I'd like to take a stab at contributing Kotlin support along with Gradle build with Kotlin DSL assuming this work hasn't already started. 

Any pointers other than looking at what was done for Java?

**Comment by digitalsanctum** [comment] 2018-12-06 06:12
I’ve written a POC which uses Kotlin language and Gradle Kotlin DSL: https://github.com/digitalsanctum/cdk-kotlin-example. I don’t think it would take much to add support for Kotlin and Gradle but the wiring up of `cdk.json` and `app.sh` leaves something to be desired.

**Comment by digitalsanctum** [comment] 2018-12-06 15:43
Thanks. I've replied to your questions there. 

The POC was a first step to prove that supporting Kotlin and Gradle wouldn't be a lot of extra effort. I'd like to address #1294 and further simplify the semantics around `app.sh` and `cdk.json` before including as a template for `cdk init`.

**Comment by willings** [comment] 2019-04-03 12:56
I've started one, roughly tested :P
https://github.com/aws-cdk-dsl/aws-cdk-kotlin-dsl

**Comment by eladb** [comment] 2019-04-03 13:22
@willings this is great! Would love to explore the option of adding this to our official release

**Comment by Ramalus** [comment] 2019-08-23 03:26
Any news on this? @willings repo looks promising.

**Comment by toliner** [comment] 2019-09-04 02:32
Hi, I'm working on wrapper library of cdk.

Now, no documents are available but all source codes are available:
https://github.com/justincase-jp/AWS-CDK-Kotlin-DSL
And generated & built packages are available too:
https://bintray.com/justincase/aws-cdk-kotlin-dsl

This is WIP project, so any issue comment, or contribution is welcome.

**Comment by nbraid** [comment] 2020-04-28 22:50
Another approach could be leveraging Kotlin's JS compatibility. JetBrains provides [dukat](https://github.com/Kotlin/dukat) to generate Kotlin JS files from TS definitions.

**Comment by codeslubber** [comment] 2020-05-23 21:01
Jesus what happened here?? seemed like it was going to happen, but no... !

**Comment by ethanjdiamond** [comment] 2020-07-03 17:20
Any updates on this?

**Comment by pkrishnath** [comment] 2020-12-06 08:51
Any updates?

**Comment by michaelbrewer** [comment] 2021-04-06 01:55
I have created a cookiecutter template, that I can open source if people are interested (and maybe add it to the CDK templates):

<img width="716" alt="Screen Shot 2021-04-05 at 6 46 57 PM" src="https://user-images.githubusercontent.com/5442469/113647240-4e8e8080-963f-11eb-87b7-30245430bca7.png">

This is what the directory structure looks like, it assumed your `cdk` code is within a larger project:

```
.
├── README.md
├── build.gradle
├── cdk
│   ├── README.md
│   ├── build.gradle
│   ├── cdk.context.json
│   ├── cdk.json
│   └── src
│       ├── main
│       │   └── kotlin
│       │       └── com
│       │           └── fiserv
│       │               └── services
│       │                   └── footie
│       │                       └── cdk
│       │                           ├── app
│       │                           │   └── App.kt
│       │                           └── stack
│       │                               └── ApplicationStack.kt
│       └── test
│           └── kotlin
│               └── com
│                   └── fiserv
│                       └── services
│                           └── footie
│                               └── cdk
│                                   └── stack
│                                       └── ApplicationStackTests.kt
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
└── settings.gradle

21 directories, 14 files
```

* `settings.gradle` - Adds the `cdk` subproject
* `build.gradle` - Is the base project with just the junit5 deps
* `cdk/build.gradle` - Has the CDK deps
* `cdk/cdk.json` - Has some demo properties and the app command to build and run the cdk code.

`cdk/build.gradle`:
```groovy
plugins {
    id "application"
}

def cdkVersion = "1.96.0"
dependencies {
    implementation("org.slf4j:slf4j-simple:1.7.30")

    // AWS Cloud Development Kit
    implementation("software.amazon.awscdk:core:$cdkVersion")

    // Respective AWS Construct Libraries
    implementation("software.amazon.awscdk:iam:$cdkVersion")
    implementation("software.amazon.awscdk:lambda:$cdkVersion")
    implementation("software.amazon.awscdk:dynamodb:$cdkVersion")
    implementation("software.amazon.awscdk:apigateway:$cdkVersion")
}

application {
    mainClassName = 'com.fiserv.services.footie.cdk.app.AppKt'
}
```

`cdk/cdk.json`:
```json
{
  "app": "cd ../; ./gradlew -q cdk:run",
  "context": {
    "branch": "develop",
    "env_dev": {
      "example": "DEMO ENVIRONMENT VARIABLE"
    }
  }
}
```

Example stack.kt
```kotlin
package com.fiserv.services.footie.cdk.stack

import software.amazon.awscdk.core.*
import software.amazon.awscdk.core.Stack

class ApplicationStack(scope: Construct, id: String, props: StackProps? = null) : Stack(scope, id, props) {
    init {
        val environment = this.node.tryGetContext("env") as String? ?: "dev"
        val branch = this.node.tryGetContext("branch") as String? ?: "develop"
        val namespace = "$environment${if (branch == "master") "" else "-$branch"}"
        @Suppress("UNCHECKED_CAST")
        val settings = this.node.tryGetContext("env_$environment") as Map<String, String>? 
            ?: throw RuntimeException("settings needs to be configured for $environment")

        // NOTE: Example of getting a environment config value from the cdk.json
        val example = settings.requireNotNull("example")
        CfnOutput(
                this,
                "ExampleOutput",
                CfnOutputProps
                        .builder()
                        .exportName("example-variable-$namespace")
                        .value(example)
                        .description("Example variable you can show or share for this stack: $namespace")
                        .build()
        )
    }

    private fun Map<String, String>.requireNotNull(name: String) = requireNotNull(this[name]) {
        "'$name' needs to be configured in cdk.json"
    }
}
```

**Comment by michaelbrewer** [comment] 2021-04-06 02:01
Btw. what @willings is the best I have seen for CDK, I hold AWS takes this on,.

**Comment by luistrigueiros** [comment] 2022-01-03 21:43
Yes this is great idea, a fluent Kotlin DSL for CDK would be great

**Comment by ecejmsr** [comment] 2022-01-09 06:53
+1 I just got “done” working on a stack that I’ve been at it for like… 6 months? TS isn’t bad once I got used to it. Kotlin would be nice. Would compile/run times times be relatively slower or faster than TS? Would auto scaling be impacted?

**Comment by luistrigueiros** [comment] 2022-01-09 11:26
I agree that TS is not bad alternative, my preference for Kotlin comes from the fact that:

1. Kotlin has excellent, support of internal DSL's, but I have doubt whether this is possible with the current infrastructure for code generation from JSII as the code generation would have to be done in a way that makes possible to leverage  Kotlin's idioms like type safe builders [https://kotlinlang.org/docs/type-safe-builders.html] an interesting example is of what is possible with Kotlin is this one [https://kotlinlang.org/docs/type-safe-builders.html]
2. Another issue with TS and JS ecosystem in general for me is security with NPN/Node.JS I think and the fact that it can easily pull so many packages with full access to filesystem in build infrastructure.

On the last one I think that it would be very interesting if the CDK/TS could run via [https://deno.land/] where there is much better security and sandboxing of JS code.

**Comment by waltervargas** [comment] 2022-11-26 16:06
Is there any update on this?

**Comment by MrArnoldPalmer** [comment] 2023-01-24 20:41
Closing this as a duplicate of https://github.com/aws/jsii/issues/1541

**Closed by MrArnoldPalmer** 2023-01-24 20:41 UTC
Labels: feature-request, effort/large, language/support, feature/new-language
