### ISSUE TITLE
HostedZone: Referencing array attributes cross-stack breaks with Template Format Error

### ISSUE THREAD

**Issue by surecloud-meason** [aws/aws-cdk#22846] opened 2022-11-09 13:41 UTC
### Describe the bug

When referencing a HostedZoneNameServer from another stack the Output created is invalid and on deployment errors with:
"Template format error: Every Value member must be a string."

CDK Synth Cloudformation Snippet Generated:

```
Outputs:
  ExportsOutputFnGetAttprodukdnshostedzone423B3F93NameServers1C276690:
    Value:
      Fn::GetAtt:
        - produkdnshostedzone423B3F93
        - NameServers
    Export:
      Name: prod-uk-dns:ExportsOutputFnGetAttprodukdnshostedzone423B3F93NameServers1C276690
```

### Expected Behavior

The auto created output handles lists correctly for use within another stack.

### Current Behavior

The deploy fails due to an cloudformation format error .

### Reproduction Steps

DNS Stack:

```
import {Construct} from 'constructs';
import {StackProps} from 'aws-cdk-lib';
import {PublicHostedZone} from 'aws-cdk-lib/aws-route53';

export interface DnsStackProps extends StackProps {
    zoneName: string;
}

export class Dns1Stack extends Stack {

    public readonly hostedZone: PublicHostedZone;

    constructor(scope: Construct, id: string, props: DnsStackProps) {
        super(scope, id, props);

        this.hostedZone = new PublicHostedZone(this, `${this.stackName}-hosted-zone`, {
                zoneName: props.zoneName,
            }
        );

    }
}
```

Stack Referencing the above stack

```
import {Construct} from 'constructs';
import {Duration, StackProps} from 'aws-cdk-lib';
import {PublicHostedZone} from 'aws-cdk-lib/aws-route53';

export interface DnsStackProps extends StackProps {
    zoneName: string;
    dnsHostedZone: PublicHostedZone;
}

export class Dns2Stack extends Stack {
    constructor(scope: Construct, id: string, props: DnsStackProps) {
        super(scope, id, props);

        const timeToLiveMinutes = 5;

        new NsRecord(this, `${this.stackName}-prod-env-ns-record-set`, {
            zone: hostedZone,
            recordName: props.dnsHostedZone.zoneName,
            values: props.dnsHostedZone.hostedZoneNameServers as string[],
            ttl: Duration.minutes(timeToLiveMinutes),
        });

    }
}

```

Stack Instantiations

```
const Dns1Stack = new Dns1Stack(app, `dns1`, {
    zoneName: `${deploymentType}.somedomain.com`,
    env: {
        region: 'us-east-1',
    },
});

const Dns2Stack = new Dns2Stack(app, `dns2`, {
    zoneName: 'somedomain.com',
    dnsHostedZone: Dns1Stack.hostedZone,
    env: {
        region: 'us-east-1',
    },
});

```

### CDK CLI Version

2.50.0

### Node.js Version

v16.18.0

### OS

Ubuntu 20.04

### Language

Typescript

**Comment by peterwoodworth** [comment] 2022-11-12 02:13
Thanks for reporting this @surecloud-meason, I was able to reproduce this.

I'm pretty stumped why this is occurring. Everything in the template is formatted correctly, there should be no validation errors occurring here.

I've created a ticket for CloudFormation (P75318355), hopefully they'll be able to help out here. I'll let you know if there are any updates. Thanks!

**Comment by peterwoodworth** [comment] 2022-11-16 21:57
Ah, the issue is due to the result of the output `HostedZone.NameServers` being a list of strings. Here is how the template could look instead:

```
Outputs:
  HZNameServer:
    Value: !Join ["", !GetAtt myHostedZone.NameServers]
```

You could work around this for now by creating your own CfnOutput and referencing it directly in the other stack when needed

**Comment by comcalvi** [comment] 2023-01-05 17:42
Is this still an issue? Pretty sure this has been fixed by #22873

**Comment by peterwoodworth** [comment] 2023-01-05 21:22
Yeah we can probably close this, I tested this prior to the change linked

**Closed by peterwoodworth** 2023-01-05 21:22 UTC
Labels: bug, p1, @aws-cdk/aws-route53, effort/small

**Comment by kbrownlees** [comment] 2024-06-30 21:03
@peterwoodworth I just hit this with the latest version of CDK (2.147.2 (build f4b0897)) FYI. Basically the same setup - create a hosted zone in my main stack and trying to reference .hostedZoneNameServers when creating a `ZoneDelegationRecord` in another Stack.

**Comment by adminy** [comment] 2024-09-10 17:51
![image](https://github.com/user-attachments/assets/2a864fdf-7b17-4f47-9b43-63983bc249fa)

As you can see in the docs @kbrownlees, it says that it will be undefined if its imported by another stack.
