### ISSUE TITLE
[cdk pipelines] CDK - Issue with multiple Stacks within a Stage

### ISSUE THREAD

**Issue by srethira** [aws/aws-cdk#9237] opened 2020-07-23 22:01 UTC
## :question: General Issue

Following this documentation https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/

### The Question

Created a pipeline using CDK Pipelines. Added CDK Stage construct with two Stacks, which worked fine. When additional Stacks added to the Stage, ran into this issue. Any suggestions ?

### Environment

  - **CDK CLI Version:** 1.51.0
  - **Module Version:** 1.51.0
  - **Node.js Version:** v14.5.0
  - **OS:** OSX Mojave
  - **Language (Version):** Python (3.7.3) 

### Other information

Do you wish to deploy these changes (y/n)? y
Pipeline: deploying...
[0%] start: Publishing XXXX-us-east-2
[100%] success: Published:XXXX-us-east-2
Pipeline: creating CloudFormation changeset...
 
❌  Pipeline failed: Error [ValidationError]: Template may not exceed 460800 bytes in size.
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2020-07-23T19:06:19.649Z,
  requestId: '8092251f',
  statusCode: 400,
  retryable: false,
  retryDelay: 590.3288129916684
}

**Template may not exceed 460800 bytes in size.**

**Comment by njlynch** [comment] 2020-07-28 09:22
This is mostly a duplicate of #9066, and a dupe of #9225. Closing this out to track any remainder in #9225.

**Closed by njlynch** 2020-07-28 09:22 UTC
Labels: @aws-cdk/pipelines, guidance
