### ISSUE TITLE
CDK fails to synth CF code

### ISSUE THREAD

**Issue by pasard** [aws/aws-cdk#5275] opened 2019-12-02 18:01 UTC
The CDK CLI fails to run any cdk command ( 'cdk synth', 'cdk ls', ...) for any Python CDK project. See error log.

### Reproduction Steps
1. install CDK (in my case 1.18.0) and Python release (3.7.5 in my case)
2. create a test directory (cdk-test in my case)
3. cd to the test directory
4. run 'cdk init --language python' from the CLI
5. run 'source .env/bin/activate' from the CLI
6. run 'cdk synth' (or 'cdk ls') from the CLI

### Error Log

CDK toolkit version: 1.18.0 (build bc924bc)
Command line arguments: {
  _: [ 'synth' ],
  verbose: true,
  v: true,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  staging: true,
  'no-color': false,
  noColor: false,
  '$0': '/usr/local/bin/cdk'
}
Determining whether we're on an EC2 instance.
Does not look like EC2 instance.
cdk.json: {
  "app": "python3 app.py"
}
cdk.context.json: {
  "@aws-cdk/core:enableStackNameDuplicates": "true"
}
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true
}
Setting "CDK_DEFAULT_REGION" environment variable to eu-west-1
Resolving default credentials
Retrieved account ID <myaccount> from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to <myaccount>
context: {
  '@aws-cdk/core:enableStackNameDuplicates': 'true',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'eu-west-1',
  CDK_DEFAULT_ACCOUNT: '<myaccount>',
  CDK_CONTEXT_JSON: '{"@aws-cdk/core:enableStackNameDuplicates":"true","aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '1.16.0',
  CDK_CLI_VERSION: '1.18.0'
}
data=b'{"name": "@aws-cdk/cx-api", "version": "1.18.0", "tarball": "<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/cx_api/_jsii/cx-api@1.18.0.jsii.tgz", "api": "load"}'
> {"name":"@aws-cdk/cx-api","version":"1.18.0","tarball":"<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/cx_api/_jsii/cx-api@1.18.0.jsii.tgz","api":"load"}
[jsii-kernel] load {
  name: '@aws-cdk/cx-api',
  version: '1.18.0',
  tarball: '<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/cx_api/_jsii/cx-api@1.18.0.jsii.tgz',
  api: 'load'
}
[jsii-kernel] creating jsii-kernel modules workdir: /var/folders/94/7_t2z2cn51dc5y5jdf7kfxcs4hxb8b/T/jsii-kernel-37Oq82
[jsii-kernel] removing staging directory: /var/folders/94/7_t2z2cn51dc5y5jdf7kfxcs4hxb8b/T/jsii-kernel-install-staging-TUMPfz
< {"ok":{"assembly":"@aws-cdk/cx-api","types":29}}
data=b'{"name": "@aws-cdk/core", "version": "1.18.0", "tarball": "<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/core/_jsii/core@1.18.0.jsii.tgz", "api": "load"}'
> {"name":"@aws-cdk/core","version":"1.18.0","tarball":"<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/core/_jsii/core@1.18.0.jsii.tgz","api":"load"}
[jsii-kernel] load {
  name: '@aws-cdk/core',
  version: '1.18.0',
  tarball: '<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/core/_jsii/core@1.18.0.jsii.tgz',
  api: 'load'
}
[jsii-kernel] removing staging directory: /var/folders/94/7_t2z2cn51dc5y5jdf7kfxcs4hxb8b/T/jsii-kernel-install-staging-Z8Lwr8
< {"ok":{"assembly":"@aws-cdk/core","types":108}}
[jsii-kernel] removing install dir /var/folders/94/7_t2z2cn51dc5y5jdf7kfxcs4hxb8b/T/jsii-kernel-37Oq82
auto_synth=None, context=None, outdir=None, runtime_info=None, stack_traces=None, tree_metadata=None
Props=AppProps()
data=b'{"fqn": "@aws-cdk/core.App", "args": [{"$jsii.struct": {"fqn": "@aws-cdk/core.AppProps", "data": {"autoSynth": null, "context": null, "outdir": null, "runtimeInfo": null, "stackTraces": null, "treeMetadata": null}}}], "overrides": [], "interfaces": ["@aws-cdk/core.IConstruct"], "api": "create"}'
internal/fs/utils.js:220
    throw err;
    ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:516:3)
    at SyncStdio.readLine (<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13322:25)
    at InputOutput.read (<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:13272:34)
    at KernelHost.run (<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7228:32)
    at Immediate.<anonymous> (<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:37)
    at processImmediate (internal/timers.js:439:21) {
  errno: -35,
  syscall: 'read',
  code: 'EAGAIN'
}
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    app = core.App()
  File "<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "<mypath>/cdk-test/.env/lib/python3.7/site-packages/aws_cdk/core/__init__.py", line 3445, in __init__
    jsii.create(App, self, [props])
  File "<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 223, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 310, in send
    self._next_message(), _ProcessResponse_R
  File "<mypath>/cdk-test/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 261, in _next_message
    return json.loads(self._process.stdout.readline(), object_hook=ohook)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Subprocess exited with error 1
Error: Subprocess exited with error 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/aws-cdk/lib/api/cxapp/exec.ts:115:23)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:478:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)

### Environment

  - **CLI Version      :** 1.18.0
  - **Framework Version:** 
  - **OS               :** MacOS X Darwin 18.7.0 x86_64
  - **Language         :** 

### Other

--- 

This is :bug: Bug Report

**Comment by nataibi** [comment] 2019-12-02 18:53
Duplicate of #5187 (similar situation , few users reporting the same error code within the syscall)

**Comment by SomayaB** [comment] 2019-12-02 21:32
Closing since it's a duplicate of #5187

**Closed by SomayaB** 2019-12-02 21:32 UTC
Labels: bug, duplicate, language/python, package/tools, status/needs-triage
