### ISSUE TITLE
The cloudformation for event pattern generated by cdk contains 'detailType' while it should generate the key as 'detail-type'

### ISSUE THREAD

**Issue by rookieCoderArpit** [aws/aws-cdk#5703] opened 2020-01-08 02:34 UTC
**Description of the bug**: When i use Cdk the cloudformation template that is generated for the 'event pattern ' in a CfnRule construct contains the key as 'detailType' rather than 'detail-type'

### Reproduction Steps

Use the following in a Cdk stack
  ```
 const cbEventPattern :EventPattern ={

      source: [
          'aws.codebuild'
      ],
      detail: {
          'build-status': [
              'FAILED'
          ],
          'project-name':' some value'
      },      
      detailType: [
        'CodeBuild Build State Change'
    ],

  
  }
    const codeBuildRule = new CfnRule(this, 'CodeBuildCloudWatchEventsRule', {
      description: 'Code Build cloudwatch events rule',
      eventPattern: cbEventPattern,
      name: '',
      state: 'ENABLED'
  })
```

### Environment

  - **CLI Version**      : **1.20.0**
  - **Framework Version**:**0.22**
  - **OS**               :**Windows**
  - **Language**         :**typescript**

### Other

I found the following link 
https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts#L348
although i see a solve is there it does not work.

--- 

This is :bug: Bug Report

**Comment by netroy** [comment] 2020-01-08 14:41
@rookieCoderArpit looks like you are using the incorrect construct.

instead of 
```
import { CfnRule } from '@aws-cdk/aws-events';
...
const codeBuildRule = new CfnRule(this, 'CodeBuildCloudWatchEventsRule', {
  description: 'Code Build cloudwatch events rule',
  eventPattern: cbEventPattern,
  name: '',
  state: 'ENABLED'
})
```

please use the `Rule` construct (which does the remapping, as pointed out by you)
```
import { Rule } from '@aws-cdk/aws-events';
...
const codeBuildRule = new Rule(this, 'CodeBuildCloudWatchEventsRule', {
  description: 'Code Build cloudwatch events rule',
  eventPattern: cbEventPattern,
  ruleName: '',
  enabled: true
});
```

**Comment by SomayaB** [comment] 2020-01-13 19:13
Thanks @netroy! @rookieCoderArpit, did that fix your issue?

**Comment by SomayaB** [comment] 2020-01-22 23:00
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by OzQu** [comment] 2020-12-08 10:21
This is still an issue. I bumbed into this while doing my construct with `CfnRule`, instead of `Rule`. 
I have to use `CfnRule`, because I couldn't find a way to use inputTransformer wiht `Rule`. 

I'm triggering Codebuild from ECR, when new image is pushed to ECR, and I want to tranform ecr push event for my codebuild environment variables, like in this example https://github.com/aws-samples/amazon-ecr-cross-region-replication/blob/master/template.yaml. Though I'm not doing cross region, I'm doing cross account replication, but the example is good for that also.

**Comment by enrico-usai** [comment] 2021-03-12 12:29
I resolved this problem by passing a raw dictionary, rather than an EventPattern, given that `event_pattern` attribute [can be `Any`](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_events/CfnRule.html):



```python
     events.CfnRule(
            scope=self,
            id="xxx",
            event_pattern={
                "detail": {
                    "build-status": ["FAILED", "STOPPED", "SUCCEEDED"],
                    "project-name": [xxx],
                },
                "detail-type": ["CodeBuild Build State Change"],
                "source": ["aws.codebuild"],
            },
            state="ENABLED",
        )
```

**Comment by rix0rrr** [comment] 2021-03-15 10:46
You are mixing L1 and L2 types. `EventPattern` is NOT intended to be the type of `CfnRule` patterns, it's intended to be the type of `Rule` patterns.

This is not a bug.

**Closed by rix0rrr** 2021-03-15 10:46 UTC
Labels: @aws-cdk/aws-events, bug, cause/mixing-l1-and-l2, needs-triage

**Comment by rektide** [comment] 2021-12-08 21:50
@rix0rrr the docs for https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.CfnRule.html#eventpattern-1 are incredibly confusing:

```
Type: any

AWS::Events::Rule.EventPattern.
```

This is confusing but it gives the impression that it expects an EventPattern. The EventPattern docs helpfully clarify this is not the case, but the docs for CfnRule are quite confusing. [EventPattern trying to correct the situation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-events.EventPattern.html):

```
Important: this class can only be used with a Rule class. In particular, do not use it with CfnRule class: your pattern will not be rendered correctly. In a CfnRule class, write the pattern as you normally would when directly writing CloudFormation.
```
