### ISSUE TITLE
aws-lambda-event-sources: S3EventSource Requires Bucket, but only needs an IBucket

### ISSUE THREAD

**Issue by Styerp** [aws/aws-cdk#23940] opened 2023-02-01 00:39 UTC
### Describe the bug

I want to use an externally created bucket as an event notification source for a lambda

### Expected Behavior

An IBucket can be used as the notification source 

### Current Behavior

Type errors.  An `IBucket` cannot be assigned to a `Bucket`. 

### Reproduction Steps

```
import * as core from "aws-cdk-lib";
import * as event_sources from "aws-cdk-lib/aws-lambda-event-sources";
import * as s3 from "aws-cdk-lib/aws-s3";

const app = new core.App()
const ibucket = s3.Bucket.fromBucketName(app, "IBucket", "IBucket");
const eventSource = new event_sources.S3EventSource(ibucket, {events: [s3.EventType.OBJECT_CREATED]})
```

> TS2345: Argument of type 'IBucket' is not assignable to parameter of type 'Bucket'.

### Possible Solution

Since `addEventNotification` is the only method used by S3EventSource and is available on an IBucket, I think it should be safe to loosen the type restriction to IBucket. 

Coercing the type and deploying works.

### CDK CLI Version

2.40.0

### Node.js Version

16

### OS

OSX

### Language

Typescript

**Comment by peterwoodworth** [comment] 2023-02-01 02:21
Thanks for this request, it looks to me like it's not necessary to only allow a `Bucket`, and that having `IBucket` here would be fine. However, this would cause issues when adding a notification for a `LambdaDestination`, as that requires having the Bucket construct 

However there is already an existing check for this: https://github.com/aws/aws-cdk/blob/c164a49c67def802a84f37b6ad779a78442e5a53/packages/%40aws-cdk/aws-s3-notifications/lib/lambda.ts#L17-L20

If properly documented we could be able to allow for imported buckets to be used here to allow for more use cases

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

**Comment by casyalex** [comment] 2023-04-18 02:40
+1

**Comment by bferdousi** [comment] 2023-04-26 12:04
+1

**Comment by MacHu-GWU** [comment] 2023-05-30 04:30
Tested on 2.81.0, this is not fixed yet. In case you are having the same issue, here's my alternative solution:

```python
        bucket = s3.Bucket.from_bucket_attributes(
            self,
            "ImportedBucket",
            bucket_arn=f"arn:aws:s3:::{self.env.s3dir_source.bucket}",
        )

        use latest
        bucket.add_event_notification(
            s3.EventType.OBJECT_CREATED,
            s3_notifications.LambdaDestination(
                self.lambda_func_mapper[self.env.lbd_s3sync.name][KEY_FUNC],
            ),
            s3.NotificationKeyFilter(
                prefix=f"{self.env.s3dir_source.key}",
            ),
        )

        use alias
        bucket.add_event_notification(
            s3.EventType.OBJECT_CREATED,
            s3_notifications.LambdaDestination(
                lambda_.Function.from_function_attributes(
                    self,
                    f"LambdaAliasAttribute{self.env.lbd_s3sync.short_name_camel}",
                    function_arn=self.lambda_func_mapper[self.env.lbd_s3sync.name][KEY_ALIAS].function_arn,
                    same_environment=True,
                ),
            ),
            s3.NotificationKeyFilter(
                prefix=f"{self.env.s3dir_source.key}",
            ),
        )
```

**Comment by tim-finnigan** [comment] 2023-07-26 23:08
This appears to be a duplicate of this older issue: https://github.com/aws/aws-cdk/issues/4323. I'm going to close this in order to consolidate issues.

**Closed by tim-finnigan** 2023-07-26 23:08 UTC
Labels: good first issue, p2, feature-request, effort/small, @aws-cdk/aws-lambda-event-sources
