### ISSUE TITLE
[cli] How to see the YAML output of synth command in multi-stack projects

### ISSUE THREAD

**Issue by akefirad** [aws/aws-cdk#9286] opened 2020-07-28 08:47 UTC
I can't see the YAML output of `synth` command in multi-stack projects. I'm not sure what I'm doing wrong.

### Reproduction Steps
```
# cdk ls
MyStack1
MyStack2
# cdk synth
Successfully synthesized to cdk.out
Supply a stack id (MyStack1, MyStack2) to display its template.
# cdk synth MyStack1
Successfully synthesized to cdk.out
Supply a stack id (MyStack1, MyStack2) to display its template.
```

### Environment

  - **CLI Version      :** aws-cli/2.0.24 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev28
  - **Framework Version:** 1.54.0 (build c01b9b9)
  - **Node.js Version:** v14.5.0
  - **OS               :** Mac OS X 10.15.6
  - **Language (Version):** typescript ~3.7.2

This is :bug: Bug Report

**Comment by shivlaks** [comment] 2020-07-29 06:50
@akefirad I believe this is a duplicate of #3721 
Please feel free to reopen this issue if that's not representative of the friction you're running into.

**Closed by shivlaks** 2020-07-29 06:50 UTC
Labels: bug, needs-triage, package/tools
