### ISSUE TITLE
cli: Respect --build option in cdk.json as well

### ISSUE THREAD

**Issue by acomagu** [aws/aws-cdk#32329] opened 2024-11-29 09:34 UTC
### Describe the feature

The `--build` option was introduced for `cdk deploy` or `cdk watch` command at #19663, but the equivalent field in cdk.json is not introduced.

This issue proposes to support `build` field to cdk.json as well as `--build` flag.

### Use Case

Rather than add `--build ./build.sh` flag each time executing `cdk deploy`, it's convenient if we could write the build command to cdk.json, like

```json
{
  "app": "...",
  "build": "./build.sh"
}
```

### Proposed Solution

Support `build` field in cdk.json.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.165.0

### Environment details (OS name and version, etc.)

Linux acm-envy3-win 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux

**Comment by ashishdhingra** [comment] 2024-11-29 17:11
Appears to be valid feature request to support `build` option in `cdk.json`, similar to other options like `app` and `versionReporting`.

@acomagu Feel free to contribute PR that could be reviewed by the team. They should get back to you in case of any concerns or review comments.

**Comment by acomagu** [comment] 2024-11-30 04:34
@ashishdhingra Thank you for your insight! Unfortunately I won't be able to start working on PR in at least a week, but I intend to do it sooner or later.

But I also don't intend to prevent others from make PR.

**Comment by tmokmss** [comment] 2024-11-30 07:54
Afaik this feature has already been available via cdk.json.

**Comment by ashishdhingra** [comment] 2024-11-30 08:47
> Afaik this feature has already been available via cdk.json.
> 
> 
> 
> edit) found the PR: #17176. It seems `~/cdk.json` (user config) is not supported though. Is this the feature you need?

@tmokmss Thanks for your reply. Unsure if this is documented in CDK guide.

@acomagu Could you please give it a try and if it works, kindly close the issue.

**Comment by tmokmss** [comment] 2024-11-30 14:58
@ashishdhingra I found this doc somewhat relevant:

> You can pass options through command-line arguments. For most options, you can configure them in a cdk.json configuration file.
> https://docs.aws.amazon.com/cdk/v2/guide/ref-cli-cmd.html#ref-cli-cmd-configure

But the problem is that it is not clear what `most options` are 😓

**Comment by rix0rrr** [comment] 2024-12-02 15:37
Thanks for the feedback. I'll pass this note along for considerations of consistency for some upcoming work.

**Closed as completed** 2024-12-02 15:38 UTC
Labels: p2, feature-request, package/tools, effort/small
