### ISSUE TITLE
aws-batch JobDefinition: Support import using 'fromJobDefinitionName'

### ISSUE THREAD

**Issue by ayush987goyal** [aws/aws-cdk#7172] opened 2020-04-04 05:42 UTC
Currently `JobDefinition` constructs only supports `fromJobDefinitionArn`. For using `Batch` in `StepFunctions`, we can provide `JobDefinition` as any one of `name`, `name:revision` or `ARN` ([Ref](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html#Batch-SubmitJob-request-jobDefinition))

Now to import `JobDefinition` in `StepFunctions`, we can only use `fromJobDefinitionArn` which is not flexible since `JobDefinitionArn` contains the `revision` as well. This leads to an ARN update after every change in revision (very frequent). The ideal way to handle this would be to import using `name` instead of the `ARN`

Hence a method like `fromJobDefinitionName` would suit this particular use case.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment] 2020-04-12 14:44
Hi @ayush987goyal 

Notice that you can do:

```typescript
const jobDef = JobDefinition.fromJobDefinitionArn(arn)
const jobDefName = jobDef.jobDefinitionName
```

The problem is that the `aws-stepfunction-tasks` module, that accepts a `JobDefinition`, always uses the [`Arn`](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-stepfunctions-tasks/lib/run-batch-job.ts#L242), even though it can use the `name` if the user so desires.

I am relabeling this request to the `aws-stepfunction-tasks` module. 

Thanks for reporting this!

**Comment by iliapolo** [comment] 2020-04-12 14:45
@nija-at Can you share you thoughts here?

**Comment by ayush987goyal** [comment] 2020-04-12 15:19
@iliapolo What I was trying to refer to int the issue was:

Consider the scenario where the `JobDefinition` is maintained in a different stack altogether. It has its own lifecycle of code changes and the version is bumped every now and then. We want to use the latest version of the this `JobDefinition` is another stack for `StepFunctions`. 

To achieve this, let's say we made a stack export of `JobDefinitionArn` from the `JobDefinition` stack and then used it in `StepFunctions` stack using:
```
JobDefinition.fromJobDefinitionArn(arn)
```

Now, when there is a code change and version updates for the `JobDefinition`, it changes the the `ARN` (since `ARN` contains version number). This leads to deployment failure for the `JobDefinition` stack since it would say the `export` is currently used in another stack (`StepFunctions` stack). To resolve this, we would have to remove the reference of that export from the `StepFunctions` stack and then redeploy. We have to do this for every code change.

To prevent this issue, `StepFunction` for `Batch` supports passing only the `JobDefinitionName` as well. But this is currently not possible since to import a `JobDefinition` from one stack to another, it only supports `fromJobDefinitionArn`. Therefore we would probably need `fromJobDefinitionName` in `Batch`.

I hope it was clear.

**Comment by iliapolo** [comment] 2020-04-12 15:50
Hi @ayush987goyal 

Yes this is clear. The feature you want still mainly requires changes in the `stepfunction-tasks` module since it needs to do:

```typescript
JobDefinition: this.props.jobDefinition.jobDefinitionName
```

Instead of 

```typescript
JobDefinition: this.props.jobDefinition.jobDefinitionArn
```

In addition, I understand that you would like to export the job definition name and not the arn, so you won't have to redeploy every time the job definition undergoes a version bump. 

The thing that pops to mind when implementing a `fromJobDefinitionName` is that the resulting object will be incomplete, since it will be missing the ARN. There is no way to infer the ARN from the name, as opposed to the other way around. Thats not to say we can't come up with a solution here, it would just require a slightly different API.

**Comment by nija-at** [comment] 2020-04-14 09:53
I have a feeling that the revision portion of the ARN is optional, referring to the latest version of the job when unspecified. Have we checked this? This SO answer suggests that - https://stackoverflow.com/a/55031183.

If such is the case, the `fromJobName()` API can be added. @iliapolo ?

**Comment by iliapolo** [comment] 2020-04-14 10:10
@nija-at Thats interesting. In that case just using `fromJobDefinitionArn` would also work by omitting the revision from the ARN.

@ayush987goyal Any chance you can see if that works for you? 

If that works, then yeah we can add a `fromJobDefinitionName` function that creates this "partial" ARN for ease of use. 

Though it still feels a bit awkward. Looking at the `stepfunction-tasks` code a user would not be able to distinguish between a task that runs the latest revision of a job definition or a specific one. Using `jobDefinitionName` though would make it clear that no revision is passed, and hence the latest is used. (just like the API suggests).

**Comment by ayush987goyal** [comment] 2020-04-14 10:57
@iliapolo That would only be possible to work with if we construct the ARN manually and export. I do no know if there is a helper method to get the ARN without revision.

**Comment by iliapolo** [comment] 2020-04-14 11:39
> Maybe we need to give flexibility to the consumer to decide if they want to use name or name + revision etc

Yes. I mean we will give the flexibility either way because the user can choose to use a full or a partial ARN. Its just that it would require some additional knowledge from the user to actually understand what is going to be executed.

> I do no know if there is a helper method to get the ARN without revision.

You should be able to use this in the exporting stack:

```typescript
Stack.of(this).formatArn({
        service: 'batch',
        resource: 'job-definition',
        resourceName: 'job-definition-name'
      }
```

Or, if you want to change the importing stack:

```typescript
    const components = cdk.Arn.parse(arnWithRevision);
    const arnWithoutRevision = cdk.Arn.format({
      ...components,
      resourceName: cdk.Fn.select(0, cdk.Fn.split(':', components.resourceName!))
    }, Stack.of(this))

```

**Comment by nija-at** [comment] 2020-04-16 13:26
Moving this back into the queue for batch. This does not belong to stepfunctions.

**Comment by ayush987goyal** [comment] 2020-09-20 11:51
Added a PR https://github.com/aws/aws-cdk/pull/10448 to close this issue.

**Closed** 2020-09-30 13:28 UTC
Labels: @aws-cdk/aws-batch, effort/small, feature-request, in-progress, p1
