### ISSUE TITLE
(pipelines): CloudFormation deploy is not retryable

### ISSUE THREAD

**Issue by bilalq** [aws/aws-cdk#21677] opened 2022-08-19 06:36 UTC
### Describe the bug

Right now, if a pipeline has a step that does a Prepare/Deploy action to a CloudFormation stack, a failed deployment leaves the pipeline in a stuck state. This happens because the ChangeSet gets removed, but the the Prepare step gets on retries skipped because it already succeeded. 

### Expected Behavior

Retrying the deployment should work (or at least actually try to deploy again).

### Current Behavior

The changeset gets deleted after the deployment fails. When the pipeline step is retried, it skips the Prepare step because it has already succeeded.

### Reproduction Steps

You can create a minimal reproduction of the issue by trying to deploy a stack update that has a named resource that already exists in the account. This issue is not limited to such a reproduction step. This has happened on occasions where CloudFormation was having availability issues and returning 500 errors.

### Possible Solution

Don't skip the Prepare step if it already succeeded on a retry. Instead, re-run it. 

Alternatively, if there's a way to keep the changeset, that could work too. 

### CDK CLI Version

2.33.0

### Node.js Version

16.16.0

### OS

MacOS

### Language

Typescript

### Language Version

4.7.4

**Comment by gshpychka** [comment] 2022-08-19 12:27
Duplicate of https://github.com/aws/aws-cdk/issues/11995, I'm afraid, which was closed as non-actionable.

**Comment by peterwoodworth** [comment] 2022-08-19 23:59
Unfortunately it's still the case that there's no action CDK can take regarding this issue, this is an issue for codepipeline service. Sorry for the experience here

**Closed** 2022-08-19 23:59 UTC
Labels: bug, blocked, @aws-cdk/pipelines

**Comment by gshpychka** [comment] 2023-03-31 09:20
> > Unfortunately it's still the case that there's no action CDK can take regarding this issue, this is an issue for codepipeline service. Sorry for the experience here
> 
> 
> 
> Has anyone raised an issue with the codepipline service?  Can the cdk team tell them what we need and get it on their roadmap?

No real need, this is now possible with https://github.com/aws/aws-cdk/pull/21619
