### ISSUE TITLE
(cdk-pipelines): Destroy stacks when they are removed / renamed in a CdkPipeline or Stage

### ISSUE THREAD

**Issue by mpvosseller** [aws/aws-cdk#12463] opened 2021-01-11 14:48 UTC
We should destroy stacks when they are removed (or renamed) in a `CdkPipeline` or `Stage`:

1) When an `applicationStage` is removed from a `CdkPipeline` the stacks associated with that stage should be destroyed 
2) When an `applicationStage` is renamed the stacks associates with the old name should be destroyed
3) When a stack is removed from a `Stage` the stack should be destroyed
4) When a stack is renamed in a `Stage` the stack with the old name should be destroyed

This is surprising behavior given how the rest of a CDK application behaves and requires careful manual intervention to delete stacks as the code changes.

Consider deploying a CDK Pipeline application like the following:

```typescript
class MyStack1 extends Stack {}

class MyStack2 extends Stack {}

class MyStage extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    super(scope, id, props)
    new MyStack1(this, 'my_stack_1')
    new MyStack2(this, 'my_stack_2')
  }
}

class MyPipelineStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props)
    const pipeline = new CdkPipeline(this, 'Pipeline', {
      //...
    })
    pipeline.addApplicationStage(new MyStage(this, 'PreProd', {}))
    pipeline.addApplicationStage(new MyStage(this, 'Prod', {}))
  }
}

const app = new App()
new MyPipelineStack(app, 'my_pipeline', {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION,
  },
})
```

Now as an example of each issue above consider making the following changes and redeploying. 

1) If we remove the following line and redeploy then `PreProd_my_stack_1` and `PreProd_my_stack_2` are not destroyed
```typescript
pipeline.addApplicationStage(new MyStage(this, 'PreProd', {}))
```

2) If we change the name of `PreProd` to `Staging` and redeploy then `PreProd_my_stack_1` and `PreProd_my_stack_2` are not destroyed

3) If we remove the following line and redeploy then `PreProd_my_stack_2` and `Prod_my_stack_2` are not destroyed
```typescript
new MyStack2(this, 'my_stack_2')
```

4) If we rename `my_stack_2` to `my_stack_new` and redeploy then `PreProd_my_stack_2` and `Prod_my_stack_2` are not destroyed

### Use Case

This change would make the CDK more consistent and remove the need to manually delete stacks as the code changes.

### Other
Related to https://github.com/aws/aws-cdk/issues/10190

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2021-01-18 13:29
Duplicate of #10759

**Closed by rix0rrr** 2021-01-18 13:29 UTC
Labels: @aws-cdk/pipelines, feature-request, needs-triage
