### ISSUE TITLE
ApiGateway CDK problem with binaryMediaTypes and another content data

### ISSUE THREAD

**Issue by MagdalenaMecinska** [aws/aws-cdk#15569] opened 2021-07-15 13:51 UTC
Hi, I ran into a problem with the body sent in the request. My case only requires binary file support in some endpoints, in others it is plain json. My problem is that when I include binary support in my api, any other json body is auto converted to base64 and no matter what the meta data on s3 is set to application/octet-stream. It is quite bothersome because in lambdas I have to restore their state to normal json and set the ContentType before send them to s3 "manually".
I am using cdk and RestApi. I tried various ways to configure such properties like contentHandlig, but without any results.
I guess there must be another solution to handle that problem. Any ideas?

  - cdk v1.106.0 
  - Node.js v16.4.1
  - TypeScript v3.9.7

**Comment by peterwoodworth** [comment] 2021-07-19 17:26
Hey @MagdalenaMecinska,

how exactly are you currently trying to accomplish this in cdk? Are you using an apigateway::RestApi construct to create your API? Here's the description for the [binaryMediaTypes property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-binarymediatypes)

**Comment by MagdalenaMecinska** [comment] 2021-07-21 12:49
I am using CDK and apigateway:RestApi

**Comment by peterwoodworth** [comment] 2021-07-23 02:22
I don't fully understand your issue @MagdalenaMecinska, how exactly does this issue relate to CDK? I understand you're using the CDK but without understanding you exactly you're implementing things I don't think I can help you.

**Comment by peterwoodworth** [comment] 2021-08-04 18:47
Closing this issue for staleness, please provide more information and ping me if you still want help with this :)

**Closed by peterwoodworth** 2021-08-04 18:47 UTC
Labels: @aws-cdk/aws-apigateway, closing-soon, guidance

**Comment by monigala** [comment] 2025-04-04 19:31
What was the solution to the question? I am faced with the same issue. We are using nodejs:
```
		"aws-cdk": "^2.1003.0",
		"aws-cdk-lib": "^2.183.0",
		"constructs": "^10.4.2",
```

![Image](https://github.com/user-attachments/assets/d7adf6cf-c45a-408b-b4b5-2fd3648c62a9)

We have about 20 endpoints for this RestAPI. The issue is the binary-media-type gets applied to EVERY endpoint. I only need it applied to a single endpoint. Thus the other 19 endpoints fail to work after enabling binary media type at the RestAPI level. it would be great if we could define that at a "pre-endpoint" configuration.

Is this possible?
