### ISSUE TITLE
(cli):  bootstrap should create role for `cdk` CLI to assume when doing cross account deploys

### ISSUE THREAD

**Issue by redbaron** [aws/aws-cdk#11848] opened 2020-12-03 02:48 UTC
### Use Case

cdk CLI makes calls to a target account using either current credentials or credentials obtained from a plugin. Because single CDK app can deploy to multiple accounts, current credentials won't work and it is required to assume role in every target account. `cdk-assume-role-credential-plugin` helps to make assume role seamless, but there is currently no such role created by the bootstrap process and separate out of band role creation required. 

### Proposed Solution

Bootstrap process shouls create a new  role in a target account, with enough permissions to do following:
- assume existing bootstrap roles for deploy, image upload and file upload
- allow resource lookups in the target account

`cdk-assume-role-credential-plugin` can then be configured to use that role, making cross account deploys easier to implement.

### Other

Existing roles for deploy, image assets and file assets allow establishing trust relationship with account where deploys should be running from, but it is not clear how exactly that cross account trust should be used. CDK CLI assumes these roles at various stages, but prior to it validates, that account it is running from matches account we are deploying to , aborting execution if they don't. This makes `bootstrap --trust` half complete.

If proposed feature is implemented, there will be not cross account `sts:AsumeRole` calls for these roles, only for the new one.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2020-12-08 14:09
Duplicate of https://github.com/aws/aws-cdk/issues/11792, https://github.com/aws/aws-cdk/issues/8905, https://github.com/aws/aws-cdk/issues/9597

**Closed by rix0rrr** 2020-12-08 14:09 UTC
Labels: feature-request, needs-triage, package/tools
