### ISSUE TITLE
AwsCustomResource returns no values since update

### ISSUE THREAD

**Issue by Console32** [aws/aws-cdk#7061] opened 2020-03-29 11:53 UTC
I have a AwsCustomResource in place to read the UserPoolDomain DomainDescription.CloudFrontDistribution property.

This worked fine in 1.25, but no longer works in 1.31

### Reproduction Steps
```typescript
    const userPoolDomainDescription = new customResources.AwsCustomResource(this, 'user-pool-domain-description', {
      policy: customResources.AwsCustomResourcePolicy.fromSdkCalls({
        resources: customResources.AwsCustomResourcePolicy.ANY_RESOURCE
      }),
      onCreate: {
        physicalResourceId: customResources.PhysicalResourceId.of("UserPoolDomainDescription"),
        service: 'CognitoIdentityServiceProvider',
        action: 'describeUserPoolDomain',
        parameters: {
          Domain: userPoolDomain.domain
        }
      }
    });

    const dnsName = userPoolDomainDescription.getResponseField('DomainDescription.CloudFrontDistribution').toString();
```

results in a Vendor response doesn't contain DeomainDescription.CloudFrontDistribution key error.

### Error Log

```
 0/1 | 1:44:25 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack   | auth CustomResource attribute error: Vendor response doesn't contain DomainDescription.CloudFrontDistribution key in object arn:aws:cloudformation:eu-central-1:688677094802:stack/auth/b7875810-22ef-11ea-a9e9-0647b6afc3d8|userpooldomaindescription7C44EB82|b18e54c9-3487-4c14-83d2-f3609915565a in S3 bucket cloudformation-custom-resource-storage-eucentral1
```

### Environment

  - **CLI Version      :*1.31*
  - **Framework Version:*.131*
  - **OS               :*macOS Catalina*
  - **Language         :*ts*

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2020-04-11 10:01
Hi @Console32 

I am not able to reproduce this. Here is the code i'm using:

```typescript
    const userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName: 'cdk-playground'
    })

    const userPoolDomain = new cognito.CfnUserPoolDomain(this, 'UserPoolDomain', {
      domain: 'test-domain',
      userPoolId: userPool.userPoolId,      
    })

    const userPoolDomainDescription = new cr.AwsCustomResource(this, 'user-pool-domain-description', {
      policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
        resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE
      }),
      onCreate: {
        physicalResourceId: cr.PhysicalResourceId.of("UserPoolDomainDescription"),
        service: 'CognitoIdentityServiceProvider',
        action: 'describeUserPoolDomain',
        parameters: {
          Domain: userPoolDomain.domain
        }
      }
    });

    const dnsName = userPoolDomainDescription.getResponseField('DomainDescription.CloudFrontDistribution').toString();    

    new cdk.CfnOutput(this, 'Domain', {
      value: dnsName
    })
```

Which produced the following output:

```console
Outputs:
AwsCdkPlaygroundCustomResource.PlaygroundDomain1CF0C627 = d1lcia0inyjsq.cloudfront.net
```

I did however receive the same error when trying to describe a non existing user pool domain. Is it possible that was the case for you? 

Please if you can share the code you use to instantiate the `userPoolDomain` variable so we can dig a bit deeper. 

Thanks

**Comment by SomayaB** [comment] 2020-04-28 22:33
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Closed by SomayaB** 2020-04-28 22:33 UTC
Labels: @aws-cdk/custom-resources, bug, closing-soon

**Comment by mj7007** [comment] 2021-12-06 02:31
I faced the same issue. When the stack is created for the first time, it worked and when I tried to update the stack awsCustomResource.getResponseFeild threw an error. I fixed it by implementing onUpdate lifecycle method.
