### ISSUE TITLE
DependsOn is missing when creating pipeline

### ISSUE THREAD

**Issue by ben8p** [aws/aws-cdk#7161] opened 2020-04-03 12:21 UTC
This bug only occurs when having custom construct in a different package.  
This is a regression starting from 1.29.0. Version 1.28.0 does not have this problem.  

When there is a `Construct` creating a `Pipeline` in a package `Foo` and the main `app` is in package `Bar`, `app.synth` does not add `DependsOn` on the Pipeline resources (resulting in an invalid stack)

### Reproduction Steps

This is rather complex to setup so I made a repository.
1. Clone https://github.com/ben8p/aws-cdk-bug-reproduction-steps
1. Run `npm install`
1. Run `npm run build`
1. Open `packages/infrastructure/build/PipelineConstruct.template.json`
1. Observe the lack of `DependsOn`
1. Replace `1.31.0` by `1.28.0` in all `package.json`
1. Run `npm install`
1. Run `npm run build`
1. Open `packages/infrastructure/build/PipelineConstruct.template.json`
1. Observe the presence of `DependsOn`

### Error Log

No error, just invalid template

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **OS               :**
  - **Language         :**

### Other

I have the feeling it might have been introduced by https://github.com/aws/aws-cdk/pull/6722

--- 

This is :bug: Bug Report

**Comment by ben8p** [comment] 2020-04-03 20:23
@skinny85 same problem with 1.29.0 indeed.
1.28.0 is working fine

**Comment by skinny85** [comment] 2020-04-03 20:34
That's significant, because `1.29.0` is the first version with the `constructs` library dependency...

I'm still investigating. Will update the ticket as soon as know more.

**Comment by skinny85** [comment] 2020-04-04 00:18
Hey @ben8p ,

the problem is not in the CDK, but in your setup with Lerna. My guess is that with the way your dependencies are set up, you have 2 copies of the `@aws-cdk/core` library in your `node_modules` (one in `infrastructure/node_modules/@aws-cdk/core`, one in `infrastructure/node_modules/@bug-cdk/constructs/node_modules/@aws-cdk/core`).

Here's a PR that changes that setup, and using it, you get the `DepensOn` element again:

https://github.com/ben8p/aws-cdk-bug-reproduction-steps/pull/1

Let me know if that fixes your problem!

Thanks,
Adam

**Comment by skinny85** [comment] 2020-04-04 01:28
Here's the root cause - it's actually in the `constructs` library, not strictly in the CDK: https://github.com/aws/constructs/issues/32

**Comment by ben8p** [comment] 2020-04-04 07:38
@skinny85 thanks a lot for picking this up that fast!
After reading https://github.com/aws/constructs/issues/32 it now perfectly make sense.
I will monitor the original issue and go with the workaround for now.

**Comment by apalumbo** [comment] 2020-04-04 10:43
@ben8p Didi you have the issue while you have your package linked with something like `npm link`?

**Comment by SomayaB** [comment] 2020-04-11 03:07
Closing for now. Feel free to reopen.

**Closed by SomayaB** 2020-04-11 03:07 UTC
Labels: bug, package/codepipeline, response-requested
