### ISSUE TITLE
CDK generates unsupported property when combining with Condition

### ISSUE THREAD

**Issue by NGL321** [aws/aws-cdk#9761] opened 2020-08-05 20:00 UTC
*Copied from @yidimu*

### What did you expect to happen?

I was trying to create a lambda function within VPC when a `RunLambdaInVPC` condition equals to true.
Below is the expected and correct CFN template. Please note the first letter of `SecurityGroupIds` and `SubnetIds` are upper case.
``` json
        "FindingsEsIndexer": {
            "Type": "AWS::Serverless::Function",
            "Properties": {
                "CodeUri": { ... },
                "Handler": "...",
                "Runtime": "...",
                "AutoPublishAlias": { ... },
                "DeploymentPreference": { ... },
                "Environment": { ... },
                "Events": { ... },
                "FunctionName": "...",
                "MemorySize": ...,
                "Role": { ... },
                "Timeout": ...,
                "VpcConfig": {
                    "SecurityGroupIds": [
                        {
                            "Fn::GetAtt": [
                                "LambdaSecurityGroup",
                                "GroupId"
                            ]
                        }
                    ],
                    "SubnetIds": [
                        {
                            "Fn::ImportValue": "PrivateSubnet01"
                        },
                        {
                            "Fn::ImportValue": "PrivateSubnet02"
                        }
                    ]
                },
                "ProvisionedConcurrencyConfig": { ... }
            },
            "Metadata": { ... }
        },
```

### What actually happened?

However, when I add condition, with the following code, CDK generates the template with `securityGroupIds` and `subnetIds` (first letter lower case). And I got "Encountered unsupported property securityGroupIds" error. CDK could still generate correct property name when removing the condition though.
``` java
CfnFunction.VpcConfigProperty vpcConfigProperty = CfnFunction.VpcConfigProperty.builder()
                .securityGroupIds(Arrays.asList(cfnSecurityGroup.getAttrGroupId()))
                .subnetIds(Arrays.asList(
                        Fn.importValue("PrivateSubnet01"),
                        Fn.importValue("PrivateSubnet02")
                ))
                .build();
CfnFunction function = new CfnFunction(this, "functionName",
                CfnFunctionProps.builder()
                        .codeUri(...)
                        .handler(...)
                        .runtime(...)
                        .memorySize(...)
                        .timeout(...)
                        .environment(...)
                        .role(...)
                        .functionName(...)
                        .autoPublishAlias(stackHelper.getStage())
                        .vpcConfig(Fn.conditionIf(runLambdaInVPC.getLogicalId(), vpcConfigProperty, Fn.ref("AWS::NoValue")))
                        .build());
```

### Environment

  - **CLI Version      :**
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** Java

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-08-17 09:48
Transferring this to @RomainMuller since the errors are coming from the JSII kernel and I suspect something ain't working there.

**Comment by RomainMuller** [comment] 2020-08-17 10:36
I'm actually able to reproduce the issue in **TypeScript**, so this is **not** a jsii bug.

The `Error: Module '@aws-cdk/aws-sam' not found` you got however seems to be a class loader oddity that **is** probably a jsii bug however (likely due to the nested class loading not causing it's wrapping class to be loaded, and I don't reckon we emit `jsii.load` calls from nested class initializers)

**Comment by nija-at** [comment] 2020-08-17 12:56
Thanks @RomainMuller. Opened a separate issue for the error I encountered - https://github.com/aws/jsii/issues/1904

**Comment by rix0rrr** [comment] 2020-08-18 07:36
We don't really support generating templates with complex conditional logic executed at deployment time, and it's unlikely we will anytime soon. We recommend putting the conditional logic in your Java application.

**Closed by rix0rrr** 2020-08-18 07:36 UTC
Labels: @aws-cdk/core, bug
