### ISSUE TITLE
[@aws-cdk/aws-ecs] Task count issue !

### ISSUE THREAD

**Issue by ibuchh** [aws/aws-cdk#10226] opened 2020-09-07 22:57 UTC
### Reproduction Steps
I created an ECS Service based on Fargate using CDK with 4 number of tasks. All looks good. 
1. I use the AWS Management Console to update the number of tasks to 2.
2. Then when I try to run cdk diff, it shows me "There were no differences".

### What did you expect to happen?
It should have detected the new number of tasks as 2.

### What actually happened?

Is this an expected behavior?

### Environment

  - **CLI Version      :**
aws-cli/2.0.42 Python/3.8.5 Darwin/17.7.0 source/x86_64
  - **Framework Version:**
cdk --version
1.62.0 (build 8c2d7fc)
  - **Node.js Version:** 
v14.8.0
  - **OS               :**
Mac
  - **Language (Version):** 
Javascript
### Other

--- 

This is :bug: Bug Report

**Comment by jonny-rimek** [comment] 2020-09-07 23:45
if you run `cdk diff` it compares the locally generated cloudformation against the state in that was applied last.
If you change something in the console cloudformation does not get updated. 

The behavior you did is commonly referred to as configuration drift. That means your actual state does not reflect what you last applied and is currently stored in cloudformation.

So yes it is the expected behavior.

To avoid configuration drift, best practice is to create a read only User and only change code through cloudformation/cdk

**Comment by ibuchh** [comment] 2020-09-08 00:50
Ok thanks. I am coming from Terraform world where a terraform plan compares the current state in the AWS account with the terraform state.

**Comment by SomayaB** [comment] 2020-10-02 01:48
Closing since it seems to have been resolved. Feel free to reopen.

**Closed by SomayaB** 2020-10-02 01:48 UTC
Labels: @aws-cdk/aws-ecs, bug
