### ISSUE TITLE
ECR: support `force` upon deletion

### ISSUE THREAD

**Issue by digitalsanctum** [aws/aws-cdk#2765] opened 2019-06-06 04:47 UTC
When deleting an ECR repository using the SDK or CLI there's a `force` option which will delete the repository regardless if there images in the repository. Please support this option, otherwise users are forced to use a custom resource as a workaround.

For reference, see:
1. https://docs.aws.amazon.com/cli/latest/reference/ecr/delete-repository.html
1. https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DeleteRepository.html

**Comment by RomainMuller** [comment] 2019-06-07 13:58
This feature is not supported by [CloudFormation currently](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html). This means that, if CDK does anything about it, it'll have to involve... a CustomResource.

**Comment by heiba** [comment] 2020-05-28 18:58
How can we raise this request the CloudFormation team to support force deletion of ECR repositories ?

**Comment by heiba** [comment] 2020-06-07 05:39
I created a new issue in the CloudFormation Coverage Roadmap repository
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/515

Please let me know if I should take another action to escalate this issue to the CloudFormation team

**Comment by peterwoodworth** [comment] 2021-04-13 21:58
It looks like the CFN team is looking at the issue @heiba created as of 11 days ago. Hopefully we'll be able to support this feature soon without the need for a custom resource

**Comment by NukaCody** [comment] 2021-04-20 23:59
It looks like this is [already done with S3](https://github.com/aws/aws-cdk/blob/HEAD/packages/@aws-cdk/aws-s3/lib/bucket.ts#L1832), with a [custom resource here](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-s3/lib/auto-delete-objects-handler/index.ts).

**Comment by heiba** [comment] 2021-05-30 14:55
@MrArnoldPalmer @RomainMuller While I'm chasing the CloudFormation team to hopefully update us on this issue. Any chance the CDK team can implement it using a custom resource ?

**Comment by heiba** [comment] 2021-08-07 06:32
@kirintwn referencing your new branch that includes deleting of ecr repos via a custom resource.

https://github.com/aws/aws-cdk/issues/12618

**Comment by TheRealAmazonKendra** [comment] 2023-01-24 23:48
Closing in favor of https://github.com/aws/aws-cdk/issues/12618. More or less a duplicate of that one.

**Closed by TheRealAmazonKendra** 2023-01-24 23:48 UTC
Labels: feature-request, needs-cfn, @aws-cdk/aws-ecr
