### ISSUE TITLE
(certificate manager): cannot use cross-region certificate, cannot get custom domain URL

### ISSUE THREAD

**Issue by revmischa** [aws/aws-cdk#15689] opened 2021-07-21 09:35 UTC
Two issues I had trying to set up a custom domain mapping for my ApiGwV2 HttpApi.

1) I cannot use a DNS-validated cross-region certificate from `us-east-1` in a different stack. I get #9608. Because I have a certificate for CloudFront and also my HttpApi it means I need to create two `Certificate`s, one from us-east-1 and one in my current region, even though the [docs strongly suggest](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-certificatemanager-readme.html#cross-region-certificates) that I can use my us-east-1 cert in another region.

```ts
    const hostedZone = HostedZone.fromLookup(this, "Zone", {
      domainName: hostedZoneDomain,
    })

    const certificate = new DnsValidatedCertificate(this, "RegionCertificate", {
      domainName: hostedZoneDomain,
      hostedZone,
      // region: "us-east-1",  <---- I want to use this so I can re-use this with my CloudFront dist
    })
```

2) I cannot figure out how to get the URL with custom domain and base path
```ts
    const httpApi = new HttpApi(this, `Api${appName}`, {
      apiName: this.stackName,
      defaultDomainMapping: {
        domainName,
        mappingKey: envName,
      },
    })
    new CfnOutput(this, "ApiBase", { value: httpApi.defaultStage?.url || "unknown" }) // <--- tried httpApi.url too
```
This just gives me the boring old execute-api URL, not `https://foo.com/dev` that I want. How can I get a stack output with the custom domain URL?

### Environment

  - **CDK CLI Version  :*1.110.0*
  - **Framework Version:**
  - **Node.js Version:** 14
  - **OS               :**
  - **Language (Version):** 

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2021-07-28 14:03
I've opened a feature request for your second request here - https://github.com/aws/aws-cdk/issues/15801

**Comment by nija-at** [comment] 2021-07-28 14:04
Transferring request to certificate manager for your first request.

**Comment by njlynch** [comment] 2021-07-30 13:39
@revmischa ,

When/where are you getting the mentioned error with the certificate?

Can you show a minimal repro? 

The root cause of the issue you linked was that the related account/region wasn't bootstrapped. There's also https://github.com/aws/aws-cdk/issues/10529, which is another case of ApiGateway + Certificate Manager causing this issue; in that case, the endpoint type had been set to REGIONAL instead of EDGE. Do either of those solutions help?

**Comment by revmischa** [comment] 2021-07-30 13:55
I have run `cdk bootstrap` for this environment and region. 

I am doing this to set up the domain mapping:
```ts
    new ARecord(this, "ApiDNSv4", {
      zone: hostedZone,
      recordName: domainName.name,
      target: RecordTarget.fromAlias(
        new ApiGatewayv2DomainProperties(domainName.regionalDomainName, domainName.regionalHostedZoneId)
      ),
    })
```

Taken from the docs. I don't want a regional endpoint but I don't know any other way to define my v2 HTTP API as a route53 alias target.

**Comment by njlynch** [comment] 2021-09-21 07:59
@revmischa ,

Sorry for the delay in response here. We apparently have some broken automation around our `response-requested` label that kept this from coming back into my queue. My apologies.

Re-reading through your initial description, I'm wondering if perhaps I've misinterpreted what you're trying to do:

> Because I have a certificate for CloudFront and also my HttpApi it means I need to create two Certificates, one from us-east-1 and one in my current region, even though the docs strongly suggest that I can use my us-east-1 cert in another region.

The docs you linked to above -- for the `DnsValidatedCertificate` -- allow you to _request_ a certificate cross-region, not necessarily use a certificate in a separate region with any service. The primary use case for this construct is allowing users to request certificates in `us-east-1` when their primary stack is elsewhere, for use with CloudFront. It sounds like you want to have a single `us-east-1` certificate, and use it with an `HttpApi` in another region; that (I believe) is not supported by API Gateway.

If my understanding above is incorrect, can you let me know, and provide a minimal repo that shows what you're trying to do?

**Comment by revmischa** [comment] 2021-09-21 08:13
Okay got it, I need a certificate in every region I deploy then

**Closed** 2021-09-21 08:46 UTC
Labels: bug, @aws-cdk/aws-certificatemanager
