### ISSUE TITLE
Make ExcludeCharacters configurable for aws-rds masterSecret

### ISSUE THREAD

**Issue by ahammond** [aws/aws-cdk#7911] opened 2020-05-11 17:15 UTC
ExcludeCharacters is currently `"@/\`, but there are other characters which cause issues when used in passwords.

### Use Case

DMS is slightly broken in that it can't accept all possible legal passwords. The following characters are un-supported by DMS `: ;+%`.

### Proposed Solution

In order to make it easy to extract data from RDS using DMS, we should either expand the ExcludeCharacters to include these by default. A more general solution would be to make it configurable.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nija-at** [comment] 2020-05-12 10:07
This is a duplicate of the issue - https://github.com/aws/aws-cdk/issues/4144

**Closed by nija-at** 2020-05-12 10:07 UTC
Labels: @aws-cdk/aws-rds, feature-request, needs-triage
