### ISSUE TITLE
(cdk-cli): Difficult to track `cdk deploy` issues

### ISSUE THREAD

**Issue by gabriels1234** [aws/aws-cdk#26924] opened 2023-08-29 13:41 UTC
### Describe the bug

Hi, this is between a bug and an annoyance.

When running cdk deploy , any error (in red) will make the deployment to fail.

The error is **key** to finding a solution.

But the real error disappears (sometimes too quickly) so we need to be trained into:
- See red, pless control-C to halt execution, copy error and do the research to fix it.

This need not to be this way.

### Expected Behavior

The summary need to include all the errors.

### Current Behavior

```
Dev/MyStack (Dev-MyStack) failed: Error: The stack named Dev-MyStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at FullCloudFormationDeployment.monitorDeployment (/Users/user/.nvm/versions/node/v18.17.1/lib/node_modules/aws-cdk/lib/index.js:443:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/user/.nvm/versions/node/v18.17.1/lib/node_modules/aws-cdk/lib/index.js:446:153718)
    at async /Users/user/.nvm/versions/node/v18.17.1/lib/node_modules/aws-cdk/lib/index.js:446:137166
```

### Reproduction Steps

(best way to reproduce would be to run into this yourself)
(one case: remove a resource that's needed by another stack)

### CDK CLI Version

2.93.0 (build 724bd01)

### Node.js Version

v18.17.1

### OS

Mac OS 13.4

### Language

Python

### Language Version

Python (3.11)

**Comment by peterwoodworth** [comment] 2023-08-29 19:48
I think I know what you're describing - to see the errors you should be able to go to your CloudFormation stack in the console to view the error message in the events tab as a workaround.

The error message in the console is handled by the API call we make to CloudFormation, I'm not sure how easy it would be to make the message persist in the terminal, but it would certainly be helpful if the descriptive error never disappeared

**Comment by melhakim** [comment] 2024-05-07 12:24
+1 on this one. There's also no log file in cdk.out that stores these error messages. I have to redeploy and quickly copy the error before it gets wiped off the terminal

**Comment by melhakim** [comment] 2024-05-07 14:28
Identifying the resource is just one step. But if you don't know why it is failing, debugging can be very difficult.

**Comment by ethyaan** [comment] 2024-07-09 13:53
this just started to happen to me.

**Comment by rix0rrr** [comment] 2024-10-18 15:50
Let's make 100% sure that the resource error is part of the exception that gets thrown. That way, there's no way it doesn't end up in the output.

**Comment by sumupitchayan** [comment] 2024-10-21 18:17
I am unable to reproduce this bug - I tried by creating a CDK app with an S3 Bucket using a Bucket Name that already exists. After running `cdk deploy`,  I was able to clearly see the resource handler error message in the terminal:

```
✨  Synthesis time: 3.95s

DeployErrorTestStack: start: Building 0efe21d033e1151a570dc1e09d865c2022f184180b86db587e0373f8f9be0baa:current_account-current_region
DeployErrorTestStack: success: Built 0efe21d033e1151a570dc1e09d865c2022f184180b86db587e0373f8f9be0baa:current_account-current_region
DeployErrorTestStack: start: Publishing 0efe21d033e1151a570dc1e09d865c2022f184180b86db587e0373f8f9be0baa:current_account-current_region
DeployErrorTestStack: success: Published 0efe21d033e1151a570dc1e09d865c2022f184180b86db587e0373f8f9be0baa:current_account-current_region
Stack undefined
DeployErrorTestStack: deploying... [1/1]
DeployErrorTestStack: creating CloudFormation changeset...
10:42:52 AM | CREATE_FAILED        | AWS::S3::Bucket    | mybucket15D133BF
Resource handler returned message: "source-bucket-groundtruth-56 already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: 8aa26f87-c710-a554-a7f7
-8006b151ab09, HandlerErrorCode: AlreadyExists)

❌  DeployErrorTestStack failed: The stack named DeployErrorTestStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "source-bucket-groundtruth-56 already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: 8aa26f87-c710-a554-a7f7-8006b151ab09, HandlerErrorCode: AlreadyExists)
```

@gabriels1234 @ethyaan @melhakim can any of you confirm whether you still encounter this bug? It may have been fixed in a more recent CDK version.

**Closed** 2024-10-22 15:36 UTC
Labels: bug, p1, response-requested, package/tools, effort/medium
