### ISSUE TITLE
(core): `Vpc.fromVpcAttributes` using list tokens now throws errors

### ISSUE THREAD

**Issue by bf-sodle** [aws/aws-cdk#11945] opened 2020-12-08 19:12 UTC
When importing a VPC using outputs from another stack, if the route table IDs are not specified for each imported subnet, a warning is printed to the console, as expected:
```
No routeTableId was provided to the subnet '#{Token[TOKEN.58]}'. Attempting to read its .routeTable.routeTableId will return null/undefined. (More info: https://github.com/aws/aws-cdk/pull/3171)
```

This warning line is wrongly evaluated by the new "floating token" check introduced by #11899, and throws an error when synthesizing the stack:
```
Found an encoded list token string in a scalar string context. Use 'Fn.select(0, list)' (not 'list[0]') to extract elements from token lists.
```
Additionally, this line is "consumed" by the floating-token check and does not reach the console.

### Reproduction Steps

```typescript
import * as cdk from "@aws-cdk/core";
import * as ec2 from "@aws-cdk/aws-ec2";

class TestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props: cdk.StackProps) {
    super(scope, id, props);

    const vpcId = cdk.Fn.importValue("myVpcId");
    const availabilityZones = cdk.Fn.split(",", cdk.Fn.importValue("myAvailabilityZones"));
    const publicSubnetIds = cdk.Fn.split(",", cdk.Fn.importValue("myPublicSubnetIds"));

    ec2.Vpc.fromVpcAttributes(this, "importedVpc", {
      vpcId,
      availabilityZones,
      publicSubnetIds,
    });
  }
}

const app = new cdk.App();
new TestStack(app, "TestStack", {});
```

### What did you expect to happen?

VPC is imported without error, and the following warning line is printed to the console:
```
No routeTableId was provided to the subnet '#{Token[TOKEN.58]}'. Attempting to read its .routeTable.routeTableId will return null/undefined. (More info: https://github.com/aws/aws-cdk/pull/3171)
```

### What actually happened?

No warning is printed about the route table, and the stack fails to synthesize with the following error:
```
Found an encoded list token string in a scalar string context. Use 'Fn.select(0, list)' (not 'list[0]') to extract elements from token lists.
```

### Environment

  - **CDK CLI Version  :** 1.77.0
  - **Framework Version:** 1.77.0
  - **Node.js Version:** 12.20.0
  - **OS               :** Linux (Pop!_OS 20.04 LTS x86_64)
  - **Language (Version):** TypeScript 3.9.7

### Other

The floating token check should ignore CDK "logging" lines if possible.

--- 

This is :bug: Bug Report

**Comment by markus7811** [comment] 2020-12-08 20:08
Wanted to open up this issue right now :-) None of my projects work with cdk 1.77

got exactly the same behaviour ... 

i added some debug output tu the core function ```function resolve(obj, options) {```

```
// If this is a "list element" Token, it should never occur by itself in string context
        if (encoding_1.TokenString.forListToken(obj).test()) {
            throw new Error(`Found an encoded list token string in a scalar string context. Use \'Fn.select(0, list)\' (not \'list[0]\') to extract elements from token lists. ${obj}`);
        }
```
and ended up with an error message like:

```Error: Found an encoded list token string in a scalar string context. Use 'Fn.select(0, list)' (not 'list[0]') to extract elements from token lists. No routeTableId was provided to the subnet '#{Token[TOKEN.198]}'. Attempting to read its .routeTable.routeTableId will return null/undefined. (More info: https://github.com/aws/aws-cdk/pull/3171)```

please fix this, want to use cdk 1.77 because auf WEB_IDENTITY_TOKEN_FILE Credentials, but right now its unusable :-/

**Comment by bf-sodle** [comment] 2020-12-08 20:17
@markus7811 I was able to work around this by importing the route tables IDs as well. This silences the warning, and prevents it from triggering the check. That could be an option for you as well if that data is available to you.

**Comment by markus7811** [comment] 2020-12-08 21:18
good point ... testing it out :-)

**Comment by rix0rrr** [comment] 2020-12-09 09:36
Thanks for the reproduction steps @bf-sodle , but the code you pasted doesn't do it for me.

**Comment by markus7811** [comment] 2020-12-09 09:39
I figured it out, that this line is causing problems:

https://github.com/aws/aws-cdk/blob/3530e8c758df3ea2fb26d654109e17a75f157b37/packages/%40aws-cdk/aws-eks/lib/cluster.ts#L1642

**Comment by rix0rrr** [comment] 2020-12-09 09:45
Honestly, because of the way the CDK works, `ec2.Vpc.fromVpcAttributes` with an `ImportValue` (or a `CfnParameter` for that matter), *can and will never work*.

You must have been getting infrastructure that was only using the first AZ/SubnetId of your list, right?

I mean, it *could* be done if you tell us how many elements there will be in the list, but not automatically.

**Comment by rix0rrr** [comment] 2020-12-09 09:48
Since the `#{Token[TOKEN.58]}` token wouldn't be resolved even in previous versions, I'm also struggling to see how any template synthesized before (which would still have that literal value in it), would have successfully deployed.

**Comment by markus7811** [comment] 2020-12-09 13:19
It was working ... i was using it with ssm parameter and fn.split to get an array ... (the parameter was written joining the subnetids with ",")

**Comment by rix0rrr** [comment] 2020-12-09 13:21
Can you show me some code of how you were using that Vpc imported in that way though? With what kind of resource(s) were you using it?

**Comment by markus7811** [comment] 2020-12-09 15:54
of course :-) As written above, I import eks clusters from ssm ...

```typescript
 this.clusterRef = eks.Cluster.fromClusterAttributes(this, id, {
      clusterName: props.clusterName,
      vpc: ec2.Vpc.fromVpcAttributes(this, 'Vpc', {
        availabilityZones: ssm.StringListParameter.fromStringListParameterName(this, 'VpcAvailabilityZonesSsm', `/eks/${props.clusterName}/EksClusterRef/VpcAvailabilityZones`).stringListValue,
        vpcId: vpcId,
      }),
      kubectlRoleArn: ssm.StringParameter.fromStringParameterName(
        this,
        'KubectlRoleArnSsm',
        `/eks/${props.clusterName}/EksClusterRef/KubectlRoleArn`,
      ).stringValue,
      kubectlSecurityGroupId: ssm.StringParameter.fromStringParameterName(
        this,
        'KubectlSecurityGroupIdSsm',
        `/eks/${props.clusterName}/EksClusterRef/KubectlSecurityGroupId`,
      ).stringValue,
      kubectlLayer: lambda.LayerVersion.fromLayerVersionArn(
        this,
        'KubectlLayer',
        ssm.StringParameter.fromStringParameterName(
          this,
          'KubectlLayerSsm',
          `/eks/${props.clusterName}/EksClusterRef/KubectlLayer`,
        ).stringValue,
      ),
      clusterCertificateAuthorityData: ssm.StringParameter.fromStringParameterName(
        this,
        'ClusterCertificateAuthorityDataSsm',
        `/eks/${props.clusterName}/EksClusterRef/ClusterCertificateAuthorityData`,
      ).stringValue,
      clusterEncryptionConfigKeyArn: ssm.StringParameter.fromStringParameterName(
        this,
        'ClusterEncryptionConfigKeyArnSsm',
        `/eks/${props.clusterName}/EksClusterRef/ClusterEncryptionConfigKeyArn`,
      ).stringValue,
      clusterSecurityGroupId: ssm.StringParameter.fromStringParameterName(
        this,
        'ClusterSecurityGroupIdSsm',
        `/eks/${props.clusterName}/EksClusterRef/ClusterSecurityGroupId`,
      ).stringValue,
      openIdConnectProvider: openIdConnectProvider,
      kubectlPrivateSubnetIds: cdk.Fn.split(',', ssm.StringParameter.fromStringParameterName(this, 'KubectlPrivateSubnetsStringSsm', `/eks/${props.clusterName}/EksClusterRef/KubectlPrivateSubnetsString`).stringValue),
      kubectlEnvironment: {
        http_proxy: ssm.StringParameter.fromStringParameterName(
          this,
          'KubectlEnvironmentHttpProxySsm',
          `/eks/${props.clusterName}/EksClusterRef/KubectlEnvironmentHttpProxy`,
        ).stringValue,
        https_proxy: ssm.StringParameter.fromStringParameterName(
          this,
          'KubectlEnvironmentHttpsProxySsm',
          `/eks/${props.clusterName}/EksClusterRef/KubectlEnvironmentHttpsProxy`,
        ).stringValue,
        no_proxy: ssm.StringParameter.fromStringParameterName(
          this,
          'KubectlEnvironmentNoProxySsm',
          `/eks/${props.clusterName}/EksClusterRef/KubectlEnvironmentNoProxy`,
        ).stringValue,
      },
    });
```
This was working till 1.76, but not with 1.77 ...
Tried to workaround by using vpc.fromLooukup (worked) and subnetSelection (didn't work - lacking fine grained selection). So at the moment, i think this is a baug?

**Comment by bf-sodle** [comment] 2020-12-09 19:02
On our end, we're importing the entire VPC as described above. We're then able to create an auto-scaling group like so, and it seems to span both all private subnets as it should.

```typescript
const vpc = ec2.Vpc.fromVpcAttributes(this, "importedVpc", {
  vpcId,
  availabilityZones,
  publicSubnetIds,
  privateSubnetIds,
  isolatedSubnetIds,
});

const clusterAsg = new autoscaling.AutoScalingGroup(this, "ecs-ec2-asg", {
  instanceType: ec2.InstanceType.of(instanceClass, instanceSize),
  machineImage,
  minCapacity,
  maxCapacity,
  desiredCapacity,
  vpc,
  allowAllOutbound: false,
  associatePublicIpAddress: false,
  vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE },
  role,
});
```

**Comment by rix0rrr** [comment] 2020-12-09 19:03
> it seems to span both all private subnets as it should.

Blows my mind, because I feel like that wouldn't work. I will look into that.

**Comment by bf-sodle** [comment] 2020-12-09 19:17
I believe the magic is in using the `SubnetSelection` type (the value of `vpcSubnets` when creating the ASG). It produces the following CloudFormation, which resolves our imported value into an array of subnets just fine.

```yaml
  ecsec2asgASGBC05D157:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "4"
      MinSize: "2"
      DesiredCapacity: "2"
      LaunchConfigurationName:
        Ref: ecsec2asgLaunchConfig487A86FD
      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue: myPrivateSubnetIds
```

**Comment by markus7811** [comment] 2020-12-10 21:39
I solved it for my use case by switching to VPC fromLookup instead of fromAttributes and switching from ssm.StringParameter.fromStringParameterName to ssm.StringParameter.valueFromLookup for the subnet part. Now the warnings are displayed and it works like it should ...

**Closed** 2020-12-14 09:07 UTC
Labels: @aws-cdk/core, bug, needs-triage

**Comment by adriantaut** [comment] 2021-01-04 13:52
@rix0rrr not sure if I'm missing something, but I'm still facing the same issue with `aws-cdk@1.82.0` when attempting to spin up an EKS cluster, please find my code below:

```ts
const vpc = Vpc.fromVpcAttributes(scope, 'DefaultVpc', {
    vpcId: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/VpcId`),
    availabilityZones: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/AvailabilityZones'),
    privateSubnetIds: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/PrivateSubnetIds'),
    privateSubnetRouteTableIds: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/PrivateSubnetRouteTableIds'),
    publicSubnetIds: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/PublicSubnetIds'),
    publicSubnetRouteTableIds: ssm.StringParameter.valueForStringParameter(scope, `${basePath}/PublicSubnetRouteTableIds'),
  });

        const cluster = new eks.Cluster(this, 'DetestadrCluster', {
            vpc: vpc,
            vpcSubnets: [ { subnetType: ec2.SubnetType.PRIVATE } ],
            defaultCapacity: 0,
            version: eks.KubernetesVersion.V1_18
        });
```

**Comment by jahtoe** [comment] 2021-02-26 14:03
Greetings,

Is the [LAMP stack scalable and durable](https://s3.us-west-2.amazonaws.com/cloudformation-templates-us-west-2/LAMP_Multi_AZ.template) example on on the [example templates to provision application frameworks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-appframeworks-us-west-2.html) AWS page as good example of a template that can lead to the error when trying to resolve the subnets from the parameter?

Such that if you set a default for the subnets as follows

`  "Subnets" : {
      "Type" : "List<AWS::EC2::Subnet::Id>",
      "Description" : "The list of SubnetIds in your Virtual Private Cloud (VPC)",
      "ConstraintDescription" : "must be a list of at least two existing subnets associated with at least two different availability zones. They should be residing in the selected Virtual Private Cloud.",
      "Default": [ "subnet-123a351e", "subnet-456b351e" ]
  },`

Which is referenced in the AutoScaling resource by 

`"VPCZoneIdentifier" : { "Ref" : "Subnets" }`

When trying to resolve an item in the CfnAutoScalingGroup C.getVpcZoneIdentifier() list, using the template this.resolve(item) method, the error

`Found an encoded list token string in a scalar string context. Use 'Fn.select(0, list)' (not 'list[0]') to extract elements from token lists.
`
is Expected?


And a solution is to replace the reference to the subnet parameter as

`"VPCZoneIdentifier" :  [ "subnet-123a351e", "subnet-456b351e" ]`

Or is there a coding solution for this and a way to recognize this problem?

Regards
Alex
