### ISSUE TITLE
S3EventSource in different stack causes cyclic dependency error

### ISSUE THREAD

**Issue by vertti** [aws/aws-cdk#5010] opened 2019-11-13 13:39 UTC
### Reproduction Steps

With app like:
```
const s3Stack = new S3Stack(app, 'TtpS3Stack', { vpc: vpcStack.vpc })
new TtpImporterStack(app, 'TtpImporterStack', { importBucket: s3Stack.importBucket })
```
where the first creates a bucket to `s3Stack.importBucket` and the second stack creates a lambda and an `S3EventSource` to trigger the lambda:

```
    ingestLambda.addEventSource(
      new S3EventSource(props.importBucket, {
        events: [s3.EventType.OBJECT_CREATED],
      })
    )
```
causes the following error:
```
Error: 'TtpImporterStack' depends on 'TtpS3Stack' (TtpImporterStack -> TtpS3Stack/TtpImportBucket/Resource.Arn). Adding this dependency (TtpS3Stack -> TtpImporterStack/TTPIngestFunction/Resource.Arn) would create a cyclic reference.
```

Removing just the above S3EventSource snippet removes what ever is causing the cyclic dependency.

### Error Log

```
Error: 'TtpImporterStack' depends on 'TtpS3Stack' (TtpImporterStack -> TtpS3Stack/TtpImportBucket/Resource.Arn). Adding this dependency (TtpS3Stack -> TtpImporterStack/TTPIngestFunction/Resource.Arn) would create a cyclic reference.
    at S3Stack.addDependency (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/stack.ts:312:15)
    at TtpImporterStack.prepareCrossReference (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/stack.ts:795:24)
    at S3Stack.prepare (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/stack.ts:651:37)
    at Function.prepare (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/construct.ts:81:28)
    at Function.synth (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/construct.ts:40:10)
    at App.synth (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/app.ts:142:36)
    at process.App.process.once (/home/vertti/dev/kesko/k-ruoka-product-service/node_modules/@aws-cdk/core/lib/app.ts:121:45)
    at Object.onceWrapper (events.js:286:20)
    at process.emit (events.js:198:13)
    at process.EventEmitter.emit (domain.js:448:20)
```

### Environment

  - **CLI Version      :** 1.5.0
  - **Framework Version:** 1.5.0
  - **OS               :** Ubuntu
  - **Language         :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by richardhboyd** [comment] 2019-11-28 03:24
This is a known issue with S3Notifications and Lambda. I think there's even an AWS Docs page that explains it. The only solution available currently is a two step cfn deploy that CDK doesn't really support, though we could probably do more to make this limitation clear.

https://medium.com/@windix/s3-bucket-notification-to-lambda-in-cloudformation-without-circular-reference-f8f56ec5342c

**Comment by nija-at** [comment] 2020-08-05 14:35
Duplicate of https://github.com/aws/aws-cdk/issues/4641

**Closed by nija-at** 2020-08-05 14:35 UTC
Labels: @aws-cdk/aws-lambda, bug, p2
