### ISSUE TITLE
[lambda] Auto-generated Lambda Version structure change causes runtime error during deploy

### ISSUE THREAD

**Issue by blimmer** [aws/aws-cdk#10274] opened 2020-09-09 19:56 UTC
Upon upgrading my CDK application from 1.56.0 to 1.62.0, I received the following runtime error:

```
1:22:26 PM | CREATE_FAILED        | AWS::Lambda::Version                | ContentPreviewLamb...b465a413
94e502e55a
A version for this Lambda function exists ( 6 ). Modify the function to create a new version.

	new Version (/Users/blimmer/code/project/node_modules/@aws-cdk/aws-lambda/lib/lambda-version.t PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack          | ContentPrevi
s:186:21)
	\_ NodejsFunction.get currentVersion [as currentVersion] (/Users/blimmer/code/project/node_mod4e502e55a]. The following resource(s) failed to update: [CDKMetadata].
[███████████████████▎······································] (2/6)

1:22:26 PM | CREATE_FAILED        | AWS::Lambda::Version                | ContentPreviewLambda/CurrentV
ersion
A version for this Lambda function exists ( 6 ). Modify the function to create a new version.
1:22:28 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack          | ContentPrevi
ew
The following resource(s) failed to create: [ContentPreviewLambdaCurrentVersionF2162CC0eed68d0edb0f5bb4
65a41394e502e55a]. The following resource(s) failed to update: [CDKMetadata].
```

I believe this issue is caused by this output I saw in the CDK diff:

```
[-] AWS::Lambda::Version ContentPreviewLambdaCurrentVersionF2162CC0c8fa0af5a3ff110c26ef41ef03ce39ee orphan
[+] AWS::Lambda::Version ContentPreviewLambda/CurrentVersion ContentPreviewLambdaCurrentVersionF2162CC01e97584f747339e300741474cc3e51c0 
```

I think because of this naming convention change (from `ContentPreviewLambdaCurrentVersionF2162CC0c8fa0af5a3ff110c26ef41ef03ce39ee` to `ContentPreviewLambda/CurrentVersion ContentPreviewLambdaCurrentVersionF2162CC01e97584f747339e300741474cc3e51c0`), it's trying to recreate the version that already exists.

I worked around the problem by making a small, meaningless change to a `console.log` statement, which seems to have resolved the issue.

### Reproduction Steps

1. Create a lambda version with aws-cdk version `<= 1.56.0` (I think the naming convention was changed [in 1.57.0](https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#1570-2020-08-07))
1. Upgrade to `>= 1.57.0`
1. Try to `cdk deploy` that lambda version

I think you should see an error message similar to that above.

### What did you expect to happen?

I expected for the issue to be automatically worked around, whether by creating a new Version or otherwise.

### What actually happened?

A runtime error occurred when trying to deploy, stating that the Lambda Version already existed.

### Environment

  - **CLI Version      :** 1.62.0 (build 8c2d7fc)
  - **Framework Version:** 1.62.0
  - **Node.js Version:**  v12.18.3
  - **OS               :** macOS
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by nija-at** [comment] 2020-09-17 13:26
I'm not able to reproduce this error. I've used the following CDK app, deployed it using CDK 1.56.0 and then upgraded to 1.62.0 and successfully deployed the update again.

```ts
#!/usr/bin/env node
import { App, Stack } from '@aws-cdk/core';
import { Function, Code, Runtime, Version } from '@aws-cdk/aws-lambda';
import { LambdaDestination } from '@aws-cdk/aws-lambda-destinations';

const app = new App();
const stack = new Stack(app, 'mystack');

const fn = new Function(stack, 'myfn', {
  code: Code.fromInline('foo'),
  runtime: Runtime.NODEJS_12_X,
  handler: 'index.handler',
});

new Version(stack, 'myversion', {
  lambda: fn
});
```

**Comment by blimmer** [comment] 2020-09-17 13:35
Hey @nija-at - this lambda is a Lambda@Edge, associated with a CloudFront Distribution. Maybe that's a key in reproducing the error from 1.56?

I was able to work around this, so if we can't repro this, maybe we close the issue for now and let others chime in if they experience the same problem.

**Comment by nija-at** [comment] 2020-09-17 13:51
The failure you've posted is for `AWS::Lambda::Version`, so it's likely not going to change based on lambda@edge situation.

I'm closing this for now. Feel free to post or open a new issue if you find more information.

**Closed by nija-at** 2020-09-17 13:51 UTC
Labels: @aws-cdk/aws-lambda, bug, needs-triage, response-requested
