### ISSUE TITLE
aws-lambda: Cannot grant url invoke by ArnPrincipal

### ISSUE THREAD

**Issue by 95Wictor** [aws/aws-cdk#31059] opened 2024-08-08 06:03 UTC
### Describe the bug

The CDK fails to synth if an ArnPrincipal is given to aws-lambda.Function.grantInvokeUrl.

### Expected Behavior

grantInvokeUrl should accept ArnPrincipal, as grantInvoke does and as aws-s3.Bucket.grantRead does.

### Current Behavior

En error occurs during synthesis: Resolution error: ID components may not include unresolved tokens: InvokeFunctionUrlArnPrincipal(${Token[TOKEN.59]}).

### Reproduction Steps

Create a new CDK Typescript app, and replace the sample stack code with the following. Then run `npx cdk synth`.
```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Bucket } from 'aws-cdk-lib/aws-s3';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { ArnPrincipal, ServicePrincipal } from 'aws-cdk-lib/aws-iam';

export class ProductionStack extends cdk.Stack {
	constructor(scope: Construct, id: string, props?: cdk.StackProps) {
		super(scope, id, props);

		// These resources will grant permissions to a Lambda function
		const someBucket = new Bucket(this, 'someBucket', {
			removalPolicy: cdk.RemovalPolicy.DESTROY,
		});
		const lambdaThatWillGrant = new Function(this, 'someLambda', {
			runtime: Runtime.PYTHON_3_12,
			handler: 'handler',
			code: Code.fromInline('def handler(context):\n\treturn "hi"'),
		});
		lambdaThatWillGrant.applyRemovalPolicy(cdk.RemovalPolicy.DESTROY);

		// This lambda function will have permissions to use the above resources
		const lambdaThatWillInvoke = new Function(this, 'grantee', {
			runtime: Runtime.PYTHON_3_12,
			handler: 'handler',
			code: Code.fromInline('def handler(context):\n\treturn "hi, pretend I am invoking the other lambda or reading form S3"'),
		});
		lambdaThatWillInvoke.applyRemovalPolicy(cdk.RemovalPolicy.DESTROY);

		// Now we grant permissions.
		const arnPrincipal = new ArnPrincipal(lambdaThatWillInvoke.functionArn);
		someBucket.grantRead(arnPrincipal); //works
		// Below line does not work. Synth error: " Resolution error: ID components may not include unresolved tokens: InvokeFunctionUrlArnPrincipal(${Token[TOKEN.59]})."
		lambdaThatWillGrant.grantInvokeUrl(arnPrincipal);

		// To get around this issue, we can use a conditional principal
		const conditionalPrincipal = new ServicePrincipal('lambda.amazonaws.com').withConditions({
			// Creating the condition has its own problems, but these would be separate issues
			// 1) The AWS here MUST be lowercase, despite it showing uppercase in the AWS console.
			//    https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html (It should be case-insensitive.)
			// 2) We also cannot use StringEquals for Lambda, though we if the bucket was granting to this principal.
			"ArnLike": { "aws:SourceArn": lambdaThatWillInvoke.functionArn }
		});
		lambdaThatWillGrant.grantInvokeUrl(conditionalPrincipal); // works
	}
}
```

### CDK CLI Version

2.151.0 (build b8289e2)

### Node.js Version

20.9.0

### OS

Windows 11

### Language

TypeScript

### Language Version

5.5.4

**Comment by ashishdhingra** [comment] 2024-08-08 21:17
@95Wictor Good afternoon. Thanks for opening the issue. I was able to reproduce the issue at my end getting error `Error: Resolution error: ID components may not include unresolved tokens: InvokeFunctionUrlArnPrincipal(${Token[TOKEN.309]}).`.

Here are my findings for the root cause:
- For [lambda.grantInvokeUrl()](https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-lambda/lib/function-base.ts#L490) scenario, the logic constructs an identifier via statement `const identifier = `InvokeFunctionUrl${grantee.grantPrincipal}`; // calls the .toString() of the principal``. As noted in the comment , it invokes `toString()` method of the principal. The identifier is used to maintain map Function URL invocation grants.
  - For [ArnPrincipal](https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L435), [toString()](https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L448) is implemented like ``return `ArnPrincipal(${this.arn})`;``. This relies on `this.arn`. For your use case, `this.arn` is the ARN of Lambda function which would invoke. The ARN is not yet resolved until the CDK stack is deployed. Hence, it is tokenized.
  - For [ServicePrincipal](https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L531C14-L531C30), [toString()](https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-iam/lib/principals.ts#L573) is implemented like ``return `ServicePrincipal(${this.service})`;``. This relies on the constant string `this.service`, which in your use case is `lambda.amazonaws.com`.

  Since, ARN for an `ArnPrincipal` is tokenized, we are getting the error.

- For [s3.grantRead()](https://github.com/aws/aws-cdk/blob/79b5cd2390508e7b5c3d5c93001e30387bf88a4e/packages/aws-cdk-lib/aws-s3/lib/bucket.ts#L768), it doesn't rely on generating identifier which might call `toString()` method of the underlying Principal. Hence `ArnPrincipal` works in this scenario.

The reason for using a map for `lambda.grantInvokeUrl()`, (per code comment) is to memoize the result so subsequent grantInvoke() calls are idempotent. Hence, `ArnPrincipal` would not work in this scenario.

Thanks,
Ashish

**Comment by 95Wictor** [comment] 2024-08-10 07:42
Thanks for looking into it. I see you've added the "response-requested" label, but I don't see any questions in your comment. Do you need anything from me?

**Comment by ashishdhingra** [comment] 2024-08-10 16:12
> Thanks for looking into it. I see you've added the "response-requested" label, but I don't see any questions in your comment. Do you need anything from me?

@95Wictor The response-requested label was added so that you could review the findings. Based on the findings, this is not a bug. Hence, please confirm if we are good to close the issue.

Thanks,
Ashish

**Closed** 2024-08-11 15:44 UTC
Labels: bug, response-requested, @aws-cdk/aws-lambda, p3
