### ISSUE TITLE
CDK CodePipeline causes `Circular dependency between resources` error in UpdatePipeline step

### ISSUE THREAD

**Issue by phongnlu** [aws/aws-cdk#18704] opened 2022-01-28 00:49 UTC
### What is the problem?

Hello,

CodePipeline has been working fine until cdk 2.9.0. It started throwing `Circular dependency between resources` error, even with basic CodePipeline like this:

new CodePipeline(this, 'FooPipeline', {
  pipelineName: 'FooPipeline',
  synth: new ShellStep('Synth', {
    input: CodePipelineSource.connection(`${owner}/${repo}`, 'branch', {
      connectionArn: `arn:aws:codestar-connections:${region}:xxxxxxxxxx:connection/xxx`,
    }),
    commands: [],    
  }),
});

Here's the error:

FooCiCdStack failed: Error [ValidationError]: Circular dependency between resources: [FooPipelineBuildSynthCdkBuildProjectE18FAEBF, FooPipelineBuildSynthCdkBuildProjectRoleDefaultPolicy46A3C53B, FooPipelineBuildSynthCodePipelineActionRoleDefaultPolicy8CA65E66, FooPipelineUpdatePipelineSelfMutation5E645806, FooPipelineUpdatePipelineSelfMutationRoleDefaultPolicy45B46F02, FooPipeline8C1F4A35, FooPipelineUpdatePipelineSelfMutateCodePipelineActionRoleDefaultPolicy819D6ED3]
    at Request.extractError (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/xxxxx/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-01-28T00:23:05.830Z,
  requestId: 'xxx',
  statusCode: 400,
  retryable: false,
  retryDelay: 310.88243961233576
}
Circular dependency between resources: [FooPipelineBuildSynthCdkBuildProjectE18FAEBF, FooPipelineBuildSynthCdkBuildProjectRoleDefaultPolicy46A3C53B, FooPipelineBuildSynthCodePipelineActionRoleDefaultPolicy8CA65E66, FooPipelineUpdatePipelineSelfMutation5E645806, FooPipelineUpdatePipelineSelfMutationRoleDefaultPolicy45B46F02, FooPipeline8C1F4A35, FooPipelineUpdatePipelineSelfMutateCodePipelineActionRoleDefaultPolicy819D6ED3]

It seems that this error likely happens to existing pipeline rather new pipeline deployed the first time. I did some investigation, by validating the CloudFormation template with some tracing for the dependency graph and noticed that there's indeed circular referencing between following resources:

FooPipelineUpdatePipelineSelfMutation5E645806 -> FooPipeline8C1F4A35
FooPipeline8C1F4A35 -> FooPipelineUpdatePipelineSelfMutation5E645806

This happens with cdk 2.9.0, switching back to cdk 2.8.0 fixes the issue so looks like this is a regression issue.

### Reproduction Steps

new CodePipeline(this, 'FooPipeline', {
  pipelineName: 'FooPipeline',
  synth: new ShellStep('Synth', {
    input: CodePipelineSource.connection(`${owner}/${repo}`, 'branch', {
      connectionArn: `arn:aws:codestar-connections:${region}:xxxxxxxxxx:connection/xxx`,
    }),
    commands: [],    
  }),
});

### What did you expect to happen?

Stack is built, deployed, updated correctly

### What actually happened?

Stack failed with Error [ValidationError]: Circular dependency between resources

### CDK CLI Version

2.9.0

### Node.js Version

14.17.6

### OS

MacOs Catalina

### Language

Typescript

### Language Version

4.2.4

**Comment by skinny85** [comment] 2022-01-28 00:57
Duplicate of https://github.com/aws/aws-cdk/issues/18673.

**Closed by skinny85** 2022-01-28 00:57 UTC
Labels: bug, @aws-cdk/aws-codepipeline, needs-triage
