### ISSUE TITLE
(aws-cognito): Pinpoint integration

### ISSUE THREAD

**Issue by phuctm97** [aws/aws-cdk#15427] opened 2021-07-05 16:57 UTC
Add support for analytics configuration option in user pool client.

### Use Case

Integrate with Pinpoint

### Proposed Solution

Use L1 CfnUserPoolClieng AnalyticsConfiguration option, also probably create service-linked role for Cognito to put events to Pinpoint.

### Other

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by michaelgmcd** [comment] 2021-07-14 13:58
I tried opening a PR for this, but Pinpoint is still in the "experimental" state, so it can't be a dependency of aws-cognito. I could probably work around this, but there's an easy workaround in the meantime:

```js
const cfnUserPoolClient = this.userPoolClient.node.defaultChild as CfnUserPoolClient;

cfnUserPoolClient.analyticsConfiguration = {
  applicationArn: pinpointApp.attrArn,
  userDataShared: true,
};
```

**Comment by phuctm97** [comment] 2021-07-15 01:18
> I tried opening a PR for this, but Pinpoint is still in the "experimental" state, so it can't be a dependency of aws-cognito. I could probably work around this, but there's an easy workaround in the meantime:
> 
> ```ts
> const cfnUserPoolClient = this.userPoolClient.node.defaultChild as CfnUserPoolClient;
> 
> cfnUserPoolClient.analyticsConfiguration = {
>   applicationArn: pinpointApp.attrArn,
>   userDataShared: true,
> };
> ```

Thanks for sharing @michaelgmcd, will this work? As I remember `analyticsConfiguration` also requires a serviced link `role` param which should declare AWS Cognito permission to upload the Pinpoint project.

**Comment by michaelgmcd** [comment] 2021-07-15 03:19
Cloudformation will generate one if you don't specify a "role" parameter.

**Comment by phuctm97** [comment] 2021-07-15 07:11
> Cloudformation will generate one if you don't specify a "role" parameter.

That's great news! Thanks, Michael!

So the step now is to bring Pinpoint pass "experimental" state, which I can imagine is to build the whole L2 of Pinpoint module?

**Comment by nija-at** [comment] 2021-07-15 14:36
This is a duplicate of https://github.com/aws/aws-cdk/issues/9731

**Closed by nija-at** 2021-07-15 14:36 UTC
Labels: @aws-cdk/aws-cognito, @aws-cdk/aws-pinpoint, feature-request, needs-triage

**Comment by kg-pb** [comment] 2023-07-21 05:27
> I tried opening a PR for this, but Pinpoint is still in the "experimental" state, so it can't be a dependency of aws-cognito. I could probably work around this, but there's an easy workaround in the meantime:
> 
> ```ts
> const cfnUserPoolClient = this.userPoolClient.node.defaultChild as CfnUserPoolClient;
> 
> cfnUserPoolClient.analyticsConfiguration = {
>   applicationArn: pinpointApp.attrArn,
>   userDataShared: true,
> };
> ```

How to implement same in python?
