### ISSUE TITLE
[cli] Improve error message output when failing to deploy the nested stack

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#6402] opened 2020-02-22 12:50 UTC
Print out the detail error message of nested stack in console. It would be useful for finding out what's wrong happened, then fix it quickly.

### Use Case

I have a large app consists of few nested stacks. When the deployment failure happens in nested stack, there is no helpful error message in CDK's output. It just reports the nested stack deployed failure. I have to check the event output to see what's wrong happened in nested stack from CloudFormation web console.

The user experience would be much worse when deploying the stack from scratch. The nested stack will be deleted totally when the stack failed to be deployed. The developer can NOT find any helpful information to see what caused the failure. The developer have to comment the resources in nested stack to find out which resource causing the failure(like a `git bisect`), but it's really annoying and slow to find out the root cause!

### Proposed Solution

Print out the detail output message of nested stack in deployment.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by nickls** [comment] 2022-06-04 21:20
This lack of this feature makes it very difficult to manage changes to substacks. And incentivise developers to make different architectural changes.

It also make it nearly impossible to figure out what is wrong when launching a new sub stack.

**Comment by TheRealAmazonKendra** [comment] 2023-01-26 00:21
Duplicate of https://github.com/aws/aws-cdk/issues/5974

**Closed by TheRealAmazonKendra** 2023-01-26 00:21 UTC
Labels: p2, feature-request, package/tools, effort/small, in-progress
