### ISSUE TITLE
 aws-ecs-patterns (QueueProcessingFargateService): Allow providing a Task Role during creation

### ISSUE THREAD

**Issue by VarshaVid** [aws/aws-cdk#23625] opened 2023-01-10 08:06 UTC
### Describe the feature

Current implementation of `QueueProcessingFargateService` does not allow for the task role to be provided by user during initialization. Other `aws-ecs-patterns` constructs like `NetworkLoadBalancedFargateService` allows provinding the role through the optional `taskDefinition` parameter.
https://github.com/aws/aws-cdk/blob/fd5808f47111c0f72050f60e414df7f3f4ded6aa/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts#L19

### Use Case

We have a queue-processing application that needs to access on multiple other resources whose permissions need to be configured for the Task Role, and the references for the resources (e.g. S3 bucket name) also need to be provided as the Environment Variables to the task. This creates a cyclic dependency since the resource links are needed before the Fargate Service creation (so they can be set as env variables) but the permissions can only be configured after the Fargate Service creation (because the Task Role is not available before).

Being able to create the Role before the Fargate Service creation will simplify this.

### Proposed Solution

An optional parameter can be added to the `QueueProcessingFargateServiceProps` that can be used while initializing the `taskDefinition` here: https://github.com/aws/aws-cdk/blob/fd5808f47111c0f72050f60e414df7f3f4ded6aa/packages/%40aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts#L124-L128

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

1.141

### Environment details (OS name and version, etc.)

NodeJS-14

**Comment by peterwoodworth** [comment] 2023-01-11 21:13
Closing as duplicate of https://github.com/aws/aws-cdk/issues/16297, thanks for reporting!

**Closed by peterwoodworth** 2023-01-11 21:13 UTC
Labels: feature-request, needs-triage, @aws-cdk/aws-ecs-patterns
