### ISSUE TITLE
(@aws-cdk/aws-s3): Missing attribute of `CfnAccessPoint`

### ISSUE THREAD

**Issue by HsiehShuJeng** [aws/aws-cdk#15930] opened 2021-08-07 03:55 UTC
At the L1 level of `CfnAccessPoint`, i.e. `AWS::S3::AccessPoint`, there is an [attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-accesspoint.html#cfn-s3-accesspoint-name) of `name`. Yet at the moment, when I attempted to deploy an S3 access point via the CDK, I encountered the following error message:

```typescript
const adminAccessPoint = new s3.CfnAccessPoint(this, 'AdminS3AccessPoint', {
      bucket: bucket.bucketName,
      name: 'some-name',
    });
```
```bash
Argument of type '{ bucket: string; name: string; }' is not assignable to parameter of type 'CfnAccessPointProps'.
  Object literal may only specify known properties, and 'name' does not exist in type 'CfnAccessPointProps'.
```

### Reproduction Steps
```typescript
import * as s3 from '@aws-cdk/aws-s3';
import * as cdk from '@aws-cdk/core';

class TypescriptStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const testBucket = new s3.Bucket(this, 'TestBucket', {
      bucketName: `test-bucket-${cdk.Aws.ACCOUNT_ID}`,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true
    });
    const s3AccessPoint = new s3.CfnAccessPoint(this, 'S3AccessPoint', {
      bucket: testBucket.bucketName,
      name: 'something-wrong',
    });

  }
}

const app = new cdk.App();
new TypescriptStack(app, 'TypescriptStack', {
  stackName: 'CfnAccessPoint-issue-reproduction',
});


```

### What did you expect to happen?
The same declaration in the previous versions of the CDK once worked, and it should work in the latest CDK version at the L1 level.

### What actually happened?
The same declaration in the previous versions of the CDK once worked, yet the `name` attribute is missing now.

### Environment
- CDK version: `1.117.0 (build 0047c98)`
- OS:
  ```
  ProductName:    macOS
  ProductVersion: 11.4
  BuildVersion:   20F71
  ```

- Language: TypeScript (4.3.5)

--- 

This is :bug: Bug Report

**Comment by otaviomacedo** [comment] 2021-08-09 10:41
Hi, @HsiehShuJeng 

Is the problem still happening? This was caused by a breaking change in the CloudFormation template. The issue was fixed on Friday (6 August).

**Comment by casperhartfraedom** [comment] 2021-08-17 22:10
I had the same issue with `1.118.0`. Upgrading to the recent release `1.119.0` appears to have fixed it.

**Closed** 2021-08-20 09:21 UTC
Labels: bug, response-requested, @aws-cdk/aws-s3, needs-triage
