### ISSUE TITLE
[@aws-cdk/core] cdk synth slowness on a new MacBook

### ISSUE THREAD

**Issue by moltar** [aws/aws-cdk#10668] opened 2020-10-03 06:11 UTC
Running `cdk synth` within the exact same codebase:

 * `2.9 Ghz Quad-Core Intel Core i7`: 12s
 * `2.4 GHz 8-Core Intel Core i9`: 1m49s

### Reproduction Steps

My stack is not that complex. I have 9 lambda functions across 3 nested stacks.

### What did you expect to happen?

To run faster.

### What actually happened?

Runs slow.

### Environment

  - **CLI Version      : 1.64.1 (build 14a8c8d)**
  - **Framework Version: 1.64.1**
  - **Node.js Version:** v12.18.4
  - **OS               : macOS Catalina 10.15.7 (19H2) **
  - **Language (Version):** TypeScript (3.9.7)

### Other

N/A

--- 

This is :bug: Bug Report

**Comment by moltar** [comment] 2020-10-03 06:23
Hm, seems like no matter how far back I rewind the repo, it still takes forever. So maybe it's not related to the Aspect change.

I have recently switched to a new MacBook (`2.4 GHz 8-Core Intel Core i9`), wonder if that has anything to do with it.

I will try this on an older MacBook later on.

**Comment by moltar** [comment] 2020-10-03 06:46
Pretty much edited everything in the issue to reflect new findings.

**Comment by moltar** [comment] 2020-10-03 06:54
I have tried many things, including disabling stack trace via `CDK_DISABLE_STACK_TRACE` flag, but I cannot make any dent in the time it takes to synth.

Please let me know if there is any other flags I can try or any other debug things I can do.

Thanks.

**Comment by moltar** [comment] 2020-10-03 10:49
I'm not really an expert on profile, so forgive me if I shared the wrong info, but I did run:

```sh
node --prof node_modules/.bin/cdk synth
```

And then:

```sh
node --prof-process isolate-0x108008000-39374-v8.log
```

I'm sharing what I believe are relevant bits, but if there is anything else you'd like to see - let me know. I kept the log files.

```
[Summary]:
   ticks  total  nonlib   name
     13    1.3%    1.3%  JavaScript
    976   95.2%   98.5%  C++
     61    6.0%    6.2%  GC
     34    3.3%          Shared libraries
      2    0.2%          Unaccounted
```

```
[C++]:
   ticks  total  nonlib   name
    259   25.3%   26.1%  t node::fs::Read(v8::FunctionCallbackInfo<v8::Value> const&)
    190   18.5%   19.2%  t __ZN2v88internalL37Builtin_Impl_Stats_UnsupportedThrowerEiPmPNS0_7IsolateE
    126   12.3%   12.7%  T _open$NOCANCEL
    108   10.5%   10.9%  t node::fs::InternalModuleStat(v8::FunctionCallbackInfo<v8::Value> const&)
     74    7.2%    7.5%  T node::contextify::ContextifyContext::CompileFunction(v8::FunctionCallbackInfo<v8::Value> const&)
     49    4.8%    4.9%  t node::fs::InternalModuleReadJSON(v8::FunctionCallbackInfo<v8::Value> const&)
     40    3.9%    4.0%  T node::native_module::NativeModuleEnv::CompileFunction(v8::FunctionCallbackInfo<v8::Value> const&)
     21    2.0%    2.1%  T _vm_copy
     14    1.4%    1.4%  T ___ulock_wait
     10    1.0%    1.0%  T __kernelrpc_thread_policy_set
      9    0.9%    0.9%  t node::fs::Open(v8::FunctionCallbackInfo<v8::Value> const&)
      8    0.8%    0.8%  T void node::StreamBase::JSMethod<&(int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&))>(v8::FunctionCallbackInfo<v8::Value> const&)
      6    0.6%    0.6%  t node::url::(anonymous namespace)::Parse(v8::FunctionCallbackInfo<v8::Value> const&)
      4    0.4%    0.4%  t _tiny_malloc_should_clear
      4    0.4%    0.4%  T node::fs::Close(v8::FunctionCallbackInfo<v8::Value> const&)
      4    0.4%    0.4%  T _task_policy_set
      4    0.4%    0.4%  T _mach_msg_server
      3    0.3%    0.3%  T node::TTYWrap::New(v8::FunctionCallbackInfo<v8::Value> const&)
      3    0.3%    0.3%  T _kdebug_typefilter
      2    0.2%    0.2%  t std::__1::basic_istream<wchar_t, std::__1::char_traits<wchar_t> >& std::__1::__input_arithmetic<long long, wchar_t, std::__1::char_traits<wchar_t> >(std::__1::basic_istream<wchar_t, std::__1::char_traits<wchar_t> >&, long long&)
      2    0.2%    0.2%  t node::(anonymous namespace)::ProcessWrap::Spawn(v8::FunctionCallbackInfo<v8::Value> const&)
      2    0.2%    0.2%  t __ZN2v88internal11StringShape33DispatchToSpecificTypeWithoutCastIZNS1_22DispatchToSpecificTypeIZNS0_6String3GetEiE19StringGetDispatchertJRiEEET0_S4_DpOT1_E17CastingDispatchertJRS4_S6_EEES7_SA_
      2    0.2%    0.2%  T node::binding::GetInternalBinding(v8::FunctionCallbackInfo<v8::Value> const&)
      2    0.2%    0.2%  T ___sflags
      1    0.1%    0.1%  t unsigned long std::__1::__hash_table<node::CleanupHookCallback, node::CleanupHookCallback::Hash, node::CleanupHookCallback::Equal, std::__1::allocator<node::CleanupHookCallback> >::__erase_unique<node::CleanupHookCallback>(node::CleanupHookCallback const&)
      1    0.1%    0.1%  t std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> > std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char> >, char const*, char const*, char const*, std::__1::ios_base&, char)
      1    0.1%    0.1%  t std::__1::messages_byname<char>::~messages_byname()
      1    0.1%    0.1%  t non-virtual thunk to node::http2::Http2Stream::IsClosing()
      1    0.1%    0.1%  t node::os::GetUserInfo(v8::FunctionCallbackInfo<v8::Value> const&)
      1    0.1%    0.1%  t node::fs::Stat(v8::FunctionCallbackInfo<v8::Value> const&)
      1    0.1%    0.1%  t node::fs::ReadDir(v8::FunctionCallbackInfo<v8::Value> const&)
      1    0.1%    0.1%  t node::fs::FStat(v8::FunctionCallbackInfo<v8::Value> const&)
      1    0.1%    0.1%  t _tiny_try_realloc_in_place
      1    0.1%    0.1%  t _tiny_free_no_lock
      1    0.1%    0.1%  t _small_malloc_should_clear
      1    0.1%    0.1%  t _rack_region_insert
      1    0.1%    0.1%  t _nanov2_find_block_and_allocate
      1    0.1%    0.1%  t _free_small
      1    0.1%    0.1%  t __platform_memmove$VARIANT$Haswell
      1    0.1%    0.1%  t __cxxabiv1::__function_type_info::~__function_type_info()
      1    0.1%    0.1%  T std::__1::__next_prime(unsigned long)
      1    0.1%    0.1%  T _read$NOCANCEL
      1    0.1%    0.1%  T _fopen
      1    0.1%    0.1%  T __platform_strncmp
      1    0.1%    0.1%  T ___rec_fpipe
      1    0.1%    0.1%  T __ZNK2v88internal21ObjectLiteralProperty18IsCompileTimeValueEv
      1    0.1%    0.1%  T __ZN2v88internal9Accessors23FunctionPrototypeGetterENS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEE
      1    0.1%    0.1%  T __ZN2v88internal5Scope28AllocateVariablesRecursivelyEv
      1    0.1%    0.1%  T __ZN2v88internal5Scope17LookupInScopeInfoEPKNS0_12AstRawStringEPS1_
      1    0.1%    0.1%  T __ZN2v88internal16DeclarationScopeC1EPNS0_4ZoneEPNS0_5ScopeENS0_9ScopeTypeENS0_12FunctionKindE
      1    0.1%    0.1%  T __ZN2v88internal16DeclarationScope7AnalyzeEPNS0_9ParseInfoE
      1    0.1%    0.1%  T __ZN2v88internal15AstValueFactory24GetOneByteStringInternalENS0_6VectorIKhEE
      1    0.1%    0.1%  T __ZN2v88internal11VariableMap6LookupEPKNS0_12AstRawStringE
      1    0.1%    0.1%  T __ZN2v820EscapableHandleScopeC2EPNS_7IsolateE
```

**Comment by moltar** [comment] 2020-10-03 11:20
Oh my! Found the issue!

I had a dir `./data` in my project root, which I used for a bunch of testing data. This dir was `.gitignore`'ed from the project.

The dir contained ~ 20,000 of small and medium sized `*.json.gz` files. Total size was ~ 3 GB.

I just fetched these files from S3 to test bulk loading locally. This is not relevant to CDK or issue at hand, just providing some more context.

For some reason `cdk` assumed that these files were relevant to the project and it was copying them to the `cdk.out` directory.

Any ideas?

**Comment by rix0rrr** [comment] 2020-10-05 08:10
What kind of assets do you have in your app?

**Comment by moltar** [comment] 2020-10-05 08:18
> What kind of assets do you have in your app?

 * Lambda functions
 * Docker container

**Comment by rix0rrr** [comment] 2020-10-05 08:19
Yes and where are they rooted? In a parent directory of the directory that contains your `./data` folder perhaps?

**Comment by moltar** [comment] 2020-10-05 08:25
I am sorry, I don't understand the question.

I'll outline the root dir structure though:

 * `src` <- all app source code
 * `data` <- the data dir in question
 * `Dockerfile`
 * `.dockerignore` <- does **not** ignore `data/`, which is how i realized this issue was happening
 * `webpack.config.ts` <-- webpack config for building lambda functions
 * `dist` <-- output of webpack'ed lambda code, which is where CDK is told to look for it

**Comment by rix0rrr** [comment] 2020-10-05 09:24
Yes so the issue is that your `Dockerfile` lives above the `data` directory. Every file in the same or a lower directory from your `Dockerfile` is copied into the cloud assembly.

Yes you can solve that with a `.dockerignore` but you can also just stick the `Dockerfile` into a subdirectory with just the files it needs for the build.

Closing this issue as you seem to have figured it out.

**Closed by rix0rrr** 2020-10-05 09:24 UTC
Labels: @aws-cdk/core, guidance, needs-triage, response-requested

**Comment by moltar** [comment] 2020-10-05 10:15
But it is not clear why CDK needs to copy these files into it's own dir, if they are just used for building a Dockerfile?
