### ISSUE TITLE
@aws-cdk/aws-lambda-python-alpha: don't rebuild with docker unless code has been modified

### ISSUE THREAD

**Issue by jbschooley** [aws/aws-cdk#23602] opened 2023-01-06 18:41 UTC
### Describe the feature

I'm moving an existing backend with dozens of Python Lambda functions to CDK. I've noticed that each lambda is rebuilt every time `cdk diff` or `cdk synth` or `cdk deploy` is run.  It would be better to detect code changes before triggering a docker build.

### Use Case

Docker eats resources like nothing else and _destroys_ battery life on laptops. That's fine if I'm editing a function, but frustrating when I'm working on some other portion of the backend (appsync, IAM etc) that has nothing to do with function code, and I have to leave Docker running the whole time so my battery life gets cut in half. Even while on AC power, building all those functions when code hasn't changed adds valuable seconds to each diff check.

Or, lets say another dev on the team changes the python version used in a function. You want to deploy a new appsync resolver but now you have to wait for a 500mb+ docker image to download so it can rebuild a function that hasn't been touched.

### Proposed Solution

Would putting function code into a zip file and hashing that before any docker stuff work?

Amplify has its issues, and uses a less stable pipenv pipeline to build functions, but it's able to skip triggering the build process at all if code hasn't been modified.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.59.0 (build b24095d)

### Environment details (OS name and version, etc.)

Windows 11 22H2

**Comment by eruvanos** [comment] 2023-03-16 10:36
We have the same issue, but would also go a little further.

While this issue points out the requirement to always have Docker running, it also has to run for unnecessary things.

The most load seems to be the download and packaging of dependencies, it should be possible to detect, that these dependencies did not change within the past 1 hour. 
Hashing some lock file might be already enough.

> Hope this fits here, otherwise I can drop it.

**Comment by peterwoodworth** [comment] 2023-03-30 01:37
Thanks for the request, closing as a duplicate of https://github.com/aws/aws-cdk/issues/23829

**Closed by peterwoodworth** 2023-03-30 01:37 UTC
Labels: p2, feature-request, @aws-cdk/aws-lambda-python
