### ISSUE TITLE
[iam] MalformedPolicyDocument when role is assumedBy a group

### ISSUE THREAD

**Issue by adam-nielsen** [aws/aws-cdk#11505] opened 2020-11-17 02:53 UTC
I get no errors with `cdk synth` when creating a new policy and attaching it to a group, but `cdk deploy` fails with:

    Invalid principal in policy: "AWS":"arn:aws:iam::12345:group/exampleGroup" (
      Service: AmazonIdentityManagement;
      Status Code: 400;
      Error Code: MalformedPolicyDocument;
      Request ID: 54fabff2-1208-43da-ae06-5194ee277c7a;
      Proxy: null)

### Reproduction Steps
```
this.group = new cdkIAM.Group(this, `group`, {
	groupName: `exampleGroup`,
});

this.role = new cdkIAM.Role(this, `role`, {
	roleName: `exampleRole`,
	assumedBy: this.group,
});
```
I presume it is wrong to have a role assume a group, however the docs suggest this is possible as the group is an `IPrincipal` so the types match, and this field is mandatory so I am not sure what else to specify here.  At any rate, it would be nice if CDK picked this mistake up in the `synth` stage instead of generating an invalid CloudFormation template, otherwise you don't realise the problem until you attempt to deploy thinking you are done.

### What did you expect to happen?

The group and policy would be created, such that members of the group would have the policy applied to them.

### What actually happened?

The deploy failed with a MalformedPolicyDocument error, but it would have been nicer if CDK refused to generate the malformed document in the first place so I could pick up my mistake sooner.

### Environment

  - **CDK CLI Version  :** 1.73.0
  - **Framework Version:**
  - **Node.js Version:** v14.13.0
  - **OS               :** Arch Linux
  - **Language (Version):** Javascript

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-11-23 11:01
Your report is better but the other PR has a lower number (and I saw it first :)). Sorry!

Duplicate of https://github.com/aws/aws-cdk/issues/11479

**Closed by rix0rrr** 2020-11-23 11:01 UTC
Labels: @aws-cdk/aws-iam, bug, needs-triage

**Comment by adam-nielsen** [comment] 2020-11-24 01:57
@rix0rrr No problem at all, sorry for not finding the existing bug report first!
