### ISSUE TITLE
(aws-lambda-nodejs): `.mjs` file extension and `import.meta` not supported

### ISSUE THREAD

**Issue by blake-regalia** [aws/aws-cdk#13274] opened 2021-02-25 00:56 UTC
Although Lambda now supports Node v14:
 1. `.mjs` entry files are rejected by a regex pattern in aws-lambda-nodejs
 2. `esbuild` is transpiling the scripts to `cjs` format (commonjs) but BundlingOptions provides no means to specify `format: "esm"`, and consequently esbuild polyfills `import.meta` which breaks all of its uses in the scripts

### Reproduction Steps

`lib/my-stack.mjs`:
```
export class MyStack extends Stack {
    constructor(scope, id, props) {
        super(scope, id, props);

        // ...

        new NodejsFunction(this, 'Example', {
            runtime: Runtime.NODEJS_14_X,
            entry: 'src/entry-file.mjs',
            bundling: {
                target: 'es2020',
                // format: 'esm',   <-- should be able to pass this option here
            },
        };

        // ...
    }
}
```

`src/entry-file.mjs`:
```
export async function Example() {
    return import.meta.url;
}
```

### What did you expect to happen?

1. `entry-file.mjs` to be allowed to be used as an entry file.
2. `import.meta` to be defined and `Example()` to return a string.

### What actually happened?

1. `Error: Only JavaScript or TypeScript entry files are supported.`
2. `Example()` returns undefined since `import.meta` is polyfilled with an empty plain object.

### Environment

  - **CDK CLI Version  :** n/a
  - **Framework Version:**
  - **Node.js Version:** 14.13.0 
  - **OS               :** n/a
  - **Language (Version):** 

### Other

1. For the `.mjs` extension:
https://github.com/aws/aws-cdk/blob/5d71d8e815529ccde7ffe13bb72f57ae88e896dc/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L140

2. Allow passing in the [`format` option to `esbuild`](https://esbuild.github.io/api/#format):
https://github.com/aws/aws-cdk/blob/5d71d8e815529ccde7ffe13bb72f57ae88e896dc/packages/%40aws-cdk/aws-lambda-nodejs/lib/bundling.ts#L141-L158

--- 

This is :bug: Bug Report

**Comment by jogold** [comment] 2021-02-25 08:38
Hi @blake-regalia, does Lambda support `mjs` files? How? AFAIK it only supports CJS.

**Comment by blake-regalia** [comment] 2021-02-25 17:50
Yes in node.js >= v14.13 environment you can use esmodules.

**Comment by jogold** [comment] 2021-02-25 19:43
> Yes in node.js >= v14.13 environment you can use esmodules.

I understand that you want to use `.mjs` files as input and it's easy to update the regex there.

But regarding the output of `esbuild` I don't think Lambda knows how to deal with `.mjs` files so we'll always have to transpile to CJS, no?

**Comment by blake-regalia** [comment] 2021-02-25 20:42
I don't know where you are getting this assumption about Lambda not knowing how to deal with `.mjs` files; I must admit I don't know exactly how it is done currently but I don't see why this would cause any issues. As long as the environment is the correct version of node.js, it should be able to run mjs files in module mode.

**Comment by jogold** [comment] 2021-02-26 08:26
> I don't know where you are getting this assumption about Lambda not knowing how to deal with `.mjs` files; I must admit I don't know exactly how it is done currently but I don't see why this would cause any issues. As long as the environment is the correct version of node.js, it should be able to run mjs files in module mode.

Tried in the Lambda console and I was not able to do this. If you manage to successfully run files in module mode in the Lambda environment, let me know how you did it.

**Comment by ronaldocpontes** [comment] 2021-03-09 11:08
I am also getting errors on a new lambda with node 14.x.

Could someone publish a working example of using .mjs?

**Comment by ronaldocpontes** [comment] 2021-03-09 13:21
I believe the problem is that the lambda engine is using CommonJS require to load the handler method. This won't work if the lambda handler is an ES6 module or a .mjs file as it will fall in the error quadrant on the table below.

So the question is: how do we use nodejs 14.x out-of-the-box ES6 modules on AWS Lambdas? 

https://pencilflip.medium.com/using-es-modules-with-commonjs-modules-in-node-js-1015786dab03
![image](https://user-images.githubusercontent.com/3316428/110475453-d16ffa00-80d8-11eb-9ce7-0efe61d1829a.png)

**Comment by revmischa** [comment] 2021-04-24 17:04
I would like to load a `"type": "module"` package in CDK when building my `aws-lambda-nodejs` Lambda, even if it's being eventually output as commonJS. There should be some way to set it up so esbuild is doing an `import` instead of `require()` somewhere

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/cyber/dev/jb/jkv2-demo/cdk/node_modules/@jetkit/cdk/build/index.js
require() of ES modules is not supported.
require() of /Users/cyber/dev/jb/jkv2-demo/cdk/node_modules/@jetkit/cdk/build/index.js from /Users/cyber/dev/jb/jkv2-demo/cdk/packages/infra/lib/cdk-stack.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/cyber/dev/jb/jkv2-demo/cdk/node_modules/@jetkit/cdk/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/cyber/dev/jb/jkv2-demo/cdk/packages/infra/lib/cdk-stack.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/cyber/dev/jb/jkv2-demo/cdk/packages/infra/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/cyber/dev/jb/jkv2-demo/cdk/packages/infra/node_modules/ts-node/src/index.ts:1059:12)
```

**Comment by jogold** [comment] 2021-04-26 13:10
> Right now my function is very large and appears to contain all of @aws-cdk and typeorm and others,

This is really strange... can you share a repro? Are those dependencies imported in your handler? If yes, why? If not, they shouldn't be bundled.

**Comment by revmischa** [comment] 2021-04-26 13:14
> > Right now my function is very large and appears to contain all of @aws-cdk and typeorm and others,
> 
> This is really strange... can you share a repro? Are those dependencies imported in your handler? If yes, why? If not, they shouldn't be bundled.

My handler includes `@jetkit/cdk` which is what I'm trying to build right now. The construct I'm using is https://github.com/jetbridge/jetkit-cdk/blob/implement-view-routing/src/cdk/generator.ts and the app code is https://github.com/jetbridge/jetkit-cdk/blob/implement-view-routing/src/test/sampleApp.ts

**Comment by jogold** [comment] 2021-04-26 18:51
> My handler includes `@jetkit/cdk` which is what I'm trying to build right now

Can you show your handler? Is it a `.ts` file?

**Comment by revmischa** [comment] 2021-04-26 19:01
Yes, https://github.com/jetbridge/jetkit-cdk/blob/implement-view-routing/src/test/sampleApp.ts is the handler file. It's the `handler` export
```ts
export const handler = apiViewHandler(__filename, AlbumApi)
```

`apiViewHandler` is defined here: https://github.com/jetbridge/jetkit-cdk/blob/5d3adb8dbf732fdc1d968b5d5486ad2ec433a0fd/src/api/base.ts#L219

I'm trying to make some decorators that a CDK construct can make use of to generate NodeJsLambda functions and APIGW routes automatically

**Comment by Sparticuz** [comment] 2021-05-11 14:23
According to [this SO question](https://stackoverflow.com/questions/66676555/nodejs-14-x-native-aws-lambda-import-export-support), the Node on Lambda doesn't support ecmascript modules yet. I would love to see this happen ASAP. All of Sindre Sorhus' packages are currently moving to ESM only! https://blog.sindresorhus.com/hello-modules-d1010b4e777b

**Comment by groner** [comment] 2021-09-22 18:53
Here's a possible approach to running ES modules in lambda today (without the benefit of NodejsFunction)

The following stackoverflow answer claims success running ES modules with a shim using [dynamic `import()`](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_import_expressions).

<details>
<summary>From https://stackoverflow.com/a/69136438/91927</summary>

https://stackoverflow.com/a/69136438/91927

> This worked for me on Lambda Node 14.x -
> 
> in app.js
> 
> ```javascript
> exports.lambdaHandler = async (event, context) => {
>   const { App } = await import('./lib/app.mjs');
>   return new App(event, context);
> }
> ```
>
> And then in lib/app.mjs -
> 
> ```javascript
> class App {
> 
>   constructor(event, context) {
>     return {
>       'statusCode': 200,
>       'body': JSON.stringify({
>         'message': 'hello world'
>       })
>     }
>   }
> } 
> 
> export {App}
> ```

</details>

**Comment by groner** [comment] 2021-09-22 19:08
The following code in [aws/aws-lambda-nodejs-runtime-interface-client](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client) looks like it could be adapted to use `import()` and `import.meta.resolve()` without much trouble. 

From https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/blob/f9373b3e7cb153fe2895db446e21f3241eb156c6/src/utils/UserFunction.ts#L70-L111
```javascript
/**
 * Attempt to load the user's module.
 * Attempts to directly resolve the module relative to the application root,
 * then falls back to the more general require().
 */
function _tryRequire(appRoot: string, moduleRoot: string, module: string): any {
  const lambdaStylePath = path.resolve(appRoot, moduleRoot, module);
  if (_canLoadAsFile(lambdaStylePath)) {
    return require(lambdaStylePath);
  } else {
    // Why not just require(module)?
    // Because require() is relative to __dirname, not process.cwd()
    const nodeStylePath = require.resolve(module, {
      paths: [appRoot, moduleRoot],
    });
    return require(nodeStylePath);
  }
}


/**
 * Load the user's application or throw a descriptive error.
 * @throws Runtime errors in two cases
 *   1 - UserCodeSyntaxError if there's a syntax error while loading the module
 *   2 - ImportModuleError if the module cannot be found
 */
function _loadUserApp(
  appRoot: string,
  moduleRoot: string,
  module: string
): any {
  try {
    return _tryRequire(appRoot, moduleRoot, module);
  } catch (e) {
    if (e instanceof SyntaxError) {
      throw new UserCodeSyntaxError(<any>e);
    } else if (e.code !== undefined && e.code === "MODULE_NOT_FOUND") {
      throw new ImportModuleError(e);
    } else {
      throw e;
    }
  }
}
```

**Comment by intptr-t** [comment] 2021-11-09 12:41
Since there seems to be no progress, I will give my personal opinion.
There are two issues, which I think should be resolved independently of each other.

### 1. .mjs is not supported.
It should be legitimate for esbuild to output *.mjs and *.cjs as format=cjs.
I think it is reasonable that this be resolved by adding a feature (label=feature-request) to aws-lambda-nodejs in the CDK.
1) add a regular expression to `\. (c|m)?jsx?|(c|m)?tsx?$`
2) Allow passing in the format option to esbuild:, as shown by blake-regalia.

### 2. import.meta is not supported
The CDK is not concerned about the AWS Lambda runtime fully supporting ES2020 features (e.g. import.meta).
So it's better to wait until AWS Lambda supports it, or build it yourself using a custom runtime.

**Comment by jogold** [comment] 2022-01-07 09:31
https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/

https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/

**Comment by adamelmore** [comment] 2022-01-08 16:56
> https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/
> 
> 
> 
> https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/

Came here to see if this was in the works; @jogold are you planning to add support for native esm?

**Comment by jogold** [comment] 2022-01-09 10:20
> ame here to see if this was in the works; @jogold are you planning to add support for native esm?

I will try to have a look at it this week or next week.

**Comment by jogold** [comment] 2022-01-10 16:27
See #18346

**Closed** 2022-01-11 21:57 UTC
Labels: bug, p2, effort/small, @aws-cdk/aws-lambda-nodejs

**Comment by pfried** [comment] 2022-01-27 06:41
Not a aws-cdk Issue, but for everyone who ends up here: Using modules form layers is currently [not supported in lambda when using ESM](https://twitter.com/coderbyheart/status/1486470882008645634)

**Comment by paul-uz** [comment] 2022-03-31 09:40
@pfried damn, thats exactly the issue I hit. https://github.com/aws/aws-sdk-js-v3/issues/3386

**Comment by pfried** [comment] 2022-12-14 10:42
@paul-uz  I opened an issue here: https://github.com/aws/aws-cdk/issues/23333
