### ISSUE TITLE
(aws-ec2): Vpc.fromVpcAttributes cannot get VPC when only VPC ID is provided

### ISSUE THREAD

**Issue by mimozell** [aws/aws-cdk#12470] opened 2021-01-12 15:06 UTC
When trying to get a VPC from a given VPC ID using `Vpc.fromVpcAttributes`, instead of getting the VPC with the given ID, an error requiring you to provide the AZs will be generated.

### Reproduction Steps
`Vpc.fromVpcAttributes(scope, "imported vpc", VpcAttributes.builder().vpcId(vpcId).build())`

### What did you expect to happen?

I expected to get a VPC object provided the unique VPC identifier. I expect `Vpc.fromVpcAttributes` to behave the same as `aws ec2 describe-vpcs --filter Name=vpc-id,Values=<vpcId>`, but it doesn't. Why do you need to provide anything else when the unique identifier should be enough?

### What actually happened?

`Exception in thread "main" java.lang.NullPointerException: availabilityZones is required`

### Environment

  - **CDK CLI Version**: 1.83.0 (build 827c5f4)
  - **Node.js Version**: v12.16.3
  - **OS**: MacOS
  - **Language (Version)**: Kotlin (openjdk version "11.0.8")

### Other

--- 

This is :bug: Bug Report

**Comment by NGL321** [comment] 2021-01-29 04:11
As you can see [here](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.VpcAttributes.html), `availabilityZones` is a required property of `VpcAttributes`. This means you cant get a VPC with `fromVpcAttributes` _without_ providing the AZs for said VPC.
As for the why, I don't have a 100% certain answer for you, but from what I understand it is because the CDK has to perform a lookup to a specific environment (determined by AZs) in order to find the vpc by its id.

That said, you should be able to do exactly the same thing you are attempting sans AZs if you use `fromLookup` rather than `fromVpcAttributes`. This will allow you to lookup (in the deployed environment only) with just the `vpcId`. This is our suggested method anyway.

Please let me know if this helps resolve your problem!

😸 😷

**Comment by mimozell** [comment] 2021-01-29 08:15
@NGL321 thanks, but it still very hard to understand the logic behind this behaviour. If `VpcAttributes` is the main issue here, perhaps `Vpc` should give you a `fromId` function that lets you only provide the ID? I think we agree that the ID should be enough for you to get a VPC, right?

My problem is that the VPC ID is coming from SSM or as another stack's output and so `fromLookup` is useless. You might have seen from [this issue](https://github.com/aws/aws-cdk/issues/12485#issue-785195945) that I'm struggling "linking" stacks with just CDK. Currently moved on to using SDK to get me the values from SSM and then use those with the different `fromLookup` functions.

**Comment by peterwoodworth** [comment] 2021-02-15 22:52
Closing this issue because the VPC requiring AZs is intended behavior.

@mimozell I'll help you out on the other issue you linked [here](https://github.com/aws/aws-cdk/issues/12485).

**Closed by peterwoodworth** 2021-02-15 22:52 UTC
Labels: @aws-cdk/aws-ec2, guidance, language/java
