### ISSUE TITLE
DnsValidatedCertificate asset unavailable in pipeline deploy

### ISSUE THREAD

**Issue by kbanman** [aws/aws-cdk#6622] opened 2020-03-08 07:32 UTC
When using DnsValidatedCertificate in a stack deployed with CloudFormationCreateUpdateStackAction in a pipeline, the CFN step fails with a message like

> Parameters: [AssetParameters0b9723d54b7db3fbfc1a143398b02392e5fe080a68535480782a949b4372d0f0ArtifactHashF8F836D1, AssetParameters0b9723d54b7db3fbfc1a143398b02392e5fe080a68535480782a949b4372d0f0S3VersionKey83D9C166, AssetParameters0b9723d54b7db3fbfc1a143398b02392e5fe080a68535480782a949b4372d0f0S3Bucket0997A4A0] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: d478727f-66fd-4083-a8f0-64ec2b3df1c1)

The asset being referred to is the `CertificateRequestorFunction/Resource`, the custom resource lambda used to perform certificate validation.

When deploying the stack outside of the pipeline it works as expected.

### Reproduction Steps

```
// In stack
new DnsValidatedCertificate(this, 'ApiCert', {
    domainName: this.node.tryGetContext('apiDomainName'),
    hostedZone: props.hostedZone,
})

// In pipeline deploy stage
new CloudFormationCreateUpdateStackAction({
    actionName: `CFN_Deploy_${stackName}`,
    stackName,
    templatePath: this.output.atPath(`${stackName}.template.json`),
    adminPermissions: true,
    extraInputs: [apiDockerBuild.output],
})
```

### Error Log

Parameters: [AssetParameters0b9723d54b7db3fbfc1a143398b02392e5fe080a68535480782a949b4372d0f0ArtifactHashF8F836D1, AssetParameters0b9723d54b7db3fbfc1a143398b02392e5fe080a68535480782a949b4372d0f0S3VersionKey83D9C166, AssetParameters0b9723d54b7db3fbfc1a143398b02392e5fe080a68535480782a949b4372d0f0S3Bucket0997A4A0] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: d478727f-66fd-4083-a8f0-64ec2b3df1c1)

### Environment

  - **CLI Version      :1.27
  - **Framework Version:1.27
  - **OS               :linux
  - **Language         :TypeScript

### Other

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment] 2020-03-19 19:13
Hey @kbanman ,

yes, we are aware of this, and actively working on a solution. You can follow https://github.com/NetaNir/meerkats for our progress.

In the meantime, I'll close this as a duplicate of #1312.

Thanks,
Adam

**Closed by skinny85** 2020-03-19 19:13 UTC
Labels: bug, needs-triage, package/acm
