### ISSUE TITLE
(aws-cdk-lib): (Cloudwatch Log Groups do not have a UID suffix or stack name prefix like other components)

### ISSUE THREAD

**Issue by ssingh-01** [aws/aws-cdk#28031] opened 2023-11-16 14:40 UTC
### Describe the bug

I want to re-deploy the same stack multiple times in the same region and account with different names (for different business use cases). All the components are created with a non-conflicting name, because of the prefixed stack name and suffixed UID with each component name, except Cloudwatch Log Group. 

### Expected Behavior

If I re-deploy the same stack multiple times using a different stack name each time, all the components should be created with a non-conflicting name.

### Current Behavior

The customer wants to re-deploy the same stack multiple times with different names (for different business use cases). All the components are created with a non-conflicting name, because of the prefixed stack name and suffixed UID with each component name, except Cloudwatch Log Group. 

### Reproduction Steps

1. Bootstrap cdk in one account and region
2. Create a cdk stack with some components like lambda, eventbridge, step functions but must have an explicit cloudwatch log group in the stack.
3. Deploy the stack.
4. Redeploy it with a different stack name in same account and region, it fails due to resource conflict.
idp-poc-event-logs already exists in stack arn:aws:cloudformation:us-east-1:<acountnumber>:stack/idp-poc-sfn/75ea4bf0-8485-11ee-8204-0ec5737c0aed

### Possible Solution

For workaround :
Change the log group name or parameterize it in code to resolve the name uniquely.

### CDK CLI Version

2.96.1

### Node.js Version

v18.16.0

### OS

MAC

### Language

Python

### Language Version

3.10.6

**Comment by pahud** [comment] 2023-11-16 21:07
Did you mean it always creates the log group named `idp-poc-event-logs` even with different stack? Can you share a minimal reproducible code snippets?

**Comment by ssingh-01** [comment] 2023-11-19 16:15
> Did you mean it always creates the log group named `idp-poc-event-logs` even with different stack? Can you share a minimal reproducible code snippets?

This could be by design. In the following code snippet, if I do not provide the log_group_name, then a unique log group name is created, but if I provide a name, then it is hard coded with each stack  : 

`log_group = logs.LogGroup(self, "IDPPOCEventsGroup",log_group_name="idp-poc-event-logs")
`        

Is this expected behavior ?

**Comment by pahud** [comment] 2024-06-04 10:57
Yes, if you do not provide logGroupName, cloudformation will generate one for you.

**Comment by pahud** [comment] 2024-06-04 10:58
Closing as it's by design from CFN. Feel free to reopen if it's still relevant.

**Closed by pahud** 2024-06-04 10:58 UTC
Labels: bug, p2, effort/medium, aws-cdk-lib
