### ISSUE TITLE
(apigateway): support for minimumCompressionSize

### ISSUE THREAD

**Issue by drissamri** [aws/aws-cdk#22926] opened 2022-11-15 16:30 UTC
### Describe the feature

[SpecRestApi](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.SpecRestApi.html) doesn't support minimumCompressionSize, while [RestApi](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.RestApi.html) does 

### Use Case

We generate our API's based off a Open API specification and would like to use compression on our APIs

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.50

### Environment details (OS name and version, etc.)

OSX

**Comment by peterwoodworth** [comment] 2022-11-15 20:52
Thanks for the request, this should be pretty simple to add to our SpecRestApi props, and then passing it in here https://github.com/aws/aws-cdk/blob/4c11af6067b35125781aa590bb33c7990078d1ed/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L647

Before we support this, you can use escape hatches to make use of the property:

```ts
const specRestApi = new SpecRestApi(...);
(specRestApi.node.defaultChild as CfnRestApi).addPropertyOverride('MinimumCompressionSize', x);
```

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

Check out our [contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you're interested in contributing yourself - there's a low chance the team will be able to address this soon but we'd be happy to review a PR 🙂

**Comment by pahud** [comment] 2022-11-16 19:56
Hi @drissamri 

Are you interested to pick up with the PR against this issue? I would be happy to help you get started. Feel free to reach out to me on cdk.dev slack.

**Comment by virajmavani** [comment] 2022-11-19 02:45
I would like to take up this issue and contribute the fix. Please let me know if you can assign it. :)

**Comment by atchla** [comment] 2022-12-27 07:04
The linked PR looks like it was closed due to inactivity. Is this something I can pick up and finish off?

**Comment by peterwoodworth** [comment] 2022-12-27 21:42
Looks like the issue is yours for the taking @atchla! Go ahead 🙂

**Closed** 2023-03-01 16:09 UTC
Labels: good first issue, p2, feature-request, @aws-cdk/aws-apigateway, effort/small

**Comment by atchla** [comment] 2023-03-01 20:45
I had some things come up and didn't have enough bandwidth to take this task any more. Thanks for finishing it out @pattasai !
