### ISSUE TITLE
CDK overwrites ECS service desired count back to 1 on every deploy

### ISSUE THREAD

**Issue by nathanpeck** [aws/aws-cdk#3919] opened 2019-09-03 17:48 UTC
### What is the problem?
The default behavior of an ECS service update is to maintain the existing desired count if no desired count is specified. This is because customers often use autoscaling, or time based scaling and their scaling rules have already set the service to a specific desired count that is appropriate. Because CDK and CFN can not know this number at the time of the deploy the correct behavior is to omit it and retain the existing desired count.

However when you leave desired count out of the ECS construct in CDK it instead sets it to 1. This overrides whatever the current autoscaling set desired count is, causing a brief period of instability before the desired count is automatically restored to the right number by autoscaling.

**Comment by pgarbe** [comment] 2019-09-20 10:28
You can easily reproduce it when you change some settings of the service itself, like a changed tag. In that case DesiredCount gets overwritten by the value defined in the stack. This is not a CDK issue but rather a CloudFormation problem.

**Comment by manV** [comment] 2019-11-13 07:06
This seems like a pretty common problem, is there any workaround for this? maybe we can get current DiseredCound when doing new deploy somehow?

**Comment by manV** [comment] 2019-11-22 09:58
ping. @SoManyHs @pkandasamy91 I am happy to help any way I can.

**Comment by rix0rrr** [comment] 2019-12-02 23:01
This is CloudFormation behavior and not much we can do about this in CDK. It needs to be fixed upstream in the same way it works for AutoScalingGroups (desiredcount can be undefined, in which case it stays the same on updates, and for creates it defaults to the minimum capacity).

**Comment by manV** [comment] 2019-12-03 06:13
Thanks @rix0rrr for the clarification. I can see an issue already open on containers-roadmap [here](https://github.com/aws/containers-roadmap/issues/493).

**Comment by sonofachamp** [comment] 2020-05-05 20:58
Closing this issue in favor of the already linked containers-roadmap issue above.

**Comment by alanprot** [comment] 2020-12-03 06:24
Hi,

I think this issue should be reopened as the desiredCount is now Optional on the CFN resource.

https://github.com/aws/containers-roadmap/issues/493
https://github.com/awsdocs/aws-cloudformation-user-guide/issues/866

I could workaround this issue (below) but if i just remove the desiredCount from the FargateService it still default to 1.

    this.service = new FargateService(....);

    for (const c of this.service.node.children) {
      const cfnService = c as CfnService;
      if (cfnService !== null) {
        cfnService.desiredCount = undefined;
      }
    }


I would expect that if i don't pass the desiredCount on the `FargateServiceProps` it should not default to 1 in the underlaying CFN resource.
This seems to be the CRUX line:

https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts#L155

**Comment by piradeepk** [comment] 2020-12-03 14:38
> Hi,
> 
> I think this issue should be reopened as the desiredCount is now Optional on the CFN resource.
> 
> [aws/containers-roadmap#493](https://github.com/aws/containers-roadmap/issues/493)
> [awsdocs/aws-cloudformation-user-guide#866](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/866)
> 
> I could workaround this issue (below) but if i just remove the desiredCount from the FargateService it still default to 1.
> 
> ```
> this.service = new FargateService(....);
> 
> for (const c of this.service.node.children) {
>   const cfnService = c as CfnService;
>   if (cfnService !== null) {
>     cfnService.desiredCount = undefined;
>   }
> }
> ```
> 
> I would expect that if i don't pass the desiredCount on the `FargateServiceProps` it should not default to 1 in the underlaying CFN resource.
> This seems to be the CRUX line:
> 
> https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-ecs/lib/fargate/fargate-service.ts#L155

Agreed this is an issue with how the cdk implements the desired count, reopening this issue.

**Comment by coleman-c** [comment] 2020-12-07 09:53
Hi,

I think the same issue exists with the EC2 launch type also:  

https://github.com/aws/aws-cdk/blob/60875a5d6cd93b7d6f0f9b1b94153f6d1f4766b1/packages/%40aws-cdk/aws-ecs/lib/ec2/ec2-service.ts#L190

**Comment by SoManyHs** [comment] 2021-01-06 02:00
I believe this should be fixed by https://github.com/aws/aws-cdk/pull/12223!

**Closed by SoManyHs** 2021-01-06 02:00 UTC
Labels: @aws-cdk/aws-ecs, bug, effort/small, needs-cfn, p2
