### ISSUE TITLE
aws_cdk.aws_ecs_patterns - missing classes/contructs from CDK 1.19.0

### ISSUE THREAD

**Issue by Mejato** [aws/aws-cdk#5656] opened 2020-01-06 08:39 UTC
AWS CDK missing classes/constructs from CDK 1.19.0 for aws_cdk.aws_ecs_patterns.
- class ApplicationMultipleTargetGroupsEc2Service (construct)
- class ApplicationMultipleTargetGroupsFargateService (construct)
- class NetworkMultipleTargetGroupsEc2Service (construct)
- class NetworkMultipleTargetGroupsFargateService (construct)

### Reproduction Steps

from aws_cdk import (
    aws_ecs_patterns as ecs_patterns
    core
)

deploy_fargate = ecs_patterns.ApplicationMultipleTargetGroupsFargateService()

### Error Log

Cannot find reference 'ApplicationMultipleTargetGroupsFargateService' in '__init__.py' 

### Environment

  - **CLI Version      :** aws-cli/1.16.218 Python/3.7.5 Linux/5.3.0-24-generic botocore/1.13.8
  - **Framework Version:** 1.19.0 (build 5597bbe)
  - **OS               :** Ubuntu 19.10
  - **Language         :** Python

### Other

--- 

This is :bug: Bug Report

**Comment by SomayaB** [comment] 2020-01-06 19:54
Closing since it's a duplicate of #5605

**Closed by SomayaB** 2020-01-06 19:54 UTC
Labels: bug, package/ecs-patterns, status/needs-triage
