### ISSUE TITLE
custom-resources: PR:29648 caused Custom resources to be replaced

### ISSUE THREAD

**Issue by p3tek** [aws/aws-cdk#30121] opened 2024-05-09 06:43 UTC
### Describe the bug

the following PR - https://github.com/aws/aws-cdk/pull/29648 added an additional "logApiResponseData":true to the custom resource properties.

This triggered a replacement of existing custom resources which is not a good outcome for "onCreate" resources that are only meant to be executed once

### Expected Behavior

Not have existing custom-resources replaced with this update.

### Current Behavior

"logApiResponseData":true was not present prior to this PR and the custom resource was not triggered on stack update

### Reproduction Steps

will trigger after an update of aws-cdk-lib

### Possible Solution

allow this value to be suppressed so it doesn't trigger a resource replacement ?

### CDK CLI Version

2.138.0

### Framework Version

2.138.0

### Node.js Version

18.16.1

### OS

linux

### Language

TypeScript

**Comment by khushail** [comment] 2024-05-17 17:05
Hi @p3tek , could you please share the minimum reproducible code for repro of the issue.

**Comment by colifran** [comment] 2024-05-17 17:51
Hey @p3tek, thanks for raising this. From what I'm seeing the problem isn't necessarily the new event property being passed. What I mean is that any change we make to the underlying handler code (new property or not) will also trigger an update since it will force a change in the asset hash. This would lock us into a situation where we are unable to make any code changes because they would all force an update. Are you able to just duplicate whatever SDK call you're making for `onUpdate` so that you keep the same behavior in the event of an update?

**Comment by heikkis** [comment] 2024-05-29 09:00
Basically the CDK version upgrade causes new parameter to be added -> CR is executed after CDK upgrade which causes problem if the CR Update is not tested/used a lot/never.

**Comment by heikkis** [comment] 2024-05-29 10:59
@colifran Triggering all CR's is a big thing. The pipeline can be stuck for hours, onUpdate etc. method are not normally tested -> suddenly those are tested/used. What you think?

**Comment by colifran** [comment] 2024-05-31 14:34
@heikkis I was under the impression that any change to the handler code would have triggered an update, but I've learned that is not the case. That said I agree. I think this should be fixed so that the default is that no parameter is passed. Will work on a PR for this.

**Closed** 2024-06-06 00:41 UTC
Labels: bug, @aws-cdk/custom-resources
