### ISSUE TITLE
aws-eks: the ALB controllers aren't well configured after upgrading to CDK 2.33

### ISSUE THREAD

**Issue by lbarriosh** [aws/aws-cdk#21371] opened 2022-07-29 09:43 UTC
### Describe the bug

We manage our EKS cluster via CDK. This week we updated from CDK 2.29 to CDK 2.33, and after the update the ALB controllers weren't well configured and half of our ALB ingresses stopped working.

The AWS load balancer controller chart was updated under the covers, but sadly it wasn't configured properly.

### Expected Behavior

The values for the `eks/aws-load-balancer-controller` Helm chart should have been updated to 
1. give the cluster role for the ALB controller the access to kubernetes secrets it needs.
2. use the `aws-load-balancer-controller` service account for the ALB controller pods.

### Current Behavior

There were two problems, which we have fixed applying changes to the cluster bypassing CDK:
1. the cluster role for the ALB controller (`aws-load-balancer-controller-role`) didn't have permissions to get, list and watch secrets. This triggered errors in the logs of the `aws-load-balancer-controller` pods in `kube-system` and prevented them from starting.
2. the Helm chart for the aws load balancer controller (`eks/aws-load-balancer-controller`) hadn't been configured to use the `aws-load-balancer-controller` service account. This prevented the ingresses from being created and the errors appeared for both manual deployments via `kubectl` and for CDK deployments via CloudFormation.

### Reproduction Steps

Provision an EKS cluster with CDK 2.29 using EC2 nodes. Upgrade to CDK 2.33.

Note that we don't apply the Helm chart for the ALB controller ourselves. It is done under the covers by CDK.

### Possible Solution

Update the CDK code that applies the ALB controller helm chart to include the modifications we listed under current behavior.

### CDK CLI Version

2.33.0 (build 859272d)

### Node.js Version

v16.15.0

### OS

Linux version of AWS CodePipeline, macOS Monterey

### Language

Typescript

### Language Version

4.7.4

**Comment by Hazzard17h** [comment] 2022-08-16 15:55
As far as I understand, this is caused by #20826 and released in [v2.31.0](https://github.com/aws/aws-cdk/releases/tag/v2.31.0)
To resolve the issue I updated the AlbController to v2.4.1, as I had v2.3.0

**Comment by pahud** [comment] 2022-11-14 21:12
Hi @lbarriosh 

Thanks for your report. Please let us know if this issue still exists with Albcontroller v2.4.1 with CDK 2.33 or above? I would be happy to follow this up if it still exists.

**Comment by lbarriosh** [comment] 2022-11-15 08:26
Hi @pahud,

Thanks for following up on this. I can confirm the issue is still present with CDK 2.50. With that version, the cluster role for the ALB controller doesn't include the permissions to read secrets, which makes the ALB pods crash loop.

Luckily, the issue is trivial to reproduce: all it takes is a CDK stack using the `Cluster` EKS construct.

**Comment by pahud** [comment] 2022-11-18 21:14
@lbarriosh Thanks for the report. I am assigning this to myself and will try reproduce it in my account. However, it sounds like we have to add additional IAM policies to the cluster role for the ALB controller? Do you have any work around for this?

**Comment by lbarriosh** [comment] 2022-11-22 12:39
@pahud yes, we do. We update the cluster role for the ALB controller manually to give it permissions to access secrets, and then reapply the Helm chart for the ALB controller manually to set the correct cluster name.

**Comment by pahud** [comment] 2022-11-29 00:22
> @pahud yes, we do. We update the cluster role for the ALB controller manually to give it permissions to access secrets, and then reapply the Helm chart for the ALB controller manually to set the correct cluster name.

This is interesting. Can you share your full sample code with me so I can run on my own AWS account?

**Comment by lbarriosh** [comment] 2022-11-30 14:30
We just created an EKS 1.21 cluster via CDK:

```
const clusterProps: ClusterProps = {
      albController: { version: AlbControllerVersion.V2_3_1 },
      clusterLogging: [
        ClusterLoggingTypes.API, 
        ClusterLoggingTypes.AUDIT,
        ClusterLoggingTypes.AUTHENTICATOR,
        ClusterLoggingTypes.CONTROLLER_MANAGER,
        ClusterLoggingTypes.SCHEDULER,
      ],
      clusterName: 'ClusterName'
      defaultCapacity: 0,
      outputMastersRoleArn: true,
      version: KubernetesVersion.V1_21,
      vpcSubnets: [{ subnetType: SubnetType.PRIVATE_WITH_NAT }],
    };

    this.cluster = new Cluster(this, this.clusterName, clusterProps);

```

As soon as we added a node group to it, we could see the ALB controller pods crash looping.

That being said, the issue seems to be gone in EKS 1.23 and 2.4.1 as the ALB controller version.

**Closed** 2023-03-15 13:01 UTC
Labels: bug, investigating, @aws-cdk/aws-eks, aws-cdk-lib
