### ISSUE TITLE
"FAILED, No updates are to be performed" when adding a "Transform" to a stack

### ISSUE THREAD

**Issue by dplbd** [aws/aws-cdk#2553] opened 2019-05-15 17:07 UTC
**Describe the bug**
When using `templateOptions.transform` on a stack the below error will appear on any stack that has no updates.
```
 ❌  cdk-app failed: Error: Failed to create ChangeSet CDK-2372b61b-68c3-4cad-a447-9e5f78c8fe11 on cdk-app: FAILED, No updates are to be performed.
Failed to create ChangeSet CDK-2372b61b-68c3-4cad-a447-9e5f78c8fe11 on cdk-app: FAILED, No updates are to be performed.
Error: Failed to create ChangeSet CDK-2372b61b-68c3-4cad-a447-9e5f78c8fe11 on cdk-app: FAILED, No updates are to be performed.
    at waitFor (/tmp/.nvm/versions/node/v11.10.1/lib/node_modules/cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:115:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**To Reproduce**
`$ cdk deploy`

**Expected behavior**
If no changes are generated just move on to the next stack.

**Version:**
 - OS: macOS 10.14.4
 - Programming Language: Typescript
 - CDK Version: 0.31.0

**Comment by RomainMuller** [comment] 2019-06-26 12:24
Hey @dplbd,

I think the issue is pretty clear here - however it may help getting to a closure faster if you could provide a minimal repro example for your problem.

Regards,
Romain.

**Comment by SomayaB** [comment] 2019-09-30 23:23
Hi @dplbd, there hasn't been activity on this issue in a while, are you still experiencing this issue?

**Comment by NGL321** [comment] 2019-10-04 23:02
I am closing out the issue for now due to lack of activity. Please feel free to comment or reopen it if you are still experiencing the bug.

😸

**Comment by mpvosseller** [comment] 2020-02-07 17:54
Hi. I am experiencing this issue as well. Can you please re-open. I put together a sample project to demonstrate the issue here: https://github.com/mpvosseller/aws-cdk-issue-2553
Thanks.

**Comment by natCyberark** [comment] 2020-04-16 09:48
Hi ! We are using latest 1.32.2 version and still experience this issue with cdk deploy. Have no nested stacks.
May be some flag like --no-fail-on-empty-changeset of cloudformation deploy could be added ?
Thank you

**Comment by eladb** [comment] 2020-04-16 11:29
@natCyberark can you provide some more details about your use case? Are you trying to add a "transform" to your stack (because this is what this bug is about, albeit title might be misleading).

**Comment by eladb** [comment] 2020-04-16 11:30
I am closing this one because the `transform` issue should be resolved already (fixed by #6346) but if @natCyberark you have a different use case that this occurs, please create a new issue with the details.

**Closed** 2020-04-16 11:29 UTC
Labels: bug, p2, package/cdk-core

**Comment by natCyberark** [comment] 2020-04-16 11:56
I run 
1) pip3 install --upgrade --user awscli 
2) npm -g update aws-cdk and  
and it fixed the issue.
You can close, thank you very much !

**Comment by natCyberark** [comment] 2020-04-16 13:47
Sorry, Elad.

I got in pipfile.lock a lot of aws-cdk packages of 1.32.2 and thought that we are aligned with the latest version.
So, almost every usual stack without nested or transform started to fail in deploy if there were no real update (flow that worked before latest pipfile.lock update).

But it turned out, that my aws-cdk itself was old. So, when I run
npm -g update aws-cdk
and
pip3 install --upgrade --user awscli
it started to work ok again.

Thank you
Natasha.
