### ISSUE TITLE
[elasticloadbalancingv2] Exception in addTargetGroups when using conditions prop only

### ISSUE THREAD

**Issue by AnatolyUA** [aws/aws-cdk#9320] opened 2020-07-29 06:29 UTC
At the moment I'm using this code to add a Target Group to ALB (java):
```java
mainLBListener.addTargetGroups("EchoLambdaTg", AddApplicationTargetGroupsProps.builder().priority(100)
                                .conditions(List.of(ListenerCondition.pathPatterns(List.of("/links*"))))
                                .pathPattern("/links*").targetGroups(Collections.singletonList(tg)).build());
```
As I can understand `pathPattern` is `@deprecated Use 'conditions' instead.`. But when I remove it:
```java
mainLBListener.addTargetGroups("EchoLambdaTg", AddApplicationTargetGroupsProps.builder().priority(100)
                                .conditions(List.of(ListenerCondition.pathPatterns(List.of("/links*"))))
                                .targetGroups(Collections.singletonList(tg)).build());
```
I get this exception:
```
An exception occured while executing the Java class. At least one of 'conditions', 'hostHeader', 'pathPattern' or 'pathPatterns' is required when defining a load balancing rule.
[ERROR] Error: At least one of 'conditions', 'hostHeader', 'pathPattern' or 'pathPatterns' is required when defining a load balancing rule.
[ERROR]     at new ApplicationListenerRule (/tmp/jsii-kernel-eV4MAc/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener-rule.js:28:19)
[ERROR]     at ImportedApplicationListener.addTargetGroups (/tmp/jsii-kernel-eV4MAc/node_modules/@aws-cdk/aws-elasticloadbalancingv2/lib/alb/application-listener.js:336:13)
[ERROR]     at /tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:7746:51
[ERROR]     at Kernel._wrapSandboxCode (/tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:8398:19)
[ERROR]     at /tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:7746:25
[ERROR]     at Kernel._ensureSync (/tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:8371:20)
[ERROR]     at Kernel.invoke (/tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:7745:26)
[ERROR]     at KernelHost.processRequest (/tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:7446:28)
[ERROR]     at KernelHost.run (/tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:7384:14)
[ERROR]     at Immediate.<anonymous> (/tmp/jsii-java-runtime6258021919515626221/jsii-runtime.js:7387:37)
[ERROR]     at process.processImmediate (internal/timers.js:439:21)
```

### Environment

  - **CLI Version      :** 1.55.0
  - **Framework Version:** 1.55.0
  - **Node.js Version:** v12.15.0
  - **OS               :** Ubuntu / Windows 10
  - **Language (Version):** openjdk version "11.0.7" 2020-04-14

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-08-04 08:35
Duplicate of https://github.com/aws/aws-cdk/issues/9262

**Closed by rix0rrr** 2020-08-04 08:35 UTC
Labels: @aws-cdk/aws-elasticloadbalancingv2, bug, needs-triage
