### ISSUE TITLE
Changing APIGW Resource Policy Don't Trigger APIGW Deployment

### ISSUE THREAD

**Issue by rabereyal** [aws/aws-cdk#5354] opened 2019-12-10 07:08 UTC
## Changing APIGW Resource Policy Don't Trigger APIGW Deployment

Hi, 
I have a cdk stack with multiple resources.
One of the resources is API Gateway, which has multiple resources.
I noticed that changing the resource policy of the api (after deploying the api for the first time), don't trigger apigw deployment. This causes a false situation in which the resource policy looks like it changed in the AWS console, but actually it still the old resource policy - and indeed when I checked the deployment history I saw that no new deployment was triggered after the change. Deploying the apigw manually in the AWS console solved it.

### Environment

  - **CDK CLI Version:** 1.6.0
  - **OS:** all 
  - **Language:** TypeScript

#### Temp workaround 
*creating a 'dummy' resource with a timestamp in its name, so that every change in the api will trigger api deployment.*

**Comment by nija-at** [comment] 2019-12-11 17:49
I'm unable to replicate this error.

Here are some steps I used to try to reproduce this. (Throughout these steps real AWS account numbers are anonymized with `<account-1>` and `<account-2>`)

This is the CDK app I've used -

```ts
import apig = require('@aws-cdk/aws-apigateway');
import core = require('@aws-cdk/core');
import iam = require('@aws-cdk/aws-iam');

const app = new core.App();
const stack = new core.Stack(app, 'mystack');

const restapi = new apig.RestApi(stack, 'myrestapi', {
    policy: new iam.PolicyDocument({
        statements: [new iam.PolicyStatement({
            actions: ['execute-api:Invoke'],
            resources: ['*'],
            principals: [ new iam.AccountPrincipal('<account-1>') ]
        })]
    })
});

restapi.root.addMethod('ANY');
```

After deploying this app, I checked the permissions with the AWS CLI
```shell
⇒  aws apigateway get-rest-api --rest-api-id pya8xps0pc --query policy
"{\\\"Version\\\":\\\"2012-10-17\\\",\\\"Statement\\\":[{\\\"Effect\\\":\\\"Allow\\\",\\\"Principal\\\":{\\\"AWS\\\":\\\"arn:aws:iam::<account-1>:root\\\"},\\\"Action\\\":\\\"execute-api:Invoke\\\",\\\"Resource\\\":\\\"*\\\"}]}"
```

Next, I changed `<account-1>` to `<account-2>`, redeployed the app and ran the same command from the CLI. The `Principal` in the `policy` was `{ "AWS": "arn:aws:iam::<account-2>:root" }` as expected.

@rabereyal - could you provide a minimal app and repro steps for this bug?

**Comment by rabereyal** [comment] 2019-12-16 07:37
I didn't use AWS CLI, the issue I faced is that  entering the AWS console and checking the API Gateway resource policy showed <account-2> as you got. But, actually a new deployment of the API didn't triggered (I looked at the 'deployment history' of the API to verify it) - and therefore the new resource policy didn't changed.

**Comment by mnichols-dl** [comment] 2019-12-19 22:54
I had a similar thing occur with setting the Binary Media Types on an existing LambdaRestApi. The setting was properly added in the API Gateway, but the change didn't go into effect because no deployment occurred to the "prod" stage.

I suspect that the only values contributing (i.e. addToLogicalId()) to the hash that determines whether a stage is dropped and redeployed are methods and resources, not other settings like the policy mentioned above or the binary media types in my case.

**Comment by nija-at** [comment] 2020-01-15 16:44
Can you provide a working code example and reproduction steps for this issue (similar to the one I provided above) along with what your expected experience was and what it was actually?

**Comment by SomayaB** [comment] 2020-02-10 20:17
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by kirintwn** [comment] 2020-02-11 06:39
Can confirm the problem still exists. The resource policy is updated after CloudFormation deployment (can see it being updated from web console). But the API it self is not getting re-deployed. thus, the API is still using the old resource policy.

I think it is like using console to update the resource policy of an existing API.
[The document of AWS API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html) says: 
>If you use the API Gateway console to attach a resource policy to a deployed API, or if you update an existing resource policy, you'll need to redeploy the API in the console for the changes to take effect.

And this StackOverflow question might be related:
https://stackoverflow.com/questions/38363975/how-do-i-force-redeployment-of-my-api-gateway-using-cloudformation

**Comment by rabereyal** [comment] 2020-02-11 06:57
Steps to reproduce:

1. Create a new apigw with some resources.
2. Change the apigw resource policy and hit save (e.g: deny some IAM role to access the apigw).
3. Test the new resource policy (if you disallow some role to access the apigw, try to access the apigw using this role).

You still will be able to access the apigw, unless you will re-deploy the apigw and then the new resource policy will take action.

**Comment by nija-at** [comment] 2020-02-26 15:20
@kirintwn & @rabereyal - it seems like both of you are reporting issues with API Gateway and not with the CDK.

Closing this issue.

**Comment by tonyharrison** [comment] 2020-02-27 07:30
This not really an  API Gateway issue. It's a consequence of how the automatic deploy works.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html#deploy

The deploy is triggered by a change of f the logical id, which is generated by a hash of  "resources,methods, and options". Changing  things that are not "resources, methods or options" does not change the hash (logical id) and therefore does not trigger the deploy.

I don't know what is covered under "options" but in addition to resource  policy as reported above, I can confirm that Gateway Responses' also do not trigger the deploy, so are probably also not part of the hash.

**Closed** 2020-04-22 16:56 UTC
Labels: bug, p1, package/apigateway

**Comment by markgarcia1** [comment] 2020-08-05 20:05
What is the status of this issue? Has it been resolved if so how? I added a new lambda resource and method to my existing stack and this still did not trigger a re-deployment.

**Comment by awesomelike** [comment] 2023-04-21 11:22
What should be the workaround here? Should the Resource policy be deleted manually from the console?
