### ISSUE TITLE
aws-events-targets:ecs-task no longer works outside AWS partition

### ISSUE THREAD

**Issue by bmoor-amzn** [aws/aws-cdk#29628] opened 2024-03-27 05:32 UTC
### Describe the bug

A [recent change](https://github.com/aws/aws-cdk/commit/4af0dfcb0ecf7719d2ca15c7f971fa65ce8953cd) to the ecs-task event rule target broke using event rule targets on ECS tasks outside of the AWS partition.

Specifically [this policy statement](https://github.com/aws/aws-cdk/blob/2cc24499bf62b6dd48ae9bd265c38a6847f75a3f/packages/aws-cdk-lib/aws-events-targets/lib/ecs-task.ts#L288-L293) which explicitly disables the linter check for hardcoded partitions.   

My code was successfully working a few weeks ago and I recently noticed the failures without any changes in my CDK application, just a new dependency upgrade from cdk lib 2.x

### Expected Behavior

My CDK should deploy in all partitions successfully.

### Current Behavior

My CDK fails to deploy in any partition except AWS with an IAM validation failure on the partition arn.

### Reproduction Steps

Create an [ScheduledEc2Task](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.ScheduledEc2Task.html) or a [ScheduledFargateTask](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs_patterns.ScheduledFargateTask.html) following the example in the CDK documentation and attempt to deploy outside the AWS partition.

### CDK CLI Version

2.133.0

### Node.js Version

18.x

### OS

linux

### Language

TypeScript, Python, .NET, Java, Go

**Comment by tim-finnigan** [comment] 2024-03-27 06:21
Thanks for reporting this issue. It appears to be a duplicate of https://github.com/aws/aws-cdk/issues/29610. I raised that to a `p0` and will bring it up with the team for review.

**Closed** 2024-03-27 06:23 UTC
Labels: bug, duplicate
