### ISSUE TITLE
`cdk init --language python` fails when using cdk latest version 1.23.0

### ISSUE THREAD

**Issue by SGA-hiromichi-sugawara** [aws/aws-cdk#6157] opened 2020-02-07 07:50 UTC
## :question: General Issue
When using cdk latest version 1.23.0 with python versions listed below, the command 「cdk init --language python 」fails and the following error is output.
`Invalid regular expression: /([\p{Lowercase_Letter}\d])(\p{Uppercase_Letter})/: Invalid escape`
Could you please check?
# I used the environment cloud 9

### Environment

  - **CDK CLI Version:** 1.23.0
  - **Module Version:** npm version 6.4.1
  - **OS:** Amazon Linux AMI 2018.03 (on Cloud 9 Service) 
  - **Language:** python 3.6.8

**Comment by Jerry-AWS** [comment] 2020-02-07 16:41
I just tested this and can't reproduce it at the moment on my Windows machine. @SGA-hiromichi-sugawara what's the name of the folder you're using? `cdk init` uses the folder name to name some of the generated files, classes, etc. and it's possible there's some edge case involving particular folder names. Also, what version of Node.js do you have? `node --version`

**Comment by spfpaul** [comment] 2020-02-09 22:52
I also had the same issue just now, fixed by updating nodejs to v12.15.0

**Comment by shivlaks** [comment] 2020-02-10 15:41
@SGA-hiromichi-sugawara @spfpaul - what `Nodejs` version did you have previously?

I'm trying to reproduce the issue by spinning up a Cloud9 environment (region: `us-west-2` instance type: `m5.large`) and installed cdk. It came with Nodejs `10.18.0` and was working out of the box.

I'm also curious what characters were in your folder (I tried some characters with spaces and hyphens, but probably should not be guessing). Is there anything unique or special there that we might not be handling correctly?

**Comment by fafriat** [comment] 2020-02-12 18:50
I got same issue from Java...
using cdk init app --language java
Output:
Applying project template app for java
Invalid regular expression: /([\p{Lowercase_Letter}\d])(\p{Uppercase_Letter})/: Invalid escape

**Comment by shivlaks** [comment] 2020-02-12 18:54
@fafriat can you provide additional details

* CDK version
* Nodejs version
* OS
* project name (folder name) - please redact if needed

have you tried updating node as suggested by @spfpaul

**Comment by fafriat** [comment] 2020-02-12 18:57
I just solved it by upgrading Nodejs:
sudo npm install -g n
sudo n stable

Thank you!

**Comment by SomayaB** [comment] 2020-02-17 16:42
Closing this issue since it seems to have been solved. Feel free to reopen.

**Closed by SomayaB** 2020-02-17 16:42 UTC
Labels: package/tools, response-requested, status/needs-repro

**Comment by KarthickEmis** [comment] 2020-06-04 16:54
for windows , uninstall node, and reinstall it. It will work
