### ISSUE TITLE
lambda.Function: circular dependency error when trying to grant a function permission to invoke itself

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-cdk#13982] opened 2021-04-05 19:41 UTC
To reproduce:

    func.grantInvoke(func)   // func is a lambda.Function

This compiles fine.  However, after deploying to CFN, CFN fails with a circular dependency error.

The use case here is a benchmarking lambda that fans itself out to a high concurrency.

The work around is this:

    func.addToRolePolicy(new iam.PolicyStatement({
        effect: iam.Effect.ALLOW,
        resources: ['*'],
        actions: ['lambda:InvokeFunction']
      }));
    
   Obviously the '*' is not good.  CDK version 1.96.0

**Comment by nija-at** [comment] 2021-04-07 11:02
Hi @kjpgit -

Thanks for filing this issue.

Here's why this occurs. In order to ensure that the lambda has all of its permissions set up *before* its first invocation, we provision the IAM role and policy, before setting up the lambda handler.

To set up the IAM policy with the `grantInvoke()` permission, we need the lambda function name. And in turn, since the function is not set up, the name and ARN are not available.

As an improvement, we could amend the CDK such that for `Function` constructs whose `functionName` is already provided, we could avoid this circular dependency.

Until then, the workaround you've posted is the best option available.

> Obviously the '*' is not good. 

How about giving the a function name and replacing the '*' with the function ARN? That should achieve the right security posture.

**Comment by kjpgit** [comment] 2021-04-07 14:24
To be clear, my function did have a functionName assigned.  But both of these still fail:

    func.grantInvoke(func)
    
    func.addToRolePolicy(new iam.PolicyStatement({
      effect: iam.Effect.ALLOW,
      resources: [func.functionArn],
      actions: ['lambda:InvokeFunction']
    }));

**Comment by nija-at** [comment] 2021-04-07 14:46
You will have to hardcode the ARN in the `resources` property and not use `func.functionArn`.

**Comment by nija-at** [comment] 2021-04-07 16:07
Duplicate of https://github.com/aws/aws-cdk/issues/11020

**Closed by nija-at** 2021-04-07 16:07 UTC
Labels: @aws-cdk/aws-lambda, bug, effort/medium, p2
