### ISSUE TITLE
(neptune): Higher level constructs for Neptune

### ISSUE THREAD

**Issue by cornerwings** [aws/aws-cdk#12762] opened 2021-01-29 04:47 UTC
Add level 2 constructs for the Amazon Neptune.

### Use Case

CDK users who want to build applications that use Neptune currently have to use level 1 constructs or implement their own higher-level constructs.

### Proposed Solution

The level 2 constructs from the @aws-cdk/aws-rds package in CDK offers a good starting point since their CloudFormation resource specifications follow a similar architecture. From there, the code must be reviewed and modified to reflect Neptune's CloudFormation resources.

### Other

N/A

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NetaNir** [comment] 2021-01-29 04:49
duplicate of https://github.com/aws/aws-cdk/issues/6857

**Closed by NetaNir** 2021-01-29 04:49 UTC
Labels: @aws-cdk/aws-neptune, feature-request, needs-triage
