### ISSUE TITLE
aws-appmesh: Error: Resolution error: Supplied properties not correct for "CfnVirtualNodeProps"

### ISSUE THREAD

**Issue by niks913** [aws/aws-cdk#18399] opened 2022-01-13 10:06 UTC
### What is the problem?

Failure during cdk diff or cdk deploy with the recent version updates.
This works till aws-cdk-lib==2.5.0

### Reproduction Steps

```python
class AppMeshBuilder(CustomConstruct):
    def __init__(self, scope: constructs.Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)
        self.id = id
        self.module_prefix = "Sample"
        self.appmesh = self.set_appmesh()
        self.cloudmap_service = self.set_cloudmap_service()
        self.virtual_node = self.set_virtual_node_with_backend()
        self.virtual_service = self.set_virtual_service()
        self.set_stack_output()

    def set_appmesh(self):
        MESH_NAME = "Sample_mesh"
        MESH = appmesh.Mesh.from_mesh_name(self, self.id, mesh_name=MESH_NAME)
        return MESH

    def get_appmesh(self):
        return self.appmesh
    
    def set_cloudmap_service(self):
        NAME_SPACE_ID = "sample_namespace_id"
        NAME_SPACE_NAME = "sample_namespace_name"
        NAME_SPACE_ARN = "sample_namespace_arn"
        cloudmap_namespace = cloudmap.PrivateDnsNamespace.from_private_dns_namespace_attributes(self, "DNSNameSpaceId",
            namespace_id=NAME_SPACE_ID,
            namespace_arn=NAME_SPACE_ARN,
            namespace_name=NAME_SPACE_NAME
        )
        cloudmap_service = cloudmap.Service(self, "CloudmapService",
            namespace=cloudmap_namespace,
            dns_record_type=cloudmap.DnsRecordType('A'),
            dns_ttl=cdk.Duration.seconds(10),
            routing_policy=cloudmap.RoutingPolicy('MULTIVALUE'),
            name=self.module_prefix
        )
        return cloudmap_service
    
    def get_cloudmap_service(self):
        return self.cloudmap_service
    
    def set_virtual_node_with_backend(self):
        virtual_node = appmesh.VirtualNode(self, "VirtualNode",
            mesh=self.appmesh,
            backends=[
                appmesh.Backend.virtual_service(
		    virtual_service=appmesh.VirtualService.from_virtual_service_attributes(self, "VirtualService1",
		        virtual_service_name="BackendVirtualService1.cdk.mesh.local",
			mesh=self.appmesh
		    )
		),
                appmesh.Backend.virtual_service(
		    virtual_service=appmesh.VirtualService.from_virtual_service_attributes(self, "VirtualService2",
		        virtual_service_name="BackendVirtualService2.cdk.mesh.local",
			mesh=self.appmesh
		    )
		)
	    ],
            listeners=[appmesh.VirtualNodeListener.http(
                port=8080,
                timeout=appmesh.HttpTimeout(
                    per_request=cdk.Duration.seconds(120)
                )
            )],
            service_discovery=appmesh.ServiceDiscovery.cloud_map(service=self.cloudmap_service),
            virtual_node_name=self.module_prefix + "-VirtualNode"
        )
        virtual_node.node.add_dependency(self.cloudmap_service)
        return virtual_node
    
    def set_virtual_service(self):
        virtual_srvc_name=self.module_prefix + ".cdk.mesh.local"

        virtual_service = appmesh.VirtualService(self, "VirtualService",
            virtual_service_provider=appmesh.VirtualServiceProvider.virtual_node(
                virtual_node=self.virtual_node
            ),
            virtual_service_name=virtual_srvc_name
        )
        virtual_service.node.add_dependency(self.virtual_node)
        return virtual_service

    def set_stack_output(self):
        cdk.CfnOutput(self, id="StackOutput",
            value=self.virtual_service.virtual_service_name,
            export_name=cdk.Aws.STACK_NAME + "-" + self.module_prefix + "VirtualService"
        )
```

### What did you expect to happen?

`cdk diff` or `cdk deploy` command to pass without errors

### What actually happened?

```
jsii.errors.JavaScriptError: 
  Error: Resolution error: Supplied properties not correct for "CfnVirtualNodeProps"
    spec: supplied properties not correct for "VirtualNodeSpecProperty"
      backends: element 0: supplied properties not correct for "BackendProperty"
        virtualService: supplied properties not correct for "VirtualServiceBackendProperty"
          virtualServiceName: required but missing.
      at ValidationResult.assertSuccess (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/runtime.js:1:2506)
      at cfnVirtualNodePropsToCloudFormation (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/aws-appmesh/lib/appmesh.generated.js:1:167519)
      at CfnVirtualNode.renderProperties (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/aws-appmesh/lib/appmesh.generated.js:1:170719)
      at PostResolveToken.Resources [as processor] (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:4075)
      at PostResolveToken.postProcess (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/util.js:1:1566)
      at Object.postProcess (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1220)
      at DefaultTokenResolver.resolveToken (/tmp/jsii-kernel-dJJeL
F/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1033)
      at resolve (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2652)
      at Object.resolve (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1094)
      at resolve (/tmp/jsii-kernel-dJJeLF/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2916)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "app.py", line 26, in <module>
    app.synth()
  File "/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 15813, in synth
    return typing.cast(_CloudAssembly_c693643e, jsii.invoke(self, "synth", [options]))
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 143, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 355, in invoke
    response = self.provider.invoke(
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Resolution error: Supplied properties not correct for "CfnVirtualNodeProps"
  spec: supplied properties not correct for "VirtualNodeSpecProperty"
    backends: element 0: supplied properties not correct for "BackendProperty"
      virtualService: supplied properties not correct for "VirtualServiceBackendProperty"
        virtualServiceName: required but missing.
```

### CDK CLI Version

2.7.0 (build cfb09d5)

### Node.js Version

v12.22.6

### OS

docker:stable on Linux version 4.14.171-136.231.amzn2.x86_64 (Red Hat 7.3.1-6)

### Language

Python

### Language Version

Python 3.8.10

### Other information

npm version: 8.3.0

**Comment by Seiya6329** [comment] 2022-01-13 17:49
@niks913 - Thank you very much for reporting an issue and we deeply apologize for the inconvenience you are experiencing from this. We are taking a look at this.

Will update this thread by end of the week.

**Comment by niks913** [comment] 2022-01-15 03:43
I'll give it a try and update you.

Thank you

**Comment by Seiya6329** [comment] 2022-01-24 23:58
@niks913 - Just checking in if you had a chance to try above proposed solution. Please keep up posted.

**Comment by niks913** [comment] 2022-01-25 17:02
I tried using the `VirtualNode.addBackend()` method, but no success.

`jsii.errors.JavaScriptError: 
  Error: Resolution error: Supplied properties not correct for "CfnVirtualNodeProps"
    spec: supplied properties not correct for "VirtualNodeSpecProperty"
      backends: element 0: supplied properties not correct for "BackendProperty"
        virtualService: supplied properties not correct for "VirtualServiceBackendProperty"
          virtualServiceName: required but missing.
      at ValidationResult.assertSuccess (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/runtime.js:1:2506)
      at cfnVirtualNodePropsToCloudFormation (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/aws-appmesh/lib/appmesh.generated.js:1:167519)
      at CfnVirtualNode.renderProperties (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/aws-appmesh/lib/appmesh.generated.js:1:170719)
      at PostResolveToken.Resources [as processor] (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/cfn-resource.js:1:4075)
      at PostResolveToken.postProcess (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/util.js:1:1566)
      at Object.postProcess (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1220)
      at DefaultTokenResolver.resolveToken (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1033)
      at resolve (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2652)
      at Object.resolve (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:1094)
      at resolve (/tmp/jsii-kernel-ipKGJf/node_modules/aws-cdk-lib/core/lib/private/resolve.js:1:2916)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "app.py", line 26, in <module>
    app.synth()
  File "/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 15813, in synth
    return typing.cast(_CloudAssembly_c693643e, jsii.invoke(self, "synth", [options]))
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 143, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 355, in invoke
    response = self.provider.invoke(
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 359, in invoke
    return self._process.send(request, InvokeResponse)
  File "/.venv/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Resolution error: Supplied properties not correct for "CfnVirtualNodeProps"
  spec: supplied properties not correct for "VirtualNodeSpecProperty"
    backends: element 0: supplied properties not correct for "BackendProperty"
      virtualService: supplied properties not correct for "VirtualServiceBackendProperty"
        virtualServiceName: required but missing.`

I can try passing `VirtualService` directly instead of using `from_virtual_service_attributes()` but the issue is I needed to fetch the Virtual service using its attributes in my use case as I create my virtual services in another stack and them import the same here using virtual service name.

**Comment by Seiya6329** [comment] 2022-01-25 17:57
@niks913 - Thanks for giving try. If you are seeing same issue by using `VirtualNode.addBackend()` method, this issue might be specific to `python` language.

I will try to reproduce the error by using `python` language.

**Comment by Seiya6329** [comment] 2022-01-27 21:24
We may need little more time to investigate this issue. 

Will update this thread before mid-next week.

**Comment by Seiya6329** [comment] 2022-02-04 03:26
@niks913 - Thanks for waiting. I was also not able to reproduce the error using `python`.

I am suspecting your CDK environments might be using different versions . Can you double check if you have updated all versions?

**Comment by Seiya6329** [comment] 2022-02-11 01:25
@niks913 - Checking in to see if you had seen a resolution. Please kindly share your status.

**Comment by Seiya6329** [comment] 2022-02-17 18:38
We will be closing this issue for now.
Please kindly open new issue if anyone still find a problem.

**Closed by Seiya6329** 2022-02-17 18:38 UTC
Labels: bug, p2, language/python, @aws-cdk/aws-appmesh
