### ISSUE TITLE
@aws-cdk/aws-appsync: Add ability to create resolvers with "operation": "BatchInvoke"

### ISSUE THREAD

**Issue by asnaseer-resilient** [aws/aws-cdk#14079] opened 2021-04-09 12:13 UTC
I want to setup an AppSync resolver using the CDK to use `"operation": "BatchInvoke"` as described here https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html#advanced-use-case-batching

I am currently using the **createResolver** function to create my resolvers but cannot see a way to specify this type of operation - see here: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-appsync.LambdaDataSource.html#createwbrresolverpropsspan-[…]y-change-without-noticespan

### Use Case

The link above describes my use case.

### Proposed Solution

None

### Other

N/A

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by asnaseer-resilient** [comment] 2021-05-06 16:46
Any chance of this getting implemented in the near future?

**Comment by MrArnoldPalmer** [comment] 2021-05-06 17:37
@asnaseer-resilient the core team is not actively working on adding features to appsync right now. PRs from the community are always welcome or you may be able to implement this by extending the [`BaseDataSource`](https://github.com/aws/aws-cdk/blob/a75d52fb82ad9a4f526f82aa58ff8ee74d35a3cd/packages/%40aws-cdk/aws-appsync/lib/data-source.ts#L94).

I don't have any experience using BatchInvoke in CFN, @BryanPan342 you have any guidance to add here for implementing?

**Comment by BryanPan342** [comment] 2021-05-06 22:08
I also don't have experience with BatchInvoke, but it looks like a **Mapping Template** issue that I honestly don't have that good of an answer for 😔

I know @duarten created an RFC for mapping templates and I think that would be nice to have even though JS is looking like an alternative.. would definitely require more thought

**Comment by duarten** [comment] 2021-05-06 22:35
Most of that effort is in https://github.com/umani/ribosome, which works but isn't pretty (the API was designed to be compatible with the constraints of jsii, in case it would ever be merged into the cdk). But yeah, looking forward to JS resolvers :)

**Comment by asnaseer-resilient** [comment] 2021-05-06 23:08
I have had a look around the code base and I think the change would need to be made in **mapping-template.ts** in this method: https://github.com/aws/aws-cdk/blob/a75d52fb82ad9a4f526f82aa58ff8ee74d35a3cd/packages/%40aws-cdk/aws-appsync/lib/mapping-template.ts#L95

That method currently seems to hardwire the **operation** to "Invoke" as follows:
```
  public static lambdaRequest(payload: string = '$util.toJson($ctx)'): MappingTemplate {
    return this.fromString(`{"version": "2017-02-28", "operation": "Invoke", "payload": ${payload}}`);
  }
```
So maybe you could introduce an additional optional parameter as follows for backwards compatibility:
```
  public static lambdaRequest(payload: string = '$util.toJson($ctx)', operation: string = 'Invoke'): MappingTemplate {
    return this.fromString(`{"version": "2017-02-28", "operation": "${operation}", "payload": ${payload}}`);
  }
```
and then expose the ability to set this in the CDK. I am not really familiar enough with any of the CDK codebase to attempt to make any changes to it myself.

**Comment by BryanPan342** [comment] 2021-05-07 23:16
@asnaseer-resilient I'm currently working on the schema validation PR, but ill see what I can do. It does seem pretty straightforward but I want to make sure I read more about mapping templates before I implement anything that will change the API.

**Comment by asnaseer-resilient** [comment] 2021-06-02 10:56
@BryanPan342 - Any updates on this?

**Comment by BryanPan342** [comment] 2021-06-02 22:31
> @BryanPan342 - Any updates on this?

I'm finishing up my school quarter atm so don't have the bandwidth atm, but will look to implement it sometime in the summer

**Closed** 2021-07-19 23:00 UTC
Labels: @aws-cdk/aws-appsync, effort/small, feature-request, p2
