### ISSUE TITLE
SNS-Subs: cannot subscribe the same Lambda multiple times

### ISSUE THREAD

**Issue by spg** [aws/aws-cdk#8243] opened 2020-05-27 18:42 UTC
When adding multiple subscriptions for the same Lambda function to a SNS Topic, the following error happens:
```
➜  myproject git:(master) ✗ npx cdk diff '*'
There is already a Construct with name 'AllowInvoke:Playgroundtopic01BC750E' in Function [WebhookHandlerFunction]
Subprocess exited with error 1
```

It seems like the CDK is trying to create the `AWS::Lambda::Permission` between the given Lambda function and the SNS topic multiple times.

### Reproduction Steps

Add multiple Lambda subscriptions to a given SNS topic:
```typescript
    const topic = sns.Topic.fromTopicArn(
      this,
      "topic",
      cdk.Fn.importValue("GhWebhook:TopicArn")
    );

    topic.addSubscription(
      new snsSubs.LambdaSubscription(webhookHandlerFunction, {
        filterPolicy: {
          ghEvent: sns.SubscriptionFilter.stringFilter({
            whitelist: ["push"],
          }),
        },
      })
    );
    topic.addSubscription(
      new snsSubs.LambdaSubscription(webhookHandlerFunction, {
        filterPolicy: {
          ghEvent: sns.SubscriptionFilter.stringFilter({
            whitelist: ["delete"],
          }),
          "ghBody.ref_type": sns.SubscriptionFilter.stringFilter({
            whitelist: ["branch"],
          }),
        },
      })
    );
    topic.addSubscription(
      new snsSubs.LambdaSubscription(webhookHandlerFunction, {
        filterPolicy: {
          ghEvent: sns.SubscriptionFilter.stringFilter({
            whitelist: ["package"],
          }),
          "ghBody.action": sns.SubscriptionFilter.stringFilter({
            whitelist: ["published"],
          }),
        },
      })
    );
```

### Environment

  - **CLI Version      : 1.42.0**
  - **Framework Version: 1.42.0**
  - **OS               : OS X**
  - **Language         : Typescript**

### Other

--- 

This is :bug: Bug Report

**Comment by michaelwiles** [comment] 2020-05-29 18:20
I guess the writers never thought you'd want to subscribe a lambda twice to the same topic.

I do wonder what the solution here is... should that code just check if there is one already and leave it there? That's pretty much the only option.

But the problem's going to come when you remove one of those subscription. It's going to be quite hard to figure out whether the permission should be deleted or not. It's going to need to consider more than just the state of that individual lambda subscription. Going to need to look and see if all of them have been removed before it removes the permission.

As a work around in the mean time why don't you create multiple versions of the lambda and subscribe each of those versions to the lambda.

**Comment by MrArnoldPalmer** [comment] 2020-06-03 17:00
Hey there, this looks like a duplicate of #7832. That issue points to a potential solution based on the way SQS handles it.

Closing in favor of that

**Closed by MrArnoldPalmer** 2020-06-03 17:00 UTC
Labels: @aws-cdk/aws-sns-subscriptions, bug, needs-triage
