### ISSUE TITLE
[@aws-cdk/ecs] ECS BottleRocket OS Support. 

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/aws-cdk#9945] opened 2020-08-24 18:55 UTC
Adds support to ECS constructs to run on EC2 capacity with BottleRocket AMIs.

### Details

Currently there are some known issues with the ECS L2/L3 constructs that prevent usage with clusters running the BottleRocket OS. For example, https://github.com/aws/aws-cdk/issues/9778 describes that the current hardcoded ephemeral port range for task-definition isn't wide enough for use within BottleRocket or ARM platforms.

The current constructs also embed user bash user data automatically, which BottleRocket doesn't support.

BottleRocket uses a module called [early-boot-config](https://github.com/bottlerocket-os/bottlerocket/tree/develop/sources/api/early-boot-config) that accepts api commands via user data for OS configuration. User data constructs will have to be able to support this format.

Other specific issues with BR support may become uncovered and can be tracked here. [EKS support](https://github.com/aws/aws-cdk/pull/7282) has already been added which may give us some guidance as to what else needs to be covered.

---

This is a :rocket: Feature Request

**Comment by SoManyHs** [comment] 2021-05-13 01:35
Duplicate of https://github.com/aws/aws-cdk/issues/10085

**Closed by SoManyHs** 2021-05-13 01:35 UTC
Labels: @aws-cdk/aws-ecs, @aws-cdk/aws-ecs-patterns, effort/medium, feature-request, feature/pattern, p2
