### ISSUE TITLE
[aws-s3-deployment] Doesn't work with the new verison of bootstrap

### ISSUE THREAD

**Issue by jonny-rimek** [aws/aws-cdk#9656] opened 2020-08-12 21:29 UTC
I upgraded to the new version of bootstrap to work with the pipelines construct, but I can't create a aws-s3-deployment anymore.

error message:

````
11:17:48 PM | CREATE_FAILED        | Custom::CDKBucketDeployment               | frontend/DeployWeb...omResource/Default
Failed to create resource. Command '['python3', '/var/task/aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-ACCOUNTID-us-east-1/assets/00d41f76827bf5f7ae8ad69
96e0fd0148631ae2598a2a1c4d589cfb001d3af20.zip', '/tmp/tmp16zb0xzf/8961495e-aa20-4939-bba6-92c810182838']' returned non-zero exit status 1.
````
everything else works fine. I can still deploy, fargate, s3, API GW v1, lambdas etc.
I tried deleting the aws-s3-deployment construct and redeploying it, but the error persists

full stack trace:
````
11:17:48 PM | CREATE_FAILED        | Custom::CDKBucketDeployment               | frontendDeployWebs...omResource76C4D436
Failed to create resource. Command '['python3', '/var/task/aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-ACCOUNTID-us-east-1/assets/00d41f76827bf5f7ae8ad69
96e0fd0148631ae2598a2a1c4d589cfb001d3af20.zip', '/tmp/tmp16zb0xzf/8961495e-aa20-4939-bba6-92c810182838']' returned non-zero exit status 1.

	new CustomResource (/home/jonny/dev/wowmate/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
	\_ new BucketDeployment (/home/jonny/dev/wowmate/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts:201:5)
	\_ new Frontend (/home/jonny/dev/wowmate/lib/frontend.ts:75:3)
	\_ new Wowmate (/home/jonny/dev/wowmate/lib/wowmate-stack.ts:25:3)
	\_ Object.<anonymous> (/home/jonny/dev/wowmate/bin/wowmate.ts:16:1)
	\_ Module._compile (internal/modules/cjs/loader.js:1137:30)
	\_ Module.m._compile (/home/jonny/dev/wowmate/node_modules/ts-node/src/index.ts:858:23)
	\_ Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
	\_ Object.require.extensions.<computed> [as .ts] (/home/jonny/dev/wowmate/node_modules/ts-node/src/index.ts:861:12)
	\_ Module.load (internal/modules/cjs/loader.js:985:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:878:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ main (/home/jonny/dev/wowmate/node_modules/ts-node/src/bin.ts:227:14)
	\_ Object.<anonymous> (/home/jonny/dev/wowmate/node_modules/ts-node/src/bin.ts:513:3)
	\_ Module._compile (internal/modules/cjs/loader.js:1137:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
	\_ Module.load (internal/modules/cjs/loader.js:985:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:878:14)
	\_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
	\_ /usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14


 ❌  WoWM failed: Error: The stack named WoWM failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:294:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:266:26)
    at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:181:24)
    at main (/usr/lib/node_modules/aws-cdk/bin/cdk.ts:268:16)
    at initCommandLine (/usr/lib/node_modules/aws-cdk/bin/cdk.ts:188:9)
The stack named WoWM failed to deploy: UPDATE_ROLLBACK_COMPLETE
````

### Reproduction Steps
- create aws-s3-deployment
- deploy
- switch to new bootstrap
- deploy again

### Environment

  - **CLI Version      : 1.58
  - **Framework Version: 1.58
  - **Node.js Version: 12.18.3 
  - **OS               : ubuntu 20.04
  - **Language (Version): typescript

This is :bug: Bug Report

**Comment by jonny-rimek** [comment] 2020-08-12 21:35
looks like there is an issue, feel free to close

**Comment by shivlaks** [comment] 2020-08-14 04:04
thanks @jonny-rimek - resolving this as a duplicate of #9414 where we can continue the discussion and track the fix.

**Closed by shivlaks** 2020-08-14 04:04 UTC
Labels: @aws-cdk/aws-s3-deployment, bug, needs-triage
