### ISSUE TITLE
CDK Can't find credentials when using cdk --profile on an EC2 instance + Instance Profile

### ISSUE THREAD

**Issue by sktan** [aws/aws-cdk#4287] opened 2019-09-29 07:22 UTC
It does not looks like CDK loads the credentials properly when assuming a role (configured in ~/.aws/config) on an EC2 instance + Instance Profile.

The current indication seems to be that CDK is looking credentials in ~/.aws/credentials, but there won't be any credentials stored on the EC2 instance.

### Reproduction Steps

~/.aws/config
```
[profile testaccount]
region = ap-southeast-2
role_arn = arn:aws:iam::123456789012:role/test-admin-role
credential_source = Ec2InstanceMetadata
```

app.py
```
#!/usr/bin/env python3

from aws_cdk import core

from cdk.test_stack import TestStack

app = core.App()

TestStack(app, "teststack", env=core.Environment(account='123456789012', region='ap-southeast-2'))

app.synth()
```

```
cdk diff --profile testaccount teststack
Need to perform AWS calls for account 123456789012, but no credentials found. Tried: default credentials.
```

### Error Log

```
CDK toolkit version: 1.9.0 (build 30f158a)
Command line arguments: {
  _: [ 'diff' ],
  strict: false,
  'ignore-errors': false,
  ignoreErrors: false,
  json: false,
  j: false,
  verbose: true,
  v: true,
  ec2creds: undefined,
  i: undefined,
  'version-reporting': undefined,
  versionReporting: undefined,
  'path-metadata': true,
  pathMetadata: true,
  'asset-metadata': true,
  assetMetadata: true,
  staging: true,
  profile: 'testaccount',
  'role-arn': undefined,
  r: undefined,
  roleArn: undefined,
  'context-lines': 3,
  contextLines: 3,
  '$0': 'cdk',
  STACKS: [ 'teststack' ],
  stacks: [ 'teststack' ]
}
Determining whether we're on an EC2 instance.
cdk.json: {
  "app": "python3 app.py"
}
Looks like EC2 instance.
merged settings: {
  versionReporting: true,
  pathMetadata: true,
  output: 'cdk.out',
  app: 'python3 app.py',
  context: {},
  tags: [],
  assetMetadata: true,
  toolkitBucket: {},
  staging: true
}
Unable to determine AWS region from environment or AWS configuration (profile: "testaccount")
Setting "CDK_DEFAULT_REGION" environment variable to undefined
Resolving default credentials
Retrieved account ID 123456789000 from disk cache
Setting "CDK_DEFAULT_ACCOUNT" environment variable to 123456789000
context: {
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true
}
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: undefined,
  CDK_DEFAULT_ACCOUNT: '123456789000',
  CDK_CONTEXT_JSON: '{"aws:cdk:enable-path-metadata":true,"aws:cdk:enable-asset-metadata":true}',
  CDK_OUTDIR: 'cdk.out'
}
Some context information is missing. Fetching...
Need to perform AWS calls for account 123456789012, but no credentials found. Tried: default credentials.
Error: Need to perform AWS calls for account 123456789012, but no credentials found. Tried: default credentials.
    at CredentialsCache.getCredentials (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:261:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CredentialsCache.get (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:223:25)
    at SDK.ec2 (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/api/util/sdk.ts:126:20)
    at VpcNetworkContextProviderPlugin.getValue (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/context-providers/vpcs.ts:16:17)
    at Object.provideContextValues (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/context-providers/index.ts:31:19)
    at AppStacks.synthesizeStacks (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/api/cxapp/stacks.ts:209:9)
    at AppStacks.listStacks (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/api/cxapp/stacks.ts:179:22)
    at AppStacks.selectStacks (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/api/cxapp/stacks.ts:109:20)
    at CdkToolkit.diff (/home/ec2-user/.nvm/versions/node/v12.11.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:45:20)
```

### Environment

  - **CLI Version      :** 1.9.0
  - **Framework Version:** 1.9.0
  - **OS               :** Amazon Linux 2
  - **Language         :** Python

### Other

AWS CLI, boto3 and aws-sdk (ruby) seems to assume the roles perfectly fine when running the aws s3 ls command (and using the AWS_PROFILE environment variable), but CDK does not seem to work this way.

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2019-10-01 11:43
Closing as duplicate of https://github.com/aws/aws-cdk/issues/1656. Please reopen if this is not a duplicate.

**Closed by rix0rrr** 2019-10-01 11:43 UTC
Labels: bug, language/python, package/ec2, package/iam, status/needs-triage
