### ISSUE TITLE
[RDS] Issue with credentials & Secret attachment

### ISSUE THREAD

**Issue by Cloudrage** [aws/aws-cdk#11040] opened 2020-10-22 16:14 UTC
When updating a SecretsManager Secret defined in "credentials" prop of an RS Instance, we lost the attachment.

### Reproduction Steps

Create an RDS Instance with "credentials" prop targeting a Secret.
Update the Secret.

### What did you expect to happen?

I want to update my Secret but keep the attachment ith the DB.

### What actually happened?

You lost the attachment and it's not possible to add it because we have an error :
`Secret is already attached to a target.`

So a workaround is to update the DB with no/or another Secret.
But in that case, DB Instance is replaced/recreated (???!!!)

### Environment

  - **CLI Version      :** 1.68.0
  - **Framework Version:** 6.14.8
  - **Node.js Version:** v12.15.0
  - **OS               :** Linux
  - **Language (Version):** TypeScript

### Other

In my case, I've update the DB without the prop "credentials", then, update it again with my Secret (the Original one).
But it recreate @ll my DB instances 2 times and lost datas of course...

`credentials: rds.Credentials.fromSecret(SecretsManager)`

--- 

This is :bug: Bug Report

**Comment by skinny85** [comment] 2020-10-27 16:51
@Cloudrage is this a duplicate of #10800?

**Comment by Cloudrage** [comment] 2020-10-30 08:13
Hello @skinny85 ,

Not really sure but indeed, when updating the Secret, all fields generated by the attachment was lost.

**Comment by skinny85** [comment] 2020-11-02 21:20
Ok. Let's close this one then, and move the conversation to #10800 to have it all in one place.

**Closed by skinny85** 2020-11-02 21:20 UTC
Labels: @aws-cdk/aws-rds, bug, in-progress, needs-triage
