### ISSUE TITLE
When using aws-cdk as a library, `Vpc.fromLookup` fails

### ISSUE THREAD

**Issue by patrobinson** [aws/aws-cdk#7843] opened 2020-05-07 10:58 UTC
I'm trying to use CDK in a TypeScript project. Basically this script helps you setup a new ECS Service. I want to use CDK to setup a load balancer, so generate the template and deploy the cloudformation template.
This is a bit different to all the other use cases as we're not executing the command line.

But when calling `fromLookup` it just returns a dummy VPC.

### Reproduction Steps

Here's a code example https://gist.github.com/patrobinson/312b3fb955758cd19528b89b4b757605

### Error Log

I turned on debug logging but nothing of use was logged

### Environment

  - **CLI Version      :*1.37.0*
  - **Framework Version:*1.37.0*
  - **OS               :*OSX*
  - **Language         :*TypeScript*

--- 

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2020-05-13 09:25
Yes, the missing information is furbished by the CLI. 

Duplicate of https://github.com/aws/aws-cdk/issues/601

**Closed by rix0rrr** 2020-05-13 09:25 UTC
Labels: @aws-cdk/aws-ec2, bug, guidance, needs-triage
