### ISSUE TITLE
AutoScalingGroup vpc_subnets doesn't seem to do anything

### ISSUE THREAD

**Issue by jordan-dimov** [aws/aws-cdk#3859] opened 2019-08-29 09:01 UTC
### What is the problem?
I'm using cdk with Python and have an AutoScalingGroup launching an EC2 instance within a vpc. Everything was working fine, except when I tried to add `vpc_subnets` to the constructor in order to specify which subnet I want the instance to launch in, `cdk synth` resulted in no differences to the CloudFormation templates and `cdk diff` doesn't reflect that either. 

### Reproduction Steps

If you have code like the following, the `vpc_subnets` parameter doesn't seem to be honoured:

    aws_autoscaling.AutoScalingGroup(
        self, "MyAutoscalingGroup", 
        vpc=my_vpc,
        instance_type=aws_ec2.InstanceType.of(aws_ec2.InstanceClass.STANDARD5, aws_ec2.InstanceSize.XLARGE),
        machine_image=aws_ec2.WindowsImage(
            version=aws_ec2.WindowsVersion.WINDOWS_SERVER_2019
        ),
        vpc_subnets=aws_ec2.SubnetSelection(subnet_name="subnet-0af00000000000000"),  # (using valid subnet ID here)
    )

### Environment

  - **CDK CLI Version:** 1.6.0
  - **Module Version:** aws-cdk.aws-autoscaling==1.6.0
  - **OS:** Ubuntu
  - **Language:** Python

**Comment by rix0rrr** [comment] 2019-09-16 09:52
This seems to be a duplicate of https://github.com/aws/aws-cdk/issues/3548 (select individual subnets).

It's also a misuse of the API, which will be made more clear in an upcoming PR.

**Closed** 2019-09-16 14:40 UTC
Labels: bug, language/python, package/ec2, package/vpc
