### ISSUE TITLE
(logs): Log Group ARN has extra `:*`

### ISSUE THREAD

**Issue by kylelaker** [aws/aws-cdk#18253] opened 2022-01-03 22:12 UTC
### What is the problem?

The `logGroupArn` attribute for a `LogGroup` L2 construct has an extra `:*` at the end of the ARN. While this matches the behavior of CloudFormation's [`Arn` attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#aws-resource-logs-loggroup-return-values) for an `AWS::Logs::LogGroup`, it does not match the [documented structure](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html) for a Log Group. This breaks integration with other services, such as the creation of an `AWS::WAFv2::LoggingConfiguration`, which requires the ARN of the Log Group without `:*`.

### Reproduction Steps

Build the following constructs within a `Stack`. (Sorry for the length; building a Web ACL is noisy)

```ts
import * as wafv2 from "aws-cdk-lib/aws-wafv2";
import * as logs from "aws-cdk-lib/aws-logs";

const acl = new waf.CfnWebACL(this, "ACL", {
  scope: "REGIONAL",
  defaultAction: {
    allow: {},
  },
  visibilityConfig: {
    sampledRequestsEnabled: true,
    cloudWatchMetricsEnabled: true,
    metricName: "SampleACLMetric",
  },
  rules: [
    {
      name: "RuleWithAWSManagedRules",
      priority: 0,
      overrideAction: {
        none: {},
      },
      statement: {
        managedRuleGroupStatement: {
          vendorName: "AWS",
          name: "AWSManagedRulesCommonRuleSet",
          excludedRules: [],
        },
      },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: "SampleAWSManagedRulesMetric",
      },
    },
  ],
});

const aclLogGroup = new logs.LogGroup(this, "ACLLogs", {
  // WAFv2 Log Groups must begin with `aws-waf-logs`. Including the ACL's
  // ID hopefully prevents name conflicts.
  logGroupName: `aws-waf-logs-${acl.attrId}`,
});

const logConfig = new wafv2.CfnLoggingConfiguration(scope, "WebAclLogging", {
  logDestinationConfigs: [aclLogGroup.logGroupArn],
  resourceArn: acl.attrArn,
});
```

### What did you expect to happen?

The `AWS::WAFv2::LoggingConfiguration` resource should create successfully, referencing the `logGroupArn` attribute directly.

The `LogGroup` construct should provide the ARN in the format specified by the documentation, including
 - [CWL IAM overview](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html)
 - the [CWL SAR section](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatchlogs.html#amazoncloudwatchlogs-resources-for-iam-policies)

### What actually happened?

The `AWS::WAFv2::LoggingConfiguration` resource failed to create with the error:

> Resource handler returned message: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: LOG_DESTINATION, parameter: arn:aws:logs:us-east-1:1234657890:log-group:aws-waf-logs-foo:*

The `LogGroup.logGroupArn` had an `:*` that was not documented as part of the ARN according to most documentation for the ARN of a Log Group.

### CDK CLI Version

2.3.0 (build beaa5b2)

### Node.js Version

v14.18.2

### OS

Linux

### Language

Typescript

### Other information

It may be more viable to fix this in _other_ L2 constructs that need a log group than it is to fix it in the `LogGroup` construct itself at this point (and it doesn't seem that L2 constructs for the Web ACL logging configuration exist yet).

A workaround is to construct the ARN manually (with adjustments if the Log Group is in another account/region):

```ts
// The `.logGroupArn` attribute of `LogGroup` contains a `:*` at the end,
// which causes conflicts with the Web ACL Logging Configuration
const logGroupArn = Stack.of(this).formatArn({
  arnFormat: ArnFormat.COLON_RESOURCE_NAME,
  service: "logs",
  resource: "log-group",
  resourceName: aclLogGroup.logGroupName,
});
```

**Comment by peterwoodworth** [comment] 2022-01-04 20:16
I believe that this is intentional, since the arn comes directly from CloudFormation.

Here's where the arn is set https://github.com/aws/aws-cdk/blob/bfbdf64696a05a9a1b9dcad30904b17ff1a83f8c/packages/%40aws-cdk/aws-logs/lib/log-group.ts#L403-L417

I'm not sure what we would want to do here, since I'm not sure why CloudFormation includes this in the arn in the first place

**Comment by comcalvi** [comment] 2022-01-05 00:48
This is likely a bug in WAFv2. The CFN property that causes the issue, `LogDestinationConfigs`, is rendered to this CFN when I synthesize the provided template:

```"LogDestinationConfigs": [
          {
            "Fn::GetAtt": [
              "ACLLogs29F73701",
              "Arn"
            ]
          }
        ],
```
Those logs have the `:*` at the end of their ARN. Since CloudFormation is retrieving the actual specified ARN, WAFv2 must not be handling the ARN parameter correctly. I'll contact the WAFv2 team.

**Comment by ryancastle** [comment] 2022-01-27 01:05
Workaround example...
```
const logGroup = new LogGroup(this, 'LogGroup', {
  logGroupName: `aws-waf-logs-firewall`,
  retention: RetentionDays.SIX_MONTHS,
  removalPolicy: RemovalPolicy.DESTROY,
});

const logDestination = Fn.select(0, Fn.split('*', logGroup.logGroupArn));
```

**Comment by BeatKO** [comment] 2022-02-10 14:39
Someone managed to solve it? i can't use the provided ARN, i get this error 
 Access log destination must only contain characters a-z, A-Z, 0-9, '_', '-', '/', '.': 'IDIDIDIDIDIDF:*'

**Comment by csumpter** [comment] 2022-02-10 14:50
@BeatKO 

```ts
      const loggingGroup = new cwLogs.LogGroup(this, "LogGroup", {
        // waf log group names must start with "aws-waf-logs-" or the stack will not deploy
        logGroupName: "aws-waf-logs-myname",
        retention: 30,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });
      new waf.CfnLoggingConfiguration(this, "LoggingConfiguration", {
        // the arn that comes back natively from the LogGroup has ":*" appended on the end of it, including it on the destination will cause a deploy time error
        logDestinationConfigs: [cdk.Fn.select(0, cdk.Fn.split(":*", loggingGroup.logGroupArn))],
        resourceArn: this.webAcl.attrArn,
```

**Comment by lacteolus** [comment] 2022-04-04 15:50
It seems that workaround doesn't work anymore. 
We started getting  error for newly created stacks.

> `Resource handler returned message: "Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit.`

Old stacks deployed before are updated without issues.
It's hard to exact date or CDK version when it happened, but I guess it started a few days ago with CDK >2.12.0
Tried to switch back to using ARN:

> `Resource handler returned message: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: LOG_DESTINATION, parameter` 

Can anyone confirm this issue even with workraround applied?

**Comment by newair** [comment] 2022-04-19 02:35
> It seems that workaround doesn't work anymore. We started getting error for newly created stacks.
> 
> > `Resource handler returned message: "Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit.`
> 
> Old stacks deployed before are updated without issues. It's hard to exact date or CDK version when it happened, but I guess it started a few days ago with CDK >2.12.0 Tried to switch back to using ARN:
> 
> > `Resource handler returned message: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: LOG_DESTINATION, parameter`
> 
> Can anyone confirm this issue even with workaround applied?

We faced the same issue. Started suddenly getting 

`Resource handler returned message: "Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit`

@lacteolus Did you find a solution for this?

Thanks !

**Comment by comcalvi** [comment] 2022-05-18 23:20
@aidbal the behavior you're describing is working as intended. In the past, `fromLogGroupArn()` would return the log group ARNs without any `:*` at the end, which would break integration with IAM. Unfortunately this is one of those cases where the L1 of one service and the L2 of another don't play nice, so the solution you described (creating the L2 from the L1, and passing that instead) is the intended behavior here. See this [PR](https://github.com/aws/aws-cdk/commit/5a1a929db7eb8f7be4ad973abc1cccda1cb24d23) for details.

**Comment by stanmarsh2** [comment] 2022-08-23 09:01
> `Resource handler returned message: "Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit`
> 
> @lacteolus Did you find a solution for this?

Yes, it's a different issue.
AWS creates 10 resource based policies per region, later after limit exceeded we need to create it by ourselves.
Resource policy docs: [link](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html)
CDK Api: `logGroup.addToResourcePolicy(...)`
More info and all kudos to @lorelei-rupp-imprivata : [link](https://github.com/hashicorp/terraform-provider-aws/issues/25296#issuecomment-1155453158)

**Comment by ericxinzhang** [comment] 2022-11-23 00:49
May I know if there is any update on this issue? I've tried all the workarounds mentioned and none worked. 

- I got the following error if I do not remove `:*`:
```
Resource handler returned message: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., 
field: LOG_DESTINATION, parameter: arn:aws:logs:us-west-2:1xxxxxxxxxx2:log-group:Dev-ProposalEstimateDefaultWebAclLogGroup:* 
(Service: Wafv2, Status Code: 400, Request ID: 509e6a4a-27f4-4f0c-b12e-1eec9581a415, Extended Request ID: null)"
```

- However I got the same error when I remove `:*` from the log group arn:
```
Resource handler returned message: 
"Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., 
field: LOG_DESTINATION, parameter: arn:aws:logs:us-west-2:1xxxxxxxxxx2:log-group:Dev-ProposalEstimateDefaultWebAclLogGroup 
(Service: Wafv2, Status Code: 400, Request ID: 88100430-dc58-4dee-aed4-2b98e85ec200, Extended Request ID: null)" 
```

I am using `aws-cdk-lib@2.46.0`. I literally cannot create log group for WebACL using CDK now.

**Comment by rupertbg** [comment] 2023-03-28 03:08
The Cloudformation return value for ARN of a Cloudwatch Log Group includes the * on the end, this is fundamental to the CF resource. You'll need to use the name instead and build an ARN string.

**Comment by richard-cp** [comment] 2024-02-29 09:08
Did anyone find a solution to this? 

I get the same error:
> Resource handler returned message: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: RESOURCE_ARN 

No matter how I format the ARN. 

I have tried the mentioned workaround `[cdk.Fn.select(0, cdk.Fn.split(":*", loggingGroup.logGroupArn))]` but get the same error.

In my case the log group already exists, and have tried specifying the ARN 6 different ways, hardcoding it to get around the L1 & L2 constructs "not playing nice" - as mentioned in a post above.

Example CDK snippet with the different ARNs attempted:
```
const loggingConfig = new wafv2.CfnLoggingConfiguration(
this,
`webacl-logging-config`,
  {
	  resourceArn: webAcl.ref,
	  logDestinationConfigs: ['arn:aws:logs:us-east-1:xxxxxxxxx:log-group:app-webacl-logs'],
      // logDestinationConfigs: ['arn:aws:logs:us-east-1:xxxxxxxxx:log-group:app-webacl-logs:'],
      // logDestinationConfigs: ['arn:aws:logs:us-east-1:xxxxxxxxx:log-group:app-webacl-logs:*'],
      // logDestinationConfigs: ['arn:aws:logs:us-east-1:xxxxxxxxx:log-group:/app-webacl-logs'],
      // logDestinationConfigs: ['arn:aws:logs:us-east-1:xxxxxxxxx:log-group:/app-webacl-logs:'],
      // logDestinationConfigs: ['arn:aws:logs:us-east-1:xxxxxxxxx:log-group:/app-webacl-logs:*'],
  },
);
```

Not sure I understand what the problem is here - has anyone got a workaround that still works?

**Comment by ryancastle** [comment] 2024-03-01 07:45
Probably related to the Log Group name requirement?

https://docs.aws.amazon.com/waf/latest/developerguide/logging-cw-logs.html#logging-cw-logs-naming

**Comment by arash-cid** [comment] 2024-03-07 23:51
This is so stupid.

The error is the **Log group Name must start with `aws-waf-logs-`**

F AWS, F Microsoft

**Comment by pahud** [comment] 2024-03-13 15:27
Just bumped this issue to p1 and self-assigned. I will be looking into this issue and escalate to the team when necessary.

**Comment by pahud** [comment] 2024-03-13 16:49
I am able to `cdk deploy` with the provided sample in the original post.

```ts
export class DummyStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);


    const acl = new wafv2.CfnWebACL(this, "ACL", {
      scope: "REGIONAL",
      defaultAction: {
        allow: {},
      },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: "SampleACLMetric",
      },
      rules: [
        {
          name: "RuleWithAWSManagedRules",
          priority: 0,
          overrideAction: {
            none: {},
          },
          statement: {
            managedRuleGroupStatement: {
              vendorName: "AWS",
              name: "AWSManagedRulesCommonRuleSet",
              excludedRules: [],
            },
          },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: "SampleAWSManagedRulesMetric",
          },
        },
      ],
    });
    
    const aclLogGroup = new logs.LogGroup(this, "ACLLogs", {
      // WAFv2 Log Groups must begin with `aws-waf-logs`. Including the ACL's
      // ID hopefully prevents name conflicts.
      logGroupName: `aws-waf-logs-${acl.attrId}`,
    });
    
    const logConfig = new wafv2.CfnLoggingConfiguration(this, "WebAclLogging", {
      logDestinationConfigs: [aclLogGroup.logGroupArn],
      resourceArn: acl.attrArn,
    });


  }
}
```

The `AWS::WAFv2::LoggingConfiguration` resource was created with no error.

I assume this issue does not exist anymore.

Please comment if does.


% npx cdk --version
2.132.0 (build 9a51c89)

**Comment by mo7ty** [comment] 2024-03-13 17:29
> I assume this issue does not exist anymore.

Probably CDK might be already handling LogGroup's ARN with _extra_ `:*`, because the ARN of a LogGroup still carries it.

**Comment by emanserav** [comment] 2024-04-08 18:07
hi @pahud, interesting for me is still not working
cdk version 
2.133.0 (build dcc1e75)
I am still getting the same error:
_Resource handler returned message: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: LOG_DESTINATION, parameter:_

**Comment by pahud** [comment] 2024-04-17 17:03
As this issue doesn't seem to existing anymore. I am closing it now.
Feel free to create a new issue if there's any concern.

**Closed by pahud** 2024-04-17 17:03 UTC
Labels: p1, feature-request, effort/small, @aws-cdk/aws-logs, feature/enhancement

**Comment by MyNameIsTakenOMG** [comment] 2024-08-06 22:52
Same here, I bumped into this issue today using L2 construct to create a log group for my cognito service `LogConfiguration`, and I got cloudformation yelled at me, saying that this `:*` is invalid.

Besides, I also found a open issue on Re: Post, [CloudFormation regex validation error in Cognito::LogDeliveryConfiguration](https://repost.aws/en/questions/QUhjYRB83zR_Od3frN-PRQww/cloudformation-regex-validation-error-in-cognito-logdeliveryconfiguration-cloudwatchlogsconfiguration-loggrouparn).

Unluckily,  by the time I am writing, this issue still exists though

**Comment by blimmer** [comment] 2025-02-24 17:19
This seems to be fixed with `CfnLoggingConfiguration` from WAFv2. My guess is this was fixed in the upstream WAF construct, since the `attrArn` value for Log Groups still includes the `:*` suffix.

**Comment by artomulkahainen-elenium** [comment] 2025-02-27 05:48
I banged my head today with this few hours, but didn't notice the requirement that log group name must start with "aws-waf-logs-".

@pahud solution worked on me after renaming my log group.
