### ISSUE TITLE
(ecs): fromLookup for ECS Cluster

### ISSUE THREAD

**Issue by RichiCoder1** [aws/aws-cdk#18046] opened 2021-12-16 03:12 UTC
### Description

Currently there's a way to hydrate an `ICluster` in a stack, but it requires knowing a lot more information then should arguably be necessary for a given stack.

### Use Case

Sharing an ECS Cluster across stacks with minimal information required.

### Proposed Solution

A `fromLookup` method on `aws_ecs.Cluster` that accepts `clusterName` or `clusterArn`

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by madeline-k** [comment] 2022-01-25 01:36
Hello @RichiCoder1 , would `fromClusterArn` work for what you need? This function exists on `aws_ecs.Cluster`, but is missing from the documentation (not sure why, but I can't find it right now). You can see the function signature and description in the source code here: https://github.com/aws/aws-cdk/blob/0ca81a118d3d54b87d2d05a53fb72e4efe03b591/packages/%40aws-cdk/aws-ecs/lib/cluster.ts#L113

**Comment by madeline-k** [comment] 2022-01-25 01:37
We could still add `fromClusterName`, so leaving this feature request open for that one.

**Comment by RichiCoder1** [comment] 2022-01-25 01:46
I think the downside of `fromClusterArn` is it mostly just populates the arn, so it's missing a lot of imported information too.

**Comment by madeline-k** [comment] 2022-01-31 22:53
Yep, good point. The `fromXXXArn` functions are basically just wrappers on the ARNs themselves, they don't provide any additional information about the resource. 

We could implement something similar to `Vpc.fromLookup` ([code link](https://github.com/aws/aws-cdk/blob/c46acd5f13442c43d0c2ed339e3091dd46002741/packages/%40aws-cdk/aws-ec2/lib/vpc.ts#L1141))for an ECS cluster that would actually go query the account for the necessary information during synthesis.

@RichiCoder1 we won't be able to get started on implementing this right now, but contributions are always welcome! If you are interested to implement this feature yourself, take a look at the [contributing guide](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/CONTRIBUTING.md) to get started.

**Comment by MrArnoldPalmer** [comment] 2023-01-27 22:51
Closing as duplicate of https://github.com/aws/aws-cdk/issues/14032

**Closed by MrArnoldPalmer** 2023-01-27 22:51 UTC
Labels: p2, feature-request, @aws-cdk/aws-ecs, effort/small
