### ISSUE TITLE
CfnSubscriptionFilter failed to create

### ISSUE THREAD

**Issue by MAVDcgcg** [aws/aws-cdk#12835] opened 2021-02-02 23:15 UTC
### The Question
I am currently working on adding the Datadog mapping to our environment. I am trying to deploy the mapping but I am getting a cryptic error when I try to deploy the code:

3/18 | 12:20:52 PM | UPDATE_FAILED        | AWS::CloudFormation::Stack | ratingEngine-api.NestedStack/ratingEngine-api.NestedStackResource (ratingEngineapiNestedStackratingEngineapiNestedStackResourceCAB987DC) Embedded stack arn:aws:cloudformation:us-west-2:902498374836:stack/AA00002988-dev-ethosApis-ratingEngineapiNestedStackratingEngineapiNestedStackResourceC-ZNF4OO18KR38/775c3780-4a0b-11eb-a2ed-06a2ba0f7427 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to create: [DatadogForwarderSubscriptionFilter]. The following resource(s) failed to update: [AA00002988devpostRatingFlagDriverAA00002988devpostRatingFlagDriverroleB08BC0E3, AA00002988devgetAllRatingFlagEngineRunsfunction14DDE2A2, AA00002988devpostRatingFlagTaskfunctionE0B7A5C4]. 

The code I have is as follows:

```
constructor(scope: cdk.Construct, id: string, props?: ResourceNestedStackProps) {
    super(scope, id, props);
    this.props = props
    this.addTransform("DatadogServerless");

    const subscription = new CfnSubscriptionFilter(this, 'DatadogForwarderSubscriptionFilter', {
      logGroupName: logGroupName,
      destinationArn: forwarderArn,
      filterPattern: ''
    });

    let datadogMapping = new cdk.CfnMapping(this, "Datadog", {
      mapping: {
        Parameters: {
          nodeLayerVersion: "44"
        },
      },
    });
  }
```
Here I am trying to instantiate a subscription filter so that the Datadog instance can forward our Lambda logs. But I am not having success with this approach and do not know why this error is happening.

### Environment

  - **CDK CLI Version:** 1.74.0
  - **Module Version:** 1.74.0
  - **Node.js Version:** 11.4.0
  - **OS:** mac OS Mojave
  - **Language (Version):** Typescript 3.9

**Comment by peterwoodworth** [comment] 2021-06-25 23:27
Hmm, is that the only error you receive when the stack fails to deploy? I'm not able to reproduce this

**Comment by peterwoodworth** [comment] 2021-07-08 00:09
Ping me if you're still running into this issue, I'll be closing it for now 😄

**Closed by peterwoodworth** 2021-07-08 00:09 UTC
Labels: guidance, response-requested
