### ISSUE TITLE
aws_dynamodb.Table.from_table_attributes().table_stream_arn returns null when passing table_name or arn

### ISSUE THREAD

**Issue by Nitin-GitUser** [aws/aws-cdk#7470] opened 2020-04-21 06:07 UTC
aws_cdk.aws_dynamodb.Table class has attributes table_arn and table_stream_arn but when we are importing the already created table outside the cdk stack with static method `from_table_attributes(self, id='dynamo-table', table_name='_tablename_')` it returns ITable object which has value of table_arn already set but table_stream_arn value is not set and returns None.

### Use Case

I am trying to create dynamodb trigger on already created table outside the cdk stack. For this I am importing value of table with `from_table_attributes(self, id='dynamo-table', table_name='_tablename_')` static method it returns ITable object which I am passing to `aws-lambda-event-source.DynamoEventSource(Impotedtableobject, starting_position='aws_lambda.StartingPosition.TRIM_HORIZON')`.

DynamoEventSource class return error below error that streams needs to be created:-

```
_jsii.errors.JavaScriptError: 
  Error: DynamoDB Streams must be enabled on the table cdk-environment/notificationslkjfs
      at DynamoEventSource.bind (/tmp/jsii-kernel-Un4KOI/node_modules/@aws-cdk/aws-lambda-event-sources/lib/dynamodb.js:18:19)
      at _wrapSandboxCode (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:7663:51)
      at Kernel._wrapSandboxCode (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:8299:19)
      at ret._ensureSync (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:7663:25)
      at Kernel._ensureSync (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:8272:20)
      at Kernel.invoke (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:7662:26)
      at KernelHost.processRequest (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:7371:28)
      at KernelHost.run (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:7311:14)
      at Immediate.setImmediate [as _onImmediate] (/home/ec2-user/environment/cdk-environment/.env/lib/python3.6/dist-packages/jsii/_embedded/jsii/jsii-runtime.js:7314:37)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)_
```
 
**While the streams are actually created on table but it is not able to refer that. Now if I propogate the **table_stream_arn** value in from_table_attributes static method of dynamodb.Table class it works fine but since we are dealing with different environments in different aws account passing the table_stream_arn value hardcoded in code is not a good way, it should be referred through from_table_attributes method** 

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by SomayaB** [comment] 2020-04-22 00:03
Hi @Nitin-GitUser, thanks for submitting an issue. Please fill out the provided issue template in order for us to have as much context into the issue you are having. You can just edit the original post. Thank you

**Comment by Nitin-GitUser** [comment] 2020-04-23 06:32
@SomayaB @RomainMuller updated the issue with template

**Comment by RomainMuller** [comment] 2020-05-11 08:15
@Nitin-GitUser - you are not providing a stream ARN when you're importing your DynamoDB table, which is why you're getting this error.

Can you try to add the `table_stream_arn` kwarg to your `Table.from_table_attributes` call, and see if that helps?

**Comment by Nitin-GitUser** [comment] 2020-05-12 11:31
Hi @RomainMuller, Yes I know that after passing **table_stream_arn** kwarg to  **Table.from_table_attributes** it works that is what I have also mentioned but I was requesting if we can get this value without passing it explicitly, because as a user I want to get all the attributes by just passing name of table and it helps in maintaining different environment with same code, passing table stream arn explicity is difficult and need hardcoding for different environments

**Comment by RomainMuller** [comment] 2020-05-12 13:07
> Hi @RomainMuller, Yes I know that after passing **table_stream_arn** kwarg to **Table.from_table_attributes** it works that is what I have also mentioned but I was requesting if we can get this value without passing it explicitly, because as a user I want to get all the attributes by just passing name of table and it helps in maintaining different environment with same code, passing table stream arn explicity is difficult and need hardcoding for different environments

The problem is that the stream ARNs include a UUID that cannot be computed from the table name. This means determining the stream ARN dynamically would require a context key lookup, which is currently unavailable. We could imagine bringing a `Table.from_lookup` method which would do this... The downsides is that it would be unable to "detect" that a stream has been re-created (the UUID in the stream ARN would have changed, but the cached context would not pick the new value up automatically).

**Comment by RomainMuller** [comment] 2020-08-13 12:50
The more I think about it the more I think this would be building a 🦶🏻🔫. I'll be closing this issue off as I don't think this is something we should be doing (for the reasons I mentioned in the previous update).

**Closed by RomainMuller** 2020-08-13 12:50 UTC
Labels: @aws-cdk/aws-dynamodb, effort/large, feature-request

**Comment by SchollSimon** [comment] 2022-05-25 06:43
I think i developed a solution for our application, where we faced the exact same issue due to integration of a multiregion stack architecture, where we only create our global dynamob tables in one main stack. 

For our application we created a helper method which creates or returns an existing table, also with stream configuration
```
export const createDataTable = (
  scope: Construct,
  props: TableProps,
  indexConfigs?: GlobalSecondaryIndexProps[]
): ITable => {
```

In the method we check the region of our scope, if it is the main region (us-east-1) we only create the database instance
```
if(Stack.of(scope).region === 'us-east-1'){
  const newTable = new Table(scope, props.tableName, {
    // props contains -> stream: StreamViewType.NEW_AND_OLD_IMAGES,
    ...props,
    replicationRegions: ['eu-central-1'],
  });

  if (ndexConfigs.length > 0) {
    indexConfigs.forEach((indexConfig) =>
      newTable.addGlobalSecondaryIndex(indexConfig)
  );
}
```
if we create the eu stack or any other regional stack we want to refer the replicated table and not create a new one. But due to the inssufficient support from cdk, we have to do an AWS SDK Call during deployment. We can use dynamoDbs **listStreams** operation for listing and reading all the available stream configurations for one table.
```
else {
  const awsSdkCall: AwsSdkCall = {
    service: 'DynamoDBStreams',
    action: 'listStreams',
    region: Stack.of(scope).region,
    physicalResourceId: PhysicalResourceId.of(`${props.tableName}ListStreams` ),
    parameters: {
      TableName: props.tableName,
    },
  };

  const call = new AwsCustomResource(scope,`${props.tableName}GetTableStreams`, {
      onCreate: awsSdkCall,
      onUpdate: awsSdkCall,
      logRetention: RetentionDays.ONE_DAY,
      policy: AwsCustomResourcePolicy.fromStatements([
        new PolicyStatement({
          actions: ['dynamodb:*'],
          resources: ['*'],
        }),
      ]),
    }
  );
  return Table.fromTableAttributes(scope, props.tableName, {
    tableName: props.tableName,
    tableStreamArn: call.getResponseField('Streams.0.StreamArn'),
  });
}
```

You can have a look at the doc strings how to access the sdk calls output. Obviously you need to know how many stream configurations where created in the first place. But like you see with a CustomResource it is possible to keep this approach dynamic.

Anyway in my opinion cdk should offer this possibility out of the box.

**Comment by windrpha** [comment] 2022-11-09 19:49
Add the following to your lambda defintion:

        const userTable = new dynamodb.Table(this, 'my-stack', {
            tableName: constants.DYNAMO_USER_TABLE,
            partitionKey: { name: 'user-id', type: dynamodb.AttributeType.STRING },
            billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
            tableClass: dynamodb.TableClass.STANDARD,
            **stream : dynamodb.StreamViewType.NEW_IMAGE**
          });

**Comment by SchollSimon** [comment] 2022-11-17 07:55
> Add the following to your lambda defintion:
> 
> stream : dynamodb.StreamViewType.NEW_IMAGE
> 
> ```
>     const userTable = new dynamodb.Table(this, 'my-stack', {
>         tableName: constants.DYNAMO_USER_TABLE,
>         partitionKey: { name: 'user-id', type: dynamodb.AttributeType.STRING },
>         billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
>         tableClass: dynamodb.TableClass.STANDARD,
>         **stream : dynamodb.StreamViewType.NEW_IMAGE**
>       });
> ```

Hi thank you for the response, a few things:
- How is your answer related to the topic of this issue?
- You said 'add to your lambda definition', but your post contains a cdk table object

**Comment by bpcrao** [comment] 2023-03-21 19:24
@SchollSimon 
🙇  you simply rock.
