### ISSUE TITLE
pipelines: Upgrade Default Build Image

### ISSUE THREAD

**Issue by gburke-ppb** [aws/aws-cdk#23617] opened 2023-01-09 13:47 UTC
### Describe the feature

Any chance we can get the default image for a Build Stage updated to standard:6.0 ?

        `buildImage: cb.LinuxBuildImage.STANDARD_5_0,`

https://github.com/aws/aws-cdk/blob/61e5495105e06aba4c027fb33ae031da09a3ff33/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L793

### Use Case

I'd prefer not to be hardcoding an image version into all of my CDK pipelines code, but the latest default version has been 5.0 for some time even though 6.0 is available for quite some time now.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.59.0

### Environment details (OS name and version, etc.)

All

**Comment by peterwoodworth** [comment] 2023-01-10 03:16
Thanks for the feature request!

I think we will want to keep this as `5_0` for now to prevent this update from breaking anyone's infrastructure. Perhaps this is something that could be hidden behind a feature flag, but since this is configurable through [props](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#codebuilddefaults) this might not be likely to happen soon without support

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://cdk.dev) to solicit support for reprioritization.

**Comment by coffee-squirrel** [comment] 2023-03-03 13:53
It seems `aws/codebuild/standard:5.0` (`cb.LinuxBuildImage.STANDARD_5_0`) is going into an unsupported state soon.  We've received the following from AWS:

> We are reaching out to you because you ran a build using the Ubuntu standard 5.0 [1] Docker Image, Amazon Linux 2 ARM standard 1.0 [2], or Amazon Linux 2 standard 3.0 [3] in the last 30 days. Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.
> 
> You may continue using these images for your builds, but you will notice an increase in provisioning latency after March 30, 2023.
> These images will also not be getting any new updates. We recommend updating your Build Projects to use the latest build images in order to get the latest language runtimes and tools. For more information on how to do this you can follow 'Docker images provided by CodeBuild' [4].

**Comment by mrrzest** [comment] 2023-03-08 14:50
Can a feature flag be introduced here so that this isn't marked as a breaking change? Similar to what's being suggested for this issue: https://github.com/aws/aws-cdk/issues/16707

Here's a issue that I think is a duplicate of this issue: https://github.com/aws/aws-cdk/issues/24487

**Comment by pahud** [comment] 2023-03-09 12:33
closing for https://github.com/aws/aws-cdk/pull/24544

**Closed by pahud** 2023-03-09 12:33 UTC
Labels: p1, feature-request, @aws-cdk/aws-codepipeline, effort/small, breaking-change
