### ISSUE TITLE
Support a custom aws (cloudformation) endpoint

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cdk#12494] opened 2021-01-13 20:42 UTC
Terraform supports specifying a list of custom endpoints to use (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#getting-started-with-custom-endpoints) instead of relying on region-defaults.

It would be good if cdk carried a similar way of specifying alternative endpoints for the services it uses. I'm guessing that most "write" operations happen via cloudformation, but the various lookup functions probably use service endpoints.

### Use Case
integration testing and mocking

### Proposed Solution
Maybe the `environment` dict which now consists of region and account number could be expanded with this info

### Other
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2021-01-18 13:31
Duplicate of #1989

**Closed by rix0rrr** 2021-01-18 13:31 UTC
Labels: feature-request, @aws-cdk/aws-cloudformation, needs-triage
