### ISSUE TITLE
@aws-cdk/aws-codepipeline-actions: change default branch name

### ISSUE THREAD

**Issue by fbouteruche** [aws/aws-cdk#15379] opened 2021-07-01 07:42 UTC
As default branch naming in AWS CodeCommit is now "main" and not "master" anymore, can we switch the default branch name in the CodePipeline Action for CodeCommit here https://github.com/aws/aws-cdk/blob/06619fe793ed60eb9894d9cdaefaa8900760d498/packages/%40aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts#L69

### Use Case

When I create an a CodeCommit Action without giving a name, I want the default branch name to be "main" to fit the default naming scheme of AWS CodeCommit.

### Proposed Solution

Change de the default name here https://github.com/aws/aws-cdk/blob/06619fe793ed60eb9894d9cdaefaa8900760d498/packages/%40aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts#L69

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by skinny85** [comment] 2021-07-01 14:40
Duplicate of https://github.com/aws/aws-cdk/issues/13335. Let's move the conversation there.

**Closed by skinny85** 2021-07-01 14:40 UTC
Labels: @aws-cdk/aws-codepipeline-actions, feature-request, needs-triage
