### ISSUE TITLE
Enabling Logging for Step Functions Express

### ISSUE THREAD

**Issue by TinBui-0127** [aws/aws-cdk#6268] opened 2020-02-13 15:27 UTC
Express Type Step Functions has been released for a couple months and has been working great so far. However, one of the key feature is Execution Logging to CloudWatch Logs, which is off by default and will need to turn on manually through the console or through AWS CLI. It would be nice if CDK can turn it on 

### Use Case

In the organization I am working on, I don't have access to the console and AWS CLI only available in sandbox, not non-prod and prod environment. As of now, every role creation, policy attachment required for logging on Express Step Functions can be done with CDK except enabling the logging feature. It would be really helpful if it can be done while deploying with CDK

**Comment by nija-at** [comment] 2020-02-19 16:15
Duplicate of https://github.com/aws/aws-cdk/issues/5754

**Closed by nija-at** 2020-02-19 16:15 UTC
Labels: feature-request, package/stepfunctions, status/needs-triage
