### ISSUE TITLE
SyntaxError: Unexpected token '?' on Amazon Linux 2 CodeBuild images (Node 14 required starting at 2.28.0)

### ISSUE THREAD

**Issue by wr-cdargis** [aws/aws-cdk#20739] opened 2022-06-14 19:59 UTC
### Describe the bug

Running command `cdk synth` with latest aws-cdk from npm produces an error.

### Expected Behavior

I made no changes to source. The install step installs the most recent `aws-cdk` and it seems this error came with the newest version.

### Current Behavior

```
[Container] 2022/06/14 18:50:24 Running command cdk synth
--
663 | /usr/local/lib/node_modules/aws-cdk/lib/index.js:12322
664 | return process.env.CDK_HOME ? path.resolve(process.env.CDK_HOME) : path.join((os.userInfo().homedir ?? os.homedir()).trim() \|\| "/", ".cdk");

SyntaxError: Unexpected token '?'
--
668 | at wrapSafe (internal/modules/cjs/loader.js:915:16)
669 | at Module._compile (internal/modules/cjs/loader.js:963:27)
670 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
671 | at Module.load (internal/modules/cjs/loader.js:863:32)
672 | at Function.Module._load (internal/modules/cjs/loader.js:708:14)
673 | at Module.require (internal/modules/cjs/loader.js:887:19)
674 | at require (internal/modules/cjs/helpers.js:74:18)
675 | at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/bin/cdk.js:3:15)
676 | at Module._compile (internal/modules/cjs/loader.js:999:30)
677 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

### Reproduction Steps

```
npm install -g aws-cdk
cdk synth
```

### Additional Information/Context

I was able to explicitly install version 2.27.0 to confirm this is an issue with 2.28.0 (but I still have this problem later in the self mutate phase where I can't control the version). This was all done on a .NET CDK app. My apologies for the lack of info I know you need more I am just trying to get some attention on this as soon as I can.

### CDK CLI Version

aws-cdk@2.28.0

### Node.js Version

12.22.12

### OS

Linux

### Language

.NET

**Comment by benton** [comment] 2022-06-14 20:39
I think this is because of the NodeJS version 12, as I can reproduce it with Node 12 but not with Node 16.

When using the CDK with Node 12, I get the warning:

    npm WARN notsup Unsupported engine for aws-cdk@2.28.0: wanted: {"node":">= 14.15.0"} (current: {"node":"12.22.2","npm":"6.14.13"})
    npm WARN notsup Not compatible with your version of node/npm: aws-cdk@2.28.0

The problem is that when deploying to production, the standard CDK Pipeline image (for ARM anyway) is outdated! The latest version of Node in the AmazonLinux2 package repo for ARM is still 12!  

Plus, even if you try to pin the version of the CDK in your build, the built-in `SelfMutate` / `UpdatePipeline` step still tries to run 

    npm install -g aws-cdk@2

which then prints the above warning, and proceeds to fail with the error cited in the original post for this issue.


    [Container] 2022/06/14 20:05:12  BUILD: 1 commands
    [Container] 2022/06/14 20:05:12 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
    [Container] 2022/06/14 20:05:12 Phase context status code:  Message: 
    [Container] 2022/06/14 20:05:12 Entering phase INSTALL
    [Container] 2022/06/14 20:05:12 Running command npm install -g aws-cdk@2
    /usr/local/bin/cdk -> /usr/local/lib/node_modules/aws-cdk/bin/cdk
    npm WARN notsup Unsupported engine for aws-cdk@2.28.0: wanted: 
    {
        "node": ">= 14.15.0"
    }
     (current: 
    {
        "node": "12.22.2",
        "npm": "6.14.13"
    }
    )    
    npm WARN notsup Not compatible with your version of node/npm: aws-cdk@2.28.0
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/aws-cdk/node_modules    /fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted 
    {
        "os": "darwin",
        "arch": "any"
    }
     (current: 
    {
        "os": "linux",
        "arch": "arm64"
    }
    )

    + aws-cdk@2.28.0
    added 1 package from 1 contributor in 2.327s

    [Container] 2022/06/14 20:05:22 Phase complete: INSTALL State: SUCCEEDED
    [Container] 2022/06/14 20:05:22 Phase context status code:  Message: 
    [Container] 2022/06/14 20:05:22 Entering phase PRE_BUILD
    [Container] 2022/06/14 20:05:22 Phase complete: PRE_BUILD State: SUCCEEDED
    [Container] 2022/06/14 20:05:22 Phase context status code:  Message: 
    [Container] 2022/06/14 20:05:23 Entering phase BUILD
    [Container] 2022/06/14 20:05:23 Running command cdk -a . deploy Pipeline --require-approval=never --verbose
    /usr/local/lib/node_modules/aws-cdk/lib/index.js:12322
      return process.env.CDK_HOME ? path.resolve(process.env.CDK_HOME) : path.join((os.userInfo().homedir ??         os.homedir()).trim() || "/", ".cdk");
                                                                                                       ^
    
    SyntaxError: Unexpected token '?'
        at wrapSafe (internal/modules/cjs/loader.js:915:16)
        at Module._compile (internal/modules/cjs/loader.js:963:27)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk/bin/cdk.js:3:15)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    [Container] 2022/06/14 20:05:23 Command did not exit successfully cdk -a . deploy Pipeline --require-    approval=never --verbose exit status 1
    [Container] 2022/06/14 20:05:23 Phase complete: BUILD State: FAILED

**Comment by wr-cdargis** [comment] 2022-06-14 20:48
> Im attempting to use the 'n' command as below: installCommands:[n 16.15.1'] However, this still only gets you up to the update-pipeline phase and that still errors out as you can't control the node version in that phase

Yeap that is where I'm at. I made it that far and that is when I opened the issue. I think it is possible to control the version from the `PartialBuildSpec` props of `SelfMutationCodeBuildDefaults`. I haven't tried that yet

**Comment by tmitchel2** [comment] 2022-06-14 20:56
Nope my prod CI CD is now toast.  As per bentons comment the self mutate phase seems to default to installing latest cdk only... perhaps there is a way to override that behavour but im not aware of it....

**Comment by wr-cdargis** [comment] 2022-06-14 20:59
@tmitchel2 not sure if there is anything we can do if its installing the cdk on its own? I did notice that the `CodePipelineProps` object has a `SelfMutationCodeBuildDefaults` with `PartialBuildSpec`. I haven't given that a shot yet. But the word `Partial` doesn't have me hopeful.

**Comment by tmitchel2** [comment] 2022-06-14 21:40
Next attempt from me at workaround is

```
const pipeline = new CodePipeline(this, 'AppPipeline', {
  pipelineName: 'AppPipeline',
  // selfMutation: false,
  selfMutationCodeBuildDefaults: {
      buildEnvironment: {
          buildImage: LinuxBuildImage.STANDARD_5_0,
      },
  },
  codeBuildDefaults: {
      buildEnvironment: {
          buildImage: LinuxArmBuildImage.AMAZON_LINUX_2_STANDARD_2_0
      },
```

**Comment by wr-cdargis** [comment] 2022-06-14 21:45
@tmitchel2 my thought was to use the partial build spec to uninstall 2.28.0 and then install 2.27.0 not sure if that is possible

**Comment by tmitchel2** [comment] 2022-06-14 21:53
@wr-cdargis yup im seeing about that also.... i think i've been mucking up my testing though as im not deploying from my local machine to update the pipeline as this is one of those chicken and egg cdk issues.

**Comment by djendrju87** [comment] 2022-06-14 21:54
What helped me is installing hardcoded version of cdk in buildspec file:
`npm install -g aws-cdk@1.160.0`
Of course you can use any other version (just not the latest one).

**Comment by benton** [comment] 2022-06-14 22:07
Disabling the self-mutation feature of the Pipeline, and then deploying the Pipeline manually, successfully gets past the (non-existent) mutation step.

But apparently the `cdk-assets` library is _also_ incompatible with Node 12, because the standard `Assets` Pipeline step then fails. 

    [Container] 2022/06/14 22:00:04 Entering phase BUILD
    --
    [Container] 2022/06/14 22:00:04 Running command cdk-assets --path "assembly-Pipeline-Prod/PipelineProdCompute0DF2D855.assets.json" --verbose publish "854cac76b0b0e907cc29a9d7f4fad799f29c830c30488e844e5e00329f2ddfc6:109193998902-us-east-2"
    /usr/local/lib/node_modules/cdk-assets/node_modules/@aws-cdk/cloud-assembly-schema/lib/manifest.js:160
    if (semver.gt(actual, maxSupported) && !options?.skipVersionCheck) {
    ^
     
    SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cdk-assets/node_modules/@aws-cdk/cloud-assembly-schema/lib/index.js:15:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
            
    [Container] 2022/06/14 22:00:04 Command did not exit successfully cdk-assets --path "assembly-Pipeline-Prod/PipelineProdCompute0DF2D855.assets.json" --verbose publish "854cac76b0b0e907cc29a9d7f4fad799f29c830c30488e844e5e00329f2ddfc6:109193998902-us-east-2" exit status 1


I see that the x86_64 images are also limited to Node 12. 
Does this mean that all standard CDK Pipelines are currently broken?

**Comment by tmitchel2** [comment] 2022-06-14 22:11
I think all but Ubuntu standard:5.0 would be broken? noice.

**Comment by tmitchel2** [comment] 2022-06-14 22:13
This works! :). needs a manual push...

```
        const pipeline = new CodePipeline(this, 'AppPipeline', {
            pipelineName: 'AppPipeline',
            selfMutationCodeBuildDefaults: {
                partialBuildSpec: BuildSpec.fromObject({
                    phases: {
                       install: {
                        commands: [
                            "n 16.15.1"
                        ]
                       }
                    }
                })
            },
            codeBuildDefaults: {
                buildEnvironment: {
                    buildImage: LinuxArmBuildImage.AMAZON_LINUX_2_STANDARD_2_0
                }
            },
```

**Comment by benton** [comment] 2022-06-14 22:15
Nice - I also see `asset_publishing_code_build_defaults`, so looks like we may be able to override the image for each step.

**Comment by tmitchel2** [comment] 2022-06-14 22:17
Yes i just saw that,,, im going to try moving it into codeBuildDefaults as i think that applies to all....

**Comment by wr-cdargis** [comment] 2022-06-14 22:27
Pinning with `CodeBuildDefaults` worked for me!

**Comment by tmitchel2** [comment] 2022-06-14 22:28
How do you pin?

**Comment by wr-cdargis** [comment] 2022-06-14 22:33
I moved your partial build spec to CodeBuildDefaults

**Comment by tmitchel2** [comment] 2022-06-14 22:34
Ah ok i thought you managed to pin the version of cdk... my move to codeBuildDefaults didnt work for assets so im just splatter gunning that partialBuildSpec into codeBuildDefaults, selfMutationCodeBuildDefaults and assetPublishingCodeBuildDefaults.  Hopefully thats the end of it.

**Comment by rowilken** [comment] 2022-06-16 07:48
@tmitchel2 
I tried to adapt your workaround since we are using CdkPipeline instead of CodePipeline in out stack but it seems I can only set the buildImage there but not the partialBuildSpec:

`const pipeline = new pipelines.CdkPipeline(this, 'Pipeline', {
  synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
    environment: {
      buildImage: codebuild.LinuxBuildImage.STANDARD_5_0,
      computeType: codebuild.ComputeType.LARGE,
    },
  }),
});`

Any ideas how to get the workaround you proposed working with CdkPipeline as well?

**Comment by tmitchel2** [comment] 2022-06-16 08:32
I guess the 'workaround' is to upgrade to latest cdk?

**Comment by tmitchel2** [comment] 2022-06-16 10:10
I presumed you were using an old version because CdkPipeline is old and deprecated now.  You just need to change you code to start using CodePipeline instead.

**Comment by rowilken** [comment] 2022-06-16 10:14
OK, got your idea: 
1. Migrate to the new API
2. Applying the fix you proposed for CodePipeline
3. Hopping for AWS to supply a fixed image in the near future and remove the workaround after that

**Comment by jwoehrle** [comment] 2022-06-20 00:37
what worked for me is pinning the CDK version from the Pipeline construct. 
```

const pipeline = new CodePipeline(this, 'Pipeline', {
            ...
            cliVersion: '2.27.0',
            ...
```

then I did a manual `npx cdk deploy MyPipelineStack` from my machine (node 16.15.0). After that the CodePipeline works again

**Comment by CodeWithOz** [comment] 2022-06-22 11:51
@tmitchel2 please is there any possible way of achieving this using the `CdkPipeline` API? I'm working with another person's code and this is not my skillset so for me to try to do the migration for our production system is not realistic right now. I've tried using [`assetBuildSpec`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CdkPipeline.html#assetbuildspecspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) and [`selfMutationBuildSpec`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CdkPipeline.html#selfmutationbuildspecspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) from `CdkPipeline` as follows:
```javascript
        selfMutating: true,
        selfMutationBuildSpec: BuildSpec.fromObject({
            version: '0.2',
            phases: {
                install: {
                    // forcefully install node 14 because it's required by the latest version of cdk-assets (2.28.1)
                    // see here https://github.com/aws/aws-cdk/issues/20739#issuecomment-1155762629
                    commands: ['n 14.19.1'],
                },
            },
        }),
```

```javascript
        assetBuildSpec: BuildSpec.fromObject({
            version: '0.2',
            phases: {
                install: {
                    // forcefully install node 14 because it's required by the latest version of cdk-assets (2.28.1)
                    // see here https://github.com/aws/aws-cdk/issues/20739#issuecomment-1155762629
                    commands: ['n 14.19.1'],
                },
            },
        }),
```

But it didn't work in either scenario. My `PipelineProject` uses `LinuxBuildImage.STANDARD_5_0` as the `buildImage`. Any additional guidance you can provide please?

**Comment by rix0rrr** [comment] 2022-06-23 08:14
The issue is about the CodeBuild image.

Any CDK Pipeline created with a version of `v1.101` or higher (or `v2`) will not be affected, as it will be using the CodeBuild `standard:5.0` image[1] which contains Node14.

AL2-based images do not have Node14 yet, work is in progress on that.

[1] https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Comment by CodeWithOz** [comment] 2022-06-23 08:35
@MrArnoldPalmer thanks I'm looking forward to that. Is there any ETA you can give?

@rix0rrr I'm using `"@aws-cdk/pipelines": "^1.108.1"` and as I mentioned earlier my build image is standard 5, but I still get the problem.

**Comment by indrora** [comment] 2022-06-23 11:44
A short term workaround is to use nvm or the `n` script (included in the AL2 images) to choose the version of Node to run. 

This has been discussed here: https://github.com/aws/aws-codebuild-docker-images/issues/490

**Comment by iselcuk** [comment] 2022-06-23 13:26
I set the codeBuildDefaults for the following pipeline as suggested in [@tmitchel2's workaround](https://github.com/aws/aws-cdk/issues/20739#issuecomment-1155775163) :

    const pipeline = new CodePipeline(this, "MyPipeline", {
      pipelineName: `MyPipeline-${stageName}-${deploymentEnv.region}`,
      crossAccountKeys: true,
      synth: new ShellStep("Synth", {
        input: CodePipelineSource.connection(repoString, branchName, {
          connectionArn,
        }),
        installCommands: ["n 14.19.0"],
        commands: ["npm ci", "npm run build", "npx cdk synth"],
      }),
      cliVersion: "2.28.1",
      codeBuildDefaults: {
        buildEnvironment: {
          buildImage: LinuxArmBuildImage.AMAZON_LINUX_2_STANDARD_2_0,
        },
        partialBuildSpec: BuildSpec.fromObject({
          phases: {
            install: {
              commands: ["n 14.19.0"],
            },
          },
        }),
      },
    });

    const applicationStage = new AppStage(this, "DeployStage", {
      env: deploymentEnv,
      stageName,
      version,
    });

    const securityChangesTopic = new sns.Topic(
      this,
      "SecurityChangesTopic",
      {
        displayName: "SecurityChangesTopic",
      }
    );

    const additionalSteps: Array<Step> = [
      new ConfirmPermissionsBroadening("SecurityCheck", {
        stage: applicationStage,
        notificationTopic: securityChangesTopic,
      }),
    ];

    if (isPreApprovalNeeded) {
      additionalSteps.push(
        new ManualApprovalStep("PreApproval", {
          comment: "Test comment for preApproval step",
        })
      );
    }

    pipeline.addStage(applicationStage, {
      pre: additionalSteps,
    });



It gets applied on synth, self mutation, and asset publishing. However, "ConfirmPermissionsBroadening" step  does not respect the codeBuildDefaults. 


In the code below, is the "codeBuildDefaults" being ignored when it is a step? If so, is this the expected behaviour?

https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L728-L762


https://github.com/aws/aws-cdk/blob/cea1039e3664fdfa89c6f00cdaeb1a0185a12678/packages/%40aws-cdk/pipelines/lib/codepipeline/private/codebuild-factory.ts#L416-L435

**Comment by MrArnoldPalmer** [comment] 2022-06-24 22:55
For those using `CdkPipeline`, you can set the [`cdkCliVersion`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CdkPipeline.html#cdkcliversionspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) on the pipeline props, which also applies it to the [`UpdatePipeline`](https://github.com/aws/aws-cdk/blob/fedd51b045cb312e7259d1d20fc119c086d7d31f/packages/%40aws-cdk/pipelines/lib/legacy/pipeline.ts#L289) step. If you're using a 1.x version of the cdk with `CdkPipelines` api on codebuild AL2 images, you can use this to use an older version of the cdk cli that supports Node 12 (<=1.159.0 or earlier matching the framework version you're using).

For v2 users on AL2, add a step to your buildspec to install nodejs 14 or later using nvm as detailed above for synth steps and self-mutation steps as needed.

We are currently releasing a fix to the `ConfirmPermissionsBroadening` step to correctly use ubuntu standard 5 so keep an eye out for that. https://github.com/aws/aws-cdk/pull/20864/commits/47b5ca06c50a566af8d1fed4202164b85f793d18

**Comment by nuhasha** [comment] 2022-07-05 20:50
the issue solved for me, when I upgraded to the latest version of AWS CDK
```
npm install
npm update -g aws-cdk
```
after upgrading I got this error: 
`npm WARN notsup Unsupported engine for aws-cdk@1.162.0: wanted: {"node":">= 14.15.0"} (current: {"node":"12.22.12","npm":"6.14.16"}) npm WARN notsup Not compatible with your version of node/npm: aws-cdk@1.162.0`
So, I installed the latest version of Node.js [node-v14.19.3]

**Comment by ashishchandr70** [comment] 2022-07-05 23:26
> For those using `CdkPipeline`, you can set the [`cdkCliVersion`](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.CdkPipeline.html#cdkcliversionspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) on the pipeline props, which also applies it to the [`UpdatePipeline`](https://github.com/aws/aws-cdk/blob/fedd51b045cb312e7259d1d20fc119c086d7d31f/packages/%40aws-cdk/pipelines/lib/legacy/pipeline.ts#L289) step. If you're using a 1.x version of the cdk with `CdkPipelines` api on codebuild AL2 images, you can use this to use an older version of the cdk cli that supports Node 12 (<=1.159.0 or earlier matching the framework version you're using).
> 
> For v2 users on AL2, add a step to your buildspec to install nodejs 14 or later using nvm as detailed above for synth steps and self-mutation steps as needed.
> 
> We are currently releasing a fix to the `ConfirmPermissionsBroadening` step to correctly use ubuntu standard 5 so keep an eye out for that. [47b5ca0](https://github.com/aws/aws-cdk/commit/47b5ca06c50a566af8d1fed4202164b85f793d18)

I tried it with this code snippet but it fails in the NPM Build stage on the second pass (after NPM_Build runs and succeeds, UpdatePipeline runs and succeeds and the NPM_Build runs again and fails).

Our node version is 14.x

```
const pipeline = new CdkPipeline(this, 'CiCd', {
            pipelineName: `CiCd-${this.namespace}`,
            cloudAssemblyArtifact,
            sourceAction: new codepipelineActions.CodeStarConnectionsSourceAction({
                actionName: "GitHub",
                output: sourceArtifact,                
                connectionArn: "arn:aws:codestar-connections:us-east-xxxx",
                owner: "Owner-Name",
                repo: "Repo-Name",
                branch: this.branch
            }),
            synthAction: SimpleSynthAction.standardNpmSynth({
                actionName: `NPM_Build`,
                sourceArtifact,
                cloudAssemblyArtifact,
                installCommand: `npm run bootstrap`,
                buildCommand: `npx cross-env NODE_ENV=${this.namespace} npm run build`
            }),
            cdkCliVersion: "1.100.0"    // this is an workaround suggested by AWS CDK team per https://github.com/aws/aws-cdk/issues/20739#issuecomment-1166052414
        });
```

**Comment by MrArnoldPalmer** [comment] 2022-07-06 22:46
@ashishchandr70 sorry it's unclear at what phase your pipeline is failing? Also are you running on an AL2 image?

**Comment by CodeWithOz** [comment] 2022-07-08 14:47
@MrArnoldPalmer I tried setting the `cdkCliVersion` to the version you mentioned but it didn't make a difference. This is the config I have as my pipeline config:
```javascript
    const sourceArtifact = new Artifact()
    const buildArtifact = new Artifact()
    const project = new PipelineProject(stack, `BuildImageProject`, {
      environment: {
        buildImage: LinuxBuildImage.STANDARD_5_0,
        privileged: true,
      },
      buildSpec: BuildSpec.fromObject({
        version: "0.2",
        phases: {
          pre_build: {
            commands: [
              "echo Logging in to Amazon ECR...",
              "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username $USERNAME --password-stdin $REPOSITORY_URI",
              'TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"',
              'IMAGE_URI="${REPOSITORY_URI}"',
              'IMAGE_URI_TAGGED="${REPOSITORY_URI}:${TAG}"',
              'IMAGE_URI_LATEST="${REPOSITORY_URI}:latest"',
              'CONTAINER_NAME="${APP_NAME}"',
            ],
          },
          build: {
            commands: ['docker build -t "$IMAGE_URI_TAGGED" -t "$IMAGE_URI_LATEST" .'],
          },
          post_build: {
            commands: [
              'docker push "$IMAGE_URI"',
              `printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$IMAGE_URI_LATEST" > ${imageFileName}`,
            ],
          },
        },
        artifacts: {
          files: [imageFileName],
        },
      }),
    })

    const buildActionConfig = new CodeBuildAction({
      actionName: `BuildImage`,
      project: project,
      input: sourceArtifact,
      checkSecretsInPlainTextEnvVariables: true,
      environmentVariables: {
        AWS_DEFAULT_REGION: {
          type: BuildEnvironmentVariableType.PLAINTEXT,
          value: stack.region,
        },
        REPOSITORY_URI: {
          type: BuildEnvironmentVariableType.PLAINTEXT,
          value: this.ecrRepository.repositoryUri,
        },
        APP_NAME: {
          type: BuildEnvironmentVariableType.PLAINTEXT,
          value: serviceName,
        },
      },
      outputs: [buildArtifact],
      type: CodeBuildActionType.BUILD,
    })

/* --- the pipeline config --- */
{
        pipelineName: `${serviceName}-Pipeline`,
        selfMutating: false,
        crossAccountKeys: false,
        cloudAssemblyArtifact: buildArtifact,
        sourceAction: new GitHubV2SourceAction({
          actionName: "GitHub",
          owner: owner,
          repo: repo,
          oauthToken: SecretValue.secretsManager(...),
          output: sourceArtifact,
          branch: branch,
          filters: filters ? filters : defaultFilters,
        }),
        synthAction: buildActionConfig,
        cdkCliVersion: '1.159.0',
}
```

Does that give an idea what could be wrong? Please let me know if there's more info I can provide.

**Comment by CodeWithOz** [comment] 2022-07-08 14:53
Is it possible that my old config is getting cached somewhere and that cache is not being invalidated when I create a new build? I'm looking at the build details for the failed and I can see that the build spec and environment don't actually correspond to what's in my code. Any ideas how I can investigate this? Please bear with me I'm filling in for someone else and this is not my area of expertise.

**Comment by vdanniel** [comment] 2022-07-12 00:51
This breaking a few related projects like the Simple Forecast Solution. For now we are fixing the version to the pervious version or cdk2.28.

**Comment by MrArnoldPalmer** [comment] 2022-07-13 23:15
So [here](https://github.com/aws/aws-cdk/blob/v1.100.0/packages/%40aws-cdk/pipelines/lib/actions/update-pipeline-action.ts#L66) that the `UpdatePipeline` action buildspec is installing npm cdk with the `installVersion` suffix appended to it which is passed [from the `CdkPipeline` props](https://github.com/aws/aws-cdk/blob/v1.100.0/packages/%40aws-cdk/pipelines/lib/actions/update-pipeline-action.ts#L66)


<details>
  <summary>When creating a minimal pipeline stack like so:</summary>
  
```ts
export class Issue20739Stack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const sourceArtifact = new codepipeline.Artifact();
    const cloudAssemblyArtifact = new codepipeline.Artifact();
    const sourceAction = new codepipelineActions.GitHubSourceAction({
      actionName: 'Source',
      output: sourceArtifact,
      owner: 'mrarnoldpalmer',
      repo: 'my-repo',
      oauthToken: cdk.SecretValue.secretsManager('mygithubtoken'),
    });

    new pipelines.CdkPipeline(this, 'Pipeline', {
      cdkCliVersion: '1.100.0',
      cloudAssemblyArtifact,
      sourceAction,
      synthAction: pipelines.SimpleSynthAction.standardNpmSynth({
        sourceArtifact,
        cloudAssemblyArtifact,
        environment: {
          privileged: true,
        },
      }),
    });
  }
}
```
</details>

The output template shows the buildspec output for the UpdatePipeline step to be
```
          "BuildSpec": "{\n  \"version\": \"0.2\",\n  \"phases\": {\n    \"install\": {\n      \"commands\": \"npm install -g aws-cdk@1.100.0\"\n    },\n    \"build\": {\n      \"commands\": [\n        \"cdk -a . deploy Issue20739Stack --require-approval=never --verbose\"\n      ]\n    }\n  }\n}",
          "Type": "CODEPIPELINE"
        },
```

And without the `1.100.0` suffix when removing the `cdkCliVersion` prop.

Did you manually deploy the pipeline stack from your machine (or another that has Node 14 +) after making the change?

**Comment by MrArnoldPalmer** [comment] 2022-07-14 21:46
@ashishchandr70 all of the above posted fixes require a manual deploy as self-update can't run synth successfully to make the changes to the code to change the cdk cli version or update the containers to standard:5.0, after that deploy it will be able to self-update as usual again.

Closing this out as codebuild has made [AL2:4.0](https://github.com/aws/aws-codebuild-docker-images/tree/master/al2/x86_64/standard/4.0) which has NodeJS 16 as standard, so users wanting to continue to use AL2 with the latest CDK CLI should be able to. If you get stuck with this error in self-update, update your codebuild images and run a deploy of the pipeline stack to get the updates.

**Closed by MrArnoldPalmer** 2022-07-14 21:46 UTC
Labels: bug, package/tools

**Comment by tmitchel2** [comment] 2023-03-21 10:02
@MrArnoldPalmer AL2_4 is only x86 and not arm so ideally shouldn't be fully closed out.

**Comment by tmitchel2** [comment] 2023-03-21 18:01
My workaround as per [above](https://github.com/aws/aws-cdk/issues/20739#issuecomment-1155762629) works for me and is fine enough as a workaround, however, I just wanted to make it clear that the Arm images are getting left behind a bit and I guess still need to be addressed.
