### ISSUE TITLE
CustomResource blocks stack creation

### ISSUE THREAD

**Issue by BerndWessels** [aws/aws-cdk#2126] opened 2019-04-01 01:41 UTC
I try to add a `CustomResource` to my CDK stack, but this then blocks the stack creation and I have to wait **2 hours** before I can give it another try.

Does `CustomResource` actually work with the CDK?

Is there a way to make CloudFormation to fail and complete faster (**2 hours wait seems ridiculous**) ?

```
31 Mar 2019 23:02:53	SingletonLambdaf7d4f7304ee111e89c2dfa7ae01bbebc492C6E5C	DELETE_IN_PROGRESS	-
31 Mar 2019 23:02:48	GetDBClusterResourceIdGetDBClusterResourceIdResourceE48281BE	DELETE_FAILED	Custom Resource failed to stabilize in expected time
31 Mar 2019 22:02:33	GetDBClusterResourceIdGetDBClusterResourceIdResourceE48281BE	DELETE_IN_PROGRESS	-
31 Mar 2019 22:02:31	CdkTrialStack	UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS	-
31 Mar 2019 22:02:29	CDKMetadata	UPDATE_COMPLETE	-
31 Mar 2019 22:02:27	CDKMetadata	UPDATE_IN_PROGRESS	-
31 Mar 2019 22:02:02	CdkTrialStack	UPDATE_ROLLBACK_IN_PROGRESS	The following resource(s) failed to create: [GetDBClusterResourceIdGetDBClusterResourceIdResourceE48281BE].
31 Mar 2019 22:01:58	GetDBClusterResourceIdGetDBClusterResourceIdResourceE48281BE	CREATE_FAILED	Custom Resource failed to stabilize in expected time
31 Mar 2019 21:01:35	GetDBClusterResourceIdGetDBClusterResourceIdResourceE48281BE	CREATE_IN_PROGRESS	-
31 Mar 2019 21:01:31	SingletonLambdaf7d4f7304ee111e89c2dfa7ae01bbebc492C6E5C	CREATE_COMPLETE	-
31 Mar 2019 21:01:31	SingletonLambdaf7d4f7304ee111e89c2dfa7ae01bbebc492C6E5C	CREATE_IN_PROGRESS	Resource creation Initiated
31 Mar 2019 21:01:29	SingletonLambdaf7d4f7304ee111e89c2dfa7ae01bbebc492C6E5C	CREATE_IN_PROGRESS	-
```

stack.ts
```typescript
        ...

        const getDBClusterResourceId = new GetDBClusterResourceId(this, "GetDBClusterResourceId", {
            dbClusterIdentifier: cluster.dbClusterName,
        });

        ...
```

get-db-cluster-resource-id.ts
``` typescript
import * as path from 'path';
import {Construct} from "@aws-cdk/cdk";
import {CustomResource} from "@aws-cdk/aws-cloudformation";
import {AssetCode, Runtime, SingletonFunction} from "@aws-cdk/aws-lambda";
import {PolicyStatement, Role, ServicePrincipal} from "@aws-cdk/aws-iam";

export interface GetDBClusterResourceIdProps {
    dbClusterIdentifier: string;
}

export class GetDBClusterResourceId extends Construct {
    public readonly response: string;

    constructor(scope: Construct, id: string, props: GetDBClusterResourceIdProps) {
        super(scope, id);

        const role = new Role(this, `${id}_Role`, {
            assumedBy: new ServicePrincipal('lambda.amazonaws.com'),
        });
        role.addToPolicy(new PolicyStatement()
            .addActions('logs:CreateLogGroup',
                'logs:CreateLogStream',
                'logs:PutLogEvents')
            .addResource('arn:aws:logs:*:*:*')
        );
        role.addToPolicy(new PolicyStatement()
            .addAction('rds:DescribeDBClusters')
            .addResources('*')
        );

        const resource = new CustomResource(this, `${id}_Resource`, {
            lambdaProvider: new SingletonFunction(this, 'Singleton', {
                uuid: 'f7d4f730-4ee1-11e8-9c2d-fa7ae01bbebc',
                code: new AssetCode(path.resolve(__dirname, '../functions/get-db-cluster-resource-id/')),
                handler: 'index.handler',
                timeout: 300,
                runtime: Runtime.NodeJS810,
                role: role
            }),
            properties: {
                dbClusterIdentifier: props.dbClusterIdentifier
            }
        });

        resource.node.addDependency(role);
        
        this.response = resource.getAtt('Response').toString();
    }
}
```

index.js
```js
const AWS = require("aws-sdk");
const response = require('cfn-response');

exports.handler = async (event, context) => {

    try {
        const rds = new AWS.RDS();
        const result = await rds.describeDBClusters({DBClusterIdentifier: 'cdktrialstack-dbcluster-52ss8pozlj2o',}).promise();
        response.send(event, context, response.SUCCESS, {
            'Response': result.DBClusters[0].DbClusterResourceId
        });
    } catch (ex) {
        response.send(event, context, response.FAILED, {
            'Error': JSON.stringify(ex)
        });
    }
};
```

The lambda gets created and executed just fine looking at the CloudWatch logs
```
2019-03-31T21:01:38.857Z 8ea898d5-61da-4112-8ebb-e1334020dab8 Response body:
{
    "Status": "SUCCESS",
    "Reason": "See the details in CloudWatch Log Stream: 2019/03/31/[$LATEST]ea6ad670906341b5a985d93ff973ba01",
    "PhysicalResourceId": "2019/03/31/[$LATEST]ea6ad670906341b5a985d93ff973ba01",
    "StackId": "arn:aws:cloudformation:us-east-1:238541850529:stack/CdkTrialStack/d1d78ac0-50d9-11e9-abac-0e1ffe4de6a4",
    "RequestId": "9c0fd97c-8539-4428-b3b8-0e31aab7b12c",
    "LogicalResourceId": "GetDBClusterResourceIdGetDBClusterResourceIdResourceE48281BE",
    "Data": {
        "Response": "cluster-BKNCIYYFFR4G46T4N2L777ZKRQ"
    }
}
```

But its stuck :( Without the `CustomResource` the stack works just fine.

**Comment by sam-goodwin** [comment] 2019-04-11 18:40
Yes, custom resources do work with the CDK. Have you tried https://www.npmjs.com/package/cfn-response-promise? I'm wondering if it's a problem with async/await.

**Comment by moravcik** [comment] 2019-07-02 00:42
Yes, I have working custom resource with the CDK. However, I had to setup proper sending of response status, and I have implemented simple timeout handler:

    import { request } from 'https';
    import { parse } from 'url';
    import Timer = NodeJS.Timer;    
    
    export const handler = (event, context, callback) => {
      
      let timer: Timer | undefined = setupTimer();
      
      if (event.RequestType === 'Create') {
        // do something on custom resource create
        send('SUCCESS', { Message: 'Resource creation successful!' });
        send('FAILED', { Message: '' + err }); // when something goes wrong
    
      } else if (event.RequestType === 'Update') {
        // do something on custom resource update
        send('SUCCESS', { Message: 'Resource update successful!' });
        send('FAILED', { Message: '' + err }); // when something goes wrong
    
      } else if (event.RequestType === 'Delete') {
        // do something on custom resource update
        send('SUCCESS', { Message: 'Resource deletion successful!' });  
    
      } else {
        send('FAILED');
      }
        
      function setupTimer() {
        const timeoutHandler = () => {
          new Promise(() => send('FAILED')).then(() => callback(new Error('Function timed out')));
        };
        return setTimeout(timeoutHandler, context.getRemainingTimeInMillis() - 1000);
      }
      
      // Send response to the pre-signed S3 URL
      function send(responseStatus, responseData?) {
        const responseBody = JSON.stringify({
          Status: responseStatus,
          Reason: 'See the details in CloudWatch Log Stream: ' + context.logStreamName,
          PhysicalResourceId: context.logStreamName,
          StackId: event.StackId,
          RequestId: event.RequestId,
          LogicalResourceId: event.LogicalResourceId,
          Data: responseData
        });
        
        const parsedUrl = parse(event.ResponseURL);
        
        const options = {
          hostname: parsedUrl.hostname,
          port: 443,
          path: parsedUrl.path,
          method: 'PUT',
          headers: {
    	    'content-type': '',
    	    'content-length': responseBody.length
          }
        };
        
        const req = request(options, response => {
          context.done(); // mark as done
        });
        
        req.on('error', error => {
          console.log('sendResponse Error:' + error);
          context.done(); // mark as done
        });
        
        req.write(responseBody);
        req.end();
        
        if (timer) {
          clearTimeout(timer);
          timer = undefined;
        }
      }  
    };

**Comment by SomayaB** [comment] 2019-09-17 18:28
Closing this issue since it's a duplicate of [#3778](https://github.com/aws/aws-cdk/issues/3778)

**Closed by SomayaB** 2019-09-17 18:28 UTC
Labels: duplicate, package/cdk-core, status/needs-triage

**Comment by schmalzs** [comment] 2020-04-30 16:57
I hit this issue as well. I don't believe the root cause was the same as #3778.

I was using `async/await` on the root handler function for the custom resource lambda. When I switched it to use a more traditional `.then(...)` promise, it started working.

I'm not sure why that made a difference. I am still using `async/await` on other functions outside of the root handler and it's still working fine.
