### ISSUE TITLE
(aws-eks): cdk-v2 Support bottlerocket select instanceTypes

### ISSUE THREAD

**Issue by allen-bmf** [aws/aws-cdk#17685] opened 2021-11-24 12:21 UTC
### What is the problem?

Deploy ❌ 
```
        eksCluster.addNodegroupCapacity('BottlerocketNG', {
            minSize: 4,
            desiredSize: 4,
            maxSize: 4,
            diskSize: 200,
            instanceTypes: [new aws_ec2.InstanceType('t3.xlarge')], // select type
            amiType: eks.NodegroupAmiType.BOTTLEROCKET_X86_64,
        });
``






### Reproduction Steps

Deploy ⭕ 
```
        eksCluster.addNodegroupCapacity('BottlerocketNG', {
            minSize: 4,
            desiredSize: 4,
            maxSize: 4,
            diskSize: 200,
            amiType: eks.NodegroupAmiType.BOTTLEROCKET_X86_64,
        });
```

### What did you expect to happen?

`
```console
The specified AMI does not match the instance types architecture, either specify AL2_x86_64 or dont specify any
```

### What actually happened?

cdk deploy

### CDK CLI Version

cdk version "aws-cdk-lib": "^2.0.0-rc.31",

### Node.js Version

v14.17.3

### OS

mac

### Language

Typescript

### Language Version

ts

**Comment by otaviomacedo** [comment] 2021-11-24 15:06
Closing as a duplicate of https://github.com/aws/aws-cdk/issues/17641

**Closed by otaviomacedo** 2021-11-24 15:06 UTC
Labels: bug, @aws-cdk/aws-eks, needs-triage
