### ISSUE TITLE
Cannot look up an existing CloudFrontWebDistribution from its attributes.

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#6805] opened 2020-03-19 03:25 UTC
Many CDK constructs provide a way to find an existing resource through some type of static methods, e.g., using ARN or other attributes. `CloudFrontWebDistribution` does not provide such a method.

In order to be able to create an Alias record on Route53 with a CloudFront target, one needs a way to look up existing CloudFront distribution. Currently, there doesn't seem to be a way to be able to do that.

### Reproduction Steps

1. Create a public hosted zone on Route53.
1. Try to add an `ARecord` targeting an existing cloud front distribution.
1. The `ARecord` constructor requires `target` field of type `RecordTarget`.
1. The `RecordTarget` constructor takes a field, `aliasTarget`, of type `IAliasRecordTarget`.
1. The constructor of `CloudFrontTarget`, which implements `IAliasRecordTarget`, requires an argument of type, `CloudFrontWebDistribution`.
1. Currently, it's not possible to find an existing `CloudFrontWebDistribution`.
 
### Error Log

N/A

### Environment

  - **CLI Version - 1.30.0 (build 4f54ff7)     :**
  - **Framework Version: 1.30.0 ;**
  - **OS               Ubuntu 18:**
  - **Language         Typescript:**

### Other

This is needed, among other things, to support naked domains (zone apex record) pointing to an existing CloudFront distribution. 

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2020-03-22 11:57
Hi @realharry - Thanks for the report!

This is definitely a valid use case. I'm marking this as a feature request, among many [others](https://github.com/aws/aws-cdk/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+label%3Apackage%2Fcloudfront) we have. Ramping up this module is on our plate so stay tuned :)

You can keep track of our work for this module in the [CloudFront Tracking Issue](https://github.com/aws/aws-cdk/issues/6490).

Thanks!

**Comment by iliapolo** [comment] 2020-04-13 18:51
This is actually a duplicate of https://github.com/aws/aws-cdk/issues/5607. 

Closing

**Closed by iliapolo** 2020-04-13 18:51 UTC
Labels: effort/medium, feature-request, needs-triage, package/cloudfront
