### ISSUE TITLE
Can't override ~/.aws/config

### ISSUE THREAD

**Issue by kuridaik** [aws/aws-cdk#12879] opened 2021-02-05 04:49 UTC
### The Question
When I try to create a WAF IP Set with `scope: CLOUDFRONT` from `ap-northeast-1`, the following error occurs

```
Error reason: The scope is not valid., field: SCOPE_VALUE, parameter: CLOUDFRONT (Service: Wafv2, Status Code: 400, Request ID: 847b1ca1-8fb4-48a2-a717-48faf6ea75d2, Extended Request I
D: null)
```

This seems to be because `CLOUDFRONT` WAF can only be deployed from` us-east-1`. However, I want to create my other resources in `ap-northeast-1`, so I cut out just the WAF Stack and specified that only the deployment of the WafStack should be done in `us-east-1`.

```ts
const waf = new WafStack(app, 'WAFv2-IP-Restriction', {
  env: {
    region: 'us-east-1'
  }
})

new AnyStack(app, 'AnyStack', {
  webAcl: waf.webAcl
})
```

However, when I deploy it, I get the same error. It seems that cdk prioritizes the `~/.aws/config` over the region specification hard-coded in the definition file.

```bash
$ ./node_modules/.bin/cdk deploy --all
...
Error reason: The scope is not valid., field: SCOPE_VALUE, parameter: CLOUDFRONT (Service: Wafv2, Status Code: 400...

$ cat ~/.aws/config
[default]
region = ap-northeast-1
output = json
```

Implicit environment specification using ~/.aws/config is not recommended for production environments, but is useful for development. However, if it cannot be hard-coded and overridden, I feel that this feature is confusing.

Is there a good way to implicitly specify a default region and deploy only part of the stack to any given region? I would like to avoid the method of removing ~/.aws/config and using my own environment variables such as CDK_DEFAULT_REGION.

### Environment

  - **CDK CLI Version:** 1.88.0
  - **Module Version:** 1.88.0
  - **Node.js Version:** v14.15.1
  - **OS:** macOS Mojave
  - **Language (Version):** TypeScript

### Other information

By using wafv1 (AWS WAF Classic, `@aws-cdk/aws-waf`), I was able to avoid the core problem (which can only be deployed from `us-east-1`). But I don't want to use WAF Classic.

**Comment by peterwoodworth** [comment] 2021-06-25 20:53
Sorry for the late reply here @kuridaik,

I can't seem to reproduce this. My default region is `us-west-2`, and I've built this simple stack:

```ts
export class ProviderStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    new wafv2.CfnIPSet(this, 'IpSet', {
      ipAddressVersion: "IPV4",
      addresses: ['10.0.0.1/32'],
      scope: "CLOUDFRONT"
    })
  }
}
```
My entrypoint file looks like this:
```ts
const app = new cdk.App();
new ProviderStack(app, 'ProviderStack', { env: { region: 'us-east-1' } });
new ProviderStack(app, 'ProviderStack2')
```
On `cdk deploy --all` my first stack will deploy successfully and my second stack will get the same error you're currently getting. I'm not sure why setting the environment isn't working for you, can you share the rest of your entrypoint file?

**Comment by peterwoodworth** [comment] 2021-07-07 23:59
I'll be closing this issue now. If you're still having trouble with this ping me and I can work through this with ya!

**Closed by peterwoodworth** 2021-07-07 23:59 UTC
Labels: guidance, response-requested

**Comment by mathieudevos** [comment] 2021-11-12 12:40
Is there a way to create a construct with just the wafv2 resource of the cloudfront CfnWebAcl in that specific region or is this issue of CfnWebAcl only circumvented by using nested stacks? 

So far I've been able to generate just 1 stack with a set of constructs for each major grouping of resources, and even certificates can be specified to be specifically created in a region even though the stack itself is in a different region.
