### ISSUE TITLE
Cognito User Pool - "Email Delivery through Amazon SES"

### ISSUE THREAD

**Issue by realharry** [aws/aws-cdk#7309] opened 2020-04-10 21:12 UTC
Cognito User Pool currently has an option called "Email Delivery through Amazon SES". I couldn't find any corresponding attribute in CDK: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.UserPool.html

### Use Case

Currently, the `UserPool` construct is marked as experimental API (presumably, subject to change). But, most of the functionalities are already there. One of the missing features seems to be an attribute to be able to use AWS SES for email invitation/verification. This is somewhat related to https://github.com/aws/aws-cdk/issues/7235, but unlike #7235, this option "Email Delivery through Amazon SES" can be changed after a userpool is created, and hence I would think this feature request could be a low priority (at least, lower than #7235). Still, it would be nice to be able to automate every step without having to go to the console.
 
### Proposed Solution

There is an interface called `EmailSettings` (experimental), https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cognito.EmailSettings.html. We may be able to use this attribute to this interface.

One thing to note is that, according to the console UI, setting this value (Delivery through SES) to true requires From Email Address ARN (not just email address string). Hence, we will need a way to specify the from email address arn as well.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by duarten** [comment] 2020-04-13 02:19
As a workaround, I'm doing

```ts
;(this.pool.node.defaultChild as CfnUserPool).emailConfiguration = {
    from: ...,
    emailSendingAccount: "DEVELOPER",
    replyToEmailAddress: ...,
    sourceArn: ...,
}
```

**Comment by nija-at** [comment] 2020-04-14 08:36
@realharry - Thanks for filing this issue. This looks like a duplicate of https://github.com/aws/aws-cdk/issues/6768 and hence closing this in favour of the other one. 
Let us know if the feature is looking for is different or not covered by #6768.

**Closed by nija-at** 2020-04-14 08:36 UTC
Labels: feature-request, needs-triage, package/cognito, package/ses
