### ISSUE TITLE
[s3-deployment] new style synthesis toolkit can not deploy existing app(without "@aws-cdk/core:newStyleStackSynthesis": true) with s3-deployment resources

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cdk#9414] opened 2020-08-03 13:57 UTC
Following below guide of cdk pipeline to upgrade cdk-toolkit stack to support new style synthesis,

https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/

Deploying an application with `s3-deploy` failed on error without useful information.

```
Do you wish to deploy these changes (y/n)? y
S3DeploymentOnNewStyleAssetsStack: deploying...
[0%] start: Publishing 4184245adc1f2ed71e1f0ae5719f8fd7f34324b750f1bf06b2fb5cf1f4014f50:current
[50%] success: Published 4184245adc1f2ed71e1f0ae5719f8fd7f34324b750f1bf06b2fb5cf1f4014f50:current
[50%] start: Publishing 28787f136b08be19118211a54b6d35fc304edd6b8cd350ac678b0599dc2ba3ed:current
[100%] success: Published 28787f136b08be19118211a54b6d35fc304edd6b8cd350ac678b0599dc2ba3ed:current
S3DeploymentOnNewStyleAssetsStack: creating CloudFormation changeset...
9:50:25 PM | CREATE_FAILED        | Custom::CDKBucketDeployment | WorkerConfFileDepl...omResource426C58D0
Failed to create resource. Command '['python3', '/var/task/aws', 's3', 'cp', 's3://cdk-hnb659fds-assets-034068960621-cn-northwest-1/assets/287
87f136b08be19118211a54b6d35fc304edd6b8cd350ac678b0599dc2ba3ed.zip', '/tmp/tmpn4sybwmm/3ad9f6c2-d3e1-4f43-9d1c-625d1ec2fa1a']' returned non-zer
o exit status 1.

	new CustomResource (/Users/mengxinz/tmp/s3-deployment-on-new-style-assets/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
	\_ new BucketDeployment (/Users/mengxinz/tmp/s3-deployment-on-new-style-assets/node_modules/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.t
s:201:5)
```

### Reproduction Steps

1. Update `cdk.json` like below,
```json
"context": {
    "@aws-cdk/core:newStyleStackSynthesis": true,
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true"
  }
```
2. bootstrap CDKToolkit like below,
```
npx cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
```
3. Remove `newStyleStackSynthesis` property from cdk.json.
4. Deploying stack like below,
```ts
import * as cdk from '@aws-cdk/core';
import s3 = require('@aws-cdk/aws-s3');
import s3deploy = require('@aws-cdk/aws-s3-deployment');
import path = require('path');

export class S3DeploymentOnNewStyleAssetsStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const assetBucket = new s3.Bucket(this, 'TestBucket');

    const confPrefix = 'tunasync/worker/';
    const tmpOutput = path.join(__dirname, `./files`);
    const confFileDeployment = new s3deploy.BucketDeployment(this, 'WorkerConfFileDeployments', {
      sources: [s3deploy.Source.asset(tmpOutput)],
      destinationBucket: assetBucket,
      destinationKeyPrefix: confPrefix, // optional prefix in destination bucket
      prune: false,
      retainOnDelete: false,
    });
  }
}
```

**Workaround**:

Bootstrap a new cdk toolkit stack via option `--toolkit-stack-name toolkit-version-0`, then deploy above app via this toolkit stack.

### Environment

  - **CLI Version      :** 1.56.0
  - **Framework Version:**
  - **Node.js Version:** 
  - **OS               :**
  - **Language (Version):** 

### Other

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment] 2020-08-09 12:51
Hi @zxkane , you mentioned:

> Following below guide of cdk pipeline to upgrade cdk-toolkit stack to support new style synthesis,

What do you mean by **upgrade** the cdk-toolkit? Did you perform a new bootstrap?

Im unable to reproduce this, I followed the guide you mention to perform a **new** bootstrap and successfully deployed the `BucketDeployment` code you attached. 

Is this what you were doing?

**Comment by iliapolo** [comment] 2020-08-09 12:52
Possibly related to https://github.com/aws/aws-cdk/issues/9298

**Comment by zxkane** [comment] 2020-08-09 13:18
> Hi @zxkane , you mentioned:
> 
> > Following below guide of cdk pipeline to upgrade cdk-toolkit stack to support new style synthesis,
> 
> What do you mean by **upgrade** the cdk-toolkit? Did you perform a new bootstrap?
Yes. I ran new bootstrap to enable cdk-pipeline.
```
npx cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
```
I updated the issue with complete steps.
> 
> Im unable to reproduce this, I followed the guide you mention to perform a **new** bootstrap and successfully deployed the `BucketDeployment` code you attached.
> 
> Is this what you were doing?
Still seeing same error when deploying the stack to `ap-northeast-1` region via cdk 1.56.0. The issue originally was found when deploying to cn-northwest-1.

**Comment by zxkane** [comment] 2020-08-09 13:23
See sample project, https://github.com/zxkane/cdk-issue-9414

**Comment by iliapolo** [comment] 2020-08-09 17:23
@zxkane Prior to running the new bootstrap command, did you already have an old bootstrap stack deployed?

**Comment by zxkane** [comment] 2020-08-10 07:23
> @zxkane Prior to running the new bootstrap command, did you already have an old bootstrap stack deployed?

Yes, the cdk toolkit stack was upgraded to new boostrap version 3. It's not the root cause to cause the error.

> 
> Also, your `cdk.json` that you pasted here doesn't contain the `"@aws-cdk/core:newStyleStackSynthesis": true` key, is that intended?

Yes. I turned out the detail steps for reproducing it,

1. upgrade/create a cdk toolkit stack to version 3
1. create a cdk app including `s3-deployment` resource but does not have property `"@aws-cdk/core:newStyleStackSynthesis": true`. it's a common case for existing cdk apps.

**Comment by jonny-rimek** [comment] 2020-08-12 21:34
I'm running in the same problem: https://github.com/aws/aws-cdk/issues/9656

**Comment by iliapolo** [comment] 2020-08-18 15:30
Indeed, interacting with the new bootstrap bucket requires having `@aws-cdk/core:newStyleStackSynthesis: true` during stack synthesis. The details are explained here: https://github.com/aws/aws-cdk/issues/9607.

If you cannot redeploy your resources with the new style synthesis, you need to add the following permission to bucket deployment role:

```json
{
        Action: ['kms:Decrypt', 'kms:DescribeKey'],
        Effect: 'Allow',
        Resource: ['*'],
   }
```

Resolving in favor of https://github.com/aws/aws-cdk/issues/9607.

**Closed by iliapolo** 2020-08-18 15:30 UTC
Labels: bug, @aws-cdk/aws-s3-deployment
