### ISSUE TITLE
(aws-msk): CloudFormation error enabling open monitoring setting to MSK cluster

### ISSUE THREAD

**Issue by neovasili** [aws/aws-cdk#17505] opened 2021-11-15 13:25 UTC
### What is the problem?

When trying to add `openMonitoring` to an existing MSK cluster in an existing stack, CloudFormation applies the change to the cluster, but fails applying the change to the CloudFormation stack and rolls back the change in the stack, the resource keeps with the change.

### Reproduction Steps

Add `openMonitoring` configuration to an existing MSK cluster with the following:

```typescript
...
      openMonitoring: {
        prometheus: {
          jmxExporter: {
            enabledInBroker: true
          },
          nodeExporter: {
            enabledInBroker: true
          }
        }
      }
...
```

### What did you expect to happen?

Changes are applied to the resource and the CloudFormation stack without errors.

### What actually happened?

CloudFormation emits error after updating the MSK cluster configuration:

```shell
1:54:48 PM | UPDATE_FAILED        | AWS::MSK::Cluster   | MSKCluster
Amazon CloudFormation wasn't able to complete the request because of an issue with the server. Try again later.
```

Change is applied to the resource, but the stack it's rolled back, so any further try to apply any change to that stack always detect the previous change (the stack is drifted) is not applied and tries to apply it again.

### CDK CLI Version

1.129.0 (build fb43f89)

### Node.js Version

v16.3.0

### OS

MacOS

### Language

Typescript

### Language Version

Typescript 3.9.7

### Other information

MSK cluster is defined with L1 construct. Cluster Kafka version is `2.2.1`.

Also tried to:
- Add `enhancedMonitoring: _msk.ClusterMonitoringLevel.PER_TOPIC_PER_PARTITION` configuration with the same result
- Upgrading cdk version to latest (1.132.0) with the same result

Didn't try:
- Apply directly CloudFormation template

More info:
```shell
$ cdk diff my-stack

Stack my-stack
Resources
[~] AWS::MSK::Cluster MSKCluster MSKCluster
 ├─ [+] EnhancedMonitoring
 │   └─ PER_TOPIC_PER_PARTITION
 └─ [+] OpenMonitoring
     └─ {"Prometheus":{"JmxExporter":{"EnabledInBroker":true},"NodeExporter":{"EnabledInBroker":true}}}
```

```shell
$ cdk deploy my-stack

my-stack: deploying...
my-stack: creating CloudFormation changeset...
1:54:48 PM | UPDATE_FAILED        | AWS::MSK::Cluster   | MSKCluster
Amazon CloudFormation wasn't able to complete the request because of an issue with the server. Try again later.

	new MSKStack (/my-project-location/my-app/lib/msk.ts:63:24)
	\_ /my-project-location/my-app/bin/my-app.ts:45:3
	\_ Array.forEach (<anonymous>)
	\_ Object.<anonymous> (/my-project-location/my-app/bin/my-app.ts:21:6)
	\_ Module._compile (node:internal/modules/cjs/loader:1109:14)
	\_ Module.m._compile (/my-project-location/my-app/node_modules/ts-node/src/index.ts:1056:23)
	\_ Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
	\_ Object.require.extensions.<computed> [as .ts] (/my-project-location/my-app/node_modules/ts-node/src/index.ts:1059:12)
	\_ Module.load (node:internal/modules/cjs/loader:989:32)
	\_ Function.Module._load (node:internal/modules/cjs/loader:829:14)
	\_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
	\_ main (/my-project-location/my-app/node_modules/ts-node/src/bin.ts:198:14)
	\_ Object.<anonymous> (/my-project-location/my-app/node_modules/ts-node/src/bin.ts:288:3)
	\_ Module._compile (node:internal/modules/cjs/loader:1109:14)
	\_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
	\_ Module.load (node:internal/modules/cjs/loader:989:32)
	\_ Function.Module._load (node:internal/modules/cjs/loader:829:14)
	\_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
	\_ node:internal/main/run_main_module:17:47


 ❌  my-stack failed: Error: The stack named my-stack failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:352:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:189:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:225:9)
The stack named my-stack failed to deploy: UPDATE_ROLLBACK_COMPLETE
```

**Comment by peterwoodworth** [comment] 2021-11-15 21:42
I'm working right now on reproducing this. If I'm able to, I suspect this is going to be an issue with CloudFormation, so I'll create an internal ticket with that team.

**Comment by peterwoodworth** [comment] 2021-11-15 22:14
I wasn't able to reproduce this with a basic setup. First I deployed this:

```ts
    new CfnCluster(this, 'Cluster', {
      brokerNodeGroupInfo: {
        clientSubnets: [vpc.publicSubnets[0].subnetId, vpc.publicSubnets[1].subnetId],
        instanceType: 'kafka.m5.large'
      },
      clusterName: 'MyMskCluster',
      kafkaVersion: '2.2.1',
      numberOfBrokerNodes: 2
    });
```

and after that I deployed this succesfully 
```ts
    new CfnCluster(this, 'Cluster', {
      brokerNodeGroupInfo: {
        clientSubnets: [vpc.publicSubnets[0].subnetId, vpc.publicSubnets[1].subnetId],
        instanceType: 'kafka.m5.large'
      },
      clusterName: 'MyMskCluster',
      kafkaVersion: '2.2.1',
      numberOfBrokerNodes: 2,
      openMonitoring: {
        prometheus: {
          nodeExporter: {
            enabledInBroker: true
          },
          jmxExporter: {
            enabledInBroker: true
          }
        }
      }
    });
```

Are you consistently running into this issue?

**Comment by neovasili** [comment] 2021-11-16 07:13
Yes, I am, just tried again today to confirm and is throwing the same error. Don't know if it is relevant, but the cluster was created previously with raw CloudFormation (that's why I'm using L1 construct) on early February.

Also don't know if it will help, but here is the full definition of the cluster I have:

```typescript
    let clusterSubnets: string[] = [];

    vpc.privateSubnets.forEach(subnet => {
      clusterSubnets.push(subnet.subnetId);
    });

    const mskCluster = new _msk.CfnCluster(this, 'MSKCluster', {
      clusterName: Fn.sub('my-mskcluster-01'),
      kafkaVersion: '2.2.1',
      numberOfBrokerNodes: 3,
      configurationInfo: {
        arn: configArn.valueAsString,  // CFN parameter defined in CDK
        revision: configRev.valueAsNumber  // CFN parameter defined in CDK
      },
      encryptionInfo: {
        encryptionAtRest: {
          dataVolumeKmsKeyId: ""
        },
        encryptionInTransit: {
          clientBroker: "TLS",
          inCluster: true
        }
      },
      brokerNodeGroupInfo: {
        instanceType: 'kafka.t3.small',
        securityGroups: [defaultSg.securityGroupId],
        storageInfo: {
          ebsStorageInfo: {
            volumeSize: 20
          }
        },
        clientSubnets: clusterSubnets
      },
      loggingInfo: {
        brokerLogs: {
          cloudWatchLogs: {
            logGroup: mskLogGroup.logGroupName,
            enabled: true
          }
        }
      },
      enhancedMonitoring: _msk.ClusterMonitoringLevel.PER_TOPIC_PER_PARTITION,
      openMonitoring: {
        prometheus: {
          jmxExporter: {
            enabledInBroker: true
          },
          nodeExporter: {
            enabledInBroker: true
          }
        }
      }
    });
```

As I mentioned, if I comment the `openMonitoring` block, deployment is successful and both Resource and CFN template are updated (or keep as is), but if I try to deploy as is described here, after a few seconds I got:

```shell
8:01:50 AM | UPDATE_FAILED        | AWS::MSK::Cluster   | MSKCluster
Amazon CloudFormation wasn't able to complete the request because of an issue with the server. Try again later.
```

**Comment by peterwoodworth** [comment] 2021-11-16 21:06
The issue may be because you created this previously in CloudFormation. Have you read our [documentation](https://docs.aws.amazon.com/cdk/latest/guide/use_cfn_template.html) on properly transitioning to the CDK?

There's also a great guide [here](https://aws.amazon.com/blogs/developer/migrating-cloudformation-templates-to-the-aws-cloud-development-kit/) on migration written by a member of the team

**Comment by neovasili** [comment] 2021-11-19 17:04
Thanks for the info 😁

I want to make a PoC repeating the create from CFN and migrate to CDK using the "raw" method I used and using the one you mentioned to see if there is any difference in the behavior, will be back as soon as I can do it

**Comment by peterwoodworth** [comment] 2021-11-29 22:46
Feel free to ping me once you're back to this issue, closing for now

**Closed by peterwoodworth** 2021-11-29 22:46 UTC
Labels: guidance, @aws-cdk/aws-msk
