### ISSUE TITLE
metadata: exception when calling metadata

### ISSUE THREAD

**Issue by digitalsanctum** [aws/aws-cdk#1526] opened 2019-01-11 21:43 UTC
Calling the metadata command with latest version (0.22.0) results in an exception. 

Command executed: `cdk metadata lambda --profile ta`

results in the following (partial stacktrace):

```
/lambda/futz-sm/Resource:
  - type: aws:cdk:logicalId
    data: futzsmB920EF37
    trace:
      - new StateMachine
        (/tmp/jsii-kernel-m5UaXO/node_modules/@aws-cdk/aws-stepfunctions/lib/state-machine.js:26:26)
      - s._wrapSandboxCode
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:87042)
      - t.Kernel._wrapSandboxCode
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:95277)
      - t.Kernel._create
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:87021)
      - t.Kernel.create
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:82005)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78716)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - t.KernelHost.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79170)
      - t.KernelHost.run
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78405)
      - e.processRequest
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:78431)
      - i.then.e
        (/tmp/jsii-java-runtime13245880116113739307/jsii-runtime.js:1:79044)
      - <anonymous>
```

**Comment by rix0rrr** [comment] 2019-01-14 13:46
Looks like an infinite recursion. Could you share some of your code?

**Comment by rix0rrr** [comment] 2019-01-17 10:19
I'm confused about the error. At the top of your stack trace it says:

```
      - new StateMachine
        (/tmp/jsii-kernel-m5UaXO/node_modules/@aws-cdk/aws-stepfunctions/lib/state-machine.js:26:26)
```

But you don't seem to be using the step functions library in the code you posted. The identifier `futz-sm` does seem like you're creating a state machine?

Two notes on your CDK code itself:

* The `id` arguments you pass as the second argument to your constructs (`roleName` and `funcName`) have no bearing on the resources that get created. They're only to differentiate the in-memory objects. You can just call them `"Role"` and `"Function"`, or anything really. What controls the actual resource names is `.withRoleName()` and `.withFunctionName()` in the props argument.
* You don't need to explicitly pass a role to Function; a Role will be created automatically, and it will have `AWSLambdaBasicExecutionRole` by default. Unless you want to, of course.

**Comment by digitalsanctum** [comment] 2019-01-17 15:19
My bad, I think I had removed the step function in an effort to narrow the cause and forgot to put it back in. Here's the complete code:

```
package io.futz

import software.amazon.awscdk.App
import software.amazon.awscdk.Stack
import software.amazon.awscdk.StackProps
import software.amazon.awscdk.services.iam.Role
import software.amazon.awscdk.services.iam.RoleProps
import software.amazon.awscdk.services.iam.ServicePrincipal
import software.amazon.awscdk.services.lambda.Code
import software.amazon.awscdk.services.lambda.Function
import software.amazon.awscdk.services.lambda.FunctionProps
import software.amazon.awscdk.services.lambda.Runtime
import software.amazon.awscdk.services.stepfunctions.StateMachine
import software.amazon.awscdk.services.stepfunctions.StateMachineProps
import software.amazon.awscdk.services.stepfunctions.Task
import software.amazon.awscdk.services.stepfunctions.TaskProps
import java.util.*

class LambdaStack @JvmOverloads constructor(parent: App,
                                            name: String,
                                            localCodePath: String,
                                            props: StackProps? = null
) : Stack(parent, name, props) {
    init {

        val namespace = "futz"
        val roleName = "$namespace-role"
        val funcName = "$namespace-func"
        val stateMachineName = "$namespace-sm"
        val taskName = "$namespace-hello-task"

        val lambdaRole = Role(this, roleName, RoleProps.builder()
            .withAssumedBy(ServicePrincipal("lambda.amazonaws.com"))
            .withManagedPolicyArns(Arrays.asList("arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"))
            .build()
        )

        val code = Code.asset(localCodePath)

        val func = Function(this, funcName, FunctionProps.builder()
            .withFunctionName(funcName)
            .withCode(code)
            .withHandler("io.futz.MyFunction::handle")
            .withMemorySize(128)
            .withTimeout(5)
            .withRole(lambdaRole)
            .withRuntime(Runtime.JAVA8)
            .build()
        )

        val helloTask = Task(this, taskName, TaskProps.builder()
            .withResource(func)
            .build()
        )

        StateMachine(this, stateMachineName, StateMachineProps.builder()
            .withStateMachineName(stateMachineName)
            .withTimeoutSec(60)
            .withDefinition(helloTask)
            .build()
        )
    }
}
```

**Comment by rix0rrr** [comment] 2019-08-20 12:00
Can't reproduce this anymore with CDK 1.4.0 and the following code:

```java
package com.myorg;

import software.amazon.awscdk.core.Construct;
import software.amazon.awscdk.core.Duration;
import software.amazon.awscdk.core.Stack;
import software.amazon.awscdk.core.StackProps;
import software.amazon.awscdk.services.lambda.Code;
import software.amazon.awscdk.services.lambda.Function;
import software.amazon.awscdk.services.lambda.Runtime;
import software.amazon.awscdk.services.lambda.FunctionProps;
import software.amazon.awscdk.services.stepfunctions.StateMachine;
import software.amazon.awscdk.services.stepfunctions.StateMachineProps;
import software.amazon.awscdk.services.stepfunctions.Task;
import software.amazon.awscdk.services.stepfunctions.TaskProps;
import software.amazon.awscdk.services.stepfunctions.tasks.InvokeFunction;
import software.amazon.awscdk.services.iam.Role;
import software.amazon.awscdk.services.iam.RoleProps;
import software.amazon.awscdk.services.iam.ServicePrincipal;

public class HelloStack extends Stack {
    public HelloStack(final Construct parent, final String id) {
        this(parent, id, null);
    }

    public HelloStack(final Construct parent, final String id, final StackProps props) {
        super(parent, id, props);

        String roleName = "futz-role";
        String funcName = "futz-func";
        String stateMachineName = "futz-sm";
        String taskName = "futz-hello-task";

        Role lambdaRole = new Role(this, roleName, RoleProps.builder()
            .withAssumedBy(new ServicePrincipal("lambda.amazonaws.com"))
            .build()
        );

        Code code = Code.fromAsset("asset");

        Function func = new Function(this, funcName, FunctionProps.builder()
            .withFunctionName(funcName)
            .withCode(code)
            .withHandler("io.futz.MyFunction::handle")
            .withMemorySize(128)
            .withTimeout(Duration.seconds(5))
            .withRole(lambdaRole)
            .withRuntime(Runtime.JAVA_8)
            .build()
        );

        Task helloTask = new Task(this, taskName, TaskProps.builder()
            .withTask(new InvokeFunction(func))
            .build()
        );

        new StateMachine(this, stateMachineName, StateMachineProps.builder()
            .withStateMachineName(stateMachineName)
            .withTimeout(Duration.seconds(60))
            .withDefinition(helloTask)
            .build()
        );
    }
}
```

Closing for now. Please reopen if this issue still recurs.

**Closed by rix0rrr** 2019-08-20 12:00 UTC
Labels: bug, cli, needs-repro, service/stepfunctions
