### ISSUE TITLE
core: Custom::CrossRegionExportWriter fails with InvalidResourceId: UnknownError

### ISSUE THREAD

**Issue by JonWallsten** [aws/aws-cdk#26340] opened 2023-07-13 05:09 UTC
### Describe the bug

I'm using `crossRegionReferences` to use my Hosted Zone created in region `eu-west-1` for my Certificate created in `us-east-1` but the exported value is never created and fails with `InvalidResourceId: UnknownError` when I deploy. Downgrading to 2.69 fixes the issue.

### Expected Behavior

The deploy should work without any errors. The SSM parameter should be created.

### Current Behavior

The deploy fails with the following error:
```
Error processing event:  InvalidResourceId: UnknownError
    at deserializeAws_json1_1InvalidResourceIdResponse (/var/runtime/node_modules/@aws-sdk/client-ssm/dist-cjs/protocols/Aws_json1_1.js:7669:23)
    at deserializeAws_json1_1ListTagsForResourceCommandError (/var/runtime/node_modules/@aws-sdk/client-ssm/dist-cjs/protocols/Aws_json1_1.js:5473:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/runtime/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/runtime/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20
    at async StandardRetryStrategy.retry (/var/runtime/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async isInUse (/var/task/index.js:5:87)
    at async /var/task/index.js:3:932
    at async Promise.all (index 0) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'ff52df1c-c7bd-44cd-8c70-9ef10075ef40',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  __type: 'InvalidResourceId'
}
```

`CREATE failed, responding with a marker physical resource id so that the subsequent DELETE will be ignored`

Request:
```
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:eu-west-1:***:function:HostedZoneStack-CustomCrossRegionExportWriterCusto-oj2kKqRu7LRG",
    "ResponseURL": "...",
    "StackId": "arn:aws:cloudformation:eu-west-1:***:stack/HostedZoneStack/c980a370-20be-11ee-b44d-0a884cc475df",
    "RequestId": "ae7984ed-4a67-4ed4-b3df-6c60d1d23889",
    "LogicalResourceId": "ExportsWriteruseast10F67B507DDE2E818",
    "ResourceType": "Custom::CrossRegionExportWriter",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:eu-west-1:***:function:HostedZoneStack-CustomCrossRegionExportWriterCusto-oj2kKqRu7LRG",
        "WriterProps": {
            "exports": {
                "/cdk/exports/CertificateWAF2Stack/HostedZoneStackeuwest1RefHoztedZoneStackHostedZone662869C91D9E1585": "Z0515350ARL1Q47HQ75Z"
            },
            "region": "us-east-1"
        }
    }
}
```

### Reproduction Steps

```typescript
const hostedZoneStack = new HoztedZoneStack(app, 'HostedZoneStack', {
    zoneName: AWS_DOMAIN,
    env: AWS_ENV,
    crossRegionReferences: true
});

const certificateStack = new CertificateWaf2Stack(app, 'CertificateWAF2Stack', {
    domainName: AWS_DOMAIN,
    hostedZone: hostedZoneStack.hostedZone,
    aclName: ACL_NAME,
    wafScope: WAF_SCOPE,
    env: AWS_ENV_GLOBAL,
    crossRegionReferences: true
});

```

```typescript
import { Stack, StackProps, Tags } from 'aws-cdk-lib';
import { HostedZone } from 'aws-cdk-lib/aws-route53';
import { Construct } from 'constructs';

type Props = StackProps & {
    zoneName: string;
};

export class HoztedZoneStack extends Stack {
    public readonly hostedZone: HostedZone;

    constructor(scope: Construct, id: string, props: Props) {
        super(scope, id, props);

        this.hostedZone = new HostedZone(this, 'HoztedZoneStackHostedZone', {
            zoneName: props.zoneName
        });

        // Add tags
        Tags.of(this.hostedZone).add('Name', props.zoneName);
    }
}
```

### CDK CLI Version

2.87.0

### Node.js Version

18.14.1

### OS

Windows 10 x64

### Language

Typescript

### Language Version

5.1.6

**Comment by MichielVanDerWinden-inQdo** [comment] 2023-07-13 14:24
Same issue here, entirely not related to Route53 or ACM/WAF/Whatever CertificateWaf2Stack contains. Ran into it when trying to deploy a VPC that is set to `crossRegionReferences: true`.

Using the stack as follows:

```
const vpcStack = new VpcStack(stack, "VpcStack", {
    env,
    stage,
    projectName,
    crossRegionReferences: true
});
```

Contents of stack:
```
constructor(scope: Stack, id: string, props: ICustomProps) {
    super(scope, `${id}-${props.stage}-${props.projectName}`, props);
    const { stage, projectName } = props;
    Tags.of(this).add("stage", stage);

    this.vpc = new ec2.Vpc(this, "Vpc", {
      maxAzs: 2,
      vpcName: "vpc-test",
      natGateways: 1,
      ipAddresses: ec2.IpAddresses.cidr("10.0.0.0/16"),
      enableDnsHostnames: true,
      enableDnsSupport: true,
      subnetConfiguration: [
        {
          cidrMask: 20,
          name: "Public",
          subnetType: ec2.SubnetType.PUBLIC
        },
        {
          cidrMask: 20,
          name:  "Private",
          subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS
        },
        {
          cidrMask: 20,
          name: "Data",
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED
        }
      ],
    });
    
// Some interface endpoints here as well, mostly to do with ECS and SSM

```

Error was exactly the same:
`Error processing event:  InvalidResourceId: UnknownError`
without any other information to pinpoint the issue.

**Comment by JonWallsten** [comment] 2023-07-13 14:29
@pahud: The error is from `HostedZoneStack`, it's trying to create a value FOR the `CertificateWaf2Stack` if I understand the flow correctly. I could probably replace `CertificateWaf2Stack` with any other stack that uses the `hostedZoneStack.hostedZone` as an import. The error is generated even if I only deploy the `HostedZoneStack`.
Can I provide you with any other information?

**Comment by pahud** [comment] 2023-07-13 19:33
Making this a p1 bug. The maintainer is investigating now.

**Comment by pahud** [comment] 2023-07-14 16:20
This is weird. Looks like this this issue can't be reproduced in some cases but the deployment always fails in my environment.

https://github.com/aws/aws-cdk/issues/26340#issuecomment-1634406132

**Comment by guywilsonjr** [comment] 2023-07-15 19:31
I can verify I'm seeing this issue as well. I can't create any cross region referencing stacks

**Comment by thomasedw** [comment] 2023-07-16 19:29
This may have been introduced in 2.87.0, downgrading to 2.86.0 fixed the issue for me.

**Comment by SamuraiPrinciple** [comment] 2023-07-16 20:34
Could it be related to the switch to NodeJS 18 for all custom resources?

**Comment by leevi978** [comment] 2023-07-17 12:53
I am also seeing this issue. Downgrading to 2.86.0 seemed to fix it for me

**Comment by iliapolo** [comment] 2023-07-17 14:10
> Could it be related to the switch to NodeJS 18 for all custom resources?

Yes. Some of the handler code hasn't been appropriately updated to accommodate `aws-sdk-v3`

**Comment by mrgrain** [comment] 2023-07-20 09:59
Closed by https://github.com/aws/aws-cdk/pull/26434

**Closed by mrgrain** 2023-07-20 09:59 UTC
Labels: bug, p1, investigating, @aws-cdk/aws-route53, effort/medium, needs-review
