### ISSUE TITLE
Upgrading to v1.19.0 causes errors with EIP tag update

### ISSUE THREAD

**Issue by idm-ryou** [aws/aws-cdk#5469] opened 2019-12-18 02:38 UTC
After upgraded to CDK v1.19.0, updating existing EIP for adding auto-generated Tag causes an error at CloudFormation 

### Reproduction Steps

1. Deploy stack with Vpc construct with CDK earlier v1.19.0
1. Upgrade to CDK v1.19.0 and deploy

### Error Log

```console
$ cdk deploy NetworkStackEnvStg

NetworkStackEnvStg 
NetworkStackEnvStg: deploying... 
NetworkStackEnvStg: creating CloudFormation changeset... 
 0/6 | 2:07:22 AM | UPDATE_IN_PROGRESS   | AWS::EC2::EIP                         | Vpc/PublicSubnet1/EIP (VpcPublicSubnet1EIPD7E02669)  
 1/6 | 2:07:24 AM | UPDATE_FAILED        | AWS::EC2::EIP                         | Vpc/PublicSubnet1/EIP (VpcPublicSubnet1EIPD7E02669) API: ec2:disassociateAddress You do not have permission to access the specified resource. 
    PublicSubnet.addNatGateway (/codebuild/output/src566679633/src/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1538:21) 
    \_ NatGateway.configureNat (/codebuild/output/src566679633/src/node_modules/@aws-cdk/aws-ec2/lib/nat.ts:145:27) 
    \_ Vpc.createNatGateways (/codebuild/output/src566679633/src/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1129:14) 
    \_ new Vpc (/codebuild/output/src566679633/src/node_modules/@aws-cdk/aws-ec2/lib/vpc.ts:1044:14) 
    \_ new NetworkStack (/codebuild/output/src566679633/src/src/network-stack.ts:20:16) 
    \_ newStack (/codebuild/output/src566679633/src/src/app.ts:52:28) 
    \_ Records.mapValues (/codebuild/output/src566679633/src/src/lib.ts:62:5) 
    \_ result.toEntries.map (/codebuild/output/src566679633/src/src/lib.ts:44:31) 
    \_ Array.map (<anonymous>) 
    \_ Function.mapValues (/codebuild/output/src566679633/src/src/lib.ts:43:43) 
    \_ Object.newStackGroup (/codebuild/output/src566679633/src/src/lib.ts:61:18) 
    \_ Object.<anonymous> (/codebuild/output/src566679633/src/src/app.ts:49:27) 
    \_ Module._compile (internal/modules/cjs/loader.js:778:30) 
    \_ Module.m._compile (/codebuild/output/src566679633/src/node_modules/ts-node/src/index.ts:536:23) 
    \_ Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
    \_ Object.require.extensions.(anonymous function) [as .ts] (/codebuild/output/src566679633/src/node_modules/ts-node/src/index.ts:539:12) 
    \_ Module.load (internal/modules/cjs/loader.js:653:32) 
    \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
    \_ Function.Module._load (internal/modules/cjs/loader.js:585:3) 
    \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12) 
    \_ main (/codebuild/output/src566679633/src/node_modules/ts-node/src/bin.ts:212:14) 
    \_ Object.<anonymous> (/codebuild/output/src566679633/src/node_modules/ts-node/src/bin.ts:470:3) 
    \_ Module._compile (internal/modules/cjs/loader.js:778:30) 
    \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) 
    \_ Module.load (internal/modules/cjs/loader.js:653:32) 
    \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
    \_ Function.Module._load (internal/modules/cjs/loader.js:585:3) 
    \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12) 
    \_ startup (internal/bootstrap/node.js:283:19) 
    \_ bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) 
 1/6 | 2:07:25 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack            | NetworkStackEnvStg The following resource(s) failed to update: [VpcPublicSubnet1EIPD7E02669].  
 1/6 | 2:07:57 AM | UPDATE_IN_PROGRESS   | AWS::EC2::EIP                         | Vpc/PublicSubnet1/EIP (VpcPublicSubnet1EIPD7E02669)  
 
 ❌  NetworkStackEnvStg failed: Error: The stack named NetworkStackEnvStg is in a failed state: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [VpcPublicSubnet1EIPD7E02669]. ) 
The stack named NetworkStackEnvStg is in a failed state: UPDATE_ROLLBACK_FAILED (The following resource(s) failed to update: [VpcPublicSubnet1EIPD7E02669]. ) 
error Command failed with exit code 1. 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```

### Environment

  - **CLI Version      :** 1.19.0 (build 5597bbe) 
  - **Framework Version:** 1.19.0
  - **OS               :** Linux(on a CodeBuild project environment)
  - **Language         :** TypeScript

### Other

```console
$ cdk diff NetworkStackEnvStg

Stack NetworkStackEnvStg 
Resources 
[~] AWS::EC2::EIP Vpc/PublicSubnet1/EIP VpcPublicSubnet1EIPD7E02669  
 └─ [+] Tags 
     └─ [{"Key":"Name","Value":"NetworkStackEnvStg/Vpc/PublicSubnet1"}] 
```

Related: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/84#issuecomment-559187499

--- 

This is :bug: Bug Report

**Comment by idm-ryou** [comment] 2019-12-18 03:06
Workaround: 

```typescript
cdk.Tag.remove(this.vpc, "Name", {
  includeResourceTypes: ["AWS::EC2::EIP"]
});
```

**Comment by danlyg** [comment] 2019-12-18 04:37
I am having the same issue. After this upgrade, my VPC subnets are adding a new tag to each subnet. I am having the: 
`API: ec2:disassociateAddress You do not have permission to access the specified resource.` 

The rollback then proceeds to fail as each subnet fails to update.

**Comment by crucialfelix** [comment] 2019-12-18 13:19
"UPDATE_ROLLBACK_FAILED state and can not be updated"  I had to initiate "Continue update rollback" from the console.  I had to skip changing those resources.

So now they are out of sync.

I still get the same `API: ec2:disassociateAddress` error on subsequent changes. So I will return to 1.18.0 for now

**Comment by gbooth27** [comment] 2019-12-18 20:17
I am also seeing this bug after upgrading to `1.19.0`

**Comment by crucialfelix** [comment] 2019-12-18 22:13
I did get it to deploy still using 1.19.0 actually.  

You also have to remove any other tags that might be assigned by parent constructs. In my case I had `source: cdk` and `stage: staging` so I now have code to remove all tags from EIP:

```
cdk.Tag.remove(this.vpc, "Name", {
  includeResourceTypes: ["AWS::EC2::EIP"]
});

cdk.Tag.remove(this.vpc, "source", {
  includeResourceTypes: ["AWS::EC2::EIP"]
});

cdk.Tag.remove(this.vpc, "stage", {
  includeResourceTypes: ["AWS::EC2::EIP"]
});

```

**Comment by idm-ryou** [comment] 2019-12-19 00:34
Related Issue:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/309

**Comment by mark-schaal** [comment] 2019-12-26 22:45
I am also seeing this bug after upgrading to 1.19.0.

**Comment by nathanpeck** [comment] 2020-01-06 17:44
@rix0rrr I also encountered this bug. I ended up just wiping my stack and recreating with 1.19.0

**Comment by lkoniecz** [comment] 2020-01-21 13:59
@rix0rrr 
Any ETA on this?

thanks

**Comment by njlynch** [comment] 2021-07-05 17:27
From the associated issues, it looks like this was resolved by CloudFormation on Mar 6 2020 (15 months ago!).

I also just attempted to recreate it by creating a new CDK project on 1.18.0, adding a VPC (with EIP), then upgrading the project to 1.19.0 and deploying again. The diff showed the Tags being added, and the deployment succeeded as expected.

Based on the above, I believe this can be closed. I'm going to mark as "Closing Soon" and give folks a few days to comment if they're still impacted. If you're still being bit by this, please comment (ideally with a reproducible example) so we can continue troubleshooting.

**Comment by peterwoodworth** [comment] 2021-07-08 00:23
Closing because the bot isn't working, please ping me if anyone is still impacted by this issue

-Peter

**Closed by peterwoodworth** 2021-07-08 00:23 UTC
Labels: @aws-cdk/aws-ec2, bug, closing-soon, effort/medium, p1
