### ISSUE TITLE
swagger support for RestApi

### ISSUE THREAD

**Issue by vertti** [aws/aws-cdk#5391] opened 2019-12-12 11:17 UTC
I'd like to attach our API's Swagger documentation (swagger.json) to the Api Gateway rest api. Apparently you can do it simply by including a `Body` field to the rest api `Properties` but it seems this is not supported by CDK?

### Use Case

We took the base swagger json generated by API Gateway and improved it by adding documentation to it. Now I'd like to include it to the Cloudformation so it's available for browsing in the API Gateway Documenatiion page in the AWS Console.

### Proposed Solution

[Here](https://sookocheff.com/post/api/deploying-swagger-to-api-gateway/) is blog post showing how you can add the swagger doc directly under the `Body` like:

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PlayersAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Player API
      Description: A demo API for Player management
      Body: # Swagger Specification body goes here
```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by vertti** [comment] 2019-12-16 07:34
Currently you can attach the custom json with the following:

```
import openapiJson = require('./resources/openapi.json')

..
const cfnRestApi = api.node.defaultChild as CfnRestApi
cfnRestApi.body = openapiJson
```
where `api` is an instance of `LambdaRestApi`.

**Comment by nija-at** [comment] 2020-02-05 15:39
If I understand correctly, uploading the swagger.json or swagger.yaml file into the `Body` or the `BodyS3Location` property would also modify the Rest API methods and resources, and not only  documentation.

**Comment by nija-at** [comment] 2020-02-13 14:15
This is a duplicate of https://github.com/aws/aws-cdk/issues/1461.

Apologies for the churn, but it would be useful to move your 👍 reactions and any additional comments to the other issue.

**Closed** 2020-02-13 14:15 UTC
Labels: effort/large, feature-request, package/apigateway
