### ISSUE TITLE
[s3] Add replication configuration to existing S3 bucket

### ISSUE THREAD

**Issue by SZubarev** [aws/aws-cdk#10348] opened 2020-09-14 19:56 UTC
### The Question
I'm trying to assign replication configuration to existing S3 bucket using the code:
```
const cfnBucket = bucket.node.defaultChild as s3.CfnBucket;

    cfnBucket.replicationConfiguration = {
      role: replicationRole.roleName,
      rules:[
        {
          destination:{
            bucket: bucket.bucketName
          },
          prefix: "target_prefix",
          status: "Enabled",
          filter: {
            prefix: "source_prefix"
          }
        }
      ]
    }
```
Getting error at cdk synth:
Cannot set property 'replicationConfiguration' of undefined

If I create bucket from the CDK code - template synth is working fine.

Is there any workaround to do the trick?

### Environment

  - **CDK CLI Version:** 1.63.0 (build 7a68125)
  - **Module Version:** 
  - **Node.js Version:** v14.8.0
  - **OS:** OSX 10.14.6
  - **Language (Version):** TypeScript

**Comment by iliapolo** [comment] 2020-09-15 10:49
@SZubarev I am not able to reproduce the issue...here is the code i'm using:

```typescript
// The code that defines your stack goes here
const bucket = new s3.Bucket(this, 'Bucket');

const cfnBucket = bucket.node.defaultChild as s3.CfnBucket;

cfnBucket.replicationConfiguration = {
  role: 'myrole',
  rules:[
    {
      destination:{
        bucket: bucket.bucketName
      },
      prefix: "target_prefix",
      status: "Enabled",
      filter: {
        prefix: "source_prefix"
      }
    }
  ]
}
```

And this produced the following config:

```json
"Bucket83908E77": {
  "Type": "AWS::S3::Bucket",
  "Properties": {
    "ReplicationConfiguration": {
      "Role": "myrole",
      "Rules": [
        {
          "Destination": {
            "Bucket": {
              "Ref": "Bucket83908E77"
            }
          },
          "Filter": {
            "Prefix": "source_prefix"
          },
          "Prefix": "target_prefix",
          "Status": "Enabled"
        }
      ]
    }
  },
```

Can you maybe share the code you use to create the `bucket`? and the exact version of framework you are using?

Also note that you use `bucket.bucketName` inside the replication configuration of the same bucket. It shouldn't cause synth time problems but will fail at deploy time. 

Thanks

**Comment by SZubarev** [comment] 2020-09-15 12:01
I'm having problem when using imported bucket that already exists:
`const bucket = s3.Bucket.fromBucketName(this,"bucket", "existing-bucket-name")`

**Comment by iliapolo** [comment] 2020-09-15 12:08
@SZubarev I see, you cannot use escape hatches on imported resources because those resources are not created by your CDK app, and hence its CloudFormation configuration cannot be changed by it.

**Comment by SZubarev** [comment] 2020-09-15 12:16
Is there any way to setup replication configuration in CDK? Or just deploy it using a separate CFN?

**Comment by iliapolo** [comment] 2020-09-15 12:35
@SZubarev You can set it up just like you did, but not on an imported bucket. That is, if you create your bucket inside the same cdk app:

```typescript
const bucket = new s3.Bucket(this, 'Bucket)
```

Then you use the escape hatch just like you did.

If you need to setup replication configuration on an already existing bucket, you'd need to use the [`AwsCustomResource`](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#custom-resources-for-aws-apis) and invoke the appropriate API call using the AWS JavaScript SDK. 

A separate CFN template will also not help because you won't be able to include an existing bucket into a CFN template (this is also why CDK doesn't support it).

**Comment by SomayaB** [comment] 2020-09-30 01:19
Closing this issue since it seems to be resolved. Feel free to reopen.

**Closed by SomayaB** 2020-09-30 01:19 UTC
Labels: @aws-cdk/aws-s3, guidance

**Comment by manmartgarc** [comment] 2024-02-06 01:34
I am still having this issue. Has the issue been marked as closed won't fix or closed it has been fixed?

**Comment by evgenyka** [comment] 2024-02-06 09:09
> I am still having this issue. Has the issue been marked as closed won't fix or closed it has been fixed?
Closed won't fix. If you need to set up replication configuration on an existing bucket, you'd need to use the [AwsCustomResource](https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#custom-resources-for-aws-apis) and invoke the appropriate API call using the AWS JavaScript SDK.
