### ISSUE TITLE
(aws-ecs): Update service with a new task definition

### ISSUE THREAD

**Issue by revanthalampally** [aws/aws-cdk#15299] opened 2021-06-24 19:24 UTC
### Environment

  - **CDK CLI Version:< 1.95.1 (build ed2bbe6)>
  - **aws-ecs: <1.97.0>

**Comment by peterwoodworth** [comment] 2021-06-24 20:19
seems like a duplicate of the other one you posted

**Closed by peterwoodworth** 2021-06-24 20:19 UTC
Labels: @aws-cdk/aws-ecs, guidance
