### ISSUE TITLE
(pipelines): logging retention asset bugs on create and delete

### ISSUE THREAD

**Issue by Andrapyre** [aws/aws-cdk#15326] opened 2021-06-28 06:22 UTC
### Reproduction Steps

I can deploy a pipeline with the code below with no problems (you'll need to change the bitbucket connection info if you try to run this).

repo: https://github.com/Andrapyre/aws-cdk-problem/tree/main/pipelines-logging
lambda stack: https://github.com/Andrapyre/aws-cdk-problem/blob/main/pipelines-logging/infrastructure/lambda-stack.ts

But when I add logRetention to the lambda stack like so, there are problems.

```
import { Stack, Construct, StackProps, Duration } from "@aws-cdk/core"
import { NodejsFunction } from "@aws-cdk/aws-lambda-nodejs"
import path from "path"

export class ServiceStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    new NodejsFunction(this, "trial", {
      entry: path.join(__dirname, "..", "index.ts"),
      timeout: Duration.seconds(30),
      logRetention: 7,
    })
  }
}
```

Pipelines will deploy the first asset (the lambda), but not the second asset (another lambda to manage the log retention). When retrying deploy, it will deploy the second asset but not the first. When manually retrying just the asset creation step, it will then succeed in deploying both assets. From then on, everything is ok, until logRetention is removed from the lambda, upon which, the pipeline self-update step will fail with the following message:

`arn:aws:sts::{ACCOUNT NUMBER}:assumed-role/TrialPipeline-TrialPipelineUpdatePipel-YMLVZZYHR9J0/AWSCodeBuild-2d27283f-aa07-4074-813a-954637ad3dcd is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-west-2:{ACCOUNT NUMBER}:parameter/cdk-bootstrap/hnb659fds/version`

### What did you expect to happen?

I expected to be able to add and deploy logRetention with no issues and delete and deploy logRetention with no issues.

### What actually happened?

The pipeline role was never updated with sufficient permissions when log retention was created. It looks like the pipeline can't update bootstrapped resources (in this case the permission set of a bootstrapped role) automatically.

### Solution
Add the following to the {StackName}UpdatePipelineSelfMutationRoleDefaultPolicy when the role and policy are bootstrapped.
```
{
            "Action": "ssm:GetParameter",
            "Resource": "arn:aws:ssm:*:{INSERT ACCOUNT_NAME}:parameter/cdk-bootstrap/*",
            "Effect": "Allow"
},
```

### Environment

  - **CDK CLI Version  :** 1.110.0
  - **Node.js Version:** 14.16.0
  - **OS               :** Ubuntu 20
  - **Language (Version):** 4.3.2

This is :bug: Bug Report

**Comment by rix0rrr** [comment] 2021-06-28 11:48
Interesting. In actual fact, it shouldn't be trying to read that parameter using the self mutation role at all, it should be assuming a deploy role first.

Can you share the full log of that CodeBuild job when it's erroring?

**Comment by Andrapyre** [comment] 2021-06-28 17:47
@rix0rrr , see the full log here: https://github.com/Andrapyre/aws-cdk-problem/blob/main/pipelines-logging/mainError.log

**Comment by rix0rrr** [comment] 2021-07-05 11:56
The error log you posted seems to be different from the bug you initially reported at the top of this thread.

Can you reproduce the initial report?  If not, I guess we will close this issue.

**Closed** 2021-09-29 15:25 UTC
Labels: bug, @aws-cdk/pipelines
