### ISSUE TITLE
(aws_cdk.core): Allow intrinsics in CustomResource and CfnCustomResource parameter service_token

### ISSUE THREAD

**Issue by ddl-denis-parnovskiy** [aws/aws-cdk#15437] opened 2021-07-06 18:01 UTC
Allow code like this:

```
function = CfnFunction(...)
resource = CfnCustomResource(... service_token=function.get_att('Arn'))
```

Currently CDK only accepts string for both:
```
jsii.errors.JSIIError: Expected a string, got {"$jsii.byref":"@aws-cdk/core.Intrinsic@10092"}
```

### Use Case

When deploying lambda along with the stack, Arn of the lambda is not known and we need a function like `Fn::GetAtt` to get Arn.

No, we do not want to use the middleman Provider class because we do not need any of the functionalities there and do not want additional 5 resources.

### Proposed Solution

Expand intrinsic references in service_token field.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by rix0rrr** [comment] 2021-07-07 08:56
Looks like a jsii issue. That field should have accepted `string | IResolvable`, which is covered by `fn_getatt`.

In the mean time, you can use `Token.to_string(function.get_att('Arn'))` to force the `IResolvable` to a string.

**Comment by NGL321** [comment] 2021-07-24 03:12
@RomainMuller should this issue get transferred over to the JSII repo, or should a parallel issue get opened there?

**Comment by RomainMuller** [comment] 2021-09-15 12:03
According to [the documentation](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudformation.CfnCustomResourceProps.html), `CfnCustomResourceProps.service_token`is typed as `string`, and not `string | IResolvable`.

What @rix0rrr suggested as a workaround is actually how it needs to be done, even in TypeScript. There is no jsii issue, as the API behaves exactly as designed.

**Closed by RomainMuller** 2021-09-15 12:03 UTC
Labels: p2, @aws-cdk/core, language/python, feature-request, jsii
