### ISSUE TITLE
TokenAuthorizer (api-gateway): TokenAuthorizer doesn't update when handler changes

### ISSUE THREAD

**Issue by LarsPede** [aws/aws-cdk#22808] opened 2022-11-07 10:15 UTC
### Describe the bug

TokenAuthorizer doesn't update the lambda handler connection when the handler dependency changes "location". This is both if you add a new name to a current TokenAuthorizer lambda or if you simply add an alias to the function.

The authorization then starts failing with a 500 server error with the response: { message: null } and the API gateway logs say: "Execution failed due to configuration error: Invalid permissions on Lambda function".

### Expected Behavior

TokenAuthorizer updates when the handler changes version.

### Current Behavior

TokenAuthorizer doesn't update when handler changes version.

### Reproduction Steps

deploy the following:

```
const apiGateway: ApiGateway;
const IntegrationLambda: NodeJSLambda;
const authLambda: new NodeJSLambda(this, 'auth-lambda');
const authorizer = new TokenAuthorizer(this, 'authorizer', {
	handler: authLambda,
	resultsCacheTtl: Duration.seconds(0),
});
apiGateway.root
  .addResource('{proxy+}')
  .addMethod('ANY', new LambdaIntegration(integrationLambda, {
    timeout: Duration.seconds(10)
  }),
  {
    authorizer,
  }
);
```

Then deploy the following on top of it:

```
const apiGateway: ApiGateway;
const IntegrationLambda: NodeJSLambda;
const authLambda: new NodeJSLambda(this, 'auth-lambda-v2');
const authorizer = new TokenAuthorizer(this, 'authorizer', {
	handler: authLambda,
	resultsCacheTtl: Duration.seconds(0),
});
apiGateway.root
  .addResource('{proxy+}')
  .addMethod('ANY', new LambdaIntegration(integrationLambda, {
    timeout: Duration.seconds(10)
  }),
  {
    authorizer,
  }
);
```

You should now start seeing 500 errors when contacting the API Gateway

### Possible Solution

The easy fix for now is changing the id of the TokenAuthorizer together with the lambda.

```
const apiGateway: ApiGateway;
const IntegrationLambda: NodeJSLambda;
const authLambda: new NodeJSLambda(this, 'auth-lambda');
const authorizer = new TokenAuthorizer(this, `authorizer-v${authLambda.currentVersion}`, {
	handler: authLambda,
	resultsCacheTtl: Duration.seconds(0),
});
apiGateway.root
  .addResource('{proxy+}')
  .addMethod('ANY', new LambdaIntegration(integrationLambda, {
    timeout: Duration.seconds(10)
  }),
  {
    authorizer,
  }
);
```

So my best guess on a reason and fix is that the TokenAuthorizer is missing a dependency on the handler. It seems like it doesn't update its connection to the Authorizer lambda in case it gets moved to a different arn.

### Additional Information/Context

There is no issue when running `synth`

As I said - quick fix is changing the TokenAuthorizer id.

This also happened when we created an alias to the function.

### CDK CLI Version

2.45.0

### Node.js Version

16.15.1

### OS

macOS Monterey

### Language

Typescript

### Language Version

Typescript (4.7.4)

**Comment by peterwoodworth** [comment] 2022-12-05 23:31
Thanks for the bug report @LarsPede, and thanks for the contribution @cecheta, we'll take a look at it when we can 🙂 

Just to be clear @LarsPede, by "deploy the following on top of it", you mean to replace the code from before? Or add the code to the same stack. I assume the former, and that would make sense, I just want to make sure I'm understanding the issue correctly 🙂

**Comment by comcalvi** [comment] 2022-12-13 18:58
@LarsPede where did you import the `NodeJSLambda` from? I'm struggling to find it.

**Comment by marshmellow1328** [comment] 2022-12-21 21:16
This appears to be a duplicate of #16554. Any chance of it getting fixed in 2023?

**Comment by peterwoodworth** [comment] 2022-12-21 21:55
You're right @marshmellow1328, that issue #16554 seems to be the same. I'm going to close this issue out in favor of the original due to the original having more complete reproduction steps and already having upvotes. 

We may fix this issue with enough support to show that this is an important issue, but I think it would be more likely to get fixed sooner if a contributor were to help us out 🙂

**Closed by peterwoodworth** 2022-12-21 21:55 UTC
Labels: bug, p2, @aws-cdk/aws-apigateway, effort/small

**Comment by LarsPede** [comment] 2022-12-22 11:31
@peterwoodworth and @comcalvi sorry for not responding - Christmas vacation and all... happy to see that it's getting investigated and good catch with the duplicate - I had not seen that one :)
