### ISSUE TITLE
Regression 1.27 -> 1.31: construct does not have an associated node..

### ISSUE THREAD

**Issue by sblackstone** [aws/aws-cdk#7234] opened 2020-04-07 16:34 UTC
This code is defined in my initial stack 

```
    this.zone = route53.HostedZone.fromLookup(this, 'Zone', {
      domainName: this.props.zoneName
    });
```

It works fine in CDK 1.27 but now after upgrading to 1.31 ( and hence the new constructs library), I'm getting:

```
 throw new Error(`construct does not have an associated node. All constructs must extend the "Construct" base class`);
```

**Comment by MrArnoldPalmer** [comment] 2020-04-07 18:49
@sblackstone just using `fromLookup` doesn't trigger this error for me. Are you passing this construct to others as a prop?

Is it possible to post your complete code or a minimal reproduction for us to check out?

This looks to be the same as https://github.com/aws/aws-cdk/issues/6885, though we thought that was the only place performing this casting from `IConstruct` to `Construct`. You can see there is a workaround there that may be able to get you around the issue while we figure this out.

**Comment by sblackstone** [comment] 2020-04-07 20:23
I tried this from #6885, no dice...

```
    Object.defineProperty(this.zone, Symbol.for('constructs.Construct.node'), {
        value: this.zone.node._actualNode
    });
```

**Comment by MrArnoldPalmer** [comment] 2020-04-07 22:47
@sblackstone need some more details to help debug here. Are you passing the imported hosted zone to other constructs?

**Comment by SomayaB** [comment] 2020-04-23 06:23
Closing for now since there hasn't been a response in a while. Feel free to reopen.

**Closed by SomayaB** 2020-04-23 06:23 UTC
Labels: @aws-cdk/aws-route53, bug, closing-soon
